### ISSUE TITLE
Changing ListView to CollectionView gives an "invalid cast" exception deep in Xamarin.Android

### ISSUE THREAD

**Issue by rbrian** [dotnet/maui#7382]
### Description

I'm working on a Maui app using FreshMvvv.Maui. I have a page with a ListView that I want to convert to a CollectionView in order 
to use reordering. After changing the xaml, I get an InvalidCastException deep in Xamarin.Android: 

```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x14 in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x20 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:166,26	C#
 	0x2F in Microsoft.Maui.Controls.Handlers.Items.TemplatedItemViewHolder.Bind at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\TemplatedItemViewHolder.cs:60,5	C#
 	0x17 in Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.BindTemplatedItemViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\ItemsViewAdapter.cs:132,4	C#
 	0x3B in Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter<Microsoft.Maui.Controls.ReorderableItemsView,Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource>.BindTemplatedItemViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\StructuredItemsViewAdapter.cs:104,5	C#
```

Happens in 2 different forms with different models/pagemodels. In both cases, the ItemsSource is bound to an ObservableCollection<>. 

[ProtocolTracker.zip](https://github.com/dotnet/maui/files/8743745/ProtocolTracker.zip)

### Steps to Reproduce

1. Load the attached project file
2. Run (i'm using an android emulator, "tablet", api 30)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30

**Comment by VincentBu** [comment]
repro with vs main build(32522.39.main)

**Comment by jsuarezruiz** [comment]
Remove the TextCell and include directly a Label. That must fix the exception.

**Comment by rbrian** [comment]
While changing the TextCell to a Label does work, it's not particularly useful unless I want to completely duplicate the TextCell functionality. I'd much rather see the original issue (which was marked as verified) fixed.

**Comment by rmarinho** [comment]
TextCell and othe types of "Cell" are to be used with ListView and not CollectionView. So using a Label is the correct answer for this issue.
