### ISSUE TITLE
Databinding FontImageSource.Glyph doesn't update 

### ISSUE THREAD

**Issue by rbrian** [dotnet/maui#7383]
### Description

When trying to update a button's glyph with databinding, the glyph is set properly when the page is initially created. However, further changes to the bound property do not update the button. 

Works in Windows, doesn't work in Android. 

### Steps to Reproduce

[MauiApp1.zip](https://github.com/dotnet/maui/files/8744720/MauiApp1.zip)

1. Open and run the attached project
3. Click on the "^" button at the top of the page
4. The visibility handler works as expected, and changes the value of the glyph's bound property. The property getter is hit, returning the new value, but the glyph on the screen doesn't change.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30

**Comment by kristinx0211** [comment]
verified works in Windows, doesn't work in Android with above project.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0, This issue does not repro on Android emulator (13.0-API 33) and Windows 11 with below Project:
[MauiApp9.zip](https://github.com/dotnet/maui/files/11428005/MauiApp9.zip)
