### ISSUE TITLE
ListView and CollectionView do not scroll in a VerticalStackLayout

### ISSUE THREAD

**Issue by michaelstonis** [dotnet/maui#7386]
### Description

When a `ListView` or a `CollectionView` is encapsulated in a `VerticalStackLayout`, it doesn't appear to fill the space and fill new items in appropriately. The behavior is roughly the same on iOS, Mac, and Android.

Below is the observed behavior:

https://user-images.githubusercontent.com/120685/169619113-e6d60eb5-251c-45e2-8b0c-8fe0f86f8c59.mp4

In this example, the `ListView` has the `VerticalOptions = LayoutOptions.Fill`. In Xamarin.Forms, this kind of control would have required `FillAndExpand` to expand into any available space, but that API is deprecated and not supported on `VisualStackLayout`. It is my understanding that because the `AndExpand` variants are no longer available, that `Fill` would allow child controls to fill any available space similar to how expansion worked previously. I didn't see any documentation that stated the behavior would be otherwise.

### Steps to Reproduce

1. Clone this repo: https://github.com/michaelstonis/RxMaui/tree/feature/vsl-fill-no-go
2. Mash on the `Get Count` button until rows exceed the height of the available display
3. Try to scroll

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

macOS Monterey, iOS 15.4, Android 12

### Did you find any workaround?

You can use a `Grid` to solve the problem. Just set the `ListView` or `CollectionView` to a row with a height of star (`*`).

**Comment by kristinx0211** [comment]
@michaelstonis verified not repro on IOS 15.4 and android 12. seems it can scroll for me. let me know if I miss something.
https://user-images.githubusercontent.com/99457000/169769920-3dc5c8f3-e822-464c-a7a4-5e95d91fa418.mp4

**Comment by Symbai** [comment]
I have experienced the same bug, when I wanted to report it I saw this one here and used the workaround (thanks for that) and tracked the issue instead. For me this issue also occurred on Android 12 Pixel 5 but I've noticed two things:

1. It only happend if there are many items in the listview
2. You can scroll a bit but then items are cut off at the bottom. Like you can see there are more items but you just cannot scroll further down

It is a bit difficult to reproduce it as it seems it depends on multiple factors or specific conditions. When trying to create a quick repro now I could partly re-create it. You can still scroll down the entire list but you cannot scroll down to the `Button` at the bottom. In my production app it looked the same but it stopped on Listview items. Perhaps it helps...

[Repro.zip](https://github.com/dotnet/maui/files/8752657/Repro.zip)

https://user-images.githubusercontent.com/14368203/169773671-f4396cdb-962c-41dd-ba27-cb0d7914b5c6.mp4

**Comment by kristinx0211** [comment]
@Symbai thanks for your update, I can verified this on android 12 with the repro project.

**Comment by michaelstonis** [comment]
Attached are two videos of the issue with iOS 15.5.

### ListView in a VerticalStackLayout

The background of the view should be a pink color, but it is not shown until content is added. Once content is added that exceeds the length of the screen, notice how I am unable to scroll to the additional items. It will, momentarily, allow a display of additional items due to the iOS scroll bounce.

**Demo**

https://user-images.githubusercontent.com/120685/169825543-37bd4172-07a4-4cb2-89d0-1ce5f7818344.mp4

**Code**

```
Content =
    new VerticalStackLayout
    {
        Children =
        {
            new LifecycleButton
            {
                Text = "Get Count",
                VerticalOptions = LayoutOptions.Start
            }
                .Assign(out _myButton),
            new Button
            {
                Text = "Next Page",
                VerticalOptions = LayoutOptions.Start
            }
                .Assign(out _nextPage),
            new RxContentView()
            {
            },
            new ListView
            {
                BackgroundColor = Colors.Fuchsia,
                VerticalOptions = LayoutOptions.Fill,
            }
                .Assign(out _myCollection),
        },
        Padding = 8,
        Spacing = 8,
    };
```

### CollectionView in a VerticalStackLayout
The CollectionView will behave in a largely similar way. Notice that the background here is fully pink as if the CollectionView has expanded into all of the available area. Once enough items have been added to exceed the length of the screen, I am unable to scroll to view these items as the CollectionView does not bounce.

**Demo**

https://user-images.githubusercontent.com/120685/169826059-44771890-298b-422b-b413-8e04863b10ba.mp4

**Code**

```
Content =
    new VerticalStackLayout
    {
        Children =
        {
            new LifecycleButton
            {
                Text = "Get Count",
                VerticalOptions = LayoutOptions.Start
            }
                .Assign(out _myButton),
            new Button
            {
                Text = "Next Page",
                VerticalOptions = LayoutOptions.Start
            }
                .Assign(out _nextPage),
            new RxContentView()
            {
            },
            new CollectionView
            {
                BackgroundColor = Colors.Fuchsia,
                VerticalOptions = LayoutOptions.Fill,
            }
                .Assign(out _myCollection),
        },
        Padding = 8,
        Spacing = 8,
    };
```

**Comment by michaelstonis** [comment]
> @michaelstonis verified not repro on IOS 15.4 and android 12. seems it can scroll for me. let me know if I miss something. https://user-images.githubusercontent.com/99457000/169769920-3dc5c8f3-e822-464c-a7a4-5e95d91fa418.mp4

I don't believe that you tested this with the right branch. Please make sure to use the branch at https://github.com/michaelstonis/RxMaui/tree/feature/vsl-fill-no-go

**Comment by Vroomer** [comment]
I can confirm this issue with CollectionView on Windows platform.

**Comment by angelru** [comment]
I think if you put a Grid it can work

**Comment by Symbai** [comment]
> I think if you put a Grid it can work

Thanks but that's what @michaelstonis already said under workarounds:

> ### Did you find any workaround?
> You can use a `Grid` to solve the problem. Just set the `ListView` or `CollectionView` to a row with a height of star (`*`).

**Comment by ShiiikK** [comment]
> > I think if you put a Grid it can work
> 
> Thanks but that's what @michaelstonis already said under workarounds:
> 
> > ### Did you find any workaround?
> > You can use a `Grid` to solve the problem. Just set the `ListView` or `CollectionView` to a row with a height of star (`*`).

No, this just dont work.

**Comment by rmarinho** [comment]
Hi, this is by design. Stacklayout will expand and have a inifite height or the height for all items of the CollectionVIew. You will need to use a Grid if you want to size to screen and get the scroll.
