### ISSUE TITLE
Fix Grid Auto height based on Images

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#7388]
The following Grid determines the auto row height as being the intrinsic height of the image on Android, rather than the height of the image adjusted to maintain the aspect ratio to fit in the column space:

```
    <Grid ColumnDefinitions="*,*,*" RowDefinitions="Auto">

        <Image VerticalOptions="Start" Grid.Column="0" Source="dotnet_bot.png" BackgroundColor="LightGreen"/>
        <Image VerticalOptions="Center" Grid.Column="1" Source="coffee.png" BackgroundColor="LightBlue"/>
        <Image VerticalOptions="End" Grid.Column="2" Source="dotnet_bot.png" BackgroundColor="Orange"/>

    </Grid>
```

Leaving this as a note to myself to try fixing it on Monday.

**Comment by Dreamescaper** [comment]
Same as this one, I suppose
https://github.com/dotnet/maui/issues/5438
