### ISSUE TITLE
The style of is CollectionView selected item incorrect

### ISSUE THREAD

**Issue by Blcile** [dotnet/maui#7391]
### Description

The style of  is CollectionView  selected item incorrect.

https://user-images.githubusercontent.com/15171204/169652865-fe454f13-39c3-4931-8343-1e2f4c697206.mp4

[MauiAppCollectionViewVisualStateGroups.zip](https://github.com/dotnet/maui/files/8747654/MauiAppCollectionViewVisualStateGroups.zip)

### Steps to Reproduce

1. Download the attached project file
2. Run with Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 10

**Comment by kristinx0211** [comment]
verified not repro on android 11 with vs 17.3.0 Preview 2.0 [32517.445.main].
https://user-images.githubusercontent.com/99457000/169735132-d8797b61-b326-4c22-9947-6e14e8d3cac5.mp4

**Comment by rmarinho** [comment]
this was fixed by #7689
