### ISSUE TITLE
BlazorWebView: Uncaught SyntaxError: Identifier 'channel' has already been declared.

### ISSUE THREAD

**Issue by fairking** [dotnet/maui#7392]
### Description

Running Maui Hybrid application on Android gives the following error: `Uncaught SyntaxError: Identifier 'channel' has already been declared.`. On other platforms like Windows it is working fine.

![image](https://user-images.githubusercontent.com/13495631/169661124-644ca5d9-ac2a-48e1-9474-6a9ba819f580.png)

![image](https://user-images.githubusercontent.com/13495631/169661138-03453598-8485-4111-9e40-2630fd3ed13e.png)

![image](https://user-images.githubusercontent.com/13495631/169661328-83e37f6e-045a-465d-895b-0bb80b5d8510.png)

### Steps to Reproduce

https://gitlab.com/fairking/napos/-/tree/4-maui-spa

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9.0

### Did you find any workaround?

If I refresh the page the error disappears.

**Comment by fairking** [comment]
Could be related issue with the same error: https://github.com/dotnet/maui/issues/5850

**Comment by jfversluis** [comment]
@TanayParikh didn't you look into that back then?

**Comment by fairking** [comment]
> @fairking can you remove the `autostart=false` from here? https://gitlab.com/fairking/napos/-/blob/4-maui-spa/Napos/wwwroot/index.html#L23

I just tried to remove it but it didn't help.

**Comment by TanayParikh** [comment]
Thanks for the clarification, this type of error usually surfaces when you try to `Start` Blazor multiple times. This looks to be an app specific issue from the description you've provided. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the blazor tag.

**Comment by fairking** [comment]
But this is Blazor issue. The call `window.DotNet.invokeMethodAsync()` causes the issue, not the app ☹️

**Comment by fairking** [comment]
>> you try to Start Blazor multiple times

What do you mean? I don't start Blazor. I only included the script `_framework/blazor.webview.js`. That is what I did.

**Comment by fairking** [comment]
@TanayParikh FYI

**Comment by TanayParikh** [comment]
You'll need to move the `_framework/blazor.webview.js` script to be within the `<body>` tag:

https://gitlab.com/fairking/napos/-/blob/4-maui-spa/Napos/wwwroot/index.html#L18

and re-add the `autostart="false"`.

> The call window.DotNet.invokeMethodAsync() causes the issue, not the app ☹️

Which call are you referring to? Is it the framework making the call, or user code?

> But this is Blazor issue.

If you believe this to be an issue in the framework, please provide a minimal (with all code not related to the issue removed), public github repository that reproduces this issue. The current repro is large and has a bunch of application specific code, so it's hard to look into this issue without having context on the repo and it's architecture.

**Comment by fairking** [comment]
> You'll need to move the `_framework/blazor.webview.js` script to be within the `<body>` tag
> and re-add the `autostart="false"`. 

Thanks. It fixed the issue. Double checked Windows and Android version in Release and everything is working so far.
