### ISSUE TITLE
[Windows] Connectivity changed on throws an exception and sometimes crashes the app

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#7393]
### Description

When I switch between airplane mode and non-airplane mode in the train (train wifi is available) first ConnectivityChanged works well.
Every subsequent change of the connectivity throws this exception:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
WinRT information: The application called an interface that was marshalled for a different thread.

The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
```

Also, when this happens, the `Connectivity.ConnectivityChanged` event handler is usually (not regularly) not hit again (I print current connection status in this event handler).

Sometimes, the app crashes with this exception and sometimes it does not. The application crashes when ConnectivityChanged eventhandler is executed. The application however sometimes still crashes without entering the event handler at all.

There is no issue on Android.

### Steps to Reproduce

MAUI Blazor app Debug mode
- change internet connectivity

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

RC 2 I think

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

no

**Comment by janseris** [comment]
Basic repro:
```
@page "/"
@implements IDisposable

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

@Connection

@code{
    string Connection { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        Connectivity.ConnectivityChanged += ConnectivityChanged;
    }

    public void Dispose()
    {
        Connectivity.ConnectivityChanged -= ConnectivityChanged;
    }

    void ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
    {
        Connection = e.NetworkAccess.ToString();
    }
}
```

**Comment by janseris** [comment]
Repro #2
```
@page "/"
@using System.Diagnostics
@implements IDisposable

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

@Connection

@code{
    string Connection { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        Connectivity.ConnectivityChanged += ConnectivityChanged;
        Trace.WriteLine($"rendering page with thread {Thread.CurrentThread.ManagedThreadId}");
        ConnectivityChanged(null, null);
    }

    public void Dispose()
    {
        Connectivity.ConnectivityChanged -= ConnectivityChanged;
    }

    void ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
    {
        Trace.WriteLine($"connectivity changed event handler running on thread {Thread.CurrentThread.ManagedThreadId}");
        InvokeAsync(() =>
        {
            Connection = Connectivity.NetworkAccess.ToString(); //TEST avoid issue
        });
    }
}
```

**Comment by VincentBu** [comment]
not repro with vs main build(32627.385). There is no wlan module on my machine, so I change internet connectivity by connecting and disconnecting VPN.

**Comment by janseris** [comment]
> not repro with vs main build(32627.385). There is no wlan module on my machine, so I change internet connectivity by connecting and disconnecting VPN.

This issue is for any Internet connection type . Not only WiFi. You can simply disable Ethernet connection in settings, that would work as well.

**Comment by mattleibow** [comment]
Is this bug still happening? I can't reproduce nor can I repro the other issue #9972 not the winui bug https://github.com/microsoft/WindowsAppSDK/issues/2965#issuecomment-1279475882
