### ISSUE TITLE
Adding more than 16 controls on a page makes the TAB order wrong in Windows.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7395]
### Description

If you remove the last Entry Control, the TAB order works as it should in Windows.
Adding a ZIndex property is a solution for a Windows app but not for an Android app. ZIndex throws an error and closes the Android app when running on an Android phone.

Running Visual Studio 2022 Version 17.3.0 Previeuw 1.0 on Windows 11.

See test app in attachment.
[MauiAppTestTab.zip](https://github.com/dotnet/maui/files/8748199/MauiAppTestTab.zip)

### Steps to Reproduce

1. Create a file > New .NET MAUI App
2. Add 17 Entry fields to a page
3. Run the app in Windows

[MauiAppTestTab.zip](https://github.com/dotnet/maui/files/8748207/MauiAppTestTab.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/6140
