### ISSUE TITLE
Folders locked by WebViewHost.exe and adb.exe

### ISSUE THREAD

**Issue by guardrex** [dotnet/maui#7397]
### Description

I'm moving apps from my old PC to a new PC, and I discovered that all of my Blazor Hybrid apps (WPF-Blazor, WinForms-Blazor, and .NET MAUI-Blazor) have locked folders in processes **WebViewHost.exe**. My .NET MAUI-Blazor project folder is also locked by **adb.exe**. VS and the apps aren't running.

![image001](https://user-images.githubusercontent.com/1622880/169670203-a53c7aca-e085-4508-a90d-388580bd6adc.png)

![image002](https://user-images.githubusercontent.com/1622880/169670206-72428fad-de6a-44f1-99df-f006c7dc78ce.png)

### Steps to Reproduce

1. Create a WPF-Blazor, WinForms-Blazor, or MAUI-Blazor app.
1. Run the app(s) ... AFAIK, with the debugger. Stop the app(s).
1. Close VS.
1. Attempt to move the project folder off the system. In my scenario, I'm moving to OneDrive to transfer to another PC.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 SDK (10.0.19041.0)

### Did you find any workaround?

I used Sysinternals Process Explorer to kill the process trees. I was then able to move the project folders off the system (OneDrive folder).

**Comment by javiercn** [comment]
@guardrex I think that is "expected" if at some point you shutdown the app "ungracefully". Killing the process is the expected way to go I think.

I would expect this is something that the tooling/webview components could potentially handle as they are the ones starting the process. We do a similar thing for SPA where we launch a script that watches the parent process and kills all its children when the process stops existing.

**Comment by javiercn** [comment]
@jfversluis for the adb.exe piece of this issue, could you route this to the appropriate tooling teams? 

That looks like a general Maui tooling issue and not something specific to Blazor.

**Comment by janseris** [comment]
I suggest this program.
It works very well solving these issues - e.g. folder used by Visual Studio even when VS is closed and also adb etc.
https://lockhunter.com/

**Comment by guardrex** [comment]
@janseris ... That's not the point tho, and I don't plan on calling out workarounds for this in our tutorials (unless management calls for it). Many LOB devs ... new devs ... new-to-.NET devs ... they'll all be upset by this.

@javiercn ... I don't recall exactly how I was closing, whether I was using VS's stop button or closing the (debug config) app with its close button. I'll take a look at that as soon as I get some time 🏃 and leave a remark over on https://github.com/MicrosoftEdge/WebView2Feedback/issues/2477 as to exactly what the repro is for **WebViewHost.exe**. For **adb.exe**, I'll leave a remark on this issue if we know where that's going to be investigated.

**Comment by VincentBu** [comment]
repro with vs main build(32523.339.main). No matter how we close the vs, we need to kill adb.exe before moving the project folder(or deleting it).

**Comment by guardrex** [comment]
Still reproduces with 7.0 ...

![image](https://user-images.githubusercontent.com/1622880/213861328-04f4c5c4-9d7c-4db2-a259-cedd2d4c86a9.png)

**Comment by janseris** [comment]
> Still reproduces with 7.0. If I restart the system, I _**can**_ move the folder. It doesn't matter whether I close the app by closing its running app window or close the app via VS's stop button ... it locks either way and prevents moving the folder.
> 
> _**UPDATE**_: If I close the handle for both the `node.exe` and `adb.exe` processes in Process Explorer, that unlocks the file(s) so that the folder can be moved.
> 
> ![image](https://user-images.githubusercontent.com/1622880/213861328-04f4c5c4-9d7c-4db2-a259-cedd2d4c86a9.png)
> 
> ![image](https://user-images.githubusercontent.com/1622880/213861759-5071d463-54c3-46dc-82c9-1bccdd0a120e.png)

Yeah that is what I suggested as a workaround and my comment was marked as offtopic

**Comment by guardrex** [comment]
Perhaps, it just wasn't clear that you were providing workaround feedback because you referred to "solving" these types of issues. Marking your issue like that was probably accidental.
