### ISSUE TITLE
FlyoutPage.IsPresented- not working in runtime

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#7398]
### Description

When I change this value in run time is not affected.

### Steps to Reproduce

1.I attached demo.
2.Please see MyRootPage.xaml.cs
On ShowLoginState function + ShowNormalState function.
When it set to false is not working.
[FlyoutExample.zip](https://github.com/dotnet/maui/files/8748781/FlyoutExample.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 10 proffesinal-Windows Feature Experience Pack 120.2212.3920.0

### Did you find any workaround?

No.
Need solution

### Relevant log output

```shell
No log.
```

**Comment by jfversluis** [comment]
You will have to trigger it from `Shell.Current.FlyoutIsPresented = "true"` not on the actual flyout itself. Also see: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/flyout#open-and-close-the-flyout-programmatically

**Comment by danies8** [comment]
Thanks for answer.
I used FlyoutPage not Shell.
Shell.Current.FlyoutIsPresented = "true" not complied.
