### ISSUE TITLE
Listview - When IsPullToRefreshEnabled is enabled controls on ItemTemplate are not clickable

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7402]
### Description

When `IsPullToRefreshEnabled` is enabled, elements in the `listview `are not clickable such as a `Switch` control for example. See short demo video below. I have tested it on Android only.

### Steps to Reproduce

https://user-images.githubusercontent.com/14368203/169694080-b81c33f9-ea7f-4e23-9d98-c6233c579c8c.mp4

[Repro.zip](https://github.com/dotnet/maui/files/8749335/Repro.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, API 31, Pixel 5 (Android Simulator)

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0. This issue does not repro on Android emulator (13.0-API 33) with below Project:
[MauiApp12.zip](https://github.com/dotnet/maui/files/11428242/MauiApp12.zip)

**Comment by Symbai** [comment]
I can confirm the issue no longer occurs using latest maui version (not master)
