### ISSUE TITLE
Issue Android version 12 API  31

### ISSUE THREAD

**Issue by Javierflo95** [dotnet/maui#7404]
### Description

since I updated my cell phone to version Android 12 with API 31 several things started to fail, 2 of them are that the Splash Screen no longer shows any images and another is when I stop the app and I want to open it without debugging (without vs just from my phone) this it closes automatically by itself

### Steps to Reproduce

1. Create new Net MAUI app
2. Connect your local device,  at this moment I tested with Samsung M31
3. Run it

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android  12

**Comment by MagicAndre1981** [comment]
For Splashscreen, you need to add a [new package ](https://www.nuget.org/packages/Xamarin.AndroidX.Core.SplashScreen/1.0.0-beta02) and do some [migration](https://developer.android.com/guide/topics/ui/splash-screen/migrate)

**Comment by Javierflo95** [comment]
Is this package for only Android?, because I am using the NET MAUI splashscreen and actually I am using the MAUI latest version, and I'm not replacing the splash screen icon by default wven this doesn't appear

**Comment by Javierflo95** [comment]
Actually, I just downloaded the maui samples like 'WeatherTwentyOne' and the splashscreen still not worked well when I deploy the app in debugging mode I mean when Iaunch the app with VS 2022 preivew does not showing up the icon in the splashscreen.

@jamesmontemagno 
@geraldmrv

**Comment by jfversluis** [comment]
I'm not sure if the WeatherTwentyOne app has been updated to the latest changes at this time. I guess it would be really helpful if you could provide us with the build output or a binlog file of your build to see if there is anything weird in there.

**Comment by MagicAndre1981** [comment]
> Where can I find the build output or binlog? 

create on when calling msbuild:

https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md

**Comment by Javierflo95** [comment]
[msbuild.ProjectImports.zip](https://github.com/dotnet/maui/files/8800914/msbuild.ProjectImports.zip)

@jfversluis  here the file :)

**Comment by Symbai** [comment]
FYI: I'm having the same problem with no splash screen shown on Android. Same app, same code running on iOS splashscreen appears as it should. But for me it also isn't showing on Android version 11 API 30. I think the issue came with a MAUI update. @Javierflo95 Any chance you can test your app on an older android version so we know we're talking about the same problem?

**Comment by Javierflo95** [comment]
@jfversluis 


any update about it??

**Comment by VincentBu** [comment]
repro Splash Screen issue with vs main build(32627.385) on Android emulator. for issue 2, I can't repro it on Android emulator.

**Comment by Javierflo95** [comment]
> repro Splash Screen issue with vs main build(32627.385) on Android emulator. for issue 2, I can't repro it on Android emulator.

Hello @VincentBu , I think that in the emulator we have a less version than API 31, which is the one I currently have on my physical Samsung cell phone, because when I deploy my application in the emulator by default, it is an API less than the one I have on my cell phone, the spash screen logo can be seen well

**Comment by jonathanpeppers** [comment]
I'm trying to see if there is a general problem with the splash screen in MAUI.

One thing to note is: https://issuetracker.google.com/issues/207386164

Basically, if you have Android API 31 (Android 12+), splash screens do not show when launched in a different way than tapping an icon on the home screen (so like IDEs, etc.). We found this was the case when using the new splash screen AndroidX package, *and* the behavior currently in MAUI.

To test the splash screen, are you seeing anything different if you tap the app icon manually?

For now, I'm seeing if there is some kind of incremental build issue -- maybe changing the splash screen image is causing a bug.

**Comment by mattleibow** [comment]
I think we now have more features to use for Android: https://developer.android.com/guide/topics/ui/splash-screen#set-theme

**Comment by jonathanpeppers** [comment]
Yeah here is Android 11 vs Android 12, it's putting the app icon for the splash screen:

![image](https://user-images.githubusercontent.com/840039/176255154-646e9834-0efa-4c56-a3dc-7b695915b575.png)

It seems like this is just new behavior in 12...

Here is a workaround for Android 12+ devices:

1. Create a `Platforms\Android\Resources\values\styles.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<resources>
  <style name="My.SplashTheme" parent="Maui.SplashTheme">
    <item name="android:windowSplashScreenBackground">@color/maui_splash_color</item>
    <item name="android:windowSplashScreenAnimatedIcon">@drawable/maui_splash</item>
  </style>
</resources>
```

2. Update your `MainActivity.cs`:

```csharp
[Activity(Theme = "@style/My.SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
public class MainActivity : MauiAppCompatActivity
```

Now I get:

![image](https://user-images.githubusercontent.com/840039/176255307-2c876c1c-3b44-4f14-b67c-14bc3296fefd.png)

**Comment by Javierflo95** [comment]
@jonathanpeppers , oh got it, I'm going to try it .. thanks

**Comment by Javierflo95** [comment]
Hi @jonathanpeppers , I tried as you said and this is the result
![image](https://user-images.githubusercontent.com/11860518/176351235-b299d9ce-e872-4c76-9c81-14577da6f03c.png)

--
But still now showing when we deploy with VS, just working well manually as you said befire

**Comment by mattleibow** [comment]
This is now fixed in #8394

**Comment by sethlangel** [comment]
> Did you update your `MainActivity` to use your new style?
> 
> ```cs
> [Activity(Theme = "@style/Gen.SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
> public class MainActivity : MauiAppCompatActivity
> ```
> 
> You also need to use:
> 
> ```
> <item name="android:windowSplashScreenAnimatedIcon">@drawable/maui_splash</item>
> ```
> 
> If you want the image used in `MauiSplashScreen` in your `.csproj`.
> 
> It looks like you put a drawable named `logogeneration`, and that's what you're seeing?

Hello @jonathanpeppers I followed your steps to workaround this issue for Android 11. However I am getting the same result as @Javierflo95 where the splash icon is in a circle rather than it being a full image.

![Screenshot 2022-07-07 102258](https://user-images.githubusercontent.com/8517744/177833249-b9f96c59-22cd-43ea-acb7-15b8ab005744.jpg)

**Comment by Javierflo95** [comment]
> This is now fixed in #8394

Could you open it again pls because still not fixed

**Comment by jonathanpeppers** [comment]
So the problem before was the image wasn't shown at all, and it was just putting the app icon. That should be fixed.

Now we're hitting a new issue, Android has a lot of rules about the dimensions of the splash icon:

https://developer.android.com/guide/topics/ui/splash-screen#elements

The .NET logo I was using before, was appropriately sized and works. So I didn't even notice this cropping behavior, before.

I don't see a way to make Android _not_ clip the image to a circle. @sethlangel in your example (https://github.com/dotnet/maui/issues/7404#issuecomment-1177963549), if you make `BaseSize` smaller on the image you're using, does it *fix* the issue?

**Comment by sethlangel** [comment]
@jonathanpeppers Just tested it and made `BaseSize="64,64"` and it worked, it is no longer clipping the image into the circle! Although now I am curious, does this mean that the automation of resizing an image is not working correctly?

**Comment by jonathanpeppers** [comment]
@sethlangel it's going to try to put whatever size you have and upscale for `xxxhdpi`. Resizetizer doesn't necessarily know you're using it for a splash screen or some image inside your app.

We could maybe make an inset, something like this:

https://stackoverflow.com/a/69895108

However, it seems like it might actually be better to choose a smaller image. Because if we did this, you'd have a giant image that is scaled smaller -- an unnecessary increase to app size. You'd also lose full control somewhat.

@mattleibow we might should think about/discuss this one.

**Comment by sethlangel** [comment]
@jonathanpeppers I see what you are saying and that makes a lot of sense. 

I feel that it might be better to force the file to downscale to the optimal sizing regardless of the size of the original file. It makes sense that it would be a waste of app size but it would also make it easier for people to just throw an image in and not have to figure out what size they have to make it with `BaseSize`.

Then in documentation just state what the recommended size of the file would be and if they want to follow that they can? I am not sure on how simple or effective that would be but just an idea.

Thank you for the help and responses!

**Comment by Javierflo95** [comment]
I'm getting this message error since I did the Adnroid changes @jonathanpeppers  could you pls gelp me with that thanks


![image](https://user-images.githubusercontent.com/11860518/178775211-c74890d5-a11c-4340-ba04-ae684957c736.png)
