### ISSUE TITLE
ListView w/ Binding, Delete first item -> Crash (Maui RC3, Android)

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/maui#7406]
### Description

Crash on Android. (Works on Windows.)

Repo: https://github.com/ToolmakerSteve/MauiBug_ListView_Delete

StackOverflow: https://stackoverflow.com/questions/72339216/net-maui-app-crashes-on-basic-delete-from-list

Crash dump:
[Maui ListView - Delete Item - Crash.txt](https://github.com/dotnet/maui/files/8750018/Maui.ListView.-.Delete.Item.-.Crash.txt)

### Steps to Reproduce

* Bind a ListView to ObservableCollection in a ViewModel.
* Add 2 or 3 items.
* With a button on each item, use Command to delete that item.
* If it is NOT the last item in list, crashes on Android. (Works on Windows.)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 29 (did not test others)

### Did you find any workaround?

Perhaps use CollectionView instead of ListView.

### Relevant log output

```shell
// See above attachment Maui ListView - Delete Item - Crash.txt for full dump.
[nyname.mauiapp] java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[nyname.mauiapp] java_vm_ext.cc:570]   at void android.view.ViewGroup.addViewInner(android.view.View, int, android.view.ViewGroup$LayoutParams, boolean) (ViewGroup.java:5106)
...
[nyname.mauiapp] java_vm_ext.cc:570]     in call to CallObjectMethodA
[nyname.mauiapp] java_vm_ext.cc:570]     from android.view.View crc64e1fb321c08285b90.ListViewAdapter.n_getView(int, android.view.View, android.view.ViewGroup)
**Java.Lang.IllegalStateException:** 'Loading...'
```

**Comment by ToolmakerSteve** [comment]
Verified that above repo works (no crash on Android) if use `CollectionView` instead of `ListView` (and remove `ViewCell` from `ItemTemplate`).

**Comment by VincentBu** [comment]
repro with vs main build(32523.339.main).
