### ISSUE TITLE
FlexLayout provides space for invisible children

### ISSUE THREAD

**Issue by tbrabec** [dotnet/maui#7408]
### Description

Within a FlexLayout I have children that are IsVisible="{Binding IsVisible}" (IsVisible == false) but they still take up space. 
I was able to reproduce it on Android but the invisible children also take up some space on Windows. I did not test it on other platforms.
This bug is similar to https://github.com/xamarin/Xamarin.Forms/issues/2593.

### Steps to Reproduce

Create FlexLayout with a child set IsVisible="{Binding IsVisible}" among other visible ones, where IsVisible property is set to false.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 10, Windows 11

### Did you find any workaround?

No known workaround.

**Comment by tbrabec** [comment]
I figured out that you need to set the visibility **using a binding**.

**Comment by kristinx0211** [comment]
@tbrabec thanks for the update, I can repro this issue on android 12  using binding. repro project:
[MauiApp7.zip](https://github.com/dotnet/maui/files/8760050/MauiApp7.zip)

**Comment by hartez** [comment]
Fixed by #8660
