### ISSUE TITLE
Maui RC3 + VS For Mac Rc2 + Android 31: Carousel stopped working.

### ISSUE THREAD

**Issue by tci-ash** [dotnet/maui#7416]
### Description

With RC1 the Carousel was working, since downloading RC2 (VS For Mac) the carousel stopped working. 

### Steps to Reproduce

1. Install VS For Mac RC 1,  with Maui RC1
2. Create a simple app with Carousel in it. 
3. Run on Android. You will see Carousel in action 
4. Update to VS for mac-RC2, Maui RC3,  Run the app, Carousel gone.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

macOS

### Affected platform versions

Android 12.

### Did you find any workaround?

NO

**Comment by VincentBu** [comment]
not repro with vs main build(32523.339.main). However, on Mac, we need to scroll with scrollbar.
