### ISSUE TITLE
Processing Resources failed with error: Duplicate Entry after updating VS to version 17.3.0 Preview 1.1

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7420]
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.	Finance	C:\Sources\MsCs\MAUI\Finance\Finance\WINAPPSDKGENERATEPROJECTPRIFILE	1	
Error		PRI222: 0x80073b0f - Unspecified error occurred.	Finance	C:\Sources\MsCs\MAUI\Finance\Finance\WINAPPSDKGENERATEPROJECTPRIFILE	1	

It only happens when running in Windows, not in the Android Emulator.
It only happens when using the CommunityToolkit.Maui.
Was running fine in preview 1.0.

### Steps to Reproduce

1. Run the app in Visual Studio on the Windows Machine.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by Eilon** [comment]
@brminnick - tagging you here because the report says this:

> It only happens when using the CommunityToolkit.Maui.

Just in case you have some idea.

**Comment by VladislavAntonyuk** [comment]
it happens with each release and only with Windows. We will update CommunityToolkit soon.

**Comment by brminnick** [comment]
Yup, it's a WinUI tooling problem that occurs when the .NET MAUI version installed on the machine doesn't match the .NET MAUI Dependency on the [NuGet Package](https://www.nuget.org/packages/CommunityToolkit.Maui/).

This bug will be resolved in our release of `CommunityToolkit.Maui` v1.0.0 tomorrow.

The current release of the [`CommunityToolkit.Maui` NuGet Package (v1.0.0-rc3)](https://www.nuget.org/packages/CommunityToolkit.Maui/) targets [Microsoft.Maui.Dependencies v6.0.300-rc.3.5667](https://www.nuget.org/packages/Microsoft.Maui.Dependencies/):

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/13558917/169914692-02309318-d2ba-4479-ae1c-feb14dbbb4a3.png">

As Vlad mentioned, we have seen this same Issue reported each time the .NET MAUI team has released a new version. It is resolved once we publish an update to the [`CommunityToolkit.Maui` NuGet Package](https://www.nuget.org/packages/CommunityToolkit.Maui/) that matches the user's installed version of the .NET MAUI Workload.

It is reported on the .NET MAUI Community Toolkit repo here:
- https://github.com/CommunityToolkit/Maui/issues/253
- https://github.com/CommunityToolkit/Maui/issues/256
- https://github.com/CommunityToolkit/Maui/issues/299
- https://github.com/CommunityToolkit/Maui/issues/328
- https://github.com/CommunityToolkit/Maui/issues/330

**Comment by brminnick** [comment]
@Eilon - Now that .NET MAUI has reached GA, how can we work with the .NET MAUI + WinUI engineering teams to ensure this doesn't happen with future releases of .NET MAUI?

We would like to pin `CommunityToolkit.Maui`'s .NET MAUI Dependency to .NET MAUI v6.0.300 for backwards compatibility, enabling our library to work with for many users as possible (similar to how we keep the [`Xamarin.CommunityToolkit` NuGet Package](https://www.nuget.org/packages/Xamarin.CommunityToolkit) pinned to a lower version of `Xamarin.Forms` than the current stable version of `Xamarin.Forms`).

We need future releases of .NET MAUI to work with our libraries that use .NET MAUI v6.0.300 as a Dependency and I assume our fellow .NET MAUI Library maintainers in the community will require the same.

**Comment by Eilon** [comment]
Paging @mattleibow and @jonathanpeppers who know a lot more about SDKs, Packs, and Workloads than I do. I'm not quite sure how to "pin" a specific MAUI dependency. This applies not only to specific GA releases, but also to previews, I assume? That is, MAUI Community Toolkit vX.Y needs exactly MAUI 7.0 preview 4, no more and no less? (Or something to that effect?)

**Comment by geertgeerits** [comment]
Thanks for the quick solution.
Kind regards.

**Comment by jonathanpeppers** [comment]
> Now that .NET MAUI has reached GA, how can we work with the .NET MAUI + WinUI engineering teams to ensure this doesn't happen with future releases of .NET MAUI?

@brminnick you should add an integration test in MAUI that uses the community toolkit. If a test runs on every PR, they won't be able to break it?

I'd recommend a test that actually runs on devices, maybe it could load the simplest control and just assert that it works?

**Comment by mattleibow** [comment]
Just adding a note, I have a workaround: https://github.com/mattleibow/DuplicateEntryMauiTest/blob/main/Directory.Build.targets
