### ISSUE TITLE
Contacts API namespace conflicts on MacCatalyst and iOS

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#7421]
### Description

I just upgraded to VS 17.3 P1.1 and the essentials API is complaining that the `Contacts` type in the `Microsoft.Maui.ApplicationModel.Communication` namespace is missing. Digging further it seems that there is a conflict with the type because there is a root namespace of `Contacts` already imported.

Generic code for .NET MAUI that should compile across all platforms won't compile for iOS or MacCatalyst without #if or always fully qualifying the type.

### Steps to Reproduce

Code that contains the following line should work on all platforms. It won't compile on iOS/MacCatalyst

```csharp
var contact = await Contacts.Default.PickContactAsync();
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS, macOS

### Affected platform versions

Unsure

### Did you find any workaround?

You have to fully qualify the name:

```csharp
var contact = await Microsoft.Maui.ApplicationModel.Communication.Contacts.Default.PickContactAsync();
```

### Relevant log output

```shell
CS0234	The type or namespace name 'Default' does not exist in the namespace 'Contacts' (are you missing an assembly reference?)	PlatformIntegration (net6.0-ios), PlatformIntegration (net6.0-maccatalyst)	
```
```

**Comment by Eilon** [comment]
> there is a conflict with the type because there is a root namespace of Contacts already imported.

Do you know what that `Contacts` root namespace is? Is that code in your app, or is it from some other project/package?

**Comment by adegeo** [comment]
@Eilon it seems to be something with mac/ios directly. There is a root namespace automatically imported when you target that namespace. Here is the output of the intellisense and browsing to the code of one of those items:

![image](https://user-images.githubusercontent.com/67293991/169901232-3da572ad-3fdb-4b0a-8b7f-389dd804a0f2.png)


```csharp
#region Assembly Microsoft.iOS, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
// C:\Program Files\dotnet\packs\Microsoft.iOS.Ref\15.4.303\ref\net6.0\Microsoft.iOS.dll
#endregion

using ObjCRuntime;
using System.Runtime.Versioning;

namespace Contacts
{
    [Native]
    [SupportedOSPlatform("ios9.0")]
    [SupportedOSPlatform("macos10.11")]
    [SupportedOSPlatform("maccatalyst9.0.0")]
    public enum CNAuthorizationStatus : long
    {
        NotDetermined = 0,
        Restricted = 1,
        Denied = 2,
        Authorized = 3
    }
}
```

**Comment by Eilon** [comment]
@adegeo thank you that is very helpful. I'm not sure what we could do about it, but perhaps some clever folks here could come up with something reasonable. We could consider adding a global using like `using Contacts = Microsoft.Maui.ApplicationModel.Communication.Contacts` to the SDK, which I _think_ would work, but this also shows the danger of global usings to begin with. So, we could fight fire with fire, or give up while we're behind 😄 I think that renaming the Essentials Contact API is a theoretical option, but a huge breaking change, so likely not a practical option.

**Comment by VincentBu** [comment]
repro with vs main build(32523.339.main) and using `Microsoft.Maui.ApplicationModel.Communication.Contacts.Default.PickContactAsync()` does solve the issue.

**Comment by adegeo** [comment]
@Eilon  I'm finding that if iOS or Mac is a target, you must always fully qualify the type, or you can't compile for all platforms. And these are targeted by default, obviously.

When I ran into this issue, I tried what you suggested, mapping `Contacts` specifically, this didn't work though

![image](https://user-images.githubusercontent.com/67293991/170345090-2350b93b-98a7-4edb-b6c5-b8b111c0c803.png)

The only way this works is by mapping the namespace instead:

```csharp
using Communication = Microsoft.Maui.ApplicationModel.Communication;

...

Communication.Contacts.Default.Get...
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2. Not repro this issue.

**Comment by adegeo** [comment]
I just upgraded to Preview 2 also and I still see the problem. However, there is only one way to fix this, which is to remove the types using the `Contacts` namespace. I don't think that's going to happen, so this issue should probably be closed. @Eilon what do you think? Just closet the issue as won't fix?

**Comment by Eilon** [comment]
In my opinion this is an unfortunate 'Won't fix' because no matter what we do, it would probably make things worse.

**Comment by adegeo** [comment]
Please feel free to add the appropriate label and close the issue, I don't have perms for that in this repo.
