### ISSUE TITLE
Using #IF when targeting windows isn't working

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#7423]
### Description

When I have a `#IF WINDOWS` directive, it doesn't seem to be recognized during compile. The intellisense correctly highlights and works when you change the project context to windows, but compiling shows no error but it fails. Once you look at the build output, or try to run `dotnet build -f net6.0-windows10.0.19041.0` directly, you can see the real error, which is indicating the code in `#IF WINDOWS` isn't being included.

### Steps to Reproduce

First, use this code in the App.xaml.cs file:

```csharp
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		MainPage = new AppShell();

		TestWrite.Write("hi!");
	}

#if ANDROID
	public static class TestWrite
    {
		public static void Write(string text) =>
			Console.WriteLine(text);
    }
#elif WINDOWS
	public static class TestWrite
    {
		public static void Write(string text) =>
			Console.WriteLine(text);
    }
#elif MACCATALYST
	public static class TestWrite
    {
		public static void Write(string text) =>
			Console.WriteLine(text);
    }
#elif IOS
	public static class TestWrite
    {
		public static void Write(string text) =>
			Console.WriteLine(text);
    }
#endif

}
```

When you compile for windows it fails:

![image](https://user-images.githubusercontent.com/67293991/169903726-69b6fa40-e8d4-47c8-9a88-0f7ae054b25c.png)
![image](https://user-images.githubusercontent.com/67293991/169903860-6e6528d5-61e1-48d9-be2e-ab0093ad21a0.png)

Build output shows the true error:

```
Build started...
1>------ Build started: Project: MauiApp4, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.303\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed
1>MauiApp4 -> C:\code\Work\temp\MauiApp4\bin\Debug\net6.0-ios\iossimulator-x64\MauiApp4.dll
1>MauiApp4 -> C:\code\Work\temp\MauiApp4\bin\Debug\net6.0-maccatalyst\maccatalyst-x64\MauiApp4.dll
1>C:\code\Work\temp\MauiApp4\App.xaml.cs(11,3,11,12): error CS0103: The name 'TestWrite' does not exist in the current context
1>MauiApp4 -> C:\code\Work\temp\MauiApp4\bin\Debug\net6.0-android\MauiApp4.dll
1>Done building project "MauiApp4.csproj".
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No

**Comment by VincentBu** [comment]
repro with vs main build(32523.339.main).

**Comment by Eilon** [comment]
Indeed, I was able to repro this as well on a fairly clean VM.
