### ISSUE TITLE
MAUI to auto adjust capitalization 

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#743]
Hi,

I just had an issue with Syncfusion SfMap Marker crashing on Android and then found the reason was my XAML was referring to MapMarker.png which works perfectly on iOS but Android was looking for a lower letters file (mapmarker.png)

I hope MAUI will solve this issue and we just need to add the file in whatever way but MAUI will convert it to lower for Android.

Thanks,
Jassim

**Comment by Redth** [comment]
If you're using <MauiImage, we require a lowercase filename in a format that is compatible across platforms, so this should not be an issue, as it will surface as a build error.

You're on your own for platform specific resources.
