### ISSUE TITLE
Page layout is completely messed up in Android after adding too many controls

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7434]
### Description

When more than 16 controls are placed on a page, the layout is completely wrong on Android.
This is about Labels and Entry fields.

### Steps to Reproduce

1. Open the attached app in Visual Studio.
2. Run the app in Windows and press de Calculate button.  You will see a text (Test-Test) in a label.
3. Run the app in Android and press de Calculate button.  There will be no text in the label.
4. Also layout is completely messed up (also for the TAB order).
5. If you remove 1 control then everything is correct.
[MauiAppTestLabel.zip](https://github.com/dotnet/maui/files/8760400/MauiAppTestLabel.zip)

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
can be reproduced on windows and android 12 with above project.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 5.0. Not repro on android emulator with above project.
repro project: [MauiAppTestLabel.zip](https://github.com/dotnet/maui/files/8760400/MauiAppTestLabel.zip)
Android:
![image](https://user-images.githubusercontent.com/82450723/237050554-2cbded9a-0f15-4353-a7fb-d93e29e6fadd.png)
Windows:
![image](https://user-images.githubusercontent.com/82450723/237050782-a8261753-fd37-4280-8000-9c41d841144c.png)

**Comment by geertgeerits** [comment]
The problem has indeed been solved with one of the recent versions.
Thank you.
