### ISSUE TITLE
Please update the viewhandler document

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#7435]
### Description

There are lots of 3rd party native controls can be consumed in MAUI like renderer in Forms.
But I can not found any documents about how to use viewhandler.
I tryed to build an sample app use the viewhandler [here](https://github.com/jingliancui/XamarinFormsTencentX5Sample/blob/master/MAUI/SampleApp/SampleApp/Handlers/TencentWebViewHandler.cs) that I refer the maui sample you build when maui was rc version.
So please update docs about viewhandler. thanks.

### Public API Changes

nothing

### Intended Use-Case

guide developer how to use viewhandler.

**Comment by PureWeen** [comment]
https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create
