### ISSUE TITLE
iOS Linker doesn't work with Grpc.Core

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7437]
### Description

Hello, I have a library that uses the nuget package Grpc.Core. Unfortunately, if I want to build the project on an IOS device, I get the following message

Android works

![image](https://user-images.githubusercontent.com/53478848/169995252-9651701e-8ef6-40cd-9a01-8155a5897a32.png)
![image](https://user-images.githubusercontent.com/53478848/169995836-044c20d8-e285-450a-b50b-f65c697684ac.png)

```
2>ld: symbol(s) not found for architecture x86_64
2>clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(1214,3): error : clang++ mit Code 1 beendet
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(1214,3): error :
```

**My question is now how do I tell the linker that it ignores the package Grpc.Core in the library "ClassLibrary1" ??**

### Steps to Reproduce

1. Use Repro [link](https://github.com/HausBJB/MauiAppGrpc.git)
2. Build Project in iOS

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

I would also like to know

**Comment by drasticactions** [comment]
I don't believe this is an MAUI issue, it's specific to the Xamarin.MaciOS SDK (https://github.com/xamarin/xamarin-macios). This bug should be filed there, I don't think the team in this repo can fix that.

**Comment by HausBJB** [comment]
Hello, I don't know what the problem is.

again to my question can I work around the problem first? can I tell the linker to ignore the library

**Comment by drasticactions** [comment]
You should ask that question to [Xamarin.MaciOS](https://github.com/xamarin/xamarin-macios) as that is the team that maintains the tooling you're trying to use.

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/898335/170065240-deedf9e2-573f-40c4-af98-16844072d9e4.png">

This is a `net6.0-ios` app with that library added, and it blows up on the same clang call. It has nothing to do with MAUI.

Also, looking up Grpc.Core shows [this blog post](https://grpc.io/blog/grpc-csharp-future/) that you should probably switch off of that.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/898335/170065575-2e69beed-e7e1-4cc8-9b36-c8d7fe9c434d.png">


Switching Grpc.Core to Grpc.Net.Client, it worked.

**Comment by HausBJB** [comment]
Great the switching Grpc.Core to Grpc.Net.Client also works


THANK YOU
