### ISSUE TITLE
Cannot display alert from modal page on iOS

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#7444]
### Description

In my Xamarin Forms app, I have many modal pages that contain fields for user input. On my modal base page, I check for an IsDirty flag, and if true I pop up a an alert with Page.DisplayAlert or Page.DisplayActionSheet.

As of the latest version of .NET Maui, when the code for DisplayAlert() executes, the request fails with an output message:

    [Presentation] Attempt to present <UIAlertController: 0x7fe880ac6400> on <Microsoft_Maui_Controls_Handlers_Compatibility_NavigationRenderer: 0x7fe87dab8a00> (from <Microsoft_Maui_Controls_Handlers_Compatibility_NavigationRenderer: 0x7fe87dab8a00>) which is already presenting <Microsoft_Maui_Controls_Platform_ModalWrapper: 0x7fe881886f60>.

Is this a bug or new rules for Maui?

### Steps to Reproduce

1. In a .NET Maui app, create a page to navigate to. On this page (call it ModalPage), add a button. In the code behind, add a call to Page.DisplayAlert.

2. Create a button on the main page, and in the code behind create an instance of ModalPage, wrap it in a NavigationPage, and push that onto the modal navigation stack.

        var modalPage = new ModalPage();
        var navPage = new NavigationPage(modalPage);
        Navigation.PushModalAsync(navPage);

Run it, and press the button to navigate to the modal page. On the modal page, press the button to pop up the alert. Instead of working, it should display the above mentioned message in the output window.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.5, Mac Catalyst 15.5

### Did you find any workaround?

No

**Comment by emorell96** [comment]
I had this bug on my app too. I had to workaround it by using Toasts from the CommunityToolkit.Maui.

**Comment by VincentBu** [comment]
repro with vs main build(32524.329.main)

**Comment by manuelelucchi** [comment]
@hartez aren't 2 months a little too much to fix a big issue like this? you literally can't use modal pages on ios, it's shameful

**Comment by DancesWithDingo** [comment]
This also seems to be impacting the Picker control on Mac Catalyst.

**Comment by agendamatic** [comment]
This is a pretty severe issue. There is no workaround for Picker controls not popping up on modal pages on MacCatalyst. I can't even alpha test without a fix for this.

**Comment by dazzknowles** [comment]
Our whole commercial project is on hold because of this so we could really do with this not slipping anymore.
