### ISSUE TITLE
Border.Stroke Shape is not fully displayed

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7448]
### Description

Hello, I have a border with EllipseGeometry that is not fully displayed

Repro
https://github.com/HausBJB/MauiApp2.git

this fix was already there and then the following happened #6851

Ok because this change
https://github.com/dotnet/maui/pull/6851/commits/f0cf10d285e09cb8900ac8e1bfbd1cd18b49df74

flew out again with this one

https://github.com/dotnet/maui/commit/b8727a40b18bd12a8707af146e19b8be87e86086

main
https://github.com/dotnet/maui/blob/main/src/Core/src/Graphics/MauiDrawable.Android.cs
![image](https://user-images.githubusercontent.com/53478848/170081704-7ffe9dee-0843-4c31-83e2-c31f11d09a1f.png)

### Steps to Reproduce

1. Create new MauiApp
2. Add XAML code in MainPage 
3. Run App

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by jsuarezruiz** [comment]
This definitely didn't work before https://github.com/dotnet/maui/pull/6851 and after remove platform-specific density calculations from the cross-platfor layer here https://github.com/dotnet/maui/commit/e50621cd91d64f778627ba4f5956269523781d89, the issue is back.

**Comment by HausBJB** [comment]
This error persists

6.0.400 (Service Release 1)

please open

**Comment by jsuarezruiz** [comment]
> This error persists @jsuarezruiz 6.0.400 (Service Release 1)
> 
> #7448 please open

Could you upload again the sample https://github.com/HausBJB/MauiApp2?

**Comment by HausBJB** [comment]
Hello, I just uploaded it again
