### ISSUE TITLE
Frame Background with Bound Colors causes null exception and invalid frame handler trace

### ISSUE THREAD

**Issue by VWilcox2000** [dotnet/maui#7449]
### Description

In Android, if you use Frame.Background to assign a linear gradient brush using colors bound from Maui color values in the model, it throws a null exception that looks like it's in the color to platform color conversion and throws a frame has invalid handler error.
In Windows, there is no crash, but the frame does not render at all.
Unfortunately, my iOS simulator is refusing to function for the moment, so I cannot verify the behavior on iOS at moment.

### Steps to Reproduce

Create a content view with a frame assigning a gradient in the background which uses binding to acquire the gradient colors as follows (code that worked in Xamarin):

            <Frame.Background>
              <LinearGradientBrush StartPoint="0,0"
                                   EndPoint="0,1">
                <GradientStop Color="{Binding bgGradColor1_family}"
                              Offset="0" />
                <GradientStop Color="{Binding bgGradColor2_family}"
                              Offset="1" />
              </LinearGradientBrush>
            </Frame.Background>

Binding source (in my case it is in a model):

           public Color bgGradColor1_family =>Color.FromRgb(66, 133, 244); 
           public Color bgGradColor2_family =>Color.FromRgb(53, 103, 201);
           // note: Color IS Microsoft.Maui.Graphics.Color

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 31, Windows 10.0.19041.0, unable to evaluate iOS behavior atm

### Did you find any workaround?

To get around the issue, I eliminated the background xaml section and directly bound Background to a Brush property in the model.  The model now uses a helper function to create the linear gradient from the two colors:

          <Frame Margin="0,5,0,5"
                 Padding="0,14"
                 BackgroundColor="{Binding bgColor_team}"
                 CornerRadius="13"
                 HasShadow="False"
                 BorderColor="{Binding borderColor_team}"
                 HorizontalOptions="FillAndExpand"
                 VerticalOptions="FillAndExpand"
                 Background="{Binding bg_team}">  <-- Background binding here instead of in section

                 // model property
                   public Brush bg_team =>
                   TopDownGradient(
                     bgGradColor1_team,
                     bgGradColor2_team);

                 // the helper function (not pertinent to the bug but in case anyone works around same issue and it is of use)
                   public static Brush TopDownGradient(
                     Color top,
                     Color bottom)
                   {
                     GradientStopCollection gradientStops;
                     Brush ret;

                     gradientStops = new GradientStopCollection();
                     gradientStops.Add(
                       new GradientStop(
                         top,
                         0.0f));
                     gradientStops.Add(
                       new GradientStop(
                         bottom,
                         1.0f));
                     ret =
                       new LinearGradientBrush(
                         gradientStops,
                         new Point(0.0, 0.0),
                         new Point(0.0, 1.0));
                     return ret;
                   }

### Relevant log output

*** the following is for Android as Windows doesn't log anything ***

```shell
Exception popup:
Microsoft.Maui.Platform.ToPlatformException: 'crc64e1fb321c08285b90.FrameRenderer{158977b V.E...... ......I. 0,0-0,0 #73} found for Microsoft.Maui.Controls.Frame is incompatible'

Inner Exception:
{System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.Maui.Graphics.Platform.GraphicsExtensions.AsColor(Color target) in D:\a\_work\1\s\src\Microsoft.Maui.Graphics\Android\GraphicsExtensions.cs:line 28   at Microsoft.Maui.Platform.ColorExtensions.ToPlatform(Color self) in D:\a\_work\1\s\src\Core\src\Platform\Android\ColorExtensions.cs:line 14   at Microsoft.Maui.Controls.Platform.BrushExtensions.GetGradientBrushData(GradientBrush gradientBrush) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\BrushExtensions.cs:line 261   at Microsoft.Maui.Controls.Platform.BrushExtensions.UpdateBackground(GradientDrawable gradientDrawable, Brush brush, Int32 height, Int32 width) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\BrushExtensions.cs:line 147   at Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.UpdateBackground() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Android\FrameRenderer.cs:line 246   at Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.<>c.<.cctor>b__63_2(FrameRenderer h, Frame _) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Android\FrameRenderer.cs:line 27   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 183   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view, IPlatformViewHandler nativeViewHandler, Action`1 onElementChanged, Frame& currentVirtualView, IPropertyMapper& _mapper, IPropertyMapper _defaultMapper, Boolean autoPackage) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\VisualElementRenderer.cs:line 271   at Microsoft.Maui.Controls.Handlers.Compatibility.ViewHandlerDelegator`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view, Action`1 onElementChanged, Boolean autoPackage) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ViewHandlerDelegator.cs:line 86   at Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.Microsoft.Maui.IElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Android\FrameRenderer.cs:line 341   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 307   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 98}

Console log output:
**Microsoft.Maui.Platform.ToPlatformException:** 'crc64e1fb321c08285b90.FrameRenderer{158977b V.E...... ......I. 0,0-0,0 #73} found for Microsoft.Maui.Controls.Frame is incompatible'
```

**Comment by CiarogSoftware** [comment]
See [minimal repo here](https://github.com/CiarogSoftware/BindingToColourProblem)

It happens any time you use binding on a GradientStop Color property.

My experience is different from @VWilcox2000 in that it will crash out when run on Windows with `"System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"` but on Android the page simply does not display. I do not have an iOS device to test.

**Comment by VincentBu** [comment]
repro with vs main build (32604.83.main) on Android emulator
![image](https://user-images.githubusercontent.com/44959937/172087555-eb2fda72-0845-454a-b081-b8139c2ae76d.png)

**Comment by VWilcox2000** [comment]
Interesting indeed that it would be reversed.  Since that happened, I've gotten familiar with the MAUI style system and it is better than the workaround I posted above which might interest somebody new to MAUI like myself.

In the same folder as Colors.xaml and Styles.xaml, I added a Gradients.xaml file with build action MauiXaml.  I put my gradients in there:

      <?xml version="1.0" encoding="UTF-8" ?>
      <?xaml-comp compile="true" ?>
      <ResourceDictionary xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                          xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
      
        
        <LinearGradientBrush x:Key="WhiteGradient"
                             StartPoint="0,0"
                             EndPoint="0,1">
          <GradientStop Color="White"
                        Offset="0" />
          <GradientStop Color="#dfdfdf"
                        Offset="1" />
        </LinearGradientBrush>
            ...

And then in Resource/Themes, I have LightTheme.xaml and DarkTheme.xaml also MauiXaml, and they have theme specific styles which can leverage the gradients by name from the gradients.xaml file like so:

        <Style x:Key="activeAppModeStyle"
               TargetType="Border">
          <Setter Property="Background"
                  Value="{StaticResource IntenseBlueGradient}" />
                    ...

Then in the original Border where I had the gradients, I can use Background="{DynamicResource activeAppModeStyle}"  <-- dynamic so it updates when I swap the themes.

It's documented on MAUI site though not thoroughly enough I didn't have to experiment some to get all that working with things in the right places.

You also need to add your new resource / style files to app.xaml as below:

      <?xml version = "1.0" encoding = "UTF-8" ?>
      <Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:local="clr-namespace:MyApp"
                   x:Class="MyApp.App">
        <Application.Resources>
          <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
              <ResourceDictionary Source="Resources/Colors.xaml" />
              <ResourceDictionary Source="Resources/Gradients.xaml" />
              <ResourceDictionary Source="Resources/Styles.xaml" />
              <ResourceDictionary Source="Resources/Themes/LightTheme.xaml" />
            </ResourceDictionary.MergedDictionaries>
          </ResourceDictionary>
        </Application.Resources>
      </Application>

It's a pretty neat system and more powerful than the 3rd party Style additions that were available in Xamarin.  I do get some graphical anomalies on different platforms at times with some styles, but most I can overcome and hopefully that goes away as they move into a final release.  Using this system is quite convenient, though, as instead of a AppThemeBinding on every element in your xaml, you just assign the Style -- and then set the values for that style differently in each theme file.  Happy Hunting!

**Comment by nor0x** [comment]
will this PR be in the next release? is there a way to get PR or early builds?
