### ISSUE TITLE
ShellContent Title doesn't observe changes to bound properties

### ISSUE THREAD

**Issue by jskeet** [dotnet/maui#7453]
### Description

I have a shell with a page that itself has two tabs. The title of each tab can change dynamically, so it's set using `<ShellContent Title="{Binding ...}" />`. The binding is active initially, i.e. the title *is* taken from the binding - but if the bound property changes, the title doesn't change.

### Steps to Reproduce

Code is in [ShellContentTitleBinding.zip](https://github.com/dotnet/maui/files/8765438/ShellContentTitleBinding.zip)

The important parts are:

AppShell.xaml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="ShellContentTitleBinding.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:ShellContentTitleBinding"
    Shell.FlyoutBehavior="Disabled">

    <TabBar>
        <Tab Title="Nested tabs">
            <ShellContent BindingContext="{Binding Tab1}" Title="{Binding Name}" ContentTemplate="{DataTemplate local:TabView}" />
            <ShellContent BindingContext="{Binding Tab2}" Title="{Binding Name}" ContentTemplate="{DataTemplate local:TabView}" />
        </Tab>
    </TabBar>
</Shell>
```

TabView.xaml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ShellContentTitleBinding.TabView"
             Title="TabView">
    <StackLayout>
        <Label Text="{Binding Name}" />
        <Button Text="Change name" Clicked="ChangeName" />
    </StackLayout>
</ContentPage>
```

The `ChangeName` handler changes the property, which raises the appropriate event.

Importantly:

- The initial value of the `Name` property *is* used in the title (so the binding is fundamentally making a connection)
- The changed value of the `Name` property *is* visible in the label in the view (so the binding notification code seems to be okay)
- The changed value *isn't* used in the title, as per this screenshot:

<img width="400" alt="Screenshot of issue" src="https://user-images.githubusercontent.com/17011/170109014-795e4b16-c5d1-473e-bdea-6da0af574094.png">

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 / Pixel 5 / API 30, Windows10.0.19041.0

### Did you find any workaround?

Not yet.

**Comment by PureWeen** [comment]
@jskeet 

1) There's definitely a bug here
2) Once the bug is fixed, I just want to point out that the `BindableProperty` for `Title` by default uses `OneTime` binding. This decision was made for performance reasons when `Shell` was first created. I'm not the biggest fan of this as it feels unexpected and I have my doubts if it really does much for performance. 

So you have to define the bindings yourself using `OneWay`
```XAML
<ShellContent BindingContext="{Binding Tab1}" Title="{Binding Name, Mode=OneWay}" ContentTemplate="{DataTemplate local:TabView}" />
<ShellContent BindingContext="{Binding Tab2}" Title="{Binding Name, Mode=OneWay}" ContentTemplate="{DataTemplate local:TabView}" />
```

If you change the bindings to `OneWay` you'll see that Android works slightly better (if you click away and then back it updates). So there are still bugs here :-)

**Comment by jskeet** [comment]
Wonderful - thank you so much for a swift diagnosis and workaround!

**Comment by jskeet** [comment]
I can confirm that the workaround works well for me. (As it happens, the name is changed in the background in my real app, before the tab is even visible, so this actually addresses *my* issue completely. But it's not just about my existing use case, of course :)

**Comment by VincentBu** [comment]
repro with vs main build(32525.350.main)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Windows 11 and Android 13.0 with below Project:
[ShellContentTitleBinding.zip](https://github.com/dotnet/maui/files/11439508/ShellContentTitleBinding.zip)

**Comment by ewerspej** [comment]
The same is true for other bindings on ShellContent elements, e.g. showing and hiding tabs in the TabBar by binding to the `IsVisible` property.

**Comment by Pottzork** [comment]
I have the same issue where I have to click on a tab to get the binding to work. But I need it to work on first load. 
And I also notice that the binding sets the correct value before view is rendered, but still I need to reload the view to get it to show.
