### ISSUE TITLE
Shell.NavBarIsVisible does not update on hot reload on Android 8

### ISSUE THREAD

**Issue by NoThrottle** [dotnet/maui#7459]
### Description

Shall.NavBarIsVisible is a property that tells the ShellContent whether it should display the Navigation Bar. When you change this between true or false, the change is not immediately reflected. You can modify the Title property from "Home" to anything (e.g "homeawd") and the title will update, but any changes to the navbarisvisible property will still not be reflected. 

For the changes to be reflected, you need to press restart in visual studio (as opposed to hot reload).

I have not tested this in other versions of android, or on other platforms.

### Steps to Reproduce

1. Create a New Project > .NET MAUI App
2. Go to Solution Explorer and open AppShell.xaml
3. Run an Android 8 emulator or connect an Android 8 running device.
4. Run the app on said devices.
5. Add Shell.NavBarIsVisible="False" under ShellContent
6. Save

Nothing should happen to the app

7. Change the Title property from "Home" to anything like "Hello".

It should update and you will see it since the navbar is still visible.

8. Restart the app (Ctrl+Shift+F5 is the default)

Once it's done, you should see the changes to the NavBar be reflected.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8 (API 26)

### Did you find any workaround?

I just do a full restart instead of a hot reload to see the changes.

**Comment by kristinx0211** [comment]
verified repro on android 12 with 17.3.0 Preview 2.0 [32524.359.main].

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on android platform.
![5](https://github.com/dotnet/maui/assets/77434865/a39646c8-8665-4158-86f0-bd8e4e36b227)
