### ISSUE TITLE
ANDROID: apk release version is differ from Debug Mode (GA)

### ISSUE THREAD

**Issue by bautistavirchar** [dotnet/maui#7461]
### Description

as expected UI display in **debug mode** is changing in **release** version of apk this is not a Blazor.

### Steps to Reproduce

1 . Debug mode - display of controls are good
2. Change to Release - margins changed, list view rows of data not properly display
3. As I've observed the results is different.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

I don't get it why Debug mode is working than Release version.

### Relevant log output

```shell
no logs specified.
```

**Comment by drasticactions** [comment]
I'm not sure what you mean by your issue, can you make a repro project showing it?
