### ISSUE TITLE
MediaPicker not working on Windows

### ISSUE THREAD

**Issue by Cywizz** [dotnet/maui#7465]
### Description

I have followed the official documentation [here](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/picker?tabs=windows)

I get Android to open the camera to take a photo just fine.
It is not working on Windows.
The manifest capabilities required for windows (mentioned above) also causes app manifest error (Registration failed)
I tried to use **DeviceCapability Name="microphone"** and **DeviceCapability Name="webcam"** instead which compiled and ran, but the webcam does not activate and a null FileResult is returned from CapturePhotoAsync()

Using VS 2022 Version 17.3.0 Preview 1.1

### Steps to Reproduce

1. Create a new MAUI App
2. Follow capabilities requirements for Windows in above documentation
3. Add code example in above documentation
4. Run app will throw error that Registration of the app failed.
5. Replace capabilities with what I mentioned above and run app
6. Run code which will result in null FileResult being returned.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

### Did you find any workaround?

No

**Comment by janseris** [comment]
Related:
https://github.com/dotnet/maui/issues/6660

**Comment by VincentBu** [comment]
repro with vs main build (32605.41.main). Same deployment error(Registration of the app failed) for me.

**Comment by jfversluis** [comment]
See https://github.com/dotnet/maui/issues/6660#issuecomment-1195227133
