### ISSUE TITLE
Large space above and below Carousel View

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7472]
### Description

On iOS there is large space above and below CarouselView. I am on Stable version of Maui.

### Steps to Reproduce

Run the repro project and see the empty space above and below CarouselView.
[MauiRepro.zip](https://github.com/dotnet/maui/files/8771244/MauiRepro.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on IOS15.4 with above project.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 5.0. Not repro on iOS Platform.
repro project: [MauiRepro.zip](https://github.com/dotnet/maui/files/8771244/MauiRepro.zip)
iOS: 
![image](https://user-images.githubusercontent.com/82450723/236612276-c91dbd51-45ca-498e-8379-bba2987a5d66.png)
