### ISSUE TITLE
Border does not clip when stroke shape is provided in iOS and maccatalyst

### ISSUE THREAD

**Issue by PaulAndersonS** [dotnet/maui#7475]
### Description

Border does not clip and the child gets overlapped.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestApp.MainPage">

    <Grid>
        <Border HeightRequest="200" WidthRequest="200" StrokeThickness="5" Stroke="Red">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="100" />
            </Border.StrokeShape>

            <Image Background="yellow"
                Source="dotnet_bot.png"
                HorizontalOptions="Center">
            </Image>
        </Border>
    </Grid>
</ContentPage>`

![image](https://user-images.githubusercontent.com/42271912/170274732-c6682229-699c-4588-91ae-2c92d5975933.png)

### Steps to Reproduce

Run the attached code snippet in a .NET MAUI application

### Version with bug

.NET MAUI GA

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS15

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/7335
