### ISSUE TITLE
Android does not detect physical devices, emulators do not deploy

### ISSUE THREAD

**Issue by RemcoDEV** [dotnet/maui#7477]
### Description

Visual studio version: 17.3.0 Preview 1.1
MAUI version: GA
I'm converting a Xamarin project to a MAUI project. So far, I've been able to get it working for iOS and Windows, but not for Android.

**Android Emulator**
Debug output states that the app was successfully deployed, while in fact it did not deploy the app. Visual studio basically behaves like 'build' and not deploy.
![Android issue](https://user-images.githubusercontent.com/23697539/170285658-c18a082c-5b0b-434f-9926-da2b6fee89ee.png)

![2022-05-25_16h33_36](https://user-images.githubusercontent.com/23697539/170287779-657f8412-de8f-41cc-93c3-cc8915661cc8.png)

**Android physical device**
So, I thought I'd try it with a physical device. Yet they do not appear as a target.

I've tried various emulators (pixel devices - api 30 & 31) and various physical devices (samsung phone, samsung tablet).
![image](https://user-images.githubusercontent.com/23697539/170288167-7f32f97c-fa10-47f5-b62b-dca7a1956848.png)

### Steps to Reproduce

-

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

At least android 11 and up

### Did you find any workaround?

No. I hope someone can tell me here what the issue is and if there is a workaround :)

**Comment by developer9969** [comment]
I have this issue too , attached physical android device and it's not detected in Version 17.3.0 Preview 1.1

**Comment by jfversluis** [comment]
I assume you have developer mode enabled and you gave permission to actually connect and debug on the device?

Seems this might be a Visual Studio/tooling issue though, which is better if you report through the Help menu. Help > Provide Feedback > Report a Bug.

**Comment by RemcoDEV** [comment]
Hi @jfversluis ,

> Seems this might be a Visual Studio/tooling issue though, which is better if you report through the Help menu. Help > Provide Feedback > Report a Bug.

Probably is indeed. Will do it there. Thanks.
