### ISSUE TITLE
Elements in same layout doesn't response IsVisible changes [iOS][Mac]

### ISSUE THREAD

**Issue by enisn** [dotnet/maui#7482]
### Description

When an element's IsVisible property is changed, other elements' position doesn't change, they stay in the same position.

Let me explain with following gifs. When I try the same scenario in Windows or Android, everything works great. But it doesn't work as expected on iOS and MacOS.

✅ Works fine:

|||
|---|---|
| Windows | Android|
|  ![windows-demo](https://user-images.githubusercontent.com/23705418/170366454-4f4422c5-2040-4ff8-94ed-20249492332d.gif)  | ![android-demo](https://user-images.githubusercontent.com/23705418/170366505-85007eb2-190d-4a3d-9d69-0d3d01c01fa1.gif) |

❌ Doesn't work as expected:

|||
|---|---|
| iOS | MacOS |
| ![ios-demo](https://user-images.githubusercontent.com/23705418/170367140-da914c23-0f3e-4f6b-9489-dac03a5fbeeb.gif) | ![macos-demo](https://user-images.githubusercontent.com/23705418/170366916-3682e6db-aa8f-4f44-ba8e-74bd4484e999.gif) |

### Steps to Reproduce

1. Create a new project.
2. Add 2 elements in the same stacklayout and set a name for the first one.
3. Add a button to the page and set the first element's `IsVisible` as `false`.
4. You'll see, the second element won't go up and stay at the same position.

_You can try the opposite, initialize the first element with IsVisible as false and set IsVisible as true via button. You'll see the second element will be rendered on the first element._

---

Also, I have a repository for my complex situation, you can clone and run `SandboxTreeView` project to reproduce the issue.

https://github.com/enisn/TreeView.Maui

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Unfortunetely.

**Comment by kristinx0211** [comment]
verified repro on ios15.4 with the above peoject.

**Comment by enisn** [comment]
The same problem can be shown there too: https://github.com/dotnet/maui/issues/3410#issue-1054755643
Android elements go up when IsVisible is set false, but ios elements stay

**Comment by AidarNurmukhametov** [comment]
Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue. It has a High priority for us and we do not have a workaround. Thank you for your help

**Comment by AntonKosenkoDX** [comment]
@kristinx0211 Hello! Any update on this issue?

**Comment by enisn** [comment]
@AidarNurmukhametov could you find a workaround?

**Comment by AidarNurmukhametov** [comment]
> @AidarNurmukhametov did you find a workaround?

@enisn No, I don't. Temporary solution was to use another layout, I don't consider that a workaround, result is not the same

**Comment by hartez** [comment]
@AidarNurmukhametov Have you tried updating VS to the latest preview? This may have been fixed in service release 2.

**Comment by enisn** [comment]
I've tested it on version `6.0.486` and couldn't reproduce it. I think this is solved.
