### ISSUE TITLE
The underline of label is not displayed on ios and maccatalyst

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#7486]
### Description

If the initial value of the label text content is empty, the underline is not displayed after the text content is subsequently set.

### Steps to Reproduce

1. Download the demo 
[LabelUnderlineDemo.zip](https://github.com/dotnet/maui/files/8775227/LabelUnderlineDemo.zip)

2. Click both buttons.
3. Observe whether the underlines of the two labels are displayed normally.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15.4, iOS 15.5

**Comment by kristinx0211** [comment]
verified repro on ios15.4 with above project.

**Comment by rkops-bd** [comment]
This issue is still not working (. @jfversluis Any idea when this will be fixed?

**Comment by frantisekvojtech** [comment]
Same issue with TextDecorations of type strikethrough. The label is not crossed out on iOS, after the biding content is set.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0. Can repro on iOS platform with above project.
[LabelUnderlineDemo.zip](https://github.com/dotnet/maui/files/8775227/LabelUnderlineDemo.zip)

**Comment by mattleibow** [comment]
Verified this is now fixed in .NET 8
