### ISSUE TITLE
LinearGradientBrush overflow button  making CornerRadius invisible

### ISSUE THREAD

**Issue by cris-m** [dotnet/maui#7488]
### Description

When button Background is set to `LinearGradientBrush`  the button `CornerRadius` become invisible. Here is an example:

```xaml
<Button  
       Text="Next"
       BorderWidth="10"
       WidthRequest="300"
       HeightRequest="70"
       BorderColor="#e5e5e5"
       CornerRadius="20">
      <Button.Background>
           <LinearGradientBrush StartPoint="0,0" EndPoint="0,1">
                  <GradientStop Color="#5B93F5" Offset="0.1"/>
                  <GradientStop Color="#6253BF" Offset="1"/>
              </LinearGradientBrush>
      </Button.Background>
</Button>
```
The above `xaml` code result is the following:

<img width="371" alt="Screen Shot" src="https://user-images.githubusercontent.com/29815096/170399338-1e97aaec-624e-4245-8441-ed640dd6025a.png">

### Steps to Reproduce

1. Create a button
2. Set background property to  `LinearGradientBrush`.
3. Set `CornerRadius` property.
4. Set `BorderColor` and `BorderWidth` on the button to see if the button have radius corner

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS, Android

### Affected platform versions

Android 11 and up, iOS15

**Comment by VincentBu** [comment]
not repro on with vs main build(32525.350.main)

**Comment by jsuarezruiz** [comment]
> not repro on with vs main build(32525.350.main), but the round corner on Android looks different from that on IOS: CornerRadius="50"
> 
> on Android: ![image](https://user-images.githubusercontent.com/44959937/170423960-e2fad4c9-bb3f-4830-a40b-c0eae18ff687.png)
> 
> on IOS: ![image](https://user-images.githubusercontent.com/44959937/170423834-574c33d9-fb50-4d1f-b74a-4efbaed90d41.png)

The Button CornerRadius difference will be fixed by https://github.com/dotnet/maui/pull/7215
