### ISSUE TITLE
The indicatorView render outside of border

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7493]
### Description

I defined a CarouselView and Indicator view. They are both the child of VerticalStackLayout. The VerticalStackLayout is the Child of Border. But the Indicator View remains outside of border on iOS. 

### Steps to Reproduce

Run the repro project. Scroll down and see the indicatorview at the bottom of the screen outside of border.
[MauiRepro.zip](https://github.com/dotnet/maui/files/8778151/MauiRepro.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/7335
