### ISSUE TITLE
Grid measures and layouts itself and children incorrectly

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#7499]
### Description

Hello, I am developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/), and I experienced a bug described below. It has moderate severity.

### Steps to Reproduce

1. Create a Maui app
2. Put Grid with two rows: 
```xaml
    <Grid RowDefinitions="*,Auto" HeightRequest="70" BackgroundColor="Yellow" VerticalOptions="Center" RowSpacing="0">
        <BoxView HeightRequest="200" BackgroundColor="Red"/>
        <BoxView Grid.Row="1" HeightRequest="5" BackgroundColor="Green"/>
    </Grid>
```
3. Run app on Android or iOS

### Expected Behavior
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-26 at 17 05 50](https://user-images.githubusercontent.com/41049348/170493462-99c363e3-bf9c-4263-a759-c2d9b1f3bb1b.png)

### Actual Behavior
Grid has incorrect size

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-26 at 16 32 09](https://user-images.githubusercontent.com/41049348/170493479-02775f7e-2a58-48df-8f4e-89925ff16477.png)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 Android 11

**Comment by VincentBu** [comment]
I'm using vs main (32526.619.main) and I only see a black block:
![image](https://user-images.githubusercontent.com/44959937/170650399-c487c90c-4140-4b99-8552-9583b027c0f6.png)

I will validate it again if there is a new build.

**Comment by ToolmakerSteve** [comment]
I see that Row 0 has content (red boxview) that asks for 200 height.

Is it spec'd that a container's HeightRequest will always constrain its children?

Or does the child asking for more height, cause the grid height to grow?

**Comment by AntonKosenkoDX** [comment]
@VincentBu Hello! Any update on this issue?

**Comment by VincentBu** [comment]
still get a black block on side
![image](https://user-images.githubusercontent.com/44959937/175896935-67ba6831-ad29-4d2a-8d95-0f76dc30017a.png)

**Comment by hartez** [comment]
Once #8720 is released, the markup above will produce the correct results. However, you'll need to add `IsClippedToBounds="True"` to the Grid, because the BoxView's height exceeds the Grid's.
