### ISSUE TITLE
[Enhancement] Please prioritize minimizing application startup speed

### ISSUE THREAD

**Issue by Happypig375** [dotnet/maui#75]
This is a long-standing issue of Xamarin.Forms - we all saw the native apps that start in less than 1 second which cannot ever be achieved by Xamarin.Forms. Please prioritize minimizing application startup speed!

**Comment by JohnH-FF** [comment]
Do you mean startup time on Android? I definitely agree, they are appalling, especially on legacy devices.
But our XF apps on iOS, MacOS and UWP all start up sub second, thankfully.

**Comment by Happypig375** [comment]
Yes

**Comment by JonDouglas** [comment]
@Happypig375 We are consistently delivering startup speed performance on platforms like Android. For example, a recent feature to bring startup speed from 4.8s -> 1.9s without a huge APK size bloat.

https://devblogs.microsoft.com/xamarin/faster-android-startup-times-with-startup-tracing/

We will continue to invest in these areas as we are making significant progress to that 1s milestone.
