### ISSUE TITLE
Getting a XamlC error when trying to use common xmlns only in XAML without x:Name

### ISSUE THREAD

**Issue by vvgeorgiev** [dotnet/maui#7503]
### Description

I am creating custom controls in a library assembly. I have added XmlnsDefinition for the corresponding namespaces. If I use the controls in XAML and if I do not set x:Name, I get the following compile time error:
XamlC error XFC0000: Cannot resolve type "http://schemas.mycompany.com/2022/xaml/maui:prefix:MyControl".
If I set x:Name in the page, where the controls are used -- it works, if I use the controls in code behind in addition to XAML -- it works.

### Steps to Reproduce

1. Rebuild the attached solution
2. Observe the error: 
`XamlC error XFC0000: Cannot resolve type "http://schemas.mycompany.com/2022/xaml/maui:prefix:MyControl"`
[MauiXmlnsRepro.zip](https://github.com/dotnet/maui/files/8779666/MauiXmlnsRepro.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A - compile-time issue

### Did you find any workaround?

Setting x:Name in the page fixes it, but it is outside my control as a component vendor.

**Comment by StephaneDelcroix** [comment]
Looks like a linking issue. Adding x:Name creates a ref that prevents linking out. I’ll investigate further

**Comment by VincentBu** [comment]
repro with vs main build(32606.310.main)

**Comment by StephaneDelcroix** [comment]
not a trimming/linking option.

**Comment by pictos** [comment]
Just a reminder, in order to use the custom-schema, generated by `XmlnsDefinition` you need to have some C# code that references the lib. More info [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/custom-namespace-schemas#consuming-a-custom-namespace-schema).

After adding ` _ = new RadioButton();  _ = new RadGauge();` in the code I was able to run, but for some reason the `RadioButton` still fails, not sure if it's because you have the same custom schema for two different assemblies

**Comment by StephaneDelcroix** [comment]
The workaround pointed by @pictos works: adding a code reference to each assembly (not each type) solve the issue. But the intent of this workaround, and documentation, was to prevent linking for runtime-inflated Xaml. With Maui, Xaml Compilation is enforced for Release builds, and we could get rid of this requirement.

So, not a new error, but I'm still investigating if we can get rid of it...

**Comment by bijington** [comment]
@StephaneDelcroix if you can improve on this issue that would be fantastic. I have seen a few projects where people make use of the .NET MAUI Community Toolkit via library projects and without C# directly accessing the components they need they see this issue.

I would be more than happy to provide any details/assistance on this.

**Comment by mrlacey** [comment]
Also get this if use a Map with no other properties set.

e.g.:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:vm="clr-namespace:EmulatorApp6.ViewModels"
			 x:Class="EmulatorApp6.Views.MapPage"
			 x:DataType="vm:MapViewModel">

	<Map />
</ContentPage>
```

```ascii
1>        Done building project "App6.csproj" -- FAILED.
1>        Views\MapPage.xaml(8,3): XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2021/maui:Map".
```

**Comment by NasTheRobotKing** [comment]
I also get this issue all over the place after converting my .NET Xamarin project to MAUI. Any resolution? 

![image](https://user-images.githubusercontent.com/73680975/218218549-1b04433c-b15f-4e27-8f9a-a223e42b267a.png)

**Comment by jonathanpeppers** [comment]
I tried the original example (upgraded to .NET 7):
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:telerik="http://schemas.telerik.com/2022/xaml/maui"
             x:Class="MauiApp14.MainPage">
    <Grid>
        <telerik:RadButton></telerik:RadButton>
        <telerik:RadGauge></telerik:RadGauge>
    </Grid>
</ContentPage>
```
And XamlC emits this in `Release` mode on Android:
```csharp
private void InitializeComponent()
{
	RadButton radButton = new RadButton();
	RadGauge radGauge = new RadGauge();
	Grid grid = new Grid();
	MainPage mainPage;
	NameScope value = (NameScope)(NameScope.GetNameScope(mainPage = this) ?? new NameScope());
	NameScope.SetNameScope(mainPage, value);
	grid.Children.Add(radButton);
	grid.Children.Add(radGauge);
	mainPage.SetValue(ContentPage.ContentProperty, grid);
}
```

Which looks right to me.

But then I get a crash at runtime because the handler is missing:
```
04-13 16:52:39.305  8175  8175 I MonoDroid: android.runtime.JavaProxyThrowable: Microsoft.Maui.Platform.HandlerNotFoundException: Handler not found for view MauiLib.Controls.RadButton.
```

So yeah, there might be something fundamental here. Why is `MauiLib.Controls.dll` even trimmed at all in this example?

**Comment by jonathanpeppers** [comment]
Oh, Debug mode crashes in the same way. Does someone have a more recent repro?

I am not getting a XamlC error using the latest stable MAUI.
