### ISSUE TITLE
Resx file does not produce designer file, application is crashing

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#7504]
### Description

Hello there!

I'm in the process of migration TaskLoaderView to MAUI, it was going alright till I launch the app for the first time.
It crashed right after the Splashscreen.
It was complaining about my resx file (located in `Resources\Localization\SampleResources.resx`), not being embedded in the resources...
After that I tried a few things, and now it seems even worst: it crashes **before** the splash, when loading resources assemblies:

```
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/Retronado.Maui.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-US/Retronado.Maui.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/Retronado.Maui.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/Retronado.Maui.resources.dll
[.retronado.mau] * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:456
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9031 (.retronado.maui), pid 9031 (.retronado.maui)
```

I think it is related to the resx file, cause It fails to generate the design file when building the project on Rider EAP AND on VS Mac Preview.

### Steps to Reproduce

Here is the repo sample:

https://github.com/roubachof/Sharpnado.TaskLoaderView/tree/failing-resx

* Project is `Retronado.Maui`
* The resx is `Resources\Localization\SampleResources.resx`

### Version with bug

6.0 (current)
VS for Mac preview 17.3 build 191

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 21 and up, probably iOS, since resx doesn't generate anything

### Did you find any workaround?

nope

**Comment by VincentBu** [comment]
verified with with vs main (32526.500.main)
it works fine on Android emulator:
![image](https://user-images.githubusercontent.com/44959937/170638153-74af9de7-5e92-46df-a48a-813e73d6f7cb.png)

**Comment by roubachof** [comment]
Sorry I forgot to say that the project that is crashing is:

Project is Retronado.Maui
The resx is Resources\Localization\SampleResources.resx

I edited the issue

**Comment by VincentBu** [comment]
whoops! my bad. repro on android emulator, the app also crashed on IOS emulator
![image](https://user-images.githubusercontent.com/44959937/170648481-e383de4e-fa7b-4f50-8fa2-44f4b9a2547c.png)

**Comment by drasticactions** [comment]
@roubachof Did you try moving the resx files into a different directory besides under `Resources`?

**Comment by roubachof** [comment]
@drasticactions yes, at the beginning, the resx was in the `Localization` directory, directly at the project's root.

**Comment by drasticactions** [comment]
Have you tried making an iOS app without MAUI (ex. `dotnet new ios`) and trying the same thing? does it work there?

**Comment by pictos** [comment]
Maybe it's related to #1855 ?

**Comment by roubachof** [comment]
@drasticactions the android app launches successfully in this case, with the same resx file.
But like the MAUI single project file, it fails to generate the designer file from the resx file
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/596903/170760015-b50bdf43-efad-44c6-a944-4acc4853203d.png">

**Comment by roubachof** [comment]
created a branch for this issue: https://github.com/roubachof/Sharpnado.TaskLoaderView/tree/failing-resx

**Comment by PureWeen** [comment]
@jonathanpeppers does this ring any bells?

**Comment by jonathanpeppers** [comment]
So does the app crash and/or the `.resx` file doesn't work at runtime on Android?

The Xamarin sample for `.resx` looks a bit different:

https://github.com/xamarin/xamarin-forms-samples/blob/0a9d148ef06fae1e99b8bf080c0abfbad3df746b/UsingResxLocalization/UsingResxLocalization/UsingResxLocalization/UsingResxLocalization.csproj#L42-L45

We have tests similar to this in xamarin/xamarin-android, that the built-in `.resx` support works ^^

If the Sharpnado sample uses:

```xml
<None Include="Localization\SampleResources.resx">
  <UseVocaDbResManager>true</UseVocaDbResManager>
  <GenerateResource>false</GenerateResource>
  <Generator>ResXFileCodeGenerator</Generator>
</None>
<!-- ... -->
<PackageReference Include="VocaDb.ResXFileCodeGenerator" Version="3.1.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

Does this VocaDb package just have an issue with MAUI / .NET 6 projects?

**Comment by roubachof** [comment]
@jonathanpeppers :)
you are not looking at the correct branch, this is the master where I'm trying to workaround this issue.
The original branch is here: https://github.com/roubachof/Sharpnado.TaskLoaderView/tree/failing-resx

**Comment by jonathanpeppers** [comment]
So the error is:
```
System.Resources.MissingManifestResourceException: Could not find the resource "Sample.Localization.SampleResources.resources" among the resources "Retronado.Maui.Resources.Localization.SampleResources.resources", "Retronado.Maui.App.xaml", "Retronado.Maui.MainPage.xaml", "Retronado.Maui.Platforms.Windows.App.xaml", "Retronado.Maui.Resources.Styles.Colors.xaml", "Retronado.Maui.Resources.Styles.Global.xaml", "Retronado.Maui.Resources.Styles.Icons.xaml", "Retronado.Maui.Resources.Styles.Sizes.xaml", "Retronado.Maui.Resources.Styles.StylesGameView.xaml", "Retronado.Maui.Resources.Styles.Text.xaml", ... embedded in the assembly "Retronado.Maui", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
```
I see the `.resources` file in here with a different name:
![image](https://user-images.githubusercontent.com/840039/176772431-58488f3f-ece4-4265-9ab7-96bb3c8f79e2.png)

The file in there matches the `$(RootNamespace)` of this project:
```xml
<EmbeddedResource Update="Resources\Localization\SampleResources.resx">
```

Are you somehow bringing in the source code for this class within this assembly?

![image](https://user-images.githubusercontent.com/840039/176772537-f451d72f-4659-4a28-8d30-693441c76e6a.png)

I don't really understand how these projects are setup, but it looks like `Samples.csproj` is expecting the `.resources` file to be named based on its `$(RootNamespace)`. Your app has the `$(RootNamespace)` of `Retronado.Maui`.

We have some tests in .NET 6 for `.resx`, so it seems like they are generally working:

https://github.com/xamarin/xamarin-android/blob/main/tests/Mono.Android-Tests/Localization/LocalizationTests.cs

**Comment by pierre01** [comment]
I have the same issue!

**Comment by pierre01** [comment]
> I have the same issue!

(This issue was fixed - for me)

**Comment by jfversluis** [comment]
I think this was fixed, if not, please let us know!
