### ISSUE TITLE
Unable to run MAUI app after updating to the latest version

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#7505]
### Description

Installed the latest version of the MAUI and trying to run on VS MAC preview 
**Error info**
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets : warning MSB4011: "/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" cannot be imported again. It was already imported at "/Users/developer/Projects/ew/ew/ew.csproj". This is most likely a build authoring error. This subsequent import will be ignored. 
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets : warning MSB4011: "/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets" cannot be imported again. It was already imported at "/Users/developer/Projects/ew/ew/ew.csproj". This is most likely a build authoring error. This subsequent import will be ignored. 
**/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.402/targets/Xamarin.Shared.Sdk.targets(1739,3) : error: The RuntimeIdentifier 'win-x64' is invalid.**
Unable to create package spec for project. '/Users/developer/Projects/ew/ew/ew.csproj'

Version Info

Version 17.3 Preview (17.3 build 191)
Installation UUID: e4819864-6148-4666-9a02-b7322f3b64b7

Runtime
.NET 6.0.3 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.2.0-3.22181.8+a59a22c6f3c2cc1883e20cece412209f18f4a29f

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.300/Sdks
SDK Versions:
	6.0.300
	3.1.419
MSBuild SDKs: /usr/local/share/dotnet/sdk/6.0.300/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.5
	3.1.25

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.3.99.58 (Visual Studio Enterprise)
Commit: xamarin-android/main/64b22fc
Android SDK: /Users/developer/Library/Android/sdk
	Supported Android versions:
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: adf1bc4
Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.38.2@7b1e016
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.47
Hash: d6dd135
Branch: remotes/origin/dev/tondat/main-1512059~2
Build date: 2022-05-19 16:01:17 UTC

Android Device Manager
Version: 0.0.0.1127
Hash: 4bb4d48
Branch: remotes/origin/dev/tondat/main-1536295~1
Build date: 2022-05-19 16:01:17 UTC

Apple Developer Tools
Xcode 13.3.1 (20103)
Build 13E500a

Xamarin.Mac
Version: 8.10.0.1 (Visual Studio Enterprise)
Hash: 568bdb24e
Branch: d17-2
Build date: 2022-04-08 18:52:56-0400

Xamarin.iOS
Version: 15.10.0.1 (Visual Studio Enterprise)
Hash: 568bdb24e
Branch: d17-2
Build date: 2022-04-08 18:52:57-0400

Xamarin Designer
Version: 17.3.0.70
Hash: 4cf1a2208
Branch: remotes/origin/d17-3
Build date: 2022-05-19 16:01:22 UTC

Build Information
Release ID: 1703000191
Git revision: 6e028abf3763bf8fde618c0de2c24b1091eb76d8
Build date: 2022-05-19 15:59:07+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.3.1

As per the project file there is no  RuntimeIdentifier 'win-x64' in project. 

Can anybody help me on that is happening and why we are trying to install or searching for a win-x64 target in MAC. 

### Steps to Reproduce

1. Create a MAUI app and try to run the same 
2. No additional setup required 
3. Not even working with default template for MAUI

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All platforms

### Did you find any workaround?

No

**Comment by liveinvarun** [comment]
Any update on the why this issue happens- I tried reinstalling VS 2022 preview and then also no change.

**Comment by VincentBu** [comment]
not repro with vs main build. @justadaniel, @liveinvarun , can updating the vs(if there is update available) fix this issue?

**Comment by justadaniel** [comment]
I tried updating and there wasn't an update available, however now all of a sudden it is fixed. Maybe it has to do with nuget packages on the servers possibly being cached?

**Comment by VincentBu** [comment]
I'm not familiar with VS Mac, according to **Error info**, it looks like a wrong RuntimeIdentifier(RID) is selected? 
Anyway, the vs works well, let me close this issue for now. If you run into the same error in the future, feel free to open a new issue.
