### ISSUE TITLE
can maui execute code using interperter mode for upload app to appstore?

### ISSUE THREAD

**Issue by srxqds** [dotnet/maui#7516]
### Discussed in https://github.com/dotnet/maui/discussions/7340

<div type='discussions-op-text'>

<sup>Originally posted by **srxqds** May 20, 2022</sup>
will maui can use interperter mode to upload app to appstore?</div>

**Comment by Eilon** [comment]
To distribute iOS applications in the Apple App Store, you will need to use Ahead of Time (AOT) compilation for the app. Other platforms and app stores support Just In Time (JIT) compilation and/or interpretation.

If you try to distribute a non-AOT app to the Apple App Store, I believe they will reject the submission.

**Comment by srxqds** [comment]
why, the interpreter and aot are not jit, not generate native code in runtime.

**Comment by srxqds** [comment]
how can apple appstore check the execute mode between interpreter or aot?

**Comment by Eilon** [comment]
> why, the apple app store forbids dynamic code generated, but the interpreter and aot are not jit, not generate native code in runtime.

I tried finding more info on this and I'm not so sure anymore if what I said was correct. The iOS App Store doesn't allow _downloading_ code for execution, but it seems it might be OK to use interpretation for code that is already part of the app. See https://developer.apple.com/app-store/review/guidelines/, section 2.5.2.

> How apple appstore detect the difference between aot and interpreter, the aot and interpreter are the same for them?

I'm not sure. It's probably a proprietary technique that Apple uses.

But, either way, this is likely a question for individual App Stores, and not a question for MAUI directly.

**Comment by srxqds** [comment]
ok, thank you
