### ISSUE TITLE
[Bug] Strange Border with StrokeThickness and Clipped Content

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#7521]
### Description

Hello,

Borders StrokeThickness does not have the same width between iOS and Android.

Android seems to not have a perfect interior line rounded 
iOS seems ok, but it put an extract padding on the left image

PS: Right Image has a negative padding to see the clip issue, but it's a known issue #7576 #6986
--------------------------Android------------------------------------------------------------ iOS-------------------------
![Screenshot 2022-05-27 at 17 26 03](https://user-images.githubusercontent.com/4518686/170730360-e10461a0-9091-44ab-9621-428e5fdbf919.png)

### Steps to Reproduce

1. Create a new Border
2. Put as a Content a Grid with some stuff in it (Images ,etc..)
3. Use a RoundRectangle as Border.StrokeShape with different CornerRadius to see the result.

--------------------------iOS------------------------------------------- Android-------------------------
![Screenshot 2022-05-27 at 13 08 20](https://user-images.githubusercontent.com/4518686/170688280-cd9baee1-63cc-4014-81bb-ae9e7fffec24.png)
````
                <Border StrokeThickness="20"
                        Stroke="Silver"
                        Background="White"
                        Margin="0"
                        Padding="0">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="30" />
                    </Border.StrokeShape>
                    <Grid HeightRequest="30" BackgroundColor="Green">
                        <StackLayout Orientation="Horizontal">
                            <Frame Padding="0" HasShadow="false"
                                   BackgroundColor="Maroon"
                                   CornerRadius="20"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                            <Label Text="Parameters"
                                   VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                   FontSize="Medium" FontFamily="Bold"
                                   HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
                            <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
                                   BackgroundColor="Blue"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                        </StackLayout>
                    </Grid>
                </Border>
````

### Expected Behavior
![Screenshot 2022-05-27 at 17 22 38](https://user-images.githubusercontent.com/4518686/170730046-02232195-82e3-41f7-843a-06f70e7f133a.png)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

MAUI 6.0.312

**Comment by kristinx0211** [comment]
@Phenek thanks for your report, could you provide a sample project/screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by Phenek** [comment]
Hello,

I updated the issue I provide you the Xaml sample.
No need an entire project, just copy and past

````
                <Border StrokeThickness="20"
                        Stroke="Silver"
                        Background="White"
                        Margin="0"
                        Padding="0">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="30" />
                    </Border.StrokeShape>
                    <Grid HeightRequest="30" BackgroundColor="Green">
                        <StackLayout Orientation="Horizontal">
                            <Frame Padding="0" HasShadow="false"
                                   BackgroundColor="Maroon"
                                   CornerRadius="20"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                            <Label Text="Parameters"
                                   VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                   FontSize="Medium" FontFamily="Bold"
                                   HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
                            <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
                                   BackgroundColor="Blue"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                        </StackLayout>
                    </Grid>
                </Border>
````

-------------------------iOS------------------------------------------------------Android--------------------
![Screenshot 2022-05-27 at 13 08 20](https://user-images.githubusercontent.com/4518686/170688280-cd9baee1-63cc-4014-81bb-ae9e7fffec24.png)

**Comment by kristinx0211** [comment]
can be reproduced on android with above code.

**Comment by jsuarezruiz** [comment]
Tried with the latest version and the result on Android is the following:

![Screenshot_1656586810](https://user-images.githubusercontent.com/6755973/176661501-d0e2810d-e7ab-480c-9b83-1613a5fb2013.png)

Is the expected one right?. On iOS the current version is not clipping the content, have been fixed by  https://github.com/dotnet/maui/pull/7335 and will be available in the upcoming version.

**Comment by Phenek** [comment]
Hey @jsuarezruiz Glad to see that coming

You choose to use inside border overlaping the content of the same size.
I think it's the best compromise, it leaves us the choice to put a padding to the content as we wish.

Thx

**Comment by Phenek** [comment]
@jsuarezruiz Glad to see that coming!

I see you choose an inside border that overlap the content.
I think it's the best compromise, it let us the choise to make a padding on the content of the size of the border or as we wish.

I just removed the green background and found this on Android, 
![Screenshot 2022-06-30 at 23 16 23](https://user-images.githubusercontent.com/4518686/176779693-d7f34a72-5818-4b0a-ab5c-b01f2807f2cb.png)
We are not so far from the perfect behavior!
````
                <Border StrokeThickness="10"
                        Stroke="Silver"
                        Background="White"
                        Margin="0"
                        Padding="0"
                        HeightRequest="60">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="30" />
                    </Border.StrokeShape>
                    <Grid HeightRequest="30">
                        <StackLayout Orientation="Horizontal" HeightRequest="30">
                            <Frame Padding="0" HasShadow="false"
                                   BackgroundColor="Maroon"
                                   CornerRadius="20"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                            <Label Text="Parameters"
                                   VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                   FontSize="Medium" FontFamily="Bold"
                                   HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
                            <Frame Padding="0" HasShadow="false" CornerRadius="0"
                                   BackgroundColor="Blue"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                        </StackLayout>
                    </Grid>
                </Border>
````

**Comment by Phenek** [comment]
@jsuarezruiz So here a little update on the issue,
this is inside a StackLayout with 0 spacing.
---------------------------iOS--------------------------|-----------------------Android---------------------
![Screenshot 2022-07-09 at 11 09 52](https://user-images.githubusercontent.com/4518686/178099463-dfb70760-47f4-4fe8-882c-49e17caa8c49.png)
