### ISSUE TITLE
ScrollView Orientation dynamic change not working in Android

### ISSUE THREAD

**Issue by karthikraja-arumugam** [dotnet/maui#7523]
### Description

Changing scroll view orientation in runtime is not affected in view. If we have horizontal orientation on view loading and changing orientation to vertical in runtime the vertical scrolling is not working. 

### Steps to Reproduce

1. Run the attached sample. Note horizontal scroll is enabled.
2. Scroll horizontally. Works as expected.
3. Click the change orientation button. It will change the scroll orientation to vertical.
4. Now scroll vertically and it won't work.

Note: Vertical scroll works after changing the device orientation. Please refer the attached video

https://user-images.githubusercontent.com/92788387/170629772-4e1c720a-2cd4-43de-b024-fb43f45c497f.mp4

[MAUITestApp.zip](https://github.com/dotnet/maui/files/8783921/MAUITestApp.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10.0

### Did you find any workaround?

If we reset the content of the scroll view after changing the orientation it works.

### Relevant log output

```shell
NA
```

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0, Not repro on Android platform with above project. 
[MAUITestApp.zip](https://github.com/dotnet/maui/files/11438608/MAUITestApp.zip)
![ScrollView](https://github.com/dotnet/maui/assets/77434865/65134bcd-b0da-4cf1-a9d4-52b0b30b8bb8)
