### ISSUE TITLE
Border does not grow when editor inside it grows

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7524]
### Description

Given the following XAML

```
 <Border Stroke="Black" StrokeThickness="2" StrokeShape="RoundRectangle 20" Padding="10" HorizontalOptions="Center" VerticalOptions="Center">
        <Editor WidthRequest="200" Placeholder="Text here" AutoSize="TextChanges"></Editor>
    </Border>
```
If you enter a new line the border will not grow in iOS.

### Steps to Reproduce

Enter the  XAML in Description in a content page. Run the project on iOS. Enter text and press enter key.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
verified repro on IOS 15.4 with vs 17.3.0 Preview 2.0 [32601.361.main].
![image](https://user-images.githubusercontent.com/99457000/171542789-68db6ab0-d68f-4e43-b226-8bcd425748ee.png)

**Comment by varyamereon** [comment]
I have noticed this as a problem in general, if the layout/control inside the Border changes size for whatever reason the Border just clips the content and does not resize with it.

**Comment by jsuarezruiz** [comment]
Need to vaidate it with net6.0 branch on iOS. On Android is working as expected.

![fix-7524](https://user-images.githubusercontent.com/6755973/178313083-9df787e2-6b22-4b5b-a84b-1ad042b44fef.gif)

**Comment by hartez** [comment]
I suspect that this issue and #8923 have the same root cause.

**Comment by rmarinho** [comment]
This is fixed in the latest stable version. Just tested with 7.0.52.
