### ISSUE TITLE
No documentation for Maui-specific tags introduced in .csproj projects

### ISSUE THREAD

**Issue by coolbluewater** [dotnet/maui#7525]
### Description

Maui introduces these tags in the .csproj format: `<UseMaui>`, `<SingleProject>`.

I could not find any official documentation for these tags. I need to know how they work at a low level. Currently I'm doing a lot of guesswork about the side effects of these tags.

Please add docs in the body of this issue, and also to your official docs.

### Steps to Reproduce

See above

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by mattleibow** [comment]
I believe this is documented here: https://docs.microsoft.com/dotnet/maui/user-interface/images/app-icons

If there are missing docs, please open an issue using the feedback link at the bottom of the page.
