### ISSUE TITLE
[Bug] iOS Layout doesn't resize on rotation

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#753]
### Description

When rotating on iOS, layouts rotate but don't resize properly to fill the screen. Android works as expected tho.

![Simulator Screen Shot - iPhone 12 - 2021-04-15 at 12 35 43](https://user-images.githubusercontent.com/41873/114915723-8d63c980-9de9-11eb-8f62-4ac710ea1cfc.png)

![Simulator Screen Shot - iPhone 12 - 2021-04-15 at 12 51 13](https://user-images.githubusercontent.com/41873/114915702-83da6180-9de9-11eb-914f-48a8752b38d0.png)

### Basic Information

- Version with issue: preview 3
- Platform Target Frameworks: 
  - iOS:  12.4

### Reproduction Link

https://github.com/davidortinau/LayoutLab

**Comment by davidortinau** [comment]
Android screenshots

![Screenshot_1618456276](https://user-images.githubusercontent.com/41873/114916387-580bab80-9dea-11eb-95ff-8d28384c0ed6.png)
![Screenshot_1618456272](https://user-images.githubusercontent.com/41873/114916389-580bab80-9dea-11eb-8d8c-15abd2deadc9.png)

**Comment by hartez** [comment]
This was fixed by #812.
