### ISSUE TITLE
ListView crashes on scrolling through 9,100 items

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7530]
### Description

Got a listview with over 9,100 items. Application crashes when scrolling through the very first items. See video below.

There are hundred of lines in VS output but the following might be the ones of interest?

```
Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer found for Microsoft.Maui.Controls.ViewCell is incompatible
[ns.testapp] java_vm_ext.cc:579]  ---> Java.Lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference
```

```
java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception android.runtime.JavaProxyThrowable: Microsoft.Maui.Platform.ToPlatformException: Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer found for Microsoft.Maui.Controls.ViewCell is incompatible
[ns.testapp] java_vm_ext.cc:579]  ---> Java.Lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference
[ns.testapp] java_vm_ext.cc:579]    at Java.Interop.JniEnvironment.StaticMethods.CallStaticVoidMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 13250
[ns.testapp] java_vm_ext.cc:579]    at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeVoidMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 41
[ns.testapp] java_vm_ext.cc:579]    at Microsoft.Maui.PlatformInterop.RequestLayoutIfNeeded(View view) in D:\a\_work\1\s\src\Core\src\obj\Release
et6.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 421
```

### Steps to Reproduce

https://user-images.githubusercontent.com/14368203/170691484-cca626ea-8503-4078-8b2e-9262d5df14e6.mp4

[Repro.zip](https://github.com/dotnet/maui/files/8786330/Repro.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, API 31, Pixel 5 Android Emulator

**Comment by PureWeen** [comment]
This will be fixed by the following [PR](https://github.com/dotnet/maui/pull/7485) for SR1

If it's still broken for you on SR1 we can re-open

**Comment by Symbai** [comment]
Well its a major bug, can't you at least test if the PR really fixes it? I would have to wait for SR1 and if its still broken I have to wait another time but this bug currently blocks me from releasing my app to the app stores.

Or if there is  ANY way I can use a nightly build or something with this PR included then please let me know.
