### ISSUE TITLE
Measure not working correctly on Layouts with fixed size constraints

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#7531]
### Description

Calling `Measure` on `Layout` controls with size constraints that are finite numbers returns some surprising results. For example, let's say we measure a `Grid` with size constraints of 1000x1000 pixels. The `Measure` method of the `Grid` would almost always return a desired size of 1000x1000 pixels, regardless of the actual `Grid` contents. In contrast, calling `Measure` on the same `Grid` with constraints of `double.PositiveInfinity` would return the correct size, which can be smaller.

This is not consistent with how `Measure` works for other controls, e.g. `Label`, `Button` etc. For instance, calling `Measure` on a `Label` with size constraints of 1000x1000 pixels would always return the correct size of the `Label`. In fact, calling `Measure` with fixed size constraints vs `double.PositiveInfinity` would make any difference only if the text is too long and need to be wrapped. I believe this is the correct and intended behavior.

I am not certain whether the current behavior of `Measure` on `Layout` controls is intentional or not. My point is, this odd (mis)behavior breaks the .NET MAUI layout system in so many ways it is not even pretty. Imagine the pain of a control vendor trying to implement a custom layout strategy for some control, when calling `Measure` on the children does not return the correct size reliably. The typical such implementation is full of ugly hacks and workarounds, often requiring to call `Measure` multiple times with different size constraints to figure out the correct size.

### Steps to Reproduce

Download and run the attached sample test project.

[TestApp.zip](https://github.com/dotnet/maui/files/8786326/TestApp.zip)

The project contains a `Grid` with a `Label` we are going to measure.

1. Tap the `Measure Label with Infinity` button: the `Label` returns some small desired size, e.g. 100x19 pixels.
2. Tap the `Measure Label with Size` button: the `Label` returns the same small desired size, e.g. 100x19 pixels.
3. Tap the `Measure Grid with Infinity` button: the `Grid` returns the same small desired size, e.g. 100x19 pixels.
4. Tap the `Measure Grid with Size` button: the `Grid` returns the passed size constraints as desired size.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

### Did you find any workaround?

The workaround is not pretty and very error-prone, often requiring to call `Measure` multiple times with different constraints. Please, keep in mind that the `Layout` remembers the last measured size in the `DesiredSize` property and uses that during `Arrange`, often ignoring what is passed as a bounding rectangle. This can cause strange, unpredictable results sometimes, as the final layout size is not known during the `Measure` phase, but is available during the `Arrange` phase only. Of course, calling `Measure` again during `Arrange` is a common hack, but crashes with a layout loop on Windows, unfortunately. ;-)

**Comment by ivan-todorov-progress** [comment]
I am not certain if the following bug is somehow related to this one: https://github.com/dotnet/maui/issues/7535

**Comment by ToolmakerSteve** [comment]
Despite the names "widthConstraint" and "heightConstraint" on Measure, the values sent from XAML are WidthRequest and HeightRequest. Which has a very different meaning.

If change how Measure interprets its parameters, at minimum, any current overrides people have might behave differently.

Seems to me any proposed change would require a lot of testing, not just of Maui internal code, but of third party vendors.

**Comment by ivan-todorov-progress** [comment]
> Measure parameters "widthConstraint" and "heightConstraint", in XAML are WidthRequest and HeightRequest.
> 
> Are we sure those always mean the same thing as a "max size" constraint?

If that is correct, it seems very confusing to me that calling `Measure` is a means to specify `WidthRequest` and `HeightRequest`, which are then respected during `Arrange`. Please, check my other issue: https://github.com/dotnet/maui/issues/7535.

My current workaround to avoid this misbehavior is something like the following (assume a layout strategy similar to the one in `VerticalStackLaout`):

```charp
// Measure with infinity first to stack the items vertically.
// We cannot use heightConstraint here, as that would make
// the view occupy the entire available space.
var desiredSize = view.Measure(widthConstraint, double.PositiveInfinity);

// Re-measure with the actual size to avoid odd behavior on arrange.
desiredSize = view.Measure(widthConstraint, desiredSize.Height);
```

**Comment by ivan-todorov-progress** [comment]
As a final thought: try to implement `LayoutOptions.FillAndExpand` for `HorizonalStackLaout` and `VerticalStackLaout`, which are currently not supported. I am sure you'll see the problem immediately - it is not possible with the current scheme, when `Measure(100, 100)` means: "use `WidthRequest = 100` and `HeightRequest = 100` for the next `Arrange`".

**Comment by VincentBu** [comment]
repro with vs main build(32606.310.main) on Windows

**Comment by hartez** [comment]
@jsuarezruiz Can you elaborate on how it's failing? Or provide some screenshots for context?
