### ISSUE TITLE
Arrange on Layouts not respecting correctly the passed bounding Rect

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#7535]
### Description

Simply put, `Arrange` should not assume that the passed bounding `Rect` has the same `Size` as the passed size constraints on `Measure`. For instance, it is completely valid to call `Measure` with 200x100 size constraints, but then call `Arrange` with a 400x300 bounding `Rect`. The actual available `Size` is often not known during `Measure`, but is only available during `Arrange`.

What happens in practice is, when `Measure` is called on a `Layout` with some finite size constraints, the `Layout` remembers the measured size in the `DesiredSize` property and uses that during `Arrange`, disregarding the actual size passed with the bounding `Rect`.

### Steps to Reproduce

Download an run the attached sample project.

[TestApp.zip](https://github.com/dotnet/maui/files/8787073/TestApp.zip)

The sample project contains a `CustomLayout`, which is used to demonstrate the incorrect behavior. The `CustomLayout` simply calls `Measure` and `Arrange` on its only child forwarding the passed parameters. The content of the `CustomLayout` is a `Grid` with a `Label`, which is centered inside the `Grid`. The `CustomLayout` has a `bool` property to control whether to pass the original size constraints when measuring the child or `double.PositiveInfinity`. Observe how the child `Grid` behaves differently on `Arrange`, depending on the arguments passed on `Measure`, even though we pass the same bounding `Rect` during `Arrange`. I have set a `BacgroundColor` on the `Grid` to demonstrate that the `Grid` is arranged correctly in both cases.

The following screenshot illustrates the behavior with *finite* size constraints on `Measure` (the `Label` is centered in the `Grid`):

![image](https://user-images.githubusercontent.com/98032058/170712004-86fade73-91eb-4fcd-9dec-2d093f2ee09a.png)

The next screenshot demonstrates the behavior with *infinite* size constraints on `Measure` (the `Label` is not centered in the `Grid`):

![image](https://user-images.githubusercontent.com/98032058/170712209-14c991f7-cdfb-4a6a-ba95-f712b4ff9bf7.png)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

### Did you find any workaround?

One semi-working workaround is to call `Measure` of the child during `Arrange` with the final size constraints. This crashes on Windows with an infinite layout loop however. ;-)

**Comment by kristinx0211** [comment]
verified repro on android with above repro project.

**Comment by hartez** [comment]
This is now working as expected in with 6.0.400.

![Screenshot_20220915-102115](https://user-images.githubusercontent.com/538025/190473385-4c362871-8e31-4060-b59f-182ffbd4a832.png)
