### ISSUE TITLE
Verify all open issues from Xamarin.Forms in MAUI

### ISSUE THREAD

**Issue by PawKanarek** [dotnet/maui#7536]
### Description

HI,
I have been a Xamarin developer since 2016 and still use it on a daily basis. First of all I would like to congratulate you for releasing MAUI as a Generally Available release! 🥳

Secondly, I wonder what will happen with the "legacy" of the Xamarin Forms community. Currently there are [2810 open issues in Xamarin.Forms GitHub](https://github.com/xamarin/Xamarin.Forms/issues). I believe that some part of those issues will still be relevant in the MAUI project.

### Do you plan to verify all the issues from Xamarin.Forms in MAUI?

I know that verifying 2,8k issues would need enormous amounts of work especially when you have already 1,1k open issues in MAUI, but I'm worried that hard work that the community has put into creating those issues in Xamarin will be lost or forgotten.

My theory is that MAUI has origins in Xamarin.Forms, and if something had happened in Xamarin.Forms, may also happen in MAUI, so better test it before disaster happens. You could also add a new label in Xamarin GitHub **s/fixed-in-maui** or
**s/not-revelant-in-maui** or if it happens then create a clone of the issue in MAUI.

There are a lot of reproduction repositories in Xamarin.Forms issues, and I'm thinking that it would also be a great training area to automatize migrating from Forms to MAUI project ;)

I'm writing this because I love .net and I don't want newcomers to label .net as a buggy framework, I'm worried that GA release was made a little too fast. (MAUI has 1,1k open issues and [547 verified](https://github.com/dotnet/maui/issues?q=is%3Aopen%20is%3Aissue%20label%3As%2Fverified%20label%3At%2Fbug)). Look at Cyberpunk 2077 game release - they shipped it buggy, and users were at least "not happy".

Quality not Quantity!

Cheers.

### Public API Changes

//

### Intended Use-Case

//

**Comment by janseris** [comment]
I am joining this because exactly the idea of the mobile frameworks being buggy in .NET is what Xamarin effect was e.g. for our university. The teacher mentioned that there is a mobile framework in .NET but immediately discouraged anyone from using it. I hope MAUI even if it is multi-platform, will not have the same fate. 
Forgotting about issues from Xamarin is not a good idea because as far as I have seen here, MAUI Android is basically an extended wrapper of Xamarin (I am probably oversimplifying it).

**Comment by AlleSchonWeg** [comment]
In the last months, some issues were fixed in XF and not transfered to maui. 
The support for XF exists only theoretical. Factual almost nobody from MS looks at the issues. So the XF issues are rising and a lot of people are frustrated (including me). 
I think the XF repo will be closed or read only.

**Comment by PawKanarek** [comment]
@AlleSchonWeg About XF support, you have right. [Last closed issue in XF repo was 11 days ago!](https://github.com/xamarin/Xamarin.Forms/issues?q=is%3Aissue+is%3Aclosed )

**Comment by AlleSchonWeg** [comment]
@PawKanarek And this was a community fix.
The fix is not transfered to maui: https://github.com/dotnet/maui/blob/fc0970b6f3e4e8eebd5aa37d5213ee481b083dcc/src/Compatibility/Core/src/iOS/Renderers/EditorRenderer.cs#L287
if i understand the code correctly.

**Comment by PawKanarek** [comment]
Yes, indeed you are right. OnEnded method from [X.F 5.0.0-sr10](https://github.com/JustickDM/Xamarin.Forms/blob/release-5.0.0-sr10/Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs#L278) looks identical to the method from MAUI from 
[the latest release 6.0.312](https://github.com/dotnet/maui/blob/6.0.312/src/Compatibility/Core/src/iOS/Renderers/EditorRenderer.cs#L287). 

But thats weird. i've heard that MAUI wont use renderers anymore, they replaced it with handlers. That looks like some deprecated (compatibility) code in MAUI. 

I went deeper into rabbit hole and noticed that new [ iOS Handler has almost identical OnEnded method](https://github.com/dotnet/maui/blob/3409e87ba4781bb4d386330319a3774b34529002/src/Core/src/Handlers/Editor/EditorHandler.iOS.cs#L131)

With the difference that Handler sets property `IsFocused = false` & calls method `Completed()` on some `VirtualView`
and renderer was setting these actions accordingly `Element.SetValue(VisualElement.IsFocusedPropertyKey, false);` & `ElementController.SendCompleted();` 

So im like 95% sure that [fix from this PR](https://github.com/xamarin/Xamarin.Forms/pull/15369) should be also applied to MAUI... 

And that is the key point of what I am trying to bring up here. Thank you!

### Issues from Xamarin needs to be verified in MAUI.

**Comment by hartez** [comment]
We do track issues which need to have the same or similar fixes in .NET MAUI; for example, see #8702. 

If we had infinite time and resources, we would verify every open issue in Xamarin.Forms to see if it applied to .NET MAUI. But we do not have an infinite amount of either. So we have to focus on the highest priority issues, and it's possible that we miss some XF fixes which should apply. 

If you know of a specific fix in XF which you believe also applies to .NET MAUI, please open an issue for it.

**Comment by janseris** [comment]
Does maybe MAUI or Xamarin team plan extending in the terms of number of people/resources? That is the only solution to actually help.
