### ISSUE TITLE
VerticalOptions doesn't work inside a layout.

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#7537]
### Description

![image](https://user-images.githubusercontent.com/6466875/170723671-17de3272-293b-4557-b764-eb47851796dc.png)

![image](https://user-images.githubusercontent.com/6466875/170723812-f8e3bdc7-32da-4c67-bd4f-937743678dd3.png)

### Steps to Reproduce

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <StackLayout BackgroundColor="Red">
        <Label Text="Label1"
               VerticalOptions="Start" />

        <Label Text="Label1"
               VerticalOptions="Center" />

        <Label Text="Label1"
               VerticalOptions="End" />
    </StackLayout>

</ContentPage>

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by hartez** [comment]
VerticalOptions have no effect in a vertical StackLayout. If you want to subdivide the screen into 3 sections and display your Labels at the top, center, and end of those 3 sections, I would suggest a Grid:

```
<Grid RowDefinitions="*,*,*" Background="Red">
	<Label Text="Label1" VerticalOptions="Start"/>
	<Label Text="Label2" Grid.Row="1" VerticalOptions="Center"/>
	<Label Text="Label3" Grid.Row="2" VerticalOptions="End"/>
</Grid>

```

**Comment by pierrebrito** [comment]
@hartez Thanks.
This worked so well in Xamarin, why on Maui does it not work?

**Comment by ToolmakerSteve** [comment]
Are you _sure_ that worked vertically in Xamarin? AFAIK, XF StackLayout never takes more vertical space than its children ask for.

**Comment by EPS-Lac** [comment]
From my experience this didn't work in Xamarin.Forms either. You need to set it to "CenterAndExpand" (or StartAndExpand/EndAndExpand) for it to fill up the space available.
