### ISSUE TITLE
[Windows] Border removes child when using Line, PolyLine, Polygon as StrokeShape

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#7538]
### Description

Using Line, PolyLine, or Polygon as a border StrokeShape causes the element inside to disappear on Windows. I didn't check on other platforms.

The elements in question are Label and ImageButton. I didn't try with other Elements

```
<Border Stroke="Black" StrokeThickness="1" StrokeShape="Ellipse" Padding="0"
                    HorizontalOptions="Center"
                    VerticalOptions="Center">
                <ImageButton
                WidthRequest="400"
                HeightRequest="200"
                    Source="dotnet_bot.png"/>
            </Border>
            <Border Stroke="Black" StrokeThickness="1" StrokeShape="Line 0,100 100,100" Padding="0"
                    HorizontalOptions="Center"
                    VerticalOptions="Center">
                <Label Text="A LABEL!!!"/>
            </Border>
            <Border Stroke="Black" StrokeThickness="1" StrokeShape="Line 0,0 0,100" Padding="0"
                    HorizontalOptions="Center"
                    VerticalOptions="Center">
                <ImageButton
                WidthRequest="400"
                HeightRequest="200"
                    Source="dotnet_bot.png"/>
            </Border>
```

Result:
![image](https://user-images.githubusercontent.com/2334530/170728359-8034f12f-af21-4c78-bf87-a7bd9eceb5c1.png)

The intended use is to create a bar indicator like on Windows:
![image](https://user-images.githubusercontent.com/2334530/170728928-638745ba-338c-462a-9c85-2c825dccfa95.png)

### Steps to Reproduce

1. Create a new Maui app (GA with vs22 17.3.0pre1.1
2. Paste in the code in the description

Expected: The Label and second ImageButton have a Line border as defined
Actual: The Line is rendered, but the element itself is invisible.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Use a Line inside a Layout with the Element. However, this may impact performance given enough Layout elements.

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.3.0 Preview 2.0 [32531.271.main]. the element itself is invisible. repro project:
[MauiApp13.zip](https://github.com/dotnet/maui/files/8813072/MauiApp13.zip)
![image](https://user-images.githubusercontent.com/99457000/171378452-fc012e81-56b3-489d-a7d7-2903f6aaaf26.png)
on android 12 also incorrect:
![image](https://user-images.githubusercontent.com/99457000/171378635-0a973293-bd30-408e-8292-536ff6dc96b0.png)

**Comment by jsuarezruiz** [comment]
I'm doing tests on the current main branch and Polyline, Polygon if they render the content. The Line does not, although it is expected.

![image](https://user-images.githubusercontent.com/6755973/172349262-d18d3134-95bf-46d4-a91c-b3425b4a47f5.png)

@redth Should we review whether to limit the use of Line maybe or some change?

**Comment by davidortinau** [comment]
Border adds a layout anyway, so I wouldn't recommend it for this scenario. I propose it's reasonable to scope usage to complete/enclosed shapes like Rectangle, RoundRectangle, Ellipse, Polygon, etc. and note Line as a limitation.

**Comment by davidortinau** [comment]
Closing. @davidbritch if you think it'd be ok, perhaps add a mention of this to the Border doc.
