### ISSUE TITLE
[Bug] Catalyst layout doesn't account for the status bar

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#755]
### Description

Content is hidden under mac status bar. Compare Mac and iOS images:

https://github.com/davidortinau/LayoutLab

![Screen Shot 2021-04-15 at 1 16 46 PM](https://user-images.githubusercontent.com/41873/114922375-3104a800-9df1-11eb-9d7a-8e7681fb5c22.png)

![Simulator Screen Shot - iPhone 12 - 2021-04-15 at 12 36 03](https://user-images.githubusercontent.com/41873/114922403-37931f80-9df1-11eb-9fef-b4cd76d0d1f7.png)

### Basic Information

- Version with issue: Preview 3

**Comment by Redth** [comment]
No longer repros:
![image](https://user-images.githubusercontent.com/271950/140558997-035b3c17-144b-42c1-98e1-fe559eefcbff.png)
