### ISSUE TITLE
Resizetizer has an empty error with an invalid file name

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#7554]
### Description

When including an image file that has an invalid file name like `foo-bar.svg` the build will have several errors. These errors have no Target Framework, Error Code or Description (though I would imagine that I'm seeing one for each target framework).

![image](https://user-images.githubusercontent.com/3860573/170797409-8a5b169b-68ee-46f3-aae2-86ebffc882bf.png)

### Steps to Reproduce

1. Add an image to the Resources\Images
2. Include a dash `-` in the name
3. Build

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

n/a

### Did you find any workaround?

Rename the file

**Comment by NabodevMats** [comment]
After adding a file with invalid characters and then rectifying the file, I still cannot compile without the same error. I have removed all images from the resource/images folder, cleaned the project, manually deleted the bin/obj folders, restarted the solution, visual studio and the whole computer. 

I'm using visual studio for mac 2022 v17 and compiling for maccatalyst

**Comment by ToolmakerSteve** [comment]
Same as [this StackOverflow question](https://stackoverflow.com/q/72414708/199364)?

Where creating a new project, then adding all the good images [none with bad name], the new project works?

(Even though the two projects seemed to be identical, so its a cache somewhere.)

**Comment by kristinx0211** [comment]
repro this issue with 17.3.0 Preview 2.0 [32531.271.main].
