### ISSUE TITLE
No icon generated for older Android Devices

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#7556]
### Description

When building a MAUI App for Android, we would expect that Resizetizer would generate the necessary app icons. While we see that the generated icon is present on newer devices/emulators, older devices do not have the expected app icon. 

| Visual Studio Emulator (API 25) | API 29 |
|-------|--------|
| ![image](https://user-images.githubusercontent.com/3860573/170797819-1c640cd9-6ca5-4329-a245-ad913fc1522d.png) | ![image](https://user-images.githubusercontent.com/3860573/170799048-8e9f0bbf-7807-4db2-86aa-4ea3ef793850.png) |

### Steps to Reproduce

1. Create a new MAUI App
2. Build for Android
3. Deploy to an emulator 

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1

**Comment by kristinx0211** [comment]
this issue can be reproduced on android 7.1. not repro on android 12.

**Comment by davibittencourtome** [comment]
Any news about this?

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/23178
