### ISSUE TITLE
Support the Mac Idiom for Mac Catalyst apps

### ISSUE THREAD

**Issue by coolbluewater** [dotnet/maui#7559]
### Description

Mac apps built with Mac Catalyst support two user interface idioms, iPad or Mac. See https://developer.apple.com/documentation/uikit/mac_catalyst/choosing_a_user_interface_idiom_for_your_mac_app/

However, there is no way to select this idiom when building a C# app and the idiom is always iPad. This is a high-severity issue because it limits the type of Mac Catalyst app that can be created.

### Steps to Reproduce

See above.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
@rolfbjarne @dalexsoto ?

Is this something we can do with the Mac Catalyst SDK already? I think I remember this being brought up before, and it's an option you can enable in Xcode, but wasn't something that was available in the SDK.

**Comment by rolfbjarne** [comment]
This looks like https://github.com/xamarin/xamarin-macios/issues/14621 - you believe you can change the idiom by setting `UIDeviceFamily` to `6` in your Info.plist. Can you try that and see if it works?

**Comment by coolbluewater** [comment]
Yes, that works, thanks! 
This needs to be exposed in the UI in a manner similar to Xcode, otherwise it is impossible to discover.

**Comment by drasticactions** [comment]
@coolbluewater That's something that needs to be added to the IDE tooling, which isn't maintained here. I would file that [here](https://developercommunity.visualstudio.com/spaces/8/index.html).

Closing this issue as there is a workaround. If you edit the info.plist for your Mac Catalyst app and set `UIDeviceFamily` to `6`, it will switch the UI Idiom to Mac.
