### ISSUE TITLE
[Bug] Mac Catalyst doesn't resize content to window

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#756]
### Description

When resizing the window, content should re-measure and layout.

![Screen Shot 2021-04-15 at 1 15 04 PM](https://user-images.githubusercontent.com/41873/114922616-8345c900-9df1-11eb-8a24-1fe9af6be6b4.png)
![Screen Shot 2021-04-15 at 1 14 58 PM](https://user-images.githubusercontent.com/41873/114922619-83de5f80-9df1-11eb-9252-0078024b8f61.png)
![Screen Shot 2021-04-15 at 1 14 42 PM](https://user-images.githubusercontent.com/41873/114922620-83de5f80-9df1-11eb-956c-7743e2863bc1.png)

### Basic Information

- Version with issue: Preview 3

### Source

https://github.com/davidortinau/LayoutLab

**Comment by jsuarezruiz** [comment]
Tried with Preview 11 and now is working as expected.
