### ISSUE TITLE
.NET Multi-platform App UI development

### ISSUE THREAD

**Issue by AhmedLotfi** [dotnet/maui#7565]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

.NET Multi-platform App UI development, this option is not available in visual studio 2022 17.2.2v

**Comment by MagicAndre1981** [comment]
> .NET Multi-platform App UI development, this option is not available in visual studio 2022 17.2.2v

you need the [17.3 preview](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-windows#get-started-with-visual-studio-2022-173-preview)

**Comment by drasticactions** [comment]
While MAUI itself is GA, the tooling is only available in 17.3 Previews and up.
