### ISSUE TITLE
Maui Android OnBackPressed has wrong return type

### ISSUE THREAD

**Issue by leubeem** [dotnet/maui#7567]
### Description

I wanted to use the AndroidLifeCycle in a Maui App like shown in [https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle). Everything worked fine except the method OnBackPressed. 
OnBackPressed required a bool as return paramter instead of void, as shown in Microsoft.Maui.LifecycleEvents:
```
namespace Microsoft.Maui.LifecycleEvents
{
    public static class AndroidLifecycle
    {
        public delegate void OnApplicationCreating(Application application);
        public delegate void OnNewIntent(Activity activity, Intent? intent);
        public delegate void OnConfigurationChanged(Activity activity, Configuration newConfig);
        public delegate bool OnBackPressed(Activity activity);
        public delegate void OnActivityResult(Activity activity, int requestCode, Result resultCode, Intent? data);
        public delegate void OnPostResume(Activity activity);
        public delegate void OnPostCreate(Activity activity, Bundle? savedInstanceState);
        public delegate void OnRestart(Activity activity);
        public delegate void OnDestroy(Activity activity);
        public delegate void OnRequestPermissionsResult(Activity activity, int requestCode, string[] permissions, Permission[] grantResults);
        public delegate void OnSaveInstanceState(Activity activity, Bundle outState);
        public delegate void OnPause(Activity activity);
        public delegate void OnResume(Activity activity);
        public delegate void OnStart(Activity activity);
        public delegate void OnCreate(Activity activity, Bundle? savedInstanceState);
        public delegate void OnApplicationConfigurationChanged(Application application, Configuration newConfig);
        public delegate void OnApplicationTrimMemory(Application application, TrimMemory level);
        public delegate void OnApplicationLowMemory(Application application);
        public delegate void OnApplicationCreate(Application application);
        public delegate void OnStop(Activity activity);
        public delegate void OnRestoreInstanceState(Activity activity, Bundle savedInstanceState);
    }
}
```
Every method has void as return type except OnBackPressed. Is this a bug?

### Steps to Reproduce

1. Create a Maui App
2. Open MauiProgram.cs
3. Write Code for Android Lifecycle methods like shown in [https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#android](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#android)
4. See Error for ``` .OnBackPressed((activity) => LogEvent("OnBackPressed")) ```

![Shown error message](https://user-images.githubusercontent.com/48156489/170832557-322bf922-2dd6-4b4a-b387-6b2846b9307f.png) (Sorry for german image)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by nabond251** [comment]
No, I don't think this is a bug.  The `bool` return value indicates whether the back button pressed event has been handled.  Seems the current docs don't say much on this score, but referring to the corresponding [Xamarin docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.onbackbuttonpressed?view=xamarin-forms):
> Application developers can override this method to provide behavior when the back button is pressed.
> ...
> Returns
> [Boolean](https://docs.microsoft.com/en-us/dotnet/api/system.boolean)
> Whether or not the back navigation was handled by the override.

Return `true` and the underlying framework won't continue handling it; return `false` and it will.  Useful for intercepting/preventing back navigation.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. This does not repro on Android 13.0 with below Project:
[7567.zip](https://github.com/dotnet/maui/files/11449238/7567.zip)

There is no Error for .OnBackPressed((activity) => LogEvent("OnBackPressed"))
![image](https://github.com/dotnet/maui/assets/97647558/beea8dfb-07fd-4874-9573-88694fed6875)

@leubeem , please let us know if you have any update.
