### ISSUE TITLE
When renaming a newly added XAML page in Visual Studio 2022 only the filename gets changed

### ISSUE THREAD

**Issue by gfmoore** [dotnet/maui#7568]
### Description

So if I add a new item by right clicking on a folder, say a maui content page and I mispell it, I think no worries, I'll just rename it. It renames the file, but not the underlying code. I have to do this manually.

Don't know if this is a bug as in its the behaviour I would have expected or it needs to be a feature request, or it's a VS issue but there it is.... :)

### Steps to Reproduce

As above

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Visual Studio

### Did you find any workaround?

Manually edit files

**Comment by kristinx0211** [comment]
repro this using vs 17.3.0 Preview 2.0 [32531.271.main].

**Comment by kjpou1** [comment]
Repro this using:

```
Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 2012)
```
