### ISSUE TITLE
Unable to disable zooming in MAUI Blazor App for Windows

### ISSUE THREAD

**Issue by zsuatem** [dotnet/maui#7569]
### Description

Unable to disable zooming in MAUI Blazor App despite having `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />` in HTML head.

I've seen a similar problem in iOS #4996, but it has been eliminated, so I assume this is not a proper behavior.

![](https://i.imgur.com/H38ItlQ.gif)

### Steps to Reproduce

1. Create new MAUI Blazor App
2. Open on Windows
3. Zoom in/out with e.g. <kbd>Ctrl + Scroll</kbd> or <kbd>Ctrl + +/-</kbd>

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by Eilon** [comment]
Hi @zsuatem , it appears that in WebView2 there is an additional setting that your app would have to enable to completely disable zooming. Fortunately, it's only 1 line of code to enable!

First, I updated `MainPage.xaml` to wire up a new event handler that gets called when BlazorWebView is starting:

```xaml
    <BlazorWebView HostPage="wwwroot/index.html" BlazorWebViewInitialized="Bwv_BlazorWebViewInitialized">
        ...
```

Second, in the new event handler, in case it's running on Windows, I configured WebView2's settings to disable zoom:

```c#
    private void Bwv_BlazorWebViewInitialized(object sender, Microsoft.AspNetCore.Components.WebView.BlazorWebViewInitializedEventArgs e)
    {
#if WINDOWS
        e.WebView.CoreWebView2.Settings.IsZoomControlEnabled = false;
#endif
    }
```
