### ISSUE TITLE
"Pressed" Visual State not changing back to "Normal" until you click away on Windows

### ISSUE THREAD

**Issue by keithmullins** [dotnet/maui#7570]
### Description

I started a new MAUI app to see how to change a button's visual state when it has been pressed. I found that the code I used for this works on macOS but not on Windows. 

Firstly, I added colours to the Colors.xaml file
```
<Color x:Key="PrimaryBackgroundColour">#337ab7</Color>
<Color x:Key="PrimaryBorderColour">#2e6da4</Color>
<Color x:Key="PrimaryBackgroundActiveColour">#204d74</Color>
<Color x:Key="PrimaryBorderActiveColour">#122b40</Color>
```

I then added a new style to the Styles.xaml file which adds the Visual States
```
<Style x:Key="PrimaryButton"  
        TargetType="Button">
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroupList>
            <VisualStateGroup x:Name="CommonStates">
                <VisualState x:Name="Normal">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource PrimaryBackgroundColour}, Dark={StaticResource White}}" />
                        <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource PrimaryBorderColour}, Dark={StaticResource White}}" />
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Pressed">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource PrimaryBackgroundActiveColour}, Dark={StaticResource White}}" />
                        <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource PrimaryBorderActiveColour}, Dark={StaticResource White}}" />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </Setter>
</Style>
```

I then changed by Button to have this new style:
```
<Button 
    Text="Login"
    WidthRequest="300"
    HorizontalOptions="Center"
    Style="{StaticResource PrimaryButton}" />
```

When I ran the app on Windows I found that the button's Visual State when pressed did change correctly, but it didn't revert back to the Normal state until I clicked away (for example, clicking in to one of the Entry controls):
![Example on Windows](https://gyazo.com/af91ebc6d928be4ab6bee729309d1405.gif)

When I run the same code on macOS it works as expected:
![Example of macOS](https://gyazo.com/1d1703b52dc58970c0f8247bfec808f0.gif)

### Steps to Reproduce

I create a new Maui app. 

I added colours to the Colors.xaml file
```
<Color x:Key="PrimaryBackgroundColour">#337ab7</Color>
<Color x:Key="PrimaryBorderColour">#2e6da4</Color>
<Color x:Key="PrimaryBackgroundActiveColour">#204d74</Color>
<Color x:Key="PrimaryBorderActiveColour">#122b40</Color>
```

I then added a new style to the Styles.xaml file which adds the Visual States
```
<Style x:Key="PrimaryButton"  
        TargetType="Button">
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroupList>
            <VisualStateGroup x:Name="CommonStates">
                <VisualState x:Name="Normal">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource PrimaryBackgroundColour}, Dark={StaticResource White}}" />
                        <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource PrimaryBorderColour}, Dark={StaticResource White}}" />
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Pressed">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={StaticResource PrimaryBackgroundActiveColour}, Dark={StaticResource White}}" />
                        <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource PrimaryBorderActiveColour}, Dark={StaticResource White}}" />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </Setter>
</Style>
```

I then changed by Button to have this new style:
```
<Button 
    Text="Login"
    WidthRequest="300"
    HorizontalOptions="Center"
    Style="{StaticResource PrimaryButton}" />
```

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.3.0 Preview 2.0 [32531.271.main] as described above . works ok on android. repro project:
[MauiApp11.zip](https://github.com/dotnet/maui/files/8811915/MauiApp11.zip)

**Comment by DarkNoir** [comment]
Same issue on Windows 11 : 10.0.22000.0

**Comment by jsuarezruiz** [comment]
We need to review this. What happens is that on Windows, clicking the Button sets the focus to the control. So, although the state momentarily changes to Normal after the click, it immediately changes to Focused.

**Comment by alexp9982** [comment]
Able to reproduce, hope this gets fixed

**Comment by blanc99** [comment]
Able to reproduce as well. Thanks to jsuarezruiz, the workaround I put in is to add the 'Focused' visual state and set the colors to be the same as those of 'Normal' (as I do not need to highlight a focused button.)

**Comment by codechavez** [comment]
I'm encountering the same issue. I have to click outside to go from pressed to normal. Please fix soon!

**Comment by blackcatpolice** [comment]
> Same issue on Windows 11 : 10.0.22000.0
> 
> More Info: Work Around, add event to reset. C# :
> 
> ```
>  private void Button_Pressed(object sender, EventArgs e)
> {
>     Button b = (Button)sender;
>     Dispatcher.DispatchDelayed(TimeSpan.FromMilliseconds(400), () =>
>     {
>         VisualStateManager.GoToState(b, "Normal");
>     });
> }
> ```

This code work for me

**Comment by EmanterolaDN** [comment]
I'm facing same issue, applied all workarounds suggested here... Even other attempts with PointerGestureRecognizer pointerEntered, pointerExited, pointermoved, button pressed, released or unfocused... Also tried with WinUI3 but nothing worked.

BTW doing same than issue (As expected) IsPressed and IsFocused are set to true. None of VisualStateManager workarounds worked for me in W10 and .Net 7.

GL!

**Comment by PureWeen** [comment]
I tested this on NET7 and for me it's currently working.
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/visual-states#define-visual-states-on-a-view

You'll need to define an empty normal state or an empty pointer over state which basically tells it to revert back to the setters defined in the style.

Both of these variations worked fine for me. 

```XAML
<Setter Property="VisualStateManager.VisualStateGroups">
	<VisualStateGroupList>
		<VisualStateGroup x:Name="CommonStates">
			<VisualState x:Name="Normal">
			</VisualState>
			<VisualState x:Name="Pressed">
				<VisualState.Setters>
					<Setter Property="BackgroundColor" Value="Green" />
					<Setter Property="TextColor" Value="Orange" />
				</VisualState.Setters>
			</VisualState>
		</VisualStateGroup>
	</VisualStateGroupList>
</Setter>
```

And this
```
<Setter Property="VisualStateManager.VisualStateGroups">
	<VisualStateGroupList>
		<VisualStateGroup x:Name="CommonStates">
			<VisualState x:Name="PointerOver">
			</VisualState>
			<VisualState x:Name="Pressed">
				<VisualState.Setters>
					<Setter Property="BackgroundColor" Value="Green" />
					<Setter Property="TextColor" Value="Orange" />
				</VisualState.Setters>
			</VisualState>
		</VisualStateGroup>
	</VisualStateGroupList>
</Setter>
```

If someone has a repro they can comment here with where it's not working for you and seems like a bug let me know.
