### ISSUE TITLE
MAUI on Big Sur with Xcode 12

### ISSUE THREAD

**Issue by SasukeK93** [dotnet/maui#7572]
Creating a new maui project and trying to compile it

`dotnet new maui`
`dotnet build -t:Run -f net6.0-maccatalyst`

gives the folowing error

`Could not map the Mac Catalyst version 14.0 to a corresponding macOS version. Valid Mac Catalyst versions are: 13.3, 13.3.1, 13.4, 13.1, 13.5, 13.2, 13.6`

This can be easily fixed by changing the version in the .csproj, but when trying to build it again.

`This version of Microsoft.MacCatalyst requires the MacCatalyst 15.4 SDK (shipped with Xcode 13.3). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).`

I can't install Xcode 13.3 cause it needs macOS 12.0+
How do i set the Linker Behavior to 'Link Frameworks SDKs Only' in my .csproj ?

**Comment by drasticactions** [comment]
@rolfbjarne @dalexsoto ?

IMO I would upgrade to Big Sur or greater and get the newer Xcode. Trying to get MAUI or the iOS SDKs working on previous versions, while maybe _technically_ possible (Although I think MAUI depends on the newer SDKs and libraries, so I don't think it'll work on Xcode 12 anyway), is only going to cause pain down the road.

**Comment by SasukeK93** [comment]
@drasticactions On [microsoft docs](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms)  have the following information :

> .NET Multi-platform App UI (.NET MAUI) apps can be written for the following platforms:
> 
> Android 5.0 (API 21) or higher.
> iOS 10 or higher.
> macOS 10.13 or higher, using Mac Catalyst.
> Windows 11 and Windows 10 version 1809 or higher, using [Windows UI Library (WinUI) 3](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)

I'm on macOS 11.2, so it should be possible to build a MAUI app on it

**Comment by drasticactions** [comment]
> @drasticactions On [microsoft docs](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms) have the following information :
> 
> > .NET Multi-platform App UI (.NET MAUI) apps can be written for the following platforms:
> > Android 5.0 (API 21) or higher.
> > iOS 10 or higher.
> > macOS 10.13 or higher, using Mac Catalyst.
> > Windows 11 and Windows 10 version 1809 or higher, using [Windows UI Library (WinUI) 3](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
> 
> I'm on macOS 11.2, so it should be possible to build a MAUI app on it. SInce macOS and Xcode launch updates too fast and my internet connection is bad i can't update so often

Running said app and _building_ said app are two different things. That said, it may be that that requirement list was written before upgrades to the iOS SDK and its Xcode Requirements made it impossible, so that requirement list should be updated.

As for your situation though. I sympathize, but the right way to fix this is to upgrade.

**Comment by SasukeK93** [comment]
thx @drasticactions @rolfbjarne
After after changing the "linker behavior" the project build and run successfully.

Currently the requirement when compiling is Xcode 13.3, it is planned to keep that version as the minimum requirement (at least for maui + .net 6) or it will always be recommended to keep Xcode updated to the latest version.

**Comment by rolfbjarne** [comment]
@SasukeK93 yes, it will always be recommended to use the latest Xcode version - whenever Apple releases a new Xcode version with new APIs, and we release a new version of our product with support for those APIs, then it will be recommended to use the same Xcode version (once you upgrade to our new version).

**Comment by drasticactions** [comment]
A good rule of thumb is to build with whatever iOS/Mac SDK that MAUI itself builds with, which means using that specific Xcode version (or supported set). Going above or below may introduce subtle issues (or more breaking ones) that you won't catch. 

That may be things that should be better explained in the documentation and supported versions.
