### ISSUE TITLE
VerticalOptions cannot be set on a Rectangle in Windows

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#7573]
### Description

I'm having a `Grid` with a fixed size and a background color. Inside that I'm trying to draw a `Rectangle` from the bottom (like a vertical progress bar). This works as expected in Android. But in Windows the inner rectangle always fills the `Grid`. Drawing the inner rectangle with a `Grid` solves the problem.

This is from Windows:

![image](https://user-images.githubusercontent.com/3163293/170836202-c9915fc6-446d-4a92-b79b-5e8b10b373c5.png)

And this is from Android:

![image](https://user-images.githubusercontent.com/3163293/170836230-c1cb0489-21f0-455f-a1ea-d5753223d0f2.png)

The left progress bar is draw with two `Grid`s, the right one with a `Grid` and a `Rectangle`.

### Steps to Reproduce

1. Create a new MAUI app.
2. Replace the MainPage.xaml with this:

``` XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage">

    <HorizontalStackLayout 
        Spacing="25" 
        Padding="30,30" 
        VerticalOptions="Start"
        >
        <!-- This works fine -->
        <Grid WidthRequest="100" HeightRequest="200" BackgroundColor="{StaticResource Gray600}">
            <Grid  
                HeightRequest="50" 
                VerticalOptions="End" 
                BackgroundColor="{StaticResource Blue100Accent}"
            />
        </Grid>

        <!-- This is fine on Android, but not on Windows -->
        <Grid WidthRequest="100" HeightRequest="200" BackgroundColor="{StaticResource Gray600}">
            <Rectangle
                HeightRequest="50" 
                VerticalOptions="End" 
                BackgroundColor="{StaticResource Blue200Accent}"
            />
        </Grid>
    </HorizontalStackLayout>
</ContentPage>
```

Full sample: https://github.com/pekspro/MauiIssues/tree/7573_VerticalOptions_Rectangle_Windows

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.171340.0

### Did you find any workaround?

Use `Grid` instead of `Rectangle`.

**Comment by kristinx0211** [comment]
verified repro on windows with above project.

**Comment by pekspro** [comment]
I've updated sample application to .NET 7. The same issue remains.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Windows 11 with below Project:
[7573.zip](https://github.com/dotnet/maui/files/11449748/7573.zip)

![image](https://github.com/dotnet/maui/assets/97647558/67442a09-0f3d-448a-8f8c-15d125e5d94e)
