### ISSUE TITLE
[iOS]The "FontAttributes" property of label is not rendered  on ios and maccatalyst.

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#7574]
### Description

Whether the "FontAttributes" property is set to "Bold" or "Italic", nothing changes on ios and maccatalyst.
iOS
![Simulator Screen Shot - iPhone 13 - 2022-05-29 at 03 39 48](https://user-images.githubusercontent.com/39898152/170842099-5ef3a13b-3218-4b45-83c0-7f208a388a13.png)
android
![Screenshot_1653768516](https://user-images.githubusercontent.com/39898152/170842109-814b1944-de0f-4f83-8ced-f7f4112da7f2.png)

### Steps to Reproduce

1. Copy the code snippet below into your project.
```
     <VerticalStackLayout
            Spacing="25" 
            Padding="30,0" 
            VerticalOptions="Center">          
            <Label Text="Hello, World!"/>
            <Label
                Text="Hello, World!(Bold)"
                FontAttributes="Bold"/>
            <Label 
                Text="Hello, World!(Italic)"
                FontAttributes="Italic"/>
            <Label 
                Text="Hello, World!(None)"
                FontAttributes="None"/>
        </VerticalStackLayout>
```
2. Run the project.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

 iOS 15.5

**Comment by kristinx0211** [comment]
verified repro on IOS with the code.

**Comment by matt-goldman** [comment]
Also having this problem.

**Comment by jsuarezruiz** [comment]
What version of .NET MAUI do you use? Tried with the current main branch and can't reproduce the issue.
<img width="1082" alt="Captura de Pantalla 2022-05-31 a las 10 40 58" src="https://user-images.githubusercontent.com/6755973/171131431-f71712ca-ce05-48f6-b769-9b2c036f29c2.png">

**Comment by kristinx0211** [comment]
repro this on IOS 15.4 emulators. vs 17.3.0 Preview 2.0 [32530.169.main].
![image](https://user-images.githubusercontent.com/99457000/171132814-5e31d685-6a15-44fc-860b-38eb101a09e0.png)

**Comment by kristinx0211** [comment]
on maccatalyst is also show like this:
![image](https://user-images.githubusercontent.com/99457000/171134391-6468f25b-8979-46df-a596-5e19d16aa0f6.png)

**Comment by jformo** [comment]
I have been having the same problem on MacCatalyst/iOS (Visual Studio for Mac 17.3 build 2083).

While not very clean, I did discover a workaround (tested on MacCatalyst): place the text within a <Span> instance.

Example:
```xaml
<Label>
   <Label.FormattedText>
      <FormattedString>
         <Span Text="Hello, World!(Bold)" FontAttributes="Bold"/>
      </FormattedString>
   </Label.FormattedText>
</Label>
```

**Comment by singhwong** [comment]
@jformo Yes, this works fine.

**Comment by singhwong** [comment]
In maui 6.0.452, `FontAttributes="Bold"` works fine, but `FontAttributes="Italic"` still doesn't work.

**Comment by davidortinau** [comment]
Hi all, this is related to using a custom font. If you use the default fonts for macOS and iOS it works (i.e. don't specify a font family), but with the OpenSans FontFamily it doesn't (which is also why you have different font faces - we include regular and semi-bold in the template).

```
<Label
    Text="Hello, World!"/>

<Label
    Text="Hello, World! (Bold)" FontAttributes="Bold"/>

<Label
    Text="Hello, World! (Italics)" FontAttributes="Italic"/>

<Label
    Text="Hello, World!" FontFamily=""/>

<Label
    Text="Hello, World! (Bold)" FontAttributes="Bold" FontFamily=""/>

<Label
    Text="Hello, World! (Italics)" FontAttributes="Italic" FontFamily=""/>
```

From MauiProgram.cs:

```
fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
```

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-04 at 13 21 21](https://user-images.githubusercontent.com/41873/182923216-e674829d-c1bd-43b1-8e22-6d0ee8451d00.png)
<img width="901" alt="Screen Shot 2022-08-04 at 1 20 37 PM" src="https://user-images.githubusercontent.com/41873/182923223-07206821-254c-4433-a532-dcb817357d44.png">

Please check your fonts and open an issue with additional information if needed.
