### ISSUE TITLE
FlyoutIcon does not work on Windows, although it works on Android

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui#7577]
### Description

I am taking a course about .NET MAUI in Microsoft Learn (https://docs.microsoft.com/en-us/learn/dotnet-maui/create-multi-page-apps/3-exercise-implement-flyout-navigation).... I did the exercise, where you have to specify an icon to replace the hamburger menu. When I run the example, it works fine on Android showing the new icon, but on Windows, it still shows the hamburger menu.

I uploaded 2 images: one for Android and another for Windows => https://postimg.cc/gallery/p2JShgP

### Steps to Reproduce

Follow 3rd step of this page: [Microsoft Learn MAUI Course](https://docs.microsoft.com/en-us/learn/dotnet-maui/create-multi-page-apps/3-exercise-implement-flyout-navigation)

Add a FlyoutIcon property to the <Shell> node to display an image. By default it will display 3 horizontal bars, but we can change it to be whatever we like. The markup should look like this:

```xaml
<Shell
    x:Class="Astronomy.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:Astronomy.Pages"
    FlyoutIcon="moon.png">
```

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

I dont know a workaround for this error.

**Comment by pierre01** [comment]
I saw the same issue on windows only

**Comment by kristinx0211** [comment]
verified repro on windows, it works on android, but does not work windows. repro project:
[Astronomy.zip](https://github.com/dotnet/maui/files/8796619/Astronomy.zip)

**Comment by ToolmakerSteve** [comment]
NOTE: For me, to see ANY menu icon on Windows, need at least TWO ShellContents.  

Adding a second one to that repo, I confirmed that it was still the hamburger menu.

**Comment by Padanian** [comment]
Me too. +1. Subscribed

**Comment by HobDev** [comment]
Facing same issue on Windows

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/14663
