### ISSUE TITLE
Error: System Image folder in config.ini doesn't exist

### ISSUE THREAD

**Issue by marknoble** [dotnet/maui#7578]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

When loading Pixel 5 - API 30, it had an error:

![image](https://user-images.githubusercontent.com/3819700/170845581-7651a3a3-1b63-4b0b-82ae-9f52891b5ed2.png)

But it seemed to correct itself and now I see a Start button.

**Comment by Eilon** [comment]
I'm guessing this is an error specifically with the Android Emulator itself?

**Comment by jfversluis** [comment]
This has been open for a while, I'm going to assume this was fixed. If you still see this issue, please let us know. Thanks!
