### ISSUE TITLE
DataTemplateSelector not returning DataTemplate used with BindableLayout FlexLayout

### ISSUE THREAD

**Issue by abdelbary8** [dotnet/maui#7584]
### Description

Using DataTemplateSelector with FlexLayout

```
<FlexLayout
    BindableLayout.ItemTemplate="{StaticResource MenuButtonTemplate}"
    ...
```

### Steps to Reproduce

Write simple DataTemplateSelector and use it with BindableLayout FlexLayout

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS 15, macOS 12.4

### Did you find any workaround?

Using the same DateTemplateSelector with CollectionView working without any issue
  ```
<CollectionView
    ItemTemplate="{StaticResource MenuButtonTemplate}">
    ...
```

**Comment by jfversluis** [comment]
Thanks for the report! I see you mention this doesn't work for iOS/macOS, did you happen to test Android and/or Windows? Does it work there?

**Comment by hartez** [comment]
@abdelbary8 Can you post the code for your DataTemplateSelector?

**Comment by abdelbary8** [comment]
@hartez Here's the DataTemplateSelector i'm using
`	public class MenuButtonDataTemplateSelector : DataTemplateSelector
    {
        public DataTemplate CategoryButton{ get; set; }
        public DataTemplate ItemButton{ get; set; }
        public DataTemplate BackButton { get; set; }

        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            return (((MenuButton)item).name_en == "Back")? BackButton:
                (((MenuButton)item).category_id > 0) ? ItemButton: CategoryButton;
        }
    }`

**Comment by abdelbary8** [comment]
> Thanks for the report! I see you mention this doesn't work for iOS/macOS, did you happen to test Android and/or Windows? Does it work there?

i will try it soon and post with the result

**Comment by Dmbandit** [comment]
> Thanks for the report! I see you mention this doesn't work for iOS/macOS, did you happen to test Android and/or Windows? Does it work there?

Just to add to this, FlexLayout + BindableLayout.ItemTemplateSelector is not working for me on Android either. I am having the exact same problem where if I use a DataTemplateSelector it doesn't work, where as the actual templates themselves work fine if I directly use either of them in BindableLayout.ItemTemplate.

Data Template Selectors are working fine for me everywhere else, this does seem to be specific to FlexLayout BindableLayout.ItemTemplateSelector.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with VSM 17.6.7 (build 417). Not repro this issue.
