### ISSUE TITLE
在Entry和Editor上输入，取消焦点和离开当前页后，键盘依然显示，并且影响页面。

### ISSUE THREAD

**Issue by silmooninc** [dotnet/maui#7588]
### Description

在Entry或Editor上输入数据，点击其他空白处，键盘依然存在，焦点依然在输入框。
如果含有一个按钮点击之后，使用PushModal到另外的页面，键盘依然存在，使用back键后键盘消失，存在的键盘会截断新页面的显示。
![1](https://user-images.githubusercontent.com/76204563/170876206-328ea16b-9025-4de5-a736-8ab56160acae.jpg)

### Steps to Reproduce

1. 使用默认模版，创建MauiApp。
2. 在MainPage中创建Entry和Button（尽量创建在页面上方）。
3. Button创建事件“Clicked="Button_Clicked"”
   private async void Button_Clicked(object sender, EventArgs e)
    {
        await Navigation.PushModalAsync(new NewPage1());
    }
4. 创建新页面NewPage.xaml，内容默认（可添加一个按钮，事件是await Navigation.PopModalAsync()）
5. 在安卓模拟器下运行。
6. 将光标转移到Entry内，输入一些数据。
7. 点击空白处，发现键盘依然存在。焦点依然在输入框中。
8. 点击Button，转到新的页面，发现光标提示和键盘依然显示。
9. 点击back按钮，键盘消失，显示部分上个页面的内容，当前页面内容被裁剪。

https://user-images.githubusercontent.com/76204563/170876707-18d7bb33-f0d3-4c59-94ea-ebb5da5224cb.mp4

### Version with bug

6.0 Release Candidate 1 or older

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 11***

**Comment by silmooninc** [comment]
If the video can't play, please download and play.

**Comment by VincentBu** [comment]
@silmooninc, let me translate this issue into English, feel free to point out anything doesn't make sense:

**Description**
Display a modal page with the keyboard opened, the keyboard will not be closed and can partially covers the new modal page.
Closing keyboard by back button, the keyboard will be closed but leave the area blank.

**Steps to Reproduce**
1. run this project: [maui7588.zip](https://github.com/dotnet/maui/files/8802809/maui7588.zip)
2. type something in Entry control and make the keyboard opened
3. click the button to display modal page
4. click back button to hide the keyboard.

Expected:
![image](https://user-images.githubusercontent.com/44959937/171113117-4d862256-26e8-4967-a46b-3433d2739fca.png)

Actual:
![image](https://user-images.githubusercontent.com/44959937/171113200-cded4cd2-9f24-49c8-94a1-c74f4f5b258b.png)

**Version with bug**
6.0 Release Candidate 1 or older

**Last version that worked well**
Release Candidate 3 (current)

**Affected platforms**
Android

**Affected platform versions**
Android 11***

**Did you find any workaround?**
No response

**Relevant log output**
No response

**Comment by silmooninc** [comment]
Because when using Chinese, the description is guaranteed to be clear and concise, and there is no ambiguity.

In the MainPage Page, click on the Entry control, the focus is in the control, at this time, if you click on the other empty space on the page, you cannot cancel the focus of the Entry, and the keyboard is always there.
On Android you can cancel the focus by pressing the Back key, and under iOS you can't cancel the focus anyway, which becomes my biggest trouble.

If you enter the cursor, the handle is displayed. The handle also remains on the new page.

![1](https://user-images.githubusercontent.com/76204563/171195376-2e472243-bfc1-44d2-9dcb-2da423ec7de1.jpg)
![2](https://user-images.githubusercontent.com/76204563/171197074-211b64ba-fec5-4ea9-8ee4-788ef91773a5.jpg)

**Comment by silmooninc** [comment]
此问题依然存在，并且在Android和iOS上都有错误。

**Comment by solayuta** [comment]
两个月过去了 没解决方案吗？无尽的BUG

**Comment by silmooninc** [comment]
> 两个月过去了 没解决方案吗？无尽的BUG

好像根本没人吊这个BUG，这个问题不解决无法把现有的Xamarin迁移过来。。。
