### ISSUE TITLE
WSA Using Advanced Network Is Ignored by Visual Studio.

### ISSUE THREAD

**Issue by dingdang66686** [dotnet/maui#7591]
### Description

Adb can discover WSA as "emulator-5554" without any extra configuration when WSA is using advanced network in the latest version. Other tools work normally but visual studio can't find this device for deploying applications & debugging.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/42102822/170877103-4b7e398a-c86e-4f44-80f8-bdf61927d023.png">

### Steps to Reproduce

1. Install WSA from microsoft store.
2. Enable advanced network in WSA settings page, then enable developer mode.
3. Open a MAUI project in visual studio.
4. WSA is not discovered by visual studio.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12L

### Did you find any workaround?

Adb connect localhost:58526 works.

**Comment by drasticactions** [comment]
This is a tooling bug with WSA and Visual studio, it's unrelated to MAUI. The same will happen from a "legacy" Xamarin.Android or dotnet 6 Android app without MAUI.

I would file a feedback item to https://developercommunity.visualstudio.com/home so it can go to the team that can fix this issue. Sorry!
