### ISSUE TITLE
Compiling Mac app in VSforMac 2022 preview, app loses previously granted permissions

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#7593]
### Description

When compiling and running an app that requires permissions, I the app checks and asks the user for permission this works. App can be started directly on the Mac and the permissions are persisted.
Make a change to the app code and compile and run, the app no longer has those granted permissions.

### Steps to Reproduce

When compiling and running an app that requires permissions, I the app checks and asks the user for permission this works. App can be started directly on the Mac and the permissions are persisted.
Make a change to the app code and compile and run, the app no longer has those granted permissions.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 12.3

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
If you try the same permission checks in a Mac Catalyst app without MAUI (`dotnet new maccatalyst`) does it do the same thing?

**Comment by Eilon** [comment]
I wonder if something is changing the identity of the app, so it has to re-request permissions after "significant" changes?

**Comment by JohnHDev** [comment]
Not making any significant changes, change the properties of a label etc and it will forget its previous permissions.
I am using VSforMac 2022 preview btw, so that could be a significant factor here.

**Comment by Eilon** [comment]
@JohnHDev right, I mean that something that is perhaps _accidentally_ causes the identity of the app to change. For example, maybe it gets a new identity of some sort every re-build? Or close to that?

**Comment by JohnHDev** [comment]
Of course, I agree that's possible, and probable too I would think.
Any logs I can provide to help MS figure this out?

**Comment by Eilon** [comment]
@JohnHDev sorry I'm not sure. Hopefully someone who knows more about this can help.

**Comment by jfversluis** [comment]
With Essentials you can make things as the bundle identifier show up: https://docs.microsoft.com/xamarin/essentials/app-information?tabs=android#obtaining-application-information

Would be interesting to see if there are any changes going on per run there. If anything, could you maybe put the code you're using on GitHub so we can have a look? Maybe adding some of this code to check if the bundle ID indeed changes and causing this issue?
