### ISSUE TITLE
RadioButton GroupName and IsChecked properties work inconsistently on Windows

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#7595]
### Description

When Radio Buttons are direct child of the same container, they act all as part of the same group, even when given a different GroupName property.

Also regardless of their grouping only the last button with  IsChecked="true" will be checked. even if other buttond from other GroupName are also Checked by default.

### Steps to Reproduce

Non working and semi working issue are reproduced here:

https://github.com/pierre01/RadioButtonsIssue

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro 22H2

### Did you find any workaround?

Gouping RadioButtons individually in containers allows them to be mutually exclusive based on GroupName
But this is not fixing the issue where only one Radio Button is taking the IsChecked="true" value. (among all buttons regardless of the GroupName property)

**Comment by kristinx0211** [comment]
verified repro on windows the above project.

**Comment by tekmun** [comment]
I encountered the same issue. Any workaround? Thanks.

**Comment by erledzus** [comment]
Ran into this issue also

**Comment by deviprasad987** [comment]
Any update on this issue, I am also facing the same issue.

**Comment by Chavakorns** [comment]
me too

**Comment by Chavakorns** [comment]
> Any update on this issue, I am also facing the same issue.

me too.

**Comment by ShaneBridges** [comment]
This issue goes back for at least 9 months.  RadioButton groups are what I would call a BASIC functionality. How can bugs like these make it into MAUI's release?  I sure do miss WPF (and Xamarin to a lesser extent) where, for the most part, everything just worked. Who's testing this stuff?!

- frustrated.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Windows 11, not repro on Android 13.0 with below Project:
[7595.zip](https://github.com/dotnet/maui/files/11450487/7595.zip)

Windows:
![CheckBoxWindows](https://github.com/dotnet/maui/assets/97647558/7877cd78-b8a1-42d6-8ef2-1f48fe38a0e3)

Android:
![CheckBoxAndroid](https://github.com/dotnet/maui/assets/97647558/3f66e099-e17f-4529-b929-122283489ba2)
