### ISSUE TITLE
[Android] Some DevExpress DevControl issues in the .NET MAUI 1.0

### ISSUE THREAD

**Issue by danch15** [dotnet/maui#7599]
### Description

I use .NET MAUI RC3 and DevExpress.Maui.DataGrid (22.1.1-pre-22115) in Android, all work fine.

Today I update the project the new version of .NET MAUI 1.0 (6.0.312), see here, I run my app, by the DataGridView just show the Column Header, the DataRow is empty. There is the same problem when I create a newest maui project template demo with the DevExpress.Maui.DataGrid.

It seems like each time I update the maui new version, the new problem is coming together.

Issue 1: I don't want to show the navigation bar when I show the popup windows, How can I handle this? ( I dont't found a better way to hidden the Navigation bar, so I only can't use the Obsolete method to hidden it)
Issue 2: The DataGridView can see the row's data, It seems like the bug of the Layout Control. But in MAUI RC3 is OK.
Issue 3: The DevExpress DXCollectionView not supported the GridItemsLayout. (The Rotorsoft.Forms CollectionViewSource is troublesome to use, the DevExpress DXCollectionView is easy to use the Filter, Sorting...)

P.S. Forgive my poor English O(∩_∩)O

### Steps to Reproduce

All can see here: https://github.com/danch15/MauiAndDevDemo

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 7.1.2 and Android Samsung NOTE 9 Cell Phone (Android 10)

**Comment by DmitryRomenskiy** [comment]
Hello @danch15 ,

DevExpress recommends contacting our technical support using the [Support Center](https://supportcenter.devexpress.com/ticket/list) to check if such issues are specific to our controls rather than the platform in general. I created separate tickets there on your behalf and put them in our processing queue. We will answer you there shortly.

**Comment by drasticactions** [comment]
Closing this, as it's DevExpress related.

**Comment by danch15** [comment]
Hello @DmitryRomenskiy, see here: https://supportcenter.devexpress.com/ticket/details/t1092373/android-some-devexpress-devcontrol-issues-in-the-net-maui-1-0
