### ISSUE TITLE
Modify all Color/Brush pairs so that the Brush is the source of truth but Color matches Brush when it can

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#760]
Brush/Color pairs like this

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/VisualElement.cs#L204-L216

Aren't kept in sync on the Controls side of the code which is causing crashes on the compatibility side of the renderer code. Because the renderers still use the "Color" part of these APIs as well as the Brush.

https://github.com/dotnet/maui/blob/main/src/Compatibility/Core/src/Android/VisualElementRenderer.cs#L220

1) We need a defined way to keep these Color/Brush pairs in sync on the controls side so the renderers don't have to worry about the behavior
2) The compatibility renderers need to be updated to only use brush. I realize we don't really want to touch the compatibility code but with the new changes to color being a nullable property we have to
3) We should obsolete the color side of all of these properties for MAUI v1 and then remove them in MAUI v2

**Comment by jsuarezruiz** [comment]
This is already implemented.
