### ISSUE TITLE
Binding relative source type intellisense only shows classes with default constructor

### ISSUE THREAD

**Issue by CiarogSoftware** [dotnet/maui#7608]
### Description

See issue in Xamarin repo [here](https://github.com/xamarin/Xamarin.Forms/issues/8680)

When working in XAML, in any binding, use {Binding Source={RelativeSource AncestorType={x:Type viewModels:

Intellisense will only display viewmodels with default constructors

### Steps to Reproduce

Create a new MAUI app
Create a class "TestService"
In MauiProgram.cs register TestService for dependency injection using `builder.Services.AddSingleton<TestService>();`

Create a folder for ViewModels called viewModels
Add a viewModel "HomeViewModel" with a parameter of type TestService

Add a ContentPage Home.xaml
Add a namespace reference `xmlns:viewModels="clr-namespace:MauiApp1.ViewModels"`
Add a CollectionView and attempt to bind to HomeViewModel
`<CollectionView ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type viewModels:`
See intellisense does not offer HomeViewModel

Now edit HomeViewModel.cs and remove the parameters in the constructor
Go back to Home.xaml and delete the `:` and re-add it, you will see HomeViewModel in the intellisense

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

No

**Comment by CiarogSoftware** [comment]
I want to add that if you type the missing member in manually, it works perfectly.

I have created a test project to show the issue [here](https://github.com/CiarogSoftware/IntellisenseProblemSample)

The README.md links to the file showing the issue.

**Comment by mgoertz-msft** [comment]
@drasticactions Yes, this is handled in our XAML IntelliSense code.

@CiarogSoftware, would you mind opening a feedback ticket through Visual Studio's Report a problem functionality? That way it gets into our work item tracking in Azure DevOps. Thanks.

**Comment by CiarogSoftware** [comment]
@mgoertz-msft Reported now [link](https://developercommunity.visualstudio.com/t/Binding-relative-source-type-intellisens/10058938)

Thanks for your help

**Comment by jfversluis** [comment]
Issue transferred to the right place!
