### ISSUE TITLE
iOS CollectionView selects Items SelectionMode="None"

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7614]
### Description

Hello, I am using CollectionView and I have the property SelectionMode="None".

On Android it works as expected,
on iOS sets a selection color.

You could fix this with VisualState, which is not an option as BackgroundColor is different for each element and is defined by the binding
![iOS](https://user-images.githubusercontent.com/53478848/171039934-3d3fea58-43d2-40f4-a843-79b6564b4f20.gif)
![Android](https://user-images.githubusercontent.com/53478848/171040037-e6e87d19-0127-4b82-b632-17bcfb37d455.gif)

![image](https://user-images.githubusercontent.com/53478848/171040087-29f0f439-6b16-4191-876b-3bcb17e19f54.png)

### Steps to Reproduce

1.Create Maui App
2.Add code
```
<CollectionView SelectionMode="None">
        <CollectionView.ItemsLayout>
            <LinearItemsLayout ItemSpacing="0" Orientation="Vertical" />
        </CollectionView.ItemsLayout>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Grid Padding="8,1,8,8">
                    <Label Text="{Binding .}" />
                </Grid>
            </DataTemplate>
        </CollectionView.ItemTemplate>
        <CollectionView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
                <x:String>Hallo</x:String>
            </x:Array>
        </CollectionView.ItemsSource>
    </CollectionView>
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.5

**Comment by VincentBu** [comment]
repro with vs main build 32530.83.main
