### ISSUE TITLE
Windows 7 desktop target?

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/maui#762]
eg `net6.0` i guess :/

**Comment by jonathanpeppers** [comment]
I moved the issue to dotnet/maui, I don't know what the plans are for Windows 7 support.

**Comment by SupinePandora43** [comment]
Xamarin.Forms had https://github.com/xamarin/Xamarin.Forms/tree/wpf

**Comment by Redth** [comment]
We are not planning this for .NET 6
