### ISSUE TITLE
[iOS]Grouped CollectionView have extra space on ios and maccatalyst

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#7620]
### Description

Group collectionview and set "GridItemsLayout.VerticalItemSpacing", you will see that there will be extra space under each grouped child item.

VerticalItemSpacing=“10”
![Simulator Screen Shot - iPhone 13 - 2022-05-31 at 14 36 42](https://user-images.githubusercontent.com/39898152/171111659-03d6c6dd-f713-4826-9252-c6c677733508.png)

VerticalItemSpacing=“20”
![Simulator Screen Shot - iPhone 13 - 2022-05-31 at 14 40 51](https://user-images.githubusercontent.com/39898152/171114339-7a35ba6d-5b9b-409b-a69e-84bc22d77e51.png)

### Steps to Reproduce

1. Download demo（Demo code is copied from https://github.com/dotnet/maui/issues/5014#issuecomment-1115026270)
[GroupDemo.zip](https://github.com/dotnet/maui/files/8802811/GroupDemo.zip)
2. Run the demo and you will see the extra space.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

 iOS 15.5

**Comment by kristinx0211** [comment]
verified repro on IOS with above project.

**Comment by Redth** [comment]
Can't repro on net7 after changing the vertical item spacing of 20

<img width="1136" alt="Screenshot 2022-11-28 at 2 06 10 PM" src="https://user-images.githubusercontent.com/271950/204360179-da40bbc6-7ce5-4a94-a424-c36ffbdd9675.png">
