### ISSUE TITLE
FlexLayout does not re-layout when a child's visibility changes

### ISSUE THREAD

**Issue by paulvarache** [dotnet/maui#7621]
### Description

In the linked reproduction repo, I used a FlexLayout with 2 images and a box view. I used a button to toggle the `IsVisible` of the first image. When `IsVisible` is `false`, the BoxView whose `Flex.Grow` is set to `1` does not reclaim the space left by the image.

Reproduction link: https://github.com/paulvarache/MauiIssueFlexLayoutIsVisible

```xaml
<FlexLayout>
    <Image
        x:Name="image"
        Source="dotnet_bot.png"
        HeightRequest="32" />
    <BoxView BackgroundColor="Red" FlexLayout.Grow="1" />
    <Image
        Source="dotnet_bot.png"
        HeightRequest="32" />
</FlexLayout>
```

Left image has `IsVisible` set to `true`
![Screenshot_1653983026](https://user-images.githubusercontent.com/5550089/171120176-7aec2343-d499-491e-95d1-36c4bf56a782.png)
Left image has `IsVisible` set to `false`
![Screenshot_1653983030](https://user-images.githubusercontent.com/5550089/171120181-b9afc765-96ec-4c0a-88d2-c675fa1a0648.png)

### Steps to Reproduce

1. Create a new project
2. Add a flex layout with some fixed size children and a child with `Flex.Grow="1"`
3. Toggle `IsVisible` on one of the fixed sized child

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by enisn** [comment]
Also same with https://github.com/dotnet/maui/issues/7482
