### ISSUE TITLE
Entry (IsPassword="True") Placeholder does not take a FontFamily

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7624]
### Description

Hello, if Entry is set to IsPassword="True" and you want to use a FontFamily, the placeholder won't accept that

Android 
![image](https://user-images.githubusercontent.com/53478848/171137441-c65eecbc-c3bb-42ef-927a-d623ce25ffe1.png)

iOS works
![image](https://user-images.githubusercontent.com/53478848/171137678-74dac4c0-80c5-4ba5-a0d5-0acb3e6c13ea.png)

### Steps to Reproduce

1.Create Maui App
2. Add Code
```
<VerticalStackLayout>
                        <Entry
                            FontFamily="RoboRegular"
                            HorizontalTextAlignment="Center"
                            IsPassword="True"
                            Placeholder="Password"
                            PlaceholderColor="Black}"
                            Text="{Binding Password}"
                            TextColor="Black"
                            VerticalTextAlignment="Center" />
                        <Entry
                            FontFamily="RoboRegular"
                            HorizontalTextAlignment="Center"
                            IsPassword="False"
                            Placeholder="Password"
                            PlaceholderColor="Black}"
                            Text="{Binding Password}"
                            TextColor="Black"
                            VerticalTextAlignment="Center" />
  </VerticalStackLayout>
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
verified repro on android 12 with above code.
