### ISSUE TITLE
Build / Publish solution in Developer PowerShell

### ISSUE THREAD

**Issue by FarhadAmjad** [dotnet/maui#7625]
### Description

I have 2 issues which are related: 1) Build publish using powershell 2) IPA file not generated.

(1) 
I have a solution with multiple projects. main mobile project has target frameworks android and ios, the supporting projects contain my net 6.0 code which are libraries referenced by the main project.

I use the following command to publish
dotnet publish -f:net6.0-ios -c:Release /p:_DotNetRootRemoteDirectory=/Users/user220094/Library/Caches/Xamarin/XMA/SDKs/dotnet/

And would get errors:
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\repos\Avant\Avant.CustomerApp.Code\obj\project.assets.json' doesn't have a target for 'net6.0-ios'. Ensure that restore ha
s run and that you have included 'net6.0-ios' in the TargetFrameworks for your project. [C:\repos\Avant\Avant.CustomerApp.Code\Avant.CustomerApp.Code.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\repos\Avant\Avant.Blazor.Shared\obj\project.assets.json' doesn't have a target for 'net6.0-ios'. Ensure that restore has r
un and that you have included 'net6.0-ios' in the TargetFrameworks for your project. [C:\repos\Avant\Avant.Blazor.Shared\Avant.Blazor.Shared.csproj]

The supporting libraries are net 6 class library project hence I cannot add target net6.0-ios as target framework. When I publish from Menu > Build > Publish Selection, I do not get the same error and completes the process. 

(2)
But it does not create .ipa file.

### Steps to Reproduce

1. Create .Net Maui Project with Blazor template
2. Set target framework android, ios
3. Add Class Library project target framework net 6.0, this project would contain helper classes, services, abstractions etc.
4. Add class library to dependencies of maui project
5. build or publish from developer powershell -> error occurs - details in description above
6. Publish using Publish Selection in Build menu, completes but does not generate IPA file.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

NA

### Did you find any workaround?

no work around found.

**Comment by RichardMarsh** [comment]
Right now the tooling in VS doesn't create IPAs, the only way is through the cli

That said, try adding the two switches to your build statement

/p:RuntimeIdentifier=ios-arm64
 /p:ArchiveOnBuild=true

So that it looks like this

`dotnet publish -f:net6.0-ios -c:Release  /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64`

In addition, see if these[ docs](https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview#publish) can help and ensure your workloads are up to date

**Comment by EmilyFeng97** [comment]
This issue also reproduce when runnuing the following command to publish the application with the deployment target set to Windows Machine.
`msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:TargetFrameworks="net6.0-windows10.0.19041;net6.0" /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="YOUR_CERT_THUMBPRINT_HERE" /p:PackageCertificatePassword="AnyTestPasswordYouLike"`
![image](https://user-images.githubusercontent.com/66412474/171584404-a11062d9-0ac7-4309-835b-0fd079dccdac.png)

**Comment by FarhadAmjad** [comment]
I have the switches mentioned above already and the issue persists.

**Comment by FarhadAmjad** [comment]
@jfversluis that works. so to publish we have to use the main project where the platforms are defined. :)
