### ISSUE TITLE
Button CornerRadius does not work yet

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#7626]
### Description

On iOS, the CornerRadius button is ignored when using a style

```
    <Style x:Key="testStyle" TargetType="Button">
        <Setter Property="Background">
            <Setter.Value>
                <LinearGradientBrush StartPoint="0,1" EndPoint="1,0">
                    <GradientStop Offset="0.1" Color="#0a7af0" />
                    <GradientStop Offset="1.0" Color="#7ac3f3" />
                </LinearGradientBrush>
            </Setter.Value>
        </Setter>
    </Style>
```

iOS
![image](https://user-images.githubusercontent.com/53478848/171140278-81e0462e-5236-4cdf-9bed-32d4454b957c.png)

Android
![image](https://user-images.githubusercontent.com/53478848/171140567-fa34d611-c5a1-45cb-95d1-b5ac1c7852d9.png)

### Steps to Reproduce

1.Create Maui App
2.Add code
```
        <Button
            CornerRadius="15"
            HeightRequest="40"
            Style="{StaticResource testStyle}"
            Text="Log In"
            TextColor="White" />
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.5

**Comment by jsuarezruiz** [comment]
Is the same or similar to https://github.com/dotnet/maui/issues/7488
