### ISSUE TITLE
[Android] Editor typing is inconsistent

### ISSUE THREAD

**Issue by bhuvan94** [dotnet/maui#7627]
### Description

While typing large text in edit control, cursor automatically moves to next line.

### Steps to Reproduce

1. Create Maui app.
2. Add Editor control.
3. Run the app in Android, type longer text or run this sample .[MauiApp7.zip](https://github.com/dotnet/maui/files/8805048/MauiApp7.zip)
 
**Actual Output**

https://user-images.githubusercontent.com/20217737/171172521-4ad71ed2-0a67-41e1-9a6d-3d6ee3971dcb.mp4

 

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

None

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by An0d** [comment]
Got the same behavior

**Comment by ncarandini** [comment]
Same to me.

**Comment by An0d** [comment]
Noticed it happens when setting HeightRequest.

If you configure AutoSize, it works
