### ISSUE TITLE
Rendering is not visible before rebuilding the entire control

### ISSUE THREAD

**Issue by PraveenGopalsamy** [dotnet/maui#7639]
### Description

Hi, I'm trying to perform drawings based on the interaction. In windows, the **Draw** method gets invoked at load time but there is no rendering in the UI. This didn't get worked until rebuilding the entire application using the InvalidateMeasureOverride() method.

XAML

```
<ContentPage.Content>
       <local:SampleView />
 </ContentPage.Content>
```

C#

```
public class SampleView : GraphicsView
{
    public SampleView()
    {
        Drawable = new GraphicsDrawable();
    }

    protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
    {
        return new Size(widthConstraint, heightConstraint);
    }
}

public class GraphicsDrawable : IDrawable
{
    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        // Draw something here.
        canvas.FillColor = Colors.Yellow;
        canvas.FillRectangle(dirtyRect);
        canvas.DrawRectangle(dirtyRect);
        canvas.DrawString("Welcome to MAUI !!!", 10, 50, HorizontalAlignment.Left);
    }
}
```

### Steps to Reproduce

1. Create a new Maui App.
2. Create a new class, which extends the class from GraphicsView.
3. Create a new class that implements IDrawable, and assign this Drawable to GraphicsView.
4. Now draw a simple text or rectangle using the passed dirtyRect.
5. Here at load time or any interaction didn't get rendered. Once we have invoked the InvalidateMeasureOverride() method, the rendering gets visible.

Demo: [Windows rendering issue demo](https://user-images.githubusercontent.com/83585210/171255489-4803e3de-b543-46fe-8128-07e440ab16c5.mp4)

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

### Did you find any workaround?

Not Applicable.

**Comment by kristinx0211** [comment]
repro on windows with 17.3.0 Preview 2.0 [32531.271.main]. repro project:
[MauiApp5.zip](https://github.com/dotnet/maui/files/8810460/MauiApp5.zip)
