### ISSUE TITLE
Blazor MAUI integration err_addresss_invalid

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-MAUI-integration-err_addresss_inv/10052255)._

---
Hi,

We're developing a point of sale in Blazor, and we are trying to move into a MAUI app to run under Windows, iOS and Android. We added the Client and Shared projects to our new solution (which now has three projects, the third project being the MAUI side of things). The Client is set as a class library. Also added the references to the MAUI project. When running the project, we get our spinning busy wheel. This is in our index.html page. But it doesn't go beyond this.

Now in Blazor the index.html contains the scripts etc used by our Blazor pages, and Blazor does the routing e.g. @page "/backend" to go to the Index.razor page. The default page is Home.razor (@page "/")

But as a MAUI app it just seems to go to the index.html which in itself does nothing, and in the console (F12) we get this

>Failed to load resource: net::ERR_ADDRESS_INVALID

with no indication of what it is referring to.

All our razor pages are in the Client project, not in the MAUI project. And the index.html is also in the Client project now, not in the MAUI project (we removed it after the compiler complained of ambiguity).

Our MainPage.xaml in the MAUI project is this:

```



    
        
            
        
    


```

We are also using the latest webview:

```
	
	  
	

```

Why is the MAUI throwing the invalid address error?
We need it to route to our Home.razor page which has the paged defined with

```
@page "/"
```

We tried changing the HostPage within the BlazorWebView control to Home.razor but an unhandled win32 exception occurs. We just want the Blazor client to be hosted by the BlazorWebView/MAUI project. Hope this all makes sense. We don't know if we've done something wrong or it's just a buggy control being in its infancy. We are using Visual Studio 2022 Preview 17.3.0 Preview 1.1

Richard

---
#### Feedback Bot on 5/24/2022, 11:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SteveSandersonMS** [comment]
Hopefully this covers what you need, but if not, please let us know!
