### ISSUE TITLE
Maui Nightly builds

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7653]
### Description

I would like to be able to install nightly builds based on the main branch. I had a couple of issues where it has been said "Works fine on main" and I was not able to verify. Also I reported a couple of issues which have been fixed by a PR but no maui update has been released and I am stuck.

It would be nice to get a nightly installers just like the .NET runtime repo

### Public API Changes

No API change

### Intended Use-Case

We are no longer stuck in development because we have to wait for a new MAUI release. Also we are able to confirm if a bug also happens in main branch or not.

**Comment by drasticactions** [comment]
There already is, https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

Green Main builds should already be uploaded. If you run the workload steps from the Development guide, you can install them. It's also (technically) possible to download and install PR builds and install them, although that requires some "deep knowledge" (Setting up local nuget feeds and rollback files) and light hackery of the workload system. That stuff could be documented.

But yeah, if your fix landed in main, you should be able to follow the Develoment guide and run it.

**Comment by drasticactions** [comment]
If you use the rollback file for the GA build, that will roll it back

`dotnet workload install maui  --from-rollback-file https://aka.ms/dotnet/maui/6.0.300.json`

**Comment by danielftz** [comment]
> There already is, https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md
> 
> Green Main builds should already be uploaded. If you run the workload steps from the Development guide, you can install them. It's also (technically) possible to download and install PR builds and install them, although that requires some "deep knowledge" (Setting up local nuget feeds and rollback files) and light hackery of the workload system. That stuff could be documented.
> 
> But yeah, if your fix landed in main, you should be able to follow the Develoment guide and run it.

When I build execute 
```
dotnet tool restore
dotnet cake --target=VS 
```
inside of <PATH_TO_MAUI>/maui/bin/dotnet, I get 
```
Error: Bootstrapping failed for '<PATH_TO_<MAUI>/maui/bin/dotnet/build.cake'.
build.cake, line #0: Could not find script '<PATH_TO_<MAUI>/maui/bin/dotnet/build.cake'.
```

**Comment by Symbai** [comment]
Same, but that's not important because if I run VS (2022 preview) and debug the app it already uses the nightly build. Also `dotnet` uses the nightly build. So `dotnet cake --target=vs` doesn't seem necessary for me I just ignored it and it works fine.
