### ISSUE TITLE
Setting Border Height/Width at runtime causes unhandled exception

### ISSUE THREAD

**Issue by Cywizz** [dotnet/maui#7655]
### Description

Changing HeightRequest or WidthRequest of the Border control while debugging **Windows**  (Hot Reload) causes an Unhandled exception. 
Android works fine.

Unhandled Exception:  **"Specified argument was out of the range of valid values."**

### Steps to Reproduce

1. Create new MAUI APP
2. Add a Border control
3. Set initial HeightRequest and WidthRequest (Say 20 each)
4. Run app
5. Change any of the above values, i.e. remove the 2 to add a 5
6. App crashes due to invalid number
7. Launching the app with the invalid numbers (i.e. 0) will also cause the crash

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Not changing the numbers at runtime, or ensure you don't force an invalid number entry

### Relevant log output

```shell
{"Specified argument was out of the range of valid values."}
Message = "Non-negative number required. (Parameter 'height')"
```

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?.  How do you update the values (Hot Reload)? Tried but cannot reproduce it.
![issue-7655](https://user-images.githubusercontent.com/6755973/171375778-6ecf241f-1f43-45f6-a84c-ccfdc4c57270.gif)

**Comment by Cywizz** [comment]
[MauiApp8.zip](https://github.com/dotnet/maui/files/8813103/MauiApp8.zip)

Sample project attached
