### ISSUE TITLE
No maui template in list

### ISSUE THREAD

**Issue by csandoy** [dotnet/maui#7661]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have added .NET Multi-platform App UI development to Viseual Studio 2022 preview 
but Maui does not show up in list when I create a new project

**Comment by derKosi** [comment]
https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio

I had the same issue, and isntalled the maui workload with a dotnet command

dotnet workload install maui

I think.
I am still evaluatin if that really helped to be honest

**Comment by jfversluis** [comment]
You could also try to install the templates with the command `dotnet new -i Microsoft.Maui.Templates`. I think for the most part the templates are installed correctly, unfortunately there are still instances where this doesn't happen. We're aware of this issue and working on getting this resolved. Hope that you are unblocked for now, let us know if that is not the case.
