### ISSUE TITLE
The Placeholder property of IPlaceholder is currently read-only (allow it to be modified)

### ISSUE THREAD

**Issue by nacompllo** [dotnet/maui#7662]
### Description

The Placeholder property of IPlaceholder is currently read-only, it would be appropriate to allow it to be modified if necessary.

<img width="711" alt="170742091-3a4dd332-f887-42e6-b623-4d88fc82efdc" src="https://user-images.githubusercontent.com/20904914/171405869-72dea551-dbf1-4394-a9c2-44b0524b7d8c.png">

### Steps to Reproduce

Check the IPlaceholder interface and verify that the Placeholder property is read-only. I should have { get; **set;** } to also allow to modify it.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

**Comment by hartez** [comment]
This doesn't need a setter in MAUI Core - this is the responsibility of the implementing SDK. And you don't need it for the particular issue you're trying to solve - see [my comment](https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/issues/113#issuecomment-1143936686).
