### ISSUE TITLE
Build and deploy for windows target in CLI

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/maui#7678]
### Description

In Maui, you can build and deploy for every platform with CLI except windows. For windows you need to open Visual Studio. I don't want to always open visual studio when I'm doing something simple, especially in blazor and comet apps. But there is no way to build for windows from CLI.

### Public API Changes

`dotnet build -t:Run -f net6.0-windows`

### Intended Use-Case

Easier windows build

**Comment by drasticactions** [comment]
AFAIK this is an issue with WinUI. WinUI only just got support for the dotnet CLI tooling, and it may not support building and deploying. I would verify that in their repo (https://github.com/Microsoft/microsoft-ui-xaml) and with a WinUI project. MAUI can't support it unless WinUI does.

**Comment by jfversluis** [comment]
A lot has changed in the past few months around this. Please also check the updated documentation we have for this here:  https://learn.microsoft.com/dotnet/maui/windows/deployment/overview?view=net-maui-7.0

If you still experiences issues with this, feel free to open a new issue with all the (updated) details. Thanks!
