### ISSUE TITLE
TypeConverter not respected when evaluating Binding

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#7683]
### Description

When evaluating a `Binding` and the evaluated value type does not match the target type of the `BindableProperty`, the binding should check if a `TypeConverter` is available to perform the necessary conversion. This is convenient, as we do not always want to depend on UI-related types from `Microsoft.Maui.Controls`, `Microsoft.Maui.Graphics` etc. in the underlying `ViewModel`s.

This was working correctly in Xamarin.Forms, but I have discovered it is no longer working in MAUI, after migrating some code.

### Steps to Reproduce

Download and run the attached MAUI sample project.

[MauiTestApp.zip](https://github.com/dotnet/maui/files/8821746/MauiTestApp.zip)

The sample project has a single `Page` with a single `ViewModel`. The `ViewModel` exposes a collection of strings representing color names. The user can choose one of the color names with a `Picker` and that color name is bound to the `TextColor` property of two `Label`s. The first `Label` binds directly to the string property, assuming the `TypeConverter` of the `Color` type would kick-in to do the necessary conversion. The second `Label` binds to the string property via a `IValueConverter` like the following one:

```csharp
public class ValueTypeConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var typeConverter = GetConverter(targetType);

        return typeConverter.ConvertFromInvariantString((string)value);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var typeConverter = GetConverter(targetType);

        return typeConverter.ConvertToInvariantString(value);
    }

    private static TypeConverter GetConverter(Type targetType)
    {
        // Code omitted for brevity.
    }
}
```

When selecting a color from the `Picker`, notice how the first `Label` does not change its `TextColor`, while the second one changes the `TextColor` correctly. Apparently the `TypeConverter` applied to the `Color` type is not respected.

I have double-checked and the `Color` type is declared like this in `Microsoft.Maui.Graphics`:

```csharp
namespace Microsoft.Maui.Graphics
{
    [DebuggerDisplay("Red={Red}, Green={Green}, Blue={Blue}, Alpha={Alpha}")]
    [TypeConverter(typeof(Converters.ColorTypeConverter))]
    public class Color
    {
        // Code omitted for brevity.
    }
}
```

For reference, I have attached a similar app in Xamarin.Forms:

[XamTestApp.zip](https://github.com/dotnet/maui/files/8821795/XamTestApp.zip)

Notice that in Xamarin.Forms both `Label`s change their `TextColor` accordingly.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

### Did you find any workaround?

The workaround i have found is to implement a custom `IValueConverter` that simply calls the necessary `TypeConverter` to perform the desired conversion.

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by ryanaw83** [comment]
Although this isn't directly related... there looks to be another bug with value converters: value converters aren't being called for custom controls.  i.e. in the code below the value converter doesn't ever get called

`<cc:CustomControl BackgroundColor="{Binding PriorityRanking, Converter={StaticResource PriorityRankingToBackgroundConverter}}" />`

**Comment by DP-Technology-LLC** [comment]
I am still seeing this issue in 7.0.

**Comment by jsuarezruiz** [comment]
Reviewed in the current main branch and this issue have been fixed by: https://github.com/dotnet/maui/pull/9814

![issue-7683](https://user-images.githubusercontent.com/6755973/232799538-10637351-f929-4766-b3b4-b46795ed3191.gif)
