### ISSUE TITLE
[IOS] Launch performance

### ISSUE THREAD

**Issue by NielsKnaap** [dotnet/maui#7687]
### Description

For the past few months I've been comparing Xamarin.forms and .NET MUAI.
Among other things, I looked at the startup speed of the application on iOS and Android.

To make the differences clear, I developed the same application for Xamarin.forms and .NET MAUI.

For Android I used the script from jonathanpeppers. Here I did indeed see an improvement as you point out in the latest devblog and in the readme from jonathanpeppers. 

Now there is little to be found about the performance of iOS. I used Xcode instruments here to measure the startup speed of the applications. My results indicated that the .NET MAUI application launches 9% slower. After that, I zoomed in on the different startup components, which showed the "WillFinishLaunchingWithOptions" component to take 235 times longer:

| Activity                                     | Xamarin    | .NET MAUI   |
|----------------------------------------------|------------|-------------|
| Launching – UIKit Initialization             | 0.0240342s | 0.02698242s |
| Launching – UIKit Scene Creation             | 0.0003936s | 0.00042555s |
| Launching - WillFinishLaunchingWithOptions   | 0.0000899s | 0.02119327s |
| Launching - DidFinishLaunchingWithOptions    | 0.2511294s | 0.24910752s |
| Launching – Initial Frame Rendering          | 0.0233976s | 0.03332989s |

I see the same result when I create a new "Xamarin.forms blank" project and compare it with a new .NET MAUI project.

Now I don't know enough about what happens in this startup part. But was wondering if this is known? And what could make such an impact on the WillFinishLaunchingWithOptions?

### Steps to Reproduce

1. Create a new Xamarin.forms blank project
2. Create a new .NET MAUI project
3. Add development certificate for provisioning
4. Build and deploy to physical iOS device (I used a iphone 7 on iOS 15.4.1)
5.  Use Xcode instrument launch to record a trace file of application startup

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4.1

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by jonathanpeppers** [comment]
@NielsKnaap I think a better comparision vs the `dotnet new maui` template would be a Xamarin.Forms template using shell. You could also take out shell & the dotnet bot image from the MAUI template to compare against a blank Forms app.

I also heard that using Xcode/instruments is probably not the right way to go, as it introduces a lot of overhead to the app launching. We don't have docs, but here is the method used for measuring iOS startup for the .NET fundamentals teams' benchmarks:

* https://github.com/dotnet/performance/pull/2355
* https://github.com/dotnet/performance/pull/2404

It's using [xharness](https://github.com/dotnet/xharness) to launch the app normally (no profiler attached), then looking at log messages to get the time. I would do this on a physical device and not a simulator.

**Comment by mattleibow** [comment]
I added the numbers up and the difference is very small, maybe 31ms?

The main reason for the difference in WillFinishLaunchingWithOptions is because we are now doing more work in there - and moved things into there from DidFinishLaunchingWithOptions:

https://github.com/dotnet/maui/blob/ed349ff262691f6aafe559d7eb8aec92818097a0/src/Core/src/Platform/iOS/MauiUIApplicationDelegate.cs#L27

Activity | Xamarin | .NET MAUI
-- | -- | --
Launching – UIKit Initialization | 0.0240342 | 0.02698242
Launching – UIKit Scene Creation | 0.0003936 | 0.00042555
Launching -  WillFinishLaunchingWithOptions | 0.0000899 | 0.02119327
Launching - DidFinishLaunchingWithOptions | 0.2511294 | 0.24910752
Launching – Initial Frame Rendering | 0.0233976 | 0.03332989
  | **0.2990447** | **0.33103865**
