### ISSUE TITLE
[iOS]Wrong cursor position in Editor on ios and maccatalyst

### ISSUE THREAD

**Issue by singhwong** [dotnet/maui#7691]
### Description

If you insert other languages (such as Chinese or Japanese, etc.) into the Editor text, the cursor will go to the end of the text every time you delete non-end characters.

https://user-images.githubusercontent.com/39898152/171622370-5e8af37d-2736-4558-bde1-45282fd47cec.mov

### Steps to Reproduce

1. Download demo.
[EdiorCursorIssueDemo.zip](https://github.com/dotnet/maui/files/8823386/EdiorCursorIssueDemo.zip)
2. Running the demo, when deleting characters in the first Editor, the cursor position works fine, but when deleting characters in the second Editor, the cursor moves to the end of the text.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

 iOS 15.5

**Comment by kristinx0211** [comment]
verified repro on mac with above project.

**Comment by singhwong** [comment]
It was fixed in maui 6.0.452, so I closed this issue.
