### ISSUE TITLE
[MacCatalyst] Application crashes when it is signed with added Entitlements.plist

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#7693]
### Description

I am trying to upload my application to the apple store. For that purpose the store promps and asks me to sandbox the application - the sandbox is required by the store. In order to enable the sandbox an Entitlements.plist is added. However, after building the application with a codesign parameter it crashes when I try to open it.

<img width="328" alt="Screenshot 2022-06-02 at 14 48 44" src="https://user-images.githubusercontent.com/9336157/171627578-2c45a7d0-e646-4e20-a11f-d2d0edb11375.png">

I have found a thread where somebody complained about the same issue, but the workaround suggested there doesn't work for me: https://github.com/dotnet/maui/issues/5399#issuecomment-1107700318

### Steps to Reproduce

Build the attached application using the following command:
dotnet build HelloMaui.csproj -c Release -f net6.0-maccatalyst -p:CodesignKey="ENTER YOUR KEY HERE" -p:CodesignProvision="ENTER YOUR PROVISION HERE" /p:CreatePackage=true -p:ApplicationVersion=1.1.9

You need to code sign the application with a real provisioning profile in order to reproduce the issue. By simply building it in Release (without sign) everything is working.
[HelloMaui.zip](https://github.com/dotnet/maui/files/8823620/HelloMaui.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.4

### Relevant log output

```shell
Here is some output from the terminal when I try to open the application:

The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000039c2f40 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by drasticactions** [comment]
Did you try doing this with a new Mac Catalyst app (Ex. `dotnet new maccatalyst`) without MAUI? Does it blow up in the same way?

**Comment by rolfbjarne** [comment]
Are you trying to execute the app that you just built for distribution (with an "Apple Distribution: ..." certificate) locally? If so, that won't work, the app has to be uploaded to the app store, then Apple will do some magic and re-sign it, and then when you download the app (for instance through TestFlight), it'll work.

**Comment by APopatanasov** [comment]
@rolfbjarne You are right. After installing the application from TestFlight it is working as expected - the issue is observed only locally. 

Thanks for the information and help. I am closing the issue.
