### ISSUE TITLE
WinUI: Pushing the same page instance onto a NavigationPage after popping it causes a crash.

### ISSUE THREAD

**Issue by Keflon** [dotnet/maui#7698]
### Description

UWP only: 
Push a ContentPage onto a NavigationPage.
Pop the page, using the back button.
Push the same page again.
Exception = {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"}

Minimal repro:
https://github.com/Keflon/MauiNavigationBugRepro

### Steps to Reproduce

1. Create a MAUI app.
2. Make this change in App.xaml.cs:
```csharp
public App()
{
    InitializeComponent();
    //MainPage = new AppShell();
    MainPage = new NavigationPage(new MainPage());
}
```
In MainPage.xaml.cs add the following, where `_childPage` is set to an instance of a Maui Page
```csharp
private void OnNavigateClicked(object sender, EventArgs e)
{
    App.Current.MainPage.Navigation.PushAsync(_childPage);
}
```
3. Add a Button in MainPage.xaml that raises the click handler.
```xaml
<Button 
    x:Name="NavigateBtn"
    Text="UWP Navigate Bug"
    SemanticProperties.Hint="Demonstrates a UWP navigation bug"
    Clicked="OnNavigateClicked"
    HorizontalOptions="Center" />
```

4. Click the Button.
5. Press the back button.
6. Click the button.
7. Notice UWP crashes with Exception = {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"}

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Windows

### Affected platform versions

Latest

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Updated the title. MAUI uses WinUI, not UWP.

**Comment by kristinx0211** [comment]
verified repro on windows using above repro project.

**Comment by mlancione** [comment]
Any update on this issue? I'm running into the same exception when trying to create a SwapChainPanel custom renderer in WinUI.

**Comment by mlancione** [comment]
The issue with SwapChainPanel seems unrelated to this issue. The issue was caused by Maui's Background assignment which is not allowed on WinUI's SwapChainPanel. I had to add an empty property mapping handler for the Background property via the ModifyMapping method to prevent the crash.

**Comment by dgerding** [comment]
@mlancione Would you be willing to share the code fragment that you implemented as a workaround with Background?

**Comment by mlancione** [comment]
@dgerding In my Maui custom View constructor I added this:
```
this.propertyMapper = new PropertyMapper<View>();
var overrides = GetRendererOverrides<CustomView>();
overrides.ModifyMapping( "Background",
        ( handler, view, act ) =>
        {
        } );
```

**Comment by julioenabled** [comment]
![image](https://user-images.githubusercontent.com/54295801/201619041-62642ae7-b98d-439a-8d03-e06ba7f00254.png)
I got same error using a singleton page and then navigating back and forth.

**Comment by SqueakyBed** [comment]
Same error using Maui Blazor App too. It crashes as soon as I push the settings page. If I remove the button from the xaml it works just fine!

![image](https://user-images.githubusercontent.com/66184708/205400570-c449cc0e-8b5b-4503-82f3-018d65e3da7c.png)

![image](https://user-images.githubusercontent.com/66184708/205400475-0208df5f-4902-4ea0-bbb2-193f0ab02aeb.png)

![image](https://user-images.githubusercontent.com/66184708/205400715-4d580310-3cac-4c88-abbb-5dbbb80ab207.png)

**Comment by drasticactions** [comment]
Notes on this so far:

The Unhandled exception is thrown because "NavigationFailed" is not handled in the MAUI `NavigationRootView`. If you handle that, you can continue down the stack to see the "real" exception.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/898335/217428147-41686b16-86fc-4b2e-907c-fc98fec8be73.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/898335/217428309-24bc2eeb-1b4a-403f-a16e-7b66d166898b.png">

I'm not sure how the `PlatformView`s are generally handled in MAUI, but I _think_ when you navigate back and forth, the handlers are destroyed and recreated, and somewhere in there, it can't recreate the new session. Still need to look into that.

**Comment by drasticactions** [comment]
Okay, I made this more accessible to repro.

If you replace the `App.Current.MainPage` with an existing page, you can get the same `No installed components were detected` to throw.

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/898335/217444210-c2878c82-ed29-4c8c-b713-b6e8a73459ee.png">

**Comment by jsuarezruiz** [comment]
Will do more tests but, cannot reproduce it with the current main branch (7.0.200).

**Comment by jbe2277** [comment]
I just installed VS 17.4.5 which comes with a new MAUI version:

```maui-windows                  7.0.59/7.0.100         VS 17.4.33403.182```

The issue still occurs. See screencast:

![Maui-Win-Issue](https://user-images.githubusercontent.com/10452896/219084380-6292db26-4e8c-4153-afc6-6143f7709aa6.gif)

How to reproduce:
1. Clone https://github.com/jbe2277/waf/commit/ef8376017d9e7553214e9062fe1198f1ab104a2b or latest master
2. Open `./src/NewsReader/NewsReader.sln`
3. Set `NewsReader.MauiSystem` as startup project
4. Run it for Windows (error comes in Debug and Release config)

**Comment by drasticactions** [comment]
> Will do more tests but, cannot reproduce it with the current main branch (7.0.200).

https://github.com/drasticactions/MauiRepros/tree/main/MauiReusePageBug

On the Current MAUI stable and main, it throws with the same errors listed above.

**Comment by datvm** [comment]
How do you handle the `NavigationFailed` event to get the causing exception? I am having the same issue with MAUI Blazor: tapping a Blazor button to push another ContentPage, then press Back and the app crashes.

**Comment by PureWeen** [comment]
@datvm can you log a new bug?

**Comment by datvm** [comment]
@PureWeen  Hi, I don't know where to put the code in to log it. That's my question. How do I handle it or get the underlying exception that causes it? Right now all I get is the "Catastrophic failure ..." exception from the OP post.

**Comment by vsvsav** [comment]
There are a lot of problems with navifation in MAUI, and no problems with Android & iOS. So we rejected winui support.
Exception = {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"}

**Comment by omghb** [comment]
Please, fix this bug. 

It blocks our migration from Xamarin to MAUI for the Windows support. We have not found a workaround to overcome this crash.

**Comment by Murtaya** [comment]
Hitting this bug also.  I'm trying out Maui to see if our team can move to it, but the pushback on fixing such an easy-to-get error is not encouraging.
![image](https://user-images.githubusercontent.com/35792868/235055677-5b113a4d-55c5-4c89-b442-d72ffc643db0.png)

**Comment by axa88** [comment]
As this issue was marked fixed months ago, I was curious if anyone has confirmed it fixed using .net 8 preview?
Cant update to .net 8 myself do to other problems, but seems to me this is a critical issue yet not convinced it was addressed in the closing issue.
