### ISSUE TITLE
Layout incorrect using a horizontal linear layout inside a grid

### ISSUE THREAD

**Issue by iot-crazy** [dotnet/maui#7703]
### Description

I have a `CollectionView` which uses a `Grid` in the `ItemTemplate` which in turn contains another `CollectionView` with a `LinearItemsLayout` with horizontal orientation containing some rectangles (also tried with labels instead of rectangles. 

When the page first renders, the rectangles all appear lower than expected with the lower part of the rectangles all clipped. resizing the width of the window causes them to render as expected with the full rectangle visible and also the text for the outter collection moves slightly higher on the screen. Resizing the height of the window has no affect, neither does moving the window.

### Steps to Reproduce

1. Obtain the sample code here  [https://github.com/iot-crazy/MauiLayoutDemo](https://github.com/iot-crazy/MauiLayoutDemo)
2. Build and execute for windows
3. See the bottoms of the rectangles clipped
4. Change the width of the window
5. See the rectangles now rendered correctly

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

net6.0-windows10.0.19041.0, VS 2022 17.3.0 Preview 1.1, 

### Did you find any workaround?

Not yet.

**Comment by xtuzy** [comment]
ScreenShot
- Windows
  - Start App:
![sharex-20220603080542](https://user-images.githubusercontent.com/17793881/171760238-af7c8f66-685d-41b6-b40e-739eb3586ae0.png)

  - After Resize:
![sharex-20220603080556](https://user-images.githubusercontent.com/17793881/171760255-3935eeff-8975-4a49-b844-718803e8c07d.png)
- Android
![sharex-20220603083405](https://user-images.githubusercontent.com/17793881/171762205-4aa79dd6-f1d4-4224-9d8c-e9f2d02bbee9.png)

**Comment by kristinx0211** [comment]
verified repro on windows using repro demo with 17.3.0 Preview 3.0 [32606.354.main].

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 5.0. Can repro on windows platform with above project.
repro project: https://github.com/iot-crazy/MauiLayoutDemo
![demo0004](https://user-images.githubusercontent.com/82450723/237044560-c245c139-4777-4b4c-9df3-06e84225a804.gif)
