### ISSUE TITLE
Build and deploy slow

### ISSUE THREAD

**Issue by williambuchanan2** [dotnet/maui#7716]
### Description

Build and deploy of Maui apps is unbelievably slow. We are talking minutes rather than seconds.

This is on a relatively new laptop which doesn't have the same issue with other project types.

### Steps to Reproduce

Create a new maui app.
Build - takes anything from 2 to 5 minutes
Deploy - takes around 1 minute

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 11 Pro 21H2

### Did you find any workaround?

No

**Comment by xtuzy** [comment]
First time it is slow, but when run you can use hotreload.

**Comment by williambuchanan2** [comment]
> First time it is slow, but when run you can use hotreload.

We had to turn hot reload off because it caused too many issues. Plus it's only good for some changes so you still need to go through the process of build and deploy fairly regularly.

**Comment by janseris** [comment]
Debug is ok after first build
Release is as OP describes on every build

**Comment by jfversluis** [comment]
Thanks for the report! Sorry you're having this experience. Right now, the tooling and Visual Studio that .NET MAUI is running on are still in preview. Performance and developer productivity is top of mind always. I hope that as the development on the tooling for .NET MAUI progresses, this will become better over time. Additionally, unfortunately deploying to mobile emulators or devices is slower than developing for ASP.NET or Windows for instance.

I'm going to close this for now, by the time Visual Studio (and the tooling) reach a more mature and stable state, please let us know if this is still something that is bothering you. To make sure it gets routed to the right team directly, you might want to use the Help menu from Visual Studio. That's under Help > Provide Feedback and then choose the right option.

Thanks!
