### ISSUE TITLE
Maui multi target projects don't appear to support linked files?

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#7717]
### Description

I am trying to reduce code duplication between iOS and Mac for a number of platform specific helper classes. So I have looked into using linked files to add a file from platforms/iOS to platforms/MacCatalyst.
Compiling for Mac I get an error saying the platforms folder doesn't exist in the using clause I add for Mac. If I add another class to the MacCatalyst folder in the same namespace as the iOS file, compile fails with the class cannot be found.

So it appears linked files don't work within Maui projects, is this a bug or by design? If by design, how should we reduce code duplication across similar platforms?

### Steps to Reproduce

New Maui solution.
Add a class to the platforms/iOS folder.
Add a link to the above class in the platforms/MacCatalyst folder.
Add an interface for the class so you can register for DI.
Wire up the DI for iOS and Mac.
Compile for iOS, it works.
Compile for Mac, it fails as it can't locate the linked class.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Copying the actual file works, but does't solve the 'reduce duplication' issue.

**Comment by xtuzy** [comment]
You need see .csproj, whether the setting of your file is correct, or you can use #if#endif to set code only compile for ios and mac, that is best easy way.

**Comment by jfversluis** [comment]
Personally I don't really like linked files. I think they should work, but it might need some effort to get it right. I think the real question here is: 

> how should we reduce code duplication across similar platforms?

By default, putting something in one of the platform folders will only compile it for that platform. As described [here](https://docs.microsoft.com/dotnet/maui/platform-integration/configure-multi-targeting#configure-filename-based-multi-targeting). But we can add to this behavior by defining our own rules in the `csproj` file. You can see that described [here](https://docs.microsoft.com/dotnet/maui/platform-integration/configure-multi-targeting) in the Docs.

If you would add the code underneath to your `csproj` file, you can now compile files based on their filename. And as you can see whenever you do `.iOS.cs` it is included for both iOS and Mac Catalyst. Of course you can tweak this behavior, and filenames, as you please.

```xml
<ItemGroup Condition="$(TargetFramework.StartsWith('net6.0-android')) != true">
  <Compile Remove="**\**\*.Android.cs" />
  <None Include="**\**\*.Android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework.StartsWith('net6.0-ios')) != true AND $(TargetFramework.StartsWith('net6.0-maccatalyst')) != true">
  <Compile Remove="**\**\*.iOS.cs" />
  <None Include="**\**\*.iOS.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>

<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true ">
  <Compile Remove="**\*.Windows.cs" />
  <None Include="**\*.Windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>
```

Then inside of your classes, if there are differences for iOS and macOS, you can work with the `#if` directives.
