### ISSUE TITLE
Can't find my app resource file with iOS

### ISSUE THREAD

**Issue by dedet6** [dotnet/maui#7722]
### Description

When I run the app on iOS, none of my Labels show up. Indeed, I have a "Language" file in my Resources folder where there is all the content of my Labels in a .resx file.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Create a .resx file where you insert all the content of your Labels
3. Call the .resx file in your .xaml file
4. Run the app on iOS
5. Observe the bug

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Don't use a .resx file.

**Comment by Eilon** [comment]
Hi @dedet6 , could you post an app to a GitHub repo so that we can see exactly what code you have?
