### ISSUE TITLE
How can I build Universal 2 Mac builds?

### ISSUE THREAD

**Issue by nicksilverstein** [dotnet/maui#7725]
How can I build Mac Catalyst Universal 2 Builds?

I've figured out how to set the target indemnifier to maccatalyst-arm64 and maccatalyst-x64 but, how can I do maccatalyst-universal?

**Comment by nicksilverstein** [comment]
Any ideas on how to do maccatalyst-universal?

**Comment by drasticactions** [comment]
For debugging, I don't think it's possible to build a "Universal" binary. For "traditional" debug MacOS apps you're always going to get the individual platforms, and that's IMO what you would want anyway. 

For _publishing_ and releasing a final build, I'm also not sure. @rolfbjarne Is this a thing a user can do?

**Comment by rolfbjarne** [comment]
We've covered this in our release notes: https://github.com/xamarin/xamarin-macios/wiki/.NET-release-notes-Xcode-13.3#how-to-create-a-universal-app-with-support-for-multiple-architectures, do this:

```xml
<PropertyGroup>
    <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>
</PropertyGroup>
```

**Comment by drasticactions** [comment]
> We've covered this in our release notes: https://github.com/xamarin/xamarin-macios/wiki/.NET-release-notes-Xcode-13.3#how-to-create-a-universal-app-with-support-for-multiple-architectures, do this:
> 
> ```
> <PropertyGroup>
>     <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>
> </PropertyGroup>
> ```

And this is why I ask, I had no idea we could do this now. Awesome!

@nicksilverstein Can you try this in your project?
