### ISSUE TITLE
CollectionView SelectedItems not rendering on android until scrolling

### ISSUE THREAD

**Issue by TonyK-FmGroup** [dotnet/maui#7726]
### Description

A `CollectionView` with some items being selected in code behind works on window but not on Android, until the selected items are scrolled out of view and back again.

Possibly related to this older issue [https://github.com/dotnet/maui/issues/3342](https://github.com/dotnet/maui/issues/3342)

### Steps to Reproduce

1. Obtain the example solution here [https://github.com/TonyK-FmGroup/MauiSelectBugDemo](https://github.com/TonyK-FmGroup/MauiSelectBugDemo)
2. Execute in an Android emulator
3. Click the 'Select Some' button
4. Scroll the list, you'll see some items start to show their selected state

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android emulator api30, 

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
can be reproduced on android 12 with vs 17.3.0 Preview 3.0 [32605.41.main]. until scroll the list, items start to show their selected state.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0. Not repro on android platform with repo project https://github.com/TonyK-FmGroup/MauiSelectBugDemo
