### ISSUE TITLE
The invisible element holds space on iOS

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7727]
### Description

I created a custom control to show and hide text on tap. On iOS the control holds space even when it is invisible.

### Steps to Reproduce

Run the project. Click on the top text. It is make the bottom text invisible. But on iOS the space is still being hold by the invisible text
[MauiApp1.zip](https://github.com/dotnet/maui/files/8832093/MauiApp1.zip)
.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by hartez** [comment]
> I think this is no different in Xamarin.Forms. We make it invisible, but it doesn't collapse the space it is using.

No, invisible in Forms and MAUI.Controls means collapsed. Should not take up space.

**Comment by kristinx0211** [comment]
verified on windows, android and IOS:
The behavior on windows :
https://user-images.githubusercontent.com/99457000/174963716-a934c0c6-e412-48ce-bb69-14c8b2ef5b34.mp4
The behavior on Android:
https://user-images.githubusercontent.com/99457000/174964214-e943b969-1526-420f-8c83-704059ddf9c3.mp4
The behavior on IOS:
https://user-images.githubusercontent.com/99457000/174964696-c2acd765-2d16-4548-8194-c5692a172b49.mov

**Comment by HobDev** [comment]
Strangely on current Visual Studio Version 17.3.0 Preview 2.0 the iOS works fine but Invisible item holds space on Android. Tested with the above attached repro.

**Comment by HobDev** [comment]
Actually the size does not change with the change in visibility on Android. In the above repro project if the bottom label is invisible at the startup the size will not grow when it's IsVisible Property is set to true. On the other hand if the bottom label is Visible at the startup it's size will not decrease when It's IsVisible Property is set to false.

**Comment by hartez** [comment]
This is fixed on both platforms in the next release.
