### ISSUE TITLE
The app styles does not react when theme changes 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7730]
### Description

I described the app styles in C#. With the XAML  styles that are included in the default template the app changes the theme in real time. But the C# styles that I want to use the app does not change the theme in real time. Although the app theme changes after restart. 

### Steps to Reproduce

Run the repro project and change the theme of the device. The theme will be applied to the label and background. Now comment out the `ResourceDictionary` declaration in App.Xaml , run the project again and change the device theme. Now the theme will not be applied to the label whereas the label have style attached to it.  But it will adapt to the device theme after restart. 

[MauiApp1.zip](https://github.com/dotnet/maui/files/8832373/MauiApp1.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment]
You're using the `AppThemeBindingExtension` which doesn't look right. Seems to me that this scenario is simply not possible right now and the C# Markup package needs to implement ways to support the `AppThemeBindings`. If you still think there is an issue, please provide a reproduction without the use of C# Markup.
