### ISSUE TITLE
The theme does not apply on iOS

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#7733]
### Description

I created a maui project with default template and run it on iOS. When I changed the theme the UI does not adapted according to the selected theme. 

### Steps to Reproduce

Run the project on iOS and change the theme of the iOS simulator. 
[MauiApp1.zip](https://github.com/dotnet/maui/files/8832462/MauiApp1.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by jfversluis** [comment]
Seems to be something with the templates maybe? Because it does work on our .NET MAUI sample app we have in our repo... @rachelkang ?

**Comment by kristinx0211** [comment]
using the above template, the UI does not change with the theme of the iOS simulator's change, also I tried with other project, it changes with the theme.
