### ISSUE TITLE
Android app crashes after splash screen - [OpenGLRenderer] unknown bitmap configuration

### ISSUE THREAD

**Issue by yungfox** [dotnet/maui#7737]
### Description

While i was working on a project i'd been working flawlessly on for weeks my Android app started crashing at load after the splash screen. Basically all is good up to the default purple .net splash screen, but when the app should start everything crumbles. This is particularly baffling since it started happening seemingly out of nowhere mid coding, and at the time of me typing this i still haven't found a way to make it work, i've tried restarting Visual Studio, the Android emulator and my machine, deleting the build and rebuilding from scratch and deleting and reinstalling the Android Virtual Device. 
The first error in the debug console is ```[OpenGLRenderer] unknown bitmap configuration``` followed by a mile long stack trace, of which i included an excerpt (if you want me to include the full 800 lines let me know).
At this point i don't really know what to do, cause i can't seem to find the issue and it completely halted development for me. Nothing critical in fact, it was just a personal project. But still i'm putting this out there in case this occurs to somebody else as well.

### Steps to Reproduce

Just start debugging from Visual Studio. Currently running VS2022 v17.3.0 preview 1.1 and the suggested Pixel 5 - API 30 emulator on Windows 10 Pro 20H2 19042.1706

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 - API 30

### Relevant log output

```shell
Loaded assembly: /data/data/com.companyname.weather_maui_test/files/.__override__/System.ComponentModel.Primitives.dll [External]
Loaded assembly: Anonymously Hosted DynamicMethods Assembly [External]
[OpenGLRenderer] unknown bitmap configuration
[ather_maui_tes] runtime.cc:655] Runtime aborting...
[ather_maui_tes] runtime.cc:655] Dumping all threads without mutator lock held
[ather_maui_tes] runtime.cc:655] All threads:
[ather_maui_tes] runtime.cc:655] DALVIK THREADS (27):
[ather_maui_tes] runtime.cc:655] "main" prio=10 tid=1 Runnable
[ather_maui_tes] runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x716b2338 self=0x7a9dad0897b0
[ather_maui_tes] runtime.cc:655]   | sysTid=6116 nice=-10 cgrp=top-app sched=0/0 handle=0x7a9ed2ebc4f8
[ather_maui_tes] runtime.cc:655]   | state=R schedstat=( 8553462852 559252246 2511 ) utm=392 stm=462 core=1 HZ=100
[ather_maui_tes] runtime.cc:655]   | stack=0x7ffce10e7000-0x7ffce10e9000 stackSize=8192KB
[ather_maui_tes] runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
[ather_maui_tes] runtime.cc:655]   native: #00 pc 000000000054da9e  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+126)
[ather_maui_tes] runtime.cc:655]   native: #01 pc 000000000069615c  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+380)
...
[ather_maui_tes] runtime.cc:655]   at android.os.Handler.dispatchMessage(Handler.java:99)
[ather_maui_tes] runtime.cc:655]   at android.os.Looper.loop(Looper.java:223)
[ather_maui_tes] runtime.cc:655]   at android.app.ActivityThread.main(ActivityThread.java:7656)
[ather_maui_tes] runtime.cc:655]   at java.lang.reflect.Method.invoke(Native method)
[ather_maui_tes] runtime.cc:655]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[ather_maui_tes] runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[ather_maui_tes] runtime.cc:655] 
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6116 (ather_maui_test), pid 6116 (ather_maui_test)
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
```

**Comment by yungfox** [comment]
Update - recreating the app by creating a brand new project and pasting in the original source seems to have fixed the issue... The original project was created with VS2022 17.2 preview and the new one with 17.3 preview 1.1 and that's about the only difference i can find between the two projects, implying that has any influence with all this. I did notice some changes between the boilerplate code generated by the previous version of Visual Studio vs the current one, but that's to be expected when something like Maui is still in the works i guess.
Anyway, the problem seems to be solved for now, but that wasn't very practical and i could do it just because i didn't have all that much code in my project, i can see this being a much bigger headache if it happened on a larger project.

**Comment by yungfox** [comment]
Think i found the issue, setting ```Shell.FlyoutBehavior``` to ```Locked``` makes the app crash as i described above, any other value works just fine.

**Comment by VincentBu** [comment]
not repro with vs main build 32609.23.

**Comment by mattleibow** [comment]
Closing this issues as not reproducable.
