### ISSUE TITLE
Border set in maui styles.xaml is ignored in a xaml page

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#7744]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Border-set-in-maui-stylesxaml-is-ignore/10053643)._

---
[severity:I'm unable to use this version]
1. Using the current GA of maui (v1.0) [also present in previous RCs], 
2. if I create a new maui project with the default template
3. edit the mainpage.xaml to add a border around the image:
            
```
            ...
            
            
            
            ...
```
4. run the application in debug using an iOS simulator, an android emulator or as a windows app
5. the border does not appear.
6. If I change the border in the styles.xaml to a roundrectangle, e.g.
    
```
<style>
</style>
```
7. the border appears (using hot reload)
8. If I restart the debug session causing a recompile
9. the border has disappeared again.

I wasted a lot of time trying to understand what was wrong with my much more complex ResourceDictionary thinking such a basic thing must be tested.

This is one of several breaking quality issues which make migration from xamarin seemingly impossible at the moment (others include  in a ResourceDictionary does not compile ('Thickness does not exist in the namespace...') even though it is used in MS maui examples:
https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/resource-dictionaries
MSAL does not work with iOS...

---
#### Feedback Bot on 5/25/2022, 08:04 PM: 

(private comment, text removed)
#### Vincent Croft on 5/26/2022, 00:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MichelMichels** [comment]
I have the same problem. I resorted to using Frames, but the MSDN docs explicitly state to use Borders instead of Frames.

**Comment by SophisticatedConsulting** [comment]
I am reposting the original report as the copy from vs is missing the code:

To reproduce:
1. Using the current GA of maui (v1.0) [also present in previous RCs],
2. if I create a new maui project with the default template
3. edit the mainpage.xaml to add a border around the image: 
```
<Border>
            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center"</Border>
```
4. run the application in debug using an iOS simulator, an android emulator or as a windows app
5. the border does not appear.
6. While the app is running, if I change the border in the styles.xaml to a roundrectangle, e.g.
```
<Style TargetType="Border">
        <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
        <Setter Property="StrokeShape" Value="RoundRectangle 10,10,10,10"/>
        <Setter Property="StrokeThickness" Value="5"/>
    </Style>

```
7. the border appears (using hot reload)
8. If I restart the debug session causing a recompile
9. the border has disappeared again.

**Comment by SophisticatedConsulting** [comment]
And here is the workaround:
···
Replace in the generated template code:
`<Setter Property="StrokeShape" Value="Rectangle"/>`

as below:
```
<Style TargetType="Border">
        <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
        <Setter Property="StrokeShape">
            <Rectangle/>
        </Setter>
        <Setter Property="StrokeThickness" Value="1"/>
</Style>
```
The problem remains that the template code for a Border generated for a new maui project does not work (and I assume it should!)
