### ISSUE TITLE
CarouselView does not work on Windows (snapping and selection)

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#7749]
### Description

I have a CarouselView and I am trying to use it to select an image via CurrentItem. It appears that the snaps are not working (maybe related to #6356) and it does not select the item even if the view is on screen.

However, it appears setting the CurrentItem via the binding - setting Source in my VM - will cause the CarouselView to scroll to the image. It never gets to the image and then wraps, but at least it starts scrolling indicating that something happened.

### Steps to Reproduce

```xaml
<CarouselView Grid.Row="1"
                HeightRequest="100"
                ItemsSource="{Binding Sources}" CurrentItem="{Binding Source}">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <Grid Padding="6,0">
                <Image Source="{Binding}" Aspect="AspectFit" />
            </Grid>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

**Comment by cbaer-extron** [comment]
Are these connected?  [https://github.com/dotnet/maui/issues/7180](url)

**Comment by cbaer-extron** [comment]
This Issue has been left behind in 6.0-sr2.  I don't see any updates on it, and also not in the related issue [https://github.com/dotnet/maui/issues/7180](url) that I reported.  This renders CarouselView useless to anyone who wants to support Windows.
