### ISSUE TITLE
i am using windows 10 and i type this comant in visual code "dotnet restore"  

### ISSUE THREAD

**Issue by Divyeshpatel6073** [dotnet/maui#775]
it shows me this error 
error NETSDK1139: The target platform identifier ios was not recognized.

![image](https://user-images.githubusercontent.com/20996843/115143006-5e0bc180-a062-11eb-8689-b2fef439f36f.png)

**Comment by sps014** [comment]
It looks like you don't have ios workload installed , you can manually install it from below link or use maui-check tool.

For manual install download, 

iOS:

Windows: Microsoft.NET.Workload.iOS.14.4.100-preview.3.1326.msi

Also you don't forget to update nuget feeds

You can watch Jame's guide
https://youtu.be/yxahL0xF3RU
