### ISSUE TITLE
Android Emulator would not start

### ISSUE THREAD

**Issue by katkovd73** [dotnet/maui#7750]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

I created a few Maui projects to test it and the Android Emulators are not being loaded on start debugging. It is trying to load it for about 10 - 30 minutes and then it either crashes or freezes. Windows apps of the same projects are working great. I went through the instruction (https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup) and nothing helps.

I have experience working with XamarinForms and it has always been a pain to get  the Android emulator going. I hope , one day, it will just work right out of the box without any additional configurations and troubleshooting. Thank you for your help.

I am working on Windows 11. Below are the specs for my laptop.

OS Name	Microsoft Windows 11 Home
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LAPTOP-4252QAM0
System Manufacturer	HP
System Model	HP Laptop 17-cn0xxx
System Type	x64-based PC
System SKU	3C9N4UAR#ABA
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	AMI F.20, 3/3/2022
SMBIOS Version	3.3
Embedded Controller Version	69.18
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	883C
BaseBoard Version	69.18
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22000.527"
User Name	LAPTOP-4252QAM0\katko
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.7 GB
Available Physical Memory	17.0 GB
Total Virtual Memory	36.4 GB
Available Virtual Memory	17.5 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by bautistavirchar** [comment]
delete then re-create

**Comment by deepx** [comment]
Maybe this Video from @jfversluis helps to Setup your Emulator correctly:
https://youtu.be/nxdApcTMjz8

**Comment by jfversluis** [comment]
Without any description of what exactly goes wrong this is hard to diagnose, if not impossible.

As you have already found there are multiple guides out there, you might also want to look into Windows Subsystem for Android which allows you to run Android apps. 

If you still can't get it to work, please open a new issue, following the template and provide more details on what exactly isn't working: error messages, logs, etc. thanks!

**Comment by katkovd73** [comment]
It's not working well on the Windows Home edition. I did a bunch of troubleshooting, played with Hyper-V and BIOS settings and still wasn't be able to run an Android Emulator on my machine. The solution that worked for me was actually using my Android phone instead of an emulator. I enabled a developer mode on my phone, connected to my PC using USB cable and deployed on my phone via Visual Studio.
