### ISSUE TITLE
Grid children default ZIndex is wrong

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#7752]
### Description

Converting some XF code that relies on the default Index (obviously, as XF doesn't have ZIndex).
Adding controls to a grid that overlap each other should have a default ZIndex so that the latest is always on top of the previous. That doesn't appear to be the case with Maui.

### Steps to Reproduce

New Maui project, replace the MainPage content with the following code:

            var grid = new Grid()
            {
                RowSpacing = 1,
                ColumnSpacing = 1,
                BackgroundColor = Colors.Blue
            };

            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));

            for (int col = 0; col < 5; col++)
            {
                for (int row = 0; row < 5; row++)
                {
                    var frame = new Frame()
                    {
                        BackgroundColor = Colors.White,
                        HorizontalOptions = LayoutOptions.Fill,
                        VerticalOptions = LayoutOptions.Fill,
                    };

                    Grid.SetRow(frame, row);
                    Grid.SetColumn(frame, col);
                    grid.Children.Add(frame);
                }
            }

            for (int row = 0; row < 5; row++)
            {
                var label = new Label()
                {
                    Text = "Some long text bla bla bla dfgdfgdfg dfg d gd dgf dfg fg dg df dfg",
                    //ZIndex = 100,
                    TextColor = Colors.Black
                };

                Grid.SetRow(label, row);
                Grid.SetColumn(label, 0);
                Grid.SetColumnSpan(label, 5);
                grid.Children.Add(label);
            }

            Content = grid;

You will see on iOS, Droid and Mac that some of the text doesn't appear at all in some of the rows, and some that do appear don't show on all the columns.
Uncomment ZIndex and that resolves the issue on iOS and Droid but breaks Mac.

By default, the ZIndex should be the order the controls are added to the grid.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15, droid, Mac

### Did you find any workaround?

Forcing a ZIndex resolves the issue in this example, but with more complex layouts we would need to keep track of all the controls being added, when Grid itself should manage this.

**Comment by kristinx0211** [comment]
verified repro on android 12 with 17.3.0 Preview 3.0 [32605.41.main]. repro project:
[MauiApp6.zip](https://github.com/dotnet/maui/files/8843084/MauiApp6.zip)
