### ISSUE TITLE
Scrolling a CollectionView with SwipeView items causes exception on Windows

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#7757]
### Description

If you have a `CollectionView` where `SwipeView` is used in the `DataTemplate` and you are scrolling, you will eventually get an unhandled exception:

![image](https://user-images.githubusercontent.com/3163293/172020869-01eb49e7-cbcf-4582-82a5-09dfa923325c.png)

This seems to only happens on Windows. I have tested on Android too, and there it's fine.

### Steps to Reproduce

1. Create a new MAUI-application.
2. Update MainPage.xaml:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage">

    <CollectionView ItemsSource="{Binding Items}">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <SwipeView>
                    <Grid>
                        <Label Text="{Binding Id}" />
                    </Grid>
                </SwipeView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```

3. Update MainPage.cs:

``` CS
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();

        Items = TimeZoneInfo.GetSystemTimeZones().ToList();

        BindingContext = this;
        
	}

    public List<TimeZoneInfo> Items { get; }
}
```

4. Run the application on Windows.
5. Scroll the list.

Full sample project: https://github.com/pekspro/MauiIssues/tree/7757_Scrolling_a_CollectionView_with_SwipeView_causes_exception

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0

**Comment by kristinx0211** [comment]
can be reproduced on windows with above project. vs version 17.3.0 Preview 3.0 [32605.41.main].

**Comment by pekspro** [comment]
I've updated sample application to .NET 7. The same issue remains.

**Comment by KeithBoynton** [comment]
I can confirm this issue still remains in 8.0.100-rc.2.23502.2 is this going to get resolved for .net 8 ?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). This issue does not repro on Windows 11, Android 14.0-API34, iOS 17.0 and MacCatalyst with below Project:
[7757.zip](https://github.com/dotnet/maui/files/13455707/7757.zip)
![Scroll](https://github.com/dotnet/maui/assets/97647558/0a24f945-3560-4b50-8806-b8091502b17b)
