### ISSUE TITLE
Having trouble getting started

### ISSUE THREAD

**Issue by seabluescn** [dotnet/maui#7762]
### Discussed in https://github.com/dotnet/maui/discussions/7680

<div type='discussions-op-text'>

<sup>Originally posted by **seabluescn** June  2, 2022</sup>
I created a MAUI project using the system default template. After creating the project, I only changed one code, as follows:

```c#
   private async void OnCounterClicked(object sender, EventArgs e)
   {
        await DisplayAlert("Hello", "Hello World!", "OK");
    }
```

I debug from my Android phone and it works fine, but if I do the following sequence it throws an error:
1. Click the desktop icon to start the APP
2. Press the "back" button to exit the program
3. Click the icon again to start the APP (this time it should be recovery, not startup)
4. Click the "Click Me" button, the APP will crash

The debugging error message is as follows:

```
System.Reflection.TargetInvocationException
   Message=Exception has been thrown by the target of an invocation.
```

</div>

**Comment by deepx** [comment]
Verified with actual .NET MAUI Template and Android-Emulator API30.

**Comment by jfversluis** [comment]
Could you please retest with the latest release that happened 2 days ago at the time of writing? Thanks!
