### ISSUE TITLE
FlyoutBackgroundImage Not showing Windows and Crashes IOS

### ISSUE THREAD

**Issue by craigbosward** [dotnet/maui#7763]
### Description

After trying to add FlyoutBackgroundImage in an app i had several issues.  So to test.  Create New Maui App in VS 2022 Preview 17.11 v1.1.  in shell added FlyoutBackgroundImage.  
This works as expected in Android for https, jpeg, gif and png images.  
When clean and rebuild and then load winui the shell content displays but NO Image.  
When clean and rebuild and loading to IOS  in simulator iphone13 pro 15.5 the system stops in main at UIApplication.Main(args, null, typeof(AppDelegate));  platform exception loading.  
i also tried as an embedded resource using image resource as per docs,  but this made no difference.

![Screenshot_1654409417](https://user-images.githubusercontent.com/96669462/172037967-1afef6b1-ef54-483d-8aaf-c3140ed91a64.png)
![windows](https://user-images.githubusercontent.com/96669462/172037981-99adfdb0-ec0b-42e0-bacd-3079e0771761.png)
![ios](https://user-images.githubusercontent.com/96669462/172038393-6cf5eb3f-7b8b-4315-a6b0-87497673023c.png)

### Steps to Reproduce

1. create new Maui app.
2.  Added image as maui asset jpg. resources\images
3. changed shell to: 
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp3.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:local="clr-namespace:MauiApp3" FlyoutHeaderBehavior="CollapseOnScroll"   FlyoutBackgroundColor="AliceBlue"
   FlyoutBackgroundImage="aaa.jpg"
       FlyoutBackgroundImageAspect="Fill"
    Shell.FlyoutBehavior="Flyout">
    <Shell.ItemTemplate>
        <DataTemplate>
            <Grid ColumnDefinitions="0.2*,0.8*">
                <Image Source="{Binding FlyoutIcon}"  Margin="5"  VerticalOptions="Center"
               HorizontalOptions="{OnPlatform Default=Center, WinUI=Start}"
               HeightRequest="{OnPlatform Android=24, iOS=22, WinUI=56}"
               WidthRequest="{OnPlatform Android=24, iOS=22, WinUI=56}"/>

                <Label Grid.Column="1" Text="{Binding Title}"  FontSize="Title" FontFamily="OpenSansSemibold" VerticalTextAlignment="Center" TextColor="Red" FontAutoScalingEnabled="True"  FontAttributes="Italic" HorizontalTextAlignment="Start" />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>
    <ShellContent
        Title="Home" Icon="dotnet_bot.png"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />
    <ShellContent
        Title="Home2" Icon="dotnet_bot.png"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage1" />
    <ShellContent
        Title="Home3" Icon="dotnet_bot.png"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage2" />
</Shell>
Results are as per files attached above.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

Windows SDK 10.0.19041, IOs iphone simulator 13 pro 15.5

### Did you find any workaround?

not yet

**Comment by kristinx0211** [comment]
verified repro on windows with 17.3.0 Preview 3.0 [32605.41.main]. repro project: [MauiApp3.zip](https://github.com/dotnet/maui/files/8842443/MauiApp3.zip)
Android 12:
![image](https://user-images.githubusercontent.com/99457000/172110941-38e100a8-671a-4181-a8b6-7a49a9f12b6c.png)
windows: 
![image](https://user-images.githubusercontent.com/99457000/172111085-241146b3-7bda-4313-95db-8d5476ed63eb.png)

**Comment by jsuarezruiz** [comment]
```
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToUIViewController(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(UIWindow platformWindow, IWindow window, IMauiContext context)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiApp3.Program.Main(String[] args) in /Users/jsuarez/Downloads/MauiApp3/MauiApp3/Platforms/MacCatalyst/Program.cs:line 13
```

**Comment by jsuarezruiz** [comment]
> The iOS exception:
> 
> ```
> Microsoft.Maui.Platform.ToPlatformException: <Microsoft_Maui_Controls_Handlers_Compatibility_ShellRenderer: 0x7ff374e1edd0> found for MauiApp3.AppShell is incompatible
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Maui.ImageSourceExtensions.GetPlatformImageAsync(IImageSource imageSource, IMauiContext mauiContext)
>    at Microsoft.Maui.ImageSourceExtensions.LoadImage(IImageSource source, IMauiContext mauiContext, Action`1 finished)
>    at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutContentRenderer.UpdateFlyoutBgImageAsync()
>    at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutContentRenderer.UpdateBackground()
>    at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutContentRenderer.ViewDidLoad()
>    at UIKit.UIViewController.get_View()
>    at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRenderer.ViewDidLoad()
>    at UIKit.UIViewController.get_View()
>    at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRenderer.Microsoft.Maui.Controls.Platform.Compatibility.IShellFlyoutRenderer.get_View()
>    at Microsoft.Maui.Controls.Handlers.Compatibility.ShellRenderer.get_NativeView()
>    at Microsoft.Maui.Controls.Handlers.Compatibility.ShellRenderer.Microsoft.Maui.IElementHandler.get_PlatformView()
>    at Microsoft.Maui.Handlers.ViewHandler.MapInputTransparent(IViewHandler handler, IView view)
>    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
>    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
>    at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
>    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Layout, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.LayoutHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
>    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
>    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.ShellRenderer.SetElement(VisualElement element)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.ShellRenderer.Microsoft.Maui.IElementHandler.SetVirtualView(IElement view)
>    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
>    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
>    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
> ```

Preparing PR with the fix.
