### ISSUE TITLE
Border Margin

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#7764]
### Description

Border has gaps when no margins are set
![1](https://user-images.githubusercontent.com/42528522/172039060-a1149e81-d1d7-4e39-be18-dfde125cd71a.png)

### Steps to Reproduce

[MauiApp1.zip](https://github.com/dotnet/maui/files/8839464/MauiApp1.zip)

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

Manually set a margin of -2

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.3.0 Preview 3.0 [32605.41.main].
![image](https://user-images.githubusercontent.com/99457000/172104894-6790bda5-2f43-437b-89c3-08af2da27733.png)

**Comment by Martinedo** [comment]
Actually the workaround is to set `Margin="-1" StrokeThickness="0"` becuase `StrokeThickness = 1` by default.

**Comment by shameelfazul** [comment]
is there a fix for this? setting `StrokeThickness` adds margins even though its set to 0 ..

**Comment by hartez** [comment]
This may have been fixed by #10964, we need to verify.

**Comment by rmarinho** [comment]
This is still a issue on main, just tested on Android and iOS

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/pull/14402
