### ISSUE TITLE
The RuntimeIdentifier 'ios-arm64' is invalid.

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7765]
### Description

On Windows trying to publish my app using a mac host fails with `The RuntimeIdentifier 'ios-arm64' is invalid.` I've followed the documentation. I'm using MAIN branch. 

### Steps to Reproduce

in csproj file:
```XML
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>iPhone Distribution: XXX XXX (XXX)</CodesignKey>
    <CodesignProvision>XXXXXX</CodesignProvision>
    <ArchiveOnBuild>true</ArchiveOnBuild>
    <TcpPort>58181</TcpPort>
  </PropertyGroup>
```

in windows terminal:
```dotnet publish -f:net6.0-ios -c:Release  /p:RuntimeIdentifier=ios-arm64 /p:ServerAddress=192.168.178.54 /p:ServerUser=xxxxxx /p:ServerPassword=xxxxxxx /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/xxxxx/Library/Caches/Xamarin/XMA/SDKs/dotnet/```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Relevant log output

```shell
C:\Program Files\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(1739,3): error : Th
e RuntimeIdentifier 'ios-arm64' is invalid.
```

**Comment by jfversluis** [comment]
Could you try `dotnet publish MyProject.csproj` and then add the additional parameters?

**Comment by Symbai** [comment]
Thanks but unfortunately it results in the same error:

```
C:\Users\xxxx\source\repos\xxxx\xxxx>dotnet publish xxxx.csproj -f:net6.0-ios -c:Release  /p:RuntimeIdentifier=ios-arm64 /p:ServerAddress=192.168.178.54 /p:ServerUser=xxxx /p:ServerPassword=xxxx /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/xxxx/Library/Caches/Xamarin/XMA/SDKs/dotnet/
Microsoft (R)-Build-Engine, Version 17.2.0+41abc5629 für .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Projects to be restored are identified...
C:\Program Files\dotnet\packs\Microsoft.MacCatalyst.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(1739,3): error : Th
e RuntimeIdentifier 'ios-arm64' is invalid. [C:\Users\xxxx\source\repos\xxxx\xxxx\xxxx
xxxx.csproj]

C:\Users\xxxx\source\repos\xxxx\xxxx>
```

**Comment by fatb0tlp** [comment]
I am having the same exact error. Extreme difficulty in publishing anything meaningful for IOS and Maui. Has there been any additional insight into this issue?

The only article I can find about publishing an iOS app is here: https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview

Though I have followed the steps, I have had no success.

**Comment by Orgbrat** [comment]
I am having this same exact error (error : The RuntimeIdentifier 'ios-arm64' is invalid.)  when trying to publish my MAUI iOS application from command line. I have watched @jfversluis video at [Release Your .NET MAUI iOS App to the Apple App Store](https://www.youtube.com/watch?v=kpZi5xAvpZA&t=1186s) and also followed the Microsoft docs at [Publish a .NET MAUI app for iOS](https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview).

After trying both set of instructions multiple times, I have had no success.

`dotnet publish -f:net6.0-ios -c:Release /p:RuntimeIdentifier=ios-arm64 /p:ServerAddress=192.xx.xx.xx  /p:ServerUser=xxxxx /p:ServerPassword=xxxxx /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/xxxxxx/Library/Caches/Xamarin/XMA/SDKs/dotnet/`

Has anyone found a solution for this issue?

**Comment by Symbai** [comment]
> Has anyone found a solution for this issue?

I copied the project to the Mac and published it there using `dotnet publish -f:net6.0-ios -c:Release`. I dont think we will see a fix for this problem in the near future.

**Comment by jfversluis** [comment]
Looks like this is a bug in the .NET SDK as seen in this issue: https://github.com/dotnet/sdk/issues/21877

Please add your details there. Seems a workaround could be to add `--no-restore`

**Comment by fatb0tlp** [comment]
I was able to publish working through this thread:
https://github.com/dotnet/docs-maui/issues/681#issuecomment-1173703085
