### ISSUE TITLE
CollectionView not updating when direct content of ContentPresenter

### ISSUE THREAD

**Issue by eliolo** [dotnet/maui#7770]
### Description

When a CollectionView is the direct content of a ContentPage or ContentView with a ControlTemplate containing a ContentPresenter, the CollectionView doesn't behave as expected when items are added to it.
On Android the CollectionView is not updated until a swipe gesture has been made on the CollectionView.
On Windows the CollectionView is not updated until the window is resized. Also on Windows, the CollectionView cannot be scrolled.
Not tested on other platforms.

Reproduction project:
Visual Studio 17.3.0 Preview 1.1 MAUI template with modified App.xaml, MainPage.xaml and MainPage.xaml.cs
https://github.com/eliolo/CollectionViewInContentPresenter

❌ CollectionView as direct content:

Android
![android_bug](https://user-images.githubusercontent.com/54113463/172046401-eb387b14-e222-4b09-bed1-9c43ccb14f38.gif)

Windows
![windows_bug](https://user-images.githubusercontent.com/54113463/172046450-75a81498-971f-4704-b6a5-aa8fdf62a8cb.gif)

### Steps to Reproduce

1. Run reproduction project.
2. Press add item button to add item to CollectionView.
3. Items are not visible until above actions are taken.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 - API 30, Windows SDK 10.0.19041

### Did you find any workaround?

✅ Wrapping the CollectionView in a Grid:

Android
![android_working](https://user-images.githubusercontent.com/54113463/172046539-d83aa2d2-ea7b-4329-8118-9bcf7d62dc8f.gif)

Windows
![windows_working](https://user-images.githubusercontent.com/54113463/172046547-db6dd617-72b7-4f3c-a8f8-41cc1dc399fb.gif)

**Comment by Symbai** [comment]
It's probably the same cause as of #7386 with same workaround being mentioned.

**Comment by kristinx0211** [comment]
using above repro project, verified repro on windows and android 12 with vs 17.3.0 Preview 3.0 [32605.41.main]. same as described above.

**Comment by tsquillario** [comment]
I'm able to reproduce on 17.4.0. It's happening to me even if I wrap the CollectionView in a Grid.

**Comment by XamerDev** [comment]
hello guys did you have any workaround for this? i tried everything which was pointed here but without success
It is sad that this bug was reported so long time ago and it is still not fixed. I reported exactly the same here : https://github.com/dotnet/maui/issues/11897
Problem is really critical because all of my pages are actually contentViews
any help will be HUUUGE appreciated

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 6.0. Not repro on Android and Windows platform with repo project https://github.com/eliolo/CollectionViewInContentPresenter
