### ISSUE TITLE
Maui Splash Screen on Android using wrong svg icon

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#7772]
### Description

The splash screen icon on Android is using the svg file specified in the MauiIcon instead of MauiSplashScreen. This is an issue if I choose to use different svg files for AppIcon and Splash Screen.
Looking into the apk, svg files are converted into xml files. I suspect the Splash Screen xml file is referenced to the MauiIcon instead of MauiSplashScreen during the generation of xml files.
The issue does not exist in iOS.

### Steps to Reproduce

1. Create a new Maui App.
2. Replace the <MauiSplashScreen Include="Resources\splashscreen.svg"
3. Add splashscreen.svg into the Resources folder.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 31

**Comment by janseris** [comment]
https://github.com/dotnet/maui/issues/7303

**Comment by tekmun** [comment]
> It happens on Android 12 only afaik (and possibly Android 13) #7303
Verified that the issue does not happen in Android 11 (API 29). Is it possible to be fixed for Android 12, 13 and beyond?

**Comment by MagicAndre1981** [comment]
https://github.com/xamarin/xamarin-android/issues/6517

**Comment by Hottemax** [comment]
Corroborated, happens for example with [MAUI DI ](https://github.com/jamesmontemagno/MauiApp-DI/) sample app from James Montemagno. Splash screen foreground shows up on Android 12 (API 31), does not show on Android 11 (API 30). Color in MauiSplashImage is read (i.e. changing Color in `<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" BaseSize="128,128" />` will display a different color, but the ".NET" will still not show up.

**Comment by kristinx0211** [comment]
replace the  MauiSplashScreen  as `<MauiSplashScreen Include="Resources\Images\dotnet_bot.svg" Color="#512BD4" BaseSize="128,128" />` , the Splash Screen work ok on android 11, but not work on android 12.
