### ISSUE TITLE
DesignMode.IsDesignModeEnabled not working as expected.

### ISSUE THREAD

**Issue by beto-rodriguez** [dotnet/maui#7773]
### Description

The `DesignMode.IsDesignModeEnabled` is not working as it should.
The property value is true even when it is running inside the Android emulator:

> true if the applications is being run in a previewer, false is the applications is being run on a device or emulator.

### Steps to Reproduce

1. Clone https://github.com/beto-rodriguez/MauiDesignModeBug
2. Run the application and see the output console.

If ran on WinUI:

![image](https://user-images.githubusercontent.com/10853349/172064111-ad769393-a46c-4ce8-ac87-42137f3b4a68.png)

If ran on Android emulator:

![image](https://user-images.githubusercontent.com/10853349/172064149-31516b89-68fc-4ed3-9658-b979c5543b84.png)

You can find additional information about this issue at https://github.com/dotnet/maui/issues/7350

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 (at least)

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on android 12 with vs 17.3.0 Preview 3.0 [32605.41.main].

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-android#7765
