### ISSUE TITLE
[Enhancement] Kindly include support for Bluetooth and BLE in MAUI

### ISSUE THREAD

**Issue by nitinjs** [dotnet/maui#778]
## Summary
Kindly include support for Bluetooth BLE in .NET MAUI

## Intended Use Case
Most of the PCs and Laptops have bluetooth BLE, also there are various dongle available which support BLE
it will be very good if .net maui provide support for bluetooth BLE so that my ble supported app can run seamlessly across android/ios/mac/windows.

thanks,
nitin

**Comment by Redth** [comment]
We have no current plans for this, but do check out Shiny which handles BLE and will be supporting MAUI in the future! https://github.com/shinyorg/shiny

**Comment by qcjxberin** [comment]
We currently have the same needs

**Comment by Rowingwolf** [comment]
Shiny doesn't seem to support Maui yet.  An Shiny bluetooth documentation leaves something to be desired.

**Comment by qcjxberin** [comment]
Are there currently plans to support it?
