### ISSUE TITLE
[MacCatalyst] Button's appearance does not look good after building an application with adopted Mac idiom

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#7782]
### Description

When I adopt the Mac idiom for my catalyst application the appearance of the Button changes and doesn't look good. Here is the button with iPad idiom:
<img width="657" alt="Screenshot 2022-06-06 at 10 40 32" src="https://user-images.githubusercontent.com/9336157/172118935-659cd4d7-a20b-4753-890a-46da697d14d6.png">

And here is how the Button looks after adopting the Mac idiom:
<img width="657" alt="Screenshot 2022-06-06 at 10 41 14" src="https://user-images.githubusercontent.com/9336157/172119145-a3957cd0-676c-4cbc-85e5-946ef160f6d4.png">

As you can see it looks like the background of the control is not applied fully (only partially) which makes it look like there is some kind of a border around the control.

### Steps to Reproduce

1. Create a new maui project.
2. Go to the Info.plist of Catalyst and set the UIDeviceFamily to 6 - that enables the optimized interface for macOS.
3. Run the application and check the Button's appearance.

Attached you can find a project that demonstrates the issue.
[HelloMaui.zip](https://github.com/dotnet/maui/files/8842766/HelloMaui.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.4

### Did you find any workaround?

You can set PreferredBehavioralStyle of the native Button to Pad in order to preserve the iPad look and feel of the control:
`button.PreferredBehavioralStyle = UIBehavioralStyle.Pad;`

**Comment by kristinx0211** [comment]
confirm this issue on macOS using above repro project.

**Comment by jsuarezruiz** [comment]
in iOS 15, the UIButton gets a new struct that allow the customization [UIButton.Configuration](https://developer.apple.com/documentation/uikit/uibutton/configuration).

Using the button of type System, with an appearance closer to the usual in macOS, we need to modify some properties of the Configuration.. For example:

```
var configuration = UIButtonConfiguration.FilledButtonConfiguration;
configuration.BaseBackgroundColor = Colors.Red.ToPlatform();
handler.PlatformView.Configuration = configuration;
```

Pass the Configuration to the extension methods, checking if we're on Catalyst and using the Mac UIDeviceFamily, and if so, updating the Configuration.

<img width="1006" alt="Captura de Pantalla 2022-07-21 a las 13 05 26" src="https://user-images.githubusercontent.com/6755973/180200995-9cae576d-dea3-4a2c-86f1-8ca730e94daa.png">

We can also modify the **MacIdiomStyle** property to change the appearance of the Button. With this small change we would not need changes in the extension methods, although the appearance of the Button by default is not the usual one in macOS (it can be achieved by customizing the background color, radius etc)

`configuration.MacIdiomStyle = UIButtonConfigurationMacIdiomStyle.BorderlessTinted;`

<img width="1020" alt="Captura de Pantalla 2022-07-21 a las 13 22 00" src="https://user-images.githubusercontent.com/6755973/180202043-7ffaaf32-585e-4cd7-a906-a7e7404ec15d.png">

Feedback?

**Comment by APopatanasov** [comment]
I like both suggestions. And this is expected to be built-in the control. Is that correct? The developer only needs to set the UIDeviceFamily to 6 and the Button should have MacOS look and feel as expected.
