### ISSUE TITLE
Build crashes on iPadOS immediately when using Location

### ISSUE THREAD

**Issue by justadaniel** [dotnet/maui#7801]
### Description

I'm trying to build an app I'm making that utilizes location to iPad. I've encountered this bug in Xamarin.Forms before. It pretty much comes down to the fact that iPads don't have a GPS, but location services still work thanks to location detection through WiFi. I don't know what is specifically going on under the hood, the kit is mainly for iPhone & Apple Watch, but Apple says that SensorKit is available to iPadOS as well.

Apple Docs: [SensorKit](https://developer.apple.com/documentation/sensorkit)

### Steps to Reproduce

1. Create a project.
2. Utilize location services.
3. Deploy to iPad.
4. Crash on boot.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS/iPadOS 14+

### Did you find any workaround?

None

### Relevant log output

```shell
Launched application '<AppID>' on 'Daniel Christmas’ iPad' with pid 31794
dyld[31794]: Library not loaded: /System/Library/Frameworks/SensorKit.framework/SensorKit
  Referenced from: /private/var/containers/Bundle/Application/00DCEA18-CEB4-40A7-B7E3-633DCA2CC3A1/<DisplayName>.app/<DisplayName>
  Reason: tried: '/System/Library/Frameworks/SensorKit.framework/SensorKit' (no such file)
Application '<AppID>' terminated (with exit code '' and/or crashing signal '6).
```

**Comment by Eilon** [comment]
@justadaniel - can you please show the exact code you are using to get the location? Ideally, a complete project uploaded as a GitHub repo (not a ZIP). But at a minimum, showing the C# code that you used, including any relevant context. Thank you!

**Comment by justadaniel** [comment]
> @justadaniel - can you please show the exact code you are using to get the location? Ideally, a complete project uploaded as a GitHub repo (not a ZIP). But at a minimum, showing the C# code that you used, including any relevant context. Thank you!

Here, I'll leave the previous issue on XF here for reference while I make a project. It is indeed happening due to a mixture of MTouchLink and calling location services apis. [https://github.com/xamarin/xamarin-macios/issues/9938](https://github.com/xamarin/xamarin-macios/issues/9938)

**Comment by Eilon** [comment]
@justadaniel thank you, that will be helpful to the investigation.

**Comment by justadaniel** [comment]
> @justadaniel - can you please show the exact code you are using to get the location? Ideally, a complete project uploaded as a GitHub repo (not a ZIP). But at a minimum, showing the C# code that you used, including any relevant context. Thank you!

Here's a [link to the repo](https://github.com/justadaniel/dotnetmaui_ipad_locationcrash) I just made. Be sure to build to a physical device. 

Log:
`dyld[39463]: Library not loaded: /System/Library/Frameworks/SensorKit.framework/SensorKit
  Referenced from: /private/var/containers/Bundle/Application/81B9CC16-616E-4C0C-9B8C-A2CCD1B7A909/DotNetMaui-LocationCrash.app/DotNetMaui-LocationCrash
  Reason: tried: '/System/Library/Frameworks/SensorKit.framework/SensorKit' (no such file)
Application 'com.companyname.dotnetmaui_locationcrash' terminated (with exit code '0' and/or crashing signal ').
Launched application 'com.companyname.dotnetmaui_locationcrash' on 'Daniel Christmas’ iPad' with pid 39463`

**Comment by jfversluis** [comment]
Hey @justadaniel sorry it's been a while. Can you please confirm this is still an issue in current versions? Thanks!
