### ISSUE TITLE
MSTEST project referring to a MAUI project sometimes fails to build

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#7806]
### Description

When a test project has a dependency on a maui project the test project will sometimes fail to build with:

```
>C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.
>C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.

```
This can be reliably triggered by adding a nuget reference to Microsoft.Identity.Client to the MAUI project. This may be an issue with the package or a local configuration issue, but I reproduced it on a clean Azure VM, so at best it's obscure.
 

### Steps to Reproduce

1. Create a file>New .NET MAUI App
2. Add a Test project to the same solution
3. Add a project dependency from the test project to the maui project
4. To the MAUI project add a package reference to Microsoft.Identity.Client
5. Rebuild the solution - it will probably fail, but if not, try running the tests using the test explorer (there'll be one dummy test), it will trigger a build that will fail.

There's a simple project exhibiting this problem on github [here](https://github.com/david-maw/MauiMsTest.git) is the URL to the project repository.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
same errors using 17.3.0 Preview 3.0 [32608.296.main].

**Comment by daowrey** [comment]
Still occurs in 17.4.4.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Windows 11 with below Project:

[7806.zip](https://github.com/dotnet/maui/files/11483504/7806.zip)

Failed on .NET6 and .NET7.
![image](https://github.com/dotnet/maui/assets/97647558/2d897fc8-54bd-4da8-9690-88689f4c823d)

**Comment by rmarinho** [comment]
This doesn't t seem to be a issue anymore
