### ISSUE TITLE
DeviceDisplay.MainDisplayInfoChanged  The active Window can not be detected. Ensure that you have called Init in your Application class.

### ISSUE THREAD

**Issue by 601093318** [dotnet/maui#7809]
### Description

DeviceDisplay.MainDisplayInfoChanged  The active Window can not be detected. Ensure that you have called Init in your Application class.

### Steps to Reproduce

Set maindisplayinfo changed in mainpage initialization function，throw exception "The active Window can not be detected. Ensure that you have called Init in your Application class".

``` C#
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
        DeviceDisplay.MainDisplayInfoChanged += DeviceDisplay_MainDisplayInfoChanged;
    }
    private void DeviceDisplay_MainDisplayInfoChanged(object sender, DisplayInfoChangedEventArgs e)
    {
        //todo
    }
}
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 SDK(10.0.19041.0)

**Comment by VincentBu** [comment]
repro with vs main build 32609.239.

**Comment by pierre01** [comment]
I have the same issue
