### ISSUE TITLE
TextToSpeech.GetLocalesAsync(); inconsistent values in Locale, 

### ISSUE THREAD

**Issue by SchreinerK** [dotnet/maui#7813]
### Description

The result from TextToSpeech.GetLocalesAsync returns inconsistent values in different OS
in Windows
  Language="en-US"
  Country =""
in Android
  Language="en"
  Country ="US"

Since "en-US" is a locale and not a language, I think the content is wrong for Windows and should be as for Android.

Version: Microsoft Visual Studio Preview Version 17.3.0 Preview 1.1

### Steps to Reproduce

simple call TextToSpeech.GetLocalesAsync and compare the results

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 19044.1706

**Comment by VincentBu** [comment]
On windows, I get the same result. But on Android emulator, `GetLocalesAsync` returns null.
