### ISSUE TITLE
MAUI Templates are missing in VS 2022 17.3.0 Preview 1.1

### ISSUE THREAD

**Issue by nZeus** [dotnet/maui#7819]
### Description

Installed the VS 17.3.0 Preview 1.1, and I cannot create a MAUI project anymore.

![image](https://user-images.githubusercontent.com/2727326/172387409-bc71bf46-ed4b-4eff-bafa-94cef01b7398.png)

### Steps to Reproduce

1. Install Visual Studio 2022 17.3 Preview 1.1
2. Start new Project
3. Drop down for Project Type doesn't include Maui
4. Open Console
5. Type "dotnet new --list" to see list of templates
6. Notice it is missing.

![image](https://user-images.githubusercontent.com/2727326/172388089-fb6f6a41-c645-4233-a14c-438ace4c5b26.png)

![image](https://user-images.githubusercontent.com/2727326/172388378-95ff1410-c2d4-46f5-b6c6-8650d99182a8.png)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11 Pro 22H2 22621.1

### Did you find any workaround?

no

**Comment by Symbai** [comment]
MAUI is incompatible with .NET 7 so you might want to uninstall it. Got the same VS version and I got all the MAUI templates.

![image](https://user-images.githubusercontent.com/14368203/172401515-4577ea6b-5071-4974-aa1b-645d0ac164c9.png)

![image](https://user-images.githubusercontent.com/14368203/172401631-da3ee27d-f600-4f92-96a6-a5f6a66b8b68.png)

![image](https://user-images.githubusercontent.com/14368203/172402014-c2b544fd-53e4-4853-8c92-9ca0b81e059f.png)

**Comment by nZeus** [comment]
Thank you @Symbai , I think you're right.

If I add a `global.json` file and run `dotnet new --list`, then I see MAUI templates in the list:

I would say that the issue is that Visual Studio doesn't show all the templates, from all the SDKs.

**Comment by mprogers** [comment]
I have the same problem. I'm running Windows 11 on a Mac Studio, I dunno if that's the problem, but 
dotnet --version 
6.0.300

But when I look in Visual Studio 2022 Preview (17.3.0, 1.1), or when I run dotnet new --list, I don't see anything about MAUI:

Template Name                                 Short Name           Language    Tags
--------------------------------------------  -------------------  ----------  --------------------------
ASP.NET Core Empty                            web                  [C#],F#     Web/Empty
ASP.NET Core gRPC Service                     grpc                 [C#]        Web/gRPC
ASP.NET Core Web API                          webapi               [C#],F#     Web/WebAPI
ASP.NET Core Web App                          webapp,razor         [C#]        Web/MVC/Razor Pages
ASP.NET Core Web App (Model-View-Controller)  mvc                  [C#],F#     Web/MVC
ASP.NET Core with Angular                     angular              [C#]        Web/MVC/SPA
ASP.NET Core with React.js                    react                [C#]        Web/MVC/SPA
Blazor Server App                             blazorserver         [C#]        Web/Blazor
Blazor WebAssembly App                        blazorwasm           [C#]        Web/Blazor/WebAssembly/PWA
Class Library                                 classlib             [C#],F#,VB  Common/Library
Console App                                   console              [C#],F#,VB  Common/Console
dotnet gitignore file                         gitignore                        Config
Dotnet local tool manifest file               tool-manifest                    Config
EditorConfig file                             editorconfig                     Config
global.json file                              globaljson                       Config
MSTest Test Project                           mstest               [C#],F#,VB  Test/MSTest
MVC ViewImports                               viewimports          [C#]        Web/ASP.NET
MVC ViewStart                                 viewstart            [C#]        Web/ASP.NET
NuGet Config                                  nugetconfig                      Config
NUnit 3 Test Item                             nunit-test           [C#],F#,VB  Test/NUnit
NUnit 3 Test Project                          nunit                [C#],F#,VB  Test/NUnit
Protocol Buffer File                          proto                            Web/gRPC
Razor Class Library                           razorclasslib        [C#]        Web/Razor/Library
Razor Component                               razorcomponent       [C#]        Web/ASP.NET
Razor Page                                    page                 [C#]        Web/ASP.NET
Solution File                                 sln                              Solution
Web Config                                    webconfig                        Config
Windows Forms App                             winforms             [C#],VB     Common/WinForms
Windows Forms Class Library                   winformslib          [C#],VB     Common/WinForms
Windows Forms Control Library                 winformscontrollib   [C#],VB     Common/WinForms
Worker Service                                worker               [C#],F#     Common/Worker/Web
WPF Application                               wpf                  [C#],VB     Common/WPF
WPF Class Library                             wpflib               [C#],VB     Common/WPF
WPF Custom Control Library                    wpfcustomcontrollib  [C#],VB     Common/WPF
WPF User Control Library                      wpfusercontrollib    [C#],VB     Common/WPF
xUnit Test Project                            xunit                [C#],F#,VB  Test/xUnit

I'm trying to prep this summer for a class that I'm teaching in the fall, so any help would be **greatly** appreciated!

**Comment by jfversluis** [comment]
You might want to check it .NET 7 preview is installed (run `dotnet --version`), if that's the case the templates are installed but they won't show up. More info on that [here](https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio).

If the templates are not installed you can run `dotnet new -i Microsoft.Maui.Templates` to still get them. Please do not use the version that is at the end, especially not the one as advertized here because that is an older version. If you do not specify a version the newest ones will be installed.

We're investigating why the templates are not installed in some instances and will fix that. Since we have multiple issues about this I'm closing this one. Please let us know if you still can't get the templates to show up.

@mprogers I hope this helps, if not, feel free to reach out to me directly so we can start helping that prep! We don't want to leave the students out in the cold!

**Comment by nZeus** [comment]
Indeed that was my problem - I had preview 7 installed.
It is very nice that you have that wiki page, thanks a lot!

I agree, the issue can be closed
