### ISSUE TITLE
Net.Maui Blazor not running on Android 7.1 Tablet 

### ISSUE THREAD

**Issue by fkozaslan** [dotnet/maui#7840]
### Description

Like this issue [#39086](https://github.com/dotnet/aspnetcore/issues/39086)

Visual Studio: 
![image](https://user-images.githubusercontent.com/41776940/172598355-675bf285-6919-4fae-b55c-d9c0c5ae3002.png)

Device About:

![image](https://user-images.githubusercontent.com/41776940/172597086-0486991b-5f77-4c77-9bb2-760c2fce6d50.png)

I getting this error when app running:

[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token import", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(29)] "Uncaught TypeError: Cannot set property 'sendMessage' of undefined", source:  (29)
[chromium] [INFO:CONSOLE(2)] "Uncaught ReferenceError: Blazor is not defined", source:  (2)
![image](https://user-images.githubusercontent.com/41776940/172596177-e39cb5c3-0839-4f62-a240-b29136832e8a.png)
![image](https://user-images.githubusercontent.com/41776940/172596309-b1fa71f2-1148-451d-92b7-561b51fa20fd.png)

### Steps to Reproduce

1. Open Debug Mode Maui App On Device (Android 7.1)
2. Stopping White Screen

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1 - SDK 25

**Comment by javiercn** [comment]
@fkozaslan thanks for contacting us.

It looks like the version of Chrome you are using on that device is too old.

**Comment by janseris** [comment]
@javiercn maybe there could be a guideline for required Chrome version on Android?

**Comment by danroth27** [comment]
We document that we require updated platform web view controls in the Blazor docs, but we should also mention that in the .NET MAUI docs as a .NET MAUI Blazor platform requirement. Updated here: https://github.com/dotnet/docs-maui/pull/594.

I've also opened an issue to document the steps for updating Chrome in the Android emulator as it can be trick to do if the image doesn't have Google Play services installed: https://github.com/dotnet/AspNetCore.Docs/issues/26089

**Comment by fkozaslan** [comment]
Thank you for your quikly answers :) I will try chrome manuel update on device and I will be waiting for the document

**Comment by fkozaslan** [comment]
@danroth27 Can we open issue again ?  we needs help because our project usings on this devices and project completed just we want the solve this issue, we waiting yours helpings https://github.com/dotnet/AspNetCore.Docs/issues/26089#issuecomment-1165438694

**Comment by javiercn** [comment]
@fkozaslan I'm not sure there is anything we can do here. If you have devices using an unsupported browser version, the best thing you can do is to display a message on the index page including instructions to update the browser. For example:

```html
<p id="old-browser-version" style="display:none">The current browser version is not supported. Please upgrade to a newer browser following 
	<a href="link-to-update-instructions">these instructions</a></p>
<script type="text/javascript">
try {
	if (Number.parseInt(/Chrome\/(?<version>\d{2,})/.exec(navigator.userAgent).groups.version) < 90) {
		document.querySelector('#old-browser-version').setAttribute("style", "display:block");
	}
}
catch {
      }
</script>
```
