### ISSUE TITLE
ILifecycleBuilder

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#7843]
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ILifecycleBuilder' does not contain a definition for 'AddWindows' and no accessible extension method 'AddWindows' accepting a first argument of type 'ILifecycleBuilder' could be found (are you missing a using directive or an assembly reference?)	MPAUI.OS (net6.0-android), MPAUI.OS (net6.0-ios), MPAUI.OS (net6.0-maccatalyst)	

       builder.ConfigureLifecycleEvents(events => {
            events.AddWindows(windows => windows
                            .OnWindowCreated(window =>
                            {
                                window.SizeChanged += OnSizeChanged;
                            }));
        });
        

what can i say

https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#windows

### Steps to Reproduce

made in Description

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 11

**Comment by ThuCommix** [comment]
Its exactly working like in the docs, as you can see the code is wrapped in pre compiler directives:

```
#if WINDOWS
                   events.AddWindows(windows => windows
                          .OnActivated((window, args) => LogEvent("OnActivated"))
                          .OnClosed((window, args) => LogEvent("OnClosed"))
                          .OnLaunched((window, args) => LogEvent("OnLaunched"))
                          .OnLaunching((window, args) => LogEvent("OnLaunching"))
                          .OnVisibilityChanged((window, args) => LogEvent("OnVisibilityChanged"))
                          .OnPlatformMessage((window, args) =>
                          {
                              if (args.MessageId == Convert.ToUInt32("0x02E0"))
                              {
                                  // DPI has changed
                              }
                          }));
#endif
```

**Comment by PirasathLuxchumykanthan** [comment]
Oka is set to Windows Machone but i see the text in grey like is not activ, :(

**Comment by ThuCommix** [comment]
Its an editor bug, the path actually gets compiled even though its greyed out. (If you switched to Windows Machine). The best thing is to write the code without the preprocessor directive so you have IntelliSense and then apply it after you finished.

**Comment by PirasathLuxchumykanthan** [comment]
yes nice..
i see thx... big hug to you

**Comment by jfversluis** [comment]
Seems this is resolved then!
