### ISSUE TITLE
Placeholder text alignment not respected on Windows ref #3808

### ISSUE THREAD

**Issue by Michal-MK** [dotnet/maui#7844]
### Description

The exact same behaviour as in #3808
![image](https://user-images.githubusercontent.com/12874766/172613886-1d7a3704-6104-4772-8559-b4e5b664d1da.png)

![image](https://user-images.githubusercontent.com/12874766/172614816-faa88428-f28e-441e-b475-334a0cd01e49.png)

### Steps to Reproduce
```
<Grid ColumnDefinitions="*, auto">
    <Entry Placeholder="Zadejte rodné číslo..." VerticalTextAlignment="Center"/>
    <Button Grid.Column="1" Text="Hledat"/>
</Grid>
```
I removed some extra code that I think is irrelevant.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.22000.0

### Did you find any workaround?

It probably worked at some point since the issue was closed? But I do not know which version...

**Comment by kristinx0211** [comment]
verified repro on windows using above code with vs 17.3.0 Preview 3.0 [32608.296.main].
![image](https://user-images.githubusercontent.com/99457000/172780157-10cb2f82-4054-4888-b0cd-160f0515e4a6.png)

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/8684
