### ISSUE TITLE
MacCatalyst Bundle has "Windows" platform folder in Contents/Resources/Platforms instead of "MacCatalyst" folder

### ISSUE THREAD

**Issue by hunsra** [dotnet/maui#7866]
### Description

Building a MacCatalyst app results in a macOS app bundle that includes `Contents/Resources/Platforms/Windows` instead of `Contents/Resources/Platforms/MacCatalyst`, causing platform specific resources to fail to load.

### Steps to Reproduce

1. Clone the dotnet MAUI samples project on GitHub:  [https://github.com/dotnet/maui-samples](https://github.com/dotnet/maui-samples)
2. Open the WeatherTwentyOne sample app in Visual Studio for Mac Preview, version 17.3 Preview (17.3 build 198).
3. Choose the Debug configuration, build and run the MacCatalyst app.  You should notice that the Mac status bar icon the app intends on establishing doesn't appear.
4. Quit the app.
5. Using Finder, navigate to the `bin/Debugnet6.0-maccatalyst/maccatalyst-x64` folder in the `WeatherTwentyOne` project folder.
6. Right click on `WeatherTwentyOne `and choose "Show Package Contents".
7. Using Finder, navigate to `Contents/Resources/Platforms`.
8. Observe that `Windows` appears instead of `MacCatalyst`.
9. Using Finder, navigate into `Windows` and observe that the `trayicon.ico` resource file appears.

[build.log](https://github.com/dotnet/maui/files/8864482/build.log)
[app-output.log](https://github.com/dotnet/maui/files/8864483/app-output.log)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.4, Visual Studio for Mac preview 17.3 build 198

### Did you find any workaround?

I have not found a workaround.

### Relevant log output

```shell
See build.log and app-output.log attached to repro steps.
```

**Comment by jfversluis** [comment]
Is this something you also see outside of the Weather 21 sample app? I'm thinking this is maybe just some mixup in that sample somehow.

**Comment by hunsra** [comment]
@jfversluis, yes this seems to be associated with the sample app.  I created a new MAUI app and the resources show up in the bundle under Contents/Resources without a platform folder, which I assume is the correct way.  I'm curious how the sample app could be controlling this.  Could it be the build targets configuration?
