### ISSUE TITLE
Entry properties CursorPosition and SelectionLength are not updated

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#7867]
### Description

For both Entry and Editor controls, I've noticed that CursorPosition is 0 and never changes. [Edit] I've also noticed that SelectionLength isn't updated either.

In Xamarin Forms, Entry.CursorPosition is set correctly and updates as the cursor is moved.

### Steps to Reproduce

Add an Entry control named TheEntry to a ContentPage in a .NET MAUI app.

In the code behind, add the following to the constructor:

        TheEntry.PropertyChanged += (s, e) => {
            if ( e.PropertyName == Entry.CursorPositionProperty.PropertyName )
                Debug.WriteLine($"CursorPosition: {(s as Entry).CursorPosition}");
            else if ( e.PropertyName == Entry.SelectionLengthProperty.PropertyName )
                Debug.WriteLine($"SelectionLength: {(s as Entry).SelectionLength}");
        };

Run and enter text in the Entry control. The value of CursorPosition is always zero, and the value of SelectionLength never changes when text is selected.

In a Xamarin Forms project, repeat the above steps. Note that CursorPosition is updated correctly.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS 15.5, Mac Catalyst 15.5, Android API 29

### Did you find any workaround?

No, although a custom handler that updates CursorPosition every time input changes or an arrow key is pressed. Yikes.

[Edit] I found a workaround: in a custom handler, I handled event UITextView.SelectionChanged. In the event handler, I set the editor's CursorPosition and SelectionLength from the UITextView.SelectedRange property.

**Comment by kristinx0211** [comment]
verified repro on android, on windows, seems can work, repro project:
[MauiApp2.zip](https://github.com/dotnet/maui/files/8866557/MauiApp2.zip)

**Comment by agendamatic** [comment]
Updated issue to reflect that SelectionLength property is not updated either.

**Comment by agendamatic** [comment]
Updated issue with workaround.

**Comment by breenbob** [comment]
I'm also finding that _setting_ CursorPosition does nothing either, at least for Entry on Windows. This makes it impossible to have input mask behaviour where the cursor can be skipped over a placeholder character, e.g. the '/' in __/__/____ for a date input mask.

**Comment by jsuarezruiz** [comment]
Have done some tests on the current net6.0 branch and CursorPosition, SelectionLength  properties seems to work.
![issue-7867](https://user-images.githubusercontent.com/6755973/178696478-112dbb26-2d05-496f-8884-f374a98d913b.gif)
Could you try with the latest version?

**Comment by agendamatic** [comment]
I just updated to all of the current versions on Mac, and I'm seeing no change on iOS, Mac Catalyst or Android. Neither property is updated when either an Entry or Editor text is changed or selected. (Please ensure you don't have a custom renderer in place using the workaround mentioned above.)

**Comment by hartez** [comment]
This is fixed in 17.4.
