### ISSUE TITLE
Sync blazorserver & blazor-maui templates

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/maui#7868]
There have been some recent changes in the `blazorserver`/`blazorwasm` templates. Using this issue to track synchronizing those changes with `blazor-maui`

**Comment by TanayParikh** [comment]
https://github.com/dotnet/aspnetcore/commits/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp

https://github.com/dotnet/aspnetcore/commits/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp

**Comment by mkArtakMSFT** [comment]
Closing as we'll cover this as part of https://github.com/dotnet/aspnetcore/issues/30162
