### ISSUE TITLE
UICollectionViewCompositionalLayout.GetLayout(config); always returns null

### ISSUE THREAD

**Issue by curtis91a** [dotnet/maui#7874]
### Description

Trying to use the ios call UICollectionViewCompositionalLayout.GetLayout(config); always returns null

I first sent this bug to the microsoft .net forum and they stated it works but does not work in maui

UICollectionViewCompositionalLayout.GetLayout(config); always returns null
Hi,

I am trying to implement the ipados sidebar code with the new .net 6 core ios and the below code always returns null

     public override void ViewDidLoad()
     {
         base.ViewDidLoad();
         var config = new UICollectionLayoutListConfiguration(UICollectionLayoutListAppearance.Sidebar);
         config.HeaderMode = UICollectionLayoutListHeaderMode.None;
         config.HeaderMode = UICollectionLayoutListHeaderMode.FirstItemInSection;
         var layout = UICollectionViewCompositionalLayout.GetLayout(config); // <--- this will always return null, why?
    }
[dotnet-maui](https://docs.microsoft.com/answers/topics/460228/dotnet-maui.html)
 Comment ·  Hide 1 
 Save
 [WenyanZhang-MSFT ](https://docs.microsoft.com/answers/users/7784358/wenyanzhang-msft.html)· [1 day ago](https://docs.microsoft.com/answers/comments/879574/view.html)
Hi @CurtisConner-4423 , I test by native iOS(OC), Xamarin.iOS, it will not be null, but it always returns null in MAUI project, you could create a new thread at https://github.com/dotnet/maui/issues to report this issue, thanks for your cooperation.

### Steps to Reproduce

UICollectionViewCompositionalLayout.GetLayout(config); always returns null
Hi,

I am trying to implement the ipados sidebar code with the new .net 6 core ios and the below code always returns null

     public override void ViewDidLoad()
     {
         base.ViewDidLoad();
         var config = new UICollectionLayoutListConfiguration(UICollectionLayoutListAppearance.Sidebar);
         config.HeaderMode = UICollectionLayoutListHeaderMode.None;
         config.HeaderMode = UICollectionLayoutListHeaderMode.FirstItemInSection;
         var layout = UICollectionViewCompositionalLayout.GetLayout(config); // <--- this will always return null, why?
    }
[dotnet-maui](https://docs.microsoft.com/answers/topics/460228/dotnet-maui.html)
 Comment ·  Hide 1 
 Save
 [WenyanZhang-MSFT ](https://docs.microsoft.com/answers/users/7784358/wenyanzhang-msft.html)· [1 day ago](https://docs.microsoft.com/answers/comments/879574/view.html)
Hi @CurtisConner-4423 , I test by native iOS(OC), Xamarin.iOS, it will not be null, but it always returns null in MAUI project, you could create a new thread at https://github.com/dotnet/maui/issues to report this issue, thanks for your cooperation.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

ios 15

### Did you find any workaround?

no

**Comment by curtis91a** [comment]
Any idea when this will be looked at? its a real blocker for me

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with VSM 17.6.7 (build 417). Not repro this issue.
