### ISSUE TITLE
OnNightModeChanged Android not functional

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#7877]
### Description

If you want to check natively on the platform if the Ui mode has been changed, you can normally use the native function "OnNightModeChanged " of the Mainactivity Script in the Android-Plattfrom folder.

But this method seems to be dead, no matter what I tried and tested, the function was not called under any of the tested Android versions

### Steps to Reproduce

1. Create Maui project 
2. Target Android with min version 10 otherwise darkmode is not supported
3. Import the method "protected override void OnNightModeChanged(int mode)" in the MainActivity script which is located in the Android platform folder
4. Add a debug log to this method to check if the method was called
5. Start the emulator or the device 
6. Switch the darkmode/lightmode
7. If the error still exists, nothing should be output

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10 >=

### Did you find any workaround?

In the MainActivity script located in the Android dependent folder I added a separate method . I also added a singleton to the MainActivity so that I can call the method from the instance. 

This works, but it is an ugly detour 

The solution is added to the repo as seperated branch named workaround

https://github.com/DeepWorksStudios/ReproductionProjectBug_7877.git

**Comment by jfversluis** [comment]
Would you be able to add a little reproduction project that shows this? That will really help try some things out and diagnosde the potential issue.

**Comment by DeepWorksStudios** [comment]
> 

Of course i'm on it will be ready in short time :)

**Comment by kristinx0211** [comment]
verified repro on android.

**Comment by DeepWorksStudios** [comment]
Any Updates?

**Comment by jfversluis** [comment]
Hey thanks for the ping here! Just out of curiosity: why do you need the platform specific one?

Another thing I would be interested in is: does this work on an Android project without .NET MAUI? 
If you do `dotnet new android` and try the same thing. Does that work?

Did you add the actual workaround code? I don't see it? I wonder what it is that you did to do make it work?

**Comment by DeepWorksStudios** [comment]
Hey Gerald, 
thanks for the quick reply! Actually I don't need the platform specific one, I just diagnosed that this is the root of the problem why themerequestchanged doesn't work on Android and I dug deeper and found out that the main system never calls this plattfrom dependent function no matter what situation. The thing to try with only a pure android project  I can't understand unfortunately because I still need the other platforms for my project and don't know how to help with that I'm sure it's the implementation and not android itself that causes this issshu. i can  still be wrong is just my guess. Main reason I just need the event  
themerequestchanged but fully functional otherwise it's actually quite useless since i called the event hardcoded myself via singelton and a simply methoded call wich invokes localy the change if triggerd by the app ui (selfmade) not system triggerd so its not a real workarround only to make it partialy work . If you still want to see the workarround I could create an additional repo

Thanks again for the help i struggel with this kind of bugs a long time since you can see whene i reported them (its not the only bug i reported releated to app theming)

**Comment by DeepWorksStudios** [comment]
Any updates?

**Comment by DeepWorksStudios** [comment]
@jfversluis ?

**Comment by DeepWorksStudios** [comment]
@samhouts why you removed the verified tag? It is verfiand still present??

**Comment by DeepWorksStudios** [comment]
@samhouts why you removed the verified tag? It is verfiand still present??

**Comment by samhouts** [comment]
We're doing a bulk re-triage of issues to see if latest changes affected the behavior at all.

**Comment by DeepWorksStudios** [comment]
@samhouts Alright i will check today all my bug repos and will update the reports i made

**Comment by DeepWorksStudios** [comment]
I can verfi that the issue still remains
I updated the repo to .net 7

**Comment by DeepWorksStudios** [comment]
Any Updates @samhouts @jfversluis

**Comment by jfversluis** [comment]
I don't think this issue is specific to .NET MAUI. I've tried with an Android project without .NET MAUI and there it also doesn't trigger. So either there is something that needs to be activated for Android so that this method gets called, or there is a bug somewhere that prevents this from being triggered. But you'd most likely have better luck at https://github.com/xamarin/xamarin-android or https://github.com/xamarin/AndroidX

In the meanwhile, if you want to detect changes in dark theme, you can use this as an alternative:

```csharp
public override void OnConfigurationChanged(Configuration newConfig)
{
    base.OnConfigurationChanged(newConfig);

    System.Diagnostics.Debug.WriteLine(newConfig.IsNightModeActive);
}
```

Unfortunately I don't think there is much we can do here at this time, so closing this for this repo.
