### ISSUE TITLE
IJSRuntime and window.print() break MAUI Blazor App

### ISSUE THREAD

**Issue by OrihuelaConde** [dotnet/maui#7880]
### Description

When using JS `window.print()` in a MAUI Blazor App it breaks the App.

### Steps to Reproduce

1. Create a new MAUI Blazor App.
2. Add the next code to wwwroot/index.html: 
```
<script>
      function printPage() {
	      window.print();
      }
</script>
```
3. Add the next code to Pages/Index.razor:
```
@inject IJSRuntime JS

<button class="btn btn-primary" @onclick="Print">Print</button>

@code {
    private async void Print()
    {
        await JS.InvokeVoidAsync("printPage");
    }
}
```
4. Start the App, try to Print and then move to another page 🐞

![image](https://user-images.githubusercontent.com/12591371/172797714-16224b97-19ed-40cd-885f-2f9d3de0139b.png)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11 (22000)

### Relevant log output

```shell
Received unexpected acknowledgement for render batch 3 (next batch should be 2)
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.NotifyRenderCompleted(Int64 batchId)
   at Microsoft.AspNetCore.Components.WebView.IpcReceiver.OnRenderCompleted(PageContext pageContext, Int64 batchId, String errorMessageOrNull)
   at Microsoft.AspNetCore.Components.WebView.IpcReceiver.OnMessageReceivedAsync(PageContext pageContext, String message)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.<>c__DisplayClass18_0.<<MessageReceived>b__0>d.MoveNext()
```

**Comment by kristinx0211** [comment]
@OrihuelaConde Not repro on windows with vs 17.3.0 Preview 3.0 [32614.275.main]. Start the App, and then show the print page, click print and then print successfully. let me know if I miss something. my repro project: [MauiApp11.zip](https://github.com/dotnet/maui/files/8908222/MauiApp11.zip)
![image](https://user-images.githubusercontent.com/99457000/173801304-9accce67-39d9-4170-83a9-105f231ad663.png)

**Comment by mkArtakMSFT** [comment]
Thanks for validating this, @kristinx0211.
Closing this as `no-repro`.
