### ISSUE TITLE
Radiobutton custom content is not displaying on Android

### ISSUE THREAD

**Issue by BlagoCuljak** [dotnet/maui#7881]
Hi, on new install, you can add code from [your documentation about custom radio button display](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton), but on Android, there  is a issue with display of your control.
![MAUI Android Radiobutton](https://user-images.githubusercontent.com/34435929/172802302-50c818c0-0b88-4ccb-adb2-5e8beb3e25e9.png)
[MauiApp1.zip](https://github.com/dotnet/maui/files/8868474/MauiApp1.zip)

**Comment by priyarishi** [comment]
The issue still persists . Any update on this?

**Comment by rachelkang** [comment]
Hi, all - here's an example of how this should be coded to get this to work as expected:

```xaml
<Label Text="If we select a ControlTemplate, we can use a View as Content on any platform. In this case, we're using the default template:"/>
<RadioButton ControlTemplate="{x:Static RadioButton.DefaultTemplate}">
          <RadioButton.Content>
                        <Image Source="coffee.png"/>
          </RadioButton.Content>
</RadioButton>

```

@davidbritch could we perhaps update the docs to reflect this scenario?

**Comment by davidbritch** [comment]
@rachelkang The doc already explains that the example doesn't work on Android, and instead to use a ControlTemplate (with a link to an example). I think this issue can be closed.
