### ISSUE TITLE
[Android] Border Background not changed to Brush once we set the Gradient

### ISSUE THREAD

**Issue by Choza-rajan** [dotnet/maui#7885]
### Description

The Border Background was not changed into Brush once we set the Gradient color in Android. The same sample works properly in WinUI platforms.

### Steps to Reproduce

1. Run the attached sample
2. Click the button 
3. See the border background
4. Once the gradient was set then the solid brush was not set in Android alone

[BorderBackgroundSample.zip](https://github.com/dotnet/maui/files/8869878/BorderBackgroundSample.zip)

Issue image,
<img width="207" alt="BorderBackground" src="https://user-images.githubusercontent.com/92723643/172837482-ab65f7fc-6274-4191-aeb1-9a0923913421.png">

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

No, I have not found any workaround

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.
