### ISSUE TITLE
Maui embedded issues: DisplayAlert not working and Application.Current is null

### ISSUE THREAD

**Issue by jdunaway** [dotnet/maui#7887]
### Description

In a maui embedded project when trying to use Application.Current.MainPage.DisplayAlert in an AlertService there is an exception because Application.Current is null.  When trying to call DisplayAlert in the page code behind the alert is not displayed.  

### Steps to Reproduce

1. Create a File -> New "Android application" (.NET 6 template) or File -> New "iOS application" (.NET 6 template)
2. Follow https://github.com/dotnet/maui/pull/5218 to enable MAUI embedding in the Android project or iOS project.
3. Add a MAUI page to the project
4. In the new page code behind add the following code in the constructor after InitializeComponent: DisplayAlert("Hello World", "test", "OK");

### Version with bug

6.0 Current

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

all

### Did you find any workaround?

Going to look into using MAUI Community Toolkit popups as a workaround for now.

**Comment by AmazingSully** [comment]
I can confirm I am having the same issues. It's worth noting that it's not isolated to images however as I've had it occur with listviews that have no images in them.

**Comment by ultimategrandson** [comment]
I am having this issue as well. I used my own custom implementation of dialogs on ios/android and that seems to work fine.

**Comment by XamlTest** [comment]
@jdunaway Would you be able to add a little reproduction project that shows this?
