### ISSUE TITLE
[Enhancement] Please document and improve MVVM

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/maui#79]
[This question on Stackoverflow](https://stackoverflow.com/questions/1939345/wpf-should-a-user-control-have-its-own-viewmodel) is the poster child for a number of issues and questions surrounding MVVM and WPF.  

1.) Please clearly and specifically define a ViewModel.  The fact that a question such as the one posted even exists indicates a need for documentation at the source.  For lack of anything better I personally define a ViewModel as a single object that is the source for rendering a View.  I think of a ViewModel as something different than a Presentation Model, which is simply one of many objects that may be used to compose a ViewModel.  [More here](https://www.samwheat.com/post/The-function-of-ViewModels-in-MVC-web-development).

2.) Please allow UserControls to participate in the Dependency Injection system.  Currently if I inject an instance of my control into my page I have to manually deal with all the bindings.  I want to be able to inject my ViewModel into my control, and inject my control into my page.

3.) A control is a reusable UI component.  Reusable means there is no such thing as a top-level control or a bottom level control.  A control should be consumable by any other control, which may be consumed by some other control, and so on.   The assertion that the MVVM pattern works only at a single level in the control hierarchy implies that the MVVM pattern itself or its implementation is flawed.  The pattern must be able to generalize across all levels of the UI hierarchy.

4.)  As you might expect I disagree with the accepted answer to the question posted above.  However the author makes a valid point:

	> When you create a ViewModel for your UserControl, you also break the natural flow of data via the DataContext. This is where you will experience the most pain. 

5.)  There needs to be a better way to communicate between ViewModels in a control hierarchy.  I don't know exactly how this might be done.  I suspect that just as controls are hierarchical objects, so too should ViewModels be hierarchical objects.  An example of this [can be found here](https://github.com/dotnet/wpf/issues/2596).  See also point 3.

**Comment by charlesroddie** [comment]
> at the source

The source of "MVVM" is not MAUI. It may be some of the creators of WPF, but is now a movement with various community enforcers. The question of what is "true MVVM" doesn't seem within the remit of the MAUI repository to comment on.
