### ISSUE TITLE
DateTime.Now and DateTime.UtcNow.ToLocalTime() returns UTC time on IPhone and IPad

### ISSUE THREAD

**Issue by otium99** [dotnet/maui#7903]
### Description

I've used the following ways of getting the local device time. Tested on  IPhone 13 Pro Max and IPad 8th generation. Both devices have their Date & Time set to automatically. They both are in UTC-3, which is shown correctly on the device itself.

DateTime.Now;
DateTime.UtcNow;
DateTime.UtcNow.ToLocalTime();
TimeZoneInfo.Local.Id

- They all return UTC time.
- TimeZoneInfo.Local.Id returns "UTC"
- The project is compiled on a Windows with Visual Studio Version 17.3.0 Preview 1.1
- Displaying the value in UI and logging them to a Database produces the same output (UTC)
- In the Windows app these times are returned correctly:
DateTime.Now -> Shows the time the device is set to (local)
DateTime.UtcNow -> Shows the UTC time
DateTime.UtcNow.ToLocalTime() -> Shows the time the device is set to (local)

### Steps to Reproduce

Create a basic, simple .NET MAUI app including these lines of code

DateTime.Now;
DateTime.UtcNow;
DateTime.UtcNow.ToLocalTime();
TimeZoneInfo.Local.Id

Display the return values in the UI and also log them to a file or database, to make sure there is no difference between the  display and the actual content.

Run it on an IPhone or IPad with iOS 15.3.1 / iOS 15.1

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.3.1 / iOS 15.1

### Did you find any workaround?

No.

**Comment by campersau** [comment]
Might already be fixed by https://github.com/dotnet/runtime/pull/70149 backport to 6.0 https://github.com/dotnet/runtime/pull/70288

**Comment by NestorPV** [comment]
I have the same issue on a physical device, emulator works as expected. 
@jfversluis any update?

**Comment by jfversluis** [comment]
@rolfbjarne should this be fixed by the linked runtime issues?

**Comment by rolfbjarne** [comment]
@jfversluis yes, I believe so.

**Comment by mattleibow** [comment]
This is now fixed.
