### ISSUE TITLE
[Blazor Hybrid] CSS Hot Reload changes get applied with a flicker on the UI

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/maui#7905]
The current implementation of CSS Hot Reload reapplies all CSS changes on the page, which results in a visible flicker on the UI.
This issue tracks the work to eliminate the flicker by applying only the changed CSS parts.

Here is the original implementation: https://github.com/dotnet/maui/pull/6097
Per @SteveSandersonMS, there is a risk associated with applying fine-grained CSS changes, so the decision back then was intentional.

**Comment by mkArtakMSFT** [comment]
Talked to @SteveSandersonMS a bit more about this and the thinking is the following:
we want to address this if it is really an issue. `An issue` here means a difference how CSS Hot Reload works on the web vs in MAUI Blazor app. If in the web project there is no flickering, then we should try to understand why there is a difference and try to address that. Otherwise, if they're the same, perhaps we can live with this for now till we hear clear signal from customers that this is a problem.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on windows platform.
![3](https://github.com/dotnet/maui/assets/77434865/af5e3761-5ec3-46b2-bf63-4a2132b4e215)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
