### ISSUE TITLE
Razor SDK incompatible with iOS SDK regarding "Content" items

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#791]
A Blazor Desktop with .NET MAUI project uses a combination of several .NET SDKs (in the "SDK-style project" sense). The iOS and Razor SDKs have a conflict where they disagree about how to process `*.razor` files that are `<Content ... />` items in the project. The Razor SDK converts those to `<RazorComponent ... />` items so that the Razor compiler (source generator) can process them. The iOS SDK wants to include them along with `<BundleResource ... />` items and include them in the generated PKG file.

Unfortunately the iOS targets seem to encounter a fatal error and in a "default" scenario with no workaround, you end up with MSBuild errors such as these:

```
Main.razor The path '../../../../../../../../src/Controls/samples/Controls.Sample/Main.razor' would result in a file outside of the app bundle and cannot be used.
         [/Users/eilonlipton/Documents/GitHub/maui/src/Controls/samples/Controls.Sample/Maui.Controls.Sample-net6.csproj]
Pages/Index.razor The path '../../../../../../../../src/Controls/samples/Controls.Sample/Pages/Index.razor' would result in a file outside of the app bundle and cannot be used.
         [/Users/eilonlipton/Documents/GitHub/maui/src/Controls/samples/Controls.Sample/Maui.Controls.Sample-net6.csproj]
_Imports.razor The path '../../../../../../../../src/Controls/samples/Controls.Sample/_Imports.razor' would result in a file outside of the app bundle and cannot be used.
         [/Users/eilonlipton/Documents/GitHub/maui/src/Controls/samples/Controls.Sample/Maui.Controls.Sample-net6.csproj]
```

I'm not sure if this is a bug in the iOS targets or not, but regardless of that, we don't want the iOS targets to try to bundle the `*.razor` files as resources anyway.

So, we need to try to prevent the iOS SDK from even seeing these files as potential bundle resources and let the Razor SDK do its compilation.

One way to solve this is to include some build assets in the .NET MAUI BlazorWebView NuGet package that convert  `*.razor` files that are `<Content ... />` items in the projectand convert them to `<RazorComponent ... />` so that the iOS targets won't see them at all, and the Razor SDK will compile them as intended.

**Comment by Eilon** [comment]
Another related issue is static assets. Static assets such as HTML and CSS in Blazor are typically marked as Content, but the iOS SDK wants to include them as BundleResources. To work around this I remove them from Content and add them as None. This is not the right long-term solution because they will need to get _into_ the bundle for iOS (though for MacCatalyst it might be OK).

**Comment by rolfbjarne** [comment]
> One way to solve this is to include some build assets in the .NET MAUI BlazorWebView NuGet package that convert `*.razor` files that are `<Content ... />` items in the projectand convert them to `<RazorComponent ... />` so that the iOS targets won't see them at all, and the Razor SDK will compile them as intended.

This is the correct solution.

> Another related issue is static assets. Static assets such as HTML and CSS in Blazor are typically marked as Content, but the iOS SDK wants to include them as BundleResources. To work around this I remove them from Content and add them as None. This is not the right long-term solution because they will need to get _into_ the bundle for iOS (though for MacCatalyst it might be OK).

Where in the iOS app bundle do you want the static resources?

You can set the Link metadata on Content items to specify where in the app bundle you want these items to end up.

**Comment by pranavkm** [comment]
> One way to solve this is to include some build assets in the .NET MAUI BlazorWebView NuGet package that convert *.razor files that are <Content ... /> items in the projectand convert them to <RazorComponent ... /> so that the iOS targets won't see them at all, and the Razor SDK will compile them as intended.

While this may be ideal, changing the itemgroup is going to be challenge. The change affects regular Blazor users (outside of MAUI) with customization around these items. We'd also have to juggle having different ItemGroups per TFM since we cannot change the ItemGroup for existing .NET 6 and earlier apps as part of an SDK update.

My suggestion was to instead add an attribute to `Content` items that the iOS and Android targets can ignore e.g. `<Content Include="..." ExcludeFromBundleResources="true" />`. There is precedence for this pattern in the .NET SDK: with things like [`ExcludeFromSingleFileExe`](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props#L30)

> Where in the iOS app bundle do you want the static resources?

@Eilon could you help with this?

**Comment by rolfbjarne** [comment]
> My suggestion was to instead add an attribute to `Content` items that the iOS and Android targets can ignore e.g. `<Content Include="..." ExcludeFromBundleResources="true" />`. There is precedence for this pattern in the .NET SDK: with things like [`ExcludeFromSingleFileExe`](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props#L30)

We can do this, we already have a `PublishFolderType` metadata we support for other item groups, we can easily add support for it to `Content` items as well (so you could set `PublishFolderType=None` for these).

**Comment by Eilon** [comment]
> Where in the iOS app bundle do you want the static resources?

We don't directly put them as iOS resources at all. We want the Razor SDK to see certain files (e.g. `wwwroot/**/*`) as Razor Static Web Assets. It then needs to convert those to `MauiAsset` MSBuild items, which is a feature of .NET MAUI. Then the MauiAssets tasks do "stuff" to convert those to whatever iOS/Android/Windows/MacCatalyst need on their systems (which, in iOS, is presumably a BundleResource?).

**Comment by rolfbjarne** [comment]
> > Where in the iOS app bundle do you want the static resources?
> 
> We don't directly put them as iOS resources at all. We want the Razor SDK to see certain files (e.g. `wwwroot/**/*`) as Razor Static Web Assets. It then needs to convert those to `MauiAsset` MSBuild items, which is a feature of .NET MAUI. Then the MauiAssets tasks do "stuff" to convert those to whatever iOS/Android/Windows/MacCatalyst need on their systems (which, in iOS, is presumably a BundleResource?).

Sounds like the same approach of having a custom metadata on Content items that tells us to not bundle those items in the app bundle would help here too.

**Comment by pranavkm** [comment]
Spoke to @jonathanpeppers and the plan is to something similar with the Android targets - the scope there is a bit more limited since all we need to do is exclude it from a warning check https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L778-L785.

**Comment by rolfbjarne** [comment]
I'm implementing support for the `PublishFolderType` on `Content` (and `BundleResource`) items for the next preview (14): https://github.com/xamarin/xamarin-macios/pull/14162.

Set `PublishFolderType=None` to prevent these items from being copied to the app bundle.
