### ISSUE TITLE
MultiWindow on iPad OS (splitview) share same underlying instance

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#7917]
### Description

James Montemagno shared that MultiWindow works in Preview 11 (https://www.youtube.com/watch?v=JFeulsDijs0). It is true that I can have multi window on iOS using SceneDelegate.cs. However, the app in each window is the same!

MauiUIApplicationDelegate.Current.Application is protected. This has to allow a new instance to be created for each new UIWindow.

In Xamarin.Forms, I can do the following:
      _application = new App();
      Xamarin.Forms.Application.SetCurrentApplication(_application);

Also, MauiProgram.CreateMauiApp() is static. Hence, I am unable to create multiple instances.

On iPad OS, all my interactions on any window occur on the latest instance of window.

### Steps to Reproduce

1. Create a new project.
2. Create SceneDelegates.cs in Platforms/iOS folder.
3. Insert the necessary info into info.plist to enable multiple windows.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPad OS

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Can you make a repro project of what you're expecting to happen?

If I create a new UIWindow, that _is_ a new window, and the contents in it are for that window. I'm not sure if you're trying to interact with stuff from `Application.Current` and that's where it gets weird?

**Comment by tekmun** [comment]
I am still working on a sample project. I try to revert by next week.
