### ISSUE TITLE
Mac Catalyst Remove existing MenuBarItem

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#7919]
### Description

For Mac Catalyst, Apple populates a standard template for the Main Menu Bar. According to Apple's documentation, we should override BuildMenu and then use the builder to remove unwanted menu. I have added the following in the AppDelegate.cs. I don't think this function is called or the UIMenu string ".format" is wrong. I want to remove the default Format MenuBarItem.

    public override void BuildMenu(IUIMenuBuilder builder)
    {
        base.BuildMenu(builder);
        builder.RemoveMenu(".format");
  }

### Steps to Reproduce

1. Create a new Maui App.
2. Add the function above in AppDelegate.cs for Mac Catalyst.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac Big Sur

### Did you find any workaround?

No.

**Comment by tekmun** [comment]
Can we escalate the resolution of this bug? I cannot publish a Mac App where the main menu bar contains menu that is irrelevant to my app. The Format menu is completely irrelevant to my app and hence must be removed before my app can be published. Thanks.

**Comment by kristinx0211** [comment]
verified this method does not work for Mac Catalyst.

**Comment by tekmun** [comment]
Thanks. It works.
The App Name can be changed using the CFBundleName.
