### ISSUE TITLE
Control status bar

### ISSUE THREAD

**Issue by 601093318** [dotnet/maui#7922]
### Description

I want to can hide or display the status bar, and can set the color of the status bar

### Public API Changes

```C#
public class Page
{
...
public class StatusBar {get;set;}

...
}
```

### Intended Use-Case

I want to can hide or display the status bar, and can set the color of the status bar

**Comment by janseris** [comment]
I am working for statusbar feature as well. Could you elaborate more on the use case that you want to achieve?

**Comment by TanayParikh** [comment]
Hi all, thanks for commenting. This appears to be a duplicate of https://github.com/dotnet/maui/issues/6159, closing this issue out to track there.
