### ISSUE TITLE
[MacOS] Program not crashing after throwing exception

### ISSUE THREAD

**Issue by xDaijobu** [dotnet/maui#7923]
### Description

[maui-test1.zip](https://github.com/dotnet/maui/files/8877677/maui-test1.zip)

<img width="1694" alt="Screen Shot 2022-06-10 at 16 37 05" src="https://user-images.githubusercontent.com/22674537/173037381-c79a087b-1741-416d-8136-44babb565b8f.png">

### Steps to Reproduce

Click the counter button & observe the bug.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 12.4

**Comment by jfversluis** [comment]
Hm I would think that maybe this is a bug in Visual Studio for Mac rather than with us...

**Comment by drasticactions** [comment]
If I understand it right (@PureWeen, @rolfbjarne correct me if I'm wrong) but I think MacOS apps capture and wrap all uncaptured application exceptions. I think you need to set something in the application context to rethrow the exception.

I don't think this is a MAUI specific issue, it's something that affects Mac apps in general, as (I think) it's following the general design of Mac apps. The Xamarin Mac SDK (And MAUI) are following that. Again, I think, I'm not sure if that's true, it's based off vague conversations I've had in the past. lol

But yeah, @PureWeen, @rolfbjarne, what do you think?

**Comment by rolfbjarne** [comment]
Yeah, this is a dup of #7176, which is also related to https://github.com/xamarin/xamarin-macios/issues/15037.
