### ISSUE TITLE
TextColor does not work correctly in Windows for the Picker and DatePicker.

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#7924]
### Description

The text color always remains black even if you put it in a different color. For the picker, the color changes to black when you move the mouse over it, sometimes the color changes just like that. Works correctly in Android.

Another bug is that the calendar icon shown on the DatePicker in Windows is not visible in Android.

I find the calendar very basic. It should be possible to enter the date with the keyboard as well. Now it is almost impossible to enter dates of birth.

### Steps to Reproduce

1. Open the attached app.
2. Try out the Picker and DatePicker.
3. 
[MauiAppTestPickers.zip](https://github.com/dotnet/maui/files/8877727/MauiAppTestPickers.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on windows and android 12 with vs 17.3.0 Preview 3.0 [32611.49.main].
on windows:
![image](https://user-images.githubusercontent.com/99457000/173295955-70a15050-ff91-4be1-b01f-0fa294bd1379.png)
on android:
![image](https://user-images.githubusercontent.com/99457000/173295883-75331c52-fba9-471f-afb9-b5a2d9125f0c.png)
