### ISSUE TITLE
ImageButton does not respect the height and width given to it

### ISSUE THREAD

**Issue by AswinPG** [dotnet/maui#7927]
### Description

The size of an Imagebutton is not accurate. The Heightrequest and widthrequest values are not respected. I will attach an image showing an ImageButton and a Button with the same height and width given in. During hot reload it sizes correctly but after the project is rerun the issue happens..
![Screenshot_20220610-163549](https://user-images.githubusercontent.com/29278621/173053524-d5199ff0-a8de-49b3-923d-0b751aafc77c.jpg)

### Steps to Reproduce

1. Create an imagebutton
2. Give it a fixed size 
3. check if the size is what we have given in..
4. You can compare it with a button of the same size

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12  

### Did you find any workaround?

No

**Comment by AswinPG** [comment]
![Screenshot_20220610-163549](https://user-images.githubusercontent.com/29278621/173053431-2e4a3273-0131-40ea-b910-43f5eacd0c9c.jpg)

**Comment by jfversluis** [comment]
Did you also check on other platforms if this happens or not? Windows, iOS/macOS?

**Comment by AswinPG** [comment]
It's working as expected on windows. I Could not test on iOS or macos

**Comment by kristinx0211** [comment]
@AswinPG I can't repro your issue, because on android 12, `button `and `imagebutton `works as the same size. please see the repro project and let me know if I miss somthing. repro project: 
[MauiApp16.zip](https://github.com/dotnet/maui/files/8889774/MauiApp16.zip)

![image](https://user-images.githubusercontent.com/99457000/173322539-5fc8a2cd-64fe-4d0c-a3a6-313bfb4b52a8.png)

**Comment by AswinPG** [comment]
@kristinx0211 It seems like the sizing issue is only present if you add padding to the imagebutton. I'll upload an updated sample. If padding is 0 there is no issue.
![Screenshot_1655115042](https://user-images.githubusercontent.com/29278621/173331628-46e20394-77ec-48c6-a593-7f3fa4aca48f.png)

[MauiApp16.zip](https://github.com/dotnet/maui/files/8890133/MauiApp16.zip)

**Comment by AswinPG** [comment]
https://github.com/dotnet/maui/pull/4665#issuecomment-1058786525
I think this here is the issue I am experiencing. Was this fix not included in the latest release ?

**Comment by kristinx0211** [comment]
@AswinPG thanks for your update, I can repro this issue with add padding.

**Comment by EthanHipps** [comment]
I am also running into this same issue

**Comment by JozefGula** [comment]
I have the same issue when applying padding on ImageButton (Only android).

**Comment by hemantbeast** [comment]
On iOS/Mac it takes full size of the image.
Image size: 72x72 px
 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/10476066/203234924-5090003e-24b1-47cd-b957-8edd1ab50739.png">

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10476066/203235055-71875766-fa09-4b5d-9cbf-c696da1065f3.png">

**Comment by muak** [comment]
In Android, if Padding is set, the display size will be reduced by the Padding and will not be displayed correctly.
In iOS, WidthRequest and HeightRequest are the display size and the size of the ImageButton itself is WidthRequest+Padding, but this is not the case in Android.
