### ISSUE TITLE
Unable to block popups in BlazorWebView

### ISSUE THREAD

**Issue by Flaflo** [dotnet/maui#7930]
### Description

When trying to manually handle CoreWebViewOnNewWindowRequested Event we are unable to supress the starting of an external process opening the file dragged into the webiew. It will always open for example Notepad when dragging a .txt file into it.

I managed to locate why this is happening:
[https://github.com/dotnet/maui/commit/78c1ffe593965d16b5aacd9d320e19c1cac55031#diff-75c4562a2bc68615b8d28c071b33a112272d1e08e4ba087c461736787ff8f534](https://github.com/dotnet/maui/blob/d6bc1ca6ff47d49d0ce2d254df7416f0aee52e68/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs#L343)

I think it would be better to check if ``args.Handled`` is already set to true and do not proceed if condition matches.

```c#
    private void CoreWebView2_NewWindowRequested(object? sender, CoreWebView2NewWindowRequestedEventArgs args)
    {
        // Intercept _blank target <a> tags to always open in device browser.
        // The ExternalLinkCallback is not invoked.

        if (!args.Handled && Uri.TryCreate(args.Uri, UriKind.RelativeOrAbsolute, out var uri))
        {
            LaunchUriInExternalBrowser(uri);
            args.Handled = true;
        }
    }
```

I did not test it and it may depend on the order of execution of the event listeners. But there has to be a way to disable it.
This also prevents any js popup to appear through the webview.

### Steps to Reproduce

1. Create a WinForms app with BlazorWebView.
2. Drag any file into the webview
3. A Process will start

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Any Version of Windows, MacOS or Linux

### Did you find any workaround?
If the page has loaded just do this. It will remove any event handler that was not registered by current class:
```c#
    var coreWebView = _blazorWebView.WebView.CoreWebView2;
         
    var eventHandlerField = (EventHandler<CoreWebView2NewWindowRequestedEventArgs>) coreWebView.GetType().GetFields(BindingFlags.Instance | BindingFlags.NonPublic)
            .First(it => it.Name == "newWindowRequested").GetValue(coreWebView);

    foreach (EventHandler<CoreWebView2NewWindowRequestedEventArgs> subscriber in eventHandlerField.GetInvocationList())
    {
        if (subscriber.Method.DeclaringType == GetType()) continue;
        coreWebView.NewWindowRequested -= subscriber;
    }
```

**Comment by janseris** [comment]
@jfversluis does removing needs-verification tag without actual verification on a lot of issues in MAUI mean that the bug has been actually known already?

**Comment by TanayParikh** [comment]
@Flaflo, I'm unable to repro this using the steps provided, can you please provide a minimal, public, github repository which repros this issue?

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/14852843/173466033-99ff49d4-ca8c-44ab-96d9-602802114f8c.png">

**Comment by Flaflo** [comment]
> @Flaflo, I'm unable to repro this using the steps provided, can you please provide a minimal, public, github repository which repros this issue?
> 
> <img alt="image" width="1329" src="https://user-images.githubusercontent.com/14852843/173466033-99ff49d4-ca8c-44ab-96d9-602802114f8c.png">

I'll try my best.

**Comment by Flaflo** [comment]
I updated my reproduction steps because they weren't correct. You have to create a WinForms App and use BlazorWebView.

**Comment by TanayParikh** [comment]
Thanks @Flaflo I'm able to repro.

> I think it would be better to check if args.Handled is already set to true and do not proceed if condition matches.

Unfortunately, this doesn't appear to be sufficient as it's already `false`.


<img width="1329" alt="image" src="https://user-images.githubusercontent.com/14852843/173664893-bfe6e32d-3d81-41b8-b4d3-757f9ade3b50.png">

This does appear to be unintentional behavior though. I've created a separate issue on the `CoreWebView2` to try to understand what may be going on here. https://github.com/MicrosoftEdge/WebView2Feedback/issues/2527

**Comment by TanayParikh** [comment]
Looks like this is a known issue on the webview, closing this out as a duplicate of https://github.com/MicrosoftEdge/WebView2Feedback/issues/278.

**Comment by Flaflo** [comment]
To sum it up: This is not WebView's fault. The reason why the files are open externally is because of the registered event finding a valid uri like "file://" or "about:blank" and tries to "LaunchUriInExternalBrowser".

**Comment by TanayParikh** [comment]
> The problem is that the event handler opens a file without the posibility to cancel or turn off that behavior.

I beg to differ, the issue here is the fact that dragging a file onto the webview results in the invocation of the `NewWindowRequested` event handler.

https://github.com/dotnet/maui/commit/78c1ffe593965d16b5aacd9d320e19c1cac55031#diff-75c4562a2bc68615b8d28c071b33a112272d1e08e4ba087c461736787ff8f534R206-R215

If that event handler isn't called in the first place, then there isn't any need to "cancel" the request at all.

**Comment by Flaflo** [comment]
The problem would be fixed if you would make registering that event handler optional.

**Comment by TanayParikh** [comment]
> It mimics the behavior of a normal browser that whould also try to open the file in a new tab or window. 

Yeah I think that's a fair argument. 

> JS popups are kind of important to me. And if just dragging files in would stop calling the new window requested event, leaving your code untouched, it would still stop my application to open any popup windows.

It's a bit unclear what you mean by JS popups here / what the intended use case is. Could you please clarify by providing an example or repro of the JS Popup behavior you're trying to achieve. 

Re-opening this issue to consider integrating the New Window default logic with the [`URLLoadingStrategy`](https://docs.microsoft.com/aspnet/core/blazor/hybrid/routing?view=aspnetcore-6.0) we have for regular links.

https://github.com/dotnet/maui/blob/d6bc1ca6ff47d49d0ce2d254df7416f0aee52e68/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs#L343-L352

**Comment by TanayParikh** [comment]
Clearing labels/milestone/project so we can re-discuss during triage.

**Comment by Flaflo** [comment]
> Yeah I think that's a fair argument.

Thank you.

> It's a bit unclear what you mean by JS popups here / what the intended use case is. Could you please clarify by providing an example or repro of the JS Popup behavior you're trying to achieve.

I don't know if this needs a specific use-case, because I can't come up with a reason why it should be activly blocked from working.
But a specific use-case is a popup that is opened through JS that has content dynamically generated inside, that gets automatically opened in a print-view by the chromium print function. I unfortunately cannot share the code or more details here.

A repro of the popup behavior is already in the repro I sent before. There is a button you can click and it trys to open a about:blank popup window.

https://github.com/Flaflo/maui_repro_7930/blob/master/maui_repro_7930/wwwroot/js/app.js

**Comment by TanayParikh** [comment]
> A repro of the popup behavior is already in the repro I sent before. There is a button you can click and it trys to open a about:blank popup window.
> https://github.com/Flaflo/maui_repro_7930/blob/master/maui_repro_7930/wwwroot/js/app.js

I can't run this project in my current environment, but to confirm, you're saying the issue is this doesn't work (ie. doesn't open a new browser window in the default browser?) Is there a reason you're doing `window.open` instead of `<a target="_blank" href="https://github.com"></a>`? Can you potentially use the anchor tag and "click" it via JS to simulate `window.open`? If you haven't already I'd recommend reviewing the URL loading strategy behavior here: https://docs.microsoft.com/aspnet/core/blazor/hybrid/routing?view=aspnetcore-6.0


> that gets automatically opened in a print-view by the chromium print function

If printing is your goal, this should already be [supported](https://github.com/dotnet/maui/issues/7880#issuecomment-1156269043) and longer term, there exists https://github.com/dotnet/maui/issues/4795.

**Comment by Flaflo** [comment]
> Is there a reason you're doing `window.open` instead of `<a target="_blank" href="https://github.com"></a>`

Yes because there is a part in JS that injects DOM using the window instance.

> If printing is your goal, this should already be [supported](https://github.com/dotnet/maui/issues/7880#issuecomment-1156269043) and longer term, there exists #4795.

This would not fit our use-case unfortunately.

**Comment by TanayParikh** [comment]
> Yes because there is a part in JS that injects DOM using the window instance.

Not sure what you mean by "part in JS", are you saying your application JS code is manipulating the DOM? Regardless, if we do decide to integrate the URL loading strategy with the new window handler, then you can simply `Cancel` the default handling and it'll be as if the handler wasn't there in the first place. I believe this would achieve what you're looking for.

**Comment by Flaflo** [comment]
> Not sure what you mean by "part in JS", are you saying your application JS code is manipulating the DOM?

The app is creating a blank popup with "about:blank" and dynamically injects DOM into it.

> Regardless, if we do decide to integrate the URL loading strategy with the new window handler, then you can simply `Cancel` the default handling and it'll be as if the handler wasn't there in the first place. I believe this would achieve what you're looking for.

Sounds good to me.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by Flaflo** [comment]
> Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

I would argue, that this is a security risk and regardless of community interest, this should be fixed. Dropping files into the WebView executes them. Please reconsider.
