### ISSUE TITLE
MAUI Blazor project template should be consistent in indentation type (spaces vs. tabs)

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/maui#7934]
### Description

When creating a new project, the files created use a mix of spaces and tabs for indentation.

Files with tabs:
* Data\WeatherForecast.cs
* Data\WeatherForecastService.cs
* Pages\FetchData.razor
* Platforms\Android\AndroidManifest.xml
* Platforms\Android\MainApplication.cs
* Platforms\iOS\AppDelegate.cs
* Platforms\iOS\Program.cs
* Platforms\MacCatalyst\AppDelegate.cs
* Platforms\MacCatalyst\Program.cs
* Platforms\Tizen\Main.cs
* Shared\MainLayout.razor
* Shared\NavMenu.razor
* App.xaml.cs
* MainPage.xaml.cs
* MauiProgram.cs

Files with spaces:
* Pages\Counter.razor
* Platforms\Android\Resources\values\colors.xml
* Platforms\Tizen\tizen-manifest.xml
* Platforms\Windows\app.manifest
* Platforms\Windows\App.xaml
* Platforms\Windows\App.xaml.cs
* Shared\MainLayout.razor.css
* Shared\NavMenu.razor.css
* Shared\SurveyPrompt.razor
* App.xaml
* MainPage.xaml

Files with a mix of both:
* wwwroot\css\app.css
* wwwroot\index.html
* Main.razor

Furthermore, the use of tabs is inconsistent with all other file templates in VS, as per #5068, so adding any additional files to the project will create more inconsistency.  (This is in small part a VS issue, but this is the only template that uses tabs, so... 🤷‍♂️)

The MAUI App template (non-Blazor) uses spaces consistently.

### Steps to Reproduce

1. Create a new project
2. Submit for PR
3. Be ridiculed for having mixed indentation by your friends and coworkers ;)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

VS 17.3.32602.284

### Did you find any workaround?

Open each file and format it the way I expect.

**Comment by janseris** [comment]
Why is this even a problem? Vim cannot display identation using TABs?

**Comment by jimmylewis** [comment]
It's an annoyance to those who notice it.

**Comment by TanayParikh** [comment]
> Be ridiculed for having mixed indentation by your friends and coworkers ;)

Verified repro, put up https://github.com/dotnet/maui/pull/7976 😄
