### ISSUE TITLE
[Win] Editor's CursorPosition and SelectionLength properties are not limited to Text.Length

### ISSUE THREAD

**Issue by SotoiGhost** [dotnet/maui#7937]
### Description

If you set the Editor's `CursorPosition` or `SelectionLength` properties by code, you can set a value beyond the Text.Length value. On Android or iOS, the value is capped to the text's length.

Here's the testcase: https://github.com/SotoiGhost/maui-EditorPropertiesIssue

https://user-images.githubusercontent.com/5924210/173146088-22e247e1-e908-450e-a563-a4f362397653.mp4

### Steps to Reproduce

1. Open the testcase
2. Run the testcase
3. Click on the "Click me" button

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0 and up

**Comment by VincentBu** [comment]
repro with vs main build 32611.49

**Comment by hartez** [comment]
This was fixed by #7371.
