### ISSUE TITLE
Blazor Desktop .NET MAUI templates

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#794]
Need a `dotnet new` template that is essentially the same as a regular .NET MAUI project in terms of structure, but with content from the default Blazor Web project.

**Comment by Eilon** [comment]
* Main template work was done here: https://github.com/dotnet/maui/pull/1055
* WinUI template was implemented here: https://github.com/dotnet/maui/pull/1065

**Comment by Dukenware** [comment]
Would it be possible to add a .NET MAUI Blazor template with options "ASP.NET Core hosted" and "Authentication" at the same time?

**Comment by Eilon** [comment]
@Dukenware please file a new issue for that. It's unlikely to happen for v1 because it's a _lot_ of work to build such a thing, but in the future perhaps.

**Comment by Dukenware** [comment]
I have created a new issue for this: https://github.com/dotnet/maui/issues/4488
