### ISSUE TITLE
rzc rewritecss exited with code -2147450730.

### ISSUE THREAD

**Issue by anirugu** [dotnet/maui#7955]
### Description

On fresh VS 2022 LTSC 17.0 and then upgrade to preview 17.3.1. I create multiple projects and try to run them (which work fine from other PC I have).

Didn't make any changes. Just create from VS and try to run. It's failing with the error.

![image](https://user-images.githubusercontent.com/35772421/173215321-f0cdb769-2f5d-4d01-9384-774faf685614.png)

### Steps to Reproduce

It might be due to 17.0 LTSC which I update to the latest preview. Earlier I checked xamarin + .net web and later MAUI got selected when I updated.

### Version with bug

6.0 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android12

### Did you find any workaround?

NA

### Relevant log output

```shell
NA
```

**Comment by MagicAndre1981** [comment]
run `dotnet --info` from inside cmd.exe and check if SDK 6.0.300 is installed. You maybe only have the .100 and preview SDKs but miss the stable 300 SDK.

**Comment by anirugu** [comment]
I uninstall the VS and install the preview version directly (without upgrade from LTSC) and it's started working. Thanks
