### ISSUE TITLE
MAUI Templates missing from Visual Studio 2022 Preview 17.3 on macOS 

### ISSUE THREAD

**Issue by omar-ebrahim** [dotnet/maui#7958]
**Description**

After installing MAUI, I am unable to add any new XAML pages. Xamarin or MAUI templates should appear
![image](https://user-images.githubusercontent.com/11367432/173222853-1749bd4c-d763-4f67-a7ef-8034f3cd2d93.png)

Windows version for comparison
![image](https://user-images.githubusercontent.com/11367432/173223159-804b7395-d5e2-44d3-8175-5396675751cb.png)

I have installed the necessary packages
![image](https://user-images.githubusercontent.com/11367432/173222922-8683ce3b-f0a1-41c2-a75d-878fdce0a8b3.png)
<img width="912" alt="Screenshot 2022-06-12 at 08 49 02" src="https://user-images.githubusercontent.com/11367432/173222944-4689d948-6d79-4fff-bfc4-1754f48a4b9f.png">

Running `dotnet new maui --list` shows the following output
```
omar@Omars-MacBook-Pro ~ % dotnet new maui --list
These templates matched your input: 'maui'

Template Name                        Short Name        Language  Tags                                                     
-----------------------------------  ----------------  --------  ---------------------------------------------------------
.NET MAUI App                        maui              [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen        
.NET MAUI Blazor App                 maui-blazor       [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen/Blazor 
.NET MAUI Class Library              mauilib           [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen        
.NET MAUI ContentPage (C#)           maui-page-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentPage (XAML)         maui-page-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentView (C#)           maui-view-csharp  [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ContentView (XAML)         maui-view-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Tizen/Xaml/Code
.NET MAUI ResourceDictionary (XAML)  maui-dict-xaml    [C#]      MAUI/Android/iOS/macOS/Mac Catalyst/WinUI/Xaml/Code
```

**Steps to reproduce**

1. Install Xcode and run it to finish installing the Cocoa packages
2. Install Visual Studio Preview 2022 17.3
3. Select all available templates to install **including MAUI**
4. Once installed, create a new MAUI project
5. Right-click the project that's been created and click `Add > New file...`

**Version with bug**

17.3 (current)

**Last version that worked well**

Unknown/Other

**Affected platforms**

All / N/A

**Affected platform versions**

macOS Monterey 12.4

**Did you find any workaround?**

No

**Relevant log output**

None

**Comment by mrward** [comment]
[Visual Studio for Mac 17.3 preview 2](https://docs.microsoft.com/en-us/visualstudio/releases/2022/mac-release-notes-preview#17.3.0-pre.2) which was released today has support for MAUI item templates.

![](https://user-images.githubusercontent.com/372361/170731280-2bae93e3-74a0-48e4-81d1-5e3fdc6571b8.png)

**Comment by coreyperkins** [comment]
@mrward I have this issue with preview 2. I have dotnet version 6.0.301

`❯ dotnet --version
6.0.301
❯ dotnet new --list
These templates matched your input:

Template Name                                 Short Name      Language    Tags
--------------------------------------------  --------------  ----------  -------------------------------------
ASP.NET Core Empty                            web             [C#],F#     Web/Empty
ASP.NET Core gRPC Service                     grpc            [C#]        Web/gRPC
ASP.NET Core Web API                          webapi          [C#],F#     Web/WebAPI
ASP.NET Core Web App                          webapp,razor    [C#]        Web/MVC/Razor Pages
ASP.NET Core Web App (Model-View-Controller)  mvc             [C#],F#     Web/MVC
ASP.NET Core with Angular                     angular         [C#]        Web/MVC/SPA
ASP.NET Core with React.js                    react           [C#]        Web/MVC/SPA
ASP.NET Core with React.js and Redux          reactredux      [C#]        Web/MVC/SPA
Blazor Server App                             blazorserver    [C#]        Web/Blazor
Blazor WebAssembly App                        blazorwasm      [C#]        Web/Blazor/WebAssembly/PWA
Class Library                                 classlib        [C#],F#,VB  Common/Library
Console App                                   console         [C#],F#,VB  Common/Console
dotnet gitignore file                         gitignore                   Config
Dotnet local tool manifest file               tool-manifest               Config
EditorConfig file                             editorconfig                Config
global.json file                              globaljson                  Config
MSTest Test Project                           mstest          [C#],F#,VB  Test/MSTest
MVC ViewImports                               viewimports     [C#]        Web/ASP.NET
MVC ViewStart                                 viewstart       [C#]        Web/ASP.NET
NuGet Config                                  nugetconfig                 Config
NUnit 3 Test Item                             nunit-test      [C#],F#,VB  Test/NUnit
NUnit 3 Test Project                          nunit           [C#],F#,VB  Test/NUnit
Protocol Buffer File                          proto                       Web/gRPC
Razor Class Library                           razorclasslib   [C#]        Web/Razor/Library/Razor Class Library
Razor Component                               razorcomponent  [C#]        Web/ASP.NET
Razor Page                                    page            [C#]        Web/ASP.NET
Solution File                                 sln                         Solution
Web Config                                    webconfig                   Config
Worker Service                                worker          [C#],F#     Common/Worker/Web
xUnit Test Project                            xunit           [C#],F#,VB  Test/xUnit`

**Comment by coreyperkins** [comment]
@mrward - reinstalled the maui workload via the steps at https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md and the templates are back.

**Comment by jfversluis** [comment]
A new preview has been releases one or two days ago that should have the templates. Enjoy!
