### ISSUE TITLE
Maui-ios Adding appcenter to MAUI default project throws link error in debug 

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#7959]
### Description

I have added the appcenter latest nuget and the application failed to run in device throwing a link error.

Only adding the nuget creates this issue.

<ItemGroup>
	  <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.5.1" />
	  <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.5.1" />
	</ItemGroup>

ILLink : iOS error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information.
ILLINK : error MT2403: The linker step 'Backing Fields Optimizer' failed processing `System.Void Microsoft.AppCenter.Crashes.iOS.Bindings.MSACExceptionModel::Dispose(System.Boolean)`.
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(109,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.

### Steps to Reproduce

Add refrence to the Appcenter nuget in a fresh Maui project and it fails to run in iOS it throws link error when trying to run iOS.

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 1

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No workaround untill now setting  <PublishTrimmed>True</PublishTrimmed> to false also throws an error it should be true in ios.

### Relevant log output

```shell
Using "NETSdkError" task from assembly "/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
  Task "NETSdkError"
    /usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(109,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
  Done executing task "NETSdkError" -- FAILED.
```

**Comment by jfversluis** [comment]
App Center has not released versions that are compatible with .NET MAUI yet. Please add on their repo or feedback channels, for instance here: https://github.com/microsoft/appcenter/issues/2360

**Comment by Syed-RI** [comment]
> App Center has not released versions that are compatible with .NET MAUI yet.

Does that imply a release is incoming or being worked on? ;)
