### ISSUE TITLE
IOS ShellContent Icon property disables page navigation

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#7962]
### Description

Setting the Icon property to ShellContent in Shell makes page inaccessible And does not display Icon  
![image](https://user-images.githubusercontent.com/2603287/173229634-00573ca1-8728-4cfd-b9ff-1f803b20ff47.png)

Works Correctly on Android

### Steps to Reproduce

Create MauiApp
Add Pages
Set the Icon property on one of the ShellContent items
Run the app
Select the page in the menu
The page stays the same and never navigates to the selected page

Expected Result:
Icon should display (like on Android)
And selecting This ShellContent menu item should navigate to the page

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15.5 and others

### Did you find any workaround?

Remove the Icon property

**Comment by kristinx0211** [comment]
@pierre01 I write a simple project to repro this issue, but I don't see this issue on my IOS15.4 emulator, the Icon is show for me and I can navigates to the selected page. could you verified this and tell me if I miss something on it.
```
    <ShellContent
        Title="Buttons"
        ContentTemplate="{DataTemplate local:ButtonPage}"
        Route="ButtonPage" />
    <ShellContent
        Title="Text Inputs"
        ContentTemplate="{DataTemplate local:TextInputPage}"
        Route="TextInputPage" />
    <ShellContent
        Title="TestPage"
        ContentTemplate="{DataTemplate local:TestPage}"
        Icon="dotnet_bot.png"
        Route="TestPage" />
```
repro project:[MauiApp4.zip](https://github.com/dotnet/maui/files/8907119/MauiApp4.zip)
![image](https://user-images.githubusercontent.com/99457000/173775349-42bea8b0-c467-4b4e-ad4b-c6c8ecabf3ed.png)
![image](https://user-images.githubusercontent.com/99457000/173775417-d4592fcb-eac5-49fa-8b19-18ab6fec92e5.png)

**Comment by pierre01** [comment]
@kristinx0211 This issue had to do with the recent reorganization of folders in the new MAUI templates.
If I add this line in the project : everything works. 

`<MauiImage Include="Resources\AppIcon\*" />`

This was likely the cause of the bugs (I was using the app icon as an image).
The image existed in the project but was not considered an image.

I will verify on IOs once I am able to run my MAUI apps again
