### ISSUE TITLE
Entry changes font family when IsPassword is true

### ISSUE THREAD

**Issue by sact1909** [dotnet/maui#7966]
### Description

If you put an Entry and set the property IsPassword to True, the entry changes the font

|IsPassword = False|IsPassword = True|
|---|---|
|![image](https://user-images.githubusercontent.com/23615129/173237969-cc66d568-a4b0-4efe-9bce-e8d68037300d.png)|![image](https://user-images.githubusercontent.com/23615129/173237944-429f9d39-b2e5-4a1e-8239-64dec5f8af34.png)|

### Steps to Reproduce

1. Create a .NET MAUI APP
2. Add an Entry
3. Set a Placeholder label
4. Set the Property IsPassword to True

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

**Comment by kristinx0211** [comment]
verified repro on android  12 with vs 17.3.0 Preview 3.0 [32611.49.main]. repro project: [MauiApp13.zip](https://github.com/dotnet/maui/files/8887619/MauiApp13.zip)
![image](https://user-images.githubusercontent.com/99457000/173272639-9f1778da-8f39-4478-b214-529b7714d28e.png)
