### ISSUE TITLE
DatePicker: Format not working on Windows. VS 2022 - Version 17.3.0 Preview 1.1

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui#7972]
### Description

I defined DatePicker with this format: "dd/MM/yyyy"; here you have the XAML definition:

`            <Label Text="Fecha de Nacimiento"/>
            <DatePicker Format="dd/MM/yyyy"/>`

Format is not working on Windows, it displays the standard date format: "MM/dd/yyyy". On Android, this specific format is working well.

Please, see the images attached...

On Windows:
![image](https://user-images.githubusercontent.com/5513105/173242302-6166bc8a-e42e-43f6-bbb1-fd3c3cdecf74.png)

On Android:
![image](https://user-images.githubusercontent.com/5513105/173242371-e1645334-5db3-449b-8a53-32a4f6e311de.png)

### Steps to Reproduce

1. Create a New MAUI App (Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.1)
2. Add a Label and a DatePicker with this XAML fragment:

`            <Label Text="Fecha de Nacimiento"/>
            <DatePicker Format="dd/MM/yyyy"/>`
3. Run it on Windows (in my case Windows11) and on Android (in my case Android12 - Api 31).

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

6.0.300 [C:\Program Files\dotnet\sdk]

### Did you find any workaround?

No.

**Comment by NonameMissingNo** [comment]
Reproducible on Windows 11, VS 17.3.0 Preview 1.1
![image](https://user-images.githubusercontent.com/40233496/173243437-1b61538e-51a2-4e6d-bf74-c7e595d52864.png)

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.3.0 Preview 3.0 [32611.49.main].
![image](https://user-images.githubusercontent.com/99457000/173270586-a829270b-1a8c-480b-b7df-f36a2ff1cbb0.png)

**Comment by michel-ls** [comment]
I'm sorry but on the last sdk 6.0 on VS 2022 Version 17.4.0 Preview 2.1 it is not working
