### ISSUE TITLE
ClockPage Refresh of current time clock is stop after some seconds or time

### ISSUE THREAD

**Issue by SandeepBhor** [dotnet/maui#7978]
### Description

I am trying to run ClockPage sample explained in document.
In this page time gets refresh using ClockViewModel : INotifyPropertyChanged
But clock stops refresh after some seconds or may be minutes
[ClockPage.zip](https://github.com/dotnet/maui/files/8889270/ClockPage.zip)

### Steps to Reproduce

Just run the project
Click on navigate
After some time clock with be stop to refresh.
If you go back to main page and again navigate to clock page, it works properly.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Yes
Timer tt = new Timer(new TimerCallback((s) => this.DateTime1 = DateTime.Now));
            tt.Change(0, 1000);
this works

----
but this not works
Timer tt1 = new Timer(new TimerCallback((s) => this.DateTime1 = DateTime.Now), null, 0, 1000);

**Comment by kristinx0211** [comment]
confirm this issue on android with above project.

**Comment by jfversluis** [comment]
This was an issue with the Docs (https://github.com/dotnet/docs-maui/pull/601) which is now fixed!
