### ISSUE TITLE
[Android/iOS] Scrollview Direction=Both not working with Label as the content

### ISSUE THREAD

**Issue by roubachof** [dotnet/maui#7979]
### Description

Setting Orientation=Both in scrollview only works horizontally for android, and doesn't work at all on iOS (see #7933).

```xml
 <Grid Grid.Row="1">
            <Border x:Name="LogsBorder"
                    Stroke="WhiteSmoke"
                    StrokeThickness="2">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <ScrollView Orientation="Both" >
                    <!-- <Editor x:Name="Logs" -->
                    <!--         FontSize="13" -->
                    <!--         IsReadOnly="True" -->
                    <!--         AutoSize="TextChanges" -->
                    <!--         HorizontalOptions="Fill" -->
                    <!--         VerticalOptions="Fill"/> -->
                    <Label x:Name="Logs"
                           FontSize="13"
                           Margin="5,0"
                           LineBreakMode="WordWrap"/>
                </ScrollView>
            </Border>

            <Button x:Name="Refresh"
                    Text="Refresh"
                    VerticalOptions="End"
                    Margin="0,0,0,15"
                    HorizontalOptions="Center"
                    Clicked="OnRefreshClicked"/>
        </Grid>
```

![image](https://user-images.githubusercontent.com/596903/173333232-0a89231e-0003-4fd8-bc1a-ee0a677ab6ed.png)

### Steps to Reproduce

Steps to Reproduce
Clone: https://github.com/roubachof/MetroLog/tree/maui

* Run MetroLogSmaple.Maui on Android.
* Click on the Show Logs button.
* Hit Refresh, till it fills the space.
* Try to scroll vertically

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android API 31

### Did you find any workaround?

Nope

**Comment by roubachof** [comment]
Still happening in VS 17.3.0 preview 4.0

**Comment by Mous625** [comment]
Can confirm this is also happening on iOS. Scroll only works after closing the app (NOT terminating) and reopening it. These bugs shouldn't be allowed in production-ready software especially when they weren't even present in Xamarin.
