### ISSUE TITLE
Build fails if app references library which contains framework library inside

### ISSUE THREAD

**Issue by nevse** [dotnet/maui#7980]
### Description

Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the issue described bellow. This issue has a Very High priority for us and we do not have a workaround. Thank you for your help

We are using prevew version of  Visual Studio (17.3.0 Preview 1.1) and was straggled with issue while running my app. 
```
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.303\targets\Xamarin.Shared.Sdk.targets(656,3): error : Could not find a part of the path 'C:\Users\nevse\Library\Caches\Xamarin\mtbs\builds\EditorsGetStarted\c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6\obj\Debug\net6.0-ios\iossimulator-x64\linker-cache\DXListView.framework\DXListView'
```

To run my app on VS on Windows I am using 'pair to mac' and running app on ios simulator on my mac. 
Our bindning library 'Binaries\iOS\iossimulator-x64\DevExpress.Maui.iOS.CollectionView.dll ' contains Framework library with option "<NoBindingEmbedding>false</NoBindingEmbedding>"

### Steps to Reproduce

1. I've prepared the project to reproduce issue. You can find it here https://github.com/nevse/maui-tests-pair-to-mac-static-lib
2. open solution `src\EditorsGetStarted.sln` in vs 2022 (17.3.0 Preview 1.1) 
3. pair to mac, choose one of ios emulator and try to run app

you will obtain error similar to below one

```
error : Could not find a part of the path 'C:\Users\nevse\Library\Caches\Xamarin\mtbs\builds\EditorsGetStarted\c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6\obj\Debug\net6.0-ios\iossimulator-x64\linker-cache\DXListView.framework\DXListView
```

But the real path on mac is 'Users/nevse/library/caches/Xamarin/mtbs/builds/EditorsGetStarted/c009c8458d7df2efea22d5e54f441ec27e39739c452fe504252f7d40b77cf6f6/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/DXListView.framework/DXListView'

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS, Windows

### Affected platform versions

ios15, windows 10

**Comment by rolfbjarne** [comment]
Note to self: this seems to be a Windows-only problem, the test solution works fine on macOS.

**Comment by AntonKosenkoDX** [comment]
Hello!
It's totally severe bug for us. Is there some workaround?
Thanks.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#15289

**Comment by samirgcofficial** [comment]
Our app is on high priority! Any work around or fix that helps us to resolve this issue ? 
@Devexpress @VisualStuido 
Thanks

**Comment by rolfbjarne** [comment]
@samirgcofficial we're working on fixing it, but I wasn't able to come up with a workaround (except build on Mac) :/
