### ISSUE TITLE
Readonly Editor cannot show multiple lines on Android

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#7989]
### Description

If you have an Editor that is set to read only, it will always show the content on a single line in Android:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/3163293/173368968-d5a56bce-11e4-4774-a9f3-fbd599ab75a5.png">

In Windows it works as expected:

![image](https://user-images.githubusercontent.com/3163293/173369293-febe8503-c0ac-406a-865b-8df380ef5c53.png)

### Steps to Reproduce

1. Create a new MAUI application
2. Add these line in the main page:

``` XAML
<Label Text="Normal editor" 
        FontSize="30" 
        FontAttributes="Bold"
        />

<Editor 
    HeightRequest="200" 
    BackgroundColor="Purple"
    TextColor="White"
    IsReadOnly="False" 
    Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget tempus lorem. Sed vitae elit nisi. Donec quis quam sed mi lobortis suscipit vel quis augue. Phasellus risus enim, venenatis id blandit non, vehicula nec dui. Quisque luctus nisi vel ex imperdiet, eget molestie nisl cursus. Cras posuere vulputate lectus, ut sodales augue consequat vel." 
    />

<Label Text="Readonly editor" 
        FontSize="30" 
        FontAttributes="Bold"
        />
            
<Editor 
    HeightRequest="200" 
    BackgroundColor="DarkBlue"
    TextColor="White"
    IsReadOnly="True" 
    Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget tempus lorem. Sed vitae elit nisi. Donec quis quam sed mi lobortis suscipit vel quis augue. Phasellus risus enim, venenatis id blandit non, vehicula nec dui. Quisque luctus nisi vel ex imperdiet, eget molestie nisl cursus. Cras posuere vulputate lectus, ut sodales augue consequat vel." 
    />
```

3. Run the application in Android

Full sample code: https://github.com/pekspro/MauiIssues/tree/7989_Readonly_editor_no_multiline_on_Android

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No.

**Comment by VincentBu** [comment]
repro with vs [32613.285.main]
