### ISSUE TITLE
TapGestureRecognizer does not work in label's span

### ISSUE THREAD

**Issue by yz2yz** [dotnet/maui#8004]
### Description

In the following xaml, tap does't work and react to the finger tap.

            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="Alternatively, click " />
                        <Span Text="here"
                  TextColor="Blue" FontSize="24"
                  TextDecorations="Underline">
                            <Span.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding TapCommand}"
                                          CommandParameter="https://docs.microsoft.com/dotnet/maui/" />
                            </Span.GestureRecognizers>
                        </Span>
                        <Span Text=" to view .NET MAUI documentation." />
                    </FormattedString>
                </Label.FormattedText>
            </Label>

### Steps to Reproduce

create an maui app
add label and some span
add TapGestureRecognizer 

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 10、windows sdk 10.0.19041.0

### Did you find any workaround?

no workaround. but TapGestureRecognizer  in label works like the following xaml:
            <Label Text="here"
                  TextColor="Blue" FontSize="24"
                  TextDecorations="Underline">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding TapCommand}"
                                          CommandParameter="https://docs.microsoft.com/dotnet/maui/" />
                </Label.GestureRecognizers>
            </Label>

### Relevant log output

```shell
no
```

**Comment by VincentBu** [comment]
repro with vs [32613.285.main] on Android emulator(Android 12) and Windows

**Comment by yzbai** [comment]
This is annoying.

**Comment by bdcoder2** [comment]
Copied and pasted the following code from the official docs at: [https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/label](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/label)

```
<Label>
    <Label.FormattedText>
        <FormattedString>
            <Span Text="Alternatively, click " />
            <Span Text="here"
                  TextColor="Blue"
                  TextDecorations="Underline">
                <Span.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding TapCommand}"
                                          CommandParameter="https://docs.microsoft.com/dotnet/maui/" />
                </Span.GestureRecognizers>
            </Span>
            <Span Text=" to view .NET MAUI documentation." />
        </FormattedString>
    </Label.FormattedText>
</Label>
```

The Command never fires!!   HOW do we set-up a hyperlink in .Net MAUI ??   

PLEASE update code example or provide  workaround.

Thanks in advance.

**Comment by HobDev** [comment]
This issue is on iOS too.

**Comment by ramonB1996** [comment]
This also seems to be a problem on `MacCatalyst`. 

Also the `PointerGestureRecognizer` does not work either. Might be related to all gestures in general for `Span`.
