### ISSUE TITLE
Visual Studio for Mac 2022 17.3 Preview (17.3 build 198) - MAUI Solution and Project Name Mismatch

### ISSUE THREAD

**Issue by mcberena** [dotnet/maui#8008]
### Description

When creating a new project on Visual Studio for Mac 2022 17.3 Preview (17.3 build 198), customizing the project name and solution name does not get processed properly. See the screenshot below for reference.

It seems that the name for the project always gets selected as default solution name.

<img width="447" alt="Screen Shot 2022-06-13 at 8 23 31 PM" src="https://user-images.githubusercontent.com/1165672/173468607-57fa6c59-a544-49e3-9c12-1b8dd1f8b81e.png">
 
<img width="1287" alt="Screen Shot 2022-06-13 at 8 17 28 PM" src="https://user-images.githubusercontent.com/1165672/173468677-d64a83bc-eed9-4536-baca-0ad61b691f25.png">

<img width="703" alt="Screen Shot 2022-06-13 at 8 27 04 PM" src="https://user-images.githubusercontent.com/1165672/173468789-33197206-8403-4718-a2d2-2c67ba736ebd.png">

### Steps to Reproduce

1. Open Visual Studio for Mac 2022 17.3 Preview (17.3 build 198) 
2. Create a new .NET MAUI App
3. Set Project Name: SampleProject.MAUI
4. Set Solution Name: SampleProject
5. Click create
6. Inspect the folder and file structure, the Solution Name is the same as the project name even if the rename action has been performed.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

macOS Monterey

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

**Comment by kristinx0211** [comment]
repro on macOS.
![image](https://user-images.githubusercontent.com/99457000/173481298-5722e800-c9da-46f7-b908-33cda9f8be01.png)
![image](https://user-images.githubusercontent.com/99457000/173481316-e2b0d0b4-f87c-4729-8486-7bf3f1cce19f.png)

**Comment by Eilon** [comment]
I think there's some general problem with the authoring of the templates, as also seen here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1543205/

It seems that in some cases the SLN and/or CSPROJ get an unexpected name, and are also sometimes in an unexpected location.

**Comment by mattleibow** [comment]
I think this issue is now fixed because the IDE team closed the internal issue as fixed. Just going to leave this open to ask if you still see this issue happening?
