### ISSUE TITLE
[Windows] TabbedPage inside Navigation page causes Crash

### ISSUE THREAD

**Issue by NonameMissingNo** [dotnet/maui#8009]
### Description

If you have a TabbedPage inside a NavigationPage, you click around the tabs, press back, and come back into the TabbedPage, it will crash either at launch, or when the other tab is pressed
![image](https://user-images.githubusercontent.com/40233496/173512152-6fdbe7c3-d543-41b2-a99f-0fa0b46ee8e6.png)

Sample project:
[MauiApp10.zip](https://github.com/dotnet/maui/files/8897201/MauiApp10.zip)

### Steps to Reproduce

Create a project.
Create a NavigationPage that opens the MainPage.
Create a TabbedPage with two MainPages inside it.
Redirect the click to the TabbedPage
Click around in the TabbedPage, it's working
Press back, click on the button again
Click the other Tab
Crash

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

**Comment by kristinx0211** [comment]
verified repro on windows with vs 17.3.0 Preview 3.0 [32614.275.main].
![image](https://user-images.githubusercontent.com/99457000/173794990-f724a981-d408-4b74-8634-4eb7a851165e.png)

**Comment by NonameMissingNo** [comment]
No longer crashes with VS 17.4 / .net 7
