### ISSUE TITLE
[Windows] RefreshView and ContentView are not firing commands when using mouse.

### ISSUE THREAD

**Issue by Schinwinkwinsky** [dotnet/maui#8016]
### Description

Hello, everybody

I'm developing a Pokedex app to study DotNET Maui and I'm facing two problems on the Windows app. 

1. The first one is already known and is tracked here: #6152. The RefreshView.PullToRefreshCommand is not being fired.
2. The second one is the CollectionView.RemainingItemsThresholdReachedCommand that is not being fired too.
 
When the app is running on Android device, the RefreshView.PullToRefreshCommand and CollectionView.RemainingItemsThresholdReachedCommand are being fired properly, but on Windows device they don't. 

Maybe the reason is described here: https://github.com/dotnet/maui/issues/6404#issuecomment-1118042039

### Steps to Reproduce

1. Download and run the following project: https://github.com/Schinwinkwinsky/Pokedex
4. Run the project on Android and Windows.
5. On Android it's possible to note that even RefreshView.PullToRefresh and CollectionView.RemainingItemsThresholdReachedCommand works properly, but on Windows they don't.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 19044.1706

**Comment by jfversluis** [comment]
Thanks for the report @Schinwinkwinsky ! Maybe I'm not understanding you correctly, but I don't really see what the issue is? You mention it's about `RemainingItemsThresholdReachedCommand` but what is the behavior that you expect to see and what is the actual behavior?

Would you be able to update your initial post with some more information please?

Thanks!

**Comment by Schinwinkwinsky** [comment]
> Thanks for the report @Schinwinkwinsky ! Maybe I'm not understanding you correctly, but I don't really see what the issue is? You mention it's about `RemainingItemsThresholdReachedCommand` but what is the behavior that you expect to see and what is the actual behavior?
> 
> Would you be able to update your initial post with some more information please?
> 
> Thanks!

Sorry for short descriptions. I'm going to put more details.

**Comment by kristinx0211** [comment]
verified repro on windows with above repro project.

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/6404

**Comment by Schinwinkwinsky** [comment]
Hi, @PureWeen. You closed this issue, but what about the ContentView problem? The issue 6404 just talks about RefreshView.
