### ISSUE TITLE
Visual studio 2022 - 17.2.4 maui:/

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#8027]
### Description

June 14, 2022 — [Visual Studio 2022 version 17.2.4](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.2.4)

hmmm

where are you maui... no maui..

hmmm WHATTTT................

SO MAUI GA just scam or what ?

### Steps to Reproduce

June 14, 2022 — [Visual Studio 2022 version 17.2.4](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.2.4)

hmmm

where are you maui... no maui..

hmmm WHATTTT................

SO MAUI GA just scam or what ?

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

all platform

**Comment by PirasathLuxchumykanthan** [comment]
ok what version does "GA" have i update the studio preview 

it til me 6.0.400

**Comment by PirasathLuxchumykanthan** [comment]
" Now go to the installer, hit modify, and install the .NET Maui workload"  can you explain

> 6.0.400 is the latest, it's fine. Now go to the installer, hit modify, and install the .NET Maui workload

**Comment by PirasathLuxchumykanthan** [comment]
Installed Workload Ids      Installation Source
-----------------------------------------------
maui-windows                VS 17.3.32611.2
maui-maccatalyst            VS 17.3.32611.2
maccatalyst                 VS 17.3.32611.2
maui-ios                    VS 17.3.32611.2
ios                         VS 17.3.32611.2
maui-android                VS 17.3.32611.2
android                     VS 17.3.32611.2
wasm-tools                  VS 17.3.32611.2

**Comment by PirasathLuxchumykanthan** [comment]
i thing u dont understand the point...

the maui team.
- made youtube "maui party" and told that in next relase of visual studio ga will come...


6.0.400 is not "ga"
still old version...


today new release of studio.. but no maui.... so basic maui team didnt keep the word,...

**Comment by AswinPG** [comment]
I also cannot find the maui templates in the latest update (clean install). Also maui workload is not installed

PS C:\Users\aswin> dotnet workload list

Installed Workload Ids      Installation Source
-----------------------------------------------
runtimes-windows            VS 17.3.32611.2
maui-windows                VS 17.3.32611.2
maui-maccatalyst            VS 17.3.32611.2
maccatalyst                 VS 17.3.32611.2
maui-ios                    VS 17.3.32611.2
ios                         VS 17.3.32611.2
maui-android                VS 17.3.32611.2
android                     VS 17.3.32611.2

**Comment by AswinPG** [comment]
PS C:\Users\aswin> dotnet workload install maui `
>>   --from-rollback-file https://aka.ms/dotnet/maui/main.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json `
>>   --source https://api.nuget.org/v3/index.json

Workload installation failed: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (maui.blob.core.windows.net:443))

**Comment by PirasathLuxchumykanthan** [comment]
> PS C:\Users\aswin> dotnet workload install maui `
> 
> > > --from-rollback-file https://aka.ms/dotnet/maui/main.json `--source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json`
> > > --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json `--source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json`
> > > --source https://api.nuget.org/v3/index.json
> 
> Workload installation failed: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (maui.blob.core.windows.net:443))

is not "ga" maui have not release ir, only release in the new version of studio.. the  maui team inform that live in youtube but today is the release.. and there are no maui in that release,, begin to fell like this is the same stuff as what happen to silverlight..

**Comment by jfversluis** [comment]
Please see [this question](https://github.com/dotnet/maui/wiki/faqs#why-do-i-still-need-visual-studio-preview-to-use-net-maui) in the FAQ.

Also, @PirasathLuxchumykanthan, please try to open constructive issues or discussions. Calling us a scam, repeating the same information, etc. is not a part of that.

We did not break any promise, nor is this the next Silverlight. Thanks
