### ISSUE TITLE
iOS Hot Restart feature not working after updating to VS2022 17.3 Preview 2

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#8029]
### Description

After updating to VS2022 17.3 Preview 2, iOS Hot Restart was unable to deploy the app to the connected device.

It previously worked fine a few days back with VS2022 17.3 Preview 1.1

Log attached from VS IDE and it's a fresh project creation.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Connect the Apple device to the machine
3. Set iOS as the build target and select the connected device from the `iOS Local Devices` list
4. Build and deploy the app

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Nope

### Relevant log output

_Have removed the Device name from the log output and the path is shortened with the environment variable._

```shell
Deploy Error: Could not install the application '%LocalAppData%\Temp\Xamarin\HotRestart\Signing\MauiApp5.app\out\MauiApp5.ipa' on the device <Device_Name>. Details: ApplicationVerificationFailed|0xE8008016 - Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.zvVwPI/extracted/Payload/MauiApp5.app : 0xe8008016 (The executable was signed with invalid entitlements.)
Deploy failed. The app 'MauiApp5.app' could not be deployed to the device '<Device_Name>'. Please check the logs for more details.
```

**Comment by egvijayanand** [comment]
Have reported this issue as VS feedback also. 

Since it got logged as a code signing error. Wanted to report here as well.

**Comment by drasticactions** [comment]
This is an IDE tooling issue that can't be fixed here in this repo. Since you have VS Feedback, can you link that here?

**Comment by jfversluis** [comment]
> Wanted to report here as well.

While I appreciate the effort, please don't. The more fragmented information we have, the less likely it is that it will get resolved soon. Additionally, all the time we spend on this issue in this repo is time we cannot spend on building and improving actual .NET MAUI.

It would really help us if you report the issues only in the places where they belong. I get that it's not always clear where the right place is, but in this case you got it right (well done!) then either the issue will be routed here if needed, or they will resolve it there.

For completeness, please add the link here so people stumbling on this issue can go to the right place. Closing this for now.

**Comment by egvijayanand** [comment]
> This is an IDE tooling issue that can't be fixed here in this repo. Since you have VS Feedback, can you link that here?

https://developercommunity.visualstudio.com/t/iOS-Hot-Restart-feature-not-working-afte/10070532

**Comment by egvijayanand** [comment]
> > Wanted to report here as well.
> 
> While I appreciate the effort, please don't. The more fragmented information we have, the less likely it is that it will get resolved soon. Additionally, all the time we spend on this issue in this repo is time we cannot spend on building and improving actual .NET MAUI.
> 
> It would really help us if you report the issues only in the places where they belong. I get that it's not always clear where the right place is, but in this case you got it right (well done!) then either the issue will be routed here if needed, or they will resolve it there.
> 
> For completeness, please add the link here so people stumbling on this issue can go to the right place. Closing this for now.

Have added the VS feedback link to track the issue.

I understand as even I don't prefer reporting it in different places. Just wanted the team to be made aware that one of the most sought-after features is again broken.
