### ISSUE TITLE
Image with different format not working In IOS

### ISSUE THREAD

**Issue by sachincvn** [dotnet/maui#8036]
### Description

.svg .xml Format Images not showing in ios devices

### Steps to Reproduce

1. Added Images of different format in Resources/images (img1.svg, img2.xml)
2. Added image code in xaml :    `<Image Source="img1.svg" />`

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

iOS

### Affected platform versions

IOS

### Did you find any workaround?

Not Yet

**Comment by jfversluis** [comment]
The images are translated to PNGs. Could you try to refer to them as `img1.png` does that resolve the problem?

Also, I see you mention Release Candidate 3, is that correct? If so, what is the reason you're not using the latest version?

**Comment by sachincvn** [comment]
Hi, I am using the latest version of MAUI(Release version). I am using xml/svg for images should I use png or just change extension for the same file.

**Comment by sachincvn** [comment]
Tried 

> The images are translated to PNGs. Could you try to refer to them as `img1.png` does that resolve the problem?
> 
> Also, I see you mention Release Candidate 3, is that correct? If so, what is the reason you're not using the latest version?

I tried writing img1.png for a .svg file and it is working but for .xml files it is the same. Thanks

**Comment by Symbai** [comment]
SVG files will be converted to PNG files on build. Thats why you have to change the file extension in XAML. I've never seen an image being transmitted as XML and I don't believe MAUI supports it at all. Can you perhaps convert them to a more common image format, JPG PNG or SVG?

**Comment by kristinx0211** [comment]
verified set as .png can work on windows, Android And IOS,  .xml file extension is not work currently.

**Comment by sachincvn** [comment]
Thank You, Adding .png in the source is working..
