### ISSUE TITLE
Maps should be independent from the System Maps

### ISSUE THREAD

**Issue by paule96** [dotnet/maui#8037]
In the PR #7886 Maui adds map support. But in this PR it will only refer to the system implementation of the different OSs.

It would be good to give the user the freedom to use the map apps they want to use. For example it can be a blocker, because of political conflicts. (for example Huawei Phones, can't use GMS anymore)

> everything refers to this lines: https://github.com/dotnet/maui/blob/1dc807fa71c6f168731aa30b552c262992ffabb1/src/Controls/samples/Controls.Sample.Sandbox/MauiProgram.cs#L8

On the most huawai apps it's solved by just using the petal maps app.
The question is, if there is a more general approach across maps apps.

P.S.: I open this issue here to don't block the PR. And the referred PR brings value for many users. So this is definitely a feature request.

**Comment by jfversluis** [comment]
Thanks for bringing this to our attention! We currently don't have any plans to do so, and I don't think we will anytime soon.

For the specific implementation of a provider on all platforms there are a couple of plugins. One of them being [MapsUI](https://mapsui.com/) which allows for different tile providers.

PS; can I kindly ask you to use the feature request template next time, thanks?

**Comment by paule96** [comment]
@jfversluis ofc you can. I created this issue over the mobile github website. That website doesn't show the template... So sorry for that. Thanks to point this out.
