### ISSUE TITLE
ANDROID Shell.Current.GoToAsync doesn't work if Shell.PresentationMode="ModalAnimated"

### ISSUE THREAD

**Issue by HausBJB** [dotnet/maui#8038]
### Description

Hello since version sr1 the Shell.Current.GoToAsync function no longer works on Android

Can I fix it somehow or go back to the last version?

repro
https://github.com/HausBJB/MauiApp1/

### Steps to Reproduce

1. use repro
2. Click button GoTo
3. Android not works

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by jfversluis** [comment]
Thanks for the report! You mention only Android, can I assume that you did test this on iOS and/or Windows and it still works as intended there?

Also, small request for next time; the fact that you added a repro is awesome, thanks for that! The reproduction steps are then still also very much appreciated so we know where to click and what to do and mostly: what do you expect to see and what are you actually seeing.

Thanks!

**Comment by HausBJB** [comment]
Hello on Windows and iOS it works.
Unfortunately, I can't say MacOS.

This is understandable if you want as much information as possible.

But you can't go wrong with a project with a button called GoTo.

And now to my question, how do I get back to the last version


It's depressing when it worked before and now there are more bugs that haven't been fixed yet

**Comment by kristinx0211** [comment]
verified repro on android with above project, `Shell.Current.GoToAsync(nameof(MainPage));` does not work on android, can work on windows.

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/8062
