### ISSUE TITLE
Improve BindableLayout.SetItemsSource

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#804]
Hi,

I hope you will have a better way to improve the BindableLayout.SetItemsSource because currently you can bind the data to ListView and any other control using ItemSource but when you try to bind the same data output using BindableLayout.SetItemsSource it work..

There is should be a standard way to do it to avoid changing the code.

Also, when I try the use BindableLayout.SetItemsSource with some controls such as Syncfusion Card it works but not when binding to a Grid.

Please refer to:

[https://docs.microsoft.com/en-us/answers/questions/363302/how-to-bindablelayoutsetitemssource.html](https://docs.microsoft.com/en-us/answers/questions/363302/how-to-bindablelayoutsetitemssource.html)

Thanks,
Jassim

**Comment by GalaxiaGuy** [comment]
What isn't working when you use `BindableLayout` with `Grid`?

Binding the children of `Grid` works the same as `StackLayout`. One thing that makes it less useful is that without setting `Grid.Column` and/or `Grid.Row`, everything will overlap (the same as if you manually add children to a `Grid`).

https://github.com/galaxiaguy/xf-bugs/tree/test/binding-grid

Xamarin Community Toolkit has a `Behavior` that lays out items in a grid in order:

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/ImpliedOrderGridBehavior.shared.cs

**Comment by jrahma** [comment]
Please see the issue in the attached sample

[TestBinadleLayout.zip](https://github.com/dotnet/maui/files/6361582/TestBinadleLayout.zip)

**Comment by GalaxiaGuy** [comment]
In your sample, you don't have a `BindableLayout.ItemTemplate` defined on your grid. This is the element that would be repeated foreach item in the `BindableLayout.ItemsSource`.

You also seem to be trying to show two different elements for each item in the `ItemsSource` (which isn't possible for any `ItemsSource`, whether `BindableLayout` or a `ListView`).

You could get around that converting your source list into a list different elements to be placed in the grid and using a `DataTemplateSelector` to choose a different template for different types.

**Comment by Redth** [comment]
Thanks for the suggestions, there's workarounds here and it's not on our roadmap.
