### ISSUE TITLE
Pointer pressed not received in panel when using scroll view in windows

### ISSUE THREAD

**Issue by BharanikhumarSR** [dotnet/maui#8046]
### Description
I have been developing a custom control using handlers. For windows, I have used panel class for the native view part. So when I placed the control in a scroll view, the pointer pressed in not invoked. Also there is no way to handle the scroll view touch interception. For eg. we have Dispatch event and DisallowInterceptTouchEvent in android
Note: I am receiving the pointer move method correctly.

### Steps to Reproduce

1. Create a sample using Panel as a platform view,
2. Subscribe pointer pressed, moved and released events on the native.
3. Place the custom control as Scroll view children in PCL.
4. Check that pointer pressed is not invoked and no way to handle the scroll view interception.

### Version with bug

MAUI-6.0.400 preview 22301.1(Current version), VS-2022 Preview

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

To get touch view to the control, I have used grid now. But I'm in need to use [LayoutPanel](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/LayoutPanel.cs) where I need to get Hit test when background is null.

**Comment by jfversluis** [comment]
Hello there, thanks for the report! I see you indicate that you do not know the .NET MAUI version? How come? What version of .NET are you using and which Visual Studio?

Also, I think it will greatly speed up the process for this issue if you would attach a reproduction that shows this issue. Thanks!

**Comment by BharanikhumarSR** [comment]
Hi @jfversluis , 
I'm using the current MAUI update which is MAUI-6.0.400 preview 22301.1(Current version) with Visual Studio 2022 Preview.

**Comment by jfversluis** [comment]
Thank you! Would you be able to provide a little reproduction project please?
