### ISSUE TITLE
ContentView OnAppearing and OnDisappearing

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#805]
Hi,

I hope MAUI will provide OnAppearing and OnDisappearing for the ContentView

Thanks,
Jassim

**Comment by PureWeen** [comment]
These are the life cycle events that we plan on providing currently

https://github.com/dotnet/maui/issues/30

OnAttachedHandler and OnDetachedHandler

should give you everything you need at the ContentView level

Calculating if a contentview is visible to the user is very expensive so currently we don't plan on exposing that type of hook.
