### ISSUE TITLE
PushModalAsync on Android not working in latest Visual Studio Update

### ISSUE THREAD

**Issue by Wandtket** [dotnet/maui#8062]
### Description

Navigation.PushModalAsync appears to be broken on Android in the newest version of MAUI in Visual Studio Professional 2022 Preview 17.3.0 Preview 2

### Steps to Reproduce

1. Create a new .Net MAUI Project
2. Create a new MAUI Content Page
3. Create a modal to be opened on startup: Navigation.PushModalAsync(new ContentPage())
4. Run in it in the Android Emulator 

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

net6.0-android minimum 21.0

### Did you find any workaround?

No

### Relevant log output

```shell
System.InvalidOperationException: 'Current Root View cannot be null'
```

### WORKAROUND

```C#
using Microsoft.Maui.Handlers;

namespace MauiApp32;

public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        MainPage = new AppShell();
        WindowHandler.Mapper.ModifyMapping(nameof(IWindow.Content), OnWorkaround);

    }

    private void OnWorkaround(IWindowHandler arg1, IWindow arg2, Action<IElementHandler, IElement> arg3)
    {
        WindowHandler.MapContent(arg1, arg2);
    }
}
```

**Comment by egvijayanand** [comment]
Same issue while using the `Shell.PresentationMode="ModalAnimated"` attached property and navigating to that Page using Shell.

**Comment by dm-pr** [comment]
same issue,  also using ModalAnimated,  worked yesterday, then I updated VS,  cmon... today my app was scheduled to be released to testers...   and now this.. "Lucky" me I checked the app one more time, just in case..... that would have been a disaster to launch and have this bug destroy the presentation

**Comment by egvijayanand** [comment]
It worked. Handler makes life easy.

Just making it simple:

```cs
WindowHandler.Mapper.ModifyMapping(nameof(IWindow.Content), (handler, window, _) => WindowHandler.MapContent(handler, window));
```

**Comment by brianjtools** [comment]
I'm unfamiliar with this WindowHandler thing.  How do you make it work for something like this?

await Navigation.PushModalAsync(new OpenAFile(path));

Surprised this wasn't caught before the update was released because Navigation functions are very commonly used.

**Comment by jhenrich** [comment]
Can confirm that with the latest Visual Studio the navigation with `await Shell.Current.GoToAsync(nameof(LoginPage));` does throw a `Current Root View cannot be null ` Exception when I use the `Shell.PresentationMode="ModalAnimated"`. Removing the presentation mode setting in the xaml file does resolve the issue. Worked for me in the previous version

**Comment by kristinx0211** [comment]
verified repro on  android with vs 17.3.0 Preview 3.0 [32618.28.main], repro project:
[MauiApp14.zip](https://github.com/dotnet/maui/files/8939691/MauiApp14.zip)

**Comment by PureWeen** [comment]
@brianjtools  @jhenrich just copy and paste the code in the workaround into your app.xaml.cs file like it is in the workaround
