### ISSUE TITLE
Entry decoration on Android not correct.

### ISSUE THREAD

**Issue by mobycorp** [dotnet/maui#8067]
### Description

I am developing a form with Entry boxes. I am trying to make sure the UI experience is identical (or as close as possible) between windows and mobile. I get no element decoration in Android. I have had to change my code I've included below somewhat to get a clear demonstration as I am also trying to get the layout inside a frame which, IMHO, has NEVER worked. See my comments on the following issue: **Content inside a Frame layout is not visible. #7139**

Here is the Android layout. Notice no Entry element decoration...

![AndroidFrame](https://user-images.githubusercontent.com/60759137/173864375-7534e1d6-9870-4f3d-a8d2-b6c80ceec345.png)

Here is the same code rendered on Windows:

![WindowsFrame](https://user-images.githubusercontent.com/60759137/173864486-fd28b4c0-755f-4606-bb79-2f6dcde42ffd.png)

There is a faint outline of the control in windows whereas on Android it is completely missing. This will totally confuse a user... I realize this is probably a styling issue, but since you provide Styles.xaml in a new Maui project, I am expecting the controls to behave in similar fashion **ON ALL PLATFORMS** out of the box!

### Steps to Reproduce

1. Create a File -> New for a Maui application.
2. Enter the code provided.
3. Observe......

ViewModel:

```
using CommunityToolkit.Mvvm.ComponentModel;

namespace MauiApp1;

public partial class MainViewModel : ObservableObject {
	public MainViewModel () {
		Terms = "By clicking Agree & Join, you agree to the Moby User Agreement and Privacy Policy.";
	}

	[ObservableProperty]
	public string terms;
	[ObservableProperty]
	private string emailAddress;
	[ObservableProperty]
	private string name;
	[ObservableProperty]
	private string password;
	[ObservableProperty]
	private string passwordConfirmation;
}
```

Xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:MauiApp1"
	x:Class="MauiApp1.MainPage"
	x:DataType="local:MainViewModel"
	Padding="10">
	<Grid>
			<VerticalStackLayout
				MaximumWidthRequest="370"
				Spacing="5">
				<Frame
					Background="{StaticResource MobyBlue}"
					BorderColor="{StaticResource MobyBlue}"
					CornerRadius="8">
					<HorizontalStackLayout
						HorizontalOptions="Center"
						Spacing="3">
						<Image
							Grid.Column="0"
							HeightRequest="36"
							SemanticProperties.Description="Moby application logo"
							Source="moby_logo.png"
							WidthRequest="48" />
						<Label
							Grid.Column="1"
							Margin="10,0,0,0"
							FontFamily="SegoeUiSemibold"
							FontSize="28"
							Text="Moby Sign Up"
							TextColor="White"
							VerticalOptions="Center" />
					</HorizontalStackLayout>
				</Frame>
				<VerticalStackLayout
					HorizontalOptions="Center"
					Margin="0,10,0,0"
					Spacing="3">
					<Label
						Text="Name:" />
					<Entry
						Margin="0,2"
						Placeholder="Enter your name"
						Text="{Binding Name}" />
					<Label
						Text="Email Address:" />
					<Entry
						Margin="0,2"
						Placeholder="Enter your name"
						Text="{Binding Name}" />
					<Label
						Text="Password:" />
					<Entry
						IsPassword="True"
						Margin="0,2"
						Placeholder="Enter your password"
						Text="{Binding Password}" />
					<Label
						Text="Confirm Password:" />
					<Entry
						IsPassword="True"
						Margin="0,2"
						Placeholder="Confirm your password"
						Text="{Binding PasswordConfirmation}" />
					<Label
						FontSize="10"
						HorizontalTextAlignment="Center"
						Margin="10"
						Text="{Binding Terms}" />
					<Button
						Text="Agree &amp; Join" />
					<HorizontalStackLayout
						Margin="0,10,0,0"
						Spacing="5">
						<Label
							Text="Already a Moby member?"
							VerticalTextAlignment="Center" />
						<Button
							Text="Sign In" />
					</HorizontalStackLayout>
				</VerticalStackLayout>
			</VerticalStackLayout>
	</Grid>
</ContentPage>

```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12.0 - API 31 (emulator), Windows (net6.0-windows10.0.19041.0)

### Did you find any workaround?

NO...... :-(

**Comment by kristinx0211** [comment]
@mobycorp could you mind load your repro project because this can  help us to verified this issue faster. thanks.

**Comment by mobycorp** [comment]
Hey @msftbot...

It'll take you longer to pull this repo, set it up, build it and run it than it would have for you to simply create a new Maui app and cut and past the two code snippets from above, but, here it is...

https://github.com/mobycorp/MobyAndroidEntryDecorations.git

**Comment by kristinx0211** [comment]
verified repro on android with above project.
