### ISSUE TITLE
Target platform identifier android not recognized (6.0.400-preview.22301.10)

### ISSUE THREAD

**Issue by dugsteen** [dotnet/maui#8072]
I recently installed Visual Studio 2022 Preview v 17.3.0 - Preview 2.0. Now I can't `dotnet restore` on my (previously working) project files without getting the following error:
```
C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInfere
nce.targets(112,5): error NETSDK1139: The target platform identifier android was not recognized.
```
I tried creating an entirely new MAUI project using the ".NET MAUI App" template and got the same result, as well as the following build error:
```
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android	MauiApp1	C:\Git\Playground\Source\Maui\MauiApp1\MauiApp1.csproj	1	
```
If this isn't immediately fixable, is there a way for me to go back to using version "6.0.400-preview.22259.1" of the dotnet sdk, or will that not work with the new VS2022?

**Comment by erandermsft** [comment]
> If this isn't immediately fixable, is there a way for me to go back to using version "6.0.400-preview.22259.1" of the dotnet sdk, or will that not work with the new VS2022?

You can add a [global.json file](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) in the project root which references 6.0.400-preview.22259.1

**Comment by jfversluis** [comment]
All other issues describing this area seem to have also .NET 7 installed. You probably want to either uninstall that or use a `global.json` file indeed to make sure that your app uses .NET 6 which is needed by .NET MAUI right now.

Also see https://github.com/dotnet/maui/wiki/.NET-7-and-.NET-MAUI
