### ISSUE TITLE
Issue with OnPlatform in Maui

### ISSUE THREAD

**Issue by dmccolloughOneGas** [dotnet/maui#8073]
I'm working on porting a Xamarin Forms Application to Mau
In my App.Xaml in Xamarin Forms I have the following
```
	            <OnPlatform x:Key="CardFrameMargin"
                        x:TypeArguments="Thickness"
                        Android="5,5,5,5"
                        iOS="10,5,10,5" />
```

I've tried adding the above code into the Resources/Styles/Colors.xaml file in a new maui app. When I do I get red squiggles for both Android and iOS. It says the properties are not found in OnPlatform

Later in one of my styles, I reference the above platform extension in my style like below
```
           <Style x:Key="CardFrameStyle"
                   TargetType="Frame">
                <Setter Property="BackgroundColor" Value="White" />
                <Setter Property="CornerRadius" Value="{StaticResource CardFrameCornerRadius}" />
                <Setter Property="HasShadow" Value="True" />
                <Setter Property="Margin" Value="{StaticResource CardFrameMargin}" />
                <Setter Property="Padding" Value="12, 10, 12, 10" />
            </Style>
```

So how do I do this in Maui ?

**Comment by Kalyxt** [comment]
Should be like this, use ' ' instead of double quotes "0,25,0,22".

`<Setter Property="Padding" Value="{OnPlatform iOS='0,25,0,22', Android='0,5,0,5'}"/>`
