### ISSUE TITLE
[Maui]Not able to Debug MAUI apps when using Net6.0 Tizen 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MauiNot-able-to-Debug-MAUI-apps-when-u/10071057)._

---
[severity:It’s more difficult to complete my work]
Hello,

Tizen applications are supported on VS2022 based on the VisualStudio Tools for Tizen vsix
https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen

The debug properties to launch Tizen Emulator is based on IDebugLaunchProvider interface:-
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IDebugLaunchProvider.md

We have come across VS2022 Preview ver 17.3.0 which supports MAUI.

Able to debug the app keeping only net6.0-tizen as TargetFramework even after the deployment error popup which is similar to the one mentioned in the below link:-

https://github.com/dotnet/maui/issues/2493

Starting local deployment...
Deploy: START
DeployAsync: START
Reading package recipe file "C:\Users\jh5.cho\source\repos\MauiApp4\MauiApp4\bin\Debug\net6.0-tizen\tizen-x86\MauiApp4.build.appxrecipe"...
DEP1700: The recipe file "C:\Users\jh5.cho\source\repos\MauiApp4\MauiApp4\bin\Debug\net6.0-tizen\tizen-x86\MauiApp4.build.appxrecipe" does not exist. You may need to build your project.
    DeploymentSucceeded = False
    DeploymentError = Err_Recipe_DoesNotExist
    DeploymentUserError = False
    DeploymentHRESULT = 2147942402
    HasSharedCode = False
    Target.Id = 256
    ProjectGuid = {6ede1560-7c5a-42a9-8e6a-cdc97d06616f}
    Project.TargetPlatformVersion = 7.0
Deleting file "vs.appxrecipe" from layout...
DeployAsync: END (Failure, 0:00:00.103)
Deploy: END (Failure, 0:00:00.171)

Could you help us?
Thanks

---
#### Feedback Bot on 6/15/2022, 01:19 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sangwook96** [comment]
Hello,
I saw https://github.com/dotnet/maui/issues/2493
It was closed and MS team fixed it in their VS.
I think that the current issue is similar to https://github.com/dotnet/maui/issues/2493.
Could you consider it in the Maui app?
Thanks

**Comment by varinderpratap** [comment]
Hello, 
Update: 
In the latest 17.3 Preview 2.0,  we cannot debug tizen apps(net6.0-tizen targetFramework).
In previous preview versions, we could debug the Tizen app by keeping only "net6.0-tizen" as TargetFramework in csproject file.
Now, there is no debug option for "net6.0-tizen" targetFramework apps.
Could we please add a lable "bug" to this issue?
Thanks!
