### ISSUE TITLE
When editing a MAUI csproj, VS auto inserts `AndroidResource` of the item that was changed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8078]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-editing-a-MAUI-csproj-VS-auto-inse/10065356)._

---
[severity:It's more difficult to complete my work]
I'm trying to manually edit the csproj when adding items. Whenever I try to make manual changes, Visual studio automatically inserts whatever I changed as an `AndroidResource`. Previously I was trying to change the `MauIcon` and it kept switching it to Android Resource. I have included a screen grab of trying to remove an ItemGroup and VS re-adding the ItemGroup and adding it as an AndroidResource.

Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.1

---
#### Feedback Bot on 6/8/2022, 07:56 PM: 

(private comment, text removed)
#### svaldetero on 6/9/2022, 11:49 AM: 

(private comment, text removed)
#### svaldetero on 6/9/2022, 00:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by svaldetero** [comment]
> are the errors same with you what you meet with in your environment?

The erroneous `AndroidResource` addition causes android build errors. I'm not sure if it is the same as this but it presents similar results.

**Comment by PureWeen** [comment]
There's a internal ticket for this assigned to @jonathanpeppers FYI
