### ISSUE TITLE
MAUI Referencing .NET Standard 2.0 NUGet package throws System.BadImageFormatException when starting application

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8079]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Referencing-NET-Standard-20-NUGet/10060717)._

---
[severity:I'm unable to use this version]
When adding reference to .NET Standard 2.0 NUGet package from MAUI application VS 2022 Preview throws System.BadImageFormatException at application start.

If I add same dll library via Add -> Project reference -> Browse application starts normally.

---
#### Feedback Bot on 6/2/2022, 01:56 AM: 

(private comment, text removed)
#### Simon Šander on 6/2/2022, 03:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Would you be able to put together a little reproduction project, add that to GitHub and link us the repo so we are sure that we're looking at the right thing? Thanks!
