### ISSUE TITLE
Maui - No Capabilities Shown in Windows Manifest

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8082]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui---No-Capabilities-Shown-in-Windows-/10057508)._

---
I added code to request location permissions for Android. 
 
  `await Permissions.RequestAsync();`
Then went back to running on Windows and then got an error related to Location Capabilities (see additional screenshot)
Opened the Windows Package.appxmanifest to add Location Capabilities, but none were present.

If I remove the request, I can run under Windows, but not Android.

---
#### Feedback Bot on 5/30/2022, 07:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
The tooling for .NET MAUI is still in preview unfortunately at this time. You will have to edit the manifest file manually. Instructions on that can be found [here](https://docs.microsoft.com/uwp/schemas/appxpackage/how-to-specify-capabilities-in-a-package-manifest).

Another way would be to create a separate WinUI project, edit the manifest file there and copy whatever was changed back to your .NET MAUI manifest file.

The tooling should be more complete over the coming previews and GA later this year.
