### ISSUE TITLE
Directory.CreateDirectory does not work in Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 1.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8089]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DirectoryCreateDirectory-does-not-work-/10047974)._

---
\[severity:I’m unable to use this version\] \[regression\] \[worked-in:Preview Version 17.3.0 Preview 1.0\]  
I am running code that runs correctly in Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.2.0. Since I am creating a MAUI app, I need to run it in VS Preview. These statements run and do no throw any exceptions in the Preview release (in fact, the DirectoryInfo object returned by the CreateDirectory call has the correct folder I am trying to create), yet no folders are created.

```  
	_ = Directory.CreateDirectory (@"C:\Users\cimfr\AppData\Roaming\Moby");
	_ = Directory.CreateDirectory (@"C:\Users\cimfr\AppData\Roaming\Moby\Logs");
	_ = Directory.CreateDirectory (@"C:\Users\cimfr\AppData\Roaming\Moby\Setup");
   
```

They work in the current release but not the preview release. What is troubling is that the call:

`var exists = Directory.Exists (@“C:\\Users\\cimfr\\AppData\\Roaming\\Moby”);`

returns true even when the folder does not exists.

I even tried to use NuGet and get the latest version of `System.IO`, but that didn’t do anything… I also saw some post that said place a trailing “\\” at the end of the folder name, but that didn’t do anything either (as I wouldn’t have thought anyway…)

The version of System.IO.dll is 6.0.522.21309

---
#### Feedback Bot on 5/19/2022, 11:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Please try to create a project that does not use .NET MAUI. If the issue then still persists, I think you'll want to report it on the .NET runtime repo. If it actually only happens with a .NET MAUI app, which I kind of doubt, please open an issue here with all the relevant details and ideally a reproduction project that shows the issue. Thanks!
