### ISSUE TITLE
Visual Studio 2022 17.0.3 Preview 1.0 change color icons in Maui to black.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8092]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-1703-Preview-10-ch/10041517)._

---
Visual Studio 2022 17.0.3 Preview 1.0 change color icons in Maui to black. This happend on ImageButtons.

---
#### Feedback Bot on 5/13/2022, 02:03 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 5/17/2022, 01:42 AM: 

(private comment, text removed)
#### Fernando Junior on 5/19/2022, 06:02 AM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 5/23/2022, 08:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PirasathLuxchumykanthan** [comment]
Hmm strange not happen for me

**Comment by jfversluis** [comment]
New versions have come out since this was reported. Please retry with the latest version, if this is still an issue, open a new issue on the repository will all the requested details, thanks!
