### ISSUE TITLE
MSB4018 The "GenerateShims" task failed unexpectedly on MauiCheck

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8094]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MSB4018-The-GenerateShims-task-failed-/10061729)._

---
[severity:I'm unable to use this version]
Running VS2022 64-bit, version 17.2.3 on Windows 11, 21H2, 22000.675.

Trying to compile Maui-Check (https://github.com/Redth/dotnet-maui-check), downloaded a couple of days ago.

Consistently got MSB4018, The "GenerateShims" task failed unexpectedly

---
#### Feedback Bot on 6/5/2022, 07:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Please report any issues you have with the `maui-check` tool on their repo: https://github.com/Redth/dotnet-maui-check
