### ISSUE TITLE
Adorner layer does not display anything for MAUI+WinUI

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#8096]
### Description

Adorner layer does not display anything for MAUI+WinUI. This affect XAML Hot Reload experience in a significant way.

### Steps to Reproduce

1. Create new MAUI app in VS.
2. Build and F5 on Windows (a.k.a. WInUI)
3. Turn on Element Selection (either using in-app toolbar or XLP toolbar).
4. Try select element in running app on in XLP window.
Actual: no element highlighting; neither in app not in XLP (XLP still shows tooltips)
Expected: element highlighting in both app and XLP

![image](https://user-images.githubusercontent.com/48451158/173942662-b81dc683-2cee-4d2a-9f00-c14dfc98e751.png)

![image](https://user-images.githubusercontent.com/48451158/173942594-1178b9d7-27b8-4de9-a1c5-d208786bccc7.png)

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

Windows

### Affected platform versions

Win 10

**Comment by drasticactions** [comment]
@mattleibow I think there's an issue with _any_ drawn control with WinUI and MAUI. Debugging the IWindowOverlay graphicsview for WinUI, we are calling invalidate on https://github.com/dotnet/Microsoft.Maui.Graphics/blob/main/src/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop/W2DGraphicsView.cs, but it's not being invalidated, so nothing is drawn.

**Comment by mattleibow** [comment]
Fixed in #8428and currently being inserted into VS.
