### ISSUE TITLE
Windows app maximum 

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#8100]
### Description

Well i made the the titlebar black 

and then want to test it

seems there are bug..

i dont know what that bug is.. or named.. but i made a print screen.

tag by under the tilebar canvas why that line gray.

![error-30114](https://user-images.githubusercontent.com/100127577/174031459-f0e27048-de02-47af-b940-ba4691e23bc0.png)

### Steps to Reproduce

Create maui blazor
Change the title
make blazor app black.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows 11

**Comment by jfversluis** [comment]
Can't reproduce it on the current main branch it seems. Please wait until we release the next version which is planned [around June 22nd](https://github.com/dotnet/maui/milestone/21). If it's still an issue then, please let us know.

![image](https://user-images.githubusercontent.com/939291/174078652-c4d202cc-98b6-4c30-a86f-1f4009fbbcd9.png)

**Comment by PirasathLuxchumykanthan** [comment]
Why did u close it
