### ISSUE TITLE
Grid with HeightRequest=0 no longer hides child elements

### ISSUE THREAD

**Issue by AmazingSully** [dotnet/maui#8105]
### Description

Previously in Xamarin if a Grid had a HeightRequest of 0 the child elements would not be displayed. Alternatively if you had a grid with a HeightRequest smaller than the height of the elements it contained they would be cut off. This is no longer the case and now the child elements are displayed regardless of the HeightRequest of the parent Grid, however this can cause elements to overlap.

### Steps to Reproduce

1. Debug project here: https://github.com/AmazingSully/HeightRequestBugExample

Notice the child elements (the Name, Reference, TownCity, PostCode buttons) are visible, but being overlapped by another button. Expected behaviour would be to have the buttons not be visible, then when the entry field is focused for the buttons to animate into view.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

 iOS15, Android 11

### Did you find any workaround?

Setting IsVisible="False" to all of the child elements and then when triggering the HeightRequest change to set IsVisible="True" will work as a workaround.

**Comment by kristinx0211** [comment]
verified repro on android 12 and IOS using 17.3.0 Preview 3.0 [32616.205.main].

**Comment by hartez** [comment]
@AmazingSully What happens if you set IsClippedToBounds to `true` for the Grid?

**Comment by AmazingSully** [comment]
@hartez that does indeed cause the grid to act correctly.
