### ISSUE TITLE
How to select Maui version

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/maui#8109]
### Description

Since the SR1 broke some important things, I'm trying to rollback to the GA, but I'm not sure how to. I tried using RuntimeVersion and the global.json file settings the sdk to 6.0.300 but nothing seems to work. I'm not even sure if this is the right place to ask this question but I can't find anything in the docs regarding this topic that is really important in a UI framework

### Steps to Reproduce

None

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 12

**Comment by jfversluis** [comment]
#8066 has some instructions on how to do it. The next version should be out around June 22 as indicated by our milestones. Sorry about the inconvience!
