### ISSUE TITLE
Shell.Set Presentation Mode bug - Android 

### ISSUE THREAD

**Issue by KarlSearl** [dotnet/maui#8110]
### Description

Unable to navigate to Modal Pages on Android. 

Tested on Windows and this works as expected. 

IMPORTANT NOTE - Issue is resolved when removing the Shell.PresentationMode="Modal" 

### Steps to Reproduce

1. Create a brand new Maui project.
2. Add a second page and set presentation mode to modal.
3. Register route.
4. Add a button and set the clicked event to   Shell.Current.GoToAsync

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 11 API 30

### Did you find any workaround?

Not yet.

**Comment by dm-pr** [comment]
@KarlSearl repo not found, 404

**Comment by KarlSearl** [comment]
> 

Sorry, repo set to public.

**Comment by jfversluis** [comment]
Duplicate of #8062
