### ISSUE TITLE
ScrollView does not scrollable to the End after window height resized.

### ISSUE THREAD

**Issue by KarthikRajaKalaimani** [dotnet/maui#8113]
### Description

ScrollView does not scrollable to the End after window height resized.

Sample link : 
[ScrollViewIssue.zip](https://github.com/dotnet/maui/files/8919432/ScrollViewIssue.zip)

### Steps to Reproduce

i) Run the attached sample in Windows. 
ii) Scroll to see the Label13. 
iii) Note when Stop the scrolling it goes to Label 12 not to Label13. 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

IOS 15, Android 11, Windows

### Did you find any workaround?

Same code snippets working in Xamarin forms.

**Comment by kristinx0211** [comment]
verified repro on windows after resized. Label 13 disappear.
![image](https://user-images.githubusercontent.com/99457000/174218730-a9c0172a-7c60-4d84-aebe-015c3bc6b6b4.png)

**Comment by KarthikRajaKalaimani** [comment]
HI @jfversluis , 

Any update on this ? 

regards,
Karthik Raja

**Comment by jfversluis** [comment]
Issue is reproduced and verified, we'll start working on it, thanks!

**Comment by KarthikRajaKalaimani** [comment]
Hi @jfversluis , 

Any update on this ?

**Comment by jfversluis** [comment]
There is no need to keep asking for updates, when there is something we'll either mention it or you will see a PR being associated to this. Thanks.

**Comment by KarthikRajaKalaimani** [comment]
any update on this ?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on Windows platform with above code.
[ScrollViewIssue.zip](https://github.com/dotnet/maui/files/11473509/ScrollViewIssue.zip)
![Screenshot 2023-05-15 093743](https://github.com/dotnet/maui/assets/77434865/b761bc50-9fff-4ad0-a844-d36689d8bcbb)
