### ISSUE TITLE
Navigation.PushAsync(); on windows platform throws exception: Catastrophic failure (0x8000FFFF (E_UNEXPECTED)) with same page instance

### ISSUE THREAD

**Issue by mfe-** [dotnet/maui#8123]
### Description

Navigation.PushAsync(); throws exception: Catastrophic failure (0x8000FFFF (E_UNEXPECTED)) on the windows platform if a singleton instance of the page is provided. Cannot reproduced on android.

The issue still exists see #3931

### Steps to Reproduce

Repo Steps: https://github.com/mfe-/MauiApp1-Noinstalledcomponentsweredetected

1. create a new dotnet maui project with visual studio 2022
2. add a second contentpage (in this repo the name of the second contentpage is `NewGamePage.xaml`
3. In `App.xaml.cs` replace `MainPage = new MainPage()` with `MainPage = new NavigationPage(new MainPage());`
4. In `MainPage.xaml.cs` replace the content of `OnCounterClicked` with

```csharp
        public static Page page;
        private void OnCounterClicked(object sender, EventArgs e)
        {
            try
            {
                count++;
                CounterLabel.Text = $"Current count: {count}";
                SemanticScreenReader.Announce(CounterLabel.Text);
                if (App.Current.MainPage is NavigationPage navigationPage)
                {
                    if (MainPage.page == null)
                    {
                        MainPage.page = new NewGamePage();
                    }
                    navigationPage.CurrentPage.Navigation.PushAsync(MainPage.page);
                }
            }
            catch(Exception ex)
            {
                System.Console.WriteLine(ex);
            }

        }
```
5. build and run the app on the windows platform
6. click on button `click me`
7. click left arrow back button
8. click again on `click me`
9. `App.g.i.cs` throws 
10. `exception: Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled.`

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041

### Did you find any workaround?

If you use `navigationPage.CurrentPage.Navigation.PushAsync(new NewGamePage())` you won't run into the issue so it looks like it can't handle PushAsync with the same instance.

**Comment by PureWeen** [comment]
@mfe- this isn't really a supported scenario. If it works on Android that's just out of luck. 

The fix here would probably be to throw an exception on Android so all the platforms react the same way with a better error message

**Comment by mfe-** [comment]
@PureWeen I used to register my `Page`s as singleton in my previous UWP apps. This worked on the uwp platform, so I'm wondering why this is not a supported scenario.

**Comment by Keflon** [comment]
@PureWeen - Hello :) I too register my pages as singletons.

I do this for good reason - creating pages can be expensive, and if they are properly decoupled from their data they are fully reusable simply by replacing their BindingContext (or just leaving it be, depending).

I have used this approach in a number of commercial Xamarin.Forms applications without any problem.
Sample application here showing singleton page registration: https://github.com/Keflon/MvvmZeroTutorialApp#locatorcs please refer to `Locator.cs`

For clarity:
- I __don't__ expect to ever have the same page-instance in a navigation-stack multiple times.
- I __do__ expect to be able to push a page instance, pop it, then re-push the same page instance.

I'm hoping your '_... this isn't really supported ..._' refers to the former, not the latter! :)

I have ported the above MvvmZero library to MAUI and I'm waiting on this problem being fixed before publishing. 
I've made a bug reporting the same problem here: https://github.com/dotnet/maui/issues/7698.

**Comment by PureWeen** [comment]
@mfe- From the code I was thinking you were pushing the same instance onto the stack multiple times. 

If what @Keflon outlines here is true

> - I don't expect to ever have the same page-instance in a navigation-stack multiple times.
> - I do expect to be able to push a page instance, pop it, then re-push the same page instance.

Then yes that's a supported scenario and should be fixed :-)
