### ISSUE TITLE
[WinUI] Error deploying Sample.SingleProject in MainPage.xaml, "A cycle occurred while laying out the GUI."

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#8126]
### Description

If you launch the Maui Sample with the current main (as of https://github.com/dotnet/maui/commit/4d36514b656fed60e495ba1f83a34b4dbb4697d6) the Sample.SingleProject app will throw an exception when running on WinUI when the app starts. I believe this is due to some change in ScrollView

![MicrosoftTeams-image](https://user-images.githubusercontent.com/898335/174170587-108415f0-e709-4371-a57d-0e25b134fa1b.png)

If I remove this Grid, the app loads fine. If I remove the ScollView and put the original Xaml back, it also loads fine. But with both, it blows up on a cycle error.

### Steps to Reproduce

Deploy the Sample.SingleProject app from Main (https://github.com/dotnet/maui/commit/4d36514b656fed60e495ba1f83a34b4dbb4697d6)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

**Comment by PureWeen** [comment]
![image](https://user-images.githubusercontent.com/5375137/174171099-1f1a35ca-96e4-433a-b104-cb8747ec1e9b.png)

**Comment by Eilon** [comment]
I'm hitting this in `main` as well.
