### ISSUE TITLE
MacOS And Windows frame error

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#8138]
### Description

Well i see 2 things.

Mac.:
Run the app in mac whit M1 processer brand new mac,
After 30 minuttes the content inside app was hiden i dont know why..
Strange 
![Screenshot 2022-06-17 at 15 48 15](https://user-images.githubusercontent.com/100127577/174311840-2b49fbdb-d392-47c3-98d9-1a16c38c35c1.png)

Windows.:
Well after maximum the frame there was a gray line.. i dont know what and where that come from
![error-30114](https://user-images.githubusercontent.com/100127577/174312028-ac7383d8-be22-4f95-b15b-60d7dd6a8db7.png)

Plz the person who help og read this dont write something crazy or close it.. whit out do it right.

### Steps to Reproduce

 Simpel project 
 
 
github,

https://github.com/PirasathLuxchumykanthan/IHOS

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

Windows 11 and  mac os

**Comment by PirasathLuxchumykanthan** [comment]
I fix the windows path.. but not the mac path

**Comment by PirasathLuxchumykanthan** [comment]
Not to be bad person..

but soon im going to relase the app..
for windows ios android and mac,,

but im affraid to release on mac.. i just like to know if this issue going to be fix ?

btw.. all good when you open it on mac.,,

but after no touch or move of mouse.. 20 minuttes it remove the content.. and only show scroll bar total blank.. really stranges..

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Not repro on Windows platform with sample project.
https://github.com/PirasathLuxchumykanthan/IHOS
![image](https://github.com/dotnet/maui/assets/82450723/03e9da3e-088f-4861-b64a-14e6f5a4387a)
