### ISSUE TITLE
[Android] Resetting App.Current.MainPage doesn't show the new page. 

### ISSUE THREAD

**Issue by pravin271** [dotnet/maui#8141]
### Description

My App have a navigation page (with the home as a root) as a startup page of the app. From there, upon action, the app shows a tabbed page which is set directly as the Main Page of the app class (I read in a few blog posts that putting a tabbed page inside a navigation page is not a good idea). When the user clicks a button on one of the tab pages, the app tries to the shows home page again by setting a navigation page (with the home as a root) as the main page of the app. But this time, the UI goes blank. Nothing is displayed.

### Steps to Reproduce

Please run the sample project from this [github](https://github.com/pravin271/MauiIssue1) repo and press back from the tabbed page.

 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No workaround found yet.

**Comment by pravin271** [comment]
I think this happens only when we use the navigation page.

**Comment by PureWeen** [comment]
[duplicate](https://github.com/dotnet/maui/issues/7153)
