### ISSUE TITLE
Set dark icons for lightTheme

### ISSUE THREAD

**Issue by romanov** [dotnet/maui#8143]
### Description

Hello,

i'm unable to set the following:

`<item name="android:windowLightStatusBar">true</item>`

to get dark icons in statusbar. 

Any backround colors does not change the icons color.

![image](https://user-images.githubusercontent.com/644179/174403825-4f0d5fa6-3a50-4e31-83bf-400760225953.png)

### Public API Changes

Subj.

### Intended Use-Case

Sometimes, you want to show icons instead of the white statusbar.

**Comment by jfversluis** [comment]
Don’t think this is a proposal and I’m pretty sure you’re able to make this work but you’ll need some platform code. Have a look at this Effect in the Xamarin Community Toolkit for inspiration: https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/StatusBar
