### ISSUE TITLE
Web Development

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/maui#8144]
### Description

I started looking at .net maui, because I wanted to do web development with xaml.
Then I realized .net maui does not have that capability. Is this always going to be the case
or will .net maui bring xaml to the web?

### Public API Changes

none

### Intended Use-Case

To be able to use xaml for web development like I used to with silverlight

**Comment by PirasathLuxchumykanthan** [comment]
why you want to use xaml to web development ?

Well there are templeted for .net maui blazor pretty cool

**Comment by jfversluis** [comment]
Duplicate of #4528
