### ISSUE TITLE
DeviceDisplay.Current.KeepScreenOn = true isn't working

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#8145]
### Description

I searched how to prevent the screen from locking. I found the [documentation](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device/display?tabs=android#keep-the-screen-on) saying all I have to do is to write `DeviceDisplay.Current.KeepScreenOn = true;`. I did that but the screen still locks after several seconds in idle.

When searching for more information I found some posts saying I have to add `WAKE_LOCK` permission on Android for example. Or in xamarin I would have to add code in `MainActivity.cs` `oncreate()` method. But the MAUI documentation doesn't mention any of this.

Is it really enough to just write `DeviceDisplay.Current.KeepScreenOn = true;` ? If so then it's a bug because it doesn't work. if its not enough then the documentation is incorrect and I would lik to know what's missing.

### Steps to Reproduce

1. Create new MAUI app
2. In MainPage `ctor` add `DeviceDisplay.Current.KeepScreenOn = true;`
3. Stay idle until the screen lock is supposed to the lock the screen. Confirm that it locks the screen but it should not.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by jfversluis** [comment]
Did it actually work after you added that permission?

**Comment by Symbai** [comment]
No, that's the very first thing I've tried because it was easy to do. In `AndroidManifest.xml` I've added this line `<uses-permission android:name="android.permission.WAKE_LOCK" />`. I didn't tried the Xamarin stuff, because the namespace Xamarin does not exist in Maui and I don't know how to write that code in Maui (if I even have to, again its not documented anywhere).

**Comment by Symbai** [comment]
That's not the same issue. I dont get a NRE. Please create a new issue for this.

**Comment by mjphillips1981** [comment]
I thought I was having the same issue here.  I was originally trying to put the DeviceDisplay.Current.KeepScreenOn = true; In the code behind of the xaml.  But I move it to my viewmodel and now it seems to work.

**Comment by hartez** [comment]
> In the code behind of the xaml. But I move it to my viewmodel and now it seems to work.

I bet this is a timing issue. The actual implementation of KeepScreenOn in Android depends on setting WindowManagerFlags on the current Activity's Window; if `KeepScreenOn = true` is called in the cross-platform application before the Window is actually available, then it won't do anything. 

Which would explain why it didn't work for mjphillips1981 in the codebehind (if the code was in the constructor), but did work in the view model (if that code was executed later on in the app lifecycle). 

@Symbai if you set `KeepScreenOn = true` in the handler for your main page's `Appearing` event, does it work then?

**Comment by Symbai** [comment]
@hartez That did the trick, thank you. I suggest you leave a note in the documentation https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/display?tabs=windows#keep-the-screen-on
