### ISSUE TITLE
FlyoutHeader hangs ios application on startup

### ISSUE THREAD

**Issue by BaldeGH** [dotnet/maui#8146]
### Description

Adding a Layout inside of the Shell.FlyoutHeader is causing the application to hang/crash on ios simulator and device

[Repo](https://github.com/BaldeGH/MauiFlyoutBug)

![image](https://user-images.githubusercontent.com/8539709/174417242-5957d51e-bc27-437d-8771-8d2f0121e868.png)

### Steps to Reproduce

1. Create a new maui program
2. Add LayoutControl to AppShell.xaml's Shell.FlyoutHeader
3. Build & Deploy

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

Remove the VerticalStackLayout and only allow a single item in the flyout

**Comment by lnaie** [comment]
I have this header in the AppShell.xaml, just before a <Shell.FlyoutFooterTemplate>:
```
    <Shell.FlyoutHeaderTemplate>
        <DataTemplate>
            <Grid HeightRequest="150">
                <Image 
                    Aspect="AspectFill" 
                    Source="flyout_logo.jpg" 
                    Opacity="0.9" />
            </Grid>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>
```
It used to work just before the latest update for iOS. The app gets stuck on the loading screen with .net logo.

I commented it out and now the app goes past the loading screen, but -- yeah, it has some another issue, that I have yet to identify here in github. It's not getting better yet with these new builds.

**Comment by AidarNurmukhametov** [comment]
Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue in the our demo application. This issue has a High priority for us and we do not have a workaround. Thank you for your help!

**Comment by kristinx0211** [comment]
verified repro on IOS with above project.

**Comment by lnaie** [comment]
This is a disaster. Not gonna use that feature anymore with this kind of testing quality.

**Comment by pierre01** [comment]
I have the same issue when I set the **Icon** property in a **ShellContent** element in IOS

**Comment by svaldetero** [comment]
@PureWeen marked this as service release 3. Release notes from https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#summary-of-whats-new-in-this-release-of-visual-studio-2022-version-173-preview-4 just says ".NET MAUI Servicing Updates". Which service release was included in that update? Was this item included? Anywhere someone can tie a VS Update number to a MAUI Milestone so we know when our issue is fixed?

**Comment by pierre01** [comment]
I have not seen this issue with 6.0.419 anymore.

**Comment by PureWeen** [comment]
@svaldetero it should be resolved with the latest public preview release
