### ISSUE TITLE
Resolving an x:Reference in a RELEASE build picks the wrong element in some cases.

### ISSUE THREAD

**Issue by Keflon** [dotnet/maui#8149]
### Repro project
https://github.com/Keflon/MauiNameBug

### In a RELEASE build
Bindings to `x:Name="Self"` in a DataTemplate incorrectly resolve to child-controls if a child control also has `x:Name="Self"`
### Steps to Reproduce

1. Create a File->New MAUI app
1. Create a xaml 'child' `ContentControl` whose root element has `x:Name="Self"`
1. Create a xaml 'Parent' `ContentControl` whose root element also has `x:Name="Self"`
    1. Add a `CollectionView`
    1. Add a `DataTemplate` to the `CollectionView` that instantiates the 'child' `ContentControl`
    1. Databind something in the `DataTemplate` to `x:Reference Self`
 1. Add the 'Parent' control to MainPage.xaml and populate the Parent `CollectionView` with some items.

In a **DEBUG** build, the `Binding` correctly resolves to an instance of the 'Parent' control  
In a **RELEASE** build, the `Binding` incorrectly resolves to an instance of the 'Child' control  

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Latest

### Did you find any workaround?

If you give elements an `x:Name`, make them unique, including any names in 3rd-party controls.

**Comment by StephaneDelcroix** [comment]
probably a namescoping issue
