### ISSUE TITLE
Button is not disabled at start when BindCommad(...) is used after Bind(IsEnambledProperty,...)

### ISSUE THREAD

**Issue by ruko1981** [dotnet/maui#8152]
### Description

Reproduction project can be found [here](https://github.com/ruko1981/Button_IsEnabled_Issue).

When using C# markup for views; A button who's IsEnabled property is bound [and set to false] before a command is bound will not me disabled ate startup.

### Steps to Reproduce

1. Create a new .Net Maui App
2. Add CommunityToolkit.MVVM and CommunityToolkit.Maui.Markup NuGet Package
3. Delete MainPage.xaml
4. Rename MainPage.xaml.cs to MainPage.cs
5. Edit Mainpage.cs as follows

```csharp
using CommunityToolkit.Maui.Markup;

namespace MauiApp1;

public class MainPage : ContentPage
{
   public MainPage(MainPageViewModel vm)
   {
      BindingContext = vm;

      Content = new ScrollView
      {
         Content = new VerticalStackLayout
         {
            Children =
            {
               new Button
               {
                  Text = "Toggle ther button enabled"
               }
               .BindCommand(nameof(vm.ButtonClickedCommand)),

               new Button ()
               .Bind(Button.TextProperty, nameof(vm.ButtonText))
               .Bind(Button.IsEnabledProperty, nameof(vm.ButtonEnabled))
               .BindCommand(nameof(vm.DisplayAlertCommand)),
            }
         }
      };
   }
}
```

6. Add MainPageViewModel.cs as follows

```csharp
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace MauiApp1;

public partial class MainPageViewModel : ObservableObject
{
   [ObservableProperty]
   private bool _buttonEnabled = false;

   [ObservableProperty]
   private string _buttonText = "Disabled";

   [RelayCommand]
   private void OnButtonClicked()
   {
      ButtonEnabled = !ButtonEnabled;
      ButtonText = ButtonEnabled ? "Enabled" : "Diabled";
   }

   [RelayCommand]
   private async void DisplayAlert()
   {
      await Application.Current.MainPage.DisplayAlert("", "Other Button Clicked", "OK");
   }
}
```

7. Add the following to MauiProgram.cs

```csharp
builder.UseMauiCommunityToolkit().UseMauiCommunityToolkitMarkup();

builder.Services.AddSingleton<MainPage, MainPage>();
builder.Services.AddSingleton<MainPageViewModel, MainPageViewModel>();
```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android API 30 & 31

### Did you find any workaround?

Using `.BindCommand(nameof(vm.DisplayAlertCommand))` before ` .Bind(Button.IsEnabledProperty, nameof(vm.ButtonEnabled))` allows the button to work as intended.

working example
```csharp
new Button()
.BindCommand(nameof(vm.DisplayAlertCommand))
.Bind(Button.TextProperty, nameof(vm.ButtonText))
.Bind(Button.IsEnabledProperty, nameof(vm.ButtonEnabled))
```

vs not broken example
```csharp
new Button ()
.Bind(Button.TextProperty, nameof(vm.ButtonText))
.Bind(Button.IsEnabledProperty, nameof(vm.ButtonEnabled))
.BindCommand(nameof(vm.DisplayAlertCommand))
```

**Comment by d-flood** [comment]
I've experienced this same issue. The difference is that I am using XAML and the placement of the `Command` and `IsEnabled` attributes did not make any difference. If the `Command` attribute is present on a button, then the `IsEnabled` attribute is ignored and button is always enabled.

**Comment by Symbai** [comment]
If you bind `Command` then `IsEnabled` depends on the `CanExecute` state of your command. In your workaround, you just override this. In XAML it depends on how the xaml reader is parsing the text. So that does not appear as a bug to me, rather than its by-design.

Why don't you just, instead of binding `IsEnabled`, put the logic in your `CanExecute` state of your command just like it was designed for?

**Comment by StephaneDelcroix** [comment]
If you set, or bind, the button command, it will indeed, by design, override IsEnabled, as ICommand.CanExecute takes care of this already.
If you want to provide your own logic for IsEnabled outside of ICommand, define your binding after the other one
