### ISSUE TITLE
Shell Margin Exception

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8160]
### Description

The content of Shell navigation will go directly out of scope on Windows platform without setting any margins

![1](https://user-images.githubusercontent.com/42528522/174477721-d35975bf-d3e0-4b42-a6f7-839b5e95ffe2.png)

For the Android platform, some seem to work fine
![2](https://user-images.githubusercontent.com/42528522/174477747-d557426e-3e36-4be2-b8fd-fa91b83a8ce3.jpg)

### Steps to Reproduce

Navigate with the Shell

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

**Comment by kristinx0211** [comment]
@HenJigg Would you be able to add a little reproduction project that shows this?
