### ISSUE TITLE
Shell doesn't trigger OnAppearing on Second Page

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#8164]
### Description

MAUI with shell doesn't trigger OnAppearing event for second Content Page 

Shell
```
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <Tab>
            <ShellContent 
                Title="whats app"  
                Icon="{StaticResource Phone}"
                ContentTemplate="{DataTemplate views:NewCallPage}" />

            <ShellContent 
                Title="historic" 
                Icon="{StaticResource Person}"
                ContentTemplate="{DataTemplate views:CallHistoryPage}" />
        </Tab>
    </FlyoutItem>
```

Content Page
```
      protected override void OnAppearing()
          {
              base.OnAppearing();
          }
```

https://user-images.githubusercontent.com/68563526/174492169-817c4f30-74f5-49fa-b4fb-90b43ea7186f.mp4

### Steps to Reproduce

1. Create a new MAUI Project
2. Add two content pages;
3. Add Shell;
4. Insert FlyoutItem On shell
5. Insert Tab on FlyoutItem 
6. Insert two ShellContent into Tab 
7. Insert ContentPages into ShellContents
8. Run
9. Click on second Tab, and debug OnAppearing
10. OnAppearing doesn't hit

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### **NOT** Affected platform versions

Windows 11

**Comment by kristinx0211** [comment]
verified repro on android, doesn't trigger `OnAppearing `event for second Content Page. repro project:
[MauiApp2.zip](https://github.com/dotnet/maui/files/8945078/MauiApp2.zip)

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/8102
