### ISSUE TITLE
Newly Introduced System.AccessViolationException

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#8168]
### Description

An app which was working fine in earlier MAUI releases has started to fail with: 
    _**System.AccessViolationException**: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'_

The same code worked fine in earlier MAUI releases but so far I can't find a simplified test case.  The exception showed up in an assignment to Application.Current.Resources["MealViewModel"] which is a valid key, sometimes it shows up the first time an assignment is done in code (it's initialized in XAML), sometimes the second, which makes me suspect it is not this code that is causing the problem, just what's detecting it.

### Steps to Reproduce

I can reproduce it, but not in a simple test case so if there's extra debugging info you'd like, I can probably generate it.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
> I can reproduce it, but not in a simple test case so if there's extra debugging info you'd like, I can probably generate it.

Yes please, because without it this will be pretty hard to diagnose.

**Comment by MagicAndre1981** [comment]
maybe #7585 is related?

**Comment by otium99** [comment]
I have the same error, since I upgraded to Version 17.3.0 Preview 2.0

I occurs here:
![AccessViolationException](https://user-images.githubusercontent.com/67344857/174883171-707407b4-9719-49ed-a79d-35f68969bafa.jpg)

File location: obj\Debug\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs 

And the trigger is the Thread.Sleep(). I could isolate it. As soon as I step over this line in the debugger, the app crashes with the error. If I exclude this line, the app works fine.

```
public MainPageViewModel(OnesieService onesieService)
        {
            this.onesieService = onesieService;

            LoadActivityEntities();

            Thread t = new(BackgroundTask);
            t.Start();
        }

        public async void BackgroundTask()
        {
            if (!IsBusy)
                await ExecuteBackgroundProcess();

            // Keep alive
            Thread.Sleep(5000);
            BackgroundTask();
        }
```

**Comment by david-maw** [comment]
Thanks @otium99 can you reproduce it in a simple test case? I have been unable to so far but I probably was not reproducing the relevant construct.

**Comment by david-maw** [comment]
Thanks @otium99 it failed for me too, I'm relieved it wasn't trivial to reproduce since my attempts at a repro failed miserably. 

@jfversluis there's a reproducible test case available in Github now which hopefully will make diagnosing the problem a bit easier. I'll add that my app also is multi-threaded and makes use of async/await as well so I suspect they may play a role here.

**Comment by musmuris** [comment]
I got this fairly simply by creating a new MAUI Blazor app and doing the stuff in https://github.com/dotnet/maui/issues/3166 and turned off targeting iOS and Android in the project settings

Visual Studio 2022 17.3.0 Preview 2

 * My machine looks to have developer mode locked down by group policy so I cannot enable it. I changed the launch settings to `"command name": "Project"` and added `<WindowsPackageType>None</WindowsPackageType>` to the .csproj. 
 * Then disabled Target the iOS platform and Target the Android Platform

**Comment by musmuris** [comment]
@david-maw Another example of the error here: https://github.com/musmuris/MauiBlazorAccessViolation

**Comment by david-maw** [comment]
@musmuris I think the access violation is a symptom of multiple problems - the one in issue #3166 seems to predate this problem which (for me at least) is new since 6.0.300 (that release ran the same code that failed on 6.0.400 without error).

**Comment by musmuris** [comment]
@david-maw #3166 is unrelated to this issue - it was just that I had to use the steps there to even run the app as I can't currently use developer mode.  I'd literally downloaded 17.3 preview 2 to try a blazor maui app, did the steps above, got the error and googled it to bring me here.  Sorry for any confusion.

**Comment by JiuLing-zhang** [comment]
I also encountered this problem in Windows. I created a new Control(ContentView) and got an error updating the controls in the control(Multi-threading).
This code works in version 6.0.312.

![image](https://user-images.githubusercontent.com/78294929/178201607-d1f8f541-5545-4373-a3ea-4852d2f4d1f8.png)

![image](https://user-images.githubusercontent.com/78294929/178201684-fd0aab54-9d78-4b41-88c7-3c847aeaeb62.png)

**Comment by rmarinho** [comment]
@otium99  @david-maw  how can you reproduce the issue? i tested the repro and couldn't get it to crash.

**Comment by rmarinho** [comment]
After talking with the team we think we fixed this issue in the latest sr3 (6.0.419) so if you still see the problem after updating to that version please reopen.

Thanks

**Comment by david-maw** [comment]
@rmarinho great, should I be waiting for a new Visual Studio Preview or downloading something from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)? Put another way, when is the fix available to users, and how?

**Comment by JiuLing-zhang** [comment]
> @rmarinho太好了，我应该等待新的Visual Studio预览版[还是从这里下载](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)一些东西？换句话说，用户何时可以使用修复程序，以及如何使用？

@david-maw Just update VS to the latest version(17.3.0 Preview 4.0).

**Comment by JiuLing-zhang** [comment]
> @rmarinho great, should I be waiting for a new Visual Studio Preview or downloading something from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)? Put another way, when is the fix available to users, and how?

@david-maw Just update VS to the latest version(17.3.0 Preview 4.0).

**Comment by david-maw** [comment]
Thanks @JiuLing-zhang, that seemed to work fine.

That reminds me that I'm forever getting caught out by the fact there's a new preview version and I have not noticed it, do you know of any mechanism to get notifications when new versions are released?

**Comment by otium99** [comment]
@david-maw In my VS on the bottom right there is a notification bell. It shows a red number when there is a new version.

**Comment by david-maw** [comment]
Yep, I see it, thanks @otium99, I'll keep an eye on it - way easier than remembering to run the upgrade assistant to check.

**Comment by codemonkey85** [comment]
I'm seeing this issue in Visual Studio 2022 Version 17.3.1 (stable) as well.
![image](https://user-images.githubusercontent.com/1414036/185540595-39ef3286-3d18-47ca-a6fc-f8644fcb635b.png)
