### ISSUE TITLE
Cannot find nuget for lottie animations in MAUI

### ISSUE THREAD

**Issue by Awesomer9561** [dotnet/maui#8171]
### Description

I am trying to import a lottie animation in MAUI app. But so far I haven't found any nuget packages to do so.
Any idea when AirBnb is going to launch it's MAUI supported nuget or any other workarounds for this?

### Steps to Reproduce

1. Download a lottie json file from LottieFiles.
2. Search for lottie animations in Manage Nuget packages in Nuget Package Manager.
3. You will not find any nugets for MAUI.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android API 30, 31

**Comment by jfversluis** [comment]
There is no package that is compatible with .NET MAUI right now. Matthew is doing some great work based on SkiaSharp and we're trying to create a non-Skia version as well: https://twitter.com/mattleibow/status/1538541836452741123

Keep you eye on those!
