### ISSUE TITLE
Accessibility Insights for windows - flyout items with shell are wrongly named

### ISSUE THREAD

**Issue by NPavie** [dotnet/maui#8174]
### Description

While checking the accessibility of an app with a locked Flyout menu on Windows, the tool "Accessibility insights for Windows" is reporting errors on my flyout items : 
Each element of the flyout is given as a listitem, with property "Name = Microsoft.Maui.Controls.Platform.ShellFlyoutItemView", that is reported as an error in the tool.
That is happening with Title defined for all items in the flyout (ShellContent or FlyoutItem in my use case)

Possible fix i imagine : 
- Allow for SemanticProperties.Description usage on flyout items to force change this name
- Use the "Title" property of the item if it exists

### Steps to Reproduce

1. Create a sample "ShellApp" application : https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/create
2. Within the "AppShell", set the flyout locked in the XAML : `Shell.FlyoutBehavior="Locked"` attribute in the root Shell element
3. Create some flyout items (either ShellContent or FlyoutItem elements)
The example i use with some template pages to be replaced by your own : 
```xml
    <ShellContent
        Title="+ New job"
        ContentTemplate="{DataTemplate local:NewJobPage}"
        Route="NewJob"/>
    <FlyoutItem
        Title="Jobs" 
        FlyoutDisplayOptions="AsSingleItem"
        x:Name="Jobs"
        Route="jobs">
        <!-- Keeping a jobs tab with empty page for default "jobs" label to be displayed in flyout ...  
        But items are still added to flyout to keep the tabbed page behaviour -->
        <Tab Title="Jobs" Route="empty" x:Name="Empty" > 
            <ShellContent Title="No jobs launched" x:Name="NoJobs">
                <ShellContent.Content>
                    <ContentPage Title="No jobs launched yet">
                        <StackLayout>
                            <Label Text="No jobs launched yet"/>
                        </StackLayout>
                    </ContentPage>

                </ShellContent.Content>
            </ShellContent>
        </Tab>
    </FlyoutItem>
```
6. Check the resulting flyout accessibility tree with the "Accessibility insigths for windows" and look for the resulting "listitems"

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19044

### Did you find any workaround?

No workaround found yet

**Comment by PureWeen** [comment]
Closing in favor of https://github.com/dotnet/maui/issues/9066 which is being tracked by internal teams
