### ISSUE TITLE
Performance issue in LayoutExtensions.ShouldArrangeLeftToRight

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/maui#8175]
### Description

A chunk of time is spent in `LayoutExtensions.ShouldArrangeLeftToRight()`:

![image](https://user-images.githubusercontent.com/840039/174634569-fbd32ff6-e2f7-4bb7-a302-1b254e191896.png)

[maui-app_20220620_085602.speedscope.json.zip](https://github.com/dotnet/maui/files/8941918/maui-app_20220620_085602.speedscope.json.zip)

It appears the default behavior is for every MAUI view, to recurse all the way to the root `View` of the app:

![image](https://user-images.githubusercontent.com/840039/174634689-510d30e9-a038-4cdb-b26f-5af4f44a5a4e.png)

https://github.com/dotnet/maui/blob/c2c64e5a990e51fc19c209a2a3b6e4257276ffe5/src/Core/src/Layouts/LayoutExtensions.cs#L210-L222

https://github.com/dotnet/maui/blob/c2c64e5a990e51fc19c209a2a3b6e4257276ffe5/src/Core/src/Core/Extensions/IViewExtensions.cs#L5-L21

So let's say you have a nested layout, 5 views deep, with 100 `Label` on the screen. Each `Label` we end up querying the same views for flow direction 500 times.

Is there a way the default behavior could avoid recursion through parent views?

### Steps to Reproduce

1. Run this sample: https://github.com/unoplatform/performance/tree/master/src/dopes/DopeTestMaui
2. Click the button that says `Build` when the app launches
3. Record a `.speedscope` or `.nettrace` on Android: https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Any

**Comment by hartez** [comment]
Probably the easiest option would be to add an `EffectiveFlowDirection` property to the `IView` interface and locally cache the flow direction for each view. Then we just have to re-compute the flow direction for all child views when `FlowDirection` is updated for something in the hierarchy.

**Comment by jonathanpeppers** [comment]
I can confirm that the method mentioned above is gone in my latest trace:

[lols.zip](https://github.com/dotnet/maui/files/9560912/lols.zip)

Overall .NET 6 to 7 looks pretty good:

![image](https://user-images.githubusercontent.com/840039/190011385-42d9c383-697b-4ad2-b65d-74babd322454.png)
