### ISSUE TITLE
CollectionView stopped to work after VS update to 17.3.0 Preview 2.0

### ISSUE THREAD

**Issue by Schinwinkwinsky** [dotnet/maui#8178]
### Description

Hello, everybody

I'm developing a simple app to try .Net Maui and its first page has a CollectionView. It shows some info get from an API. Recently, a pop up appeared on VS saying it was available a new update. After applying that update, my app started to break on Android. At Out window an alert says: "You're using a preview version of .Net". It's running well on Windows, but on Android it's breaking with the message: _Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e440ac6'_

Before VS update, the version was 17.3.0 Preview 1.1 and now it's 17.3.0 Preview 2.0. Running the `dotnet --version` command at terminal, it shows: 6.0.400-preview.22301.10. 

The code is available at: https://github.com/Schinwinkwinsky/Pokedex

### Steps to Reproduce

1. Go to https://github.com/Schinwinkwinsky/Pokedex and download the solution.
2. Run the solution on Android.
3. Note that CollectionView items are not shown.
4. Try to scroll down. Some items will be shown.
5. Keep scrolling and the app maybe breaks.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 api 30

**Comment by kristinx0211** [comment]
verified repro on android with above project.

**Comment by AignerGames** [comment]
Any news or workaround? 

I have multiple tabs, the first tab contains a CollectionView and elements which can display a Image.
 select a entry with an image and change to a different tab, then change back to the tab with the CollectionView and in most cases I get the same exception and a crash "Canvas: trying to use a recycled bitmap"
 
I did not find any workaround so far, most Google searched result in some native Java code solutions.

It's very annoying and makes my app unusable in the current state

**Comment by Schinwinkwinsky** [comment]
> Any news or workaround? I updated to the newest MAUI version and have the same issue.
> 
> I have multiple tabs, the first tab contains a CollectionView and elements which can display a Image. select a entry with an image and change to a different tab, then change back to the tab with the CollectionView and in most cases I get the same exception and a crash "Canvas: trying to use a recycled bitmap"
> 
> I did not find any workaround so far, most Google searched result in some native Java code solutions.
> 
> It's very annoying and makes my app unusable in the current state

I resolved the problem of recycled exceptions using the MinimumHeightRequire property on images into CollectionView.
