### ISSUE TITLE
<Label Text={Binding .} /> works in Debug but not Release

### ISSUE THREAD

**Issue by polygonsheep** [dotnet/maui#8182]
### Description

Trying to use a BindableLayout to display a List of strings, e.g. List<string> MyStringList = {"Joe", "Mark", "Sarah", "Andy"}

Following xaml code works in the iOS Simulator & Android Emulator in Debug but not Release and not when published to an iPhone or Android phone.  No text is displayed in Release

`<VerticalStackLayout BindableLayout.ItemSource="{Binding MyStringList}">
  <BindableLayout.ItemTemplate>
    <DataTemplate>
       <Label Text="{Binding .}" />
    </DataTemplate>
  </BindableLayout.ItemTemplate>
</VerticalStackLayout>`

Also tried <Label Text="{Binding}" /> and <Label Text="{Binding Path=.}" />  both work on simulators not on devices.

dotnet version 6.0.301

### Steps to Reproduce

1. Create a new Maui App
2. Add a List<string> in the code behind
3. Add below code to xaml contentpage

<VerticalStackLayout BindableLayout.ItemSource="{Binding MyStringList}">
  <BindableLayout.ItemTemplate>
    <DataTemplate>
       <Label Text="{Binding .}" />
    </DataTemplate>
  </BindableLayout.ItemTemplate>
</VerticalStackLayout>

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 12

### Did you find any workaround?

no

**Comment by polygonsheep** [comment]
the bug report deleted my code. 

Here it is again

`                               <VerticalStackLayout BindableLayout.ItemsSource="{Binding MyStringList}">
                                    <BindableLayout.ItemTemplate>
                                        <DataTemplate>
                                                <Label Text="{Binding .}"/>
                                        </DataTemplate>
                                    </BindableLayout.ItemTemplate>
                                </VerticalStackLayout>
`

**Comment by polygonsheep** [comment]
More info, if you add the DataType to the DataTemplate the text will show up in Release mode. 
`<DataTemplate x:DataType="x:String">`

The DataType is not required in Debug mode.

**Comment by kristinx0211** [comment]
@polygonsheep not repro the issue, tell me if I miss something, my project: [MauiApp20.zip](https://github.com/dotnet/maui/files/9009259/MauiApp20.zip)

![image](https://user-images.githubusercontent.com/99457000/176401396-44822da5-3027-4785-86dd-f13689ad2cdc.png)
