### ISSUE TITLE
When fetching all contacts in MAUI and iterating through it, it takes a lot of time(>30s for around 1500 contacts) 

### ISSUE THREAD

**Issue by Awesomer9561** [dotnet/maui#8189]
### Description

I am creating an app where it is fetching all the contacts and showing them in a list/collection view, but the problem is whenever I try to iterate through the fetched contacts it will take me around 30+ secs to complete the iteration. I have tried multiple times with different approaches like fetching and assigning them to another variable and from there performing all the actions, implementing pagination to load a set of data at a time. But the stats for all of them are almost the same(10+ secs to load 100-300 contacts). This only happens when I am using the Contacts API in MAUI/Xamarin Essentials, fetching natively using cursor does not have any issues.

### Steps to Reproduce

var items = await Microsoft.Maui.ApplicationModel.Communication.Contacts.Default.GetAllAsync();
var count = items.Count();
//It will take around 100ms/1 contact.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 30, 31

### Did you find any workaround?

I tried fetching contacts natively using cursor in Android. Didn't try for iOS.

**Comment by PureWeen** [comment]
@Awesomer9561 can you attach a repro please? It's hard to know what's making it slow without one.

Maybe if you ToList() the returned results it'll get better?

**Comment by Awesomer9561** [comment]
[ContactsPicker.zip](https://github.com/dotnet/maui/files/8988250/ContactsPicker.zip)


> @Awesomer9561 can you attach a repro please? It's hard to know what's making it slow without one.
> 
> Maybe if you ToList() the returned results it'll get better?

Hi, this is the app. You can see all the methods over here.

**Comment by BenEdelstain** [comment]
Hi there, Same slow loading here too. Ir also crashes when trying to filter using the search bar.

//==========   ContactsPage.xaml.cs   ============
 public string FilterText
        {
            get => filterText;
            set
            {
                ContactsList = new ObservableCollection<Contact>();
                filterText = value;

                if (contacts != null)
                    foreach (var contact in contacts)
                    {
                        if (filterText == null || 
                            contact.DisplayName.ToLower().Contains(filterText.ToLower().Trim()))
                        {
                            ContactsList.Add(contact);
                        }
                    }

                lstContacts.ItemsSource = ContactsList;
            }
        }

        public ContactsPage()
        {
            InitializeComponent();
            GetAllContactCommand();
        }

        private async void GetAllContactCommand()
        {
            //ANDROID PERMISSIONS
            if (DeviceInfo.Platform == DevicePlatform.Android)
            {
                var permission = await Permissions.CheckStatusAsync<Permissions.ContactsRead>();
                if (permission != PermissionStatus.Granted)
                    permission = await Permissions.RequestAsync<Permissions.ContactsRead>();

                if (permission != PermissionStatus.Granted)
                {
                    await DisplayAlert("נא לאשר גישה לאנשי הקשר!", "אוקיי!", "ביטול");
                    return;
                }
            }

            try
            {
                // cancellationToken parameter is optional
                var cancellationToken = default(CancellationToken);
                contacts = await Contacts.GetAllAsync(cancellationToken);

                if (contacts == null)
                    return;

                FilterText = String.Empty;
			}
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
        }

//==========   ContactsPage.xaml   ============

<SearchBar Placeholder="חיפוש איש קשר..." Text="{Binding FilterText}" FlowDirection="RightToLeft" TextChanged="SearchBar_TextChanged"/>
        <ListView x:Name="lstContacts" Scrolled="lstContacts_Scrolled">

            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Padding="12"  Orientation="Horizontal" HorizontalOptions="End" FlowDirection="RightToLeft">
                            <CheckBox CheckedChanged="CheckBox_CheckedChanged" AutomationId="{Binding Id}"></CheckBox>
                            <Label Text="{Binding DisplayName}"/>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

**Comment by SunshineSpring666** [comment]
IEnumerable<PhoneContact> phoneContacts = await Contacts.Default.GetAllAsync();
this method takes very long time (about 1 min) if phone contains many Contacts.

Tried to wrap it into 
await Task.Run(async () =>{IEnumerable<PhoneContact> phoneContacts = await Contacts.Default.GetAllAsync();} );
but the phoneContacts result contains no element, and the code quits unexpectedly if try to get the phoneContacts.Count().

How to make this time-consuming method works in another thread (background, without blocking UI)?
Thanks.

**Comment by mattleibow** [comment]
I think you would want to actually get a list and not an enumerable: 

```cs
var contacts = await Task.Run(async () => {
    // get all contacts (delayed items)
    var all = await Contacts.Default.GetAllAsync();
    // force evaluation
    return all.ToList();
});
```

See some info:

* https://stackoverflow.blog/2022/06/15/c-ienumerable-yield-return-and-lazy-evaluation/
* https://codereview.stackexchange.com/questions/66756/method-returning-ienumerablet-should-tolist-or-not#:~:text=IEnumerable%20is%20lazily%20evaluated%20in%20that%20any%20operations,by%20using%20a%20fold%20%28First%20%28%29%2C%20FirstOrDefault%20%28%29%29.
