### ISSUE TITLE
maui publish windows 32bit

### ISSUE THREAD

**Issue by Snsaiu** [dotnet/maui#8196]
### Description

how do I publish windows 32bit.the default rule export 64bit when I use 'botnet publish' command.may I add any parameters?

### Steps to Reproduce

1. create maui project
2. build and run ok
3. use 'dotnet publish' command from maui document

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

windows

**Comment by MagicAndre1981** [comment]
pass Platform via parameter:

`dotnet publish -f net6.0-windows10.0.19041.0 -c Release /p:Platform=x86`

**Comment by Snsaiu** [comment]
> 通过参数传递平台：
> 
> `dotnet publish -f net6.0-windows10.0.19041.0 -c Release /p:Platform=x86`
I used this command ,but not work.
![image](https://user-images.githubusercontent.com/34592712/174929391-d6492562-1312-4d57-ab77-2c69181bac82.png)

**Comment by MagicAndre1981** [comment]
ok, if you don't need iOS, simply remove it from TargetFrameworks in the csproj and try it again. I don't develop for iOS/MAC so I removed both and only have Android and Windows and for me this works.

**Comment by Snsaiu** [comment]
> 好吧，如果你不需要iOS，只需从csproj中的TargetFrameworks中删除它，然后重试。我不为iOS / MAC开发，所以我删除了两者，只有Android和Windows，对我来说这是有效的。



> Hi @Snsaiu. We have added the "s/needs-info" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.
yes, you are right, when I delete configuration of IOS and Android in my maui project, I see the 'publish' menu is enable of project menu context, and I use your command, it really publish successfully. but when I deployed 21h2 version of windows, the package can install but not work...

**Comment by mattleibow** [comment]
I think that the Platform property is not correct - you need to use the RuntimeIdentifier.

```
dotnet publish -f net6.0-windows10.0.19041.0 -c Release -r win10-x86
```
