### ISSUE TITLE
Setup Hot Restart doesn't work

### ISSUE THREAD

**Issue by otium99** [dotnet/maui#8202]
### Description

I had previously this issue: https://stackoverflow.com/questions/72356192/setup-hot-restart-fails

And according to the comments, other people are facing similar or same issues with Hot Restart

I just upgraded to Version 17.3.0 Preview 2.0 in the hope, that now I can debug on my IPhone. Unfortunately the first error I was facing was this: https://github.com/dotnet/maui/issues/3927

After adding this line

`<ProvisioningType>automatic</ProvisioningType>`

at least the dialog comes up, just to present me with another error:
![HotRestartError](https://user-images.githubusercontent.com/67344857/174824147-db159bc4-396b-4b6a-931f-375c7c970a45.jpg)

### Steps to Reproduce

- Create a .NET MAUI App
- Connect your IPhone to the computer
- Select output -> Local Devices -> Your IPhone

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.3.1

### Did you find any workaround?

No.

**Comment by xxjnaxx** [comment]
https://developercommunity.visualstudio.com/t/Cannot-load-Apple-certificates/1692185

**Comment by PureWeen** [comment]
> https://developercommunity.visualstudio.com/t/Cannot-load-Apple-certificates/1692185

According to this you should be fixed in Preview 3
