### ISSUE TITLE
button not trigger

### ISSUE THREAD

**Issue by Ahmadmansoor** [dotnet/maui#8206]
### Description

after I update Maui, I note 2 things :
if my button is at the end of VerticalStackLayout, it will not trigger as it's unable.
but if I insert a frame or any control after it, it will work fine.
The second thing is if I debug a project on the first run it will debug under the emulator, but when I restart the project after making some changes, it will run the software under the emulator and not debug it  ( as it runs it ), to fix it I have to close the emulator then rebuild it again to get in debug mode.

### Steps to Reproduce

here the button will work 

```
<VerticalStackLayout        VerticalOptions="Start" BackgroundColor="DarkGray" Padding="4"  >
<Frame Padding="2" Margin="0,10,0,10"
               BorderColor="Blue"
               BackgroundColor="CadetBlue"
               HeightRequest="40"
               >
            <Label Text="{Binding Title}"                       
               HorizontalTextAlignment="Center"
                   HeightRequest="40"
               TextColor="DarkKhaki"                   
            />
<Button Text="Refresh"
                Margin="0,10,0,0" Padding="0"
                HeightRequest="50"
                BackgroundColor="Red"                
                Command="{Binding GetUserBySimNrCommand}" />
</VerticalStackLayout>
```

if I add this line 

`<Frame/>`

it works fine 

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS

### Affected platform versions

iOS15.5 Iphone 12

**Comment by Ahmadmansoor** [comment]
I have already tried to make CornerRadius=2
but this does not solve the issue as we see in the picture I can't press the button 

![image](https://user-images.githubusercontent.com/7176580/174950475-569e28c3-0ced-46e3-890a-3362b44a7c7a.png)

**Comment by hartez** [comment]
@Ahmadmansoor is your VerticalStackLayout inside of a ScrollView?
