### ISSUE TITLE
Shell.Current.FlyoutIsPresented = true does not toggle the first time on Android

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#8226]
### Description

Shell.Current.FlyoutIsPresented inside a button click event handler toggles flyout only after flyout was manually swiped one time.

### Steps to Reproduce

1. Run the attached example.
2. Tap on the "Toggle Flyout" button.
3. Nothing happens.
4. Swipe flyout manually.
5. Tap on the "Toggle Flyout" button again.
6. Now it works as expected.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

[MauiApp7.zip](https://github.com/dotnet/maui/files/8955500/MauiApp7.zip)

**Comment by kristinx0211** [comment]
verified repro on android with above project:
https://user-images.githubusercontent.com/99457000/175259094-e1134168-fb67-430d-88bc-777af0518e0f.mp4

**Comment by theadin** [comment]
Came across this issue too. It seems like a serious bug to me

**Comment by ViniciusAugustoRR** [comment]
has anyone found a workaround yet ?

**Comment by ViniciusAugustoRR** [comment]
> @ViniciusAugustoRR , Try adding these two lines before setting the FlyoutIsPresented to true:
> 
> ```
> Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
> Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
> Shell.Current.FlyoutIsPresented = true;
> ```

it worked, thanks a lot

**Comment by riccardominato** [comment]
> @ViniciusAugustoRR , Try adding these two lines before setting the FlyoutIsPresented to true:
> 
> ```
> Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
> Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
> Shell.Current.FlyoutIsPresented = true;
> ```

That's very helpful, but I had to guarantee that those statements are executed exactly once.
Otherwise, the button only works the first time.

```csharp
if (!_alreadyOpen)
{
    Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
    Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
    _alreadyOpen = true;
}

Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;
```

**Comment by ViniciusAugustoRR** [comment]
> > @ViniciusAugustoRR , Try adding these two lines before setting the FlyoutIsPresented to true:
> > ```
> > Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
> > Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
> > Shell.Current.FlyoutIsPresented = true;
> > ```
> 
> That's very helpful, but I had to guarantee that those statements are executed exactly once. Otherwise, the button only works the first time.
> 
> ```cs
> if (!_alreadyOpen)
> {
>     Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
>     Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
>     _alreadyOpen = true;
> }
> 
> Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;
> ```


I figured something similar to this, just less fancy lol (Used a counter instead of a bool :P), but thanks for the tip !

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Android 13.0 with below Project:
[MauiApp7.zip](https://github.com/dotnet/maui/files/11494571/MauiApp7.zip)

**Comment by MateuszLas421** [comment]
Still does not work normally, hope by autumn (.net 8.0) to fix it

**Comment by stoff99** [comment]
Still happen with newest .net8 preview ...

my workaround for now:
#if ANDROID
            if (!_alreadyOpen)
            {
                Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
                Shell.Current.FlyoutBehavior = FlyoutBehavior.Flyout;
                _alreadyOpen = true;
            }
            else
            {
                Shell.Current.FlyoutBehavior = FlyoutBehavior.Locked;
                _alreadyOpen = false;
            }
#elif IOS
            Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;
#endif
