### ISSUE TITLE
builder.Services.BuildServiceProvider() returns null on iOS

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#8231]
### Description

Using builder.Services.BuildServiceProvider() on platform iOS returns null.

Works fine on platform Android.

### Steps to Reproduce

1. Create a new project from Maui template.
2. Open MauiProgram.cs
3. Add line
       var serviceProvider = builder.Services.BuildServiceProvider();
   before
       return builder.Build();
4. Set breakpoint.
5. Start debugging on iOS device.
6. Value of serviceProvider is null.

 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by Eilon** [comment]
Hi @SailDev , that certainly seems unexpected! I don't think that API even _can_ return null, so that's quite odd. Does this happen only on a physical iOS device? Are you able to check on the iOS Simulator?

**Comment by Eilon** [comment]
Here's the relevant code for `MauiAppBuilder.Build()`, where there is no code path for returning `null`:

https://github.com/dotnet/maui/blob/main/src/Core/src/Hosting/MauiAppBuilder.cs#L152-L166

**Comment by PureWeen** [comment]
@SailDev I think this is a bug with VSMAC and that the debugger is reporting null when you inspect the value but it's not ACTUALLY null.

If you use Debug.Writeline or setup a conditional to check if it is null I'm pretty sure it won't be

**Comment by SailDev** [comment]
Sorry for the confusion, Debug.Writeline shows some values.
I was searching for a startup error in my application and thought this was the problem.

It seems to be an issue with the debugger in Visual Studio for Mac Preview Version 17.3 Preview (17.3 build 1038).

I was so close, to have the first productive Maui development session on a Mac with a real (big) application since November last year. Maybe next time.

**Comment by PureWeen** [comment]
Keeping this in s/needs-attention for now
Once this is fixed we can close

**Comment by nosami** [comment]
Fixed by https://github.com/dotnet/runtime/pull/71436

**Comment by nosami** [comment]
a workaround is `<UseInterpreter>false</UseInterpreter>` (but this breaks hot reload).

With the fix in https://github.com/dotnet/runtime/pull/71436 the workaround is not needed
