### ISSUE TITLE
Error running MAUI Blazor Application (.Net 6) using Xamarin.Firebase.Messaging

### ISSUE THREAD

**Issue by gabrielhruiz** [dotnet/maui#8233]
### Description

I try to create a MAUI Blazor Application which can receive and send push notifications. I don't found good documentation that resolves my problem. For this reason, I try to configure my application using the Xamarin documentation from [this website](https://docs.microsoft.com/es-es/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=windows).

When I finish configuring the app as in "steps to reproduce" is defined, the IDE throws the error defined in "Relevant log output" section.

### Steps to Reproduce

1. Create a new .NET MAUI Blazor Application project, using Visual Studio 2022(preview) & .net 6.
2. Add NuGet packages to work with Firebase:
- Xamarin.GooglePlayServices.Base (version 118.0.1.1)
- Xamarin.Firebase.Messaging (version 122.0.0.6)
3. Download from Firebase Console google-services.json file and include that file into project root.
4. Change property "Compilation Action" of JSON file to "GoogleServiceJson".
5. Run application in "Pixel 5 - API 30 (Android 11.0 - API 30)"
6. When the app starts to run in the environment, the IDE throws: 
`Java.Lang.NoClassDefFoundError: 'Failed resolution of: Lcom/google/android/datatransport/TransportFactory;'`

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Relevant log output

```shell
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/datatransport/TransportFactory;
[MonoDroid]  ---> Java.Lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.TransportFactory" on path: DexPathList[[zip file "/data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/lib/x86_64, /data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.ClassNotFoundException stack trace ---
[MonoDroid] java.lang.ClassNotFoundException: Didn't find class "com.google.android.datatransport.TransportFactory" on path: DexPathList[[zip file "/data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/lib/x86_64, /data/app/~~0yd9fpj-0FFrqbciHFeH4Q==/com.companyname.mauiapp2blazor-OVinhY9xrXH32TwCwxM1Zw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
[MonoDroid] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[MonoDroid] 	at com.google.firebase.datatransport.TransportRegistrar.getComponents(TransportRegistrar.java:32)
[MonoDroid] 	at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:109)
[MonoDroid] 	at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:91)
[MonoDroid] 	at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:45)
[MonoDroid] 	at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:360)
[MonoDroid] 	at com.google.firebase.FirebaseApp.<init>(FirebaseApp.java:427)
[MonoDroid] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:299)
[MonoDroid] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
[MonoDroid] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
[MonoDroid] 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
[MonoDroid] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
[MonoDroid] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
[MonoDroid] 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
[MonoDroid] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
[MonoDroid] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
[MonoDroid] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
[MonoDroid] 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:223)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[MonoDroid]
```

**Comment by rkops-bd** [comment]
Any updates?

**Comment by rkops-bd** [comment]
This issue is also in a 'normal' .net Maui application.

**Comment by jfversluis** [comment]
I've heard from people they have got this working but I see the package versions are slightly lower, see: https://gist.github.com/jfversluis/dd760594099066c7450d50cce6499368

Would you be able to maybe try those and see if that helps? If so, then it must be something that was introduced recently. 

@jonathanpeppers?

**Comment by rkops-bd** [comment]
> I've heard from people they have got this working but I see the package versions are slightly lower, see: https://gist.github.com/jfversluis/dd760594099066c7450d50cce6499368
> 
> Would you be able to maybe try those and see if that helps? If so, then it must be something that was introduced recently.
> 
> Does this only happen on Debug or Release or both? Are you using Proguard or any linker settings?
> 
> @jonathanpeppers?

Thanks @jfversluis for the tip. In my solution was adding `<PackageReference Include="Xamarin.Firebase.Iid" Version="121.1.0" />` the solution.

**Comment by jonathanpeppers** [comment]
@jpobst @moljac is there maybe a missing NuGet dependency somewhere? If adding `Xamarin.Firebase.Iid` fixes something, maybe one of the other packages should be depending on it?

**Comment by moljac** [comment]
> @jpobst @moljac is there maybe a missing NuGet dependency somewhere? If adding `Xamarin.Firebase.Iid` fixes something, maybe one of the other packages should be depending on it?

smells like DataTransport dependency (transitive)

let me check

**Comment by jpobst** [comment]
I think the issue is that our `Xamarin.Google.Android.DataTransport.*` packages do not include the `.aar` for .NET 6:

![image](https://user-images.githubusercontent.com/179295/177405379-6fb4a08f-b5c2-4462-afcc-08b297f68323.png)

(For `monoandroid90` the `.aar` is included in the `.dll`.)

We currently use `<LibraryProjectZip>` [to specify the library for binding](https://github.com/xamarin/GooglePlayServicesComponents/blob/main/templates/datatransport/Project.cshtml#L83).  It seems when this is used in `Xamarin.Legacy.Sdk`, the library does not get added to the NuGet for .NET 6.  I think we need to use `<AndroidLibrary>` instead, which seems to do the correct thing.

Local with `<AndroidLibrary>`:
![image](https://user-images.githubusercontent.com/179295/177405797-5ce17672-4a37-49bd-8676-eb94d77deb0d.png)

Thus the current workaround is to reference `Xamarin.Google.Android.DataTransport.*` versions `3.0.0` or earlier, as they did not include a .NET 6 version, so the correct Classic Xamarin `.dll` is used instead.

**Comment by gabrielhruiz** [comment]
We have tried using these libraries as mentioned in the thread but the problem persists with the same error.
```
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
  <PackageReference Include="Xamarin.Firebase.Iid"><Version>121.1.0.6</Version></PackageReference>
  <PackageReference Include="Xamarin.Firebase.Messaging"><Version>122.0.0.6</Version></PackageReference>
  <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportApi"><Version>3.0.0.4</Version></PackageReference>
  <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportRuntime"><Version>3.1.4.1</Version></PackageReference>
  <PackageReference Include="Xamarin.Google.Dagger"><Version>2.41.0.1</Version></PackageReference>
  <PackageReference Include="Xamarin.GooglePlayServices.Base"><Version>118.0.1.1</Version></PackageReference>
</ItemGroup>
```

**Comment by Giuseppetm** [comment]
Any update??

**Comment by gabrielhruiz** [comment]
no at the moment.

**Comment by jpobst** [comment]
New packages were released a few weeks ago.

For example, https://www.nuget.org/packages/Xamarin.Google.Android.DataTransport.TransportApi/3.0.0.5 contains the fix.

Can you update your packages to the latest on NuGet and see if the issue persists?

**Comment by moljac** [comment]
> * Xamarin.GooglePlayServices.Base (version 118.0.1.1)
> * Xamarin.Firebase.Messaging (version 122.0.0.6)

new versions are available:

* Xamarin.GooglePlayServices.Base
  * https://www.nuget.org/packages/Xamarin.GooglePlayServices.Base/118.1.0
* Xamarin.Firebase.Messaging 
  * https://www.nuget.org/packages/Xamarin.Firebase.Messaging/123.0.3

please provide some feedback if issue is resolved. THanks

**Comment by gabrielhruiz** [comment]
The error was resolved with these package updates. Thanks!
