### ISSUE TITLE
WinUI layout bugged

### ISSUE THREAD

**Issue by osnipezzini** [dotnet/maui#8238]
### Description

It's a shame a layout of WinUI style, i refused to use UNO because of this layout, and now MAUI bring this back. What we need to do for fix this layout ?

![image](https://user-images.githubusercontent.com/4562546/175044536-4dd9007c-01e6-41a1-844a-9e77a0c4bb2e.png)

### Steps to Reproduce

 - Create a MAUI project with Shell
 - Add some example pages
 - Run project for Windows target

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by PureWeen** [comment]
@osnipezzini can you post a repro or your Shell xaml please?
