### ISSUE TITLE
IOS: Custom font icon is not rendered in a shell tabbar tab

### ISSUE THREAD

**Issue by lnaie** [dotnet/maui#8244]
### Description

Did attach some screenshots and a code sample. 
 
![android_emul_sample](https://user-images.githubusercontent.com/1276077/175081675-50780dbf-a640-41a5-9e08-56cdbb1cf9d0.png)
<img width="456" alt="Screenshot 2022-06-22 at 16 52 40" src="https://user-images.githubusercontent.com/1276077/175081682-bf6ba04b-ec28-4e1f-a3da-8f71afe74cb2.png">

[MauiApp3.zip](https://github.com/dotnet/maui/files/8959517/MauiApp3.zip)

### Steps to Reproduce

1. It's all in the sample code.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by kristinx0211** [comment]
verified repro on IOS15.4 with vs 17.3.0 Preview 3.0 [32621.293.main].

**Comment by legrignotin** [comment]
I am having the same problem too :/

Actually they are rendered, the color is just white on white...
If you force a color on the glyph you'll see it but you'll lose the selected item style, disabled style etc...

**Comment by NPadrutt** [comment]
I'm at the same point as @legrignotin. 
It's a bit surprising to me that this is open for so long and now moved to the backlog (as is the issue with the TitleView) as those are small details that make an app look very unpolished.

**Comment by yurkinh** [comment]
Checked this issue with Maui in NET 7 RC2 an it is still present(

**Comment by NPadrutt** [comment]
Has this issue any relation with the issue that images on iOS are blurry when a page is first rendered?

**Comment by phookycom** [comment]
Is there any news on this? Unfortunately, the problem was not solved with NET 7.0 GA. And explicitly specifying the color of the TabIcon is not a solution, because the behavior of the tabs is then no longer dynamic.

` <FontImageSource FontFamily="FontAwesomeSolid" Glyph="&#xf0fc;" Size="22" Color="{StaticResource Primary}"  />`

**Comment by andrei25f** [comment]
In the attached project ([MauiApp3.zip](https://github.com/dotnet/maui/files/8959517/MauiApp3.zip)), сhange this:
`<Tab Route="main" Title="Home">`
        `<Tab.Icon>`
                `<FontImageSource FontFamily="MD" Glyph="{x:Static res:IconFont.HomeOutline}" Size="24"/>`
        `</Tab.Icon>`
        `<ShellContent ContentTemplate="{DataTemplate local:MainPage}" />`
`</Tab>`
To:
`<Tab Title="Home" Icon="{FontImage Color=Black, FontFamily=MD, Glyph={x:Static res:IconFont.HomeOutline}}">`
        `<ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="main" />`
`</Tab>`
![test](https://user-images.githubusercontent.com/112927597/202675768-8e3bd87a-ceec-4c92-8e6d-996287d9c061.png)

**Comment by Adelzu** [comment]
> In the attached project ([MauiApp3.zip](https://github.com/dotnet/maui/files/8959517/MauiApp3.zip)), сhange this:
> `<Tab Route="main" Title="Home">`
> `<Tab.Icon>`
> `<FontImageSource FontFamily="MD" Glyph="{x:Static res:IconFont.HomeOutline}" Size="24"/>`
> `</Tab.Icon>`
> `<ShellContent ContentTemplate="{DataTemplate local:MainPage}" />`
> `</Tab>`
> To:
> `<Tab Title="Home" Icon="{FontImage Color=Black, FontFamily=MD, Glyph={x:Static res:IconFont.HomeOutline}, Size=24}">`
> `<ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="main" />`
> `</Tab>`
> ![test](https://user-images.githubusercontent.com/112927597/202675768-8e3bd87a-ceec-4c92-8e6d-996287d9c061.png)


By specifying black as the icon color, you just lost dark theme

**Comment by am-kh** [comment]
Any news on this??

**Comment by NPadrutt** [comment]
Still waiting on a fix for this too.

**Comment by rysbilinski** [comment]
If it helps anyone, I managed to workaround this using styles and triggers

`<Tab
            Title="Inbox"
            FlyoutItemIsVisible="False"
            Icon="{FontImage FontFamily=Material,
                             Glyph={x:Static font:MaterialFontIcons.Notifications}}"
            Route="NotificationsPage"
            Style="{OnPlatform iOS={StaticResource notificationsTab}}">
            <ShellContent ContentTemplate="{DataTemplate views:NotificationsPage}" />
</Tab>`

Then the style:

` <Style x:Key="notificationsTab" TargetType="Tab">
                <Style.Triggers>
                    <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                        <Setter Property="Icon" Value="{FontImage FontFamily=Material, Glyph={x:Static font:MaterialFontIcons.Notifications}, Color={StaticResource SecondaryDark}}" />
                    </Trigger>
                    <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                        <Setter Property="Icon" Value="{FontImage FontFamily=Material, Glyph={x:Static font:MaterialFontIcons.Notifications}, Color={StaticResource Gray200}}" />
                    </Trigger>
                </Style.Triggers>
            </Style>`

![image](https://user-images.githubusercontent.com/13427152/214531246-bda540e2-537a-4687-8400-f96683a9097d.png)

**Comment by NPadrutt** [comment]
thanks @rysbilinsk! The only issue I have with this, is that I would have to have different colors for different themes. I tried using an AppThemeBinding for Color:

```
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon"
                            Value="{FontImage FontFamily=MaterialIcons, Glyph={x:Static views:IconFont.HomeOutline}, Color={AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource White}}}" />
                </Trigger>

```
But that gives me an error, that there is no property for Color. Before I used an FontImageSource, but I haven't found out how to use that in the style yet. In case you know how to solve that I'd greatly appreciate any hint :)

**Comment by rysbilinski** [comment]
> thanks @rysbilinsk! The only issue I have with this, is that I would have to have different colors for different themes. I tried using an AppThemeBinding for Color:
> 
> ```
>                 <Trigger TargetType="Tab" Property="IsChecked" Value="True">
>                     <Setter Property="Icon"
>                             Value="{FontImage FontFamily=MaterialIcons, Glyph={x:Static views:IconFont.HomeOutline}, Color={AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource White}}}" />
>                 </Trigger>
> ```
> 
> But that gives me an error, that there is no property for Color. Before I used an FontImageSource, but I haven't found out how to use that in the style yet. In case you know how to solve that I'd greatly appreciate any hint :)

have to be honest I am forcing my app to only have light theme for now. 

Could you maybe have the app theme binding on a resource dictionary? And have a resource dictionary containing the different themes for each file? Or just duplicate the themes for dark and light and apply the app theme binding on the style in the tab item?

**Comment by arahmancsd** [comment]
Finally, I fixed mine with this approach and it works as expected in iOS

```
<Tab Title="Discover">
            <Tab.Style>
                <Style TargetType="Tab">
                    <Style.Triggers>
                        <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                            <Setter Property="Icon">
                                <Setter.Value>
                                    <FontImageSource Size="20" Color="{DynamicResource Primary}"
                                                     Glyph="{x:Static util:FontAwesomeIcons.Home}"
                                                     FontFamily="Fas"/>
                                </Setter.Value>
                            </Setter>
                        </Trigger>

                        <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                            <Setter Property="Icon">
                                <Setter.Value>
                                    <FontImageSource Size="20" Color="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}"
                                                     Glyph="{x:Static util:FontAwesomeIcons.Home}" FontFamily="Fas"/>
                                </Setter.Value>
                            </Setter>
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </Tab.Style>
            <ShellContent ContentTemplate="{DataTemplate homeTabViews:HomePage}"/>
        </Tab>
```

**Comment by NPadrutt** [comment]
> Finally, I fixed mine with this approach and it works as expected in iOS
> 
> ```
> <Tab Title="Discover">
>             <Tab.Style>
>                 <Style TargetType="Tab">
>                     <Style.Triggers>
>                         <Trigger TargetType="Tab" Property="IsChecked" Value="True">
>                             <Setter Property="Icon">
>                                 <Setter.Value>
>                                     <FontImageSource Size="20" Color="{DynamicResource Primary}"
>                                                      Glyph="{x:Static util:FontAwesomeIcons.Home}"
>                                                      FontFamily="Fas"/>
>                                 </Setter.Value>
>                             </Setter>
>                         </Trigger>
> 
>                         <Trigger TargetType="Tab" Property="IsChecked" Value="False">
>                             <Setter Property="Icon">
>                                 <Setter.Value>
>                                     <FontImageSource Size="20" Color="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}"
>                                                      Glyph="{x:Static util:FontAwesomeIcons.Home}" FontFamily="Fas"/>
>                                 </Setter.Value>
>                             </Setter>
>                         </Trigger>
>                     </Style.Triggers>
>                 </Style>
>             </Tab.Style>
>             <ShellContent ContentTemplate="{DataTemplate homeTabViews:HomePage}"/>
>         </Tab>
> ```

This solution works for me on iOS, but has weird side effects on Android.

**Comment by ewerspej** [comment]
Is there any update on this issue?

**Comment by arnaudaug** [comment]
In addition to the solution proposed above with triggers, in the meantime if it helps you, I use this code in App.xaml.cs : 

`        Current.MainPage = DeviceInfo.Platform == DevicePlatform.iOS ||
                           DeviceInfo.Platform == DevicePlatform.MacCatalyst
            ? new AppShellApple()
            : new AppShell();`

**Comment by SliemBeji-FBC** [comment]
Unfortunately still a problem :( WE ARE ALSO AFFECTED

**Comment by zippo227** [comment]
> Here is a complete solution that works for both. I have configured the Android theme in the Resources folder so didn't add the Android styling.
> 
> ```
>     <On Platform="Android">
>         <TabBar>
>             
>             <Tab Title="My Day">
>                 <ShellContent ContentTemplate="{DataTemplate todayTab:MyDayPage}" />
>                 <Tab.Icon>
>                     <FontImageSource Glyph="{x:Static util:FontAwesomeIcons.Check}" FontFamily="Fas"/>
>                 </Tab.Icon>
>             </Tab>
>             ....
>         </TabBar>
>     </On>
> 
>     <On Platform="iOS">
>             <TabBar>
> 
>                 <Tab Title="My Day">
>                     <ShellContent ContentTemplate="{DataTemplate todayTab:MyDayPage}"/>
> 
>                     <Tab.Style>
>                         <Style TargetType="Tab">
>                             <Style.Triggers>
>                                 <Trigger TargetType="Tab" Property="IsChecked" Value="True">
>                                     <Setter Property="Icon">
>                                         <Setter.Value>
>                                             <FontImageSource Size="20"
>                                                          Color="{DynamicResource Primary}"
>                                                  Glyph="{x:Static util:FontAwesomeIcons.Check}"
>                                                  FontFamily="Fas"/>
>                                         </Setter.Value>
>                                     </Setter>
>                                 </Trigger>
> 
>                                 <Trigger TargetType="Tab" Property="IsChecked" Value="False">
>                                     <Setter Property="Icon">
>                                         <Setter.Value>
>                                             <FontImageSource Size="20" Color="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}"
>                                                  Glyph="{x:Static util:FontAwesomeIcons.Check}"
>                                                  FontFamily="Fas"/>
>                                         </Setter.Value>
>                                     </Setter>
>                                 </Trigger>
>                             </Style.Triggers>
>                         </Style>
> 
>                     </Tab.Style>
>                 </Tab>
> 
>             </TabBar>
>              ....
>         </On>
> </OnPlatform>
> ```

This solution did resolve my issues on iOS, though the OnPlatform parts had compile time issues for me. In my case the settings for android are mostly unaffected by the settings in here, so I do not, as of yet require setting OnPlatform.

I do hope the maui team is able to find a way to remove the requirement for this on iOS.

**Comment by bcaceiro** [comment]
Also the sizes are completely screwed using icon fonts

**Comment by matt-goldman** [comment]
Seem to be having the same problem with Flyout

**Comment by MitchBomcanhao** [comment]
> Same issue with TabbedPage. No xaml workaround as a page don't have IsChecked property.
@softlion check https://github.com/dotnet/maui/issues/12250#issuecomment-1771137433 for a workaround to get icons displayed on tabbedpages.

**Comment by softlion** [comment]
> > Same issue with TabbedPage. No xaml workaround as a page don't have IsChecked property.
> 
> @softlion check [#12250 (comment)](https://github.com/dotnet/maui/issues/12250#issuecomment-1771137433) for a workaround to get icons displayed on tabbedpages.

It's not for iOS, it's both Android and iOS. I actually experience the issue on Android.

Here is my workaround:

```cs
public class TabbedPage2 : TabbedPage
{
    /// <summary>
    /// Tabs don't receive OnParentSet(null) otherwise !
    /// </summary>
    protected override void OnParentSet()
    {
        base.OnParentSet();

        if (Parent == null)
        {
            var childs = Children.ToList();
            ItemsSource = null;
            //Children.Clear();
            foreach (var c in childs)
                c.Parent = null;
        }
    }

    /// <summary>
    /// Workaround for  https://github.com/dotnet/maui/issues/8244
    /// </summary>
    protected override void OnCurrentPageChanged()
    {
        base.OnCurrentPageChanged();

        if (CurrentPage.IconImageSource is SvgImageSource imageSource)
        {
            imageSource.ColorMapping = $"000=>008FBE";
            CurrentPage.IconImageSource = imageSource;
        }

        foreach (Page page in Children)
        {
            if(page != CurrentPage && page.IconImageSource is SvgImageSource imageSource2)
            {
                imageSource2.ColorMapping = $"000=>DDD";
                page.IconImageSource = imageSource2;
            }
        }
    }
}
```

It uses [SvgImageSource](https://github.com/vapolia/Svg-Samples) but you can do the same for any type of source.

**Comment by MitchBomcanhao** [comment]
well, this bug is about iOS, so it would seem that your android issue would be a different one.

**Comment by zaidmka** [comment]
i had this bug as well 
`<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="TeaStoreApp.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TeaStoreApp"
    xmlns:pages="clr-namespace:TeaStoreApp.Pages"
    Shell.FlyoutBehavior="Disabled"
    Shell.TabBarBackgroundColor="#18565F"
    Shell.TabBarTitleColor="Red"
    Shell.TabBarUnselectedColor="Green"

    
    
    >

    <TabBar>
        <Tab Title="Home" Icon="home_25">
            <ShellContent ContentTemplate="{DataTemplate pages:HomePage}"/>
        </Tab>

        <Tab Title="Cart" Icon="cart_25">
            <ShellContent ContentTemplate="{DataTemplate pages:CartPage}"/>
        </Tab>

        <Tab Title="Favorites" Icon="heart_25">
            <ShellContent ContentTemplate="{DataTemplate pages:FavoritePage}"/>
        </Tab>

        <Tab Title="Profile" Icon="profile_25">
            <ShellContent ContentTemplate="{DataTemplate pages:ProfilePage}"/>
        </Tab>
    </TabBar>
</Shell>
`
this is the AppShell
its act deferentin iOS and Android
![Screenshot 2024-04-09 223053](https://github.com/dotnet/maui/assets/83184605/4ea64445-ea00-4890-81ae-4aa0723f8670)
![Screenshot 2024-04-09 223044](https://github.com/dotnet/maui/assets/83184605/9c10874d-d71f-462e-96b6-9fb1d299c226)
also i cant adjust the bar heigh!

**Comment by tscholze** [comment]
I stumbled across this, too. Commenting for update information

**Comment by ewerspej** [comment]
> I stumbled across this, too. Commenting for update information

@tscholze You can also subscribe to posts without commenting ;) JFYI

**Comment by tscholze** [comment]
@ewerspej a thanks I totally forgot it. I really hope that experts like you can fix this issue soon. :)

**Comment by ewerspej** [comment]
@tscholze I'm actually not a member of the development team, but I'm looking for workarounds while it's not fixed. I'm not that deep into the internals of MAUI yet

**Comment by breyed** [comment]
[StackOverflow post](https://stackoverflow.com/q/74126712/145173) on issue (with additional workaround)

**Comment by samhouts** [comment]
We agree that this is an important issue. As our [roadmap ](https://github.com/dotnet/maui/wiki/Roadmap) indicates, for the near future, we are focused on:

- Issues impacting Xamarin.Forms upgrades to .NET MAUI
- CollectionView
- Layout

I am marking this as a p/2 issue because it does not meet our focus areas _right now_, but we are constantly revisiting the backlog for important issues to address as time allows. Thank you for your patience and understanding!
