### ISSUE TITLE
[WinUI] Silent crash when updating binding at runtime while thumb scrolling

### ISSUE THREAD

**Issue by RanjithkumarSyncfusion** [dotnet/maui#8247]
### Description

Application **getting crashed without any exception** while thumb scrolling(Dragging thumb).

### Steps to Reproduce
1. Create a sample with MainPage ->ScrollView -> StackLayout- > N number of labels till scrollviewer becomes scrollable.
2. Create a ViewModel class with string Property.
3. Set the ViewModel as BindingContext of MainPage or StackLayout.
4. Bind the ViewModel string property to three or more label Text property.
5. Subscribe ScrollView.Scrolled event, Inside the body update BindingContext of the MainPage or StackLayout.
6. Now deploy the sample and scroll using thumb, application will get crashed without any exception.

### Note
Try binding ViewModel.string property to more label if crashing not occurs.

### Code snippet
**MainPage.Xaml**
```
  <ScrollView Scrolled="ScrollView_Scrolled">
        <StackLayout x:Name="Stack">
            <Label Text="{Binding Name}"/>
            <Label Text="Hello"/>
            <Label Text="Hello"/>
            <Label Text="Hello"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="{Binding Name}"/>
            <Label Text="Hello"/>
            <Label Text="Hello"/>
            <Label Text="Hello"/>
               ....
               ....
            <Label Text="Hello"/>
        </StackLayout>
    </ScrollView>
```

**ViewModel**:
```
public class NumberViewModel : INotifyPropertyChanged
{
    private string name = "hello";
    public string Name
    {
        get { return name; }
        set { name = value; this.RaisePropertyChanged(nameof(Name)); }
    }

   public event PropertyChangedEventHandler PropertyChanged;
   public void RaisePropertyChanged(string propName)
   {
        if (this.PropertyChanged != null)
        {
            this.PropertyChanged(this, new PropertyChangedEventArgs(propName));
        }
   }
}
```

**MainPage.Xaml.cs**
```
public MainPage()
{
    InitializeComponent();
    this.BindingContext = new NumberViewModel();
}
private void ScrollView_Scrolled(object sender, ScrolledEventArgs e)
{
     this.BindingContext = new NumberViewModel() { Name = "Updated" };
}
```

**Video:**
https://user-images.githubusercontent.com/59435340/175104231-a8c8f96e-d093-42ec-99b3-65c140668af2.mp4

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

Windows

### Affected platform versions

10.0.17763.0

### Did you find any workaround?

When setting ScrollViewer(platform view) scrollbar visibility to Visible exception not occurring.

### Relevant log output

```shell
The program '[32648] SampleApp.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
```

**Comment by kristinx0211** [comment]
not repro on windows with vs 17.3.0 Preview 3.0 [32621.293.main]. project:[MauiApp6.zip](https://github.com/dotnet/maui/files/8963028/MauiApp6.zip)
https://user-images.githubusercontent.com/99457000/175191547-ec9fdd73-cbdf-47c4-a45f-f8436281bce3.mp4

**Comment by RanjithkumarSyncfusion** [comment]
Hi @kristinx0211 
Can you please scroll using thumb in the scrollbar. Since the crashing occurs only while scrolling with thumb.
https://user-images.githubusercontent.com/59435340/175205977-1c44302d-8a59-4682-b040-0f92533fd4e3.mp4

**Comment by kristinx0211** [comment]
@RanjithkumarSyncfusion ok, thanks for your info, I can repro as you say.
![image](https://user-images.githubusercontent.com/99457000/175222553-4e98a61e-d2b7-4df9-aa5a-59ac19b15bb2.png)

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue. Is dragging the thumb?
![issue-8247](https://user-images.githubusercontent.com/6755973/175493381-c629fa4c-fb83-461e-8df1-56d28151658a.gif)

**Comment by RanjithkumarSyncfusion** [comment]
Hi @jsuarezruiz 
Sometimes issue ain't occurring with less binding. please try increasing binding Name to more labels.

**Comment by RanjithkumarSyncfusion** [comment]
Hi Team
Any update on this?

**Comment by jsuarezruiz** [comment]
Tried with 100 bindings and still cannot reproduce it.
![issue-8247](https://user-images.githubusercontent.com/6755973/176454252-e4ce174b-dd4f-4ab0-961c-a5e97becdd29.gif)

@rachelkang Could you try to reproduce it?

**Comment by rachelkang** [comment]
Yep, I'm able to reproduce this issue. It happens if you try scrolling via thumb scrolling as soon as the app starts up. If you scroll without using the thumb scrolling / try anything else before thumb scrolling, then the issue isn't reproducible.

**Comment by BenBtg** [comment]
I've been working with a customer who is also seeing this issue.

**Comment by BenBtg** [comment]
This is causing a crash and is easily reproducible on WinUI. 
Should we be including the fatal flag and treating this as higher priority?

**Comment by breenbob** [comment]
@RanjithkumarSyncfusion is the Syncfusion ListView built on-top of the .Net Maui ListView control? I ask because we could not reproduce this with the Maui ListView, only the SfListView. I created a sample Maui app to see if I could repro the issue we are having with our Grouped SfListView in a plain .Net Maui Grouped ListView, and I've used more data and more bindings in the layouts than we have in our SfListView scenario in our "real" app, yet could not reproduce the issue in the Maui ListView... You can see my attempt [here](https://github.com/breenbob/Maui-Scroll-Crash).

**Comment by jsuarezruiz** [comment]
> Yep, I'm able to reproduce this issue. It happens if you try scrolling via thumb scrolling as soon as the app starts up. If you scroll without using the thumb scrolling / try anything else before thumb scrolling, then the issue isn't reproducible.

Could you share more details?, did you reproduce it on Windows 11?

**Comment by rachelkang** [comment]
yes, it was on windows 11. but I just created a new project on the latest version of both .NET 7 and .NET 8, and can no longer reproduce it! perhaps this has since been fixed?

@RanjithkumarSyncfusion @BenBtg is this still an issue on the latest versions?

**Comment by RanjithkumarSyncfusion** [comment]
@rachelkang 
Yes, the problem has been fixed!
