### ISSUE TITLE
Entry as plain text if IsPassword="True" and IsReadOnly="True"

### ISSUE THREAD

**Issue by eqmarcin** [dotnet/maui#8267]
### Description

Password is displayed as plain text if Entry IsPassword="True" and IsReadOnly="True".

I only have it tested on Samsung tablet with Android 11.
Android emulator (API 30) is OK.
iOS physical devices (latest iOS) are OK.

### Steps to Reproduce

`  <Entry Text="{Binding Password}" 
       Placeholder="Enter password" 
       IsPassword="True"
       IsReadOnly="True"/>`

### Version with bug

6.0.400-preview.22301.10

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Display password as Label

**Comment by NonameMissingNo** [comment]
Not repo on main
![image](https://user-images.githubusercontent.com/40233496/175247791-22b432de-ef4e-44e6-9cd8-6d98167d01f0.png)

**Comment by eqmarcin** [comment]
Sorry, I just noticed that my Mac has still version 6.0.312. Probably it was fixed in 6.0.4

**Comment by eqmarcin** [comment]
Ok, so I have tested in on Windows with 6.0.4
![code](https://user-images.githubusercontent.com/108053161/175260535-e7e4c3ab-de7b-42b5-a912-96301e3c0ef5.png)

and the issue is still here

![Screenshot_2022-06-23-09-58-22-031_com companyname mauiapp3](https://user-images.githubusercontent.com/108053161/175260759-edaedab9-3017-4504-b92d-7c0dc99c7c92.jpg)

**Comment by kristinx0211** [comment]
not repro on windows, but repro on android. vs version 17.3.0 Preview 3.0 [32623.336.main]. SDK version: 6.0.400-preview.22316.6
windows:
![image](https://user-images.githubusercontent.com/99457000/175474613-bb5ebc6f-fc81-470a-8b7d-c4db60cd6745.png)
Android:
![image](https://user-images.githubusercontent.com/99457000/175475030-7f5d06c0-7433-4bc2-b67e-1e26ce90da41.png)
