### ISSUE TITLE
VisualElement.InvalidateMeasure not work at Android after update VisualStudio to 17.3.0 preview2

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#8270]
### Description

After update VisualStudio to 17.3.0 preview2, use `VisualElement.InvalidateMeasure()` not let layout load `MeasureOverride` again at Android, it work at Windows, i don't test it at iOS.

### Steps to Reproduce

1. Download  [maui_issue_8270.zip](https://github.com/dotnet/maui/files/8965812/maui_issue_8270.zip) and Run
2. Click InvalidateContentView Button, see MeasureOverride information

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

**Comment by xtuzy** [comment]
### Video

- Android

https://user-images.githubusercontent.com/17793881/175264841-eb7c552d-55ae-4195-9295-4f8d4366cd56.mp4

- Windows

https://user-images.githubusercontent.com/17793881/175264867-a99d74e6-42fd-480b-bed8-5c20255e0726.mp4

**Comment by PureWeen** [comment]
@xtuzy this should be fixed when preview3 releases

If you are still seeing this issue with preview3 can you upload a repro to github?
