### ISSUE TITLE
Attempting to run on iOS device gets doesn't have a target for 'net6.0-ios/ios-arm64' error

### ISSUE THREAD

**Issue by hevey** [dotnet/maui#8272]
### Description

When running a MAUI project on an iOS device (not simulator) from the latest Visual Studio 2022 preview gets error "doesn't have a target for 'net6.0-ios/ios-arm64'"

### Steps to Reproduce

Create new project from Visual Studio for Mac 17.2 preview 2.1
Select iOS Device from run options
Run the project 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

### Relevant log output

```shell
/usr/local/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(5,5): Error NETSDK1047: Assets file '/Users/hevey/Development/PlayCade/Cade/src/Cade/obj/project.assets.json' doesn't have a target for 'net6.0-ios/ios-arm64'. Ensure that restore has run and that you have included 'net6.0-ios' in the TargetFrameworks for your project. You may also need to include 'ios-arm64' in your project's RuntimeIdentifiers. (NETSDK1047) (Cade)
```

**Comment by PureWeen** [comment]
@hevey this is a known issue that we are tracking internally. I'm not sure the ETA currently.

**Comment by polygonsheep** [comment]
you can add this to your csproj file

`	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	</PropertyGroup>`

when you want to build to your device. Then comment that out when you want to build for the simulator.

**Comment by gkarabin** [comment]
I am seeing this issue with VS 2022 for Mac 17.5 Preview (17.5 build 1095) on an app that I am in the process of porting from Xamarin.Forms. The workaround seems to work, but it's pretty inconvenient!
