### ISSUE TITLE
Unable to navigate to ModalPage

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#8274]
### Description

If the Presentation Mode of a ContentPage is set to Modal the Shell app does not navigate to the page.

### Steps to Reproduce

Run the repro project and click on the button. The second page will not load as it has the presentation mode of Modal. Remove the Presentation Mode and the seocnd page will load. 
[MauiApp1.zip](https://github.com/dotnet/maui/files/8966560/MauiApp1.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Use `Shell.SetNavBarIsVisible(this, false);` to hide the NavigationBar

**Comment by HobDev** [comment]
In the Maui App I am developing this is causing Exception: 

> System.InvalidOperationException: 'Current Root View cannot be null'

**Comment by AndreasReitberger** [comment]
Duplicate to: https://github.com/dotnet/maui/issues/8062#issue-1272250507
Hopefully gets fixed with the next SR 👍🏻

**Comment by devonuto** [comment]
Yep, this release has buggered everything up. All my Modal pages are no longer working.

**Comment by PureWeen** [comment]
> @PureWeen Duplicate to: [#8062 (comment)](https://github.com/dotnet/maui/issues/8062#issue-1272250507) Hopefully gets fixed with the next SR 👍🏻

Duplicate

That PR has a fairly simple workaround you can apply for now

**Comment by devonuto** [comment]
#8062 stops the error, but my modal pages don't render. Whole app just goes unresponsive
