### ISSUE TITLE
The NavBar is present in Modal page 

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#8275]
### Description

In shell app if first page is set to Modal it still have navbar.

### Steps to Reproduce

Run the repro project and see the NavBar on the Modal Page.
[MauiApp1.zip](https://github.com/dotnet/maui/files/8966631/MauiApp1.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Hide the NavBar

**Comment by PureWeen** [comment]
@HobDev The modal property only applies when you are navigating to a page not to the first page that loads. 

If you want to hide the `NavBar` then I would recommend `Shell.NavBarIsVisible="False"`
