### ISSUE TITLE
WebView not displaying Leaflet map on Android

### ISSUE THREAD

**Issue by julien-bertolini** [dotnet/maui#8276]
### Description

Leaflet map does not display at all on both Android emulator and real device.
Works fine on Windows.

Tested with Leaflet example:
https://leafletjs.com/examples/mobile/example.html

Also tested with Bing maps => works fine on Windows and Android.

### Steps to Reproduce

1. Create new Maui project
2. Add WebView control with leaflet example as Source =>
`<WebView Source="https://leafletjs.com/examples/mobile/example.html"/>`
3. Start debug on Windows => OK
4. Start debug on Android emulator => KO (white page)
![Maui_webview](https://user-images.githubusercontent.com/75125088/175286703-0289af6f-613b-489d-8f25-121b093c5cff.png)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by kristinx0211** [comment]
confirm on android, works on windows.

**Comment by julien-bertolini** [comment]
I have tested with the latest Visual Studio version 17.4 Preview 4 with net7.0, and I can confirm that it works now!
Thanks

**Comment by jsuarezruiz** [comment]
> I have tested with the latest Visual Studio version 17.4 Preview 4 with net7.0, and I can confirm that it works now!
> Thanks

Fantastic. I am going to close this issue but feel free to let us know any other issue or detail.
