### ISSUE TITLE
.net 7 preview workaround: .net 6.0.300 might not be installed when VS preview is installed, the wiki needs to be fixed.

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/maui#8288]
### Description

https://github.com/dotnet/maui/wiki/.NET-7-and-.NET-MAUI
contains a template for a global.json that references .net 6.0.300
on my pc, that version isn't installed, but some 6.0.400.preview-xxx version - that should be mentioned in the wiki.

### Steps to Reproduce

this is merely an issue for the maui wiki on github. see link. no repro.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

win11, VS 2022 17.32.0 preview 2.0

### Did you find any workaround?

manually change the global.json to 6.0.400

**Comment by jfversluis** [comment]
Was it actually not working? Because although the actual version might be wrong, the "rollForward" setting should take into account that a newer version is installed and use that. As per the Docs [here](https://docs.microsoft.com/dotnet/core/tools/global-json).

I'll add a little note regardless. Thank you!

**Comment by AdmiralSnyder** [comment]
hi @jfversluis I was surprised, too. and i read the docs like it should work, too... although the docs have errors in them - the 
 dash between z and nn seems to be missing...
maybe the problem was that allowPrerelease should have been set to true? who knows...

fyi, after i fixed the global.json, i had to repair the net7 reference in the .csproj, too... maybe this should go into that wiki article, too?
apart from these issues, i only had one further glitch where VS thought that i wanted to run the android emulator with the windows profile, and was unhappy about a recipe file missing - switching to android, running, and back, helped.

**Comment by jfversluis** [comment]
> maybe the problem was that allowPrerelease should have been set to true? who knows...

That's a good point! And also the net7 references. I'll add some about that as well. Thanks again!
