### ISSUE TITLE
The margin between the mark and content of the radio button is too narrow.

### ISSUE THREAD

**Issue by myroot** [dotnet/maui#8291]
### Description

RadioButton is TemplatedView, so some platform use DefaultTemplate to represent Radio button, but this template has some issue

1. Too narrow between radio mark and content.
2. BorderWidth not applied

This is because `DefaultTemplate` is based on Frame.

| The space between the radio mark and the content is too narrow |
|-|
|![image](https://user-images.githubusercontent.com/1029155/175428352-18d27595-796d-4d93-af72-d667e7bf3467.png)|
| BorderWidth 4 but displayed as 1 |
|![image](https://user-images.githubusercontent.com/1029155/175428429-b4c3e537-dc3d-4396-a3b3-9b0cbd0628fd.png)|

### Steps to Reproduce

1. Use RadioButton

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Not related with Platform versions

### Did you find any workaround?

Replace ControlTemplate

### Relevant log output

```shell
None
```

**Comment by legrignotin** [comment]
I also encounter this problem, even one of my customers sent me a mail about this...
Any news when a fix will be available?

**Comment by hartez** [comment]
Most likely we just need to add a margin or ColumnSpacing in the default template in RadioButton.cs. The old template from Forms probably relied on the default ColumnSpacing being 6 (or whatever it was), and now that it's zero the button/content are squished together.
