### ISSUE TITLE
Single project iOS Service Extensions

### ISSUE THREAD

**Issue by peter-bozovic** [dotnet/maui#8299]
### Description

There is currently no documentation on how to add iOS Service Extensions on MAUI and it doesn't seem to be possible in the current first release.
In Xamarin, it was needed to have separate projects for that (like for push notifications: https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications#working-with-service-extensions)
In MAUI, it would be great if this can be handled by the compiler itself and only one project could handle the main app code and the services.

### Public API Changes

Instead of adding new project, this should be handled within the new single project architecture.
It could be done by adding some attribute on the Class that will be used as a service and the build should pick this up and handle the creation of separate package if needed, etc.
Or there could be specific "Services" folder within iOS platform where different service classes could be created and transformed into service packages.

### Intended Use-Case

Needed when iOS Service Extension is necessary, like to intercept encrypted push notification and decrypt them before the display.

**Comment by emawby** [comment]
Notification Service Extensions in particular are crucial for a lot of powerful push features, such as creating categories (buttons) on demand, downloading assets (images) on demand, and other modifying content of notifications before they are displayed

**Comment by Transatranticism** [comment]
Is there any solution?
I am very confused about this matter.

**Comment by rolfbjarne** [comment]
We support extensions on iOS, and they're implemented very similarly to how they were in Xamarin.iOS: by using a separate project. The only roadblock is that we don't have any templates yet, so the simplest way to create them is likely to create a new extension using a legacy Xamarin.iOS template, and then port the project file to .NET.

See also https://github.com/dotnet/maui/discussions/3289.
