### ISSUE TITLE
.net Maui iOS BundleResource Missing / Not Working

### ISSUE THREAD

**Issue by epsmae** [dotnet/maui#8301]
### Description

For firebase services the the "GoogleService-Info.plist" file build action has to be set as "BundleResource". The build action is not available in the visual studio selecten and also does not work when setting in the project file:

```
    <ItemGroup>
      <BundleResource  Include="Platforms\iOS\GoogleService-Info.plist" />
    </ItemGroup>
```

The following errror occurs when "Firebase.Core.App.Configure()" is called:
`ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: com.firebase.core Reason: FirebaseApp.configure() could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.
Native stack trace:`

### Steps to Reproduce

1. dotnet new maui
2. Install nuget Xamarin.Firebase.iOS.CloudMessaging
3. Add GoogleService-Info.plist file to Platforms/iOS
4. Try to set build action
5. Call Firebase.Core.App.Configure(); in AppDelegate 

```
    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        Firebase.Core.App.Configure();
        return base.FinishedLaunching(application, launchOptions);
    }
```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

Yes the configuration can be set in code

```
Firebase.Core.App.Configure(new Options("1:7..4:ios:8..7", "7..4")
{
	ApiKey = "A.._W.._8.._g",
	ClientId = "...apps.googleusercontent.com",
	BundleId = "<<BUNDLE-ID>>",
	ProjectId = "<<ProjectId>>"
});
```

**Comment by PureWeen** [comment]
Moved issue to https://github.com/xamarin/xamarin-macios/issues/15347

**Comment by epsmae** [comment]
@PureWeen you moved the issue to xamarin but it works fine in xamarin the issue exists only in maui.

**Comment by Forestbrook** [comment]
@PureWeen please re-open this issue and solve it for Maui

See also issue [#7938 Build Action: BundleResource does not exist.](https://github.com/dotnet/maui/issues/7938)

**Comment by PureWeen** [comment]
@epsmae @Forestbrook I think that's just a confusion of repository names.  MAUI is just a cross platform application that's built on top of net6.0-ios and this seems like a bug with net6.0-ios which is the repository where I logged the bug.

**Comment by rricarrdo** [comment]
I believe the issue should be reopened. 

The BundleResource Build Action is available for net6.0-ios:
![image](https://user-images.githubusercontent.com/5938598/177198717-a3e500dc-b7d5-4bdf-8f85-4c1c3fdb5ea6.png)

The build action is just not available for the MAUI projects.
