### ISSUE TITLE
[Android] [Entry] Keyboard is still shown after return/done action

### ISSUE THREAD

**Issue by Kalyxt** [dotnet/maui#8302]
### Description

Keyboard should hide after return is pressed

https://user-images.githubusercontent.com/26333327/175521785-349848ce-8ff9-4758-bcce-d8c5d908da5e.mp4

### Steps to Reproduce

Create entry
Focus entry
Tap return

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

ALL

**Comment by eqmarcin** [comment]
Have the same issue on Android 11 & 6.0.400.
Works OK on iOS iPad.

**Comment by BinaryAssault** [comment]
Not a fix, but there was [this project](https://github.com/masonyc/Xamarin.KeyboardHelper) for Xamarin. Was thinking about porting it to MAUI and see if it helps as this is a very annoying issue

**Comment by PureWeen** [comment]
duplicate
https://github.com/dotnet/maui/issues/5724
