### ISSUE TITLE
[Blazor] Update templates to include a message in the app when the browser version is too old

### ISSUE THREAD

**Issue by javiercn** [dotnet/maui#8307]
Right now, when a user is using an older version of a webview, Blazor will silently fail.

We could update the template to include a snippet that checks the navigator user agent data `navigator.userAgentData` and displays a message when it detects for example an older version of chrome, maybe even providing a link to update it on the store.

That way, if the app fails to boot, at least the user has a hint to determine how to fix the problem, if we detect the installed browser is old.

By putting this on the template, developers get a hint when they use older versions of the emulator, and it is something they can remove if they choose to do so. (It's not a behavior baked in the framework).

One sample would be something like this:
```html
<p id="old-browser-version" style="display:none">The current browser version is not supported. Please upgrade to a newer browser following 
	<a href="https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DAndroid">these instructions</a></p>
<script type="text/javascript">
try {
	if (Number.parseInt(/Chrome\/(?<version>\d{2,})/.exec(navigator.userAgent).groups.version) < 80) {
		document.querySelector('#old-browser-version').setAttribute("style", "display:block");
	}
}
catch {
      }
</script>
```
Which results in something like this:
![image](https://user-images.githubusercontent.com/6995051/175551921-e141acad-5920-4d1d-aa74-37bc3c48e0de.png)

We would obviously need to tweak the above expression/sample to work for IOS too and provide appropriate instructions in that case (I don't think windows is a problem).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
