### ISSUE TITLE
Can't enable Keychain on entitlements.plist

### ISSUE THREAD

**Issue by yairp03** [dotnet/maui#8308]
### Description

The `Enable Keychain` button in the `Entitlements.plist` file doesn't work while the other buttons does

https://user-images.githubusercontent.com/45571379/175541904-40a8d959-2416-4b04-90dd-6c7ad6729cf3.mp4

### Steps to Reproduce

1. Create a File > New .NET Maui application
2. Add an `Entitlements.plist` xml file to the `iOS` project folder.
3. Open the file in an XML editor and add this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>
```
4. Open the file in the entitlements editor.
5. Go to Keychain and try to enable it (The button does not work)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

-

**Comment by PureWeen** [comment]
@yairp03 can you use the feedback tool in VS to log this issue? The feedback tool will generate additional logs that will helpful to debug this issue

**Comment by yairp03** [comment]
Reported [here](https://developercommunity.visualstudio.com/t/MAUI-Cant-enable-Keychain-on-entitlem/10080747?port=1025&fsid=146e93d6-926d-4b29-b448-53e4086af036&entry=myfeedback&ref=native&refTime=1656185722367&refUserId=55a226e1-3570-6ba9-b313-41a1b0de9207)

**Comment by jfversluis** [comment]
Perfect, thanks @yairp03 

As a workaround for now you can edit the XML directly (also see here: https://docs.microsoft.com/xamarin/ios/deploy-test/provisioning/entitlements?tabs=macos#keychain-sharing) or open the plist file with Xcode on your Mac and edit it that way.

Since it's now reported in the right place and that team should pick it up, closing it here for now. Thanks!

**Comment by yairp03** [comment]
The issue at the developer community just got closed and marked as duplicate of this issue here on github... @jfversluis
