### ISSUE TITLE
Shell Flyout is Blank When Entry is Clicked First

### ISSUE THREAD

**Issue by BinaryAssault** [dotnet/maui#8311]
### Description

If a user clicks on an entry before the flyout menu is shown, there will be no items in the flyout. You're also able to click through the flyout and edit the text. With the first example in the gif, the flyout is brought out before the entry is clicked. The second time (after app restart) the entry is clicked first and the flyout items are not present.

Android 11.0
![flyoutbug](https://user-images.githubusercontent.com/19739224/175568375-be21d96d-d54b-49f3-85a2-1f357d0910ef.gif)

Very oddly, this behavior is the polar opposite in Android 5.0
![flyoutbug5 0](https://user-images.githubusercontent.com/19739224/175570189-c2747566-519c-47cd-8783-b64e918df4a6.gif)

Functional on Windows

### Steps to Reproduce

Using the default MAUI template, 
Enable the flyout in AppShell.xaml:
``````
<Shell
Shell.FlyoutBehavior="Flyout">
``````
add an entry to MainPage.xaml
``````
<!-- Background color is not important -->
<Entry BackgroundColor="Green"/> 
``````

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android11, Android 5.0

### Did you find any workaround?

Nope

**Comment by kristinx0211** [comment]
confirm this issue repro on android 12.

**Comment by rachelkang** [comment]
@PureWeen I wonder if your recent PR fixes this too

**Comment by BinaryAssault** [comment]
@PureWeen 

The original issue of the Flyout Items disappearing is no longer an issue. 

You can no longer click through the flyout menu most of the time, but if an entry is clicked before hand, it will draw in front of the flyout menu (as shown in the original bug and below). This also improperly zooms in the selected text

See below, using latest beta on A11

![flyoutbug_latest](https://user-images.githubusercontent.com/19739224/199591956-f3a12bae-e85a-4403-9c77-4b4e5e6531f6.gif)

**Comment by BinaryAssault** [comment]
This is not fixed. Why is it closed?
