### ISSUE TITLE
Android Switch Issue (App ThemeBinding wont update)

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#8312]
### Description

If you use the switch control and give it a different color for each theme via appthemebinding, then when a theme changes on runtime the color is wont updated 

Reproduction Repo: https://github.com/DeepWorksStudios/ReproductionProjectBug_Switch

https://user-images.githubusercontent.com/59297046/175611051-e7189a0c-e05a-4f4c-94dc-40ccacf05ecc.mp4

### Steps to Reproduce

1. > Create Maui project
2. > Target Android 
3. > Add an switch 
4. > add diffrent color via apptheming
5. > add diffrent background color to page via apptheming
6. > start the emulator or the device
7. > switch theme 
8. > check if choosen color got updated

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android Version

### Did you find any workaround?

No

### Relevant log output

_No response

_

**Comment by jsuarezruiz** [comment]
Tried with net6.0 branch, the issue should be fixed in the next release
![issue-8312](https://user-images.githubusercontent.com/6755973/175936759-1fa08aa1-8572-40b0-a3c1-d592a663cf02.gif)

**Comment by DeepWorksStudios** [comment]
> Tried with net6.0 development branch, the issue should be fixed in the next release
> ![issue-8312](https://user-images.githubusercontent.com/6755973/175936759-1fa08aa1-8572-40b0-a3c1-d592a663cf02.gif)
> 
> 

Sry that I forgot to mention to make the background differ otherwise you cant reproduce it its about the switch background wich does not change accordingly. But its only visible if you got diffrent backgrounds for ech theme 

Again sry to forgot mention it

**Comment by hartez** [comment]
This is fixed for service release 3 (upcoming).
