### ISSUE TITLE
SwipeItem command not executed

### ISSUE THREAD

**Issue by christianlevesque** [dotnet/maui#8315]
### Description

When using a `<SwipeView>`, `<SwipeItem>` commands are not executed on swipe. This applies to commands with or without parameters.

[Reproduction](https://github.com/christianlevesque/maui-swipeview-command-bug)

This reproduction is based on the MAUI tutorial by James Montemagno, so there's some extra code present.

In the reproduction, the relevant code is in MauiApp1/MainPage.xaml. Lines 32-47 contain the relevant code, but they have been commented out so I could produce similar functionality with a different set of UI elements (the command is bound to an ancestor context, so I wanted to make sure I wasn't mucking up the syntax). To run the reproduction, uncomment lines 32-47 and comment out lines 49-58 (which contain the test code with different UI elements). Insert any text in the form field near the top of the app and hit the Add button. Then, swipe right on the item when it appears in the list. The code is set up to remove the swiped item from the bound collection, but the item remains.

### Steps to Reproduce

1. Create a new MAUI project
2. In MainPage.xaml, create a `<SwipeView>`.
3. Within the `<SwipeView>` from step 2, create a `<SwipeView.RightItems>` and populate it with a `<SwipeItems>` instance.
4. Within the `<SwipeItems>` instance from step 3, create a `<SwipeItem>` and give it a command.
5. Within the `<SwipeView>` and adjacent to `<SwipeView.RightItems>`, create a `<Grid>` and populate it with a `<Label>` with any text
6. Optionally set a breakpoint on the command assigned in step 4.
7. Debug the project in an Android emulator. Swipe on the label and note that the command is not executed.

Expected behavior: the bound command is executed
Observed behavior: the bound command is not executed

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API 30

### Did you find any workaround?

Use `<Button>` to execute commands on tap instead of using a `<SwipeView>`

**Comment by jsuarezruiz** [comment]
Cannot reproduce on net6.0 branch (upcoming release). I have to check the commit history to see where the issue may have been fixed.

![issue-8315](https://user-images.githubusercontent.com/6755973/175891916-36ae3ae8-87af-4bd4-98fa-f95cc7f417f8.gif)

**Comment by christianlevesque** [comment]
@jsuarezruiz when I watched your video, I realized what the issue was. It was not clear to me that the command required a click/touch event to execute - I expected that the command would be executed when the swipe was released, which is typical of other mobile UI frameworks. This is not a bug, and I apologize for the time this cost you.
