### ISSUE TITLE
App crashes with second window and WebView

### ISSUE THREAD

**Issue by Eatham532** [dotnet/maui#8323]
### Description

I have a seccond window with a webView. When I try to close the seccond window my app crashes. I did a workaround by removing the webView from the grid. But after I close the seccond window I can't use `DisplayAlert`. 

### Steps to Reproduce

1. Create two windows in Maui
2. In the first window put a button that will open the seccond window.
3. In the seccond window put a webView
4. Run the program and open the seccond window
5. Try to close the program and obsere the bug.

Expected: The seccond window closes and you can still use the first window
What happend: The application crashed.

### Version with bug
 
6.0.400-preview.22301.10

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Removed the webView before closing the window. 

```shell
MainGrid.Clear();
while (MainGrid.Children.Count > 0)
{
    await Task.Delay(500);
}
await Task.Delay(1250);

Application.Current.CloseWindow(GetParentWindow());
```

Edit: The app will crash if you use DisplayAlert after closing the window.

**Comment by kristinx0211** [comment]
@Eatham532 can you share a repro project of this issue for us to repro quickly.

**Comment by Eatham532** [comment]
Ok, Sure. I will make a repo for that now.

**Comment by Eatham532** [comment]
Got the repo: https://github.com/Eatham532/WebViewCrashRepo

**Comment by BlueHippoGithub** [comment]
The workaround works just fine when you call close on the window from code, but not when subscribing to the Destroying event of a window.
