### ISSUE TITLE
Shell Flyout Issue (App ThemeBinding wont update icon)

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#8334]
### Description

If you use the shell flyout with an icon that is supposed to change per theme. In the case where you change the theme at runtime, the icons are not updated correctly.

No matter you update them manually or via apptheming

Reproduction Repo: https://github.com/DeepWorksStudios/ReproductionProjectBug8334_Shellicon

### Steps to Reproduce

1 ,> Create Maui project
2. > Add some -flyout elements and select shell behavior for the flyout. 
3. > Give each flyout its own icon and via themebinding one variant each for dark and light.
4. > start the emulator or the device
5. > change the theme 
6. > Check if the error still occurs

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All Android Version, All Windows Verson

### Did you find any workaround?

Not really, I implemented the mvvm for the appshell and manually updated the images by binding. But it works unreliable some icons were updated some not really strange. 

**STARTUP  DARK MODE**
![WhatsApp Image 2022-06-26 at 17 48 26 (1)](https://user-images.githubusercontent.com/59297046/175822756-2fb14bc0-1fdc-4bd5-b232-03b79d96c103.jpeg)

**RUNTIME FROM DARK MODE >> LIGHT MODE**
![WhatsApp Image 2022-06-26 at 17 48 28](https://user-images.githubusercontent.com/59297046/175822620-0e3b70e6-5668-42ef-84a9-78fa9d45ffd7.jpeg)

**STARTUP  LIGHT MODE**
![WhatsApp Image 2022-06-26 at 17 51 02](https://user-images.githubusercontent.com/59297046/175822791-2ed000fa-af5e-4ab4-b089-aa9a96492a49.jpeg)

**RUNTIME FROM LIGHT MODE >> DARK MODE**

![WhatsApp Image 2022-06-26 at 17 48 26](https://user-images.githubusercontent.com/59297046/175822813-c50315ef-0165-48b4-96de-a7732331bd65.jpeg)

### Relevant log output

```shell
None
```

**Comment by DeepWorksStudios** [comment]
Whene will be this fixed?

**Comment by DeepWorksStudios** [comment]
Could you please take a look at this as soon you got some free time it would be great 
@jfversluis

**Comment by DeepWorksStudios** [comment]
@jfversluis Yes i tried it with the current version and it actually got worse.... now no icon was updated you can check the current repo i updated it to the latest .net maui version

**Comment by UkeHa** [comment]
@DeepWorksStudios - if you use FlyoutIcon instead of Icon it should work. Could you retry with the latest SDK?

**Comment by DeepWorksStudios** [comment]
> @DeepWorksStudios - if you use FlyoutIcon instead of Icon it should work. Could you retry with the latest SDK?

I will try all bugs report oit with the current sdk and give all bugs a report

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android 13.0 with below Project:
[8334.zip](https://github.com/dotnet/maui/files/11495395/8334.zip)

Start light mode -> Dark mode: The icons are not updated correctly.
![image](https://github.com/dotnet/maui/assets/97647558/007e697a-7ee9-448c-adbb-7520577f6e90)

Start dark mode -> Light mode: The icons are not updated correctly.
![image](https://github.com/dotnet/maui/assets/97647558/24fc308c-17f2-48b6-ac55-61ea20d23bd3)

**Comment by UkeHa** [comment]
@XamlTest use FlyoutIcon instead. The "Icon" Flag doesn't react to Themechanges.

![grafik](https://github.com/dotnet/maui/assets/2254304/3619d1a4-bd93-49cd-b259-be079d2ab2d1)
![grafik](https://github.com/dotnet/maui/assets/2254304/18a42da7-aeca-4b72-b6e5-d38e5593659a)

**Comment by XamlTest** [comment]
@UkeHa After update Icon to FlyoutIcon, then change the Theme in the runtime, the icons are updated correctly.
![Theme](https://github.com/dotnet/maui/assets/97647558/b51bbaf0-e2b9-445b-8f77-1c6539936c13)

**Comment by DeepWorksStudios** [comment]
I can confrim this issue got fixed

**Comment by DeepWorksStudios** [comment]
Sadly it was a mistake to close that issue since it happend again at my project i will update soon the new collected informations

**Comment by DeepWorksStudios** [comment]
My mistake i had not set the databinding mode since it somehow default seted to onetime instead of oneway
Issue got finaly resolved completly
