### ISSUE TITLE
CollectionView RemainingItemsThresholdReachedCommand Invalid

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8338]
### Description

Using the RemainingItemsThresholdReachedCommand on the CollectionView control cannot be triggered on the Windows platform, but works normally on the Android platform.
![image](https://user-images.githubusercontent.com/42528522/175870474-a82411ee-caa4-4c3b-8186-58ea51bf72a4.png)

LoadMoreCommand cannot be triggere
[MauiApp3.zip](https://github.com/dotnet/maui/files/8989037/MauiApp3.zip)
d

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/8989038/MauiApp3.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19401.0

**Comment by jballa1** [comment]
I have faced the same issue

**Comment by rachelkang** [comment]
Hi, @HenJigg - thanks for opening this issue. Please reattach the sample project as a GitHub repository so that we can investigate further!

**Comment by HenJigg** [comment]
[MauiApp3 (1).zip](https://github.com/dotnet/maui/files/8996547/MauiApp3.1.zip)

**Comment by kristinx0211** [comment]
verified repro on windows, works fine on andrroid.

**Comment by RonPeters** [comment]
I just hit this issue as well

**Comment by apavelm** [comment]
Any progress on this?

**Comment by Ruddy2007** [comment]
Also just hit this. I have been playing with MAUI for about 2 hours and so far ran into at least 5 bugs for UWP. What's going on here?

**Comment by knocte** [comment]
>  ran into at least 5 bugs for UWP

I thought MAUI's Windows backend was WinUI, not UWP?

**Comment by lucianparvu** [comment]
I have the same problem. Any Updates to this ? Any workarounds ?

**Comment by acrigney** [comment]
I have this problem as well. I thought that perhaps the RemainingItemsThreshold might need to be more than the number of items loaded initially but they don't make any difference. But apparently you need to wrap the collectionview in a refreshview?
<RefreshView Grid.Row="0" Grid.Column="0"
                     IsRefreshing="{Binding IsRefreshing}">
            <CollectionView                  
                  VerticalOptions="Start"                  
                  ItemsSource="{Binding BatchItems}"
                  SelectionMode="Single"
                  SelectionChanged="CollectionView_SelectionChanged" VerticalScrollBarVisibility="Always"
                  RemainingItemsThresholdReachedCommand="{Binding GetNextItemsCommand}"
                  RemainingItemsThreshold="50"
                  >
etc

**Comment by jaldinger** [comment]
Same problem here. Has anybody come to implement a workaround for this?

**Comment by mdbill** [comment]
Also hoping/waiting for this to get fixed

**Comment by FroggieFrog** [comment]
This is somewhat funny, because WinUI is actually the only supported UI developed by Microsoft and it is also the platform with the most quirks when using MAUI.
There really needs to be more/better support for desktop (WinUI).
