### ISSUE TITLE
[Android] Label HorizontalTextAlignment not correctly set

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#8339]
### Description

When defining a `Label` on Android, setting `HorizontalTextAlignment` to `TextAlignment.Center` has no effect.
![Screenshot_1656310605](https://user-images.githubusercontent.com/43251077/175872063-14af3a89-409b-49da-a247-55dff0df265b.png)
The `HorizontalOptions` of this `Label` object is set to `Fill` and `TextAlignment` is set to `Center` and the text should be centered. 
 

### Steps to Reproduce

Set HorizontalTextAlignment to TextAlignment.Center

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by kristinx0211** [comment]
@danielftz I am not repro your issue, see my code and result on android. If your method of reproduction is different from mine, can you share your repro project？
![image](https://user-images.githubusercontent.com/99457000/176126625-a696a61c-c42c-4238-b357-c0f9944fe3ad.png)

**Comment by NonameMissingNo** [comment]
Can't reproduce it neither in code, nor in xaml on main.
![image](https://user-images.githubusercontent.com/40233496/176132601-328ea72f-0118-40ab-8af4-b7db4a348fff.png)
![image](https://user-images.githubusercontent.com/40233496/176132627-90f758c1-4f02-4f9a-bdbc-c130f06c009c.png)
![Screenshot_2022-06-28-10-31-22-558_com companyname mauiapp1](https://user-images.githubusercontent.com/40233496/176132990-8e7b62e1-9658-4dc1-b22f-2a64861d5b1a.jpg)
