### ISSUE TITLE
Windows Shell Flyout Issue (On Scroll Exception Break)

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#8341]
### Description

If you use a shell flyout in your app with some elements and header + footer and target windows it will crash on scroll if the items dont have enough space to display all at once. The crash only happens whene you use headercolapse on scroll.

Reproduction Repo: https://github.com/DeepWorksStudios/ReproductionProjectBug8341_ShellScroll

https://user-images.githubusercontent.com/59297046/175947442-40008199-7119-4b4d-8ec7-df7251115034.mp4

### Steps to Reproduce

1. > Create Maui project
2. > Add as many flyout elements that cannot be displayed at once and choose a shell behavior for the flyout. 
3. > Add footer and header
4. > Set FlyoutHeaderBehavior="CollapseOnScroll
5. > Target windows
6. > Shrink window, so that the elements don't have enough space to be displayed
7. > Scroll and check if the error is still there 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

All Windows Version

### Did you find any workaround?

No, if you have to use the colapse attribute on scroll, it will always crash when the situation I explained earlier occurs

**Comment by DeepWorksStudios** [comment]
Is there a fix wich I can apply? Or is this really a framework bug?

**Comment by kristinx0211** [comment]
can be verified, crash when using headercolapse on scroll.
