### ISSUE TITLE
SwipeView  SwipeItemView Layout error

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8343]
### Description

Using SwipeItemView custom layout in SwipeView, the element cannot be rendered, works fine in Xamarin.Forms.

MAUI
![image](https://user-images.githubusercontent.com/42528522/175894779-51114a98-12f1-43ca-9e00-92085f4dfdc8.png)

Xamarin.Forms
![image](https://user-images.githubusercontent.com/42528522/175895139-9ce1958f-1702-42ad-9812-3417774fec55.png)

Demo:

Steps to Reproduce

### Steps to Reproduce

[MauiApp3.zip](https://github.com/dotnet/maui/files/8990048/MauiApp3.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by janseris** [comment]
Reported 2.5 months ago
https://github.com/dotnet/maui/issues/6018

**Comment by rachelkang** [comment]
Hi, @HenJigg - thank you for opening this issue. Please reattach your sample as a GitHub repository so that we may invetigate further. Thank you!

**Comment by HenJigg** [comment]
[MauiApp3.zip](https://github.com/dotnet/maui/files/8996543/MauiApp3.zip)

**Comment by kristinx0211** [comment]
using attached repro project can verified repro this issue on android 12.

**Comment by samhouts** [comment]
Duplicate of #6018
