### ISSUE TITLE
Orange horizontal strip in tabbed page with hamburger navigation

### ISSUE THREAD

**Issue by pramodhgeorge2019** [dotnet/maui#8349]
### Description

We are getting a yellow strip when we are usingTabbed page toolbar placement as bottom. Here  there are 3 tabs and 3 hamburger menus. Hamburger menus are at right top corner. We need the tabs in bottom and it is the home screen. 3 content pages are linked to hamburger. Hamburger is created natively using flyout service. 
![16563345741782928590222926800545](https://user-images.githubusercontent.com/56860010/175946973-b43b57a5-0e55-40d9-a290-3c0903c69c0c.jpg)

### Steps to Reproduce

Create a maui xamarin forms project for android and ios
Create a tabbed page as home page with 3 tabs

Create a hamburger with 3 menus which points  to corresponding simple content page

Tao on hamburger to navigate to corresponding content age

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 

### Did you find any workaround?

If you position tab positions to top color strip disappear.

**Comment by rachelkang** [comment]
Hi @pramodhgeorge2019! Could you clarify if this is a Xamarin.Forms or a .NET MAUI app? And ideally, if you could share a sample project that reproduces this issue, that would be most helpful for us in investigating this issue further.
