### ISSUE TITLE
Visual Studio 2022 17.3 Preview 2 - MAUI Comet template doesn't compile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8352]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-173-Preview-2---MAUI/10073230)._

---
/usr/local/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1112: The runtime pack for Mic
rosoft.Maui.Core.Runtime.maccatalyst was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'maccatalyst'. (NETSDK1112) (MauiTest1)

---
#### Feedback Bot on 6/16/2022, 11:14 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
For issues regarding Comet please report it on the [Comet repository](https://github.com/dotnet/comet).
