### ISSUE TITLE
MAUI Template manifest invalid - not replacing $placeholders$ and no Capabilities available.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8354]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Template-manifest-invalid---not-rep/10080708)._

---
[severity:I'm unable to use this version]
Create new MAUI App.

Go to Windows Project, app manifest
Display name is $placeholder$ and entry point is $targetentrypoint$ - these were not replaced during installation.

Also, no Capabilities available on tab.

**Comment by mattleibow** [comment]
@emanuelben not sure if this was your issue? Just want to check if this is still happening as we have fixed a few resizetizer/manifest issues over the months.
