### ISSUE TITLE
Project MAUI Title Color white and MenuItem icon color in black insteed of white

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8355]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Project-MAUI-Title-Color-white-and-MenuI/10074810)._

---
Visual Studio 2022 Version 17.3.0 Preview 2.0

When creating a Maui app, the title appears in purple blue in the background and the text in white, but the  icon appears in black, so almost invisible. Couldn't find where to edit Styles or Colors, it should be like the title, either white not black.

Sample App attached and Screenshot_1655645010.png

---
#### Feedback Bot on 6/20/2022, 01:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi there - would you mind resharing the sample (as a GitHub repository) and screenshot you've attached? I unfortunately am not seeing it, even in the original developer community ticket.

**Comment by SmartmanApps** [comment]
I'm not the person who raised this, however I've run into the same issue (and landed here) - there doesn't appear to be any way to set the colour of the Ellipsis and Hamburger menu icons in MAUI (in Xamarin they were automatically the same colour as the text in the menus). Here's a screenshot of what I'm seeing - as you can see I have my text colour set to green, but my icons are white (also the hamburger icon was in the navbar in Xamarin, but has now been moved up to the very top).
![ToolbarColour](https://user-images.githubusercontent.com/20635275/185424952-0baa6940-afca-43b2-a2aa-394519edfe88.jpg)

**Comment by nshtinkov** [comment]
I have the same problem with latest Visual Studio 17.5.1. I cannot find a way to change the color of the Ellipsis icon which is on the title bar in both Windows and Android. 
Things are slightly different for the hamburger icon as mentioned in previous comments. For me the main problem is the default Ellipsis icon in the toolbar. The problem appears in both Shell and NavigationPage.
