### ISSUE TITLE
MAUI on VS2022 (community preview) 17.3.0 preview 2.0 Content Page Title 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8356]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-on-VS2022-community-preview-173/10073301)._

---
After update my settings I restart the application calling :

        App.Current.MainPage = new AppShell();

All works fine but : 
When running in windows, Pages takes all place in main window. 
So title of content pages covers first line of all application.

I included this behaviour in a .png attachment.

In android emulators and phone deploys works fine!

Thank you

---
#### Feedback Bot on 6/16/2022, 11:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I'm afraid I don't understand what you mean. Also I don't see the mentioned PNG attachement. Would you maybe be able to provide some more information? Ideally a reproduction project that you provide through a GitHub repository so we can have a look. Thanks!
