### ISSUE TITLE
I cannot run a new MAUI blazor project on windows.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8357]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cannot-run-a-new-MAUI-blazor-project-o/10072018)._

---

I updated my VS 2022 preview to latest version, created a .net Blazor Maui project and I get  this error when I try to run the empty project on windows.

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0800: The required framework "C:\Users\Administrator\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error 0x8000000B. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.	MauiApp1			

---
#### Feedback Bot on 6/15/2022, 11:09 PM: 

(private comment, text removed)
#### ustundag on 6/16/2022, 04:03 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PirasathLuxchumykanthan** [comment]
well for me it work on windonws

**Comment by jfversluis** [comment]
Looks like something on the environment that might be locked down or network traffic that is blocked. Make sure to check with the administrator of the machine if anything is locked down. Searching for the error codes that are mentioned gives me some results. Unfortunately this doesn't seem to be something that is caused by .NET MAUI.

Please try another machine and see if it works there. Let us know if it also doesn't work on another machine and if possible provide some more detail or maybe even the msix in question? Thanks!

**Comment by skaryshev** [comment]
I am having exactly the same problem after a clean install of Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 2.0 
on Microsoft Windows Server 2022 10.0.20348 Build 20348
targeting net6.0-windows10.0.19041.0 or net6.0-windows10.0.20348.0
with dotnet --version
6.0.400-preview.22301.10
dotnet --list-sdks
6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

Please note the latest windowsappsdk nuget is 1.1.1 when win10-x64\Microsoft.WindowsAppRuntime.1.1.msix is frying to install the framework from windowsappsdk.1.1.0

**Comment by skaryshev** [comment]
Visual Studio output of deploy of new MauiApp1 targeting net6.0-windows10.0.19041.0 

Creating a new clean layout...
Copying files: Total 111 mb to layout...
Checking whether required frameworks are installed...
Framework: Microsoft.WindowsAppRuntime.1.1/X64, app package version 1000.516.2156.0 is not currently installed.
Installing missing frameworks...
DEP0800: The required framework "C:\Users\Administrator\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error 0x8000000B. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
2>Deployment of the application to the target device failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by skaryshev** [comment]
Update to Preview 3 did not remediate the issue
```
Framework: Microsoft.WindowsAppRuntime.1.1/X64, app package version 1001.524.1918.0 is not currently installed.
...
Installing missing frameworks...
DEP0800: The required framework "C:\Users\Administrator\.nuget\packages\microsoft.windowsappsdk\1.1.1\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. 
[0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1001.524.1918.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error 0x8000000B. 
See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
	DeploymentSucceeded = False
	DeploymentError = Err_Deploy_SDKInstall
	DeploymentUserError = False
	DeploymentHRESULT = -2147009287
	HasSharedCode = False
	SDKFileName = 
	Target.Id = 256
	ProjectGuid = {c0036242-b290-4a61-81d6-8df21eb34e7e}
	Project.TargetPlatformVersion = 31.0
Deleting file "vs.appxrecipe" from layout...
DeployAsync: END (Failure, 0:00:01.553)
Deploy: END (Failure, 0:00:01.631)
```
The issue has very little to do with MAUI. Should it be moved to Windows App SDK / tooling project?

**Comment by laz-oscore** [comment]
I have the same issue

**Comment by RodDaSilvaWCO** [comment]
I have the same issue.  Have the **MAUI Templates** for **Visual Studio 2022 Preview** been tested on **Windows Server 2022**?

**Comment by skaryshev** [comment]
Updating to Preview 6 did not help :(

**Comment by skaryshev** [comment]
Works fine after installing VS 17.3 "current". I think the issue may be closed.

**Comment by RodDaSilvaWCO** [comment]
> I have the same issue. Have the **MAUI Templates** for **Visual Studio 2022 Preview** been tested on **Windows Server 2022**?

Can anyone from Microsoft confirm (or deny) whether Visual Studio 2022 Preview's MAUI templates have been tested on Windows Server 2022 (with desktop experience)?

**Comment by mprogers** [comment]
> > I have the same issue. Have the **MAUI Templates** for **Visual Studio 2022 Preview** been tested on **Windows Server 2022**?
> 
> Can anyone from Microsoft confirm (or deny) whether Visual Studio 2022 Preview's MAUI templates have been tested on Windows Server 2022 (with desktop experience)?

Funny you should mention this ... I was trying this on Windows Server 2022 (with desktop experience) and got that exact same error just a moment ago. But I'm running it on a VM, I dunno if that's an issue.

All the VMs I have access to are running Windows Server of some vintage --  have you had luck with earlier versions, like 2019 or 2016?

**Comment by RodDaSilvaWCO** [comment]
I initially installed the Visual Studio 2022 Preview on Windows Server 2016 (also on a VM) and got the error.  After some research I saw the requirement was for Windows 10+ equivalent OS, so I decided to upgrade the Server to Windows Server 2022, and I still get the error.

I have also created a VM running Windows 11 and was able to successfully install the VS 2022 Preview and was able to build and run a MAUI app - so technically a VM environment doesn't appear to be the problem.  However, its all but impossible to develop that way for the other platforms since (for example) I can't get the Android Emulator to load the MAUI app as there appears to be no way to turn on hardware acceleration in a virtualized environment, and my attempts to try this with out hardware acceleration are futile (i.e.; too slow).   So I am starting to wonder if developing for MAUI means buying a new computer...

**Comment by mprogers** [comment]
Thanks for the info -- I guess I will give up on Windows Server and just stick with Windows 11. I was able to get that to work just fine (at least making Windows OS apps, which is what I've been asked to teach, rather than the mobile stuff -- that I'm doing in a different course).

**Comment by jfversluis** [comment]
Hey everyone, thanks for all the investigation here! I would be very curious what the reason is that it doesn't work on Windows Server... But I think for now we can indeed establish that using Windows 10 or 11 is the way to go. This also aligns with out official support, so I don't think there is much for us to do here at this point.

Thank you!

**Comment by ltemimi** [comment]
in my company we have to use windows servers for development are you saying my company cannot use dot net MAUI?

**Comment by jfversluis** [comment]
@ltemimi I will check with others and raise this. To be honest, it seems a bit weird to me to run Windows Server as something you would develop on. It's primary use is to run on servers, not as a daily driver for software development. You can always still spin up a VM with Windows 10 or 11 and develop through there.

**Comment by ltemimi** [comment]
I know unfortunately IT Rules are IT Rules. I think it has to do with testing in the environment you are going to deploy to. Thanks.
I think if Microsoft releases a statement that Dot net MAUI does not support windows servers for development then I think we will be allowed to use windows 10 or 11.

**Comment by ltemimi** [comment]
Great thanks very much for the help

**Comment by electroly** [comment]
Hi @jfversluis, the visualstudio.com link you've provided repeatedly links right back to this GitHub issue and tells users to comment here. The issue remains; it appears impossible to develop MAUI applications with Visual Studio on Windows Server 2022. Both of those things being the case, should this issue be re-opened? This is NOT fixed.

Running in AWS and Azure are the use cases here. Here are two examples that demonstrate that this is an officially Microsoft-supported use case:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/using-visual-studio-vm
https://aws.amazon.com/blogs/aws/new-run-visual-studio-software-on-amazon-ec2-with-user-based-license-model/

**Comment by davidortinau** [comment]
Seems this could be related to https://github.com/microsoft/WindowsAppSDK/issues/2829#issuecomment-1208551684 which states there's a bug in WinAppSDK/Windows Server 2022 that results in the SDK being unable to install.

**Comment by mattleibow** [comment]
The OS has been patched in KB5018485 and should be working. If not, please leave a comment on https://github.com/microsoft/WindowsAppSDK/issues/2829
