### ISSUE TITLE
Failed to launch android application maui with the provided template project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Failed-to-launch-android-application-mau/10058052)._

---
[severity:I'm unable to use this version]
Failed to launch android application maui with the provided template project
I am using s21 ultra phone and i can debug xamarin application just fine.
I wanted to try out maui after the GA was announced. The application runs fine if I dont start in the debugging mode.
I do not know where to look for the logs to see where the error is coming from.

---
#### Feedback Bot on 5/31/2022, 07:15 PM: 

(private comment, text removed)
#### Qiana Jiao (CSI Interfusion Inc) [MSFT] on 6/1/2022, 08:31 PM: 

(private comment, text removed)
#### Shehroze Malik on 6/6/2022, 00:34 AM: 

(private comment, text removed)
#### Feedback Bot on 6/9/2022, 00:09 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi there, thank you for opening this issue. To locate and attach your build logs, please find the instructions at https://docs.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2022.

If you are able to share your project or provide a sample project that reproduces the issue (in the form of a GitHub repository), that would also help us investigate further!
