### ISSUE TITLE
`RadialGradientBrush` with `Center` rendering is broken on Windows

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#8361]
### Description

I have this regular `Border` with a `RadialGradientBrush` as a background. I have moved the `Center `of the brush to be in the bottom right. As you can see in the screenshots this is fine on iOS and Android but broken on Windows.

```
<Border HorizontalOptions="Fill" HeightRequest="250" BackgroundColor="Transparent" StrokeThickness="0">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="20" />
    </Border.StrokeShape>
    <Border.Background>
        <RadialGradientBrush Center="0.9,0.9">
            <GradientStop Offset="0.1" Color="#F79256" />
            <GradientStop Offset="0.3"  Color="#7DCFB6" />
            <GradientStop Offset="0.6"  Color="#1D4E89" />
            <GradientStop Offset="1.0" Color="#18181C" />
        </RadialGradientBrush>
    </Border.Background>
</Border>
```

![Untitled-1](https://user-images.githubusercontent.com/3210391/175999087-b77c7516-cad1-4a49-96ae-783ae93744e7.png)

repro is here:
https://github.com/nor0x/MauiFails

existing stuff for reference
https://github.com/dotnet/maui/issues/4040
https://github.com/dotnet/maui/pull/5494

### Steps to Reproduce

1. Create new MAUI app
2. Add Border to Layout
3. set RadialGradientBrush as Background

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

**Comment by kristinx0211** [comment]
verified repro on windows with above project.

**Comment by rmarinho** [comment]
@nor0x  we should close when we merge the issue

**Comment by jsuarezruiz** [comment]
> thank you @jsuarezruiz
> 
> i'm closing this issue now

Yeah, as Rui said, we will close it after validate and merge the PR. Anyway, thanks for all your feedback!
