### ISSUE TITLE
Slider Thumb Wrong in iOS, OK on Windows

### ISSUE THREAD

**Issue by plattski** [dotnet/maui#8364]
Dave Platt here. You might remember me from my MS Press book, Introducing Microsoft .NET. I've been working with MAUI, and I think I've found a bug in the slider control. My example code is at https://drive.google.com/file/d/1mKsG7d3yeliv0k2Lp5BD_jtUwTTXCjdA 

I want to replace the standard slider thumb, which I do via the ThumbImageSource property on the Slider element in Xaml. Instead of the default blue circle, I've provided a red square. It works fine on Windows, see the short video at https://photos.app.goo.gl/ujTYUUNogYbw1wDr5 . 

https://user-images.githubusercontent.com/1096616/223789724-289d21ef-3df2-4bf6-a84f-9070eae3c4be.mp4

However, when I run the exact same project on my iPad, two bad things happen. First, when I'm dragging the thumb, the program shows the original default blue circle, instead of the red square with which I've replaced it. It shows the correct red square image after I release the thumb, but not during the drag operation. See the short video at https://photos.app.goo.gl/pF49TcyTJPDcJCXB9 . 

https://user-images.githubusercontent.com/1096616/223789982-ffad0a10-ead6-431b-9fee-f8d448bd7aa1.mp4

That would confuse the heck out of my users. I haven't found a workaround for this one. My iPad version information is in the photo at https://photos.app.goo.gl/YmFssg7hVCWhwi6V9 .

![PXL_20220627_155629941 MP](https://user-images.githubusercontent.com/1096616/223790006-ed0c6684-d48a-49d0-98d5-9628cd8a1bac.jpg)

Second, the thumb image is scaled incorrectly. Compare the size of the red square in each video. The Windows one is about right. In the iPad one, the red square is way too large, perhaps twice the size of the friendly waving bot image. I could conceivably hack together a workaround for this, with different-sized platform dependent images, but I'm sure you'll agree that's not ideal.  

I hope this helps you improve your MAUI product. Sincerely yours, David S. Platt

**Comment by kristinx0211** [comment]
verified repro on Mac as described above.
https://user-images.githubusercontent.com/99457000/177075203-38c5101a-048c-42c1-b169-899a38dfbe35.mov

**Comment by plattski** [comment]
I checked this on Android as well. You can see the results at https://photos.app.goo.gl/PfDivgWtQVVAhTfw5 . The replacement slider thumb was used throughout the drag operation. This is correct behavior that iOS does not exhibit.

However, the slider thumb was displayed as much, much, too large, perhaps twice the size of the friendly waving bot. iOS also exhibits this incorrect behavior.  

Windows handles both situations correctly, as shown in preceding videos. Hope this helps.

**Comment by mattleibow** [comment]
I think this is because your image is very large?

If it is a large image file, then maybe try setting the base size on the image in the csproj to the size you want:

```xml
<ItemGroup>
    <MauiImage Update="Resources\Images\red.png" BaseSize="64,64" />
</ItemGroup>
```

Also, are you able to upload the code as a github repo?

**Comment by mattleibow** [comment]
Might also be useful to have the version of maui/VS that you are on.
