### ISSUE TITLE
Visibility binding not resize and rearrange items inside a vertical stack layout/grid/stack layout

### ISSUE THREAD

**Issue by Awesomer9561** [dotnet/maui#8365]
### Description

Hi,
I am trying to bind visibility for control in my app but it is not resizing and whenever the control is invisible it is leaving a blank area.

### Steps to Reproduce
<VerticalStackLayout>
        <Label 
            Text="Welcome to .NET MAUI!"
            VerticalOptions="Center" 
            HorizontalOptions="Center" />
        <BoxView BackgroundColor="Red" Grid.Row="1" HeightRequest="80"
                 IsVisible="{Binding CanBeSeen}"/>

        <Button Text="Toggle" Command="{Binding ToggleVisibilityCommand}" Grid.Row="2"/>
    </VerticalStackLayout>
### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android API 30, 31

**Comment by rachelkang** [comment]
Hi, @Awesomer9561 - thanks for opening this issue. Could you please provide a bit more information about your scenario? If you can share the code you have in `ToggleVisibilityCommand` as well as any screenshots showing the behavior your are seeing vs. anticipating, that would be super helpful. Ideally, if you can share a repro project with us in the form of a GitHub erpo, that would help us to investigate this issue most efficiently. Thank you!

**Comment by Awesomer9561** [comment]
> 

Hi, @rachelkang  I have attached a repo. Please have a look at it.
[Visibility.zip](https://github.com/dotnet/maui/files/8995408/Visibility.zip)
.

**Comment by HobDev** [comment]
Duplicate of https://github.com/dotnet/maui/issues/7727

**Comment by Awesomer9561** [comment]
Closing as duplicate.
