### ISSUE TITLE
CollectionView is incompatible on Shell tabbar pages on Android

### ISSUE THREAD

**Issue by sheharyarshahid** [dotnet/maui#8366]
### Description

On the shell tab bar, I have two pages. Each page consists of Multiple collection views which get data from ViewModel. Each collection view also contains some layout settings, like vertical and horizontal options and ItemTemplate which contains Frames, Images and Labels.
On app run, homepage loads fine with its collection view but when changing page from tabbar to another page, it throws an exception Microsoft.Maui.Platform.ToPlatformException.

Dotnet version: 6.0.400-preview.22301.10
Platform OS: Windows
Visual Studio 2022 Preview: 17.3.0 Preview 2.0
Android: 11

Note: This issue is only for Android. Works fine on Windows.

![exception](https://user-images.githubusercontent.com/13855833/176021451-390f081c-0fc1-4fd9-bb47-8036effdb7fa.jpg)

### Steps to Reproduce

1. Create File > New .NET MAUI app
2. Add a shell and add minimum 2 tab bar pages
3. Each page should contain CollectionView and ItemTemplate
4. Run the android app and jump from one shell tab page to another.
5. It will throw the following exception:
Microsoft.Maui.Platform.ToPlatformException: 'Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible'

Expected outcome: Should navigate to the second tab bar page
Actual outcome: Throws exception (Microsoft.Maui.Platform.ToPlatformException)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?
Temp workaround. Remove the `EmptyView `property from a CollectionView on a page that is navigated from another page using Shell Tabbar.

_No response_

### Relevant log output

```shell
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.AppCompatResources.dll
Loaded assembly: /data/data/com.companyname.yourgreenworld/files/.__override__/Xamarin.AndroidX.AppCompat.AppCompatResources.dll [External]
Thread started: <Thread Pool> #9
[Choreographer] Skipped 40 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1101ms; Flags=0, IntendedVsync=29265937574021, Vsync=29266370907337, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=29266371150700, AnimationStart=29266371168300, PerformTraversalsStart=29266371385500, DrawStart=29266988808100, SyncQueued=29267037359300, SyncStart=29267037817400, IssueDrawCommandsStart=29267037952700, SwapBuffers=29267038900800, FrameCompleted=29267039979800, DequeueBufferDuration=173600, QueueBufferDuration=422400, GpuCompleted=1468878815232, 
[monodroid-assembly] open_from_bundles: failed to load assembly System.IO.Compression.dll
Loaded assembly: /data/data/com.companyname.yourgreenworld/files/.__override__/System.IO.Compression.dll [External]
[OpenGLRenderer] Davey! duration=745ms; Flags=0, IntendedVsync=29266370899889, Vsync=29267037566529, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=29267040398900, AnimationStart=29267040999900, PerformTraversalsStart=29267065570300, DrawStart=29267066199300, SyncQueued=29267068859900, SyncStart=29267069435500, IssueDrawCommandsStart=29267069795700, SwapBuffers=29267115793900, FrameCompleted=29267117266000, DequeueBufferDuration=260900, QueueBufferDuration=481800, GpuCompleted=1623497637888, 
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.yourgreenworld/files/.__override__/System.Runtime.Intrinsics.dll [External]
Thread started: <Thread Pool> #10
[.yourgreenworl] Explicit concurrent copying GC freed 4854(239KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6069KB/11MB, paused 753us total 10.117ms
Thread started: <Thread Pool> #11
Thread finished: <Thread Pool> #9
The thread 0x9 has exited with code 0 (0x0).
[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
**Microsoft.Maui.Platform.ToPlatformException:** 'Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible'

[.yourgreenworl] Explicit concurrent copying GC freed 10441(743KB) AllocSpace objects, 21(2436KB) LOS objects, 49% free, 6180KB/12MB, paused 281us total 9.308ms
```

**Comment by kristinx0211** [comment]
@sheharyarshahid can you share the repro project please?
