### ISSUE TITLE
[MacCatalyst] Content in ScrollView does not resize when the Window resize.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#8370]
### Description

https://user-images.githubusercontent.com/898335/176067235-378d21a5-8ba0-4d55-a5a6-88660ed75929.mov

If you have content within a ScrollView, it does not resize when you resize the Window. It does work on Android, WinUI, and iOS.

### Steps to Reproduce

1. Create content within a scrollview
2. Resize it.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

macOS

### Affected platform versions

MacCatalyst

**Comment by PureWeen** [comment]
Closing in favor of partner issue for tracking https://github.com/dotnet/maui/issues/9349

**Comment by samhouts** [comment]
Duplicate of #9349
