### ISSUE TITLE
Add guide how to connect to any service hosted at localhost from real device connected through Visual Studio

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#8379]
### Description

For MAUI run on Windows, it is easy to access localhost, it's simply localhost.
For MAUI run on Android emulator, simply replace localhost with 10.0.2.2
This is from this guide: https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/connect-to-local-web-services and it works fine.

For SQL Server Express used from emulator there is a nice tutorial here which works (the most important part is to open TCP/IP connections in the server config) _(however the new `Microsoft.Sql.Data` client does not work on Android or works only for newer Android (depending on the version))_:
https://www.youtube.com/watch?v=xNmIdFjXzl4

But for Android device which runs MAUI application attached via Visual Studio debugger? 10.0.2.2 doesn't work.

How to please connect to a service hosted on localhost? 
Not only HTTP but also TDS or any other protocol.

There is no guide for Android device afaik. But testing must be done also on a real device! 

Thank you.

### Public API Changes

Add documentation on how to access localhost from Android device when running via Visual Studio (both Debug and _**Release**_).

### Intended Use-Case

Simulating production environment with MAUI app,

### Possible workaround
- to connect localhost to Android device, if these are on the same network, a **_temporary_** private IP can be exposed by localhost and ports with applications open. However this is not a robust solution and router can frequently change the private IP addresses assigned to devices (having a static private IP address in a network is not guaranteed)

> VS bug [#1745020](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1745020)

**Comment by Eilon** [comment]
@janseris how is the Android device connected to the development machine? Is it via USB, WiFi, or something else? I wonder if this might affect the guidance?

**Comment by Eilon** [comment]
And I wonder what happens if you use the machine's actual IP address on whatever network it's on. Does that work?

**Comment by janseris** [comment]
> @janseris how is the Android device connected to the development machine? Is it via USB, WiFi, or something else? I wonder if this might affect the guidance?

I am using USB connection.
I saw some options like remote device access through a paid service over the internet but these are hard to set up.

**Comment by KazysNoobiys** [comment]
I use https://github.com/jocull/SharpProxy to connect a real device to a server on the local network.

**Comment by mattleibow** [comment]
Does 10.0.2.2 still not work in an android app? this should work on any android emulator - regardless of framework. Maybe there was an issue with the runtime and general communication.

**Comment by Alexgoon** [comment]
> Does 10.0.2.2 still not work in an android app? this should work on any android emulator - regardless of framework. Maybe there was an issue with the runtime and general communication.

I think the point is that "10.0.2.2" doesn't work when an Android device is used through USB debugging, not when an emulator is used. It seems that I have the same issue.

**Comment by janseris** [comment]
> Does 10.0.2.2 still not work in an android app? this should work on any android emulator - regardless of framework. Maybe there was an issue with the runtime and general communication.

We need to develop and test on real devices on daily basis as well. Emulator is not sufficient.

**Comment by mattleibow** [comment]
This is staying to feel like a new feature for the ide rather than maui. Maybe you can open this on the developer community site?

This repo is more for issues of features relating to the sdk itself. And also those folks won't be looking here as they are all internal.

**Comment by janseris** [comment]
> This is staying to feel like a new feature for the ide rather than maui. Maybe you can open this on the developer community site?
> 
> This repo is more for issues of features relating to the sdk itself. And also those folks won't be looking here as they are all internal.

Are you sure it is not more a documentation issue? The article is where the official MAUI docs point to.

**Comment by jfversluis** [comment]
I think there is two parts here: if you don't think the docs are sufficient at this point, open something on that repo. I see already something is linked right above here, so I guess something is in the works. You can add to that issue if you have any input.

If you have ideas around how to make this better in Visual Studio and tooling, please report it through the instructions in the earlier comment about this.

Either way, there is nothing much that we can do about it from the .NET MAUI SDK side.

Thanks!
