### ISSUE TITLE
CollectionView with GridItemsLayout: Issues when changing Span

### ISSUE THREAD

**Issue by Forestbrook** [dotnet/maui#8387]
### Description

I have a CollectionView with a GridItemsLayout. Depending on the available size I want to show more (landscape view) or less (portrait view) items on a row.

In the SizeChanged event I compute and set the right Span.

* **On iOS**: crash with NullReferenceException: CollectionView is null in GridViewLayout.HandlePropertyChanged().
* **On Windows**: Number of items on the row is NOT changed.
* **On Android**: When I add a short delay before changing Span it seems to work correct.

### Steps to Reproduce

See example project [MauiGridItemsLayoutChangeSpanIssue](https://github.com/Forestbrook/MauiGridItemsLayoutChangeSpanIssue)

In the AppShell Flyout you can select two views:
* CollectionView with workaround and
* CollectionView with bug

Rotate the phone/tablet to see the number of items on a row change.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

iOS 15.5, Windows 10.0.19044

### Did you find any workaround?

For iOS I found a workaround by adding a check for CollectionView==null in GridViewLayout.HandlePropertyChanged(). See ```GridViewLayoutExt``` in the example project. This works, because HandlePropertyChanged() for the Span property is called again when CollectionView is not null anymore, which is kinda weird.

For Windows I did not look for a workaround yet.

**Comment by kristinx0211** [comment]
verified repro on IOS15.4 and windows with above project.

**Comment by BenderNK** [comment]
Provided work-around does not work in Windows.
> A workaround that worked for me is to create a new GridItemsLayout with the new Span value.


Specifically this:
```
var newSpanValue = 5
MyCollectionView.ItemsLayout = new GridItemsLayout(span: newSpanValue, ItemsLayoutOrientation.Vertical);
```

Neither this:
```
if (MyCollectionView.ItemsLayout is GridItemsLayout gridItemsLayout)
{
    var newSpanValue = 5
    gridItemsLayout.Span = newSpanValue ;
}
```

Nothing ever happens. Original span value that was provided in the XAML is only being respected.

**Comment by hartez** [comment]
See also: #10144.
