### ISSUE TITLE
Binding to color properties does not work

### ISSUE THREAD

**Issue by hprez21** [dotnet/maui#8390]
### Description

The color binding through Bindings does not work, I tried with the BoxView control with the Color property and the RoundRectangle control with the Fill property, both have the same problem.

### Steps to Reproduce

1.- Create a new project with the ".NET MAUI APP" template.
2.- Remove default content.
3.- In the XAML file, add StackLayout as the main layout:
```
    <StackLayout>
        <BoxView
        HeightRequest="200"
        WidthRequest="200"
        Color="{Binding .}" />
    </StackLayout>
```
4.- In the code behind, assign a color to the BindingContext:
```
	public MainPage()
	{
		InitializeComponent();
		BindingContext = "#000000";
	}
```
5.- Test the application

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10, Windows 19044.1766

### Did you find any workaround?

Assigning the color with a value directly works (without the binding), however, in a CollectionView this is not feasible when you have multiple colors to be applied.

**Comment by manuelelucchi** [comment]
I found this issue as well, my workaround was a string to color converter

**Comment by janseris** [comment]
I think that it works in reverse in xaml because color has string constructor which is silently called but it doesn't work the other way around and that is why you need a converter

**Comment by kristinx0211** [comment]
@hprez21 you can binding data like this, hope can help you.
XAML:
```
    <StackLayout>
        <BoxView
        HeightRequest="200"
        WidthRequest="200"
        Color="{Binding color}" />
    </StackLayout>
```
.cs
```
public partial class MainPage : ContentPage
{
    private Color _MyColor;

    public Color color
    {
        get { return _MyColor; }
        set { _MyColor = value; }
    }

    public MainPage()
	{
        
        InitializeComponent();
        color = Colors.Orange;
        BindingContext= this;
    }
	
}
```

**Comment by hprez21** [comment]
> @hprez21 you can binding data like this, hope can help you. XAML:
> 
> ```
>     <StackLayout>
>         <BoxView
>         HeightRequest="200"
>         WidthRequest="200"
>         Color="{Binding color}" />
>     </StackLayout>
> ```
> 
> .cs
> 
> ```
> public partial class MainPage : ContentPage
> {
>     private Color _MyColor;
> 
>     public Color color
>     {
>         get { return _MyColor; }
>         set { _MyColor = value; }
>     }
> 
>     public MainPage()
> 	{
>         
>         InitializeComponent();
>         color = Colors.Orange;
>         BindingContext= this;
>     }
> 	
> }
> ```
> 
> OR the workaround of [manuelelucchi](https://github.com/manuelelucchi) is fine.

@kristinx0211 Thanks for the suggestion! The problem is because I am adding a color of a gradient to each element that is part of the CollectionView, so I can not use the name of the color, but I need to use the **Hexadecimal** code. I made the example as simple as possible to quickly understand what the problem was, however, my problem goes one step further.

Greetings!

**Comment by ShiiikK** [comment]
Hope this get fixed soon.
I need it for my ListView to display danger levels, i dont want to use pictures for this simple setting.
