### ISSUE TITLE
.NET MAUI Blazor mouse events not firing

### ISSUE THREAD

**Issue by dudchenko610** [dotnet/maui#8393]
### Description

When we set onmousedown or onmousemove listeners corresponding events are not fired on Windows platform in .NET MAUI Blazor although it works in regular Blazor WebAssembly.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add any element to razor file like so: `<div></div>`
3. Attach onmousedown event listener like so `<div @onmousedown='()=>{ Console.WriteLine("Event fired"); }'></div>` or  `<div @onmousemouve='()=>{ Console.WriteLine("Event fired"); }'></div>`
4. Try to click the item or hover the item

Expected outcome: events were triggered
Actual outcome: events weren't triggered

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows SDK

### Did you find any workaround?

I tried to attach these event listeners via js, and it works but unfortunately I wasn't able to return event data back to C# via DotNetObjectReference

**Comment by TanayParikh** [comment]
> are not fired on Windows platform

Thanks for reporting @dudchenko610. Did you happen to try this out on any other platform (iOS, Android, MacOS)? Wonder if this is a Blazor .NET MAUI issue or Windows specific.

**Comment by kristinx0211** [comment]
verified repro on windows, events can be triggered on android. but not on windows. repro project:
[MauiApp18.zip](https://github.com/dotnet/maui/files/9007548/MauiApp18.zip)

**Comment by janseris** [comment]
This must have worked before. I was doing html5 blazor canvas experiments.

**Comment by KSemenenko** [comment]
@TanayParikh we will check it on iOS and Android, we finally setup our CI/CD :)

**Comment by dudchenko610** [comment]
> > are not fired on Windows platform
> 
> Thanks for reporting @dudchenko610. Did you happen to try this out on any other platform (iOS, Android, MacOS)? Wonder if this is a Blazor .NET MAUI issue or Windows specific.

@TanayParikh, I'm not sure mouse events should work on other platforms but I'm sure they should on Windows. I tried to use them in regular Blazor WebAssembly and it is okay. It seems to me like it is Windows specific issue

**Comment by mkArtakMSFT** [comment]
@KSemenenko did you get to try this out? Any findings you can share?

**Comment by KSemenenko** [comment]
@mkArtakMSFT ios and Android are fine. It’s just windows issue

**Comment by MackinnonBuck** [comment]
The repro project is using `Console.WriteLine()`, which doesn't currently output to the browser console (see [this](https://github.com/dotnet/maui/discussions/6091#discussioncomment-2565073)).

If I change it to do something else, like display an alert via JS interop, the callbacks appear to work fine.

@dudchenko610 @KSemenenko Could you try something like:
```razor
<div @onmousedown='() => JS.InvokeVoidAsync("alert", "Alert from onmousedown")'>
    Click the text!
</div>
```
and see if an alert pops up when you click the text? Thanks!

**Comment by MackinnonBuck** [comment]
Going to close this out unless we get additional feedback that this is still an bug.
