### ISSUE TITLE
Labels added in code are not displayed on Android

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#8395]
### Description

This project dynamically adds and removes `Label`s from/to an existing `StackLayout` as indicators of action results (action = DB call).

When each action finishes, a new label is added into the `StackLayout` container.

On Windows, the labels are displayed.
![image](https://user-images.githubusercontent.com/64279914/176287946-76348b22-fc4e-4398-b6fc-91dcfdaee0f4.png)

![image](https://user-images.githubusercontent.com/64279914/176289372-8cef8e70-8ff6-4dc6-acb3-09715d3558ae.png)

On Android, there are no labels displayed (or they are empty? I don't know)

This is supposed to be displayed:
![image](https://user-images.githubusercontent.com/64279914/176289136-1a67ab1c-0af8-450d-91c1-2f38dd3d212b.png)
Actual display (nothing):
![image](https://user-images.githubusercontent.com/64279914/176289174-ec7c9240-04de-4506-a78e-c465954fc5a4.png)

I have added a debug print to show expected label contents in the Debug Output window.

### Steps to Reproduce

Run the following project on Android:

https://github.com/janseris/MAUI_SQLServer_Test/commit/98b96c03d6e3f3ce09a0e4f00254d44bb9cc28d3

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, Android 5

**Comment by markadrake** [comment]
Coming here after launching a new .NET Maui app in the Android Simulator and noticing that the button label does not resize to fit the text. So although the button text is indeed changed to "clicked x times", the button does not resize to fit the text. 

I can only assume all of these rendering issues are related.

**Comment by janseris** [comment]
Update, see this version of the sample project:

- it is possible to get the labels to appear by writing into the Editor control
  - if the Labels should be there, they appear after writing into the Editor control (DB calls must be executed so that the Labels are supposed to show because they show the results of these DB calls)

**Comment by hartez** [comment]
This should be fixed as of service release 3.
