### ISSUE TITLE
[Enhancement] Converter tools from other frameworks (MAUI Desing guide)

### ISSUE THREAD

**Issue by tomasfabian** [dotnet/maui#84]
I know it would be a difficult task, but it would be nice to have converter tools for porting from older or different environments to MAUI

**Proposal:**
WPF/UWP/WinForms => WinUI 3 converter (or direct converters to MAUI)
 
WinUI 3, Xamarin.Forms, Blazor, etc. => MAUI converter

- I assume that WinUI 3 will have at least to some extent a different XAML dialect.

**Use case:**
Otherwise all teams in the world will have to do it on their own (not DRYish)

**Edit:**
It could be also a good design guide for MAUI designers to realize how are these similar platforms diverging and standardize some of the commonalities based on a ConverterBase.

**Comment by mrwcjoughin** [comment]
if you watch this full "Journey to .NET" video from build (the full thing wasn't presented live but only released after):
https://channel9.msdn.com/Events/Build/2020/BOD106?ocid=AID3012654&WT.mc_id=Build2020_pmmsocialblog <https://channel9.msdn.com/Events/Build/2020/BOD106?ocid=AID3012654&WT.mc_id=Build2020_pmmsocialblog>

It says that there will be a convertor at least to go from Xamarin.Forms to MAUI - including code name space changes

**Comment by tomasfabian** [comment]
@mrwcjoughin thx for sharing I will watch it. 
Converters from WPF and others will be much needed, too. Xamarin.Forms is more obvious to get a converter since it is going to evolve into MAUI, but the other platforms should be considered IMO, too. thx

**Comment by mrwcjoughin** [comment]
100% - the more convertors the better
