### ISSUE TITLE
Application.Current.MainPage is null on application launch in windows

### ISSUE THREAD

**Issue by PaulAndersonS** [dotnet/maui#8403]
### Description

I have a custom library and i need to validate and show popup on the application launch. So i used Application.Current.MainPage for displaying DisplayAlert as shown below. This works fine in Android  but popup not showed in windows. Seems the MainPage is null while application in launching.

```
public class CustomView : ContentView
{
	public CustomView()
	{
		MainThread.BeginInvokeOnMainThread(() => ShowPopup());
	}

	async void ShowPopup()
	{
		
		Page? page = Application.Current?.MainPage;
		if (page != null)
		{
			try
			{
				await page.DisplayAlert("PopUp", "Test", "Ok");
			}
			catch (Exception)
			{

			}
		}
	}
}
```

Note: This works fine in Xamarin.Forms also.

Sample:
[MauiApp14.zip](https://github.com/dotnet/maui/files/9008063/MauiApp14.zip)

 

### Steps to Reproduce

Run the attached sample.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on windows, DisplayAlert pop up on android but not on windows.

**Comment by PureWeen** [comment]
You aren't going to be able to rely on the timing of `MainThread.BeginInvokeOnMainThread(() => ShowPopup());` to guarantee that the main page will be set. 

Your best options here I'd say would be either
1) use the Loaded event on the contentview
2) subscribe to `Application.Current.PropertyChanged` and when the mainpage is set then call the popup code
