### ISSUE TITLE
What does the IconImageSource property of ContentPage do?

### ISSUE THREAD

**Issue by seabluescn** [dotnet/maui#8404]
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Navigation.NewPage1"            
             IconImageSource="setting.png"             
             Title="Page1">     
    <VerticalStackLayout>
        <Label    Text="Welcome to Page1!"  VerticalOptions="Center"   HorizontalOptions="Center" /> 
    </VerticalStackLayout>
</ContentPage>
```

IconImageSource not worked in Android

**Comment by SoledadIce** [comment]
Same here. It is also not working for Windows. In iOS, it works but the size is super strange

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on android platform with sample code.
![image](https://github.com/dotnet/maui/assets/82450723/c0b18b8c-c7d7-414b-82fe-43d039b5655e)

**Comment by mattleibow** [comment]
I don't think pages _show_ an icon, it is used when in a tab control or some other container that uses an image to represent the page.

>Note to myself: This probably should have been an attached property...

**Comment by mattleibow** [comment]
Closing this for now as it is a question and the answer is... nothing. Other controls use it.
