### ISSUE TITLE
What is best way to measure startup?

### ISSUE THREAD

**Issue by alexdi220** [dotnet/maui#8411]
Hello, what is the best way to measure the time of the start of MAUI application? The target platforms are iOs and Android. I've checkup that [blog](https://devblogs.microsoft.com/xamarin/performance-xamarin-android-apps/) but it looks like the "Time to initial display" is too early

**Comment by jsuarezruiz** [comment]
On Android, you can use this script https://github.com/jonathanpeppers/maui-profiling/blob/main/scripts/profile.ps1
Install the release package and then, use the script. It will take the startup time after several starts giving the final average.

**Comment by jfversluis** [comment]
Be sure to check out what @jonathanpeppers is doing. He focusses a lot on performance. Maybe also see his session from the past .NET Conf: https://www.youtube.com/watch?v=Wsizdg3xnf4&list=PLdo4fOcmZ0oWePZU3W162NJ9vcXqgpMVc&index=18

**Comment by jonathanpeppers** [comment]
Here are some links, some of these are still in progress:
* General .NET MAUI doc:
  * https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps#measuring-startup-times
* Issue tracking iOS docs, also has links to PRs on the dotnet/performance repo:
  * https://github.com/xamarin/xamarin-macios/issues/15416
* Tool I made to measure Windows/MacCatalyst apps (still WIP):
  * https://github.com/jonathanpeppers/measure-startup
