### ISSUE TITLE
CollectionView renders entries of same dimensions incorrectly when using MeasureFirstItem mode

### ISSUE THREAD

**Issue by Tederean** [dotnet/maui#8412]
### Description

I use a CollectionView to display entries where the visibility is toggled between two labels externally via a switch.

I am using ItemSizingStrategy="MeasureFirstItem". When i add multiple entries of same reference, one label is not visible except for first entry. Because both labels have same size, it should also work with MeasureFirstItem mode.

### Steps to Reproduce

1. Clone https://github.com/Tederean/CollectionViewBug
2. Deploy to Android
3. Toggle Switch on top right side

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Use ItemSizingStrategy="MeasureAllItems" instead of  ItemSizingStrategy="MeasureFirstItem"

**Comment by rachelkang** [comment]
Hi, @Tederean - thanks for opening this issue. Are you seeing the same behavior on the other platforms, or only on Android? Also, would you be able to share some screenshots demonstrating the expected vs. actual behavior?

**Comment by Tederean** [comment]
So far only Android (11) is known. Windows 10 is not affected. I could not check other platforms.

![Expected](https://user-images.githubusercontent.com/2964600/176603743-b01bef4e-c63c-4b39-8d09-df62e2ed5a20.jpg)
![Actual](https://user-images.githubusercontent.com/2964600/176603749-8090caf4-0432-4ec1-a0a7-62ff6bfeecba.jpg)
.

**Comment by kristinx0211** [comment]
verified repro on android, works fine on windows and IOS.
