### ISSUE TITLE
Very stange problem: XAML refuses to update

### ISSUE THREAD

**Issue by AbstractionsAs** [dotnet/maui#8415]
I have a VERY strange issue.

At some point, changes to my XAML files stopped beeing applied to my app.
If I make a change to XAML, anywhere - the change is not reflected in the app.
Also, every time I make a change VS says hot reload cannot apply the change without a rebuid, but after the rebuild- the change is still not applied.

It does not matter what the change is.

It does not matter if I start the app on Windows, iOS or Android.

I've tried:

- Building
- Cleaning
- Rebuilding
- Manually deleting the "bin" and "obj" folders
- Restarting VS
- Updating VS 
- Uninstalling the app from the emulators.

At this point I'm at a loss.

**Comment by AbstractionsAs** [comment]
For some reason it started working again. I have no idea why.

**Comment by drasticactions** [comment]
@AbstractionsAs Most likely, this would be a tooling issue within the IDE rather than something specific with MAUI. If you hit this again, I would file it under VS Feedback (https://developercommunity.visualstudio.com/home)
