### ISSUE TITLE
ApplicationData.Current support for Windows Unpackaged

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#8419]
- [ ] `ApplicationData.Current.LocalSettings` - TODO
- [ ] `ApplicationData.Current.LocalCacheFolder` - TODO
- [ ] `ApplicationData.Current.LocalFolder` - TODO

**Comment by mattleibow** [comment]
I think a large chunk of things were fixed in #8536

All I see is the usage in `EmbeddedFontLoader`
