### ISSUE TITLE
iOS SearchBar "Cancel" button gets rendered inconsistently

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#8425]
### Description

The SearchBar control on iOS gets rendered with the "Cancel" button only on some occasions - and when it does, it's not always visually apparent (it still gets picked up by VO though)

Without cancel button:
<img width="486" alt="Screenshot 2022-06-29 at 12 25 08 PM" src="https://user-images.githubusercontent.com/21988533/176494233-ac9f8b79-f3b8-4415-805a-eff0fdf1dbc6.png">

With cancel button:
<img width="501" alt="Screenshot 2022-06-29 at 12 07 16 PM" src="https://user-images.githubusercontent.com/21988533/176494163-8da2f2f4-dcd1-474b-8cca-b0bcee0282ff.png">

### Steps to Reproduce

1. Run Recipes App
2. Type something into the SearchBar
3. Notice there is no "Cancel" button
4. Click search or click on one of the buttons
5. Notice there is a "Cancel" button next to the SearchBar (but it might be invisible)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

15.5

**Comment by PureWeen** [comment]
Closing in favor of
https://github.com/dotnet/maui/issues/8754
