### ISSUE TITLE
Scrollview control not working properly in .Net MAUI (Android)

### ISSUE THREAD

**Issue by divyesh008** [dotnet/maui#8427]
### Description

I have created custom tab control using ScrollView control and Bindable StackLayout control.

I first created this solution in Xamarin.Forms (VS for Mac 2019) and works fine on both platforms, but the same solution when developed in .Net MAUI (VS for Mac 2022 Prev) it's not working properly in Android.

### Details available here:
https://stackoverflow.com/questions/72804245/scrollview-control-not-working-properly-in-net-maui-android

### Steps to Reproduce

https://github.com/divyesh008/Maui_sample

1 Create a new Maui project, and in MainPage.XAML takes a scroll view with Horizontal orientation and inside that take a Bindable StackLayout. 

2 After scroll view end tag add subviews that you want to display as a tab. 

3 In ViewModel write a logic to change the tab view and Maintain bool flags to show/hide relevant views.

4 Run the project in Android and try to change the tab it will display a blank screen, then if you close the app by pressing the hardware back button and open it again it will show the selected tab properly.   

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10, 11 and above

### Did you find any workaround?

No, I have tried different work arounds but none of them worked.

**Comment by kristinx0211** [comment]
verified repro on android 11 with above project.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on Android platform with project.
[Maui_sample](https://github.com/divyesh008/Maui_sample)
