### ISSUE TITLE
CarouselView scrolling slow if it contains CollectionView in Android app

### ISSUE THREAD

**Issue by kojini** [dotnet/maui#8436]
### Description

I found that CarouselView scrolling is slow in my Android app if it contains a CollectionView in it.  
The slowness is almost unnoticeable if you use a device that has enough resouce (CPU, memory, etc) such as Pixel 3.  

However, it is noticeable when I use a low spec machine such as Samsung Galaxy Tab A7 Lite (physical device).  
I expect that my app is slower on the Tab A7 than Pixel 3 but not this slow. Additionally, swiping animation is laggy.   
I noticed that CarouselView scrolling works just as smooth as it does in Pixel 3 if I comment the CollectionView (i.e. removing it from CarouselView).  
It appears that the performance of CarouselView gets low if it contains CollectionView.  

I used StackLayout with ItemTemplate and ListView instead of CollectionView. It helps improving the performance a little, but still slow and laggy.  

I added `env.conf` and set these parameters: `MONO_GC_PARAMS=bridge-implementation=tarjan,nursery-size=128m,soft-heap-limit=512m`. It helps improving the performance but scrolling is still laggy.  
If I swipe a few times quickly, the app stops responding.  

I don't need all these above if I run the app on Pixel 3 (it works fine on emulator and physical device).  

Probably I should not use CollectionView in CarouselView, but as I said it's still laggy using StackLayout. I don't have a workaround.  

I created a sample app that reproduces the issue.  
[https://github.com/kojini/CarouselViewTest](https://github.com/kojini/CarouselViewTest)  

I'm new to .NET MAUI. Please let me know if I'm doing something I should not do or something is missing.  

### Steps to Reproduce

1. Download my sample app (.zip file)
2. Run the app on a low spec device Samsung Galaxy Tab A7 Lite
3. Swipe the item on screen to left/right
4. Observe that swipe scrolling is slow and animation is laggy
5. Delete the CollectionView in the CarouselView and run the app
6. Swipe the item and observe that it scrolls smoothly

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 API 30

**Comment by kristinx0211** [comment]
I can see it works fine on android 12 emulator.
https://user-images.githubusercontent.com/99457000/176839614-ae1ce031-86d4-4fd3-baf7-b413bb933696.mp4

**Comment by kojini** [comment]
> I can see it works fine on android 12 emulator. https://user-images.githubusercontent.com/99457000/176839614-ae1ce031-86d4-4fd3-baf7-b413bb933696.mp4

Did you test it using a low spec device? You don't notice if you use pixel 3 or above or other device that have enough cpu power/memory.

**Comment by kristinx0211** [comment]
@kojini I tried to run on pixel 3 device just now, can see the scrolling is slow and leggy.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 3.0. Can repro on Android platform with sample project.
https://github.com/kojini/CarouselViewTest
![image](https://github.com/dotnet/maui/assets/82450723/a86f8dbe-244b-4d6f-97e4-5939247e7097)
