### ISSUE TITLE
Android Picker (Theme Change BackgroundColor wont Update) Bug

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#8437]
### Description

If you use the picker and give it a text color etc and change the theme (via API call or via system) it works fine, but the background color (which can't be set via property) update only if the call came from the system. If the call came via api
 Example: ( Application.Current.UserAppTheme = AppTheme.Dark;). Then the background color will not be updated.

Its a big problem if the title color match either withe or black
this causes the title to go invisable
 
Reproduction Repo: https://github.com/DeepWorksStudios/ReproductionProjectBug8437_PickerTheme

https://user-images.githubusercontent.com/59297046/176653491-dd2613b3-da95-466f-8304-716de8c8d499.mp4

### Steps to Reproduce

1. > Create Maui project
2. > Target Android 
3. > Add an picker form doc exsample
4. > add 2 buttons with events to change theme via Application.Current.UserAppTheme
6. > start the emulator or the device
7. > tap on picker and verfi right background color 
8. > switch theme via system call 
9. > tap on picker and verfi right background color 
10. > switch theme via button call 
11. > tap on picker and verfi right background color 
12. > switch theme via button call 
13. > tap on picker and verfi right background color 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

All Android Version

### Did you find any workaround?

Not really i just set the title color to gray500 wich is barly visiable in both cases but like i mentioned barly so its not really a workarround

**Comment by kristinx0211** [comment]
verified repro on android 12 with above project.

**Comment by DeepWorksStudios** [comment]
Any updates?

**Comment by acaliaro** [comment]
same problem!

**Comment by mattleibow** [comment]
Is it basically this issue? https://github.com/dotnet/maui/issues/6092

**Comment by DeepWorksStudios** [comment]
Could be the root of the issue but i am not certain about it

**Comment by jfversluis** [comment]
I think this should be fixed by #13318
