### ISSUE TITLE
Basic UI is wrong on Windows

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#8438]
### Description

`<Frame BorderColor="{DynamicResource Primary}" CornerRadius="5">`
- bottom part is not displayed

`<Label FontSize="Small">...</Label>`
- font size is like 300% instead of `Small`

Windows:
![image](https://user-images.githubusercontent.com/64279914/176661381-4d1012e5-f9f8-4860-981d-99347ae97486.png)

Android (any version):
![image](https://user-images.githubusercontent.com/64279914/176662345-4a5d0378-fc87-4c22-9e71-ead19098e1a4.png)

### Steps to Reproduce

https://github.com/janseris/MAUI_SQLServer_Test/commit/52b2a18adfec97d28b0f4dbaca83b3b1938d37aa

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

**Comment by NonameMissingNo** [comment]
The other interesting thing is that neither of them break the labels into lines

**Comment by janseris** [comment]
> The other interesting thing is that neither of them break the labels into lines

Yes I was wondering about that, too. Also another thing is that AFAIK, stack layout doesn't have any property which would define the alignment of children (vertically and horizontally) inside the stack layout, every child must define it on their self which is a loooot of copy paste.

**Comment by jsuarezruiz** [comment]
> The other interesting thing is that neither of them break the labels into lines

Are you using the LineBreakMode property?, happens on Windows?

**Comment by NonameMissingNo** [comment]
@jsuarezruiz Looking at their code, and it doesn't look like it. Although (bit off-topic), I think that the LineBreakMode should default to true, and you should opt out of it when you don't need it.

**Comment by janseris** [comment]
> > The other interesting thing is that neither of them break the labels into lines
> 
> Are you using the LineBreakMode property?, happens on Windows?

Yes, label not breaking lines happens on windows. You can see it in the first screenshot.

**Comment by elGuille-info** [comment]
If the Frame is the main content of the page, works as is expected. But not the others. In Android works fine.
 
<img width="353" alt="Screenshot 2022-09-05 030234" src="https://user-images.githubusercontent.com/71171321/188341450-b42c1e4f-dba9-48c1-8651-1bcbb05b05be.png">

Any workaround?
Guillermo

**Comment by elGuille-info** [comment]
The problem (in my code) is that the Frame is inside a VerticalLayout, using StackLayout works fine.

<img width="351" alt="Screenshot 2022-09-05 032213" src="https://user-images.githubusercontent.com/71171321/188342777-ad0c2c8a-97f0-41c5-abe4-b2688b5f32f0.png">

Hope this help.
Guillermo

**Comment by elGuille-info** [comment]
Si sirve para algo, decir que en Xamarin para Android (en este caso, ni en Windows ni en iOS) también me ha ocurrido:

La solución en ese caso ha sido ponerle un margen el `StackLayout` que tiene el contenido del `Frame`. 

```
<Frame x:Name="grbListView" Margin="4,0" Padding="3,0">

   <StackLayout>
```

![frame_error](https://user-images.githubusercontent.com/71171321/195989812-cfec6f8d-6f96-4a5c-b48f-a6aecf35ed1c.png)


```
<Frame x:Name="grbListView" Margin="4,0" Padding="3,0">

   <StackLayout Margin="2">
```

Guillermo
P.S.
Perdón si no es el sitio correcto para comentarlo, aunque esto solo me ha ocurrido en una ocasión, y me resultó raro, ya que este fallo comentado en este "issue" es para Windows con .NET MAUI y nunca me había ocurrido con Xamarin.Forms.

**Comment by Redth** [comment]
This seems ok to me now on 7.0.59 of MAUI:

![image](https://user-images.githubusercontent.com/271950/219686121-6a775709-ae82-4bc1-9ebb-994eedf0ada1.png)

There were previously some more issues with Frame and there have been fixes for that control in more recent updates, though I'd generally suggest using `Border` instead of Frame for a more consistent experience across platforms now.

In any case, this one looks resolved to me.

**Comment by janseris** [comment]
> This seems ok to me now on 7.0.59 of MAUI:
> 
> ![image](https://user-images.githubusercontent.com/271950/219686121-6a775709-ae82-4bc1-9ebb-994eedf0ada1.png)
> 
> There were previously some more issues with Frame and there have been fixes for that control in more recent updates, though I'd generally suggest using `Border` instead of Frame for a more consistent experience across platforms now.
> 
> In any case, this one looks resolved to me.

The font size small on Label does not seem to work here.
