### ISSUE TITLE
Sample Maui App fails to install on browserstack

### ISSUE THREAD

**Issue by Unlocalised** [dotnet/maui#8440]
### Description

Creating a file New Maui app using Visual Studio Preview (Mac) or downloading one of the sample apps from dotnet/maui-samples, and uploading the apk to a browserstack testing environment, the app fails to install. 

### Steps to Reproduce

1. Create a File > New Maui app from Visual Studio Mac Preview (Latest) or download the 'WeatherTwentyOne' sample app from dotnet/maui-samples
2. Run the app in an android Emulator (tested with Pixel 5 - API 30 emulator with default settings). The app should run with no issue.
3. Upload the generated signed apk file to browserstack and launch a device.

**Expected outcome:**
_- Browserstack downloads, installs and launches the APK._

**Actual Outcome:**
_- Browserstack presents error message '**App install failed: INSTALL_FAILED_NO_MATCHING_ABIS**'_

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Visual Studio Mac 17.3 preview (17.3 build 1038)

### Relevant log output

```shell
Browserstack Logs:
- Device Selected: Pixel 5 v12.0
- Connecting to real Device Cloud
- Starting device Pixel 5 v12.0
- Downloading app on Pixel 5 v12.0
- Installing app on Pixel 5 v12.0
- App install failed: INSTALL_FAILED_NO_MATCHING_ABIS
```

**Comment by jfversluis** [comment]
Looks like the build you have created cannot run on the architecture that is provided by browserstack, that's why it can't run there. Either select a different device/emulator on their side or create a build that supports the cpu they are running on.

For a bit more info see: https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk
