### ISSUE TITLE
navigation bar is displayed(the gray line)

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#8443]
### Description

When using navigation page the navigation bar is displayed(the gray line):
await App.Current.MainPage.Navigation.PushAsync(new MainPage(), true);
It possible if the NavigationPage has a shade of blue set to it.

### Steps to Reproduce

1.Create maui app.
2. Navigate to main page using 
 await App.Current.MainPage.Navigation.PushAsync(new MainPage(), true);
3.When using navigation page the navigation bar is displayed(the gray line):

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by rachelkang** [comment]
Hi, @danies8 - thanks for opening this issue. Would you mind elaborating a bit more on the issue you're seeing? It sounds right to me that you would see a navigation bar displayed when launching a navigation page. If you can provide screenshots/sample code and ideally share a sample (via a GitHub repository), that would be helpful in our investigation forward :)

**Comment by danies8** [comment]
You see this shadow.
https://192.168.108.85:8443

**Comment by danies8** [comment]
I have a shadow on the window navigation :
![image](https://user-images.githubusercontent.com/1079689/177255710-e2e8193b-bdba-4975-87b0-6734c15e55b4.png)

**Comment by danies8** [comment]
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XXXXXX.Pages.MainPage"
             xmlns:telerik="clr-namespace:Telerik.Maui.Controls;assembly=Telerik.Maui.Controls"
              FlowDirection ="LeftToRight" NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="false"   >
    <telerik:RadDockLayout x:Name="dockLayout" Background="#03446a">

**Comment by kristinx0211** [comment]
@danies8 I am not repro this issue, not see gray line in the navigation bar. could you check for my repro project and let me know if I miss something. thanks.
[MauiApp14.zip](https://github.com/dotnet/maui/files/9045564/MauiApp14.zip)

**Comment by danies8** [comment]
In your sample the navigation bar is seen although NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="false" 
```
x:Class="MauiApp14.NewPage1"
             FlowDirection ="LeftToRight" NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="false"
```

**Comment by kristinx0211** [comment]
Oh yeah, I missed that, this is a reproducible issue. the navigation bar is seen although NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="false".
![image](https://user-images.githubusercontent.com/99457000/177336615-e1ef65ae-e860-4ec7-892c-bd703a404ecd.png)

**Comment by danies8** [comment]
The second bug shown here: the window header has a shade of blue set to it.
![image](https://user-images.githubusercontent.com/1079689/180725693-eff2bb5e-91f5-4519-842b-384ebc5efa00.png)

**Comment by danies8** [comment]
How can I remove it ?

**Comment by codechavez** [comment]
I'm experiencing the same issue. I have ` NavigationPage.HasBackButton="False"` I even have 
` <Shell.BackButtonBehavior>
        <BackButtonBehavior IsVisible="False" IsEnabled="False" />
    </Shell.BackButtonBehavior>`

But I still see the back button on my Windows Maui app. FYI, I'm running the app on my local Windows computer.

Any plans to have this fix?

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with below Project:
[MauiApp9.zip](https://github.com/dotnet/maui/files/11505478/MauiApp9.zip)

The navigation bar is seen although NavigationPage.HasBackButton="False"
![image](https://github.com/dotnet/maui/assets/97647558/41e23466-264c-4ee2-8e71-fca1159527d5)

**Comment by jfversluis** [comment]
I think this issue might be cluttered a bit with another bug. Also no response to request for more info.

Please try the latest versions of .NET MAUI and see if your issues are resolved, if not, please open a new one with what you still experience. Thanks!
