### ISSUE TITLE
Can't change ImageSource on Button on Android

### ISSUE THREAD

**Issue by ZeProgFactory** [dotnet/maui#8459]
### Description

Can't change ImageSource after first initialisation on Button on Android (not tested on iOS). 

### Steps to Reproduce

Add the following code to the creator of a page:
```
      {
         var fontImageSource = new FontImageSource()
         {
            Glyph = "A",
         };

         var button = new Button
         {
            ImageSource = fontImageSource,
            Text = "Button",
            BorderColor = Colors.Black,
         };

         button.Clicked += (object sender, EventArgs e) =>
         {
            (sender as Button).ImageSource = new FontImageSource()
            {
               Glyph = "B",
            };
         };

         // add the button to StackLayout
         _Your Layout_.Children.Add(button);
      };
```
When pressing on the button, 
on Windows the button changes its image from A to B, 
on Android we only see that the button is pressed.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android API28

### Did you find any workaround?

Generate the whole button image (with text) and use ImageButton

**Comment by kristinx0211** [comment]
verified repro on android. works fine on windows. repro project:
[MauiApp1.zip](https://github.com/dotnet/maui/files/9078755/MauiApp1.zip)
