### ISSUE TITLE
iOS build does not respect link flags like <AdditionalArgs>-gcc_flags "-framework CoreMIDI"</AdditionalArgs>

### ISSUE THREAD

**Issue by philipag** [dotnet/maui#8468]
### Description

In a Xamarin.iOS project I used
`<MtouchExtraArgs>-gcc_flags "-framework CoreMIDI"</MtouchExtraArgs>` 
and this worked (the flags were passed on to the linker).  After migrating to a unified MAUI project I changed this to
`<AdditionalArgs>-gcc_flags "-framework CoreMIDI"</AdditionalArgs>`
because that appears to be the new tag supported by the MAUI build system (at least the build properties UI now only allows entry of AdditionalArgs. The problem is that these flags are not being passed on to the linker.  Looking at the diagnostic build log it seems that xcrun includes my .o libs and includes a bunch of frameworks automatically, but it does no include CoreMidi which causes link errors like this:

`Tool xcrun execution finished (exit code = 1).
1>Undefined symbols for architecture arm64:
1>  "_MIDIPortConnectSource", referenced from:
1>      _BASS_MIDI_InStart in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_MIDIPortDispose", referenced from:
1>      _BASS_MIDI_InFree in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_MIDIClientCreate", referenced from:
1>      _BASS_MIDI_InInit in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_kMIDIPropertyUniqueID", referenced from:
1>      l112 in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_kMIDIPropertyName", referenced from:
1>      l112 in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_MIDIGetSource", referenced from:
1>      l112 in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_MIDIObjectGetIntegerProperty", referenced from:
1>      l112 in libbassmidi.a(libbassmidi.a-arm64-master.o)
1>  "_MIDIObjectGetStringProperty", referenced from:`

### Steps to Reproduce

1. Create a default MAUI project
2. Go to "project properties -> iOS -> Build -> Additional Arguments" and enter: -gcc_flags "-framework CoreMIDI"
3. Turn on diagnostic logging
4. Deploy to iPhone.
5. Look at the log line starting with "xcrun execution started with arguments:".  You will see that "-framework CoreMIDI" is not included on the command line.  Other frameworks are automatically included.

If you project actually has dependencies on CoreMIDI then link will of course fail.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

no

**Comment by drasticactions** [comment]
If you build a `dotnet new ios` project and do the same thing, does it work there? I'm interested if it's a single project issues with MAUI, or a more fundamental tooling issue with Xamarin.MaciOS and net6.

**Comment by philipag** [comment]
> If you build a `dotnet new ios` project and do the same thing, does it work there? I'm interested if it's a single project issues with MAUI, or a more fundamental tooling issue with Xamarin.MaciOS and net6.

That causes "-framework CoreMIDI" to be included on the xcrun command line even when I don't specify the `<AdditionalArgs>` tag.  It seems that this new project just includes all the framworks automatically.  However, if I add `<AdditionalArgs>-gcc_flags "-framework zxcv"</AdditionalArgs>` then the bogus "zxcv" framework is not added to the xcrun command line.

So it seems that this new project still has the same issue of not passing any of the flags to the linker.

**Comment by philipag** [comment]
@drasticactions Can you also mark this as a regression because in XF this worked using the `<MtouchExtraArgs>` tag instead of the new `<AdditionalArgs>` tag.  This is preventing migration of an iOS project to MAUI....

**Comment by philipag** [comment]
@drasticactions Any update on this.  This is a show stopper for our app.

**Comment by eshvatskyi** [comment]
you could try

`<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">`
`    <EnableSGenConc>True</EnableSGenConc>`
`    <!--<AdditionalArgs>-cxx -gcc_flags "-framework zxcv"</AdditionalArgs>-->`
`  </PropertyGroup>`
`  <ItemGroup>`
`    <_MainLinkerFlags Include="-v" />`
`    <_MainLinkerFlags Include="-framework zxcv" />`
`  </ItemGroup>`

**Comment by drasticactions** [comment]
> @drasticactions Can you also mark this as a regression because in XF this worked using the `<MtouchExtraArgs>` tag instead of the new `<AdditionalArgs>` tag. This is preventing migration of an iOS project to MAUI....

It worked in Xamarin.Forms because it was using the Xamarin.iOS SDK which uses those tags, and either something changed, regressed, or whatever else inside of the newer net6.0+ versions of the iOS SDK. Going by [eshvatskyi](https://github.com/eshvatskyi)'s workaround, those are very much specific to the SDK, not MAUI.

I don't think this is a MAUI (The UI Framework) issue here, nor is it something that can be fixed here. You would better served to move this issue to https://github.com/xamarin/xamarin-macios.

**Comment by philipag** [comment]
I managed to make this work without using the linker flags:

`		<_NativeExecutableFrameworks Include="AudioToolbox" />
		<_NativeExecutableFrameworks Include="SystemConfiguration" />
		
		
		<_NativeExecutableFrameworks Include="Accelerate" />
		<_NativeExecutableFrameworks Include="CoreMIDI" />`

and then the 3rd party frameworks like this:

`		<NativeReference Include="Platforms/iOS/lib/bass_fx.xcframework">
			<Kind>Framework</Kind>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</NativeReference>`

It seems to be that _NativeExecutableFrameworks  should be made public since that is the only way to provide a list of frameworks to the linker?
