### ISSUE TITLE
Button - Pressed VisualState not setting ImageSource or Custom Properties

### ISSUE THREAD

**Issue by jhunterdfly** [dotnet/maui#8471]
### Description

I'm creating a collection of reusable buttons that extend from the button class that include a FontImageSource and some properties to change the FontImageSource values, such as IconColor, IconSize, and the Glyph.

When I run the app on the iOS Simulator (iPhone SE 3rd Gen -iOS  15.5), on the Button the BackgroundColor, and TextColor are changed as desired, but there is a translucent overlay, or something similar, that alters the actual colors on the Button.  

The Icon Color or ImageSource is not changed when the VisualState is changed to Pressed.

But if I press and hold the button and while holding, and then slide off the button, the overlay remains in place, and if I slide further away from the button the overlay disappears and the TextColor and Background Show as intended.

### Steps to Reproduce

1. Create new MAUI Apps from template.
2. Comment out button style in Styles.xaml
3. Add button to MainPage   
```
<Button
              FontSize="15"
              Padding="1"
              HeightRequest="50"
              Text="My Button"
              ContentLayout="Right,5"
              BackgroundColor="Blue"
              TextColor="White"
              ImageSource="{FontImage Color='White', FontFamily=MaterialRegular, Glyph='&#xe5ca;', Size=18}"
              Grid.Column="1">
              <VisualStateManager.VisualStateGroups>
                  <VisualStateGroup
                      x:Name="CommonStates">
                      <VisualState
                          x:Name="Normal" />
                      <VisualState
                          x:Name="Pressed">
                          <VisualState.Setters>
                              <Setter
                                  Property="BackgroundColor"
                                  Value="LightGreen" />
                              <Setter
                                  Property="TextColor"
                                  Value="Red" />
                              <Setter
                                  Property="ImageSource"
                                  Value="{FontImage Color='Red', FontFamily=MaterialRegular, Glyph='&#xe5ca;', Size=22}" />
                          </VisualState.Setters>
                      </VisualState>
                  </VisualStateGroup>
              </VisualStateManager.VisualStateGroups>
          </Button> 
```
4. Run app in iOS simulator (iPhone SE 3rd Gen -iOS  15.5)
5. Press and hold “My Button”
6. Note the following:
    1. BackgroundColor is LightGreen - as desired
    2. TextColor is Red - as desired
    3. Font Icon color is still White, though barely visible - when it should be Red
    4. There is a translucent overlay altering the color of the Text and Icon, 
        1. How can we get rid of that?
7. While still Pressing and Holding the button, 
    1. slide off the button and the overlay remains in place
    2. Slide further off the button (still holding) and the overlay disappears and the Text color is completely Red and the Icon is White

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS Simulator 15.5

**Comment by VincentBu** [comment]
repro on IOS 15.5 simulator.

**Comment by jsuarezruiz** [comment]
Verified [Issue8471.zip](https://github.com/dotnet/maui/files/9062590/Issue8471.zip)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0.
The issue of translucent overlay still repro, but the BackgroundColor, TextColor, Font Icon color is as desired on .NET 8.
Please check our Repo: [MauiApp7.zip](https://github.com/dotnet/maui/files/12226456/MauiApp7.zip).

**iOS:**
![PressButton](https://github.com/dotnet/maui/assets/97647558/38e3916c-8d3c-43f3-a5c3-67f42de67d1f)
**Android:**
![PressButtonAndroid](https://github.com/dotnet/maui/assets/97647558/da121a80-6e12-4679-b8bf-e8c04f59395f)

**Comment by Marc-Proux** [comment]
Hi everyone, 
I've got the same issue but thanks @XamlTest it's working now.
But I have one question, over elements in the styling file have their color set like this :
`<Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource White}}" />`

I would like to do the same in the button (to got something like this)
`<Setter Property="ImageSource" Value="{FontImage Color={AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}, FontFamily=Icons, Glyph='&#xe88a;', Size=50}" />`

But I got this error :
`Error XFC0009: No property, BindableProperty, or event found for "Color", or mismatching type between value and property. (XFC0009)`

Does someone have an idea to solve the problem ?

Thanks a lot
