### ISSUE TITLE
AllowExternalDrop should default to false on the Blazor WebView controls (Wpf,WinForms)

### ISSUE THREAD

**Issue by budcribar** [dotnet/maui#8478]
### Description

Currently the blazor webview controls default to AllowExternalDrop = true; This means that the out of the box experience will allow a malicious user to drag and drop an html file onto the Blazor Control and a browser will open and run the html. If the application is running as an administrator the browser window will be opened in the Administrator mode. The malicious user could then display files that they would not normally have access to. 

### Steps to Reproduce

1. Create the default demo Blazor Wpf app
2. Run the Wpf demo app as Administrator
3. Create a html file on put it on your desktop
4. drag the html file and drop it on the Wpf  Blazor control
5. A new browser window will open and display the html and will have Administrator control. Your security reviewer will not be happy!!

### Version with bug

7.0.400 (current)  and 6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Will fail on all platforms

### Did you find any workaround?

The workaround is to set the AllowExternalDrop to false on the BlazorWebViewInitialized event. However, the issue is that AllowExternalDrop should be opt in not opt out.

BlazorWebViewInitialized += Init;

private void Init(object x, BlazorWebViewInitializedEventArgs e)
        {
            e.WebView.AllowExternalDrop = false;
        }

The fix I suggest is to default AllowExternalDrop = false; when the webview is created

**Comment by TanayParikh** [comment]
Related: https://github.com/dotnet/maui/issues/7930

**Comment by budcribar** [comment]
This issue also occurs on the 6.0.400 branch

**Comment by kristinx0211** [comment]
Not repro this issue by create Maui Blazor project. the html file on my desktop can't be dropped into the blazor control.

**Comment by TanayParikh** [comment]
> Not repro this issue by create Maui Blazor project. the html file on my desktop can't be dropped into the blazor control.
> 
> ![image](https://user-images.githubusercontent.com/99457000/178224926-4c318d6c-bb78-494e-9419-108bf21f2a96.png)
> 
> 

I believe this issue is specific to Blazor Hybrid on WPF and WinForms.

**Comment by homeyf** [comment]
Visual Studio Enterprise 17.8.0 Preview 3.0. Not repro this issue.
