### ISSUE TITLE
Setting Border.StrokeShape ignores initial StrokeThickness value

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#8481]
### Description

MAUI XAML Hot Reload appears not to work properly when changing Border.StrokeShape

### Steps to Reproduce

1. Open attached app.
2. Build and run.
3. Click "change shape" button few times.
**Actual**: border shape changes but its thickness is 1 rather than what is set in XAML (which is 10).
**Expected**: border thickness matches what is set in XAM.
**Note**: if you click on "change thickness" button at least once then from this point on everything works fine, i.e. changing shape honors thickness. 
[MauiWinUI.zip](https://github.com/dotnet/maui/files/9031773/MauiWinUI.zip)
 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

win 10 21H2

**Comment by jsuarezruiz** [comment]
Verified with the attached sample.
