### ISSUE TITLE
RadioButton with ControlTemplate in a Grid can't change from invisible to visible 

### ISSUE THREAD

**Issue by sretz** [dotnet/maui#8482]
### Description

When a RadioButton is using a ControlTemplate and is in a Grid and is initially set to invisible in the first call to OnAppearing, it's not possible to make it visible later on. Where as when it's initially set as visible it is possible to make it invisible and visible again.

When trying to test on Windows 10 Pro x64 I get a COM Exception
(Note - the Windows crash portion of this report is now a separate issue: #11049)

### Steps to Reproduce

1. Download https://github.com/sretz/Reproduce.RadioGridVisible
2. Run in Android
3. Click on 30 Visable

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Andriod Pixel 5 - API 30 (Andriod 11)

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
verified repro on windows with above project.
