### ISSUE TITLE
FlexLayout doesn't respect Padding

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#8483]
### Description

The padding isn't being used here. I can add a wrapping view, but then I'm just complicating my hierarchy. 

```
<StackLayout>
    <FlexLayout
                    BackgroundColor="#D8D8D8"
                    VerticalOptions="Fill"
                    HorizontalOptions="Fill"
                    Direction="Row"
                    Wrap="Wrap"
                    Padding="15"
                    AlignContent="Start"
                    AlignItems="Start"
                    JustifyContent="SpaceBetween">
                    <Label
                        Text="Recent Activity"
                        FontSize="Large"
                        TextColor="DarkSlateGray"
                        FlexLayout.AlignSelf="Center" />
                    <Label
                        Text="{x:Static local:IconFont.ChevronRight}"
                        FontFamily="{StaticResource FontAwesome}"
                        FontSize="Medium"
                        TextColor="OrangeRed"
                        FlexLayout.AlignSelf="Center" />

                     <BoxView
                        Margin="0,20"
                        HeightRequest="1"
                        BackgroundColor="DimGray"
                        FlexLayout.Basis="100%" />

                    <Button
                        FlexLayout.Basis="100%"
                        Clicked="Button_Clicked"
                        IsEnabled="True"
                        Style="{StaticResource BookingButton}"
                        Text="Book a Flight" />
                </FlexLayout>
</StackLayout>
```
<img width="598" alt="Screen Shot 2022-07-01 at 5 10 18 PM" src="https://user-images.githubusercontent.com/41873/176973243-381c2a3e-0d07-4796-9380-7742aae11a49.png">

Should look like this (made by wrapping in a Grid with padding):

<img width="584" alt="Screen Shot 2022-07-01 at 5 22 31 PM" src="https://user-images.githubusercontent.com/41873/176973903-251691fb-ad7c-45fe-bb33-6a588dbf10fb.png">

which is the same as what XF rendered previously.

### Steps to Reproduce

Do that ^

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

all

### Did you find any workaround?

More layout wrapping :(

**Comment by Xyncgas** [comment]
A bit unrelated but I have a question here, what would you feel about developing your application using MAUI Blazor, because you are using a web layout these problem would be non existent ever again

**Comment by jsuarezruiz** [comment]
Verified.
[Issue8483.zip](https://github.com/dotnet/maui/files/9039314/Issue8483.zip)

**Comment by imanGDZ** [comment]
Any updates on this issue?

**Comment by danielftz** [comment]
Any updates on this?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0 and VSM 17.6 Preview 6. Not repro on iOS, Android, Windows and macOS platform with sample project.
https://github.com/davidortinau/FlyMe/tree/maui/
Android:
![Screenshot 2023-05-17 143236](https://github.com/dotnet/maui/assets/77434865/1011f142-c3c5-4304-b6ff-03d621e08085)
iOS:
![Screenshot 2023-05-17 095258](https://github.com/dotnet/maui/assets/77434865/46e52d98-6e6d-48f7-af04-a5eafffce6f9)
Windows:
![Screenshot 2023-05-17 170842](https://github.com/dotnet/maui/assets/77434865/bcd8ca02-1a38-4b56-9474-0ed4e44f26da)
macOS:
![Screenshot 2023-05-18 093713](https://github.com/dotnet/maui/assets/77434865/95eb40fa-6d13-4409-bbf2-3b690415dddf)
