### ISSUE TITLE
RightToLeft does not work when StackLayout has a child with EndAndExpand

### ISSUE THREAD

**Issue by Ghasan** [dotnet/maui#8488]
### Description

As the title describes, RightToLeft does not work when StackLayout has a child with EndAndExpand.

See the example below, green is correct, red is wrong. Also notice spacing is not respected too.

````xaml
    <VerticalStackLayout FlowDirection="RightToLeft">
        <StackLayout Spacing="10" Orientation="Horizontal" BackgroundColor="Green">
            <Label TextColor="White">First</Label>
            <Label TextColor="White">Second</Label>
            <Label TextColor="White">Third</Label>
        </StackLayout>

        <StackLayout Spacing="10" Orientation="Horizontal" BackgroundColor="Red">
            <Label TextColor="White">First</Label>
            <Label TextColor="White">Second</Label>
            <Label TextColor="White" HorizontalOptions="EndAndExpand">Third</Label>
        </StackLayout>
    </VerticalStackLayout>
````

![image](https://user-images.githubusercontent.com/6239205/176996930-eab485be-f86e-4133-bd30-5612504b5a1f.png)

### Steps to Reproduce

1. Create a new MAUI project
2. Copy the above code as MainPage content
3. Run and observe

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

### Did you find any workaround?

Create nested Grid :(

**Comment by jsuarezruiz** [comment]
Verified.
[Issue8488.zip](https://github.com/dotnet/maui/files/9038872/Issue8488.zip)

.NET MAUI
![image](https://user-images.githubusercontent.com/6755973/177142496-3584fd41-7c29-4902-94c1-ed274d473a9e.png)

Xamarin.Forms
![image](https://user-images.githubusercontent.com/6755973/177142334-3fd35dde-8923-4d4c-9d83-9230aef9cbbc.png)

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on android platform with project. [Issue8488.zip](https://github.com/dotnet/maui/files/9038872/Issue8488.zip)

**Comment by hartez** [comment]
This works correctly on .NET 7 and above.
