### ISSUE TITLE
About XAML partial snippets platform compilation options

### ISSUE THREAD

**Issue by HenJigg** [dotnet/maui#8491]
### Description

For cross-platform applications, especially small mobile devices, the data presentation will appear to be different from the Windows platform.

For example, the Windows platform can display a DataGrid because the display is large enough, but for mobile devices, displaying the DataGrid is not suitable for card-style data.

The idea is to decide which part of the XAML code to choose through platform options, for example:

````
<XamlCard>
     <XamlCard.Android>
          <CollectionView ItemsSource="{Binding Models}"/>
    </XamlCard.Adnroid>

   <XamlCard.Windows>
      <DataGrid ItemsSource="{Binding Models}">
           <DataGrid.Columns>
                ...
           </DataGrid.Columns>
     </DataGrid>
</XamlCard.Windows>
</XamlCard>
````

### Public API Changes

Provides similar platformized snippet functionality

### Intended Use-Case

Show different XAML snippets for different platforms

**Comment by AndreasReitberger** [comment]
You already can do this.
Use `OnPlatform`

https://docs.microsoft.com/de-de/dotnet/maui/xaml/markup-extensions/consume#onplatform-markup-extension

**Comment by jfversluis** [comment]
I would indeed say this is already possible with what we have today. If you'd like to see a different/better/improved syntax for it, please open an issue with a bit of clarification on what you are missing in the current funcionality and what your ideas might be to make it better. Thanks!
