### ISSUE TITLE
AdaptiveTriggers not working

### ISSUE THREAD

**Issue by alajev** [dotnet/maui#8492]
### Description

AdaptiveTriggers not working in Maui app or I'm missing some instruction?

### Steps to Reproduce

1. Create MAUI App.
2. Add this code to MainPage and run the app:
[Example.txt](https://github.com/dotnet/maui/files/9033088/Example.txt)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android & windows 11

### Did you find any workaround?

No.

**Comment by jsuarezruiz** [comment]
Verified.
[Issue8492.zip](https://github.com/dotnet/maui/files/9038678/Issue8492.zip)

**Comment by jsuarezruiz** [comment]
Debugging a little bit, NavigationPage is not updating the size. For that reason, the SizeChanged event is not invoked and the AdaptiveTrigger is not working.

**Comment by samhouts** [comment]
possibly related to #7242
