### ISSUE TITLE
DatePicker displays differently on iOS and Mac

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#8495]
### Description

This could be an Apple thing, but would be nice to know how to make the date display consistently. iOS pads with a leading 0 whereas Mac Catalyst doesn't.

iOS/iPadOS:
<img width="108" alt="Screen Shot 2022-07-02 at 10 17 26 AM" src="https://user-images.githubusercontent.com/41873/177006440-99e86e69-24ce-407f-8eef-4f9d5616434f.png">

Mac:
<img width="184" alt="Screen Shot 2022-07-02 at 10 17 53 AM" src="https://user-images.githubusercontent.com/41873/177006455-9ad13fb3-2564-4481-b901-094a400e6ab5.png">
<img width="123" alt="Screen Shot 2022-07-02 at 10 17 46 AM" src="https://user-images.githubusercontent.com/41873/177006456-3befbba0-2ad1-45ef-b194-c38817d3c629.png">

### Steps to Reproduce

Run a DatePicker on iOS and Mac Catalyst to compare single-digit month and day examples.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

all

**Comment by kristinx0211** [comment]
verified repro on Mac.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on iOS platform with project.
[Issue8495.zip](https://github.com/dotnet/maui/files/11484988/Issue8495.zip)
