### ISSUE TITLE
[Android]  Animated FontSize does not update width and causes text to disappear

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#8496]
### Description

Hello, I'm testing MAUI about Animations etc...,

I try to create a smooth animation on the label's FontSize, When it get bigger some text disapear
Seems related to the width.
![ezgif-2-6d75c454b2](https://user-images.githubusercontent.com/4518686/177006873-a01d2089-4b45-4dd2-90cc-67e338c856ca.gif)

### Steps to Reproduce

You can use my workspace project to reproduce the issue.
[AnimatedLabels.zip](https://github.com/dotnet/maui/files/9033212/AnimatedLabels.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
Verified with the attached sample (thanks!). Also tried the same code in current net6.0 branch and can still reproduce it.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on Android platform with above project.
[AnimatedLabels.zip](https://github.com/dotnet/maui/files/11484585/AnimatedLabels.zip)
![Text ](https://github.com/dotnet/maui/assets/77434865/8f427ba1-623d-496e-b063-a5aceaa53b4f)
