### ISSUE TITLE
Tool /usr/bin/codesign execution finished (exit code = 1).

### ISSUE THREAD

**Issue by otium99** [dotnet/maui#8497]
### Description

I am running this command

`dotnet publish -f:net6.0-ios -c:Release`

to create a *.ipa file. This has worked before, now suddenly it stopped working.

On the MAC I am using Visual Studio 17.3 build 198 and the error is this:

Tool /usr/bin/codesign execution finished (exit code = 1).
          
  /Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: code object is not signed at all
  In subcomponent: /Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app/CommunityToolkit.Mvvm.aotdata.arm64
  
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error : /usr/bin/codesign exited with code 1 [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error :          [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error : Failed to codesign '/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app': /Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: code object is not signed at all [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error : In subcomponent: /Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app/CommunityToolkit.Mvvm.aotdata.arm64 [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error :  [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.4.311/tools/msbuild/iOS/Xamarin.Shared.targets(2067,3): error :          [/Users/user123456/Documents/GitHub/OnesieMobile/OnesieMobile/OnesieMobile.csproj]

In Visual Studio on Windows, which is Version 17.3.0 Preview 2.0, the error is slightly different. This Visual Studio connects to that MAC, and as I said, it worked before.

Tool /usr/bin/codesign execution finished (exit code = 1).
  /Users/user123456/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: code object is not signed at all
  In subcomponent: /Users/user123456/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app/CommunityToolkit.Mvvm.aotdata.arm64

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : /usr/bin/codesign exited with code 1 [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error :          [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : Failed to codesign '/Users/user123456/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app': /Users/user123456/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: code object is not signed at all [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : In subcomponent: /Users/user123456/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app/Communi
tyToolkit.Mvvm.aotdata.arm64 [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error :  [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error :          [C:\Development\OnesieMobile\OnesieMobile\OnesieMobile.csproj]

### Steps to Reproduce

1. Download https://github.com/otium99/8168ErrorReproduction, which was designed to reproduce another error in .NET MAUI, but it should serve for this purpose as well
2. Add a PropertyGroup to the *.csproj file that looks something like this and matches with your code signing certificate

```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
   <CodesignProvision>Maui Provisioning</CodesignProvision>
   <CodesignKey>Apple Distribution: Your Name (12345)</CodesignKey>
   <ArchiveOnBuild>true</ArchiveOnBuild>
   <TcpPort>58181</TcpPort>
   <ServerAddress>xxxxxxx</ServerAddress>
   <!--<ServerAddress>.</ServerAddress>-->
   <ServerUser>xxxxxx</ServerUser>
   <ServerPassword>xxxxx</ServerPassword>
   <_DotNetRootRemoteDirectory>/Users/xxxxx/Library/Caches/Xamarin/XMA/SDKs/dotnet/</_DotNetRootRemoteDirectory>
</PropertyGroup>
```
3. Run this command:

`dotnet publish -f:net6.0-ios -c:Release`

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Windows VS 17.3.0 Preview 2.0 / MAC VS 17.3 build 198

### Did you find any workaround?

No!

**Comment by jfversluis** [comment]
> This has worked before, now suddenly it stopped working.

Do you have any idea of what you did in the meantime? Did you add resources? Libraries? Can you track in your source version history what might have triggered this?

**Comment by otium99** [comment]
@jfversluis Yes, I figured it out after some time.

This seems to be the causing the error. This block in *.csproj:

```
<ItemGroup>
<None Update="Resources\Icons\CheckIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
<None Update="Resources\Icons\HomeIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
<None Update="Resources\Icons\PinIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
<None Update="Resources\Icons\TitleIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
<None Update="Resources\Icons\TrashIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
<None Update="Resources\Icons\UnpinIcon.png">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
</ItemGroup>
```

And it was reproducible for me. In my own project and in the one I provided for reproduction. On Mac and Windows. The following steps should make it reproducible for others as well:

- After following the reproduction steps in this post, the error should occur.
- To reproduce the case where the error does NOT occur, follow these steps:
- Close Visual Studio
- Delete bin, obj, and *.user
- Remove the mentioned block from *.csproj
- Run `dotnet publish -f:net6.0-ios -c:Release`
- There should be no error and the *.ipa should be produced

**Comment by jfversluis** [comment]
Awesome find, thank you so much! OK for now I will close this one. Let's see if people will find/report this more often and see if it's something we really need to improve on. 

Happy developing!

**Comment by jfversluis** [comment]
Oh sorry about that, I though you had it working. You shouldn't need to add those in there for them to end up in your app. Could I ask you to maybe put together a little reproduction project and put that on GitHub and link it here so I can have a look?

**Comment by otium99** [comment]
@jfversluis Yes. You can use the one I mentioned in "Steps to Reproduce": https://github.com/otium99/8168ErrorReproduction


<img src="https://user-images.githubusercontent.com/67344857/177853670-5729cf00-d336-4700-91e7-5a29296394b5.png" width = 300>

- Once you launch it as Windows App, the above window appears and there are the icons
- Remove the block I mentioned in the *.csproj file, delete the bin folder relaunch and the icons are gone
- My understanding is, because then they are not copied to the bin folder during the build process if not instructed to do so
- In VS this is instructed under -> Resources -> Icons -> CheckIcon.png -> Properties -> Advanced -> Copy to Output Directory
- The default is set to: "Do not Copy"
- If not instructed explicitly to copy to the output directory they do not appear in the *.exe and not in the *.ipa

If there is another way how the icons end up in the final product and that doesn't break the build process I am happy to use that way.

**Comment by otium99** [comment]
@jfversluis I just saw this here: https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/single-project

So I tried this:

```
<MauiImage Include="Resources\Images\*">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</MauiImage>
```

But it does not copy to the output directory, nor does the images show up in the final product. Only if I do this:

```
<None Include="Resources\Images\*">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</None>
```

But then it crashes during *.ipa generation.

**Comment by jbfranklin** [comment]
This is not fixed. At least not for me. ANYTHING with a <none /> blows up at iOS/ARM bundle signing. 

I got around this problem with conditional compiling per platform [see here](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-7.0&tabs=windows) 

So @otium99 original code

`<MauiImage Include="Resources\AppIcon\msappicon.png>
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</MauiImage>`

Could be done with this by leaving out the "ios" platform and using "windows" and using "MauiAsset" instead of "none"

`<MauiAsset Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"
    Update="Resources\AppIcon\msappicon.png" CopyToOutputDirectory="Always"/>
`

I am not sure it works with a wild card "*"
