### ISSUE TITLE
Custom Control Property does not Bind

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#8501]
### Description

Custom control (Content View) property does not bind with the Property of a view Model. 

### Steps to Reproduce

Run the repro project. Enter text in the two entries of the Page. The first entry will Bind to the viewmodel and propagate changes. But the second entry which is a part of custom control, will not propagate changes. 

### Link to public reproduction project repository
https://github.com/HobDev/MauiApp1

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS, I was *not* able test on other platforms

### Affected platform versions

Android 11, iOS 16

**Comment by HobDev** [comment]
The `area/Xaml` label is added to the issue. But the same code in C# also cause this issue.

**Comment by jfversluis** [comment]
To be honest I doubt this is an issue in our codebase, rather something that is going wrong in how you might have set this up. Please upload the reproduction to GitHub so we can have a look. Unfortunately, we cannot accept attached zips. Thanks!

**Comment by HobDev** [comment]
Hi @jfversluis I uploaded the repro project at https://github.com/HobDev/MauiApp1.

**Comment by jfversluis** [comment]
I've been looking into this and I don't see any problems to be honest. It seems to work for me as I expect. Could you maybe add step by step what you expect to see and what isn't working according to you?

**Comment by HobDev** [comment]
@jfversluis  You are right when I put a value in the `CustomerName` Property it shows up in the UI. But When I change the value in the UI It does not update the `ViewModel` Property. You can test it by clicking on the Button.

**Comment by jfversluis** [comment]
That's because you don't set the Binding Mode to TwoWay I assume

**Comment by HobDev** [comment]
Set the BindingMode to TwoWay but it still does not work.

**Comment by jfversluis** [comment]
Ah right, yeah so while your control looks like an `Entry` it's of course not an actual `Entry`. In your code there is no propagation between the `Entry.Text` property and your `EntryValue` property. Either hook into the `Entry.TextChanged` event and update your bindable property value or setup a binding between the `Entry.Text` and your `EntryValue` property.

In addition to making the property `BindingMode.TwoWay`

**Comment by HobDev** [comment]
> Ah right, yeah so while your control looks like an `Entry` it's of course not an actual `Entry`. In your code there is no propagation between the `Entry.Text` property and your `EntryValue` property. Either hook into the `Entry.TextChanged` event and update your bindable property value or setup a binding between the `Entry.Text` and your `EntryValue` property.
> 
> In addition to making the property `BindingMode.TwoWay`.
> 
> It's explained here in a bit more detail under "Setting Up The Entry Logic": https://www.mfractor.com/blogs/news/custom-controls-in-xamarin-forms

@jfversluis  This worked for me. Thank you so much for your support. I didn't find this solution in the official docs.
