### ISSUE TITLE
Microsoft.Maui.Graphics.Platform error

### ISSUE THREAD

**Issue by pgmariotti** [dotnet/maui#8509]
### Description

I am trying to display photos in a NetMaui app by using the GraphicsView control.
This worked properly until the latest release of Maui, when the following error appeared:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Platform' does not exist in the namespace 'Microsoft.Maui.Graphics' (are you missing an assembly reference?)	TestMauiGraphics (net6.0-windows10.0.19041.0)	E:\Projects\NetMAUI\TestMauiGraphics\TestMauiGraphics\MainPage.xaml.cs	35	Active
The error is not shown as marked on the source by VS2022 17,3.0 Preview 2.0
I have created a sample project to show the error at https://github.com/pgmariotti/TestMauiGraphics
Please tell me what I am doing wrong...

### Steps to Reproduce

Just compile the program

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

Windows 11 SDK 10.0.22000.0

### Did you find any workaround?

No

**Comment by pgmariotti** [comment]
You may have noticed that it worked fine on the previous release of Maui. In any case, I am trying to compile for Android.
I enclose a zip file with the same content as the repositor
[TestMauiGraphics.zip](https://github.com/dotnet/maui/files/9039759/TestMauiGraphics.zip)

**Comment by jsuarezruiz** [comment]
Yeah, compiling in a single project you get the error because also compiles for Windows where (for now) should use W2DImage (PlatformImage not exists). This issue will be fixed by https://github.com/dotnet/Microsoft.Maui.Graphics/pull/464
Meantime, you can use compilation directives to avoid the problem.
