### ISSUE TITLE
MAUI Blazor problems return

### ISSUE THREAD

**Issue by ajgarciaj** [dotnet/maui#8511]
I'm sorry I left this for a while, I had another blazor project on my hands. Now I have taken it up again and again I have the error
 "Warning unable to buidl chain to self-signed root for signer" despite having marked the certificate as trusted, I was wondering fjvelsuis and yes, it is a project from a previous preview, I have the launchscreen.xib file in the path you mention. Any idea that can help me? Thanks

Is this a project that you have started with earlier .NET MAUI previews? Do you by any chance have this file in your project: `Platforms/iOS/Resources/LaunchScreen.xib`.

Additionally you shouldn't need `/p:EnableAssemblyILStripping=false` anymore.

_Originally posted by @jfversluis in https://github.com/dotnet/maui/issues/6866#issuecomment-1119455536_

**Comment by jfversluis** [comment]
Please remove that xib file and things should hopefully start working again. Let me know if that's the case.

**Comment by ajgarciaj** [comment]
Unfortunately I deleted the file, I ran the command again and I got the same error 

 Warning: unable to build chain to self-signed root for signer "Apple Development: Miguel Angel Sanchez Apellaniz Mein
  es (UE5BDZH9VV)"
  /Users/desarrolloapple/Library/Caches/Xamarin/mtbs/builds/CalculadoraMAUI/8fbdab6240153b953209ecc849708f579460b03cc74
  18dddbdda8e3a1e25e4f5/bin/Release/net6.0-ios/ios-arm64/CalculadoraMAUI.app: errSecInternalComponent

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : /usr
/bin/codesign exited with code 1 [E:\CalcuMAUI\CalculadoraMAUI.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error :
     [E:\CalcuMAUI\CalculadoraMAUI.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : Fail
ed to codesign '/Users/desarrolloapple/Library/Caches/Xamarin/mtbs/builds/CalculadoraMAUI/8fbdab6240153b953209ecc849708
f579460b03cc7418dddbdda8e3a1e25e4f5/bin/Release/net6.0-ios/ios-arm64/CalculadoraMAUI.app': Warning: unable to build cha
in to self-signed root for signer "Apple Development: Miguel Angel Sanchez Apellaniz Meines (UE5BDZH9VV)" [E:\CalcuMAUI
\CalculadoraMAUI.csproj]
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.414\tools\msbuild\iOS\Xamarin.Shared.targets(2067,3): error : /Use
rs/desarrolloapple/Library/Caches/Xamarin/mtbs/builds/CalculadoraMAUI/8fbdab6240153b953209ecc849708f579460b03cc7418dddb
dda8e3a1e25e4f5/bin/Release/net6.0-ios/ios-arm64/CalculadoraMAUI.app: errSecInternalComponent [E:\CalcuMAUI\Calculadora
MAUI.csproj]

I will try with a new certificate, thanks

**Comment by javiercn** [comment]
@jfversluis @jsuarezruiz I don't think this is Blazor specific, is it?

**Comment by jfversluis** [comment]
@ajgarciaj yeah this seems like a new error that has something to do with provisioning profiles for Apple. Try to refresh those :)

**Comment by ajgarciaj** [comment]
@jsuarezruiz ,  @javiercn , @jfversluis , thanks, I'll do a search on this provisioning profiles error.
