### ISSUE TITLE
Hostname not verified when sending request on Android

### ISSUE THREAD

**Issue by IgorKravchenko10** [dotnet/maui#8518]
### Description

We started developing MAUI application and stuck with error trying to send http request. We already have a Xamarin Forms application which successfully works with same API.
We get error `Hostname not verified when sending request`.
This issue described [here](https://docs.microsoft.com/en-us/answers/questions/885827/error-hostname-not-verified-when-sending-request-o.html)
MAUI reproduction (not working) [github](https://github.com/IgorKravchenko10/Maui-web-service-bug) [onedrive](https://1drv.ms/u/s!Aun0lW86yXKJijM3oPvspRfY-8nR?e=xKHhcY)
Xamarin Forms (working) [github](https://github.com/IgorKravchenko10/XFWebService) [onedrive](https://1drv.ms/u/s!Aun0lW86yXKJijT30Nexve-y0Q7k?e=OC79QY)

### Steps to Reproduce

1. Create a new MAUI application.
2. Make http request to API with self signed certificate.
3. Get error "Hostname not verified when sending request".

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android versions

**Comment by jfversluis** [comment]
I think you might better report this issue directly on the [Android repo](https://github.com/xamarin/xamarin-android/). It seems to be specific to Android.

**Comment by jonpryor** [comment]
Will be fixed by https://github.com/xamarin/xamarin-android/pull/7246
