### ISSUE TITLE
publish android,because of use of ZIndex,Crash.

### ISSUE THREAD

**Issue by 94zhudaxing** [dotnet/maui#8525]
### Description

When I Publish,or Install apk into Android Devices, It Crash in Beginning. exclude a lot of codes, Image.ZIndex cause a Crash.But Use VS F5 Install apk can work.

### Steps to Reproduce

When I Publish,or Install apk into Android Devices, It Crash in Beginning. exclude a lot of codes, Image.ZIndex cause a Crash.But Use VS F5 Install apk can work.

### Version with bug

6.0.312

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

Android

### Affected platform versions

android 12

### Did you find any workaround?

When I Publish,or Install apk into Android Devices, It Crash in Beginning. exclude a lot of codes, Image.ZIndex cause a Crash.But Use VS F5 Install apk can work.

### Relevant log output

```shell
some ContentPage  constructor
```

**Comment by NonameMissingNo** [comment]
#7331 Same issue, already fixed on the main

**Comment by jsuarezruiz** [comment]
> #7331 Same issue, already fixed on the main

Seems to be the same, already fixed by https://github.com/dotnet/maui/pull/8184

**Comment by jfversluis** [comment]
This is fixed in our current codebase and should be released as part of our next service release, thanks!

**Comment by jfversluis** [comment]
Duplicate of #7331
