### ISSUE TITLE
Windows Entry with Text (Child of Frame) causes freeze

### ISSUE THREAD

**Issue by DeepWorksStudios** [dotnet/maui#8529]
### Description

I was working on a welcome page for my app, mainly testing it with Android. After a while I was done and it works perfectly on Android, but then I launched the app via Windows and it crashed right away. It took a while to figure out what happened because it threw an unhandled exception with no log or hint. After 8 hours of undoing my work, I figured out what happened. On Android it's fine to use a frame around an entry, but on Windows it causes a render loop, I suppose.
I was able to recreate it in a reproduction project.

On Windows, it only freezes if the entry contains text.

Reproduction Repo: https://github.com/DeepWorksStudios/ReproductionProjectBug8529_FrameEntry

Edit.
I just realized that the editor control is also affected when used in the same case as above descirbed!
To reproduce just replace the entry with and editorentry

### Steps to Reproduce

1. > Create Maui project
2. > Target Windows 
3. > Add an Frame 
4. > add entry as child of frame
6. > give the entry a text value
7. > start the application
8. > observe application behavior

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Any Windows Version

### Did you find any workaround?

Sadly not except to just remove the frame

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with 6.0.400.
![issue8529](https://user-images.githubusercontent.com/6755973/177279157-a0b92787-5b91-40fc-bde4-6bc2008c3a05.gif)

I have tried to add, remove text, resize the Window, etc. maybe I missed some step?

**Comment by DeepWorksStudios** [comment]
I use the same version did you tryed the reproduction project and looked at it?

**Comment by jsuarezruiz** [comment]
> https://user-images.githubusercontent.com/59297046/177281436-a185782d-5e1c-4c66-9234-ba8e133b2e57.mp4 Look at mine
> 
> Well i am uptodate and trough finding out what causes it i also reinstalled the whole framework + vs22 everthing is up to date and clean
> 
> would be so neat to share your used code?

Weird. Used your repository: https://github.com/DeepWorksStudios/ReproductionProjectBug8529_FrameEntry
Will try in another machine to be sure.

**Comment by DeepWorksStudios** [comment]
Indeed it weird if i can anything to help resolving it let me know i am highly interrested to fix this isshue

**Comment by jfversluis** [comment]
Same here, I can't reproduce on the latest stable version (6.0.400) as well as the latest version on main. So, not sure what is going on here 😅

Tried:
- Replacing with an Editor
- Adding text
- Removing text
- Resizing window
- Minimizing and maximizing window

All seems to work fine. Please check your setup and maybe a second machine (VM maybe?) to run this code. It seems to be something specific to your machine. If you have a bit more info, please open a new issue with all the details and refer to this one.

Thanks!

**Comment by DeepWorksStudios** [comment]
Well i reinstalled windows 10
installed the new vs22 preview with dotnet maui workload
still i can reproduce the same problem

so my question is what i need to do to provide you guys with sufficent information that can help you diagnose this isshe it is verry improtant to me

**Comment by DeepWorksStudios** [comment]
@jfversluis @jsuarezruiz ?
