### ISSUE TITLE
When Shell.NavBarIsVisible="False" open and close the flyout programmatically is not working

### ISSUE THREAD

**Issue by Ainur13** [dotnet/maui#8532]
### Description

I want to create custom button to show and hide flyout, but when I hide navbar in xaml by "Shell.NavBarIsVisible="False" I can't programmaticaly do it by using "Shell.Current.FlyoutIsPresented = true/false"

Interesting fact: when I swipe, flyout opens and after that my custom button, that opens flyout programmaticaly, starts to work! 

### Steps to Reproduce

1. Create app with flyout shell
2. Hide it by "Shell.NavBarIsVisible="False"
3. Try to use "Shell.Current.FlyoutIsPresented = true" to open flyout

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by SunshineSpring666** [comment]
Same issue encountered on Android devices. I suggest Shell should have an option to let developer choose to make Hamburger Navigation Button visible on every page or not. Currently, if the back button is presented, flyout menu (Hamburger Navigation Button) doesn't show up on Android/iOS.

**Comment by TheLankyScottishNerd** [comment]
Still an issue in MAUI on .NET 7. Adding the following line:
```
Shell.Current.CurrentPage.Layout(new Rect(0, 0, Shell.Current.CurrentPage.Width + 1, Shell.Current.CurrentPage.Height + 1));
```
after ```Shell.Current.FlyoutIsPresented = true;``` is still current workaround.

**Comment by jeff-eats-pubsubs** [comment]
Encountering this with ```Shell.NavBarIsVisible="False"``` set in my view.xaml (contentpage) with a custom hamburger to trigger ```Shell.Current.FlyoutIsPresented = true```
@TheLankyScottishNerd This works great though thank you very much.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Android 13.0-API33, not repro on Windows 11 and iOS 16.4 with below Project:
[8532.zip](https://github.com/dotnet/maui/files/12744606/8532.zip)
![Flyout](https://github.com/dotnet/maui/assets/97647558/81a9bb21-30f4-491b-baeb-ce18fd33fe23)

Same with the [Shell: Cannot open shell flyout when initial page has Navbar hidden (NavBarIsVisible="False") - Android · Issue #16927 · dotnet/maui (github.com)](https://github.com/dotnet/maui/issues/16927)
