### ISSUE TITLE
[Android]Content view size not changed when changing width and height dynamically

### ISSUE THREAD

**Issue by jeya-kasipandi** [dotnet/maui#8549]
### Description

Content view size (width and height) not changed when changing width and height dynamically in Android platform.

### Steps to Reproduce

1.Run sample from below link
https://github.com/jeya-kasipandi/ContentviewIssue_sample
2.Click button to change the content view width and height
3.Content view width and height not changed in Android 
Expected Output:
ContentView should update the view based on the  width and height
Actual Output:
ContentView does not update the view based on the width and height

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment]
> 1.Run attached sample

Seems like you forgot the attachement :)

Also, please add it to a GitHub repo and add the link here. Unfortunately we're not able to accept attached zip files. Thanks!

**Comment by jeya-kasipandi** [comment]
@jfversluis  added reproducing sample and please check the reported issue

**Comment by jfversluis** [comment]
Thanks for attaching that! Just ran it against our latest code and it seems that the issue is already fixed :) it should be part of our next service release. Thanks!

https://user-images.githubusercontent.com/939291/177547583-c22d49ba-e45e-41c4-9ff4-cfd410de5ad7.mov

**Comment by jsuarezruiz** [comment]
![Screenshot_1656936863](https://user-images.githubusercontent.com/6755973/177547966-251a37b8-0d6f-4f83-b31a-09e3be3fee23.png)

**Comment by jsuarezruiz** [comment]
![issue-8549](https://user-images.githubusercontent.com/6755973/177548038-283f5f8f-1174-4f54-8a31-8b10cbb3b9f6.gif)
