### ISSUE TITLE
Debugging and error logging on VS Mac and Blazor MAUI

### ISSUE THREAD

**Issue by d4046949** [dotnet/maui#8551]
We've been slowly developing a Hybird application on a Mac using Visual Studio for Mac and the iphone emulator. Sadly though, there doesn't seem to be a good set of tools in order to understand why Blazor throws errors. WASM means we can open the Chrome browser and inspect using the dev tools. Is there something like this for Visual Studio for Mac? 

I've been looking at the output tab and the other 4 panes and none of them produce detailed stack traces to give us clues about why an exception has occured,

**Comment by TanayParikh** [comment]
> Is there something like this for Visual Studio for Mac?

Yes: https://docs.microsoft.com/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-6.0&pivots=ios

**Comment by d4046949** [comment]
Brilliant. That helped a lot. I'll close this issue
