### ISSUE TITLE
Flow direction is LeftToRight on iOS rtl language

### ISSUE THREAD

**Issue by yairp03** [dotnet/maui#8556]
### Description

On android, when the language is set to an RTL language, the flow direction of all the controls is also set to RightToLeft. Still, on iOS, even when the device language is an RTL language, the `Device.FlowDirection` is still set to `LeftToRight`.RTL

### Steps to Reproduce

1. Create a File > New .NET MAUI app.
2. Run on an iOS device whose language is set to an RTL language.
3. `Device.FlowDirection` is still set to `LeftToRight`

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by jsuarezruiz** [comment]
Are you setting RightToLeft FlowDirection and the value in Device.FlowDirection is incorrect or also the UI is not updated correctly?

**Comment by yairp03** [comment]
On Android, I do not set anything. If my phone is in Hebrew then the default flow direction for the entire app is RightToLeft without needing to set anything. If I change the phone language to English and restart the app, the flow direction will automatically be `LeftToRight`.
On iOS, it doesn't happen, and I found out that the property that is responsible for that is probably `Device.FlowDirection` cause it changes on android. Still, on iOS, its value remains `LeftToRight` even if I change the iPhone language to Hebrew, and the app is `LeftToRight`.

**Comment by yairp03** [comment]
Is there any workaround for this? A way to get the supposed flow direction and set it manually on startup?

**Comment by fazary** [comment]
I have the same issue in android (don't have mac to test) with Arabic language is still Right-to-left 
when change language to English it changed to Left-to-right 
so, the issue is Flow Direction forced to device language not to Flow Direction Property

**Comment by aljaiban** [comment]
I am also facing this issue exactly as described by @yairp03  but with Arabic. RTL does not work correctly in iOS where as it works perfectly in Android. Unfortunately it is stopping me from going to production for a customer. This issue requires a faster fix if you plan to have maui competitive to platforms like Flutter.

**Comment by khagesh-medtronic** [comment]
I Have a similar Issue, and this one more a bigger issue. When i change the language to Arabic(RTL), It doesn't show anything on the screen for child contentView. looks like RTL is completely broken in MAUI. This is the worst. I have a Xamarin form app which I am migrating to MAUI but completely block on the RTL language 

.Net version : 7.0.86 (latest)

Screenshot of sample Apps: 

English(works fine ) : 
![IMG_0240](https://github.com/dotnet/maui/assets/133243157/615579c7-c593-4dbb-acd4-d857d8bc9b4d)

Arabic( nothing shows):

![IMG_0241](https://github.com/dotnet/maui/assets/133243157/c34536d9-bdfe-442f-98b1-7506174a41f3)

**Comment by fazary** [comment]
Any updates 🤔

**Comment by khagesh-medtronic** [comment]
try adding this workaround NuGet **PureWeen.Maui.FixesAndWorkarounds**,  
https://github.com/PureWeen/ShanedlerSamples/tree/main

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on iOS platform.
