### ISSUE TITLE
CustomView causes a memory leak 

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#8557]
### Description

CustomView still causes a memory leak after the CustomView.Handler.DisconnectHandler method invoked on the CustomView.Unloaded event

### Steps to Reproduce

1. Open [TestLeaks.zip](https://github.com/dotnet/maui/files/9055561/TestLeaks.zip) project
2. Run on iOS or Android
3. On the MainPage click "Add custom control" button. The CustomTextView will be added on the page.
4. Then click "Call GC.Collect + show refs" button. Next messages will appear in the Application Output:

IsAlive: CustomTextView
IsAlive: CustomTextViewHandler
IsAlive: TextView

All of these objects are staying in a memory, it's correct. (TextView - native platform view)

5. Click "Remove custom control" button. The CustomTextView will be removed from the page.
6. Сlick "Call GC.Collect + show refs" button again. Next messages will appear in the Application Output:

IsAlive: CustomTextView
IsAlive: false
IsAlive: false

CustomViewHandler with PlatformView were disposed after GC.Collect() invoking, but the CustomTextView is staying in a memory.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 Android 11

**Comment by jsuarezruiz** [comment]
Using .NET MAUI 6.0.400 on Android. Adding the control and tapping the GC.Collect:

```
[0:] IsAlive: CustomTextView
[0:] IsAlive: CustomTextViewHandler
[0:] IsAlive: TextView
[0:] --------------- 
```
After removing the control and tapping again to the GC.Collect option:
```
[0:] IsAlive: False
[0:] IsAlive: False
[0:] IsAlive: False
[0:] ---------------
```

Seems to work as expected on Android, did you find the leak on iOS?
