### ISSUE TITLE
[Proposal] Show progress of issue on GitHub

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#8566]
### Description

Hi, it would be nice it if would be visible to the original poster (and to the public as well), if a GitHub issue is being currently solved or worked on by someone.
Currently it is visible that it is a part of a milestone which is good as well.

### Public API Changes

none

### Intended Use-Case

track and plan programming MAUI apps, allocate teams working on MAUI apps etc.

**Comment by drasticactions** [comment]
I'm not on the MAUI team directly, but I believe that's what the "Assignees" tag is for on the issue. That assignee is, ideally, the person working on it (or figuring out how to solve it). That, plus the milestone, is the reference point for when an issue is being worked on and when the hope is that it'll be finished.

**Comment by jsuarezruiz** [comment]
After creating the issue you have two important labels:
- triaged: Someone from the team reviewed the issue.
- **verified**: Someone from the team has verified that it is indeed an issue and that it has to be fixed.

After validating the issue, it will be assigned to a **milestone** where you can see the estimated date. In the process, you will see someone **assigned** to the issue. At this point you should know who is going to fix the issue and when it is estimated.

The issue will pass to in progress to done state. In this moment, you will see a PR associated with the issue.

I hope this brief description helps and if you have any ideas or suggestions to improve the process, any idea is always welcome.
