### ISSUE TITLE
[Android] If to set SystemUiVisibility = SystemUiFlags.HideNavigation on Android,  then Flyout Items are not displayed.

### ISSUE THREAD

**Issue by Ainur13** [dotnet/maui#8575]
### Description

I try to make my app full screen on Android without status bar on top and navigation bar on botttom, so in MainActivity I override OnCreate method and write inside following code:

`
Window.DecorView.SystemUiVisibility = (StatusBarVisibility)
            (SystemUiFlags.Fullscreen | SystemUiFlags.ImmersiveSticky | SystemUiFlags.HideNavigation);
`

I know that it's deprecated, but it still works! =)

But the problem is that **SystemUiFlags.HideNavigation** prevents flyout work properly: flyout items stop to be visible or not generated at all,  idk)

<img src="https://user-images.githubusercontent.com/19732508/177692070-ff80880b-294b-498a-bb38-bee8a06ac3a9.gif" width="250" height="510"/>

If I remove **SystemUiFlags.HideNavigation** everything works fine, but my app then have navigation on bottom. 

<img src="https://user-images.githubusercontent.com/19732508/177692134-2b330534-b7bc-4aa6-9bc4-d7e38c47b5ca.gif" width="250" height="510"/>

### Steps to Reproduce

1. Create app with Flyout
2. Override  OnCreate method in MainActivity on Android Platform
3. Write inside OnCreate method 
`Window.DecorView.SystemUiVisibility = (StatusBarVisibility)
            (SystemUiFlags.Fullscreen | SystemUiFlags.ImmersiveSticky | SystemUiFlags.HideNavigation);`
4. Run Android and see that flyout items are not displayed

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by nzcoward** [comment]
As you are on Android 11, can you use AndroidX as a workaround?

```csharp
using AndroidX.Core.View;

WindowCompat.SetDecorFitsSystemWindows(Window, false);
WindowInsetsControllerCompat windowInsetsControllerCompat = ViewCompat.GetWindowInsetsController(Window.DecorView);
windowInsetsControllerCompat.Hide(WindowInsetsCompat.Type.SystemBars() | WindowInsetsCompat.Type.NavigationBars());
windowInsetsControllerCompat.SystemBarsBehavior = WindowInsetsControllerCompat.BehaviorShowTransientBarsBySwipe;
`

**Comment by Ainur13** [comment]
@nzcoward Will it work on lower vwersions of Anddroid?

**Comment by nzcoward** [comment]
AndroidX works on API 28+, but I'm pretty sure not all features will. I haven't tested on lower than 30.

**Comment by Ainur13** [comment]
@nzcoward  Tested on Android 10: unfortunately, ViewCompat.GetWindowInsetsController(Window.DecorView) returns **null** at runtime and causes exception :(

**Comment by nzcoward** [comment]
Are you doing it in OnCreate and OnResume in MainActivity? I know I had some issues with it at one point in XF not being available at the right time. But not long after I upgraded to API 30 so I never looked further into it

**Comment by zslocum** [comment]
In case anyone else comes through looking for a workaround that works on API 29 (at least within emulator, did not try lower) through API 31 (on device, Pixel 3).

You can actually instantiate a WindowInsetsControllerCompat within OnCreate:
```
WindowCompat.SetDecorFitsSystemWindows(Window, false);
WindowInsetsControllerCompat windowInsetsControllerCompat = new WindowInsetsControllerCompat(Window, Window.DecorView);
windowInsetsControllerCompat.Hide(WindowInsetsCompat.Type.SystemBars() | WindowInsetsCompat.Type.NavigationBars());
windowInsetsControllerCompat.SystemBarsBehavior = WindowInsetsControllerCompat.BehaviorShowTransientBarsBySwipe;
```
