### ISSUE TITLE
TabbedPage title displays incorrectly. It displays current selected child page title

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#8577]
### Description

With TabbedPages, the parent TabbedPage and children pages can all be seperately titled. The title of the parent must display on the toolbar, and the children's titles must display on the tabs.

Currently, the seleced tab's tile also gets displayed on the toolbar.
![image](https://user-images.githubusercontent.com/7484186/177697787-a0b0c50e-6601-4f57-8dee-9af1b434940d.png)

Here is the code for the tabbed page. Notice its Title is 'TabbedPage'
```
internal class NextTabbedPage: TabbedPage
    {
        public NextTabbedPage()
        {
            Children.Add(new NextTabPage1());
            Children.Add(new NextTabPage2());

            Title = "TabbedPage";

            MenuBarItems.Add(new MenuBarItem { Text = "MenuItem1" });
            MenuBarItems.Add(new MenuBarItem { Text = "MenuItem2" });
        }
    }

```
A repro project is provided: https://github.com/hbraasch/WinMenuTester.git

### Steps to Reproduce

1. Load repro project in VS and run. Notice the error on the toolbar

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

All

**Comment by r-work** [comment]
Ran into the same issue, is there at least a workaround or something?

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Can repro this issue with above project.
https://github.com/hbraasch/WinMenuTester.git
Android:
![image](https://github.com/dotnet/maui/assets/82450723/da5160df-fda9-4474-8a6c-0060675086e3)
Windows:
![image](https://github.com/dotnet/maui/assets/82450723/5e01c8cc-c5e8-4191-bc04-1f518d13de11)

**Comment by Adam--** [comment]
A workaround I found (at least for Android) is to use a NavigationPage.TitleView in the TabbedPage. For instance, if you define your TabbedPage as

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage
    x:Class="MauiApp2.MyTabbedPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    Title="This title is ignored">
    <NavigationPage.TitleView>
        <Label Text="This TitleView is used" VerticalTextAlignment="Center" />
    </NavigationPage.TitleView>
    <ContentPage Title="Tab 1" />
    <ContentPage Title="Tab 2" />
    <ContentPage Title="Tab 3" />
</TabbedPage>
```

You'll get a NavigationPage title similar to
![image](https://github.com/dotnet/maui/assets/2179171/987ba794-d9e4-4b99-871b-10710a1d8258)

do note that you'll need to style the TitleView appropriately.

**Comment by Adam--** [comment]
Hey all, I put in a PR to fix this. It works on real devices, but I can't get the new unit tests to work. Check out the failures here https://dev.azure.com/xamarin/public/_build/results?buildId=95096&view=ms.vss-test-web.build-test-results-tab&runId=2089639&resultId=104022&paneView=debug.

In the unit tests, I'm finding that in the unit tests NavigationPageToolbar OnPageAppearing doesn't get called for the TabbedPage's children and ultimately the tests fail with the toolbar title being null. When I run on a device (Android and Windows) this gets called and the title is as expected.

If anyone here can help out with this, I'd really appreciate it.

**Comment by kwameg-a** [comment]
There's also this issue of the title text wrapping, which I could fix in Xamarin Forms to make them scroll horizintally, but have had no luck with MAUI :)
 
![image](https://github.com/dotnet/maui/assets/5632690/f35de4a5-c07e-49bb-a9ab-b59468f2ec6b)

Any ideas on how to resolve this would be greatly appreciated!

**Comment by kwameg-a** [comment]
There's also this issue of the tab title text wrapping on **Android**, which I could fix in Xamarin Forms to make them scroll horizintally, but have had no luck with MAUI :)
 
![image](https://github.com/dotnet/maui/assets/5632690/0314a663-7d70-436b-a10c-a12b4c9a9fbc)

![image](https://github.com/dotnet/maui/assets/5632690/bfa1b058-a42f-4438-8c5d-bdf10869b197)

Any ideas or help on how to resolve this would be greatly appreciated!

**Comment by Adam--** [comment]
@kwameg-a, it's best to keep the discussion here focused on the one issue and what you are mentioning isn't related. 
However, with XF I've used a custom renderer, now called a handler, to change the behavior of the tab page. If it's not working, I'd recommend asking on stackoverflow or if you've found a bug, creating a separate bug report.

**Comment by kwameg-a** [comment]
@Adam--  Thanks for your response. You're right - let's keep the discussion here focused on one issue.

**Comment by s3ttingQ** [comment]
Any update on the problem?

**Comment by Adam--** [comment]
> Any update on the problem?

It's fixed with https://github.com/dotnet/maui/pull/17039 but hasn't been completed.
