### ISSUE TITLE
Properties Height and Width have values equal -1 after Initialization of page components 

### ISSUE THREAD

**Issue by sofyaol** [dotnet/maui#8586]
### Description

Re-open issue #8176
I just wanted to do the following to make the page component responsive and square at the same time:
HeightRequest="{Binding Source={RelativeSource Self}, Path=Width}"
Nothing happens with Height. Debug says that Width property equals -1 after Initialization and it equals -1 after first call override method OnAppearing() too.
I tried to  bind it to Frame.Width or Bounds.Width, but it doesn't work too.

I also noticed that it works correctly after a hot reload. But it was expected that this would work at application start.

### Steps to Reproduce

There is my simple project which reproduce the issue:
https://github.com/sofyaol/MAUIFrameBindingIssue

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
Verified with https://github.com/sofyaol/MAUIFrameBindingIssue

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on android platform with sample project.
https://github.com/sofyaol/MAUIFrameBindingIssue
![image](https://github.com/dotnet/maui/assets/82450723/be7aa89d-819a-4ee2-a00c-2b29f93d0d52)
