### ISSUE TITLE
Label Height doesn't get updated with text 

### ISSUE THREAD

**Issue by sofyaol** [dotnet/maui#8588]
### Description

VerticalStackLayout has a Label and when text size changes it doesn't resize Label Height.
In my sample I have MainPage that contains:

VerticalStackLayout (Padding="0" Margin="0")
Label (LineBreakMode="WordWrap" MaxLines="10")

When I set string to Label.Text that contains more text Label doesn't resize and it crop text.

Also I saw #5897, but i think it has nothing to do with my problem

### Steps to Reproduce

There is my simple project which reproduce the issue:
https://github.com/sofyaol/MAUIResizingIssue

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 (Emulator)

**Comment by sofyaol** [comment]
I used Android Emulator - pixel 5 (Android 11.0 - API 30)

**Comment by sofyaol** [comment]
![ResizingIssue](https://user-images.githubusercontent.com/61603405/177838013-75d48d48-ce9f-47a8-af14-3a6daac0a9c9.gif)

**Comment by Symbai** [comment]
@hartez Its in the first post `6.0.400` and I believe the height issue is already fixed with #8136

**Comment by hartez** [comment]
As @Symbai said, this is fixed by #8136 - the next release (currently slated for next week) should have the fix.
