### ISSUE TITLE
AppThemeBinding doesn't work on iOS in runtime

### ISSUE THREAD

**Issue by alexdi220** [dotnet/maui#8606]
### Description

Hi, I've tested the AppThemeBinding and faced that it doesn't work on iOS in runtime. It works only when an application was restarted. For Android works fine.

### Steps to Reproduce

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage">

    <ContentPage.Resources>
        <SolidColorBrush x:Key="Light" Color="Red"/>
        <SolidColorBrush x:Key="Dark" Color="Blue"/>
    </ContentPage.Resources>
    <ScrollView>
        <VerticalStackLayout Spacing="10">
          <Button Text="Add" 
                  Background="{AppThemeBinding Light={StaticResource Light}, Dark={StaticResource Dark}}"/>
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jsuarezruiz** [comment]
Verified. 

[Issue8606.zip](https://github.com/dotnet/maui/files/9071256/Issue8606.zip)

**Comment by tj-devel709** [comment]
Seems to be the same issue as https://github.com/dotnet/maui/issues/11299#issuecomment-1489389618.

@jsuarezruiz I think we can close this one too as it seems the other has been fixed!

**Comment by jsuarezruiz** [comment]
Yes, must be fixed by https://github.com/dotnet/maui/pull/11200
![ios-appareance](https://user-images.githubusercontent.com/6755973/229490530-ae0aafde-ac99-4f65-b501-7a6309f9b52a.gif)

Closing for now this issue, but let us know if find any detail and can reopen it etc.
