### ISSUE TITLE
CollectionView SelectionChangedCommand does not invoke if Button is the root element of the datatemplate

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#8608]
### Description

CollectionView SelectionChangedCommand does not invoke if Button is the root element of the DataTemplate. The SelectionChangedCommand does invoke if I change the root element to Border. 

### Steps to Reproduce

Run the repro project. Comment out and UnComment the Border and Button elements one by one in the DataTemplate of the MainPage. The SelectionChangedCommand will invoke with Border but not with Button. 

[CollectionViewIssue.zip](https://github.com/dotnet/maui/files/9072021/CollectionViewIssue.zip)

https://github.com/HobDev/CollectionViewIssue

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

Use Border instead of Button. Although the Button looks much better in default settings.

**Comment by jfversluis** [comment]
Please add the reproduction project as a GitHub repository instead of a zip, see: https://github.com/dotnet/maui/blob/b1c802af62027d8b04dfe318a09d9e123798d7e9/.github/repro.md#why-cant-you-just-download-my-zip-file-reproduction

Thanks!

**Comment by HobDev** [comment]
The link to the repro is https://github.com/HobDev/CollectionViewIssue

**Comment by HobDev** [comment]
@mattleibow  I able to achieve the UI using Border. I don't know whether this is a bug or a feature request. It's on maui team to decide.

**Comment by mattleibow** [comment]
Good to hear you are not blocked.

I am going to close this as a feature as this is what Button is designed to do. If anyone feels strongly, please open a new issue with your case linking to this.
