### ISSUE TITLE
Border.IsVisible binding property changed event not work on Android.

### ISSUE THREAD

**Issue by kashin777** [dotnet/maui#8615]
### Description

Border.IsVisible binding property changed event not work on Android.

### Steps to Reproduce

BorderIsVisibleTestPage.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAppDemo.Pages.BorderIsVisibleTestPage"
             Title="BorderIsVisibleTestPage">
    <VerticalStackLayout>

        <CheckBox x:Name="CheckBox1" IsChecked="False" />
            
        <Border IsVisible="{Binding Source={Reference CheckBox1}, Path=IsChecked}"
                Stroke="Black" StrokeThickness="1" StrokeShape="Rectangle" Padding="5">
            <Label Text="CheckBox1 is checked."  />
        </Border>

    </VerticalStackLayout>
</ContentPage>
```

I expected if checked CheckBox1, displaying Border and Label message, but not work.
Work expectedly on Windows.
And If default value is True, work expectedly, on Android.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by hartez** [comment]
I think this is another instance of #8044, and should be fixed by #8136. We'll need to verify on Service Release 2.

**Comment by kashin777** [comment]
thank you.
I try version 6.0.500-preview.1.6140, it's work.

**Comment by jsuarezruiz** [comment]
Verified, fixed by https://github.com/dotnet/maui/pull/8136
