### ISSUE TITLE
Slider not working in latest Mac Catalyst

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#8620]
### Description

Slider control crashed the app.

### Steps to Reproduce

1. Create a new Maui App.
2. In the MainPage.xaml, enter a new Slider control <Slider Maximum="30" Minimum="10" Value="20" />
3. Run the app and crashed.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

macOS

### Affected platform versions

Latest Mac OS

### Did you find any workaround?

No.

**Comment by tekmun** [comment]
I have published the app on Windows, iOS and Android. I am not able to publish it on Mac Store because of this bug. 
I uninstalled Visual Studio for Mac and did a clean installation. Unfortunately, I have to download the latest version. For a workaround, how do I install a previous version of Visual Studio for Mac? Thank you.

**Comment by jsuarezruiz** [comment]
Can you share the exception log or the output?.

**Comment by tekmun** [comment]
[Crash Report.txt](https://github.com/dotnet/maui/files/9085713/Crash.Report.txt)
This is the Crash Report.
When I comment out the code "settingsdetailsG.Add(fontsizeslider, 1, 4);", my program runs well.

On Visual Studio for Mac now, I am unable to see any other outputs or logs.
