### ISSUE TITLE
Entry/Editor do not lose focus -- ContentView Binding

### ISSUE THREAD

**Issue by 11ultimate11** [dotnet/maui#8623]
### Description

Entry and Editor won‘t lose focus by any chance.The only way to  hide keyboard its to press back button...until then nothings work but still dont lose focus

ContentView IsVisible Property cant be changed from code behind or due databinding 

Methods like: 
FadeTo
TranslateTo 
Are only working sometimes

### Steps to Reproduce

Create an Entry/Editor inside a verticalstacklayout
Click on it to get focus
Try to tap anywhere else on the screen.

Create a ContentView give it an x:Name or Bind its IsVisible property. Try to change it in run time. 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android11

### Did you find any workaround?

I tried everything , nothing work

**Comment by nzcoward** [comment]
A number of controls (probably all) have IsVisible and IsEnabled issues (at least on Android).

One particular issue I saw with IsVisible is that if I bound the property to false initially, it would not be changeable, but if set to true in the initial bind, I could toggle it just fine.

**Comment by jfversluis** [comment]
As mentioned, this should be fixed by an upcoming release, which is probably the release that happened yesterday. Please update you Visual Studio and try again. If it still doesn't work, feel free to report a new issue.

Thanks!
