### ISSUE TITLE
Intellisense / HotReload

### ISSUE THREAD

**Issue by 11ultimate11** [dotnet/maui#8624]
### Description

Intelisense it is not working in xaml only in code behind
Hotreload its reloading only sometimes. 

### Steps to Reproduce

Try to lett intelisense feagure out and impirt a new namespace. Press ctl + . 
Press Hitreload button

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android11 

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Thanks for the report! This is probably something that has to do with Visual Studio and/or the tooling around that. Additionally, there was an update for Visual Studio yesterday, so you might give that a try. If it still doesn't work after updating, please report this issue through the Visual Studio Help menu and then Provide Feedback > Report a Problem.

That way it will land with the right team and all the right log files etc. for them to diagnose the issue effectively.

THanks!

**Comment by mplessis** [comment]
Hello, 

check if you have all sdk, target by your application, installed. In my case, i have no intellisense in xaml, but after installed the android sdk  31, the intellisense back.
