### ISSUE TITLE
TextColor of Label does not change with VisualStateManger inside CollectionView

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#8626]
### Description

TextColor of `Label` does not change with `VisualStateManger` inside CollectionView. Although the initial color applies to the Label from Normal State. But does not change when the state change to Selected. 

### Steps to Reproduce

Run the repro project and select the CollectionView items. The Visual State Manager setters work on Border's BackgroundColor. But it does not effect the Label's TextColor. 

[CollectionViewIssue.zip](https://github.com/dotnet/maui/files/9077422/CollectionViewIssue.zip)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 and iOS 15.5

**Comment by ToolmakerSteve** [comment]
Whether it is a bug or not depends on how you look at it.

When you select an item in a collection, the outermost layout is what becomes "Selected". In this case, that is the "Border".

But given the intended usage of Border as an "adornment", it is logical from the coder's perspective to consider the Label itself to be "Selected".

Some solution would be good.

OR maybe doc needs to tell user how to have VisualState of border be used to set a property on "border.Content" properties. That can get tricky, if the property isn't one of the fundamental properties of a View (BackgroundColor is easy): what is the syntax for setting Label's TextColor?

**Comment by HobDev** [comment]
I added 1 style for border and 1 style for Label in the contentpage resources:

```
Resources = new ResourceDictionary
            {
                new Style<Border>(VisualStateManager.VisualStateGroupsProperty, new VisualStateGroupList
                {
                    new VisualStateGroup
                    {
                        Name = nameof(VisualStateManager.CommonStates),
                        States =
                        {
                            new VisualState
                            {
                                Name = VisualStateManager.CommonStates.Selected,
                                Setters =
                                {
                                    new Setter
                                    {
                                        Property = Border.BackgroundColorProperty,
                                        Value = Colors.Orange
                                    },

                                }
                            },
                             new VisualState
                             {
                                 Name = VisualStateManager.CommonStates.Normal,
                                 Setters =
                                {
                                    new Setter
                                    {
                                        Property = Border.BackgroundColorProperty,
                                        Value = Colors.LightGray
                                    }
                                }
                             }
                        }
                    }
                }),

             new Style<Label>(VisualStateManager.VisualStateGroupsProperty, new VisualStateGroupList
                {
                    new VisualStateGroup
                    {
                        Name = nameof(VisualStateManager.CommonStates),
                        States =
                        {
                            new VisualState
                            {
                                Name = VisualStateManager.CommonStates.Selected,
                                Setters =
                                {
                                    new Setter
                                    {
                                        Property = Label.TextColorProperty,
                                        Value = Colors.White
                                    },

                                }
                            },
                             new VisualState
                             {
                                 Name = VisualStateManager.CommonStates.Normal,
                                 Setters =
                                {
                                    new Setter
                                    {
                                        Property = Label.TextColorProperty,
                                        Value = Colors.Black
                                    }
                                }
                             }
                        }
                    }
                })
        };
```

The Border in the DataTemplate of the CollectionView:

 ```
 DataTemplate interestsTemplate = new DataTemplate(() =>
        {

            Border border = new Border
            {
                StrokeThickness = 0,
                Padding = new Thickness(8, 4),
                HorizontalOptions = LayoutOptions.Fill,
                StrokeShape = new RoundRectangle { CornerRadius = new CornerRadius(20) },
                Content = new Label
                {
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center

                }.Bind(Label.TextProperty, "Name")
            };
            return border;

        });
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android 13.0 with below Project:
[MauiApp18.zip](https://github.com/dotnet/maui/files/11514838/MauiApp18.zip)

![image](https://github.com/dotnet/maui/assets/97647558/924ecea1-ba29-4b7a-9392-ffce2e977084)

**Comment by mattleibow** [comment]
@ToolmakerSteve makes an important observation here I think. The cell/border is selected, but not all the controls within. This is the same thing that happens in all XAML and one way to work around it is to used named elements (via `TargetName` in styles): https://learn.microsoft.com/en-us/dotnet/maui/user-interface/visual-states#set-state-on-multiple-elements
