### ISSUE TITLE
RemainingItemsThresholdReachedCommand in CollectionView is not triggered on Windows

### ISSUE THREAD

**Issue by tbrabec** [dotnet/maui#8627]
### Description

RemainingItemsThresholdReachedCommand is not working on Windows. It works on Android.
[Reproduction link](https://github.com/tbrabec/MauiCollectionViewIssue.git)

### Steps to Reproduce

1. Run the app on Windows
2. Scroll down

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No.

**Comment by jfversluis** [comment]
Duplicate of #8338
