### ISSUE TITLE
Images in subfolders not showing up on Windows but do on Android

### ISSUE THREAD

**Issue by pouchbunny** [dotnet/maui#8628]
### Description

How do I get the Windows version of my app to recognize images in subfolders? I have changed the Include to `<MauiImage Include="Resources\Images\**\*" />` to pick up all items and subfolders, but the images ONLY show up on Android.

![image](https://user-images.githubusercontent.com/42586025/178126677-80655e37-3bfd-41db-9752-a3f59b19f9ca.png)

### Steps to Reproduce

1. Create new Maui app
2. Add subfolder to images
3. Add new image to subfolder
4. Auto-generates ItemGroup for folder
5. But to get Android to recognize subfolders: changes <MauiImage Include="Resources\Images\*" /> to <MauiImage Include="Resources\Images\**\*" />
6. Change dotnet_bot.svg to cube.jpg
7. Run app in Android (new image is displayed)
8. Run app in Windows (no new image)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by pouchbunny** [comment]
I knew it had to be something simple. THANKS!

**Comment by hartez** [comment]
@pouchbunny If that answered your question, please go ahead and close this issue. Thanks!

**Comment by jfversluis** [comment]
No answer, assuming this is fixed!
