### ISSUE TITLE
EXEC : The application cannot be opened for an unexpected reason

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#8630]
### Description

Last login: Sun Jul 10 09:38:26 on ttys001
macm1os@Pirasaths-Mac-mini A % dotnet build -t:Run -f net6.0-maccatalyst
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  E_C -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/E_C/bin/Debug/net6.0/E_C.dll
  E_B -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/E_B/bin/Debug/net6.0/E_B.dll
  A_B -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A_B/bin/Debug/net6.0-maccatalyst/A_B.dll
  E_E -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/E_E/bin/Debug/net6.0/E_E.dll
  E_A -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/E_A/bin/Debug/net6.0/E_A.dll
  A_A -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A_A/bin/Debug/net6.0-maccatalyst/A_A.dll
  E_D -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/E_D/bin/Debug/net6.0/E_D.dll
  D_A_B -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/D_A_B/bin/Debug/net6.0/D_A_B.dll
  D_A_A_B -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/D_A_A_B/bin/Debug/net6.0/D_A_A_B.dll
  D_A -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/D_A/bin/Debug/net6.0/D_A.dll
  D_A_A_A -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/D_A_A_A/bin/Debug/net6.0/D_A_A_A.dll
  Detected signing identity:
          
    Bundle Id: social.object.app
    App Id: social.object.app
  A -> /Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/A.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
EXEC : The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002f3c3f0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error : 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}} [/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/A.csproj]
/usr/local/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(901,5): error MSB3073: The command "open "/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/bin/Debug/net6.0-maccatalyst/maccatalyst-x64//A.app" --args" exited with code 1. [/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/A.csproj]

Build FAILED.

EXEC : The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600002f3c3f0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error : 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}} [/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/A.csproj]
/usr/local/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(901,5): error MSB3073: The command "open "/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/bin/Debug/net6.0-maccatalyst/maccatalyst-x64//A.app" --args" exited with code 1. [/Users/macm1os/Desktop/OS/DeveloperZone1/Developer/A/A.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.99
macm1os@Pirasaths-Mac-mini A % 
macm1os@Pirasaths-Mac-mini A % 

What can i say never work...

https://github.com/PirasathLuxchumykanthan/DeveloperZone/

### Steps to Reproduce

https://github.com/PirasathLuxchumykanthan/DeveloperZone/

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS

**Comment by jfversluis** [comment]
I'm going to need a bit more info on what you're trying to do here instead of just log output. Also, you're providing us with a very big reproduction project that is hard to understand as an outsider. Please provide us with a reproduction as outlined here to be able to effectively diagnose your potential issue: https://github.com/dotnet/maui/blob/main/.github/repro.md

Thanks!
