### ISSUE TITLE
EmbeddedJar is showing in property explorer In Andriod Binding Project

### ISSUE THREAD

**Issue by premshahdev** [dotnet/maui#8634]
### Description

I want to Use Jar Binding in Maui Project Like Xamarin. Is there any new Concept or i Have to use old xamarin concept.
I am usng xamarin concept by following [Docs] (https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-a-jar).
I cannot able to find EmbeddedJar in Property Explorer as describe in this link.

![05-embeddedjar](https://user-images.githubusercontent.com/69380911/178145973-f1e3e91e-730b-4bbb-b43d-82694a8e0730.png)

### Steps to Reproduce

1. Create a Jar Binding Project 
2. Add Jar Item
3. Try to change to EmbeddedJar from Property explorer 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Andriod 11

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
@jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
There is not really a such thing as a binding project anymore:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md

You can just put the `.jar` in your app project if you like.

We do have a project template, though:

![image](https://user-images.githubusercontent.com/840039/178997783-c0081e5f-428d-4d36-8c51-229b000dcb5b.png)

Then you can use the `AndroidLibrary` item group for everything now, details in:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md

I think that solves this question? Thanks!

**Comment by premshahdev** [comment]
@jonathanpeppers 
I Have done as per your suggested lnik but unfortunately,  i cannot  figure it out.
i have used following step

1. Create a MauiApp Project
2. Create a MauiLibrary Project
3. Added JarItems in  MauiLibrary Project
4. Added below code in  MauiLibrary Project
`<ItemGroup>
	  <AndroidLibrary Include="JarsLib\WPOS\SDK4BaseBinderV2.1.jar"/>
	  <AndroidLibrary Include="JarsLib\WPOS\SDK4EmvBinderV2.1.jar"/>
	  <AndroidLibrary Include="JarsLib\WPOS\SDK4KeyManagerBinderV2.1.jar"/>
	</ItemGroup>`
5. added refrence in MauiApp Project
6. Created a Class Called MyPrinter
7. Now i want to inherit MyPrinter Class From Jar Project something like
`public  class MyPrinter :  Wangpos.Sdk4.Libbasebinder.Printer
{


}
`
Now It is not working .
I Have also attached project file , please check

[JarBindingProject.zip](https://github.com/dotnet/maui/files/9120360/JarBindingProject.zip)

**Comment by jonathanpeppers** [comment]
> Now It is not working .

Can you give a little more detail on what is not working? You get a build error? What is the error?

**Comment by premshahdev** [comment]
> > Now It is not working .
> 
> Can you give a little more detail on what is not working? You get a build error? What is the error?

I cannot able to acess class from Jar. i want to  inherit in MyPrinter Class From Jar Project something like
`public class MyPrinter : Wangpos.Sdk4.Libbasebinder.Printer
{
}`

**Wangpos.Sdk4.Libbasebinder.Printer** is in Jar , i want to acess this class in my Myprinter Class and i am not able to do.

**Comment by premshahdev** [comment]
@jonathanpeppers  ?

**Comment by premshahdev** [comment]
@jonathanpeppers ?
