### ISSUE TITLE
Publishing MAUI Blazor App with dotnet publish

### ISSUE THREAD

**Issue by KriszW** [dotnet/maui#8637]
### Description

I found a bug, when i wanted to publish my MAUI Blazor App to windows.

I followed [the original publishing article](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview), but when i run the following command:
`dotnet publish -f net6.0-windows10.0.19041.0 -c Release`

I always got the following error:
![image](https://user-images.githubusercontent.com/54480462/178154181-86ce59d5-f358-4aba-b80c-0158adfba8bc.png)

Which said File not found.

The file was there, so i figured out the problem not with the file not being in the specified location. The problem is the file path was too long for some component to register it.

So i copied my repo to a simplier location and everything worked fine.

Please update the article with a warning or please fix the issue!

Thank you very much in advance!

### Steps to Reproduce

1. Create a MAUI App with a very long path name (the published .msix filepath must be at least 260 characters long)
2. Follow this article about publishing your app: [article](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview)

You should an error like this in the developer console:
C:\Users\werdn\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets(501,5): error APPX1204: Failed to sign 'C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\App
Packages\StatProcessing.Gui.Maui.Blazor_1.0.0.1_Test\StatProcessing.Gui.Maui.Blazor_1.0.0.1_x64.msix'. SignTool Error: File not found: C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\StatProcessi
ng.Gui.Maui.Blazor_1.0.0.1_Test\StatProcessing.Gui.Maui.Blazor_1.0.0.1_x64.msix

My dotnet version: 6.0.400-preview.22301.10

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

You should move your repo to a simplier folder like: C:\temp and from there you can publish your MAUI app

### Relevant log output

```shell
C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor>dotnet publish -f net6.0-windows10.0.19041.0 -c Release
Microsoft (R) Build Engine version 17.3.0-preview-22277-01+f1dae6ab6 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  StatProcessing.Gui.Shared -> C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Shared\bin\Release\net6.0\LuxscanStat.StatProcessing.Gui.Shared.dll
  StatProcessing.Gui.Maui.Blazor -> C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\StatProcessing.Gui.Maui.Blazor.dll
  StatProcessing.Gui.Maui.Blazor -> C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\publish\
C:\Users\werdn\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets(341,5): warning : Path to `mspdbcmf.exe` could not be found. A symbols package will not be generated. Review https://aka.ms/windowsappsdkdocs and ensure that all prerequisites for Windows App SDK deve
lopment have been installed. [C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\StatProcessing.Gui.Maui.Blazor.csproj]
  StatProcessing.Gui.Maui.Blazor -> C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\StatProcessing.Gui.Maui.Blazor_1.0.0.1_Test\StatProcessing.Gui.Maui.Blazor_1.0.0.1_x64.msix
C:\Users\werdn\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets(501,5): error APPX1204: Failed to sign 'C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\App
Packages\StatProcessing.Gui.Maui.Blazor_1.0.0.1_Test\StatProcessing.Gui.Maui.Blazor_1.0.0.1_x64.msix'. SignTool Error: File not found: C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\StatProcessi
ng.Gui.Maui.Blazor_1.0.0.1_Test\StatProcessing.Gui.Maui.Blazor_1.0.0.1_x64.msix
 [C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\StatProcessing.Gui.Maui.Blazor.csproj]
C:\Users\werdn\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets(501,5): error APPX1204:  [C:\Users\werdn\source\repos\KriszW-Software\luxscanstatv3\src\StatProcessing\StatProcessing.Gui.Maui.Blazor\StatProcessing.Gui.Maui.Blazor.csproj]
```

**Comment by javiercn** [comment]
@KriszW thanks for contacting us.

Do the instructions work for an app that doesn't involve Blazor? (Could you try with a regular .NET Maui app)

**Comment by jfversluis** [comment]
It looks like your solution consist of multiple projects, you'll want to publish the csproj of your .NET MAUI app project. So the command will become something like `dotnet publish MyAppProject.csproj -f net6.0-windows10.0.19041.0 -c Release`

That should make it work :)
