### ISSUE TITLE
Installing and updating the Visual Studio IDE

### ISSUE THREAD

**Issue by Mohammed2021-coder** [dotnet/maui#8638]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

I do download the Visual Studio Preview every time, I see a different screen and it doesn't look like IDE with .NET MAUI

**Comment by Mohammed2021-coder** [comment]
<img width="1440" alt="Screenshot 2022-07-10 at 21 54 38" src="https://user-images.githubusercon
<img width="1440" alt="Screenshot 2022-07-10 at 21 54 51" src="https://user-images.githubusercontent.com/80024701/178160414-8d5d91b7-e4e2-4105-8fff-936cb6593272.png">
tent.com/80024701/178160397-ff2bf21c-d5d0-4cd4-a6e1-0b979b2b1f64.png">
<img width="1440" alt="Screenshot 2022-07-10 at 21 54 42" src="https://user-images.githubusercontent.com/80024701/178160411-fece6f0c-267a-4609-b0b3-a0ec2b5dbc37.png">

**Comment by Mohammed2021-coder** [comment]
What is this that I'm downloading?? 🤨

**Comment by REscobar** [comment]
Unfortunately the documentation does not have a note to differentiate between `Visual Studio 2022` and  `Visual Studio 2022 for Mac` which are 2 different products, here is the product page for Visual Studio for Mac

https://visualstudio.microsoft.com/vs/mac/preview/

As for the tutorial I'm not sure if it's available with Mac illustrations, you will have to wait a little bit for someone else to clarify that part.

**Comment by jfversluis** [comment]
This is indeed the Xamarin Profiler. I'm not sure how you managed to get that on there. I am not really clear what the issue is here exactly. I'm going to be a positive person and assume you got this sorted by now, if not, please open a new issue with all the details, thanks!
