### ISSUE TITLE
Entry keyboard 'Custom'

### ISSUE THREAD

**Issue by JkPersson** [dotnet/maui#8644]
### Description

We often encounter situations where we need an entry with a specific set of allowed characters. 

I realize that this opens for discussions about layout of the resulting keyboard. Perhaps we could start with a simple grid where the chars are listed in the order they are specified. Maybe the user could even split the list into rows in the definition.

### Public API Changes

An examplecould look something like this:
```
<Entry Placeholder="Enter text here">
    <Entry.Keyboard>
        <Keyboard x:FactoryMethod="Create">
            <x:Arguments>
                <KeyboardFlags>Suggestions,CapitalizeCharacter</KeyboardFlags>
                <KeyboardChars>123456798ABCD</KeyboardChars>
            </x:Arguments>
        </Keyboard>
    </Entry.Keyboard>
</Entry>

```
### Intended Use-Case

Examples could be:
- Guids
- A comma seperated list of integers (e.g. '99999,12323,44444')
- Integer ranges (e.g. '10-430,450')

**Comment by jfversluis** [comment]
Thanks for the idea! Unfortunately, I don't see much traction after 2+ years so I don't think we'll get to this anytime soon.

Additionally, I think part of the reason for that is that we don't want to go and create our own controls like custom keyboards. The main paradigm of .NET MAUI is to map abstract APIs onto platform-specific functionalities that are already there.
