### ISSUE TITLE
[MacCatalyst] [iOS] ScrollView is not longer visualised when placed inside VerticalStackLayout

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#8645]
### Description

When I place my ScrollView inside VerticalStackLayout the control is no longer visualised. As the stack measures the ScrollView with infinity height the final desired Height of the ScrollView seems to be 0.

**The version I am currently using is not officially released. 6.0.408** from branch https://github.com/dotnet/maui/tree/release/6.0.4xx-sr2.

**Last working version: 6.0.400**

Most probably the issue occurs due to the following change: https://github.com/dotnet/maui/pull/7514

### Steps to Reproduce

1. Run the attached project.
2. Notice how the ScrollView and its content is not visualised because the height of the control is 0.
[HelloMaui.zip](https://github.com/dotnet/maui/files/9082929/HelloMaui.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

macOS Monterey 12.4, iOS 15.5

### Did you find any workaround?

We need to explicitly set Height for the ScrollView in order to visualise it.

**Comment by hartez** [comment]
This was fixed in the .NET 7 release.
