### ISSUE TITLE
[MacCatalyst] [iOS] Gestures does not work on elements initially outside of the view port of the ScrollView

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#8647]
### Description

If you have a Button (for example) that is initially outside of the the viewport when you scroll to that Button click is not possible.

**The version I am currently using is not officially released: 6.0.408** from branch https://github.com/dotnet/maui/tree/release/6.0.4xx-sr2.

**Last working version: 6.0.400**

Most probably the issue occurs due to the following change: https://github.com/dotnet/maui/pull/7514

### Steps to Reproduce

1.Run the attached project.
2. Scroll to the bottom of the Page.
3. Try to click the button.
[HelloMaui.zip](https://github.com/dotnet/maui/files/9083428/HelloMaui.zip)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

macOS Monterey 12.4, iOS 15.5

**Comment by ili** [comment]
Facing the same issue https://github.com/ili/MauiScrollViewClickIssue

**Comment by PaulAndersonS** [comment]
Facing the same issue. Gestures not working on elements that are initially outside the viewport of the scrollview.

**Comment by hartez** [comment]
This is fixed in the latest release.
