### ISSUE TITLE
WebView hyperlink click navigation doesn't contain clicked URL on Android

### ISSUE THREAD

**Issue by michaldivis** [dotnet/maui#8648]
### Description

I am unable to find out what url has been clicked in the `WebView` control on Android. All I'm getting in the clicked url is `about:blank#blocked`.

This works on other platforms, when I click `<a href="someLink">Click me</a>` on iOS I get:
`file:///Users/developteam/Library/Developer/CoreSimulator/Devices/746A160A-BC2F-429F-AFFF-5D9D7B6F977C/data/Containers/Bundle/Application/3A46B8F3-30D2-4F35-9EC8-CB6FA738C5F7/XfWebViewApp01.iOS.app/www.baseUrl.org/test/someLink`

### Steps to Reproduce

**Here's a [reporoduction repo](https://github.com/michaldivis/maui-webView-clickedUrl) of this issue.**

And here's how to reproduce it.

#### 2. Place a `WebView` control on the `MainPage` and subscribe to it's `Navigating` event

MainPage.cs
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="MauiWebViewClickedUrl.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <ContentPage.Content>
        <WebView x:Name="TheWebView" Navigating="TheWebView_Navigating" />
    </ContentPage.Content>
</ContentPage>
```

MainPage.xaml.cs
```csharp
private void TheWebView_Navigating(object sender, WebNavigatingEventArgs e)
{
    var url = e.Url;
}
```

#### 3. Load some HTML into the `WebView`
```csharp
string html; //this contains the html code
var source = new HtmlWebViewSource()
{
    BaseUrl = "www.baseUrl.org/test/",
    Html = html
};
TheWebView.Source = source;
```
#### 4. Click a hyperlink. The hyperlink I'm clicking looks like this:
```html
<a href="someLink">Click me</a>
```

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, possibly others

### Did you find any workaround?

No workaround I can think of...

**Comment by jfversluis** [comment]
I see you mention 6.0 Release Candidate 3 as a version, is that actually correct, what makes you think that? What does `dotnet --version` tell you?

**Comment by michaldivis** [comment]
I downloaded the latest VS 2022 preview after MAUI RC 3 was announced, that's why I've assumed I'm using the latest RC version. I'm sorry if that's not the case. `dotnet --version` tells me `6.0.400-preview.22301.10`.

**Comment by michaldivis** [comment]
@jfversluis did I get the version right?

**Comment by michaldivis** [comment]
@jfversluis is this a bug or a known limitation of the Android WebView?

**Comment by michaldivis** [comment]
This is what the `dotnet workload list` command shows me:
```
Installed Workload Ids      Manifest Version                              Installation Source
--------------------------------------------------------------------------------------------------------------
ios                         15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32804.467, VS 17.4.32804.182
maccatalyst                 15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32804.467, VS 17.4.32804.182
maui-ios                    6.0.486/6.0.400                               VS 17.3.32804.467, VS 17.4.32804.182
maui-android                6.0.486/6.0.400                               VS 17.3.32804.467, VS 17.4.32804.182
android                     32.0.448/6.0.400                              VS 17.3.32804.467, VS 17.4.32804.182
maui-windows                6.0.486/6.0.400                               VS 17.3.32804.467, VS 17.4.32804.182
maui-maccatalyst            6.0.486/6.0.400                               VS 17.3.32804.467, VS 17.4.32804.182
runtimes-windows            6.0.8/6.0.300                                 VS 17.4.32804.182
```

**Comment by michaldivis** [comment]
I've figured it out! It was my fault all along.

The problem was an invalid base url. Specifically, my base url was missing a url scheme.

Loading the source in the following way resulted in link clicks returning `about:blank#blocked`:
```csharp
TheWebView.Source = new HtmlWebViewSource
{
    BaseUrl = "www.base-url.org/test/",
    Html = Properties.Resources.exampleHtml
};
```

**All I needed to do was add `https://`** (or another url scheme, I guess) **and it works!**
```csharp
TheWebView.Source = new HtmlWebViewSource
{
    BaseUrl = "https://www.base-url.org/test/", // <-- this works!
    Html = Properties.Resources.exampleHtml
};
```

Now, when I click an anchor link, the `WebNavigatingEventArgs`.`Url` has the value of `https://www.base-url.org/test/myAnchorLink`.
