### ISSUE TITLE
APT2000	El sistema no puede encontrar el archivo especificado. (2).  file:///C:/Program%20Files/dotnet/packs/Microsoft.Android.Sdk.Windows/32.0.300-rc

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8654]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/APT2000	El-sistema-no-puede-encontrar-el/10049377)._

---
[severity:It bothers me. A fix would be nice]
It's just starting a default MAUI .NET APP (Preview). When I run the project to Windows Machine there's no problem. But when I do for a Pixel 5 - API 30 emulator this problem appears. 

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	APT2000	El sistema no puede encontrar el archivo especificado. (2).	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.3.45\tools\Xamarin.Android.Aapt2.targets	212	

I have a clean installation in two PCs and I have the same problem. Just running the default MAUI .NET APP without changing anything. 

Regards

---
#### Feedback Bot on 5/22/2022, 08:17 PM: 

(private comment, text removed)
#### Javier Gómez on 5/23/2022, 01:00 AM: 

(private comment, text removed)
#### Javier Gómez on 6/17/2022, 03:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I see the author mentions the .NET MAUI (Preview) templates while they have been in preview for a while. If you get to see this, please make sure to update your Visual Studio and all the bits and try again if that helps. If it still doesn't work for you, please open a new issue here and add all the details you have. Thanks!
