### ISSUE TITLE
Restore nuget packages fails on Maui projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8655]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Restore-nuget-packages-fails-on-Maui-pro/10051905)._

---
Pretty much as title, unable to build existing Maui RC3 solution as it fails on windows workflow, even though mac or iOS simulator selected for deployment.

---
#### Feedback Bot on 5/25/2022, 00:24 AM: 

(private comment, text removed)
#### John Hair on 5/28/2022, 01:46 AM: 

(private comment, text removed)
#### jeffkl [MSFT] on 5/31/2022, 11:56 AM: 

(private comment, text removed)
#### John Hair on 6/1/2022, 01:09 PM: 

(private comment, text removed)
#### Feedback Bot on 6/2/2022, 07:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
I think the best thing to do is to update to the latest Visual Studio Preview, which includes .NET MAUI 6 GA. Preview 3 is quite old at this point and not supported.
