### ISSUE TITLE
Maui - Stepper do not turn enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8656]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui---Stepper-do-not-turn-enabled/10084165)._

---
Hello,
I'm using Stepper control, when the control turn disabled the button '-','+' turn dimmed then cannot make changes in the value.
But, when try to turn the control (Stepper) enabled, the control will not be enable anymore. 
To get around this situation, I'm using IsVisible property.
Please, thank you
Antonio

---
#### Feedback Bot on 6/29/2022, 11:13 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Looks related with the IsVisible issue and could be fixed by https://github.com/dotnet/maui/pull/8136

**Comment by jfversluis** [comment]
Please try the release from yesterday to see if this fixed your issue, if not, feel free to open a new issue here with all the details. Thanks!
