### ISSUE TITLE
MAUI Solution asking for Workloads when they are all installed.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8657]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Solution-asking-for-Workloads-when-/10085347)._

---
I created a new MAUI project from the basic template and ran with no issues.

The project is now on github - 

https://github.com/wickedw/MAUI.SSLTest

When reopening the project at a later date, it now says “Project Requires .NET Workloads ….”

I either choose to install workloads when the warning comes up OR
I right click on the project and choose Install .NET Workloads, this sometimes removes the warning box, but then shows the error at compile run time.

I have listed all the workloads on my machine and they seem fine.

How do I diagnose where this mismatch is coming from? as this is a showstopper for working with MAUI at the moment.

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.301

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Installed Workload Ids      Installation Source
-----------------------------------------------
wasm-tools                  SDK 6.0.300        
macos                       SDK 6.0.300        
maui-maccatalyst            SDK 6.0.300        
maui-ios                    SDK 6.0.300        
maui-android                SDK 6.0.300        
maui                        SDK 6.0.300        
tvos                        SDK 6.0.300        

Use `dotnet workload search` to find additional workloads to install.

Thanks for your help,
Matt

---
#### Feedback Bot on 6/30/2022, 07:45 PM: 

(private comment, text removed)
#### Theresa Zhang[MSFT] on 7/5/2022, 03:22 AM: 

(private comment, text removed)
#### Matthew Waring on 7/5/2022, 00:38 PM: 

(private comment, text removed)
#### Theresa Zhang[MSFT] on 7/8/2022, 02:13 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looking at the log output and your workload list it seems there is a mismatch in .NET 6 versions. In the log output I see 6.0.202 and in your workloads I see 6.0.300. Do you have a global.json in your project by any chance? In the preferences of Visual Studio do you see the right .NET 6 version being set? If you run `dotnet --version` what is the output? And what is the output if you run the same command from the folder of your project?
