### ISSUE TITLE
[Bug] Animated GIF files do not play on iOS/macOS

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#866]
### Description

The iOS platform does not yet have the logic to load animated images correctly. Right now it only gets the first frame.

### Steps to Reproduce

1. Add an image element
2. Set the source to an animated gif
3. Observe the image load, but not play

### Expected Behavior

Animation plays.

### Actual Behavior

Only the first frame shows.

### Workaround

https://github.com/dotnet/maui/issues/866#issuecomment-1466988089

**Comment by shimingsg** [comment]
verified with VS 17.2.0 Preview 2.0 [32224.339.main] in Android 12, windows and IOS 15.2:
the image only gets the first frame.
repro demo: [866.zip](https://github.com/dotnet/maui/files/8151124/866.zip)

**Comment by angelru** [comment]
This is still unresolved in RC3?

**Comment by mattleibow** [comment]
Let me have a look at this... It should be working on android at least because we don't do anything and hand it off to glide.

**Comment by mattleibow** [comment]
Looking at this now. I got ideas as to where....

The first issue is that we convert gif to png :)

Try adding this:

```xml
<MauiImage Update="Resources\Images\*.gif" Resize="False" />
```

or whatever the path to the gif is. Basically set Resize=false to get it to work. I am seeing windows play gif here when I do that.

**Comment by angelru** [comment]
> Looking at this now. I got ideas as to where....
> 
> The first issue is that we convert gif to png :)
> 
> Try adding this:
> 
> ```
> <MauiImage Update="Resources\Images\*.gif" Resize="False" />
> ```
> 
> or whatever the path to the gif is. Basically set Resize=false to get it to work. I am seeing windows play gif here when I do that.

Now if it works, thanks, is it the correct way to do it or do we have to wait for another RC/GA to solve this problem?

**Comment by mattleibow** [comment]
This is the correct way, but I will also make this the default so you don't have to do it. There are a few properties on MauiImage that can control how it is resized and if at all.

**Comment by angelru** [comment]
> This is the correct way, but I will also make this the default so you don't have to do it. There are a few properties on MauiImage that can control how it is resized and if at all.

on macOS desktop it doesn't work either

**Comment by MuneeshKumarG** [comment]
I have checked gif image in .Net Maui RC3. With below work around, gif working fine with WinUI. 

<MauiImage Update="Resources\Images\walking.gif" Resize="False" />

But still issue reproducing in Android.

**Comment by mattleibow** [comment]
@MuneeshKumarG Is this your issue? https://github.com/dotnet/maui/issues/7019 If not, please open a new issue related to your specific issue on Android.

**Comment by rynjas** [comment]
@mattleibow 

As you can see in the sample below, I tried the workaround, but the gif doesn't work in iOS/macOS and Android.
https://github.com/rynjas/GifMauiSample

**Comment by rynjas** [comment]
@mattleibow 
When connected to hotreload on the Android platform, the animation does not work. 
If you set IsAnimationPlaying to false and then back to true, while in hot reload mode, it should work.

Besides the hot reload issue, Android is working fine, but iOS and macOS are still not working

**Comment by Dio-rep** [comment]
Where i add this ? `<MauiImage Update="Resources\Images\*.gif" Resize="False" />`

**Comment by NonameMissingNo** [comment]
> Where i add this ? `<MauiImage Update="Resources\Images\*.gif" Resize="False" />`

In the app.xaml where the splashscreen, and similars are

**Comment by rynjas** [comment]
@Dio-rep  Could you please check this sample code and my comments above?
https://github.com/rynjas/GifMauiSample

**Comment by angelru** [comment]
any news about this?

**Comment by legrignotin** [comment]
Any news about this? Or at least a workaround?
Definitely a must have for my application

I am downloading the gifs as imagesource from my server so I cannot use the "resize trick"

**Comment by Vpatel541** [comment]
The resize trick doesnt seem to work for me

**Comment by Muhammadfaizann** [comment]
The resize trick doesn't seem to work for me either

**Comment by Muhammadfaizann** [comment]
does not play on android aswell

**Comment by akycdi** [comment]
Is there any alternative way to render a gif now? in maui.

**Comment by T-T-P** [comment]
Is this going to be resolved in .NET 7 MAUI or is this issue now only part of the .NET 8 timeline?

**Comment by liveinvarun** [comment]
@jamesmontemagno  created a control long back for the Xamarin IOS for supporting GIF's. If you use that code it will work in MAUI in net7. Request you to try that  => https://gist.github.com/jamesmontemagno/7619563

**Comment by Goldstrike** [comment]
> https://gist.github.com/jamesmontemagno/7619563

Is it possible to use this in a Handler?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 2.0. Repro on iOS 16.2 with mentioned project <https://github.com/rynjas/GifMauiSample>
![image](https://user-images.githubusercontent.com/37974803/230816548-c2940421-68ca-4e2f-b64a-c24330eb1ab5.png)

**Comment by fariz-huseynov** [comment]
I also encounter the same issue :(

**Comment by cat0363** [comment]
I got around this issue by the following method.

GIFImage.cs

    public class GIFImage : Image
    {
    }

MauiProgram.cs

    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
            builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .ConfigureMauiHandlers(handlers =>
            {
    #if IOS
                handlers.AddCompatibilityRenderer(typeof(GIFImage), typeof(Microsoft.Maui.Controls.Compatibility.Platform.iOS.ImageRenderer));
    #endif
            });

        return builder.Build();
    }

How to use is as follows.

    <local:GIFImage Source="xxxxx.gif" IsAnimationPlaying="True" />
    
Using the Xamarin.Forms renderer is a workaround, but not a solution.
Until this issue is resolved, I will work around using the method above.
I hope the underlying problem is resolved.

**Comment by xufeitt** [comment]
Where is the Platform.iOS.ImageRenderer code ?

**Comment by cat0363** [comment]
Hi, @xufeitt 
No need to write any ImageRender code. Use the one below.
Microsoft.Maui.Controls.Compatibility.Platform.iOS.ImageRenderer

**Comment by Sohel3798** [comment]
@cat0363 can you provide demo zip please

**Comment by Aqsa-Aftab** [comment]
can i play GIF on splash screen of .net maui

**Comment by umeshkamble** [comment]
> > https://gist.github.com/jamesmontemagno/7619563
> 
> Is it possible to use this in a Handler?

[Gif Animation Sample](https://github.com/umeshkamble/GifAnimation)

**Comment by ledwardsfoodzee** [comment]
Has this been fixed yet for IOS ? running this on .NET 8 and still can't render GIF's

**Comment by akycdi** [comment]
@ledwardsfoodzee  Nope still haven't fixed it on IOS but works well with Android

**Comment by billreiss** [comment]
I've had some luck using WebView to display GIFs on iOS and Android, I am working on a sample, if anyone needs something sooner let me know.

**Comment by ledwards26** [comment]
I’d love a sample if you have one?

**Comment by naaeef** [comment]
Hi @ledwards26 
What worked for me was writting a custom image handler with the code from the following PR https://github.com/dotnet/maui/pull/17207

**Comment by billreiss** [comment]
Here is my sample of using the WebView on iOS to load the GIF file. https://github.com/billreiss/MauiGifWebView

**Comment by markmccaigue** [comment]
Hi @mattleibow this is a feature we'd love to see. Just curious what the latest thoughts are within the team regarding the two PRs?
