### ISSUE TITLE
SVGs not showing on iOS

### ISSUE THREAD

**Issue by eamonn-alphin** [dotnet/maui#8663]
### Description

SVG files, used an an image source show up in android, but not in iOS. The space is there, if you color the background you can see a rectangle, but no image shows up. 

### Steps to Reproduce

1. New maui file, etc. So you can display an image. 
2. 
```
Image imageTest = new(){
    Source = ImageSource.FromFile("my_svg_image.svg"),
    WidthRequest = 100,
    HeightRequest = 100
}
```
3. Copy the svg file into Resources/Images
4. Right click on the the my_svg_image.svg file and choose BuildAction>MauiImage
5. Ensure the line
```
<MauiImage Include="Resources\Images\my_svg_image.svg"/>
```
is there. 

Build and run for both platforms. 

You should see the image show up on android, but not on ios. 

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 15.5

### Did you find any workaround?

Pngs work without any problems, but I want to use SVGs.

**Comment by SteveJML** [comment]
Have you tried the image source without the .svg extension? I am calling my images without the extension as i had similar problems.

**Comment by NonameMissingNo** [comment]
You see, you should call them in ".png" (at least for now) as they are being made into one

**Comment by eamonn-alphin** [comment]
> Have you tried the image source without the .svg extension? I am calling my images without the extension as i had similar problems.

welp. that worked. @NonameMissingNo was right, i guess? it's converting the SVGs into pngs or something, because removing the file extension worked.
