### ISSUE TITLE
Avoid the need for custom MarkupExtension to load embedded images

### ISSUE THREAD

**Issue by mgoertz-msft** [dotnet/maui#8666]
### Description

The [MAUI documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/image#load-an-embedded-image-in-xaml) says you need to write your own MarkupExtension to load embedded images from XAML. That should not be necessary.

It would be great if MAUI would support a resource URI syntax that would allow adding an assembly name just like it does for resource dictionaries.

### Public API Changes

```xaml
<Image Source="embedded_icon.png;assembly=iconlibrary.dll" />
```

### Intended Use-Case

Images embedded in local or external assemblies.

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix ^^^

**Comment by janseris** [comment]
Yeah this should be builtin

**Comment by StephaneDelcroix** [comment]
@mgoertz-msft actually, `<Image Source="foo.png" />` doesn't load an image from an embedded resource, but defaults to os loading capability. We could implement this feature by treating them like embedded resources, but iirc those aren't the fastest places to load images from (android and iOS store images in the app package)

**Comment by dotMorten** [comment]
@mgoertz-msft Silly question but is there a reason you're using embedded images over `<MauiImage />` ? AFAIK it's always been poor practice to load an assembly up with binary resources, since the entire assembly gets loaded into memory and thus reduces startup time and increases resource use.

**Comment by mgoertz-msft** [comment]
@dotMorten That was more about usability of the API. If embedded images shouldn't be used then we shouldn't even have and document this markup extension approach. If however this is supposed to be a supported scenario then we should make it easier to use.

**Comment by dotMorten** [comment]
I wonder if this left-over from Xamarin.Forms where people often resorted to EmbeddedImages because there wasn't a clean way to get images to work on all platforms.

**Comment by mgoertz-msft** [comment]
Good question. @Redth, do you know?

**Comment by Redth** [comment]
I would guess it’s as @dotMorten suggested and leftover from old docs migrated over. @davidbritch is that plausible?

As was also mentioned earlier this isn’t a great practice and we wouldn’t recommend it for a variety of reasons (performance, lack of multi dpi support). 

Perhaps it should be removed from the docs. We have no plans to help enable this approach.

**Comment by davidbritch** [comment]
Yes, it's carried over from Forms. I'll delete it.

**Comment by mgoertz-msft** [comment]
Thanks everyone! I'm closing this issue as Not Planned then.
