### ISSUE TITLE
Windows: Package name is not replaced in package.appmanifest (maui-package-name-placeholder)

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#8670]
### Description

In a Maui App runnning on windows,  `AppInfo.Current.PackageName` is not set to the `ApplicationId` msbuild property.

This property is set in the csproj file, and used by Maui to set the package name for all platforms.

### Steps to Reproduce

1. Create a maui app using the default template
2. Edit the csproj file and replace or add in the first `PropertyGroup`:  
```<ApplicationId>eu.vapolia.svgmauidemo</ApplicationId>```
3. Start the app on the windows platform, in debug mode, with a breakpoint on the first line of `AppShell.xaml.cs` for example
4. In the immediate window of the debugger, observe the value of `AppInfo.Current.PackageName` (or ` Windows.ApplicationModel.Package.Current.Id.Name`)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

In Package.appxmanifest, the package name is set to `maui-package-name-placeholder`.  
I tried replacing it with `$placeholder$` but that don't work.

I replaced it with the same value set in the ApplicationId property instead.

**Comment by Eilon** [comment]
Looks like this code is supposed to replace the hard-coded value `maui-package-name-placeholder` with a the ApplicationId:

https://github.com/dotnet/maui/blob/main/src/SingleProject/Resizetizer/src/GeneratePackageAppxManifest.cs#L95

Not sure why it isn't doing that here...

**Comment by softlion** [comment]
> Looks like this code is supposed to replace the hard-coded value `maui-package-name-placeholder` with a the ApplicationId:
> 
> https://github.com/dotnet/maui/blob/main/src/SingleProject/Resizetizer/src/GeneratePackageAppxManifest.cs#L95
> 
> Not sure why it isn't doing that here...

```if (!Guid.TryParse(ApplicationId, out _))```

ApplicationId can be any string, not only a guid ?

**Comment by mattleibow** [comment]
Fixed in https://github.com/dotnet/maui/pull/5695

Apps need to also specify the `<ApplicationGuid>` or use a `Condition` on `<ApplicationId>` for Windows.

Windows apps do not support reverse domains but require a GUID.
