### ISSUE TITLE
Add iOS native library

### ISSUE THREAD

**Issue by vasile135** [dotnet/maui#8679]
### Description

In Xamarin there is the possibility to add a reference to a native iOS library:
![image](https://user-images.githubusercontent.com/58006892/178511871-543edf5f-7c4c-4a0e-9543-23f05b22c357.png)
Didn't find the solution to do the same in MAUI.

### Public API Changes

-

### Intended Use-Case

Need to migrate from Xamarin Forms to MAUI, but it is impossible as cannot bind some key functionality native libraries.

> VS bug [#1775499](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1775499)

**Comment by jfversluis** [comment]
This is a Visual Studio/tooling issue. Reporting it there should yield more response. Sorry it took a while!

Even though this tooling makes it easier, this is definitely possible without the tooling in place for this.
