### ISSUE TITLE
[Shell][Win] No animal like a Xaminal

### ISSUE THREAD

**Issue by davidbritch** [dotnet/maui#8714]
### Description

I've ported Xaminals from Xamarin.Forms to .NET MAUI. Largely, it works. The main area that doesn't work is search handler templates on Windows.

Here's the search handler result on Android, showing the templated results:

![Screenshot_1657724021](https://user-images.githubusercontent.com/8092460/178771315-fe3a3bcf-3bff-4845-b6af-180bb36942fe.png)

All is as it should be. However, here's the same result on Windows. Instead of showing the templated results it just shows the type name for each result:

![Capture1](https://user-images.githubusercontent.com/8092460/178771432-733e827d-fd02-4212-9ef8-a10067ad0b77.PNG)

Repro:
[Xaminals.zip](https://github.com/dotnet/maui/files/9103603/Xaminals.zip)

### Steps to Reproduce

1. Run the attached sample on Windows.
2. Use the search handler, on any page.

### Version with bug

6.0.408

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by ToolmakerSteve** [comment]
Cute title, but title should summarize the bug. :)

**Comment by jsuarezruiz** [comment]
The ItemTemplate property of the AutoSuggestBox is never set.
