### ISSUE TITLE
The ScrollTo method does not carry the element in a grouping

### ISSUE THREAD

**Issue by hprez21** [dotnet/maui#8718]
### Description

When a CollectionView is populated with grouped data, the ScrollTo method does not lead to the item indicated by the parameters.

When I invoke the method through:

```
     private void Button_Clicked(object sender, EventArgs e)
     {
          collectionView.ScrollTo(0, 4);
     }
```
![hu3w1AZFwY](https://user-images.githubusercontent.com/9836726/178795584-b2c997bd-20d4-4b51-9896-fc855f12ef46.gif)

it is supposed to navigate to the first element of the fourth group, however, in the attached gif, you can see how nothing happens when you click on the button and the listing is on the first element, while when you scroll to the end of the listing, and press the button, it does not lead to the element it should be.

Attached is the project in Github: https://github.com/hprez21/CollectionViewScrollToIssue

### Steps to Reproduce

1.- Download the Github repo
2.- Run the application, and test the button with the text "Manual Scrolling".

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 10, Windows 10

**Comment by rmarinho** [comment]
works on iOS

**Comment by pekspro** [comment]
Here is a workaround for Android:

``` CS
    int position; // Item position

#if ANDROID
    var recyclerView = MyCollectionView.Handler.PlatformView as AndroidX.RecyclerView.Widget.RecyclerView;

    int groupHeaderCount = ...; //Number of group headers above item to scroll to.

    // This will make sure the item is visible, but could be anywhere on the screen:
    recyclerView.ScrollToPosition(position + groupHeaderCount);

    // Scroll like this if you want make sure the item is on top.
    // The last parameter is number of pixels to be used as margin.
    // var layoutManager = recyclerView.GetLayoutManager() as AndroidX.RecyclerView.Widget.LinearLayoutManager;
    // layoutManager.ScrollToPositionWithOffset(position + groupHeaderCount, 0);
#else
    MyCollectionView.ScrollTo(position, position: ScrollToPosition.Center);
#endif
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android 13.0 with below Project:
[CollectionViewScrollToIssue.zip](https://github.com/dotnet/maui/files/11529596/CollectionViewScrollToIssue.zip)

Windows:
![Scroll-Windows](https://github.com/dotnet/maui/assets/97647558/1c30ed78-08db-4d98-b962-99f54e33d10e)

Android:
![Scroll-Android](https://github.com/dotnet/maui/assets/97647558/1e58e59e-18ef-4208-9359-8327f417f624)
