### ISSUE TITLE
ScrollView ignores child scale

### ISSUE THREAD

**Issue by AignerGames** [dotnet/maui#8719]
### Description

The ScrollView ignores the child scale value and doesn't allow scrolling if the child is too large (after scaling)

(Only tested on "Windows Machine")

### Steps to Reproduce

1, Add a ScrollView
2, Add any child, for example a Rectangle (it's easier to see with an Image) set WidthRequest and HeightRequest any values which are small enough so that the whole child is visible without scrolling
3, Run and the child should be visible, without any scrolling -> Good
4, Now add a Scale property to the child and set a large value, for example 10, so that the child doesn't fit the view anymore
5, Run again, the child is now too large for the ScrollView, but the ScrollView ignores the scaled size and still doesn't show any scrollbars

Expected behavior: The ScrollView should consider the whole size, including scale

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

A "workaround" would be to increase the WidthRequest and HeightRequest instead of the Scale value, but I use images which are loaded at runtime and have different size. So I would need different values for every image and it looks like the Image / ImageSource doesn't even have a property to get the "original" size of the actual image. 

Im used to WPF and a ScaleTransform was considered by the ScrollViewer there and showed the correct scroll size including the scaled size, so Im not sure if this is a bug or if this is intended behavior in MAUI

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on Windows platform.
![4](https://github.com/dotnet/maui/assets/77434865/5d07ed80-23af-4fdc-b000-69e0bf603157)
