### ISSUE TITLE
UI Automation Name of a Windows Maui CollectionView item isn't updated after a change to its DataTemplate's Grid's bound SemanticProperties.Description

### ISSUE THREAD

**Issue by gbarkerz** [dotnet/maui#8722]
### Description

Repro in https://github.com/gbarkerz/MyVeryFirstMauiApp.

The repro app presents a CollectionView with items which contain a Grid with two bound text strings. The first string is bound to a name of a bird, and the second to a bool which when true gets converted to a string saying "Ticked!". The Grid has a SemanticProperties.Description which is bound to an item property called AccessibleName, which is a concatenation of any text visually shown in the item.

When the app is first run, the UI Automation Name of the items is as expected. When an item is tapped, it changes visually to include the text "Ticked" as expected. The Accessibility Insights for Windows tool shows that the UIA Name property of a group element associated with the item, (the group element is presumably associated with the item's Grid), has been updated to reflect the new SemanticProperties.Description which includes the text "Ticked!".

However, the UIA Name of the UIA list item element associated with the CollectionView item has not been updated. It is expected that the list item's UIA Name is updated in the same way that the contained group element's UIA Name.

### Steps to Reproduce

1. Build and run https://github.com/gbarkerz/MyVeryFirstMauiApp on Windows.
2. Run Accessibility Insights for Windows, and verify the UIA list items' Names match the visuals shown on the items.
3. Tap on a couple of items in the app and verify the displayed text changes on the items.
4. Refresh Accessibility Insights for Windows and notice the UIA Name of the tapped groups' UIA Name is updated, yet the list items' UIA Names has not, as shown below.

<img width="582" alt="AIWinMaui" src="https://user-images.githubusercontent.com/77085891/178814371-cf679876-194d-47ea-bcd3-4954c4d4dcb3.png">

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by Raghu-addepalli** [comment]
GitHubTags:
#.NET MAUI; #A11ySev1; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win11; #WCAG1.3.1; #GH_.NETMAUI_Win32_Apr2022; #AILimited​; #Win32;
