### ISSUE TITLE
[IOS] #6574 REGRESSION InputTransparency always cascades to Children even when CascadeInputTransparent= false

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#8725]
### Description

This bug is a regression of https://github.com/dotnet/maui/issues/6574

The TapGestureRecognizer attached on Children of Layout will NOT function when Layout is set `InputTransparent = true`, and `CascadeInputTransparent= false`.

IMO the equally pressing underlying issue is that the empty space in a layout does not Allow input to go through (works like that on Android), which forces me to set it manually. 

### Steps to Reproduce

```
Content = new AbsoluteLayout
{
    InputTransparent = true,
    CascadeInputTransparent = false,
    Children =
    {
	    new BoxView
	    {
		    Color =Colors.Green,
	    }.LayoutFlags(Microsoft.Maui.Layouts.AbsoluteLayoutFlags.PositionProportional)
	    .LayoutBounds(0.5,0.7,100,100)
	    .TapGesture(() =>
	    {
		    Debug.WriteLine("This should be clicked but doesn't");
	    }),
    }
};
```

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by danielftz** [comment]
@hartez Thank you for the help last time and please take a look at this again.

**Comment by ToolmakerSteve** [comment]
@danielftz 
> empty space in a layout does not have InputTransparent = true, which forces me to set it manually.

That sounds like correct behavior. Given that the default for input transparency is to cascade to children, the default for InputTransparent on a layout must be false. Otherwise, nothing would be clickable in any layout.

**Comment by danielftz** [comment]
> @danielftz
> 
> > empty space in a layout does not have InputTransparent = true, which forces me to set it manually.
> 
> That sounds like correct behavior. Given that the default for input transparency is to cascade to children, the default for InputTransparent on a layout must be false. Otherwise, nothing would be clickable in any layout. "empty space" doesn't exist - the click goes to the layout itself in that case.

Even when` InputTransparent` on a layout is set to `false`, the empty space of that layout should still allow input to go through it (works like that Android), which doesn't work on iOS

**Comment by hartez** [comment]
@danielftz Which version of MAUI are you on? GA? Service Release 1? 2?

**Comment by danielftz** [comment]
> @danielftz Which version of MAUI are you on? GA? Service Release 1? 2?
Service Release 2

**Comment by hartez** [comment]
@danielftz Service Release 3 should be in the latest update of VS - does the problem still occur there? (I haven't been able to reproduce the issue, but it's possible that I'm missing something or that it's already been fixed.)
