### ISSUE TITLE
[Bug] Maui Preview.3.21202 was another shoddy Microsoft product

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/maui#873]
I can't think of a single time when Microsoft has made something that worked the first time. This release is no exception.  I went through the maui-check and it complained it couldn't find Xcode 12.4.  I had the version and after installing the latest version of Xcode it complained it couldn't find the SDK. Turns out you guys closed the error claiming victory, but it turns out to be a lie as usual.  I couldn't reopen the issue because the website doesn't function. I ignored the error and proceeded anyway.

I tried to build the the samples using the command line and this time  it stated I should fix the location of the Apple SDK in the preference dialog because it couldn't find the Apple SDK.  Isn't it dumb to tell you users that you cannot build the samples using VS 2019 for Mac, but then have an error message telling them to change a setting in VS 2019 for Mac? After a lot of wasted time, I was shocked to find out it needed a path to the Xcode application, not the SDK locations.  

Anyways, I was hoping to run the Mac version of Maui. This has been an exhausting waste of time.  You guys are incompetent and everything you guys do sucks!

**Comment by GeraudFabien** [comment]
> You guys are incompetent and everything you guys do sucks!

Thanks for that kind and useful message. But has the name state Preview.3.X so it's not the first release. It's normal to have rough edge. That is not a reason to react like that. 

> I can't think of a single time when Microsoft has made something that worked the first time.

Since it's a preview it's not even the first time (release). The error describe seems to come from you so can we say it didn't work.... There is a lack of doc on the subject but that expected from a preview no?

I'm not linked from MS or the dotnet foundation in any way.

**Comment by GeraudFabien** [comment]
https://github.com/statiqdev/Statiq.Web/issues/946

It's not the first time it seems. But i read some of you're important issue and you never reply after posting the issue. Not very useful. Open Source a really good punching bag this year.

**Comment by CodingJinxx** [comment]
Really useful and kind message, thank you so much for trying to improve maui

**Comment by hartez** [comment]
Sounds like you're having problems with the dotnet-maui-check tool; I'd suggest opening a bug in [that repo](https://github.com/Redth/dotnet-maui-check/issues?q=is%3Aopen+is%3Aissue).

**Comment by Joebeazelman** [comment]
The sarcasm "thank you so much for trying to improve maui" needs to be addressed.  I've been working with Microsoft products for decades. I used to be their biggest advocate, but over the past decade or so, the quality of their products have been terrible. Where do I even begin?  There are so many issues that are so painfully obvious.  How can a product be released with so many flaws.  It's not just the developer products.  It's every single product they develop!  There are bugs in Excel, for instance, that haven't been fixed for several decades!

I just realized that a lot of my frustration comes from believing a Microsoft product will work, but turns out to be an enormous waste of time. I am going through this with Xamarin Forms on the Macintosh where VS 2019 craps out and can't save a file. When I restart it, it mysteriously works!  

It's alarming when the number of people who are recommending VS Code and Rider over VS 2019. You'd think Microsoft would do everything possible to stave off competition.  At the very least, you'd expect them to make their paid version of Visual Studio better than the free VS Code. 

Many say Microsoft has become an old farty of a tech company, but when you compare them to Apple, a company as old, if not older, it just doesn't hold much water.  The quality of Apple's products are near flawless.  They continually out innovate their competitors and are a stunning example of excellence. 

It's really time to become an Apple developer exclusively. I dread the idea of learning Swift or objective C, but it can't be any worse than dealing with Microsoft's mediocrity.

**Comment by GeraudFabien** [comment]
> How can a product be released with so many flaws.

Again it is not release. It's a preview. 

> competition

VS code is from MS it's not a competitor (and it's not an IDE).

> The quality of Apple's products are near flawless.

We clearly have not the same experience with apple.

> Many say Microsoft has become an old farty of a tech company, 

Well with Azure, Xbox, Surface, Hololens, VSCode, TypeScipt, Office365, Teams and all solution related to IA.  That for the "new" (After 2000) product that work very well.
Gtihub, NPM, Electron, Atom are all microsoft product buy through github and that still work.
I'm pretty sure a lot of company would like to have that much popularity.

VS for mac is a "new" implementation. And yes MS has a really hard time to do VS for mac.

> It's really time to become an Apple developer exclusively.

Please do. That a great idea. Just remember no Javascript or typescript and github. That the only way to not use MS techno. No VS code also.  Has for team work no Azure devops, TFS, ...

> But it can't be any worse than dealing with Microsoft's mediocrity.

Sad they had to deal with you.
