### ISSUE TITLE
yes 6.0.408 

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#8731]
### Description

so nice after so loong time a new version.

but the problem is
MAUI=cross platform..

what is the point of using it if it not working on mac.. or what is basic standart stuff.. not working..

in mac version is 6.0.312

### Steps to Reproduce

:)  

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

mac os

**Comment by PirasathLuxchumykanthan** [comment]
why did u close it... u cant handle the true.. or ppl that really love xamarin... dont need to know whats going on ?

**Comment by samhouts** [comment]
Duplicate of #8747
