### ISSUE TITLE
WebView cannot show all web page content

### ISSUE THREAD

**Issue by RayWangQvQ** [dotnet/maui#8738]
### Description

Some web page in WebView shows empty.

Link: https://plogin.m.jd.com/joinlogin/static/agreement.html?agreement=register_info
Real web page in browser:
![image](https://user-images.githubusercontent.com/31154238/179025840-4c96f9d2-af8d-4585-9b10-c6333808ee59.png)

In MAUI WebView, it shows empty:
![image](https://user-images.githubusercontent.com/31154238/179026830-e6000660-54d9-410c-be61-886a789a04d0.png)

At beginning, I thought it was zoom, so I put it into grid and color the background, but it still not work:

![image](https://user-images.githubusercontent.com/31154238/179028543-f3d6a551-4b93-485c-a028-ef71823fa573.png)

And not just this web page, I found there are many web pages that are same situation when I browser and jump in MAUI WebView.

I don't know why the WebView cannot show all content for some web pages.

### Steps to Reproduce

It is easily to reproduce,

For `MainPage.xaml` code:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="RayJdCk.MainPage"
             Title="Test">
    <WebView Source="https://plogin.m.jd.com/joinlogin/static/agreement.html?agreement=register_info"
             WidthRequest="350" 
             HeightRequest="500"/>
</ContentPage>
```

For `MainPage.xaml.cs` code:

```
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
    }
}
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by ni-xue** [comment]
@drasticactions  关于这个我 在去年 就发现了 需要优先确认 打开的页面是否本身就是这样的屏幕支持 然后才能考虑 安卓对应的版本 这和maui可能关系不大 我之前也提过相关 事件失效问题 不过那都是 半年以前了。

**Comment by RayWangQvQ** [comment]
> 
`屏幕支持`是指屏幕尺寸吗？但我使用同一个安卓手机的浏览器去浏览相同页面，是没有问题的。
BTW，你半年前的问题解决了吗？是怎么解决的？能否分享下参考意见，谢谢。

**Comment by RayWangQvQ** [comment]
And I tried it on an IOS device just now, it works fine with out any problems.

But on Android, I tried almost all settings about WebView, it still shows empty...

I don't know much about Android, is there any friends meet similar problems? Whether with MAUI or 
native Android.

**Comment by RayWangQvQ** [comment]
20220811 update：
I tried `flutter`, it works fine with Android, without any redundant settings or actions, just simple WebView widget...

**Comment by jichulu** [comment]
FYI #9517

**Comment by Gypsy-H-Takumi** [comment]
I am having this issue as well.
Yes. I worked as using below code. https://github.com/dotnet/maui/issues/9517#issue-1342860229
`webview.LayoutParameters = new Android.Views.ViewGroup.LayoutParams(-1, -1);`

**Comment by jonpryor** [comment]
Android + Native Java suffers from the same problem.  (Sample Java project: [Scratch.Gda8738.zip](https://github.com/dotnet/maui/files/9636789/Scratch.Gda8738.zip))

I believe that the problem is that [agreement.html](https://plogin.m.jd.com/joinlogin/static/agreement.html?agreement=register_info) loads its content via JavaScript, and the WebView does not appear to be evaluating that JavaScript; abbreviated contents:

```html
<body style="margin:0">
    <header>
        <span id='txt-header' class="txt-header">协议</span>
    </header>
    <script>
        var agree = …
    </script>
</body>
```

Given that MAUI and .NET Android are behaving the same as native Java, I do not consider this to be a bug.

Rather, this is either a deficiency in `WebView`, or "more" needs to be done with the `WebView` instance.

Possibly related? The [WebView documentation](https://developer.android.com/reference/android/webkit/WebView) states:

> In most cases, we recommend using a standard web browser, like Chrome, to deliver content to the user. To learn more about web browsers, read the guide on [invoking a browser with an intent](https://developer.android.com/guide/components/intents-common#Browser).

**Comment by RayWangQvQ** [comment]
If that's what you said, I suppose that Flutter has been optimized for this situation to make it run normally (because the same page can run directly in Flutter without any other operation or config).

So I want to know whether MAUI will do similar optimization work to make it work normally, just like flutter.

**Comment by RayWangQvQ** [comment]
As I am a dotneter, I prefer MAUI to flutter, but this problem has puzzled me for a long time, so I temporarily switched to using flutter...

For this issue is closed, if anyone can see my question, please give me some suggestions, I hope I can switch back to MAUI from flutter, some time in the future.
