### ISSUE TITLE
Maui Blazor IOS platform opens script tag url in the browser

### ISSUE THREAD

**Issue by pramod-kun** [dotnet/maui#8741]
### Description

I am trying to run .NET Maui Blazor in an iOS simulator, I included stripe SDK in the body section of my index.html file.
  <script src="https://js.stripe.com/v3/"></script>

When running the app on an iOS simulator, the URL opens in the browser.  The same app runs fine on android and windows, this is only happening on the iOS platform

![ios-maui](https://user-images.githubusercontent.com/106889203/179056918-4bd7879d-4b24-4109-8ac4-f3f97f0d35de.jpg)

### Steps to Reproduce

- Create a new Maui blazor app 

- Add  <script src="https://js.stripe.com/v3/"></script> in the body section of index.html (present in wwwroot folder)

- Run on an iOS simulator.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by javiercn** [comment]
@pramod-kun thanks for contacting us.

Does this behavior occur in a Maui app using a regular Webview? (No Blazor involved)

**Comment by pramod-kun** [comment]
Hello, I do not know how you use script tag in Maui app with Webview to include SDK. Maybe my explanation was not clear, I do not want the URL to open in a new tab.

**Comment by pramod-kun** [comment]
Hello @javiercn, I did the following to check the behavior on Webview - 

- Created a simple HTML file with the following content

> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="utf-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
>     <title>MyTestApp</title>
> </head>
> 
> <body>
>     <h1 style="text-align:center;color:orangered;margin-top:150px">Hello World!</h1>
>     <script src="https://js.stripe.com/v3/"></script>
> </body>
> </html>


- Added the html file to the Resources/raw folder
- Used Webview in the MainPage.xaml

 `    <WebView  Source="index.html">
        </WebView>`

The above code worked on Android and Windows but not on iOS. (Error - System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.')

- I changed the Web view source from index.html to "https://appdir/index.html" . It worked on Windows and iOS displayed a blank-screen.



![iosblankscreen](https://user-images.githubusercontent.com/106889203/179781681-eb4e6a0d-7277-43b0-a37e-0c8a89a2cb41.jpg)

**Comment by pramod-kun** [comment]
@javiercn , thank you for responding quickly. 
There are no errors when I inspect the simulator using safari Web inspector. I checked the log files of the system and simulator, there are no errors.

**Comment by javiercn** [comment]
@pramod-kun It can be that the script might have some built-in logic to detect it is being loaded inside a webview and trigger that behavior.

You might be able to setup a breakpoint on the developer tools to detect who and what is triggering the navigation, but it seems something in your code is doing it.
