### ISSUE TITLE
Can't install Release 6.0.408 on macOS

### ISSUE THREAD

**Issue by tobiasschulz** [dotnet/maui#8747]
### Description

I can't get the version from 2 days ago (6.0.408) to install on macos in any way.
I always get version 6.0.312.

Why is there no correct rollback file?

https://aka.ms/dotnet/maui/6.0.408.json -> is not a valid link
https://aka.ms/dotnet/maui/6.0.400.json -> redirects to https://maui.blob.core.windows.net/metadata/rollbacks/6.0.400/6.0.400.json

It's strange that https://maui.blob.core.windows.net/metadata/rollbacks/6.0.408/6.0.408.json does exist, but doesn't result in the right versions being installed.

### Steps to Reproduce

sudo dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/6.0.408/6.0.408.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.400

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

all

**Comment by tobiasschulz** [comment]
What is the correct rollback file for 408? and which nuget sources are required?

All the MAUI packages on nuget.org have a 408 version:
https://www.nuget.org/packages/Microsoft.Maui.Dependencies

But i can't get them to install on macos, neither with stable or preview dotnet (which is 6.0.400-preview.22330.6 for me to be exact)

**Comment by arkadym** [comment]
@tobiasschulz were you able to revert to 400 build ? I've updated today, by default it is installed as 430, i did tested and about there are layout issues, e.g. VerticalStackLayout is not able to handle when item expands inside it, it draws new content over exisiting. It was fine with 400 build, i have bin create few days ago and it still works. So i decided revert to 400 but after i installed https://aka.ms/dotnet/maui/6.0.400.json , and did clean and rebuild issue still there (.

**Comment by tobiasschulz** [comment]
No but i was using nightly builds the past few days, but now I can't get them anymore either, instead whatever i do I get the old 312 version.

**Comment by arkadym** [comment]
@tobiasschulz could you tell me how to get back to 312 ?

**Comment by tobiasschulz** [comment]
312 doesnt make sense for me at all because of a number of issues that are fixed in newer versions,
but this is how I get 312 now,
I used to be able to get nightly builds until the 408 release like this, but maybe you get 312 too if you run:

`
dotnet nuget locals all --clear
sudo dotnet nuget locals all --clear


sudo dotnet workload install maui \
  --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json \
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json \
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json \
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json \
  --source https://api.nuget.org/v3/index.json

`

**Comment by tobiasschulz** [comment]
Nightly builds worked fine, because all the bugs that I needed to be fixed were fixed, but now, it downgraded to the old GA stable version, and 408 won't install, so I basically can't work anymore right now

**Comment by tobiasschulz** [comment]
So i guess, two questions 

1. What is the rollback file URL and the sources for 408?
2. What is the rollback file URL and the sources for nightly?

And it would be really great if that information was documented and kept up to date.

Right now my app doesn't work because of the old GA version of MAUI and I can barely work on it that way.

**Comment by ScofieldOY** [comment]
I tried the following cmd, but it will upgrade to 6.0.447
`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json --source https://api.nuget.org/v3/index.json`

**Comment by mattleibow** [comment]
Hi folks, I have created an aka.ms for the maui version: https://aka.ms/dotnet/maui/6.0.408.json 

The OP posted that the full uri did not work for 408 "but doesn't result in the right versions being installed." This is due to a bug in the 400 SDK previews: https://github.com/dotnet/installer/pull/14134

Unfortunately, if you had installed the previews that were broken, it does not auto-fix itself. The current workaround is to delete the following subfolders from the <dotnet_sdk_root>/sdk-manifests/6.0.400/ folder:

 - microsoft.net.sdk.android
 - microsoft.net.sdk.maui
 - microsoft.net.workload.emscripten
 - microsoft.net.workload.mono.toolchain

You should just be left with the following:

 - microsoft.net.sdk.ios
 - microsoft.net.sdk.maccatalyst
 - microsoft.net.sdk.macos
 - microsoft.net.sdk.tvos

**Comment by tobiasschulz** [comment]
Ok thanks, i will try that 👍

**Comment by ScofieldOY** [comment]
@mattleibow currently, MAUI workload 408 works well in my local with SDK 300, but MS has stated before that the MAUI workloads are tightly coupled to the SDK. I don't know if that is still the case after GA or we don't need to worry about this mapping?
`
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.408.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
`
global,json
`{
  "sdk": {
    "version": "6.0.300",
    "rollForward": "disable"
  }
}
`

**Comment by beeradmoore** [comment]
@mattleibow I deleted those folders and VS4Mac Preview 4 now says it has updates for workloads which it says is
```
6.0.400-preview.22330.6

.NET MAUI SDK for all platforms (6.0.419)
.NET MAUI SDK for Android (6.0.419)
.NET MAUI SDK for Mac Catalyst (6.0.419)
.NET MAUI SDK for iOS (6.0.419)
```

But 419 is not 408, so I assume VS4Mac Preview which supports MAUI is trying to also install MAUI previews? But to work on MAUI stable apps on macOS we need to use VS4Mac Preview, which is going to install MAUI preview?

VS4Mac Preview 4 updater tried to install these workloads but failed anyway,
[Updater-10153.log](https://github.com/dotnet/maui/files/9146937/Updater-10153.log)

From terminal I did
```
sudo dotnet workload update
```
and it told me 
```
Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.400-preview.22330.6
```
so I assume that is why it is 419?

```
dotnet workload list

Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------
maui-maccatalyst            6.0.419/6.0.300       SDK 6.0.400        
maui-ios                    6.0.419/6.0.300       SDK 6.0.400        
maui-android                6.0.419/6.0.300       SDK 6.0.400        
maui                        6.0.419/6.0.300       SDK 6.0.400        
```

I don't want to deal with previews of either dotnet or MAUI, I just want stable dotnet and stable MAUI.

I run what I expect is the update command from these threads
```
dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.408.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
```
and it now looks like its all correct
```
Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------
maui-maccatalyst            6.0.408/6.0.300       SDK 6.0.400        
maui-ios                    6.0.408/6.0.300       SDK 6.0.400        
maui-android                6.0.408/6.0.300       SDK 6.0.400        
maui                        6.0.408/6.0.300       SDK 6.0.400 
```

I hope this comes through as how confusing it is currently to update. The need to guess URLs and hope they exist, to stay away from VS4Mac Preview updates but also need to update it to use it for MAUI development anyway (unless VS4Mac 2022 has MAUI support and I missed that announcment?). I don't follow what is stable/GA and what is preview. I don't follow what and where we are meant to be developing our apps. I am getting exhausted playing command line jenga every time I was to update so I can try continue working with MAUI. 

I hope the team can continue to communicate the processes more clearly in the future, rather than leaving outdated things around like the [wiki](https://github.com/dotnet/maui/wiki/macOS-Install) which guides you to install RC3.

**Comment by beeradmoore** [comment]
Unless I am mistake 6.0.424 is now live as my system and nuget package manager just updated a bunch of stuff.

**Comment by arkadym** [comment]
Could anyone help , somehow cannot get 486 on Windows, on mac i just run dotnet workload update and it upgraded to 486 (which i trust is SR 4?). I did upgrade VS to preview 6. When i run `dotnet workload update` i'm getting this error
```
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.sdk.ios: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.ios.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.workload.emscripten: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.workload.emscripten.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.sdk.android: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.android.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.sdk.tvos: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.sdk.macos: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.macos.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.workload.mono.toolchain.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
Failed to update the advertising manifest microsoft.net.sdk.maui: Failed to fetch results from V2 feed at 'https://nuget.telerik.com/nuget/FindPackagesById()?id='microsoft.net.sdk.maui.manifest-6.0.400.msi.x64'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 401 (Logon failed.)..
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
```

But when run `dotnet workload list`
```
Installed Workload Ids      Manifest Version                              Installation Source
---------------------------------------------------------------------------------------------
maui-android                6.0.486/6.0.400                               VS 17.3.32728.150
maui-windows                6.0.486/6.0.400                               VS 17.3.32728.150
android                     32.0.448/6.0.400                              VS 17.3.32728.150
maui-maccatalyst            6.0.486/6.0.400                               VS 17.3.32728.150
maccatalyst                 15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32728.150
maui-ios                    6.0.486/6.0.400                               VS 17.3.32728.150
ios                         15.4.446-ci.-release-6-0-4xx.446/6.0.400      VS 17.3.32728.150

Use `dotnet workload search` to find additional workloads to install.
```
It looks like it is upgrade but not everything...

**Comment by mattleibow** [comment]
@arkadym it seems your issue is that there are telerik feeds. Maybe when running the CLI, use the `--source https://api.nuget.org/v3/index.json` and then this should fix it.

**Comment by arkadym** [comment]
> @arkadym it seems your issue is that there are telerik feeds. Maybe when running the CLI, use the `--source https://api.nuget.org/v3/index.json` and then this should fix it.

```
PS C:\Users\Arkady> dotnet workload update --source https://api.nuget.org/v3/index.json

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.400

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

Failed to update the advertising manifest microsoft.net.sdk.ios: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\5cae6df5-cf25-41dd-a956-29c3558bd9eb\data\Microsoft.NET.Sdk.iOS.Manifest-6.0.400.15.4.447-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\490bc94a-72ec-42ab-bf60-471524c893e9\data\Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.15.4.447-x64.msi.
Failed to update the advertising manifest microsoft.net.workload.emscripten: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\a0fae365-4e22-41e1-a09f-a508414667f5\data\Microsoft.NET.Workload.Emscripten.Manifest-6.0.300.6.0.4-x64.msi.
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\a88e05fb-a89d-45fb-b4c3-b948b63e0809\data\Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.8-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.macos: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\1639b1da-c39c-462e-80e3-aa4291de11d1\data\Microsoft.NET.Sdk.macOS.Manifest-6.0.400.12.3.447-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.maui: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\e5fbe2ce-7c7c-47aa-8046-4caac120ba06\data\Microsoft.NET.Sdk.Maui.Manifest-6.0.400.6.0.486-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.tvos: Failed to extract information from MSI: C:\Users\Arkady\AppData\Local\Temp\915ad417-5181-4bc2-9cd9-b644728170c0\data\Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.15.4.447-x64.msi.
Updated advertising manifest microsoft.net.sdk.android.
Downloading Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 (6.0.8)
Downloading Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64 (6.0.8)
Downloading Microsoft.NET.Runtime.MonoTargets.Sdk.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 (6.0.8)

Successfully updated workload(s): maui-android maui-ios maui-maccatalyst maui-windows.

PS C:\Users\Arkady> dotnet workload list

Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------------------------------------
maui-android                6.0.496/6.0.400       SDK 6.0.400, VS 17.3.32804.467, VS 17.3.32728.150
maui-ios                    6.0.496/6.0.400       SDK 6.0.400, VS 17.3.32804.467, VS 17.3.32728.150
maui-maccatalyst            6.0.496/6.0.400       SDK 6.0.400, VS 17.3.32804.467, VS 17.3.32728.150
maui-windows                6.0.496/6.0.400       SDK 6.0.400, VS 17.3.32804.467, VS 17.3.32728.150
ios                         15.4.447/6.0.400      VS 17.3.32804.467, VS 17.3.32728.150
android                     32.0.451/6.0.400      VS 17.3.32804.467, VS 17.3.32728.150
maccatalyst                 15.4.447/6.0.400      VS 17.3.32804.467, VS 17.3.32728.150

Use `dotnet workload search` to find additional workloads to install.

Updates are avaliable for the following workload(s): maui-android. Run `dotnet workload update` to get the latest.
```

**Comment by mattleibow** [comment]
This appears to be some issue with the updating as something was done, but the warnings and additional updates look suspicious.

Maybe open an issue on the dotnet/sdk repo with this lot output so they can have a look.
