### ISSUE TITLE
Windows - TextToSpeech.Default.SpeakAsync  is not awaited.

### ISSUE THREAD

**Issue by pierre01** [dotnet/maui#8753]
### Description

On Windows: TextToSpeech.Default.SpeakAsync is taking a very long time before executing.
To the point it is not usable for utterances that are supposed to last less than 1 seconds.

### Steps to Reproduce

https://github.com/pierre01/TimerFaceMockup

Run on Windows. Then Run on an Android device.
On Windows the TTS lags, like it is not correctly awaiting.
On android it is in sync with the other animations and works fine.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro (latest)

### Did you find any workaround?

No

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on windows platform with above project.
https://github.com/pierre01/TimerFaceMockup
![demo2](https://github.com/dotnet/maui/assets/82450723/60457ec9-f64a-45cc-b166-13b65fa18a3e)
