### ISSUE TITLE
VoiceOver is reading invisible control.

### ISSUE THREAD

**Issue by Karan4495** [dotnet/maui#8754]
GitHubTags:
#.NET MAUI; #A11ySev3; #A11yTCS; #iOS; #iPad; #WCAG1.3.1; #BM_.NETMAUI_IOS_Jul2022; #Info and Relationships​; #AINotInScope;

### Description

VoiceOver is reading invisible control and also focus is moving to invisible control.

### Steps to Reproduce

1.Install and open ".NET MAUI" app.
2.Swipe till "search box" and enter recipe name and search.
3."Serach result" page will open.
4.Verify VoiceOver is reading invisible control or Not.

https://user-images.githubusercontent.com/100186395/179176627-27ff9be5-deaf-42ec-b4db-e7251dc29734.mp4

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5(iPad)

### Relevant log output

```shell
VoiceOver should not read invisible control and focus should not move to invisible control.
```

**Comment by merriemcgaw** [comment]
@Karan4495 please validate this fix as soon as possible so it can be closed. Thanks!

**Comment by Karan4495** [comment]
Verified issue in ".NET MAUI" app. issue fixed so closing the bug.
IOS Version: iPad(15.6.1)

https://user-images.githubusercontent.com/100186395/188862182-71cf2416-35b0-4c0a-bc3b-793c69638fd5.MP4
