### ISSUE TITLE
[iOS] Can't remove border from Entry

### ISSUE THREAD

**Issue by NonameMissingNo** [dotnet/maui#8755]
### Description

The docs have an example, where you can remove the borders of an entry with a handler (https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize) but that code doesn't work.

### Steps to Reproduce

Create a new project.
Put an Entry in the Xaml of the MainPage.
Copy the ModifyEntry() Method from the page.
Run the application on iOS.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by jfversluis** [comment]
Replace `#elif iOS` with `#elif IOS` and it works! I'll make sure to fix it in the Docs, thanks!
