### ISSUE TITLE
Not able to rollback to specific maui workload version (6.0.312)

### ISSUE THREAD

**Issue by ammar-madni** [dotnet/maui#8758]
### Description

`dotnet --version
6.0.400-preview.22330.6`

Upgrading Visual Studio for Mac resulted in my Maui workload being updated, this broke my app and so I rolled back to the previous version at the time with the following command:

`sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300.json`

I recently updated VS for Mac again to see if the latest updates fixed any of the issues I was having. Unfortunately, it did not. It also introduced a new issue.

I then tried to rollback with the same command and it fails with the following error:

`Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.301: microsoft.net.sdk.android.manifest-6.0.400::32.0.301 is not found in NuGet feeds https://api.nuget.org/v3/index.json"..`

Note:
I have seen [https://github.com/dotnet/maui/issues/8218](url) which recommends using the following command:

`dotnet workload install maui `
  `--from-rollback-file https://aka.ms/dotnet/maui/net6.0.json `
  `--source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json `
  `--source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json `
 ` --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json `
  `--source https://api.nuget.org/v3/index.json`

This does not work for me however as it does not rollback to the version I require.

### Steps to Reproduce

Run `sudo dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.300.json`

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by ioiooi** [comment]
There might be a no longer supported workaround you could try. Add `<MauiVersion>6.0.312</MauiVersion>` to your `.csproj`.
  
See https://github.com/dotnet/maui/issues/4812 for a bit more context.

**Comment by ammar-madni** [comment]
Managed to find a work around for the issue I was having on the latest version.
