### ISSUE TITLE
Again problems connecting a Mac.

### ISSUE THREAD

**Issue by Visual-IT-2021** [dotnet/maui#8759]
![image](https://user-images.githubusercontent.com/79186874/179217213-0039b9f0-6116-4ba4-962c-56ea63281ea2.png)

Again problems connecting a Mac.
Maui is far from being used productively. 
In my company we have now stopped all projects. 

DOTNET.MAUI is still a mess

**Comment by jfversluis** [comment]
This seems more like a Visual Studio/tooling issue. Please report this through Visual Studio, Help > Provide Feedback > Report a Problem. Other feedback can be provided that way as well. Thanks!
