### ISSUE TITLE
FlyoutHeader does not render properly on ios

### ISSUE THREAD

**Issue by JPfahl** [dotnet/maui#8769]
### Description

If you specify a FlyoutHeader it does not render properly on ios.  Same code works in android and windows.

![image](https://user-images.githubusercontent.com/101600436/179268706-3d7b6698-6722-4895-9dd2-ef690ee8aee5.png)
![image](https://user-images.githubusercontent.com/101600436/179269304-373da267-0839-4ad7-9cd3-dc3b344a499c.png)

### Steps to Reproduce

        <Setter Property="FlyoutHeader">
            <w:TitleLabelBase
                Text="{Static e:AppInfo.Name}"
                Padding="16, 12, 0, 12"
                BackgroundColor="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource PrimaryLight}}"
                TextColor="{StaticResource TitleForeground}"
            />
        </Setter>

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by mattleibow** [comment]
@PureWeen I wonder if this is fixed now with the safe areas work? Not sure who was all on that as well, maybe @rachelkang...

**Comment by JPfahl** [comment]
There is still an issue in Version 17.5.0 Preview 5.0.  it does not overlap the tool area anymore but on iOS only the header does not size to the content.  In Android and  Windows it is fine.

this can be reproduced with: 

        <Setter Property="FlyoutHeader">
            <Label Text="Title"/>
        </Setter>

iOS
![IMG_0256](https://user-images.githubusercontent.com/101600436/217332383-906b2835-5c15-4150-be45-f2c3ab2644e0.PNG)

Android
![image](https://user-images.githubusercontent.com/101600436/217333007-8d0d2364-5394-4a97-afee-0bb081432a48.png)

Windows
![image](https://user-images.githubusercontent.com/101600436/217333717-db8e7e74-f8f8-40b3-8fa4-165328a0787c.png)

**Comment by PureWeen** [comment]
This should be resolved by the following PR
https://github.com/dotnet/maui/pull/12480

I've added this issue for reference so we can make sure to test
