### ISSUE TITLE
Placeholder text is not vertically centered on Entry on windows

### ISSUE THREAD

**Issue by JPfahl** [dotnet/maui#8770]
### Description

If you specify Placeholder text for an Entry on windows it is not vertically centered in the field.

![image](https://user-images.githubusercontent.com/101600436/179270617-7db24f2a-c776-4725-844c-bcc7fb88e01c.png)

ios
![image](https://user-images.githubusercontent.com/101600436/179270814-b5703982-26aa-4c86-8ddd-e659cc9d2c00.png)

### Steps to Reproduce

set the Placeholder property.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.17763.0

**Comment by Symbai** [comment]
#8684

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/pull/8684
