### ISSUE TITLE
iOS: SwipeView placed in Border doesn't display

### ISSUE THREAD

**Issue by johnl188** [dotnet/maui#8774]
### Description

If you place a SwipeView within a Border, the contents of the SwipeView will not display on iOS. It does display on Android.

Android
![image](https://user-images.githubusercontent.com/44125912/179283515-0a4bb749-e3ca-43d9-bda2-a02070cd4104.png)

iOS
![image](https://user-images.githubusercontent.com/44125912/179284707-a7900b8e-ba11-441c-8d7e-f3d0ac8ccc95.png)

Reproduction Project: [link](https://github.com/johnl188/BorderDisplayRepo)

This recently broke with the latest VS 2022 Preview Version (17.3.0 Preview 3.0)

### Steps to Reproduce

Put a SwipeView Within a Border
```
        <Border>
            <SwipeView>
                <Label Text="This is test text" />
            </SwipeView>
        </Border>
```

Excepted: See the label text on the screen
Actual: No label text on the screen

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by rmarinho** [comment]
@johnl188  was this working in a previous version? so it's a regression?

**Comment by jsuarezruiz** [comment]
Could you try with the latest version?. Cannot reproduce the issue with net7.0 rc2.

![issue-8774](https://user-images.githubusercontent.com/6755973/196981159-b5e60e25-a581-45c0-97a4-e9570412a23f.gif)
