### ISSUE TITLE
Contentpage is cut off in iOS

### ISSUE THREAD

**Issue by inigofu** [dotnet/maui#8778]
### Description

When using top tab in Maui, content page is cut off in Ios.

In Android:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/33458620/179322182-d538dac2-6cae-4373-84d0-1e7fb825d345.png">

In Ios:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/33458620/179322232-b65d3a6e-5322-4c77-89fd-488c22d80ed9.png">

### Steps to Reproduce

The shell file configuration is:

<Shell
    x:Class="SutuMaui.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:SutuMaui"
    xmlns:views="clr-namespace:SutuMaui.View"
    xmlns:fonts="clr-namespace:SutuMaui.Resources.Fonts"
    Shell.FlyoutBehavior="Disabled">

   

    <TabBar>
       <Tab Title="MainPage" >
            <Tab.Icon>
                
            <FontImageSource Glyph="{x:Static fonts:IconFont.Home}" Color="Black"
                         FontFamily="materialicons"
                         />

            </Tab.Icon>
           
           <ShellContent Title="Cats"
                         ContentTemplate="{DataTemplate local:MainPage}" />
           
       </Tab>
            
            
       <Tab Title="Workouts">
            <Tab.Icon>
                
            <FontImageSource Glyph="{x:Static fonts:IconFont.Directions_bike}" Color="Black"
                         FontFamily="materialicons"
                         />

            </Tab.Icon>
           <ShellContent Title="Favorites" ContentTemplate="{DataTemplate local:MainPage}"/>
            <ShellContent Title="All Workouts"
                         ContentTemplate="{DataTemplate views:Workouts_All}" />
            <ShellContent Title="Free Ride"
                         ContentTemplate="{DataTemplate views:Workouts_FreeRIde}" />
       </Tab>
         <Tab Title="Plans" >
            <Tab.Icon>
                
            <FontImageSource Glyph="{x:Static fonts:IconFont.Calendar_month}" Color="Black"
                         FontFamily="materialicons"
                         />

            </Tab.Icon>
            <ShellContent Title="Cats"
                         ContentTemplate="{DataTemplate local:MainPage}" />
            </Tab>
        <Tab Title="Progress" >
            <Tab.Icon>
                
            <FontImageSource Glyph="{x:Static fonts:IconFont.Signal_cellular_alt}" Color="Black"
                         FontFamily="materialicons"
                         />

            </Tab.Icon>
            <ShellContent Title="Cats"
                         ContentTemplate="{DataTemplate local:MainPage}" />
            </Tab>

    </TabBar>

</Shell>

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by Hottemax** [comment]
Would be nice if that would be fixed since that is quite the obvious bug...

**Comment by edgiardina** [comment]
Seeing this as well on iOS.

**Comment by MSicc** [comment]
Same here, but on latest .NET 7 workload.

**Comment by Hottemax** [comment]
Pretty incredible that this is still the case a year after MAUI release.

Just sharing our quick workaround, adding a global implicit style:

<Style ApplyToDerivedTypes="True" TargetType="ContentPage">
    
    <Setter Property="Padding" Value="{OnPlatform iOS='10,50,10,0', Default='10,10,10,0'}" />
    ... your stuff
  </Style>

**Comment by pjcollins** [comment]
I was able to repro this issue with a .NET 7 project on an iOS 16 simulator. However, I am no longer seeing this when updating my project to target net8.0-ios using the latest [.NET 8 Preview 7](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) builds. Would you be able to try the latest preview version to see if that improves this behavior for you?
