### ISSUE TITLE
Image Source to null doesn't work if the Source had a different value before

### ISSUE THREAD

**Issue by AignerGames** [dotnet/maui#8787]
### Description

I have a Image and the Source property is bound to a ImageSource property of my ViewModel class.

I have a button to take a image and then update the ImageSource (including PropertyChanged etc).
This works so far, the Image updates after I take a new image.

I added a delete button to delete the image and set my ImageSource property to null (including Propertychanged call etc.)
But I noticed that the Image doesn't change back to null / blank, the old image is still shown, no matter how often I set it to null or invoke the PropertyChanged event

I even tried to take a direct reference to the Image in my View code and noticed that even setting the property directly to null by code doesn't reset the image.

So there is no way to reset the Image source after a "real" image was shown.

### Steps to Reproduce

1, Add a Image and set a "real" Image Source (Image should be visible)
2, Change the Image Source to null by code or binding (for example with a button click handler)
3, Confirm that the Image Source is null -> Old Image is still shown, even after the Source was set to null

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

Hide the image with a IsVisible Binding

**Comment by Dreamescaper** [comment]
Similar case - if MAUI fails to load the image with the new ImageSource (e.g. due to incorrect Url). It keeps showing the old image, while previously (XF or MAUI GA) it was hidden.

**Comment by rmarinho** [comment]
Thank you so much for your bug report! Unfortunately, this report seems to be missing some details.

Ideally we would love to have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that you upload to a GitHub repository and link us to. That should greatly speed up the process, thanks!

**Comment by AignerGames** [comment]
This project can be used to see the issue in action:

[See Bug #2 ImageSource Null, the file contains a custom NullConverter as a workaround because of this null ImageSource issue](https://github.com/AignerGames/MauiAppImageSourceFromFileBug.App/tree/master/TestFile)

**Comment by marcojak** [comment]
Same problem. Very annoying. I've seen there is a PR but it was closed while the team is focusing on something else.
I'm worried that with this approach, this PR will be forgotten and the bug will stay forever.

**Comment by andycambo** [comment]
Leaving a comment to also state that I've come across this issue.

You would expect setting an ImageSource to 'null' would remove the image.

**Comment by JkPersson** [comment]
Also seeing this problem.

We use it to display various error states, so obviously it very important for us to be able to clear the state when fixed.

**Comment by jerry08** [comment]
I'm facing this problem too and it seems like this bug will remain for a while so I made a workaround for now. I created a `CustomImage` class which extends `Image` and added an extension for `ImageSourcePartLoader`. Here's my code:

In view:

```
<mycontrols:CustomImage x:Name="myImage" Source="..." />
```
<br>

CustomImage (Use this if you're using a collectionview. See bug #8920):

```
using Microsoft.Maui.Controls;
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Networking;
using System.Runtime.CompilerServices;
using MyProject.Utils.Extensions;

namespace MyProject.Views;

public class CustomImage : Image
{
    public CustomImage()
    {
        Connectivity.Current.ConnectivityChanged += (s, e) =>
        {
            if (e.NetworkAccess == NetworkAccess.Internet)
                ReloadImage();
        };
    }

    protected override void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        base.OnPropertyChanged(propertyName);

        if (propertyName == nameof(Source) && Source is null)
            this.SetNullImage();
    }

    protected override void OnBindingContextChanged()
    {
        base.OnBindingContextChanged();

        ReloadImage();
    }

    public void ReloadImage()
    {
        this.SetNullImage();

        if (Handler is ImageHandler handler)
            handler.SourceLoader.UpdateImageSourceAsync();
    }
}
```

<br />

Image Extension:

```
using Microsoft.Maui.Controls;
using Microsoft.Maui.Handlers;

namespace MyProject.Utils.Extensions;

public static class ImageEx
{
    public static void SetNullImage(this Image image)
    {
        if (image.Handler is ImageHandler handler)
            handler.SourceLoader.SetNullImage();
    }
}
```

<br />
And finally, ImageSourcePartLoader extension:

```
using System;
using System.Reflection;
using Microsoft.Maui.Platform;

#if IOS || MACCATALYST
using PlatformImage = UIKit.UIImage;
#elif ANDROID
using PlatformImage = Android.Graphics.Drawables.Drawable;
#elif WINDOWS
using PlatformImage = Microsoft.UI.Xaml.Media.ImageSource;
#elif TIZEN
using PlatformImage = Microsoft.Maui.Platform.MauiImageSource;
#elif NETSTANDARD || !PLATFORM || (NET6_0_OR_GREATER && !IOS && !ANDROID && !TIZEN)
using PlatformImage = System.Object;
#endif

namespace MyProject.Utils.Extensions;

public static class ImageSourcePartLoaderEx
{
    public static void SetNullImage(this ImageSourcePartLoader sourceLoader)
    {
        var sourceLoaderType = sourceLoader.GetType();

        var setImageProp = sourceLoaderType.GetProperty("SetImage",
            BindingFlags.NonPublic | BindingFlags.Instance);
        var setImageM = (Action<PlatformImage?>?)setImageProp?.GetValue(sourceLoader);

        var sourceManager = sourceLoaderType.GetProperty("SourceManager",
            BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(sourceLoader);
        var completeLoadM = sourceManager?.GetType()
            .GetMethod("CompleteLoad", new[] { typeof(IDisposable) });

        setImageM?.Invoke(null);
        completeLoadM?.Invoke(sourceManager, new object?[] { null });
    }
}
```

<br />

When using `CustomImage`, I can set the source to null. I can also do `myImage.SetNullImage()` If you're using `Image` only, you'll have to call `image.SetNullImage()`

**Comment by Greg-Bates-Trimble** [comment]
Any update on this please?

**Comment by jerry08** [comment]
If the image source fails (e.g. invalid url or no internet), the previous image source will remain (that's if you're changing the image source from one to another). This is especially evident when using a `CollectionView` or `ListView` because these controls reuse cells when scrolling. Using those controls requires setting the source to null in order to not reuse images if the source fails to load. Setting the image as transparent will introduce bugs. (I tested it before.)
If you're loading the image from a byte array or stream, then setting the image as transparent will do just fine.
