### ISSUE TITLE
support linux and Android

### ISSUE THREAD

**Issue by passerbyo** [dotnet/maui#8802]
### Description

support linux and Android

### Public API Changes

no

### Intended Use-Case

use on linux

**Comment by Eilon** [comment]
Hi, .NET MAUI already has full support for Android.

For Linux, this is requested in https://github.com/dotnet/maui/issues/3564, https://github.com/dotnet/maui/issues/5801, and possibly others.

**Comment by YoshiRulz** [comment]
I think OP was asking for Linux+Android as dev+target, which would be #359 (currently locked). But for reference, the other Linux requests are #349 (currently locked) and the main discussion #339.
