### ISSUE TITLE
[Android] Canvas shadow didn't get applied for the drawn ellipse

### ISSUE THREAD

**Issue by PraveenGopalsamy** [dotnet/maui#8807]
### Description

Hi, I'm trying to add a shadow for the drawn ellipse but it didn't get shown on the Android platform. I have tested this same case on the Windows platform, it gets worked.

XAML

```
<ContentPage.Content>
       <Grid HeightRequest="100"
              WidthRequest="300">
            <local:SampleView />
        </Grid>
 </ContentPage.Content>
```

C#

```
public class SampleView : GraphicsView
{
    public SampleView()
    {
        Drawable = new EllipseDrawable();
    }

    protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
    {
        return new Size(widthConstraint, heightConstraint);
    }
}

public class EllipseDrawable : IDrawable
{
    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        Rect ellipseBounds = new Rect(dirtyRect.Center, new Size(30));
        canvas.FillColor = Colors.Blue;
        canvas.SetShadow(new SizeF(0f, 10f), 10f, Colors.Red);
        canvas.DrawString("Welcome to MAUI !!!", 10, 50, HorizontalAlignment.Left);
        canvas.FillEllipse(ellipseBounds);
    }
}
```

### Steps to Reproduce

1. Create a new Maui App.
2. Create a new class, which extends the class from GraphicsView.
3. Create a new class that implements IDrawable, and assign this Drawable to GraphicsView.
4. Now set `canvas.SetShadow()` and also draw a `canvas.FillEllipse()` and `canvas.DrawEllipse()` using the canvas.
5. The shadow didn't get applied for the Ellipse.

Screenshots:

Android:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/83585210/179500701-c27574a9-ab68-4a1a-965d-a7c2dc66c9dd.png">

Windows:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/83585210/179500143-809402f1-c8e9-4c47-b63a-301fcc056b6b.png">

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

All Android versions

### Did you find any workaround?

Not Applicable.

**Comment by rmarinho** [comment]
Hello i just tested and seems to be work fine, i added a [repro ](https://github.com/rmarinho/issue-8807
) for the issue, can you take a look and see if this is what you wanted and if works as expected. Please reopen if it's not. Thanks

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1235097/179556061-e8be7083-50f5-4a64-bd39-55f8badbc72a.png">

**Comment by PraveenGopalsamy** [comment]
Hi @rmarinho ,

Thanks for the update. Please check with the **Android API 27** version, this issue still replicates there.

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi @rmarinho,

Can you please check [this](https://github.com/dotnet/maui/issues/8807#issuecomment-1188612012) and reopen this issue again?

Regards,
Praveen G.
