### ISSUE TITLE
ImageSource FromFile Android internal bug?

### ISSUE THREAD

**Issue by AignerGames** [dotnet/maui#8809]
### Description

Sorry I don't have many details, but the implementation of ImageSource.FromFile (which uses a FileImageSource) seems to have bug in the implementation which causes issues on Android. 

For example when I use a Image which is bound to an ImageSource which was loaded with ImageSource.FromFile and then change tab a few time or scroll down / up it will suddenly throw a exception Canvas: trying to use a recycled bitmap android.

Doing the same thing but loading the file stream manually with ImageSource.FromStream works and doesn't cause any of these issues.

### Steps to Reproduce

1, Load image file with ImageSource.FromFile
2, Bind the ImageSource to an Image inside a Tab
3. Change the Tab a few times until Android (randomly?) throws a exception Canvas: trying to use a recycled bitmap android

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Use ImageSource.FromStream and manually load the file stream instead of using ImageSource.FromFile

**Comment by rmarinho** [comment]
Thank you so much for your bug report! Unfortunately, this report seems to be missing some details.
Ideally we would love to have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that you upload to a GitHub repository and link us to. That should greatly speed up the process, thanks!

**Comment by AignerGames** [comment]
I tried to upload a example which causes the exception on my Android 11 Lenovo Tablet
(The VS Git Dialog reported a weird warning, I hope everything is included)

[https://github.com/AignerGames/MauiAppImageSourceFromFileBug.App/tree/master/TestFile](url)
