### ISSUE TITLE
Separate Window Management from IApplication

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#8823]
### Description

Currently management of the Windows is handled by IApplication which also needs to implement IElement. In practice it's very tightly coupled with the Application Implementation. This really should be split out into it's own interface which IApplication could potentially then implement or rely on.

### Public API Changes

```cs
public interface IWindowManager
{
    IReadOnlyList<IWindow> Windows { get; }
    IWindow CreateWindow(IActivationState? activationState);
    void OpenWindow(IWindow window);
    void CloseWindow(IWindow window);
}

public interface IApplication : IElement, IWindowManager
{
    void ThemeChanged();
}
```

Maui can internally register and rely on the Window Manager rather than this being tightly coupled to the Application:

```cs
services.TryAddSingleton<IWindowManager>(sp => sp.GetRequiredService<IApplication>());
```

This could also be made easier to work with by providing a decoupled base class like:

```cs
public abstract WindowManagerBase : IWindowManager
{
    protected List<Window> Windows { get; }
    IReadOnlyList<IWindow> IWindowManager.Windows => Windows.Cast<IWindow>().ToList();
    
    protected abstract Window CreateWindow(IActivationState? activationState);
    IWindow IWindowManager.CreateWindow(IActivationState? activationState) => CreateWindow(activationState);
    
    protected virtual void OpenWindow(Window window)
    {
        // include any native hooks
    }

    protected virtual void CloseWindow(Window window)
    {
        // include any native hooks
    }

    void IWindowManager.OpenWindow(IWindow window) => OpenWindow((Window)window);
    void IWindowManager.CloseWindow(IWindow window) => CloseWindow((Window)window);
}
```

### Intended Use-Case

This would help 3rd party libraries like Prism which provide custom Navigation Services to more easily manage the Windows / Window Lifecycle without having to implement all of IApplication which is also next to impossible due to all of the Application.Current references which would break.

**Comment by PureWeen** [comment]
Related https://github.com/PrismLibrary/Prism.Maui/pull/121
