### ISSUE TITLE
MAUI Workload version vs  .Net SDK version

### ISSUE THREAD

**Issue by ScofieldOY** [dotnet/maui#8828]
### Description

Currently, MAUI workload 408 works well in my local with SDK 300, but MS has stated before that the MAUI workloads are tightly coupled to the SDK. I don't know if that is still the case after GA or we don't need to worry about this mapping?
`dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/6.0.408.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`
global,json
`{ "sdk": { "version": "6.0.300", "rollForward": "disable" } }`

### Public API Changes

N/A

### Intended Use-Case

N/A

**Comment by jfversluis** [comment]
You shouldn't have to worry about mapping it. In fact, you shouldn't have to install the workload through the command-line at all except for when using it in CI pipelines. Then installing .NET 6 and running `dotnet workload install maui` ought to be enough.
