### ISSUE TITLE
Run Maui MSI on window server 2019 not working.

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#8830]
### Description

I deployed Maui app as shown in https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
Run this on new server 2019 with Desktop Experience installed in it.
and is not working.

### Steps to Reproduce

1. Publish Maui app.
2. Run on server 2019
3. Nothing happened.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

**Comment by rmarinho** [comment]
Hello friend, what's the error you see? Can you post some logs from EventViewer for example, or some print screens?

Thanks

**Comment by danies8** [comment]
1. The msix was not clickable.
2. After installing msixmgrSetup-1.1.0.0-x64  it was clickable.
3. I run the msix and got this popup message: "You'll need new app to open this ms-appinstaller"
![MESSAGE](https://user-images.githubusercontent.com/1079689/179739945-4361d2b3-53b8-4ef6-b60b-576d14ae5b42.png)

**Comment by danies8** [comment]
I installed https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer
and is not helped , the same message.
This my control panel:
![image](https://user-images.githubusercontent.com/1079689/179748324-91515449-83fc-45f3-8eaa-d7dbe14f489d.png)

**Comment by danies8** [comment]
I installed also https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer
and is not helped , the same message.

**Comment by danies8** [comment]
I take those installations on :https://docs.microsoft.com/en-us/windows/msix/msix-server-2019

**Comment by MagicAndre1981** [comment]
install latest [Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle](https://github.com/microsoft/winget-cli/releases/download/v1.3.1872/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle) via powershell:

`Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\08d8788d59cf47ed9bf42c31e31f8efa_License1.xml -Verbose`

(XML can be found here: https://github.com/microsoft/winget-cli/releases/download/v1.3.1872/a941c144deac426082dc9f208f729138_License1.xml)

**Comment by danies8** [comment]
I got this error, what i missed
![image](https://user-images.githubusercontent.com/1079689/179786646-f8ef3b29-c307-4c2e-91fc-04e2899b7d37.png)

**Comment by MagicAndre1981** [comment]
ok, you miss the [VC++ Desktop framework dependency ](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages).

Install the x86 and x64 appx files with [Add-AppxPackage](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2019-ps#description=)

**Comment by danies8** [comment]
I tried to install the x64 version without success:
![image](https://user-images.githubusercontent.com/1079689/179913226-ac0dda50-ccc9-47e1-bdeb-602b2f793fb8.png)

**Comment by MagicAndre1981** [comment]
and what happens with x64 version? Same error?

**Comment by danies8** [comment]
Same:
![image](https://user-images.githubusercontent.com/1079689/179948688-e0181ebe-eb2a-4cdc-ba3a-9c1aebc33406.png)

**Comment by danies8** [comment]
I fixed the command to Add-AppxPackage -Path "C:\AutomationClient\Client\Microsoft.VCLibs.x64.14.00.Desktop.appx" and it work same for x86.
But run maui msix i still got error:
![image](https://user-images.githubusercontent.com/1079689/179958751-ce1337c7-e5ac-4b44-99a1-202155f7f6a8.png)

**Comment by danies8** [comment]
Any solutions ?

**Comment by MagicAndre1981** [comment]
update VS to 17.3 Preview 4 and try to create an [unpacked app](https://github.com/dotnet/maui/pull/8432) that has everything included to run.

**Comment by danies8** [comment]
1. I updated my VS to 17.3 Preview 4.
2. Does these the two commands i need to create ? I added the diffrerence in bold
msbuild /t:restore AutomationClient.MAUI.csproj
msbuild  /t:Publish AutomationClient.MAUI.csproj /p:TargetFramework=net6.0-windows10.0.19041.0 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="c01ba45666762f3615cf6813aeb4dc4b1919541d" /p:PublishSingleFile=true **/p:WindowsPackageType=none /p:WindowsAppSDKSelfContained=false**

**Comment by MagicAndre1981** [comment]
try this second command and look if this works. Server is not officially supported by MAUI, so try it and look what happens.

**Comment by danies8** [comment]
I succeeded to create EXE && it run both on window 10 && server 2019 as exe.
The fix is /p:GenerateAppxPackageOnBuild=false
Thanks

**Comment by danies8** [comment]
Currently NET runtime +NET Framework + VCLibs are installed , are they needed when I have exe?

**Comment by MagicAndre1981** [comment]
> I succeeded to create EXE && it run both on window 10 && server 2019 as exe. The fix is /p:GenerateAppxPackageOnBuild=false Thanks

great to hear this 🥳
