### ISSUE TITLE
TranslationY does not work on Frame component

### ISSUE THREAD

**Issue by MaticDiba** [dotnet/maui#8840]
### Description

I'm trying to implement a bottom drawer which is hidden when the page is loaded. But it does not work like that on Android. It's always displayed when the page is loaded but then I'm able to hide it. The same code worked on Xamarin Forms.

### Steps to Reproduce

Here is an example repo: https://github.com/MaticDiba/MauiAppBottomDrawer

Try to run this in an Android emulator or on an Android device. The bottom drawer will always be shown when the device loads.

I'm actually not sure about iOS. But it should work on windows.

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android versions I tested with

### Did you find any workaround?

No.

**Comment by rmarinho** [comment]
Seems to work fine on iOS, but on Android doesn't work as expected

**Comment by MaticDiba** [comment]
Thanks for confirming that @rmarinho 

What is the way to move one? Is there anything I can help with?

**Comment by rmarinho** [comment]
Hey @MaticDiba  you can help fix it ? :D Kidding ... it's now on the backlog and we now need to figure when we can look at it, in what sprint.

**Comment by Naxilos** [comment]
A workaround is to put Frame inside a Grid, and add TranslationY to that Grid.

**Comment by psandgren** [comment]
The workaround doesn't work when you have nested controls. For example, having a dummy boxview/rectangle in the bottom to fix the gap if panning the content upwards. The dummy will be rendered with TranslationY = 0, then jump to whatever value when running TranslateTo(). This only happens when the control is initialized though, after that it works as intended.
