### ISSUE TITLE
WinUI targets require location permissions set in manifest when asking for location

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#8842]
### Description

When requesting location access on windows, the application incorrectly validates that you have locations enabled in the application manifest. WinUI 3 apps do _not_ require this to be defined to get a location. In fact the option isn't even in the manifest designer like it was with UWP apps.
The bug seems to be here, and caused by a raw import of the older UWP code:
https://github.com/dotnet/maui/blob/117436bdba60f0a1046a43c11ec785c9b15b9965/src/Essentials/src/Permissions/Permissions.uwp.cs#L132-L144
Could likely just be changed to:
`internal static Task<PermissionStatus> RequestLocationPermissionAsync() => Task.FromResult(PermissionStatus.Granted)`

(looking over this entire file, it might be affecting most of those permissions)

### Steps to Reproduce

1. Create a new maui app
2. Add this code: `await Microsoft.Maui.ApplicationModel.Permissions.RequestAsync<Microsoft.Maui.ApplicationModel.Permissions.LocationWhenInUse>();`
3. Run on windows.
Observe the following exception thrown:

![image](https://user-images.githubusercontent.com/1378165/179817930-6c45b259-0c6a-4cc3-9ea6-92b7a9991436.png)

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 18362+

### Did you find any workaround?

Don't call this on Windows, or create custom permission:
```cs
private class LocationWhenInUse: Microsoft.Maui.ApplicationModel.Permissions.BasePlatformPermission
{
   internal static Task<PermissionStatus> RequestLocationPermissionAsync() => Task.FromResult(PermissionStatus.Granted);
}
```

**Comment by knocte** [comment]
@mattleibow what's the first non-preview MAUI version that will have this fix? 7.0?

**Comment by mattleibow** [comment]
I think this made it back to rc2. I am afk now but will check and make sure.

**Comment by knocte** [comment]
But I guess `rc` is preview, I asked non-preview :)

**Comment by mattleibow** [comment]
Ah, in that case yes. 7.0.

But the workaround will be to just define the permissions in the manifest?
