### ISSUE TITLE
Picker on windows shows "Microsoft.Maui.Controls.Picker" if ItemsSource has an empty string

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#8845]
### Description

Binding the picker to a list with an empty string populates the WinUI ComboBox with the string "Microsoft.Maui.Controls.Picker"

### Steps to Reproduce

This kind of feels like a WinUI bug

```XAML
    <Picker x:Name="picker" ItemDisplayBinding="{Binding DisplayName}" SelectedIndex="0">
    </Picker>
```

```C#
picker.ItemsSource =
				new List<object>
				{
					new { DisplayName = (string)null},
					new { DisplayName = "Not null"},
				};
```

- Select the second item
- now go back to the first item

![image](https://user-images.githubusercontent.com/5375137/179836831-2eba3e2b-9118-49e6-82c8-10f04eac2c3a.png)

From what I can tell this happens because inside `UpdateTitle` we are setting the `DataContext` of the `ComboBox` to the MAUI control. I don't really understand why setting the `DataContext` of the control would become the default text used for an empty string 🤷

Possible fixes 
- Currently we set the ItemSource to a list of strings. If you set the `ItemSource` on the `ComboBox` to actual classes and then use `DisplayMemberPath` then it will be an empty string
- Instead of setting the `DataContext` inside of `UpdateTitle` (which seems a bit extra) we could just set the header to the control that's inside the template. It seems like that XAML is re-creatable in code and doesn't need a binding
  -  Though this will still make the behavior remain incorrect if someone sets the `DataContext` 

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with below Project:
[8845.zip](https://github.com/dotnet/maui/files/11541833/8845.zip)
![image](https://github.com/dotnet/maui/assets/97647558/b4cb949e-0be7-4ba7-afe7-f3e54313b4cd)

**Comment by justinbrick** [comment]
If this is put on backlog, does anyone have a potential workaround they might be able to offer for anyone else facing the same issue?

**Comment by bronteq** [comment]
Maui 8.0.40 still has this bug
