### ISSUE TITLE
HRESULT E_FAIL with Rectangle with margin and no stroke

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#8846]
### Description

This XAML-code:

``` XAML
<Rectangle StrokeThickness="0" HeightRequest="1" Margin="0,1,0,0" />
```

causes an exception be thrown with the message:

   "Invalid number. (0x88990011)"

![image](https://user-images.githubusercontent.com/3163293/179838417-0b4cc417-7da8-48f3-a28d-466e70a747f0.png)

Similar issue: https://github.com/dotnet/maui/issues/8512

### Steps to Reproduce

1. Create a new MAUI app
2. Add this code on MainPage.xaml:

``` XAML
<Rectangle StrokeThickness="0" HeightRequest="1" Margin="0,1,0,0" />
```
3. Run the application.

Full sample: https://github.com/pekspro/MauiIssues/tree/8846_HRESULT_E_FAIL_with_Rectangle

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

It works if `Stroke` is none zero. Margin `1,0,0,0` also works.

**Comment by rmarinho** [comment]
This seems to fixed on the next version (sr3) 6.0.409, if the issue still persists in that version, please reopen the issue. 

Thanks
