### ISSUE TITLE
Preference not work with DateTime 

### ISSUE THREAD

**Issue by infrasoft2007** [dotnet/maui#8853]
### Description

When use Preferences.Default.Set() method with a DateTime value on Android Local Device, no preference is saved.

### Steps to Reproduce

1. Create Maui project
2. Replace OnCounterClicked function with:

```
private void OnCounterClicked(object sender, EventArgs e)
	{
		Preferences.Default.Set("myPreference1",DateTime.Now);

		if (!Preferences.Default.ContainsKey("myPreference1"))
		{
			Shell.Current.DisplayAlert("Error", "Preference not saved", "Ok");
		}
	}
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by rmarinho** [comment]
Yeah we need to maybe fix this, because the new API allows generic but we really just support int, string, long ,double, float types


<img width="411" alt="image" src="https://user-images.githubusercontent.com/1235097/180001868-e67119e5-4b85-4948-bca9-48eae5025162.png">

**Comment by MagicAndre1981** [comment]
ContainsKey is also broken for me for a string (json data) in WinUI MAUI app, it always returns false even after just adding data 1 line before, but calling Get returns the correct data 🤔 🤷‍♂️

**Comment by jfversluis** [comment]
@MagicAndre1981 I think that might be this #9361
