### ISSUE TITLE
Overriding CreateFileProvider for BlazorWebView throws exception

### ISSUE THREAD

**Issue by RNavaneethKumar** [dotnet/maui#8857]
### Description

I am successfully able to create a BlazorWebView dynamically in a .NET MAUI Blazor App. However when I try to override the CreateFileProvider method and set a different path, an exception is thrown without the breakpoint being hit.

This is how the code file looks like

<img width="645" alt="image" src="https://user-images.githubusercontent.com/22679526/179975960-c2797fc4-d8d5-4fe4-bfdb-4fa3b970399f.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/22679526/179979357-9e400d93-26d1-4248-93b2-64abf9bfa0b0.png">

When the blazorWebView.CreateFileProvider(FileSystem.AppDataDirectory) statement is executed, it does not hit the breakpoint set in the function being overridden and it throws an exception as follows.

<img width="233" alt="2" src="https://user-images.githubusercontent.com/22679526/179976509-dc478d19-ed35-469f-af0e-c3f3a0b5514f.png">

Please advice if I am doing anything wrong or if it is a bug.

### Steps to Reproduce

1. Create a .NET MAUI Blazor App
2. In the MainPage.xaml.cs, add the code as shown in the screenshot.
3. An exception is thrown when the CreateFileProvider method is called.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

None

**Comment by retvari** [comment]
did you find any workaround for this issue? I have the same problem...I'm trying to use the "wwwroot" folder from assembly and I wanted to use CompositeFileProvider.

**Comment by Eilon** [comment]
Hi, to see an example of using a custom IFileProvider with BlazorWebView, please check out these samples/tests from the repo:

* https://github.com/dotnet/maui/blob/main/src/BlazorWebView/tests/MauiDeviceTests/Elements/BlazorWebViewTests.cs#L90-L106
* https://github.com/dotnet/maui/blob/main/src/BlazorWebView/samples/BlazorWpfApp/CustomFilesBlazorWebView.cs#L11-L25

To use it, all you have to do is create a derived BlazorWebView that overrides the CreateFileProvider method to return a custom file provider. The [repro code](https://github.com/RNavaneethKumar/CreateFileProviderSample/blob/main/SampleApp/MainPage.xaml.cs#L28-L34) seems to be doing extra work that isn't necessary.
