### ISSUE TITLE
Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=15.4.300.0

### ISSUE THREAD

**Issue by ankasani** [dotnet/maui#8858]
### Description

CSC : error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.100.125, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [/Users/runner/work/1/s/SampleMauiApp/SampleMauiApp.csproj]

### Steps to Reproduce

Create a basic project from VS 2022 preview > MAUI template > and using the azure devops build to build it i am facing this issue!

followed: https://devblogs.microsoft.com/dotnet/devops-for-dotnet-maui/

YAML i am using

trigger:
- null

variables:
    BuildConfiguration: Release
    DotNetVersion: 6.x

stages:
- stage: BuildiOS
  jobs:
  - job: BuildMAUIApps
    displayName: Build Sample App
    pool:
      vmImage: 'macOS-12'
      demands:
      - MSBuild
      
    steps:

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Developer.p12'
        certPwd: 'xxxxxx'
        keychain: 'temp'

    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'Development.mobileprovision'

    - task: Bash@3
      displayName: Mono Version
      inputs:
        targetType: 'inline'
        script: |
          #!/usr/bin/env bash
          set -ex
          curl "https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.182.macos10.xamarin.universal.pkg" > "$HOME/Downloads/mono-installer.pkg"
          sudo installer -store -pkg "$HOME/Downloads/mono-installer.pkg" -target "/"
          mono --version
          ls -alh /Library/Frameworks/Mono.framework/Versions/Current
          
    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DotNetVersion)'
        includePreviewVersions: true
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json \
          --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-a21b9a2d/nuget/v3/index.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-52e9452f-3/nuget/v3/index.json \
          --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json \
          --source https://api.nuget.org/v3/index.json

    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          dotnet restore SampleMauiApp.sln
    - task: Bash@3
      displayName: Build iOS App
      inputs:
        targetType: 'inline'
        script: |
          dotnet publish -f:net6.0-ios -c:Release /p:ArchiveOnBuild=true
    - task: CopyFiles@2
      inputs:
        Contents: |
          **/*.app
          **/*.ipa
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop_ios'
        publishLocation: 'Container'

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 14.2

**Comment by ankasani** [comment]
@rmarinho , Thanks for the info, Do you have any steps to update MAUI in CI ?

**Comment by ScofieldOY** [comment]
@rmarinho @ankasani I run into the some issue in our Mac pipeline and I don't think MAUI workload is the root cause, we tried install different workload like 400/408 
`
![image](https://user-images.githubusercontent.com/87661789/180171427-0fa80ae9-1892-4e91-a7f8-e482c89eb135.png)
`

**Comment by jfversluis** [comment]
For the pipeline you should just be able to install .NET 6 and then `dotnet workload install` which should get you the latest available version or .NET MAUI.
