### ISSUE TITLE
[Bug] The Windows ImageDirectory property is weird and not very user-friendly

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#886]
### Description

Originally it was a platform-specific, attached property on Application. In MAUI, we need this as well, so we need a way to set it - probably in the builder. 

It feels like a configuration thing, but that might be read-only? It needs to be writeable as it is a settable property at any time in Application.

In the images PR #759 I added a weird `IImageSourceServiceConfiguration`, but his is an abomination. This works for now, but needs to change.

**Comment by mattleibow** [comment]
If we get to use the Microsoft.Extensions.DI, then this will become much easier since we can use the config classes to do this.

**Comment by Eilon** [comment]
@mattleibow - do you think this is still an issue with the recent changes you made to the Assets folder? Or is this unrelated?

**Comment by mattleibow** [comment]
Good point. I think it is partially fixed. I'll review this api agan and see if we can delete this interface. No more special assets things.

**Comment by mattleibow** [comment]
Due to all the changes all over, the best thing here would be to start over and re-work this implementation using the hosting options.

I am going to delete the interface and do it right, now that we have the full power of the MS.Ext.Hosting model.

**Comment by Eilon** [comment]
Well, we don't have all of hosting anymore. It was mostly removed in a recent PR due to perf...

**Comment by mattleibow** [comment]
But we still have configuration and options, right? I use the word hosting here for all the stuff that happens in MauiProgram.cs. Previously we just had our own custom thing that was just a dictionary.

**Comment by Eilon** [comment]
@mattleibow hmm not sure what's left. All the _default_ configuration is gone. But you can definitely register options in DI and then consume it from any component that is activated via DI. And I think if you register configuration in DI then maybe(?) it'll get picked up automatically by options types? I don't recall how that is plumbed.

**Comment by mattleibow** [comment]
I got a PR to remove it, we can fix that after we release RC 1 because bad code is worse than a month delay for good code.
