### ISSUE TITLE
HttpClientHandler ClientCertificate property is null on Android

### ISSUE THREAD

**Issue by GarageGadget** [dotnet/maui#8860]
### Description

The application I am building requires the use of Client X509 certificates. 
I am trying to add the client certificate to the HttpClientHandler, however the ClientCertificate property is null and therefore throwing an null reference exception when calling the Add() method with a X509 certificate.

_Snippet_

```
  var handler = new HttpClientHandler();
  handler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12 | System.Security.Authentication.SslProtocols.Tls13;
  handler.ClientCertificateOptions = ClientCertificateOption.Manual;
  if(handler.ClientCertificates == null)
  {
      Console.WriteLine("ClientCertificates is null");
  }
  // handler.ClientCertificates.Add(clientCert); <-- Failure


```
_Using_
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.3.0 Preview 4.0

### Steps to Reproduce

1. Create a Maui App
2. Add code similar to snippet above in a button handler or any suitable method.
3. Run and debug the Maui App on Android
4. The ClientCertificates property will be null and log the message to the console.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

**Comment by jonathanpeppers** [comment]
@steveisok @simonrozsival would you know if this is expected behavior?

Should be initialize this with an empty collection?

https://github.com/xamarin/xamarin-android/blob/ace5f71c40d05070612cb860f38764eae3deef59/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L150

@GarageGadget for now you can do this as a workaround?

```csharp
handler.ClientCertificates ??= new ();
```

**Comment by simonrozsival** [comment]
We had a similar report from a different customer recently, here's the issue in Xamarin.Android: https://github.com/xamarin/xamarin-android/issues/7274

I suggest closing this issue as it's specific to Xamarin.Android.
