### ISSUE TITLE
CollectionView: SelectedItem does not get highlighted (dotNet 6.0.400-preview.22330.6)

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui#8863]
### Description

CollectionView: when I click/tap on an item, it is not highlighted...
See this code: (I have attached a ZIP with the VS project)

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp_CollectionView.MainPage">

    <ScrollView>

        <CollectionView>
					
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 01</x:String>
                    <x:String>Item 02</x:String>
                    <x:String>Item 03</x:String>
                    <x:String>Item 04</x:String>
                    <x:String>Item 05</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
        </CollectionView>
        
    </ScrollView>

</ContentPage>`

**Try with this variant:**

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp_CollectionView.MainPage">

    <ScrollView>

        <CollectionView>
		
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid Padding="5">
                        <Label Text="{Binding .}" FontSize="20"/>
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
			
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 01</x:String>
                    <x:String>Item 02</x:String>
                    <x:String>Item 03</x:String>
                    <x:String>Item 04</x:String>
                    <x:String>Item 05</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
        </CollectionView>
        
    </ScrollView>

</ContentPage>`

**Try this variant too:**

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp_CollectionView.MainPage">

    <ContentPage.Resources>
        <Style TargetType="Grid">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="LightSkyBlue" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>

    <ScrollView>

        <CollectionView>
    
			<CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid Padding="5">
                        <Label Text="{Binding .}" FontSize="20"/>
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>

            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 01</x:String>
                    <x:String>Item 02</x:String>
                    <x:String>Item 03</x:String>
                    <x:String>Item 04</x:String>
                    <x:String>Item 05</x:String>
                </x:Array>
            </CollectionView.ItemsSource>

        </CollectionView>
        
    </ScrollView>

</ContentPage>`

**I have attached a zip with the .net MAUI project:**
[MauiApp_CollectionView.zip](https://github.com/dotnet/maui/files/9152635/MauiApp_CollectionView.zip)

### Steps to Reproduce

Please, open the project that I attached on "Description"

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11 and Android 12

### Did you find any workaround?

No

**Comment by rmarinho** [comment]
Just tested on Windows and Android and its working as expected

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1235097/180259997-7e9d602d-2522-4064-b3b7-960bca22a2ee.png">

hard t see but is a ligher dark on here on Item 05
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1235097/180260397-b4f4fdb1-a7f4-47d4-a863-8011819eca75.png">


What version are you using

**Comment by leoderja** [comment]
Hi, 
Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 4.0
dotnet --version: 6.0.400-preview.22330.6
All NuGet packages in the attached sample project are fully actualized

If you need more info, please let me know.

Thank you
