### ISSUE TITLE
How to measure the FPS ?

### ISSUE THREAD

**Issue by alexdi220** [dotnet/maui#8876]
Hello. How can I measure the FPS of MAUI's render? I need any metrics of the performance in both mobile platforms (iOS\Android). So the FPS looks like a classic. Maybe you have any benchmarks or blogs on this?

**Comment by pierre01** [comment]
`DeviceDisplay.Current.MainDisplayInfo.RefreshRate` will give you the information.
As it is fluctuating, you should listen to the following event:
`DeviceDisplay.Current.MainDisplayInfoChanged`

I must say that information is not reflective of the max refresh rate as modern devices like the Samsung S22 Ultra will  adjust the refresh rate to a lower number if your UI is not busy. to save battery. and raise it when needed.

**Comment by sjordanGSS** [comment]
Have you given this a look: https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps?

**Comment by mattleibow** [comment]
Is this still something you are looking at?

**Comment by mattleibow** [comment]
@jonathanpeppers  How did you measure the UI perf in your work?

**Comment by jonathanpeppers** [comment]
https://aka.ms/profile-maui is the same wiki link above.

If it is on Android, I would just turn on this developer setting:

https://www.neowin.net/guides/how-to-enable-the-refresh-rate-overlay-on-android-11/

Looks like this in the corner:

![image](https://user-images.githubusercontent.com/840039/201198069-b75ab823-d1a6-4c45-9e01-d0534c312e11.png)
