### ISSUE TITLE
.NET MAUI-Content Page template broken

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8896]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Content-Page-template-broken/10100418)._

---
[severity:I'm unable to use this version]
This issue occurs after creating a .NET MAUI project using the .NET MAUI App template.

Right-click the project name in the Solution Explorer, choose Add->New Item...

Choose to create a Content Page.

Visual Studio generates errors that ContentPage, ContentPage.Content, StackLayout, and Label cannot be found. 

After approximately a 5 second delay after confirmation to create a Content Page, Visual Studio also generates one or more errors indicating that "the target 'UpdateDesignTimeXAML' does not exist in the project".

---
#### Feedback Bot on 7/20/2022, 11:45 PM: 

(private comment, text removed)
#### Nina Chen [MSFT] on 7/21/2022, 02:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
@jonathanpeppers can you answer this ?

**Comment by cafbe** [comment]
I had the same issue, but I found a workaround (not great but it worked...)

Go to the project folder
Copy/paste your main page file and .cs file -> rename both to the same name
Open your project file and add the ItemGroup segments to create your DependentUpon segments
Update your class name in the .cs file to the new file (page) name and clean up unrelated code
Update your header in the xaml file with the name
Close and open, rebuild, etc.

**Comment by JonathanBout** [comment]
I had the same issue, but found that if you search for MAUI in the Add New item menu you will see the .NET MAUI ContentPage, which works fine. I think the one you see first is an old one or maybe even a Xamarin page.

**Comment by Eilon** [comment]
@phenning - any idea how we can hide Xamarin.Forms template items so that they don't show up in .NET MAUI projects?

**Comment by phenning** [comment]
I believe those templates are vstemplate style templates, so those templates would need to be updated to exclude the MAUI project capability.

<AppliesTo>!Maui</Applies>

Alternatively, project types that these template are relevant to are all CPS based project systems, I believe you could set AppliesTo to match that specific project capability.

Short of this, there is no other way that I'm aware of to suppress these unless the MAUI projects have their own project factory. In that case you could only show vstemplates like we do for aspnetcore (see below). The downside to this, is that ALL the default CSharp templates would also be hidden from the dialog. 

Josh Stevens owns the Item dialog experience in Visual Studio and may be able to provide additional context to the template owners.

```
@="ProjectFactory"
"Language(VsTemplate)"="CSharp"
"TemplateGroupIDs(VsTemplate)"="AspNetCore"
"ShowOnlySpecifiedTemplates(VsTemplate)"=dword:00000001

```

**Comment by DeerSteak** [comment]
When I add a new ContentPage or ContentView, even the MAUI ones listed specifically in the MAUI section of the New File dialog, it adds these annoying ItemGroups to the .csproj file. They don't get compiled and they don't even have Intellisense enabled until I unload the project and remove these things. I just did this in a brand new MAUI project to verify. VS2022 Community 17.4.4.

```
	<ItemGroup>
	  <MauiXaml Remove="CustomControls\NewContent1.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="CustomControls\NewContent1.xaml.cs" />
	</ItemGroup>
```

**Comment by mattleibow** [comment]
Moving this back to the VS feedback as this is because there is confusion when Xamarin.Forms templates are visible. And also, the csproj is potentially getting corrupted.
