### ISSUE TITLE
Invoking PropertyChanged() on .NET Maui does not notify Binding View on Android.  Works on Windows and iOS.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8900]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Invoking-PropertyChanged-on-NET-Maui-/10091155)._

---
Following .NET Maui training with James Montemagno's demo in his video: https://www.youtube.com/watch?v=DuNLR_NJv8U&list=TLPQMDcwNzIwMjKVcZMBH7y96A&index=2,
using Visual Studio 22 Preview Version 17.3.0 Preview 2.0, latest updates July 8/22, my Android Version 31, for both emulator and my actual Samsung Note 10+ does NOT trigger a redraw for the view as it does in his demo.  It works on Windows and iOS.  I am able to see that OnPropertyChanged() is triggered using a breakpoint when setting IsBusy, but no response UNTIL I drag on the blank screen that causes it to render.  I can see it worked on his demo.  So, likely something broke in a later release?

---
#### Feedback Bot on 7/10/2022, 07:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
This may have been fixed by #8136.

**Comment by rmarinho** [comment]
Please reopen if it's still a issue with the last version
