### ISSUE TITLE
Changing app icon of .NET MAUI app, then invoking MediaPicker crashes the app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8901]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Changing-app-icon-of-NET-MAUI-app-then/10090581)._

---
\[severity:I’m unable to use this version\]  
Replacing the appicon of a .NET MAUI app, then invoking MediaPicker crashes the app.

I do follow the documentation and clean the project/solution after updating the app icon AND remove the app already installed on device before re-compiling and re-installing it.

I created a public repo and the steps to reproduce the crash in the README file. Here’s the link to my repo:  
[https://github.com/imsam67/maui-appicon-crash](https://github.com/imsam67/maui-appicon-crash)

P.S. I’m using the latest version of Visual Studio 2022 Preview Version 17.3.0 Preview 2.0 on Windows 11 with latest updates.

And here's the SO question I posted: https://stackoverflow.com/questions/72903979/net-maui-app-mediapicker-is-crashing-with-android-content-res-resourcesnotfo

---
#### Feedback Bot on 7/8/2022, 02:57 AM: 

(private comment, text removed)

---
#### Sam Uresin solved on 7/8/2022, 02:06 PM, 0 votes: 

<p>This is definitely an issue caused by the AppIcon – or lack thereof in this case. Looks like .NET MAUI is NOT automatically generating the correct app icons form the svg file placed in <code>Resources\AppIcon</code> folder.</p>
<p>I manually created an icon and placed it under <code>Platforms\Android\Resources\mipmap</code> folder and then linked it in <code>AndroidManifest.xml</code>. It’s important to note that I had to place two files in the <code>Platforms\Android\Resources\mipmap</code> folder i.e. <code>app_icon.png</code> and <code>app_icon_round.png</code>. These two files are then referenced in <code>AndroidManifest.xml</code>.</p>
<p>Now everything is working as it should.</p>
<p>Bottom line, .NET MAUI doesn’t seem to automatically generate the necessary app icon and it looks like the icon is used when we open the photo gallery. Not having the app icon where the app is expecting to find it is what’s crashing the app.</p>

**Comment by jfversluis** [comment]
If the author happens to see this... Would you be able to test with the last release from a couple of days ago? I know we did some improvements on the app icon area.

Let us know what you find with that, thanks!
