### ISSUE TITLE
PlatformBehavior can't be attached to a view Behaviors list

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#8907]
### Description

Using this example which describes that Effects are being replaced with PlatformBehaviors:
https://devblogs.microsoft.com/dotnet/customizing-dotnet-maui-controls/

We can't get a PlatformBehavior to work. The example is badly written, with missing code, 3 different class names for what appears to be the same behaviour, and the end result if you fix everything, you can't then add the platform behavior to the view.Behaviors list. It just doesn't work at all.

Ideally, we should have actual MS documentation on how this should all work. Don't invite guest bloggers without at least peer reviewing the articles.

### Steps to Reproduce

Follow the PlatformBehavior example from here:
https://devblogs.microsoft.com/dotnet/customizing-dotnet-maui-controls/

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Using Effects probably works.

**Comment by jfversluis** [comment]
Thanks for the feedback! I'll be sure to pass it along the the right team.

**Comment by jamesmontemagno** [comment]
I have added a link to reference code: https://github.com/CommunityToolkit/Maui/tree/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor

**Comment by JohnHDev** [comment]
@jamesmontemagno Thanks for that, but I don't see usage of PlatformBehaviors, just native implementations. Am I missing something? Is a PaltformBehavior supposed to be able to be added to view.Behavoirs as per the example?

**Comment by pictos** [comment]
@JohnHDev [here's the usage of the PlatformBehavior](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs#L9). [And here a sample of usage](https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml)

The blog post had not the intention to be a full tutorial on how to use that but to show numerous ways to customize a control in Maui. But maybe we can provide a full and detailed tutorial on that

**Comment by JohnHDev** [comment]
> @JohnHDev [here's the usage of the PlatformBehavior](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs#L9). [And here a sample of usage](https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml)
> 
> The blog post had not the intention to be a full tutorial on how to use that but to show numerous ways to customize a control in Maui. But maybe we can provide a full and detailed tutorial on that

Thanks Pedro I appreciate your efforts, but the misnamed classes didn't lend itself to making the blog post very clear. I will take a look at the full sample as it appears a PlatformBehavior should indeed be capable of being added to a view.Behaviors collection.
