### ISSUE TITLE
CollectionView seems to reuse images when loading more on Android.

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#8920]
### Description

When using a CollectionView with RefreshView (See XAML), and you load more items , using a ObservableCollection, the ObservableCollections datamodel with a imageproperty from a URL, seem to re-use the image url on new item when showing new items based on the ItemTemplate. Is the CollectionView native viewcell disposing the previous image properly before loading new ones?

### Steps to Reproduce

    <Grid RowDefinitions="*,400">
        <Grid
            Grid.RowSpan="2"
            BackgroundColor="{StaticResource BackgroundColor}"
            RowDefinitions="60,45,8*,60,5"
            VerticalOptions="FillAndExpand">

        <RefreshView
                Grid.Row="2"
                Margin="10,20,10,0"
                Command="{Binding RefreshSurveysCommand}"
                IsRefreshing="{Binding IsRefreshing}">

                <CollectionView
                    BackgroundColor="{StaticResource BackgroundColor}"
                    EmptyView="{Binding .}"
                    HorizontalOptions="FillAndExpand"
                    HorizontalScrollBarVisibility="Never"
                    ItemsSource="{Binding Surveys}"
                    RemainingItemsThreshold="{Binding RemainingItemsTreshold}"
                    RemainingItemsThresholdReachedCommand="{Binding LoadMoreSurveysCommand}"
                    VerticalOptions="FillAndExpand"
                    VerticalScrollBarVisibility="Never">
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout ItemSpacing="10" Orientation="Vertical" />
                    </CollectionView.ItemsLayout>

                    <CollectionView.EmptyViewTemplate>
                        <DataTemplate>

                            <skeletonloading:SkeletonRepeater
                                RepeatCount="10"
                                RepeaterTemplate="{StaticResource EmptySurveyTemplate}"
                                Spacing="10"
                                VerticalOptions="FillAndExpand" />

                        </DataTemplate>
                    </CollectionView.EmptyViewTemplate>

                    <CollectionView.ItemTemplate>
                        <DataTemplate x:DataType="models:SurveyModel">

                            <Border
                                BackgroundColor="{StaticResource ComponentBackgroundColor}"
                                HeightRequest="60"
                                HorizontalOptions="FillAndExpand"
                                Stroke="{StaticResource ComponentBackgroundColor}"
                                StrokeThickness="2"
                                VerticalOptions="FillAndExpand">
                                <Border.StrokeShape>
                                    <RoundRectangle CornerRadius="10,10,10,10" />
                                </Border.StrokeShape>

                                <Grid
                                    Margin="0,10"
                                    ColumnDefinitions="1.5*,4*,4.5*"
                                    HeightRequest="60"
                                    HorizontalOptions="FillAndExpand"
                                    RowDefinitions="30,30">
                                    <Grid.GestureRecognizers>
                                        <TapGestureRecognizer Command="{Binding Path=BindingContext.GotoSurveyDetailsCommand, Source={RelativeSource AncestorType={x:Type ContentPage}}}" CommandParameter="{Binding .}" />
                                    </Grid.GestureRecognizers>

                                    <Image
                                        Grid.RowSpan="2"
                                        Margin="10,0"
                                        Aspect="AspectFill"
                                        HeightRequest="40"
                                        HorizontalOptions="Start"
                                        Source="{Binding FirstSurveyImage.ImageFromServerUrl}"
                                        VerticalOptions="Center"
                                        WidthRequest="40" />

                                    <Label
                                        Grid.Column="1"
                                        Margin="10,0,0,0"
                                        HorizontalOptions="Start"
                                        LineBreakMode="TailTruncation"
                                        Style="{StaticResource LabelBase}"
                                        Text="{Binding Title}"
                                        VerticalOptions="End" />

                                    <Label
                                        Grid.Row="1"
                                        Grid.Column="1"
                                        Margin="10,0,0,0"
                                        HorizontalOptions="Start"
                                        LineBreakMode="TailTruncation"
                                        Style="{StaticResource LabelBase}"
                                        Text="{Binding CustomerString}"
                                        VerticalOptions="Start" />

                                    <Label
                                        Grid.Column="2"
                                        Margin="0,0,5,0"
                                        HorizontalOptions="End"
                                        Style="{StaticResource LabelBase}"
                                        Text="{Binding CreatedOn, StringFormat='Opprettet: {0:dd.MM.yyyy}'}"
                                        VerticalOptions="End" />

                                    <Label
                                        Grid.Row="1"
                                        Grid.Column="2"
                                        Margin="0,0,5,0"
                                        HorizontalOptions="End"
                                        Style="{StaticResource LabelBase}"
                                        Text="{Binding ValidUntil, StringFormat='Gyldig til: {0:dd.MM.yyyy}'}"
                                        VerticalOptions="Start">
                                        <Label.Triggers>
                                            <DataTrigger
                                                Binding="{Binding IsExpired}"
                                                TargetType="Label"
                                                Value="True">
                                                <Setter Property="TextColor" Value="IndianRed" />
                                            </DataTrigger>
                                            <DataTrigger
                                                Binding="{Binding IsExpired}"
                                                TargetType="Label"
                                                Value="False">
                                                <Setter Property="TextColor" Value="White" />
                                            </DataTrigger>
                                        </Label.Triggers>
                                    </Label>
                                </Grid>
                            </Border>

                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </RefreshView>
            
            </Grid></Grid>

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Multiple Android versions, also Android 12 , API 31

### Did you find any workaround?

Not yet,

**Comment by jfversluis** [comment]
Does it help if you disable the image caching? https://docs.microsoft.com/dotnet/maui/user-interface/controls/image#image-caching

Or choose another cell reuse strategy?

It would be really helpful if you could put together a small repro project for us to try!

**Comment by RonnyRos** [comment]
Closed this as it was a not a bug, just bad code. :)
