### ISSUE TITLE
Label inside a HorizontalStackLayout inside a Border does not work with TailTruncation

### ISSUE THREAD

**Issue by RonnyRos** [dotnet/maui#8925]
### Description

The label does not tailtruncate inside a Border.

### Steps to Reproduce

Add a Border, with a Horizontal StackLayout and label.
Text does not truncate.

    <Border
                    Grid.Row="1"
                    Margin="20,0"
                    BackgroundColor="{StaticResource ComponentBackgroundColor}"
                    IsVisible="{Binding RefreshData, Converter={StaticResource InvertedBoolConverter}}"
                    Stroke="{StaticResource ComponentBackgroundColor}"
                    StrokeThickness="5">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="10,10,10,10" />
                    </Border.StrokeShape>

                    <HorizontalStackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                        <HorizontalStackLayout.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding Path=GotoLocationPageCommand}" />
                        </HorizontalStackLayout.GestureRecognizers>

                        <Image
                            Margin="20,0,10,0"
                            HeightRequest="20"
                            HorizontalOptions="Center"
                            Source="ic_location.png"
                            VerticalOptions="Center"
                            WidthRequest="20" />

                        <Label
                            HorizontalOptions="StartAndExpand"
                            LineBreakMode="TailTruncation"
                            Style="{StaticResource LabelBase}"
                            Text="{Binding Survey.AddressDetails.FriendlyAddressName}"
                            VerticalOptions="Center" />
                    </HorizontalStackLayout>
                </Border>

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 API 31. Samsung Device: SM-A536B

### Did you find any workaround?

Yes, set width manually on the label.

**Comment by MagdielM** [comment]
Can confirm this also happens on Windows (10.0.19043) as of 6.0.486, with either a `HorizontalStackLayout` or a `StackLayout` with its orientation set to horizontal. Wrapping the layout inside a `Border` doesn't seem to make any difference, and it's not just `TailTruncation`: the `Label` simply always behaves as if its `LineBreakMode` was set to `NoWrap`.

**Comment by pramosfsgroup** [comment]
This also happens with the Label inside a Grid trying to set LineBreakMode="CharacterWrap"

**Comment by hartez** [comment]
HorizontalStackLayout does not subdivide space horizontally - it simply stacks up the child views one after another, taking as much space as it needs. It doesn't stop when it gets to an edge. So your Label's `LineBreakMode` property never comes into play; the HorizontalStackLayout gives it infinite horizontal space, and it fits all of the text on one line.

If you want to subdivide the available space and force line wrapping, you need use a control which doesn't expand forever in the horizontal direction. I'd suggest using a Grid, and subdividing the horizontal space into columns:

```
<Border Margin="20,0" BackgroundColor="Beige" Stroke="Red" StrokeThickness="5">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="10,10,10,10" />
    </Border.StrokeShape>

    <Grid ColumnDefinitions="Auto,*">
        <Image Margin="20,0,10,0" HeightRequest="20" HorizontalOptions="Center" Source="dotnet_bot.png" VerticalOptions="Center" WidthRequest="20" />

        <Label Grid.Column="1" HorizontalOptions="Start" LineBreakMode="TailTruncation" VerticalOptions="Center"
            Text="really long text omitted for brevity"
        />
    </Grid>
</Border>
```

![image](https://user-images.githubusercontent.com/538025/193102730-d3ae6a10-5f2a-4348-8be9-f24d425e5a8d.png)

**Comment by hartez** [comment]
> This also happens with the Label inside a Grid trying to set LineBreakMode="CharacterWrap"

@pramosfsgroup Since you're seeing an issue with a different layout type and a different property, I'd suggest opening a separate issue. Thanks!
