### ISSUE TITLE
Collection View Header and Empty View not showing on Android when ItemSource is null

### ISSUE THREAD

**Issue by 3steve3** [dotnet/maui#8934]
### Description

If the data the CollectionView is bound to is null, then CollectionView.Header and CollectionView.Empty View is not visible. This issue was also tested on the Windows version and the bug does not appear.
A sample of the issue can be found here https://github.com/3steve3/EmptyCollectionViewBug

### Steps to Reproduce

1. Create a new .Net Maui project
2. Create a viewmodel for the view
3. Create a Collection View in the View.
4. Bind the Collection View item source to null variable, CollectionView.Header and CollectionView.EmptyView will not be visible on Android.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

No

**Comment by danielftz** [comment]
ETA on the fix?

**Comment by 99067718** [comment]
I'm pretty sure the header is the problem in your case.

**Comment by 3steve3** [comment]
It's not working with only the empty view, you can clone my repo and comment it out. I added the header because it is not showing either.

**Comment by 3steve3** [comment]
My application needs to have things in a header (if using a collection view) because stacking content and a collection view results in incorrect scroll height.

**Comment by Syed-RI** [comment]
cc @davidortinau @jfversluis @PureWeen . This is a basic requirement thats failing us now. Can you please assign resources in this issue please? I know you guys are working hard and really appreciate the work :) Thank you!

**Comment by 3steve3** [comment]
This is the general workaround I came up with until the bug is fixed
```
<ScrollView>
    <StackLayout>
        This is where the header would be
    </StackLayout>
    <VerticalStackLayout BindableLayout.ItemsSource="{Binding mySource}">
        <BindableLayout.ItemTemplate>
            <DataTemplate x:DataType="model:MyModel">
                the bindable content here
            </DataTemplate>
        </BindableLayout.ItemTemplate>
    </VerticalStackLayout>
</ScrollView>
```

**Comment by AlexeyStarkov** [comment]
CarouselView has the same issue: Empty view doesn't work on Android whether the source collection is null or empty.

**Comment by BurkusCat** [comment]
To confirm for CollectionView: an empty ObservableCollection does not show the empty view on Android for me.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Android 13.0 with below Project:
[8934.zip](https://github.com/dotnet/maui/files/11551087/8934.zip)

Android: CollectionView.Header and CollectionView.EmptyView is not visible.
![image](https://github.com/dotnet/maui/assets/97647558/228cb9c4-e28f-414f-b7ec-4f233ebbd588)

Windows: CollectionView.Header is not visible, CollectionView.EmptyView is visible.
![image](https://github.com/dotnet/maui/assets/97647558/471c4603-7102-491f-a8d3-b88b3f559fe4)

**Comment by HobDev** [comment]
The empty view only shows up in collectionview if it is set to a string., Facing same issue on Windows too.

**Comment by hartez** [comment]
#11763 Fixes part of this issue; with that fix applied, the EmptyView will show up as long as there is no header or footer specified. 

If a header and/or footer are specified, grouping is not enabled, and the items source does not implement INotifyCollectionChanged, then an empty/null ItemsSource will cause the EmptyView, the Header, and the Footer to disappear. Working on a PR for that right now.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/pull/15886
