### ISSUE TITLE
 Build Liberty  failed (Partial method )

### ISSUE THREAD

**Issue by bflyman** [dotnet/maui#8950]
### Description

When I use MAUI Liberty, I use partial methods. Each platform creates an implementation file for a partial method, but it also prompts me to have a partial method that has not been implemented (CS8795).  In my tests, the  TargetFrameworks  in the project file (.csproj) contains net6.0.  When compiling net6.0. partial methods are not implemented because platform files are not used during compilation.  When I tried to provide an implementation outside the platform folder, the analyzer did not report an error. But at build time, hint (CS0757).

PS: This description is generated by the translation software, please be sorry. 

### Steps to Reproduce

1. dotnet new mauilib
2.  public  partial class Class1
    {
        public partial void Tast1();
    }
3. Platforms/(Android,WINDOWS)
 public partial class  Class1
    {
        public partial void Tast1()
        {
            var x = 4;
        }
    }
4. dotnet build

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

Remove the net6.0 target from the project file

**Comment by jfversluis** [comment]
Hey there, thanks for the issue! I'm not really sure what "MAUI Liberty" is. That seems to be a translation mistake of sorts... 

Would you be able to add a reproduction project that shows the issue you see? That probably makes it easier to transfer what you mean and hopefully will make it easier for us to diagnose it.

If I would have to make an assumption, you're asking about a .NET MAUI library. Have a look at how things are set up for existing libraries, for instance the .NET MAUI Community Toolkit (https://github.com/CommunityToolkit/Maui/) maybe that helps you overcome this issue.

**Comment by bflyman** [comment]
> Hey there, thanks for the issue! I'm not really sure what "MAUI Liberty" is. That seems to be a translation mistake of sorts...
> 
> Would you be able to add a reproduction project that shows the issue you see? That probably makes it easier to transfer what you mean and hopefully will make it easier for us to diagnose it.
> 
> If I would have to make an assumption, you're asking about a .NET MAUI library. Have a look at how things are set up for existing libraries, for instance the .NET MAUI Community Toolkit (https://github.com/CommunityToolkit/Maui/) maybe that helps you overcome this issue.

It's about a .NET MAUI library

**Comment by forlayo** [comment]
I am having the same issue but with a regular MAUI project. I've on MAUI project the target of net6.0 to have a way to reference the project from a xUnit test project.

Then when I create partial class on main project and an implementation under Windows and Android platform, the project doesn't compiles as it says that partial class has method not implemented. 

That's as that class and methods aren't implemented on net6.0 target. Not sure on how to deal with this issue :(

**Comment by DiagProf** [comment]
Hello nice that the topic has already been addressed... here is another example.

I do that  https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code  Part:**Partial classes and methods** but in a .net maui **library** 

and get the following error
![image](https://user-images.githubusercontent.com/56319388/194747333-5807efba-ad6f-45d6-b25c-9806cafe7902.png)

here example project





[Demo.zip](https://github.com/dotnet/maui/files/9741130/Demo.zip)

**Comment by mattleibow** [comment]
The error occurs because you do not have an implementation for the net7.0 target framework. You can either remve the net7.0 TFM if you are not using it, or you can do something like this in the service:

```cs
#if !WINDOWS && !ANDROID && !IOS && !MACCATALYST
public partial DeviceOrientation GetOrientation()
{
    throw new NotImplementedException();
}
#endif
```

You may also want to create a dummy implementation for testing. 

This may also be better suited for interfaces so you can work with that and register them with DI and do tests without having to reference concrete types.
