### ISSUE TITLE
WebView weird behaviour on inputs that doesn't happen outside Maui

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/maui#8953]
### Description

In the app i'm currently working to, we have to show a website throught the WebView. When the user inserts some text in the inputs, the focus moves the page until the input is on the top border. Also, while you write, the cursor moves to the beginning for no apparent reason. You can see it in the attached videos. The problem is: i'm not able to reproduce it outside that website (and it's a private website) but the problem doesn't happen if I use it from chrome or from the Xamarin WebView for the same website. So I think there's some property in the website that the maui webview inout handling doesn't like and I need help to at least understand what so we can find a workaround on the website until the bug with the webview is fixed. 

Not tested on iOS

https://user-images.githubusercontent.com/17146198/180600155-31ad635c-145d-4f3a-ae7e-6a2384196add.MP4

https://user-images.githubusercontent.com/17146198/180600160-e42f1a76-bd7b-4d10-9e4b-377d9631265d.MP4

### Steps to Reproduce

Not able to reproduce

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all supported versions

### Did you find any workaround?

No, that's what I'm hoping you could help me for

**Comment by jfversluis** [comment]
So, just checking: this is a regular WebView, right? Not a BlazorWebView?

**Comment by manuelelucchi** [comment]
> So, just checking: this is a regular WebView, right? Not a BlazorWebView?

Yes @jfversluis, it's a standard webview. The website is VueJs based if that helps. I think there are some problem on the focus and data insertion

**Comment by jfversluis** [comment]
@manuelelucchi it's been a while sorry about that. Are you still working on this? Have you tried latest versions of .NET MAUI and is it still happening there?
