### ISSUE TITLE
Entry.Completed and Entry.ReturnCommand not executed

### ISSUE THREAD

**Issue by codedbycurtis** [dotnet/maui#8960]
### Description

When the `ReturnType` property is set to `ReturnType.Search`, the `Entry.Completed` event (and subsequently `Entry.ReturnCommand`) will not be invoked when pressing the return key. The `Entry` will also not lose focus.

[EntryCompletedBug reproduction](https://github.com/codedbycurtis/EntryCompletedBug)

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add an `Entry` control
3. Set the `ReturnType` property to `ReturnType.Search`
4. Add an event handler or bind a command to `Entry.Completed` or `Entry.ReturnCommand`

Expected outcome: The event handler / command is executed when pressing the return key.
Actual outcome: Nothing happens.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

**Comment by jonakirke94** [comment]
Appears to be for any ReturnType except "Default"

**Comment by mpanzica** [comment]
Hi all!
Well, only ReturnType = "Done" works as expected. 
I believe that the offending line is https://github.com/dotnet/maui/blob/56a0c13836968a4de26031e7b5fb449298747699/src/Core/src/Platform/Android/EditTextExtensions.cs#L341
That function returns 'true' only if actionId is Done or the return key has been pressed (and released) on the keyboard.
Hence if the virtual keyboard does not sport the return key, there is no way to fire the Completed event if the actionId is different from "Done".
I guess that the first condition (actionId == ImeAction.Done) should be removed at all.

Please find herewith a temporary workaround for this issue:

1) Create a new handler inherited from EntryHandler on Android:
```
#if ANDROID
class CustomEntryHandler : EntryHandler
{
    protected override void ConnectHandler(AppCompatEditText platformView)
    {
        base.ConnectHandler(platformView);
        platformView.EditorAction += OnEditorAction;
    }

    protected override void DisconnectHandler(AppCompatEditText platformView)
    {
        base.DisconnectHandler(platformView);
        platformView.EditorAction -= OnEditorAction;
    }

    private void OnEditorAction(object sender, Android.Widget.TextView.EditorActionEventArgs e)
    {
        var actionId = e.ActionId;
        var evt = e.Event;

        if (actionId == ImeAction.Done ||
           (actionId == ImeAction.ImeNull && evt?.KeyCode == Keycode.Enter && evt?.Action == KeyEventActions.Up))
            return; //Already handled by base class.

        VirtualView?.Completed();
        e.Handled = true;
    }
}
#endif
```
2) Register new handler on MauiAppBuilder

```
    public static MauiApp CreateMauiApp()
    {
        MauiAppBuilder builder = MauiApp.CreateBuilder();
        builder.UseMauiApp<App>()
#if ANDROID
            .ConfigureMauiHandlers(handlers =>
            {
                handlers.AddHandler(typeof(Entry), typeof(CustomEntryHandler));
            })
#endif
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });
        return builder.Build();
    }
```

That's it.
