### ISSUE TITLE
Two presses of the Tab key are required to move keyboard focus away from a CollectionView item that has a semantic description

### ISSUE THREAD

**Issue by gbarkerz** [dotnet/maui#8964]
### Description

Repro app is https://github.com/gbarkerz/MyVeryFirstMauiApp.

The repro app has a collection of items, and for this test the items all have the same semantic description. If keyboard focus has just moved into the set of items and is at an item, the next press of the Tab key should move keyboard focus away from the item. Instead nothing seems to happen in the app, and Accessibility Insights for Windows reports that a FocusChanged event is raised for the item where keyboard focus already is. 

### Steps to Reproduce

1. Build and run the repro app for Windows.
2. Run Accessibility Insights for Windows, and configure it to report FocusChanged events.
3. Tab into the set of items and notice keyboard focus showing at an item.
4. Press the Tab key.

Result->Nothing seems to happen and Accessibility Insights reports a FocusChanged event for the item where keyboard focus already is.
Expected->Keyboard focus should move to the focusable control that follows the set of items.

The version of .NET is 6.0.400-preview.22330.6.

The image below shows Accessibility Insights reporting UIA FocusChanged events as keyboard focus moves through the app. Two FocusChanged events are raised between focus moving away from the button before the items, and to the button following the items.

![image](https://user-images.githubusercontent.com/77085891/180649755-fbc8afe1-c406-4778-91c1-1fe621c3e4fa.png)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

Press the Tab key twice instead of once to move keyboard focus away from the item.

**Comment by fsteffi** [comment]
GitHubTags:
#.NET MAUI; #AILimited; #A11ySev1; #A11yMAS; #A11yTCS; #Android; #AndroidPhone; #WCAG1.3.1; #GH_.NETMAUI_Android_Apr2022; #Info and Relationships​;
