### ISSUE TITLE
Spelling Mistake in FlexLayout AlignContent options.

### ISSUE THREAD

**Issue by Dallion3K** [dotnet/maui#8966]
### Description

The option "SpaceAround" is missing the 'd' at the end. 
![image](https://user-images.githubusercontent.com/35102142/180657223-373e2bf6-97b0-48e4-8f13-e53526489281.png)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a FlexLayout like in the image.
3. Edit the property "AlignContent" and type "Space".

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

N/A

**Comment by jfversluis** [comment]
@Dallion3K good spot! Luckily for us it seems to be only some helper. Would you be able to verify that actually entering "SpaceAroun" won't work but "SpaceAround" does work?

**Comment by Dallion3K** [comment]
“Space Aroun” won’t compile so you’re right it looks to just be the helper.


“Space Around” does compile but will give this warning.

**Comment by rmarinho** [comment]
fixed by #8983
