### ISSUE TITLE
Two radio buttons in group - set is checked of one of them in run time not worked

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#8971]
### Description

two radio buttons in group - set is checked of one of them in run time not worked
![image](https://user-images.githubusercontent.com/1079689/180729619-3d535329-f487-4b74-b5e1-a6f95b230c6c.png)
How is can be fixed ?
[MauiApp28 - Copy.zip](https://github.com/dotnet/maui/files/9179259/MauiApp28.-.Copy.zip)

### Steps to Reproduce

I attached sample code

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

No

### Relevant log output

```shell
.....
```

**Comment by vhugogarcia** [comment]
Thanks for reporting the issue @danies8. 

I found a workaround to solve this issue. It appears to be a bug in the Radio Buttons either with implicit or explicit grouping not selecting the option you need for, and always selecting the previous of the last option or any other random option. 

Anyways, if somebody needs it, please find below the workaround:

```csharp
protected override async void OnAppearing()
{
        base.OnAppearing();

        // Hack to wait for the radios to be rendered on the screen (Mandatory).
        await Task.Delay(1000);
        
        // Personal code I use to find my radio buttons inside a ScrollView -> HorizontalStackLayout
        var hl = (HorizontalStackLayout)scrollTabs.Content;
        var bl = (IBindableLayout)hl.Children;
        var radios = bl.Children;
        
        // Check the first radio always
        var firstRadio = (RadioButton)radios[0];
        firstRadio.IsChecked = true;
}
```

**Side Note:** I was able to reproduce this issue on **iOS** and **Android** using .NET MAUI 7.0.49

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Can repro on Windows and Android platforms with above project.
repro project:[MauiApp28 - Copy.zip](https://github.com/dotnet/maui/files/9179259/MauiApp28.-.Copy.zip)
![image](https://github.com/dotnet/maui/assets/82450723/2433cb77-f51e-440a-a1c1-d1a36ce1ac0e)

**Comment by dustin-wojciechowski** [comment]
It looks like this issue is fixed when I ran your repro project again main:
```
        radioButtonRecursEvery.IsChecked = true;
        radioButtonAllDay.IsChecked = true;
```
ios:
![Simulator Screenshot - iPhone 15 - 2024-05-14 at 14 46 20](https://github.com/dotnet/maui/assets/89540402/ee6eee75-e0c7-4523-9c0d-f9148a15b729)

android:
![Screenshot_1715724800](https://github.com/dotnet/maui/assets/89540402/459858f1-cc3e-4515-a70e-f22015f595c2)
