### ISSUE TITLE
BoxView BackgroundColor always gray

### ISSUE THREAD

**Issue by tchtang** [dotnet/maui#8972]
### Description

following lesson 
[https://docs.microsoft.com/en-us/learn/modules/customize-xaml-pages-layout/4-arrange-views-stacklayout](url)

<img width="492" alt="1" src="https://user-images.githubusercontent.com/109950893/180734929-2b94e461-672b-41d7-94ce-e457590c3e06.PNG">

result always gray color

<img width="199" alt="2" src="https://user-images.githubusercontent.com/109950893/180735081-e14ccc22-8062-4802-8db0-7cda6af51334.PNG">

### Steps to Reproduce

xaml is

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Notes.NewPage1"
             Title="NewPage1">
    <StackLayout x:Name="stack" Spacing="10">
    </StackLayout>
</ContentPage>
```

code behind is

```
namespace Notes;

public partial class NewPage1 : ContentPage
{
    public NewPage1()
    {
        InitializeComponent();

        var a = new BoxView { BackgroundColor = Colors.Red, HeightRequest = 40 };
        var b = new BoxView { BackgroundColor = Colors.Green, HeightRequest = 40 };
        var c = new BoxView { BackgroundColor = Colors.Yellow, HeightRequest = 40 };

        stack.Children.Add(a);
        stack.Children.Add(b);
        stack.Children.Add(c);
    }
}
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

pixel 5 api 30, window 10

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue in the current .net6.0 branch:

![image](https://user-images.githubusercontent.com/6755973/185106771-f2d94638-7731-4395-998a-ab507d161ed4.png)

@jfversluis Could you try it when you can?. Thanks.

**Comment by tchtang** [comment]
![image](https://user-images.githubusercontent.com/109950893/185349227-a9422298-2f7b-4ad4-a901-288c8a1d5651.png)

![image](https://user-images.githubusercontent.com/109950893/185349516-9af56657-c4cd-4250-b6ba-03b5cb930f8a.png)

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage">

    <VerticalStackLayout>
        <BoxView BackgroundColor ="Aqua" HeightRequest="50" />
        <BoxView Background="Purple"  HeightRequest="50" />
        <BoxView BackgroundColor ="Red" HeightRequest="50" />
        <BoxView BackgroundColor ="Green" HeightRequest="50" />
        <BoxView BackgroundColor ="Yellow" HeightRequest="50" />
    </VerticalStackLayout>
</ContentPage>
```

![image](https://user-images.githubusercontent.com/109950893/185349757-a948233e-d397-464a-be5b-88d26be4fbb7.png)

Microsoft Visual Studio Professional 2022
Version 17.3.0 Preview 6.0
VisualStudio.17.Preview/17.3.0-pre.6.0+32728.150
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00483-00000-00004-AA809
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.3.375.53775
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.375.53775
Azure App Service Tools v3.0.0

C# Tools   4.3.0-3.22375.15+456937d952ad5c0930293ef32c4fbf8c844a9fef
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22375.15+456937d952ad5c0930293ef32c4fbf8c844a9fef
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.295 (d17-3@321c85a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.208 (remotes/origin/d17-3@e4f67afef)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

**Comment by prok155** [comment]
I also face the same issue. BoxView is always dark and I can't change BackgroundColor. I use 6.0.486 version.

**Comment by jsuarezruiz** [comment]
Could you try with the latest .NET MAUI version?. Cannot reproduce the issue with the latest version.
![image](https://user-images.githubusercontent.com/6755973/190177412-1049226e-fd83-4092-af25-cd334aad6dae.png)

**Comment by tchtang** [comment]
having issue upgrade visual studio, will try tomorrow

**Comment by tchtang** [comment]
i need more time to test, will uninstall visual studio next week

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/109950893/190602081-0ff017b6-5231-4adc-be15-5518bac7838f.png">

**Comment by tchtang** [comment]
![image](https://user-images.githubusercontent.com/109950893/190976601-c4c21a34-08fc-4d72-99e5-63d2638e16fb.png)

as 1st message color is gray, after that always black
cannot get back gray color again
could be my laptop install certain software conflict with visual studio

![image](https://user-images.githubusercontent.com/109950893/190976866-eac066c0-463b-4658-b34c-b7f7ef085b3b.png)

**Comment by m-faircloth** [comment]
This was happening to me too. When starting a new Maui project and adding a BoxView, it was always these colors listed in the default styles.xaml. I changed the Property to BackgroundColor and it begin recognizing the custom colors I applied.

<Style TargetType="BoxView">
        <Setter Property="Color" Value="{AppThemeBinding Light={StaticResource Gray950}, Dark={StaticResource Gray200}}" />
</Style>
