### ISSUE TITLE
ScrollView Does Not Work When Inside A VerticalStackLayout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#8990]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ScrollView-Does-Not-Work-When-Inside-A-V/10102103)._

---
[severity:I'm unable to use this version]
As an example when creating a new MAUI project the MainPage controls are inside a VerticalStackView inside a ScrollView.  If you increase the VerticalStackView spacing to 200 you can see the page allows scrolling.
However if you want a control to be outside the Scroll you should add an outer VerticalStackView to hold the new control (e.g. a Label) and the ScrollView.  In this case the ScrollView does not work, there is no scroll bar and the page can not be scrolled.

**MainPage.xaml with scrolling.**

    

        
            

                

                <label>

    

        <label>

        
            

                

                <label>

---
#### Feedback Bot on 7/24/2022, 07:19 PM: 

(private comment, text removed)

---
#### Glenn Taylor solved on 7/25/2022, 08:24 AM, 0 votes: 

<p>After further research I now understand how this works and why this seems to be an issue.</p>
<p>The VerticalStackLayout doesn’t put any vertical constraints on the content (by definition), so there are no vertical constraints on the ScrollView. The ScrollView sizes itself to the content until it hits a vertical constraint; after that, it stops expanding and the content becomes scrollable. But since there’s no vertical constraint to hit, that never happens.</p>
<p>There are two solutions.</p>
<ol>
<li>Set a HeightRequest for the ScrollView.</li>
<li>Use a Grid instead of a VerticalStacklayout.  Grid rows hold the child controls including the Scrollview.</li>
</ol>
<p>Once understood this is no longer an issue.</p>

**Comment by jfversluis** [comment]
Looking at the comment in vsfeedback, it seems this is resolved. Let us know if there is still something to do here. Thanks!
