### ISSUE TITLE
Use Blazor Hybrid with own rendering/interaction pipeline

### ISSUE THREAD

**Issue by honzapatCZ** [dotnet/maui#8993]
### Description

I'd like to be able to use custom Renderers for the Blazor UI, that's now(thanks to Blazor Hybrid) hosted in the parent process with access to all the underlying system(ie not wasm, thats not really useful). I suppose there's already at least some interface as even the docs state, that "Components render to an embedded Web View and control through a local interop channel". Having custom rendering and/or input would mean changing the second part of the sentence.

### Public API Changes

For getting the buffer sth. like
```cs
public Bitmap GetOutputImage();
public void SetOutputStream(WritableStream stream);
```
And for passing the inputs
```cs
public void SetMousePosition(System.Windows.Point position);

public void KeyboardKeyUp(KeyCode key);
public void KeyboardKeyDown(KeyCode key);
public void MouseButtonUp(MouseButton mouse);
public void MouseButtonDown(MouseButton mouse);
...etc
```

### Intended Use-Case

I'd like to use such for having a Desktop App as well as Overlay host in one app. A Dll could then be injected into any game/app and read the shared buffer for "to be rendered image". The Dll could also send back commands like mouse move or click, keyboard events, etc.

**Comment by honzapatCZ** [comment]
I've investigated a bit furter.
Basically what Iam asking is abstracting away the custom Controls(WPF, MAUI, WinForms) to some interface, which could then be used from the united WebView2WebViewManager. Currently there's a lot of overlap with preprocessor defines, but I think they could be abstracted away. In the end WebView would manage its control(WPF, WinForms, MAUI) implementation and dotnet/maui its abstracted platform/control agnostic WebView2WebViewManager and per platform BlazorWebview wrapper components.

**Comment by javiercn** [comment]
@honzapatCZ thanks for contacting us.

This is not a direction we plan to take, as it might drastically limit our ability to make changes in the future and it is a very specialized feature request that has not send widespread customer demand.

The best you can do is build your own flavor to suit your needs, however, the Blazor Hybrid internals are something that might be subject to change in the future and could break at any point, it is not a supported extensibility scenario.

**Comment by honzapatCZ** [comment]
Hello
I understand that his is not a high priority, but in itself could easy implementations of different libraries and make the overall concept simpler.
I believe this is partially what someone asked about in properly separing the functionality from the platforms.

Currently I really can't wrap my head around why WebView2WebViewManager in SharedSource is using Platform dependant versions of the controls. I don't see a reason why that can't be an interface(IWebViewControl) which is then populated in the Platform specific controls by the platform specific drawer/window implementations.

That also brings another problem. WebView is not actually part of the application but is a mere window overlayed on top, which brings its own problems into the WPF/UWP/MAUI world. Such proposed rendering implementation would solve such problems even if that would mean providing WebView some canvas implementation to draw itself into or polling it for its frames.

**Comment by honzapatCZ** [comment]
I don't actually think Ill be reimplementing Blazor. Ill just be reimplementing WebViewManager2(the request filtering, etc.), as actually WebViewManager is abstracted enough, that's why the spliting in WVM2 is weird.

**Comment by javiercn** [comment]
@honzapatCZ as I mentioned, that is not an extensibility point we plan to offer in the near future, as we haven't seen demand to justify it. You can if you want at your own risk, replicate the Blazor Desktop code in your own implementation to suit your concrete scenarios.

**Comment by honzapatCZ** [comment]
I researched this further and apparently WebView2 is still missing Offscreen rendering, so that's what Iam looking forward RN.
