### ISSUE TITLE
[Windows] Faced no installed components were detected exception

### ISSUE THREAD

**Issue by ashok-kuvaraja** [dotnet/maui#8997]
### Description

Hi Team,

We have created the custom control by using the Layout class. There are two classes (parent and child) derived from the Layout class in our custom control. In that control, we initialize all the properties in the child class' measure method itself instead of the parent class. So, After initializing the properties, we need to add a child to the parent class for a purpose. In this case, we are facing the no installed components were detected exception. We prepared a simple sample to reproduce the issue. Please check and update us or provide us a proper way to add a child to parent from its child at runtime (workaround) if we are wrong. 

### Steps to Reproduce

1. Run the below sample.
[SimpleSample.zip](https://github.com/dotnet/maui/files/10917687/SimpleSample.zip)
2. Click the click me button.
3. Exception will be thrown from the child adding place. 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Relevant log output

```shell
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in WinRT.Runtime.dll but was not handled in user code
No installed components were detected.

The program '[12208] SfViewSimpleSample.exe' has exited with code 4294967295 (0xffffffff).
```

**Comment by MagicAndre1981** [comment]
I get the same issue when using the DataGrid from syncfusion to display data. SfViewSimpleSample shows me that you also use their controls. So bug in their lib?

**Comment by jfversluis** [comment]
Hey there, thanks for the report! Two things:
1. Could you please provide the repro through a GitHub repo
2. Can you also reproduce this without the Syncfusion controls, to rule out that this is something that is happening there.

Thanks!

**Comment by ashok-kuvaraja** [comment]
Hi @jfversluis,

Thanks for the update.

In that simple sample, I reproduced the issue without using the Syncfusion controls. You can reproduce the issue by following the `steps to reproduce` procedure. Please check that sample and let me know your feedback,

Regards,
Ashok

**Comment by MagicAndre1981** [comment]
syncfusion support said they fix my DataGrid [with this weeks updates](https://www.nuget.org/packages/Syncfusion.Maui.DataGrid/20.2.43) , but I run into a new COMException:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
Error HRESULT E_FAIL has been returned from a call to a COM component.
```
so I can't say if their update fixed my issue or not 🤷‍♂️

**Comment by MagicAndre1981** [comment]
ok, the error `HRESULT E_FAIL has been returned from a call to a COM component.` was caused by [syncfusions SfBusyIndicato](https://help.syncfusion.com/maui/busy-indicator/overview)r, now app starts and shows data in the grid and the original error `No installed components were detected.` is gone.

**Comment by mattleibow** [comment]
Is this still an issue? I can't tell :)

**Comment by ashok-kuvaraja** [comment]
Hi @mattleibow,

Still I could face this issue in the lastest version too. Can you please check? 😬

<img width="550" alt="image" src="https://user-images.githubusercontent.com/60499432/223632884-a16cdec5-5b04-4430-b02c-cc1f1d31c3ea.png">

**Comment by mattleibow** [comment]
And the exception is just because when you do something WinUI does not like, it just dies. The Windows team is working on getting better exceptions so in recent WindowsAppSDK updates you may get better messages.
