### ISSUE TITLE
NavigationPageRenderer bug on Android

### ISSUE THREAD

**Issue by alexseho** [dotnet/maui#9003]
`handlers.AddCompatibilityRenderer(typeof(NavigationPage), typeof( xNavigationR));`

`
public class xNavigationR : NavigationPageRenderer
    {
        public xNavigationR(Context context) : base(context)
        { 
        } 
    }
`

when added a compatibility renderer to NavigationPage, pushasync not working on NavigationPage.

---

i want to use this: 
`protected override void SetupPageTransition(FragmentTransaction transaction, bool isPush)
		{
			if (isPush)
				transaction.SetCustomAnimations(Resource.Animation.enter_from_right, Resource.Animation.exit_to_left);
			else
				transaction.SetCustomAnimations(Resource.Animation.enter_from_left, Resource.Animation.exit_to_right);
		}`

**Comment by mrtcn** [comment]
I'm having the exact issue. I also couldn't find a way to migrate NavigationPageRenderer to the new handler approach.

**Comment by amittapelly11** [comment]
I'm also having the same issue. Any update on this.

**Comment by SagarPanwala** [comment]
Without this, I think we can't  port our Xamarin Forms to MAUI. As soon as we add NavigationPageRenderer maui app started to crash for Android and works for ios.

**Comment by SagarPanwala** [comment]
Were you guys able to get this done with handler?
I'm getting it hard to achieve, so please help me if anyone has work around to add animation for page transition.

**Comment by raypac** [comment]
As of writing, I am still encountering this same issue.  Is there an alternative to this?

**Comment by orwo1** [comment]
Migrating from Xamarin.Forms with PageRenderer on Android side to support custom transition,
encountered this as well.
Overriding the 4 xml files (suggested in https://github.com/dotnet/maui/issues/16353#issuecomment-1660441130)
is not really a solution, as it also affects our Splash Activity (as in the splash now animates into and out of the screen like a regular page).
Is there a time frame to support custom transitions in Maui?

**Comment by orwo1** [comment]
This doesn't need a repro, the op says everything including the code.
Can we get a response from someone in Microsoft on this issue?

**Comment by iberosmen** [comment]
same bug today

**Comment by FreakyAli** [comment]
+ 1 this should be addressed!!!

**Comment by phillippschmedt** [comment]
This issue got all the information needed. Don’t close it.

**Comment by FreakyAli** [comment]
Exactly what I was about to comment this issue already has everything you need this should not be closed!
