### ISSUE TITLE
Include support for high-Speed Bluetooth Printing and QrCode Scanning in MAUI for POS systems

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#9006]
### Description

Currently i could not find any Printing related example/library to print to Bluetooth connected Thermal Printers for Receipt Printing.
Similarly, i could not find any libraries to high-Speed Scan QrCode.

Both of this are mandatory to create POS Applicaitons.

### Public API Changes

None, these will be new Libraries

### Intended Use-Case

IN POS(Point of Sale) Applications that run on Hand Held Devices, Scanning QRCode and printing Receipts & Labels(with QrCode) are essential.

Without this feature, MAUI cannot be used on Retail or Warehouse related Application and environments

**Comment by DavidCarKc** [comment]
Hi, I was working on similar app 3 months ago an I got it to print to bluetooth printer from android with following code below, now since the rest of the app keeps crashing I'm waiting with it's developement till the MAUI gets more stable, and I haven't compiled the code to test it on newer versions of MAUI but it might be OK. It should send ECS/POS command directly via bt as com port to the printer. I was also trying to create rft file and then print it form android OS, it can get more fonts that way but I could not get it to set the paper as continous like  POS uses. 

Android.Bluetooth.BluetoothAdapter btAdapter = Android.Bluetooth.BluetoothAdapter.DefaultAdapter;
        var device = btAdapter.BondedDevices.FirstOrDefault(d => d.Name == GV.BTprinter);
        var _socket = device.CreateRfcommSocketToServiceRecord(Java.Util.UUID.FromString("00001101-0000-1000-8000-00805f9b34fb"));
        _socket.Connect();
await BTPRINT(_socket, ispis, true, true, true, true, true, 1);
await BTQR(_socket, qrkod, (byte)0x08);
#if ANDROID
    private async Task BTPRINT(Android.Bluetooth.BluetoothSocket _socket, string text, bool visi, bool dulji, bool podebljani, bool podcrtani, bool inverse, int aline)
    {
        const byte Underline = 1 << 7;
        const byte DoubleHeight = 1 << 5;
        const byte DoubleWidth = 1 << 4;
        const byte Bold = 1 << 3;

        if (aline != 0)
        {
            byte[] aline1 = { 27 };
            await _socket.OutputStream.WriteAsync(aline1, 0, 1);
            byte[] aline2 = { 97 };
            await _socket.OutputStream.WriteAsync(aline2, 0, 1);
            if (aline == 1)
            {
                byte[] aline31 = { 1 };
                await _socket.OutputStream.WriteAsync(aline31, 0, 1);
            }
            if (aline == 2)
            {
                byte[] aline32 = { 2 };
                await _socket.OutputStream.WriteAsync(aline32, 0, 1);
            }
        }

        if ((podcrtani) || (visi) || (dulji) || (podebljani))
        {
            byte[] tempArray = { 27 };
            await _socket.OutputStream.WriteAsync(tempArray, 0, 1);
            byte[] tempArray1 = { 33 };
            await _socket.OutputStream.WriteAsync(tempArray1, 0, 1);
            if ((podcrtani) && (visi) && (dulji) && (podebljani))
            {
                byte[] tempArray2 = { Underline + DoubleHeight + DoubleWidth + Bold };
                await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
            }
            if ((podcrtani) && !(visi) && !(dulji) && !(podebljani))
            {
                byte[] tempArray2 = { Underline };
                await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
            }
            if (!(podcrtani) && (visi) && !(dulji) && !(podebljani))
            {
                byte[] tempArray2 = { DoubleHeight };
                await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
            }
            if (!(podcrtani) && !(visi) && (dulji) && !(podebljani))
            {
                byte[] tempArray2 = { DoubleWidth };
                await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
            }
            if (!(podcrtani) && !(visi) && !(dulji) && (podebljani))
            {
                byte[] tempArray2 = { Bold };
                await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
            }


        }



        if (inverse)
        {
            byte[] tempArray4 = { 29 };
            await _socket.OutputStream.WriteAsync(tempArray4, 0, 1);
            byte[] tempArray5 = { 66 };
            await _socket.OutputStream.WriteAsync(tempArray5, 0, 1);
            byte[] tempArray6 = { 1 };
            await _socket.OutputStream.WriteAsync(tempArray6, 0, 1);
        }

        byte[] originalBytes = System.Text.Encoding.Latin1.GetBytes(text);
        await _socket.OutputStream.WriteAsync(originalBytes, 0, originalBytes.Length);

        //VRAĆANJE
        if (inverse)
        {
            byte[] tempArray4 = { 29 };
            await _socket.OutputStream.WriteAsync(tempArray4, 0, 1);
            byte[] tempArray5 = { 66 };
            await _socket.OutputStream.WriteAsync(tempArray5, 0, 1);
            byte[] tempArray6 = { 0 };
            await _socket.OutputStream.WriteAsync(tempArray6, 0, 1);
        }
        if ((podcrtani) || (visi) || (dulji) || (podebljani))
        {
            byte[] tempArray = { 27 };
            await _socket.OutputStream.WriteAsync(tempArray, 0, 1);
            byte[] tempArray1 = { 33 };
            await _socket.OutputStream.WriteAsync(tempArray1, 0, 1);
            byte[] tempArray2 = { 0 };
            await _socket.OutputStream.WriteAsync(tempArray2, 0, 1);
        }

        if (aline != 0)
        {
            byte[] aline1a = { 27 };
            await _socket.OutputStream.WriteAsync(aline1a, 0, 1);
            byte[] aline2a = { 97 };
            await _socket.OutputStream.WriteAsync(aline2a, 0, 1);
            byte[] aline4 = { 0 };
            await _socket.OutputStream.WriteAsync(aline4, 0, 1);
        }


        //PRINTAJ I OČISTI BUFFER

        byte[] printcommand = { 12 };
        await _socket.OutputStream.WriteAsync(printcommand, 0, 1);
        byte[] printcommand2 = { 27 };
        await _socket.OutputStream.WriteAsync(printcommand2, 0, 1);
        byte[] printcommand3 = { 64 };
        await _socket.OutputStream.WriteAsync(printcommand3, 0, 1);

        Thread.Sleep(100);
    }
    private async Task BTQR(Android.Bluetooth.BluetoothSocket _socket, string text, byte velicina)
    {

        string qrdata = text;
        int store_len = qrdata.Length + 3;
        byte store_pL = (byte)(store_len % 256);
        byte store_pH = (byte)(store_len / 256);


        // QR Code: Select the model
        //              Hex     1D      28      6B      04      00      31      41      n1(x31)     n2(x00) - size of model
        // set n1 [49 x31, model 1] [50 x32, model 2] [51 x33, micro qr code]
        // https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=140
        byte[] modelQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, (byte)0x04, (byte)0x00, (byte)0x31, (byte)0x41, (byte)0x32, (byte)0x00 };

        // QR Code: Set the size of module
        // Hex      1D      28      6B      03      00      31      43      n (ovo n određuje veličinu)
        // n depends on the printer
        // https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=141
        //	byte[] sizeQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, (byte)0x03, (byte)0x00, (byte)0x31, (byte)0x43, (byte)0x08 };
        byte[] sizeQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, (byte)0x03, (byte)0x00, (byte)0x31, (byte)0x43, velicina };


        //          Hex     1D      28      6B      03      00      31      45      n
        // Set n for error correction [48 x30 -> 7%] [49 x31-> 15%] [50 x32 -> 25%] [51 x33 -> 30%]
        // https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=142
        byte[] errorQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, (byte)0x03, (byte)0x00, (byte)0x31, (byte)0x45, (byte)0x31 };


        // QR Code: Store the data in the symbol storage area
        // Hex      1D      28      6B      pL      pH      31      50      30      d1...dk
        // https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=143
        //                        1D          28          6B         pL          pH  cn(49->x31) fn(80->x50) m(48->x30) d1…dk
        byte[] storeQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, store_pL, store_pH, (byte)0x31, (byte)0x50, (byte)0x30 };


        // QR Code: Print the symbol data in the symbol storage area
        // Hex      1D      28      6B      03      00      31      51      m
        // https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=144
        byte[] printQR = { (byte)0x1d, (byte)0x28, (byte)0x6b, (byte)0x03, (byte)0x00, (byte)0x31, (byte)0x51, (byte)0x30 };

        // flush() runs the print job and clears out the print buffer
        //flush();

        // write() simply appends the data to the buffer

        //write(modelQR);
        await _socket.OutputStream.WriteAsync(modelQR, 0, modelQR.Length);
        //write(sizeQR);
        await _socket.OutputStream.WriteAsync(sizeQR, 0, sizeQR.Length);
        //write(errorQR);
        await _socket.OutputStream.WriteAsync(errorQR, 0, errorQR.Length);
        //write(storeQR);
        await _socket.OutputStream.WriteAsync(storeQR, 0, storeQR.Length);
        //write(qrdata.getBytes());
        byte[] bytesQR = System.Text.Encoding.ASCII.GetBytes(qrdata);
        await _socket.OutputStream.WriteAsync(bytesQR, 0, bytesQR.Length);
        //write(printQR);
        await _socket.OutputStream.WriteAsync(printQR, 0, printQR.Length);
        //flush();
        byte[] printcommand = { 12 };
        await _socket.OutputStream.WriteAsync(printcommand, 0, 1);
        byte[] printcommand2 = { 27 };
        await _socket.OutputStream.WriteAsync(printcommand2, 0, 1);
        byte[] printcommand3 = { 64 };
        await _socket.OutputStream.WriteAsync(printcommand3, 0, 1);

    }
#endif

**Comment by shinnthant-lab** [comment]
We need this very urgently.

**Comment by skenuo** [comment]
I'm waiting for this feature. Our applications are warehouse or retail related.

**Comment by jenscski** [comment]
Don't expect that Maui will include high speed barcode/qr-code scanning, this usually something you need to pay for. And the price reflects what you get.

There are several companies bringing high speed, high performance scanning to mobile devices, not sure if they support Maui yet, but they usually have libraries for Xamarin, so if we are lucky they are supporting Maui soon.

I have used these two, and they work very well (but there are other out there too)
* https://codecorp.com/
* https://www.scandit.com/

**Comment by CyberryCJ** [comment]
I have a simple project using Maui blazor on how to print using Bluetooth POS printer..

**Comment by Redth** [comment]
Thanks for the suggestion.  Unfortunately, this is outside of the scope of MAUI and as mentioned by previous comments, there's some other options to consider to achieve some of these functions.  There's also a https://github.com/Redth/ZXing.Net.Maui for barcode scanning.

These ideas are great spaces for the community to build plugins/nuget packages around.  Perhaps if you build something you can share it back to the community as well!
