### ISSUE TITLE
CollectionView does not resize when items becomes invisible

### ISSUE THREAD

**Issue by causerm** [dotnet/maui#9023]
### Description

When an item's isVisible property in a CollectionView is set to false, the item is hidden as expected, however, the CollectionView does not resize to free the space of the now hidden item and an empty space remains. 

A similar issue has been reported for the Xamarin.Forms project https://github.com/xamarin/Xamarin.Forms/issues/5647

### Steps to Reproduce

1. Create a CollectionView
2. Toggle the IsVisible property of the items contained in the CollectionView to hide the item

Observed Behavior: An empty space remains for every hidden item
Expected Behavior: The  CollectionView should resize, i.e. no empty space is left

Repro: https://github.com/causerm/collectionviewmau

![Screenshot_1658921230](https://user-images.githubusercontent.com/79228869/181237235-f30b78c0-92b6-4f0a-b223-d57233a0de07.png)

![Simulator Screen Shot - iPhone 8 - 2022-07-27 at 05 26 14](https://user-images.githubusercontent.com/79228869/181237238-ca946820-26bf-4a95-bd82-8e634456a1e8.png)

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 14.2, Android 21.0

**Comment by janseris** [comment]
Should this work?  Why not remove the item from data source?

**Comment by causerm** [comment]
I would consider removing the item a workaround. Anywhere else in XF and Maui setting some control to invisible will result in the parent container to resize. Any layout, e.g. Grid, Stacklayout would be an example. Why should this not work in a CollectionView?

**Comment by janseris** [comment]
Because collectionview is not a layout container but a data source bound control
I am telling from years of experience with desktop controls. Having this work seems like a bad idea

**Comment by causerm** [comment]
The use case is to collapse and expand items in the CollectionView. I want to hide all items in a grouped list when the user taps on a header. In a previous project, we had a similar use case where the user would tap on an icon to expand/collapse some details belonging to an item.  I would argue that there are plenty of cases where this would be useful

**Comment by causerm** [comment]
If I use a bindable StackLayout instead of a CollectionView and hide items, the behavior is as I would expect it, the item is hidden and does not take up any space.

**Comment by janseris** [comment]
> The use case is to collapse and expand items in the CollectionView. I want to hide all items in a grouped list when the user taps on a header. In a previous project, we had a similar use case where the user would tap on an icon to expand/collapse some details belonging to an item. In the latter example, just removing the item would not cut it but I would need to replace it with an item without details. I would argue that there are plenty of cases where this would be useful and it's not reasonable that I need to manipulate the date source so the UI hides something properly. Feels hacky to me

Could this be achieved using conditional item template? E.g. if there is a property HasDetails, the item shows larger with more content? 
You can only use items of 1 type (data of 1 type) in CollectionView datasource I suppose.

If items need very specific reaction to events which maybe cannot be done using binding and item template etc., maybe CollectionView is not the right choice.

**Comment by ammar-madni** [comment]
Looks similar to #8820.

**Comment by causerm** [comment]
> Could this be achieved using conditional item template? E.g. if there is a property HasDetails, the item shows larger with more content (declarative approach using XAML).
> 
> If items need very specific reaction to events which maybe cannot be done using binding and item template etc., maybe CollectionView is not the right choice.

There are ways to achieve this for sure, one way or another. Here are all the workarounds I can think of. Maybe this will help out others who have the same problem in the future:

1) As suggested, I could swap out an item based on a bound property (HasDetails or IsVisible) and an TemplateSelector. To completely hide an item I would need to swap that item with an "empty" item to get the height down to zero.  

2) I could also use a bound StackLayout where I emulate the grouped list look of the CollectionView by using a TemplateSelector to insert (fake) headers followed by ordinary items. The StackLayout seems to resize properly so I could hide items without a problem. 

3) I could also add a data trigger to the layout, to request a height of zero if IsVisible is set to false. The tricky part is how to expand the item again back to its full height once it is set to being visible again. I could hardcode that height value of course. Not very pretty IMO. I believe in Xamarin.Forms you could set the HeightRequest to -1 which would trigger the Height to be calculated from scratch resulting the item expanding. This did not work with Maui when I tried 
  
     <Trigger TargetType="Grid"
              Property="IsVisible"
              Value="False">
         <Setter Property="HeightRequest"
                 Value="0" />
       </Trigger>

That said I would prefer not having to go down any of these routes

**Comment by softlion** [comment]
This is by design. On iOS native or Android native, same design.
If you need to change a cell's height, remove it then readd it.
Not ideal, but it's OS design for performance ...

**Comment by jfversluis** [comment]
I'm afraid I have to agree with the other people here that this doesn't seem to be a bug. This is the behavior also on the platforms and I don't think it's likely that we will change this anytime soon. If this is important to you I think it would make sense to open a feature request with a detailed description of how you think this should work and how you would want to use it. Then we can see if that makes sense and if the issue shows some traction and gauge if more people want this.

There is the Expander in the Xamarin Community Toolkit that is to be ported to the .NET MAUI Community Toolkit. Maybe that is a good/better fit for what you're trying to do.
