### ISSUE TITLE
Bug in .NET MAUI Entry View for Android

### ISSUE THREAD

**Issue by pfafft33** [dotnet/maui#9031]
### Description

See the sample project on github at:  https://github.com/pfafft33/TestNewMAUIApp

When I run it under "Windows Machine" it works as expected. The Entry fields show up with a background color of AliceBlue, and you can click in the Entry fields to activate them, and you can enter data.

But, when I run it on my "Android Local Device", which is a "Motorola moto g(7) power (Android 10.0 API29)", the entry fields do not show up (no AliceBlue rectangle) and there is no way to click in the field to activate it, and no way to enter data.

This buggy behavior is also demonstrated when running it under "Android Emulator" (Pixel 2 Pie 9.0 - API 28).

### Steps to Reproduce

1. Open the project from github at:  https://github.com/pfafft33/TestNewMAUIApp
2. Select "Windows Machine" and run the app to demonstrate that it works fine under Windows.
3. Now Select "Android Emulator" (Pixel 2 Pie 9.0 - API 28) and run the app to see that the Entry fields are NOT visible (no AliceBlue background) and there is now way to click and activate the field to enter data.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 and Android 10

### Did you find any workaround?

I posted this issue on StackOverflow (https://stackoverflow.com/questions/73074929/bug-in-net-maui-entry-view-for-android) and Liyun Zhang of MSFT responded and determined that the issue is caused by the Default Entry field WIDTH being  ZERO for Android.
She said that by setting the "WidthRequest" or "MinimumWidthRequest" value to greater than zero would fix the problem.

I STILL claim that this is a BUG, since the work-around REQUIRES that you set the WidthRequest.
If WidthRequest is REQUIRED just to get the Entry field to be visible and click-able, then the Analyzers should flag the code with a Warning or an Error when you do not set the WidthRequest. This is NOT the case. The sample project shows no Warnings or Errors.

In my opinion, the default Entry field Width in Android should be set to some reasonable value greater than ZERO, just as it obviously must be in Windows, since the Entry fields show up fine in Windows.

**Comment by jfversluis** [comment]
Thanks for the report @pfafft33! If lists version 6.0.400 as the affected version, it seems this is a newer version at this time and I think those have some fixes in this area. Would you be able to upgrade your Visual Studio and .NET MAUI workload to the latest version and try again if this is still an issue?

Thanks!

**Comment by pfafft33** [comment]
@jfversluis 
I thought I WAS on the latest version!!!
My "Visual Studio Installer" program shows:
Visual Studio Community 2022 Preview 17.3.0 Preview 5.0
and it doesn't show ANY upgrade being available???

**Comment by pfafft33** [comment]
WONDERFUL NEWS!!!
This bug has been fixed in version:  VS Community 2022 Preview v 17.3.0 Preview 6.0

**Comment by pfafft33** [comment]
I was reading Microsoft Docs about ".NET MAUI Control Customization with Handler" at:

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize

Based on what I saw there, I tried the following code in my MauiProgram.cs file:

    public static void ModifyEntry()
    {
        Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping("EntryWidthNonZeroForAndroid", (handler, view) =>
        {
#if ANDROID
            handler.PlatformView.SetMinimumWidth(200);
#endif
        });
    }

My Entry View field on my page is still invisible and un-clickable, on any Android platform, until I set MinimumWidthRequest in the XAML file.

**Comment by pfafft33** [comment]
AHA!!! - I found a really easy work-around.
Go into the Resources/Styles/Styles.xaml file and edit the Style block of code for TargetType="Entry" and insert the line:
<Setter Property = "MinimumWidthRequest" Value="50" />

```
    <Style TargetType="Entry">
        <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}" />
        <Setter Property="BackgroundColor" Value="Transparent" />
        <Setter Property="FontFamily" Value="OpenSansRegular"/>
        <Setter Property="FontSize" Value="14" />
        <Setter Property="PlaceholderColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
        <Setter Property="MinimumWidthRequest" Value="50" />
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal" />
                    <VisualState x:Name="Disabled">
                        <VisualState.Setters>
                            <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Gray300}, Dark={StaticResource Gray600}}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

```

I discovered this solution by watching the .NET Conf: Focus on MAUI video on YouTube.
Thanks Microsoft for all the YouTube videos that you share with the community!!!

I do still consider this a work-around, and would still like to see this get fixed eventually.

**Comment by eramrit78** [comment]
I have faced same issue .

**Comment by JawadJaber** [comment]
I am facing the same issue, but I have noticed that this problem are appearing only when I push the page modally!

**Comment by hartez** [comment]
In .NET 7 (using VS 17.4.4), the Entries are now visible and functional.
