### ISSUE TITLE
Add support for Android queryProductDetails

### ISSUE THREAD

**Issue by Adelzu** [dotnet/maui#9034]
### Description

Currently, Android.BillingClient.Api only provides 2 method to query data from play store
`public abstract void QuerySkuDetails(SkuDetailsParams p0, ISkuDetailsResponseListener p1)`
and
`public Task<QuerySkuDetailsResult> QuerySkuDetailsAsync(SkuDetailsParams skuDetailsParams)`

Since this API is deprecated and Google Play Subscription Structure has changed, access to the QueryProductDetails and queryProductDetailsAsync are vital.

### Public API Changes

```csharp
public abstract void QueryProductDetailsAsync (QueryProductDetailsParams params);
```

### Intended Use-Case

In the current API, we can only use legacy mode which makes it difficult to offer different billing options for the same plan.
In addition, the current legacy mode might be removed any time.

**Comment by czmirek** [comment]
I just found out that version 5.0.0 of the [Xamarin Billing Client](https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient) has been recently released and it has `QueryProductDetailsAsync` in it.

**Comment by mattleibow** [comment]
Good to hear!

Issues relating to those nugets are best opened on that repo: https://github.com/xamarin/GooglePlayServicesComponents
