### ISSUE TITLE
Using `.Net Maui Community Toolkit` to change the `TintColor` at runtime.

### ISSUE THREAD

**Issue by BODYsuperman** [dotnet/maui#9036]
### Description

Using `.Net Maui Community Toolkit` to change the `TintColor` at runtime.
`DynamicResource` should work instead of `StaticResource`.

### Steps to Reproduce

1. Create a MAUI project
2. Install CommunityToolkit.Maui with version 1.2.0
3. Add the following code in MainPage.xaml, don't forget adding xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit" in the ContentPage property.
   

```

       <Image  Source="dotnet_bot.svg">
                <Image.Behaviors>
                           </Image>
<mct:IconTintColorBehavior TintColor="{AppThemeBinding Light={DynamicResource Gray950}, Dark={DynamicResource White}}"/>
                </Image.Behaviors>
       </Image>
```

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

Android 11 Windows machine

**Comment by mattleibow** [comment]
If there is an issue with the community toolkit, please open an issue on the toolkit: https://github.com/CommunityToolkit/Maui
