### ISSUE TITLE
Add comment to Colors.xaml about Android specific colors

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#9039]
### Description

I thought that the `Resources\Styles\Colors.xaml` file would contain all colors that are used by MAUI and then complained about certain colors cannot be changed. After some weeks of MAUI experience I know by accident discovered `Platforms\Android\Resources\values\colors.xml` which changes the colors of controls I thought cannot be changed. I suggest to add a small comment in `Colors.xaml` file telling users that for Android more colors can be found in `Platforms\Android\Resources\values\colors.xml`

For a new developer it is not as obvious as Resources/Styles is.

### Public API Changes

Resources\Styles\Colors.xaml

```XAML
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

++    <!-- Note: For Android please see also Platforms\Android\Resources\values\colors.xml -->

    [...]

</ResourceDictionary>
```

### Intended Use-Case

Changing colors of MAUI controls

**Comment by mattleibow** [comment]
What colors were you trying to change?

In some cases, colors for various control states are set using the VisualStateManager.

Using the platform colors.xml is not meant to be used by most developers as they should all generally be available in the cross-platform colors. And, if it is added in the Android folder, none of the other platforms can use it.

**Comment by Symbai** [comment]
> What colors were you trying to change?

For example the "Ok" button text color on the dialogs which is by default purple on Android. If you change the colors in the cross platforms colors, which changes all button colors except of the dialog buttons.

**Comment by mattleibow** [comment]
I think you are referring to this issue? https://github.com/dotnet/maui/issues/6092

**Comment by Symbai** [comment]
I'm referring to these:
https://github.com/dotnet/maui/discussions/6579
https://github.com/dotnet/maui/issues/7542

But there might be others too. On iOS I dont have the issues on Android I do. I assume iOS doesn't let you style these things as much as Android does. That's why these are only in the android folder and that's completely okay for me. But I'm not really sure what your problem with my suggestions is. The file `colors.xml` in Android folder is public. It can be found and edited and changes the colors. Its just not obvious enough that there is second place where colors can be changed. All I suggest is to add a link in form of a comment to let developers know, that there are Android specific colors and where they can find them.

If you say that:

a) Developers shouldn't change the colors. Then why is the file public and editable?
b) It only applies to Android. That's a fact I agree with, but not an argument against my suggestion. I haven't said anything about iOS or that these colors would apply to all platforms.
c) If you said none of that then I misunderstood your post. Could you please tell me what's the problem then?
