### ISSUE TITLE
Method of a custom view gets callled before the constructor when an implicit style is used

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#9050]
### Description

If an implicit style of a control is added to a maui application the methods of the control are called before the constructor is executed.

### Steps to Reproduce

Let's add a control with a dependency property

```
public class Class1 : View
    {
        private string _field;

        public int MyProperty
        {
            get { return (int)GetValue(MyPropertyProperty); }
            set { SetValue(MyPropertyProperty, value); }
        }

        public static readonly BindableProperty MyPropertyProperty =
            BindableProperty.Create("MyProperty", typeof(int), typeof(Class1), propertyChanged: (s, o, n) => (s as Class1).OnMyPropertyChanged());


        public Class1()
        {
            _field = "";
        }

        private void OnMyPropertyChanged()
        {
            var length = _field.Length;
        }
    }

```
and add an implicit style

```
<Style TargetType="lib:Class1">
    <Setter Property="MyProperty" Value="5"/>
</Style>

```

When running the application, it shows the method of the control is executed before the constructor is executed. _field is null despite the constructor initializes it.

![image](https://user-images.githubusercontent.com/17496741/181598942-eadd3e40-10b2-4364-930b-afc1ef83c672.png)

Below is the repro sample

[MauiApp1.zip](https://github.com/dotnet/maui/files/9212911/MauiApp1.zip)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

The problem is reproduced in Windows, I didn't try in other platforms

**Comment by StephaneDelcroix** [comment]
Implicit styles are applied as part of the call to the base constructor, so they're executed before setting the `_field` to `""`. 

Note that `MyProperty` is correctly set.

You should handle those cases in your property handler, or better, avoid edge effects on property handler.

Oh, and if your real case is as simple as your repro, instead of assigning the default value for the field in the constructor, define it along with the field, and THAT will be assigned before calling the base constructor.

```
 private string _field = "";


        public Class1()
        {
        }
```

**Comment by arivoir** [comment]
Don't you think there is a bug if the methods of an object are called before the constructor? Implicit styles work fine for WPF
