### ISSUE TITLE
[Android] Canvas shadow didn't get applied for the drawn ellipse

### ISSUE THREAD

**Issue by PraveenGopalsamy** [dotnet/maui#9059]
### Description

Hi, I'm trying to add a shadow for the drawn ellipse but it didn't get shown on the **Android API 27** platform. I have tested this same case on the Android API 30 or Windows platform, it gets worked.

XAML

```
<ContentPage.Content>
       <Grid HeightRequest="100"
              WidthRequest="300">
            <local:SampleView />
        </Grid>
 </ContentPage.Content>
```

C#

```
public class SampleView : GraphicsView
{
    public SampleView()
    {
        Drawable = new EllipseDrawable();
    }

    protected override Size MeasureOverride(double widthConstraint, double heightConstraint)
    {
        return new Size(widthConstraint, heightConstraint);
    }
}

public class EllipseDrawable : IDrawable
{
    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        Rect ellipseBounds = new Rect(dirtyRect.Center, new Size(30));
        canvas.FillColor = Colors.Blue;
        canvas.SetShadow(new SizeF(0f, 10f), 10f, Colors.Red);
        canvas.DrawString("Welcome to MAUI !!!", 10, 50, HorizontalAlignment.Left);
        canvas.FillEllipse(ellipseBounds);
    }
}
```

### Steps to Reproduce

1. Create a new Maui App.
2. Create a new class, which extends the class from GraphicsView.
3. Create a new class that implements IDrawable, and assign this Drawable to GraphicsView.
4. Now set `canvas.SetShadow()` and also draw a `canvas.FillEllipse()` and `canvas.DrawEllipse()` using the canvas.
5. The shadow didn't get applied for the Ellipse.

Screenshots:

**Android API 27**:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/83585210/179500701-c27574a9-ab68-4a1a-965d-a7c2dc66c9dd.png">

**Windows**:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/83585210/179500143-809402f1-c8e9-4c47-b63a-301fcc056b6b.png">

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

**Android API 27**

**Comment by mattleibow** [comment]
This is now fixed in .NET 7 and .NET 8

<img width="238" alt="image" src="https://github.com/dotnet/maui/assets/1096616/876d8bb6-db5b-401b-8536-ad4ecc8e2ceb">
