### ISSUE TITLE
ImageButton IsLoading Property Is Not Set

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#9073]
### Description

Both the Image and ImageButton classes have an IsLoading property. On ImageButton, the value of IsLoading is never set. Image.IsLoading works as expected.

### Steps to Reproduce

Create a new Maui app, and on MainPage add an ImageButtonControl:

    <ImageButton x:Name="Button"/>

In the code behind, add this line to the page constructor:

    Button.PropertyChanged += (s,e)=> Debug.WriteLine($"Property: {e.PropertyName}");

Run. Note that IsLoading is not printed. Change the ImageButton to an Image and run again. Note the IsLoading property is set.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

iOS 15.5, Mac Catalyst 15.5, Android API 29 Win10-19041

### Did you find any workaround?

Use an Image with a tap gesture recognizer until this is fixed.

**Comment by rmarinho** [comment]
Fixed by #9917
