### ISSUE TITLE
Shell.FlyoutContent does not update with hot reload (most likely an SDK issue)

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9080]
### Description 

I tested this on WinUI and iOS

If you add `Shell.FlyoutContent` to replace the `FlyoutItems` the `Flyout` doesn't update.

**Comment by spadapet** [comment]
Try to repro again

**Comment by spadapet** [comment]
**REPRO:**

1. In Visual Studio, create new MAUI app from blank template
2. Replace contents in AppShell.xaml with:

```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Name="shell"
    x:Class="MauiApp6.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp6"
    Shell.FlyoutBehavior="Locked"
    Title="MauiApp6">

    <!--<Shell.FlyoutContent>
        <CollectionView BindingContext="{x:Reference shell}" IsGrouped="True" ItemsSource="{Binding FlyoutItems}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding Title}" TextColor="Red" FontSize="18" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Shell.FlyoutContent>-->

    <FlyoutItem Title='Home Flyout 1'>
        <ShellContent Title="Home 1" ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage1" />
    </FlyoutItem>
    <FlyoutItem Title='Home Flyout 2'>
        <ShellContent Title="Home 2" ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage2" />
    </FlyoutItem>
</Shell>
```

3. F5 to build and run on Windows (WinUI)
4. Ensure XAML hot reload is enabled
5. Open AppShell.xaml and uncomment the Shell.FlyoutContent

**RESULT:**
The look of the flyouts doesn't change:

![image](https://github.com/dotnet/maui/assets/2523431/f8e5bfd7-c8bf-42e2-b3d5-2a3c4fc86cfd)

**EXPECT:**
The flyouts should have a new look, like:

![image](https://github.com/dotnet/maui/assets/2523431/e8a883eb-350a-4fae-848e-482d682e860e)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on Windows platform.
![Screenshot 2023-09-04 141511](https://github.com/dotnet/maui/assets/77434865/0bb0026b-b7e0-4f83-9e6e-4feb7c5728fa)

**Comment by spadapet** [comment]
Note for the fix:
![image](https://github.com/dotnet/maui/assets/2523431/9d882916-afa3-4c41-a672-9ca967a7ff5c)

**Comment by spadapet** [comment]
Note to self: Remember to log a new bug that removing the initial value of Shell.FlyoutContent will not render the default flyout labels, only on Windows.
