### ISSUE TITLE
Label don't break (middletruncation) and overlap on the next grid's column

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#9084]
### Description

In a Grid with 2 columns, with a label and a button on each column.  
The text on the label is very very long and should truncate if there is not enough space.  

But the label never breaks and overlaps on the next grid's column instead !  
The exact same code was working on Xamarin Forms. Platform: iOS.

### Steps to Reproduce

```xaml
<Grid ColumnDefinitions="*,20">
    <Label Grid.Column="0" 
Text="13ghJdSDfSdsehreDFGfdgfgDHTDfgdfhdrgDFGDFGDRGGdfhdrftydfgdfGDFGDFGDFgdfydfgdfGDFGDFGDFgdrgrgdFGDFGDGFdfgdDFGDFGdfgdfgdf" 
MaxLines="1" LineBreakMode="MiddleTruncation" HorizontalOptions="Start" VerticalOptions="Center" 
           Margin="5,0,10,0" />
    
    <Ellipse Grid.Column="1" WidthRequest="15" HeightRequest="15" Fill="Red" VerticalOptions="Center" />

</Grid>
```

Maui version: 6.0.424
Last version that worked well: Xamarin Forms

![image](https://user-images.githubusercontent.com/190756/181878251-71ce215c-26bf-44d7-aa03-03bd84d5ce0b.png)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

no

**Comment by dapug** [comment]
When is the planned fix?

I'm finding this working on Android but not on Windows. It loads with a single line even if MaxLines is 2 or 3+. BUT... if I remove LineBreakMode from VS IDE and replace it, hot-reload actually does then render it properly. It just wont succeed on initial page load.  Clearly this is a timing/lifecycle issue on the Label control.

**Comment by hartez** [comment]
Works on Android, and with the latest on the main branch it works on Windows (Windows doesn't actually support MiddleTruncation, so it falls back to EndTruncation instead): 
![image](https://user-images.githubusercontent.com/538025/197887372-e2792892-3a00-47f0-a55b-d0f293cd411e.png)

Still broken on iOS.

**Comment by hartez** [comment]
This is on the backlog; we don't currently have a timeline for when it will be fixed.

**Comment by hartez** [comment]
This doesn't actually require a Grid to reproduce; the same Label on a Page by itself fails to truncate.

**Comment by Divyesh-Bhatt** [comment]
This is still not working.

**Comment by trungthong** [comment]
Hi everybody,
I had the same issue about my project's text label overflow issue,
My context is as follows:
when in xamarin i have custom label and set it maxline=3 and LineBreakMode="TailTruncation",HorizontalOptions="StartAndExpand" then when text is long it will display full 3 lines, if text exceeds it will show 3 lines and 3 dots.
but when I switch to Maui it doesn't work. Right now I don't know why.
I have a problem that if I build the same version of visual studio but on 2 different macs, the result is as follows:
+ build with mac osx chip ARM64 (supports m1, m2): then it will return to the line normally, and the text is too long, it will display 3 dots (as expected)
+ build with mac book pro intel chip: the text is only 1 line, and 3 dots appear. it is not as expected
@note: this case works on ipad, iphone doesn't. and i wrap this customlabel with grid
Looking forward to everyone's attention and help. Thanks a lot.
