### ISSUE TITLE
Support SkiaSharp

### ISSUE THREAD

**Issue by MohammdaSalah** [dotnet/maui#9097]
### Description

Hi, when MAUI will support SkiaSharp it's important for image processing

### Public API Changes

No api

### Intended Use-Case

Image processing

**Comment by drasticactions** [comment]
All of [Maui.Graphics](https://github.com/dotnet/maui/tree/main/src/Graphics) _is_ SkiaSharp. It's already included in the box.

**Comment by jfversluis** [comment]
Indeed support is already there so not sure what the ask is here. Hope this was a pleasant surprise and you can start implementing the awesome Skia things in your app!
