### ISSUE TITLE
Frame missing its bottom edge

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#9099]
### Description

The Frame object on Windows is sometimes missing its bottom edge. This is a minor issue for me.

### Steps to Reproduce

1. Unzip the project from
[Simple-frame.zip](https://github.com/dotnet/maui/files/9229960/Simple-frame.zip)
2. Build and run it on Windows, you should see the following, Note the bottom of the rectangle is missing:
![simple-frame-windows](https://user-images.githubusercontent.com/12423046/182050893-768c32d5-0fcf-4bd3-a8cd-f5d69cf60dc0.jpg)
3. Build and run it on Android to see how it should look
![simple-frame-android](https://user-images.githubusercontent.com/12423046/182050955-d85a1eca-67c6-48dc-982a-23f5717f3096.jpg)

 

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Use Border instead, for example:
        <Border  Stroke="Black" StrokeShape="Rectangle"/>

**Comment by janseris** [comment]
Try set magrin to the bottom element

**Comment by david-maw** [comment]
No apparent difference, except the bottom element moves down, in fact the whole page content can be replaced with just:
`<Frame BorderColor="Black" HeightRequest="50"/>`
And the same thing can be seen. Offhand it looks like an off by 1 problem drawing the frame in a constrained height, but that's just a guess.

**Comment by softlion** [comment]
Frame is deprecated. Use [Border](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/border) instead

**Comment by david-maw** [comment]
Thanks for the hint, Frame doesn't appear to be formally deprecated in MAUI, though Border is preferred for new code and is (as the documentation says) considerably more flexible, to say nothing of the fact it doesn't exhibit the same bug, I'll add it as a workaround.

**Comment by Redth** [comment]
This one still repros in 7.0.59 here... 

Looking at our source, we aren't including the extra border width in our override of measuring on the handler...  

Working on a PR.
