### ISSUE TITLE
Label:[WinUI] FontFamily is not recognized in Unpackaged application.

### ISSUE THREAD

**Issue by anjPetrov** [dotnet/maui#9104]
### Description

Label FontFamily is not recognized when App is published as type Unpackaged.
I have set up a .NET MAUI project with only a label inside of it using "Font Awesome" and declaring an icon.
Label works as expected in Debug and Release. However when the app is published as Unpackaged the FontFamily is no longer recognized. I have tried different Font families but none seem to work.

Sample app:
[DemoApp.zip](https://github.com/dotnet/maui/files/9233211/DemoApp.zip)

App look in Release:
![AppRelease](https://user-images.githubusercontent.com/93717775/182133603-7c67ad28-cdc8-4bbe-8f40-ff6a2c0b410b.png)

App look in Unpackaged application:
![AppPublish](https://user-images.githubusercontent.com/93717775/182134473-09033409-d2f5-481a-89dc-05908242f1a1.png)

 

### Steps to Reproduce

1.Open the Sample project.
2. Use the following command: dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None  -p:SelfContained=true -p:WindowsAppSDKSelfContained=true
3. Run the App from the exe file

Expected: User sees the icon of the label.
Actual: User sees an empty rectangle

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

> VS bug [#1778184](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1778184)

### Depends on
- [ ] https://github.com/microsoft/Win2D/issues/891
- [ ] https://github.com/microsoft/microsoft-ui-xaml/issues/8304
- [ ] https://dev.azure.com/microsoft/OS/_workitems/edit/43890883
- [x] https://github.com/microsoft/microsoft-ui-xaml/issues/6325

**Comment by mattleibow** [comment]
Seems to work in WinUI, so I will have to check a bit more...

[WinUI-Test-App.zip](https://github.com/dotnet/maui/files/9840576/WinUI-Test-App.zip)

**Comment by mattleibow** [comment]
Seems to be related to Win2D:

```
System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet._ICanvasFontSetFactory.Create(Uri uri)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet.<>c__DisplayClass11_0.<.ctor>b__0()
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet..ctor(Uri uri)
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile) in C:\Projects\maui\src\Core\src\Fonts\FontManager.Windows.cs:line 152
```

**Comment by mattleibow** [comment]
I managed to isolate the issue and it is a result of Win2D throwing an exception: https://github.com/microsoft/Win2D/issues/891

**Comment by danies8** [comment]
@mattleibow this bug still exists in window platform on last version.

**Comment by mattleibow** [comment]
@danies8 are those using your custom MAUI fonts or is that default controls? Was this packaged or unpackaged.

Unless you are using custom fonts from the maui app yourself, I think the issue lies in WinUI and can be resolved here:https://github.com/microsoft/microsoft-ui-xaml/issues/7866

Have you checked to see if all the system fonts are available on windows server? Like Segoe and Segoe UI?

**Comment by danies8** [comment]
1. I'm using this fonts  in maui app:
`  .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                })`
2. unpackaged installation on window 10 and server 2019
3. How do i check  if all the system fonts are available on windows server? Like Segoe and Segoe UI?

**Comment by mattleibow** [comment]
@danies8 those glyphs I do not think are part of your cusotm fonts as they are OS fonts.

For server, I am not super familiar, but can you just see the Fonts in the Control Panel?

**Comment by Redth** [comment]
Tracking in: https://dev.azure.com/microsoft/OS/_workitems/edit/43890883

**Comment by Scottj1s** [comment]
See also: https://github.com/microsoft/microsoft-ui-xaml/issues/8304
Which in turn mentions the APIs unsupported in unpackaged apps: https://github.com/microsoft/microsoft-ui-xaml/issues/6325

**Comment by mattleibow** [comment]
Reopening as we have fixed the issue in maui, but we need the win2d to be updated and released first.

**Comment by ss1969** [comment]
> This is a workaround for apps that are experiencing this:
> 
> ```cs
> #if WINDOWS
> Microsoft.Maui.Handlers.LabelHandler.Mapper.AppendToMapping("FontFamily", (handler, element) =>
> {
>     if (element.Font.Family == "FontAwesome")
>     {
>         const string FontAwesomeFamily = "ms-appx:///Fontawesome6brands.otf#Font Awesome 6 Brands";
>         handler.PlatformView.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily(FontAwesomeFamily);
>     }
> });
> #endif
> ```
> 
> I am looking into why this is happening as the code is the same and should produce the same result packaged/unpackaged...

 Don't know how to apply this workaround. Can you please paste a full MauiProgram.cs ?

**Comment by SeccoMaracuja** [comment]
> > This is a workaround for apps that are experiencing this:
> > ```cs
> > #if WINDOWS
> > Microsoft.Maui.Handlers.LabelHandler.Mapper.AppendToMapping("FontFamily", (handler, element) =>
> > {
> >     if (element.Font.Family == "FontAwesome")
> >     {
> >         const string FontAwesomeFamily = "ms-appx:///Fontawesome6brands.otf#Font Awesome 6 Brands";
> >         handler.PlatformView.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily(FontAwesomeFamily);
> >     }
> > });
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am looking into why this is happening as the code is the same and should produce the same result packaged/unpackaged...
> 
> Don't know how to apply this workaround. Can you please paste a full MauiProgram.cs ?

I am interested in that too

**Comment by SeccoMaracuja** [comment]
> This is a workaround for apps that are experiencing this:
> 
> ```cs
> #if WINDOWS
> Microsoft.Maui.Handlers.LabelHandler.Mapper.AppendToMapping("FontFamily", (handler, element) =>
> {
>     if (element.Font.Family == "FontAwesome")
>     {
>         const string FontAwesomeFamily = "ms-appx:///Fontawesome6brands.otf#Font Awesome 6 Brands";
>         handler.PlatformView.FontFamily = new Microsoft.UI.Xaml.Media.FontFamily(FontAwesomeFamily);
>     }
> });
> #endif
> ```
> 
> I am looking into why this is happening as the code is the same and should produce the same result packaged/unpackaged...

Please post a full MauiProgram.cs
