### ISSUE TITLE
SetFlowDirection/LayoutFlowDirectionAlwaysMapToLeftToRight tests are currently failing on WinUI

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9111]
### Description

The [SetFlowDirection](https://github.com/dotnet/maui/blob/6b59eb395ab2328fc2dd876f6fdeafd6ce955171/src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.Tests.cs#L47-L56) test is specifically verifying that on Windows the RTL value doesn't propagate to the platform control, but it's currently failing because the value is getting set to RTL.

Similarly the `LayoutFlowDirectionAlwaysMapToLeftToRight` is also failing.

These tests are both currently commented out.

This seems like a regression

**Comment by hartez** [comment]
Delete that #if WINDOWS section in the SetFlowDirection test and delete the LayoutFlowDirectionAlwaysMapToLeftToRight test entirely - those no longer reflect reality.
