### ISSUE TITLE
Windows Layout InputTransparencyInitializesCorrectly(true) test currently failing

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9112]
### Description

The following test is currently failing for
- LayoutStub
- inputTransparent: true

<img width="477" alt="image" src="https://user-images.githubusercontent.com/5375137/182200289-6916104f-c9ac-468f-af03-782b5b6c89e0.png">

You'll need to uncomment the test so it will run. I've commented it out so we have a baseline of passing tests for WinUI Core

**Comment by hartez** [comment]
@PureWeen That test is out of date and can be removed. `InputTransparent` doesn't actually affect hit test visibility for LayoutPanel - the panel itself needs to always be hit test visible so it can relay input to non-transparent children.
