### ISSUE TITLE
Missing PointerOver VisualState for Button on Windows

### ISSUE THREAD

**Issue by stevepeeters** [dotnet/maui#9119]
### Description

I want to change the style of a button when the pointer is moving over it. The same feature exists in WPF as PointerOver VisualState.

### Public API Changes

`<Button>
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="Normal">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor" Value="Lime" />
                </VisualState.Setters>
            </VisualState>

            <VisualState x:Name="Focused">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor" Value="Yellow" />
                </VisualState.Setters>
            </VisualState>

            <VisualState x:Name="PointerOver">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor" Value="Red" />
                </VisualState.Setters>
            </VisualState>

            <VisualState x:Name="Disabled">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor" Value="Pink" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</Button>`

### Intended Use-Case

In my application I want to give the user an indication when the pointer is moving over a button by styling that button with a different background.

**Comment by hartez** [comment]
This was implemented in #9592 - PointerOver is now available as a VisualState in Windows and Mac Catalyst.
