### ISSUE TITLE
Failed processing manifest in migrated maui app 

### ISSUE THREAD

**Issue by LaurenWholey** [dotnet/maui#9120]
### Description

Although I have migrated this app from Xamarin to Maui, the error I'm getting is from the Xamarin.Android.Aapt2.Targets. It is saying that it failed to process the manifest. I'm not sure why the Xamarin.Android.Aapt2.Targets is popping up as I no longer have any reference to Xamarin in my project. 
Here's the error: 
<img width="656" alt="Failed to process manifest" src="https://user-images.githubusercontent.com/103149052/182235498-71944bee-4f8f-4b94-b361-92d42a467691.PNG">

### Steps to Reproduce

This repo is not public. The affected file is the Xamarin.Android.Aapt2.Targets which I found a copy of on git hub. Any ideas would be greatly appreciated given the lack of reproduction. 

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Target Sdk Version: 31

### Did you find any workaround?

No work around

**Comment by jfversluis** [comment]
While I understand the repo you're working on is not public, I hope you also understand that with the current information this issue is near impossible to diagnose. At the very least we will need some relevant log output with more details. Let us know if you're able to provide us with any more details in order to be able to help you.

**Comment by softlion** [comment]
You need at least to publish you manifest xml file. In Maui, its content is minimal.

**Comment by ChristieRR** [comment]
@LaurenWholey Did you manage to figure out what was causing this issue? I'm in the same boat, and i'm not sure what the go is. My repo works/builds fine from my Desktop PC, however when working on my laptop and trying to launch the app onto my phone i'm hitting the same error.
