### ISSUE TITLE
Add empty .NET MAUI Blazor template

### ISSUE THREAD

**Issue by danroth27** [dotnet/maui#9126]
We added empty Blazor Server and Blazor WebAssembly templates. We should probably do the same for .NET MAUI Blazor.

**Comment by jfversluis** [comment]
@davidortinau is this something we actually want to do? If so, when and how?

**Comment by danroth27** [comment]
The .NET MAUI Blazor template has the default content form the other Blazor web templates, so there's a bit more to delete than with the plain .NET MAUI template. The default content is useful for folks trying out the technology for the first time, but once we get broader adoption (🤞) we expect to get feedback that the default content is annoying to have to remove each time.

**Comment by mkArtakMSFT** [comment]
@danroth27 we should also take a wider look at what templates *should* we have for Blazor Hybrid (@Eilon  brought this up).

**Comment by Eilon** [comment]
Fixed in #23615
