### ISSUE TITLE
SignalR Hub not receiving event even after successful connection in MAUI app

### ISSUE THREAD

**Issue by shaliniandroid** [dotnet/maui#9127]
### Description

SignalR Hub is able to receive events when it is a console app but same code is being using in maui app, no events received.

### Steps to Reproduce

[code.docx](https://github.com/dotnet/maui/files/9239401/code.docx)
Attached is the code 

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

ios15, ANDROID 11

**Comment by shaliniandroid** [comment]
Refer to this sample application https://github.com/shaliniandroid/MAUI-Signalr

**Comment by jfversluis** [comment]
If I would have to guess your code gets stuck on this line: https://github.com/shaliniandroid/MAUI-Signalr/blob/master/MauiApp1/SignalRHelper.cs#L37

I highly doubt this is a bug in .NET MAUI, see a working samples here: https://github.com/jfversluis/MauiSignalRSample and here: https://github.com/bijington/orbit/tree/main/games
