### ISSUE TITLE
Grid add Clicked event

### ISSUE THREAD

**Issue by tchtang** [dotnet/maui#9128]
### Description

understand programming is not easy

`Button` is improve but still not what I want

have a picture original size is 225 x 225

![image](https://user-images.githubusercontent.com/109950893/182305618-5161327a-ee3c-4c0a-8232-6f39b83312f3.png)

3rd picture is what I want, picture display fit to size and have text, click either picture or text will trigger click event
as `HorizontalStackLayout` and `VerticalStackLayout` is create to improve performance

isnt okay add `Clicked` event to control `Grid`?

### Public API Changes

```
                    <HorizontalStackLayout Spacing="10">
                        <VerticalStackLayout>
                            <Button HeightRequest="100" ImageSource="test.jpg" WidthRequest="100" Text="test" ContentLayout="Top, 20" />
                        </VerticalStackLayout>
                        <VerticalStackLayout>
                            <ImageButton Aspect="AspectFill" HeightRequest="100" Source="test.jpg" WidthRequest="100" />
                        </VerticalStackLayout>
                        <VerticalStackLayout>
                            <Image Aspect="AspectFill" HeightRequest="100" Source="test.jpg" WidthRequest="100" />
                            <Label HorizontalTextAlignment="Center" Margin="0,5" Text="test" />
                        </VerticalStackLayout>
                    </HorizontalStackLayout>
```

### Intended Use-Case

`Button` picture not display fit

**Comment by tchtang** [comment]
maybe is bug, run in windows is

![image](https://user-images.githubusercontent.com/109950893/182308078-090bb886-7662-4a2d-95a5-7ac90c95945b.png)


run in android API 30 is

![image](https://user-images.githubusercontent.com/109950893/182308314-ac95f4ff-a0ba-4442-8c6b-8efb853414c7.png)

XAML is

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Test.MainPage">
    <Grid>
        <HorizontalStackLayout Spacing="10">
            <VerticalStackLayout>
                <Button HeightRequest="100" ImageSource="meal_all.jpg" WidthRequest="100" Text="test" ContentLayout="Top, 20" />
            </VerticalStackLayout>
            <VerticalStackLayout>
                <ImageButton Aspect="AspectFill" HeightRequest="100" Source="meal_all.jpg" WidthRequest="100" />
            </VerticalStackLayout>
            <VerticalStackLayout>
                <Image Aspect="AspectFill" HeightRequest="100" Source="meal_all.jpg" WidthRequest="100" />
                <Label HorizontalTextAlignment="Center" Margin="0,5" Text="test" />
            </VerticalStackLayout>
        </HorizontalStackLayout>
    </Grid>
</ContentPage>
```

**Comment by jfversluis** [comment]
If you need a tap event on a Grid (or any other element) please look into the `TapGestureRecognizer`.

Also, please try to report 1 thing at a time and choose the right template. These are marked as a feature request, while it seems you are trying to report a bug. Thanks!
