### ISSUE TITLE
Pair to Mac fail with Error: Could not find ‘.NET Core SDK ‘ with version = 6.0.400-preview.22301.10

### ISSUE THREAD

**Issue by g-mars** [dotnet/maui#9132]
### Description

Windows VS 2022-17.3.0-Preview-2.0, connect to Mac OS 12.4.

When connecting , VS passed SSH to initialize dotnet SDK ,  I received the message ' --install -dir /User/myMac?Library/Caches/Xamarin/XMA/SDKs/dotnet --version 6.0.400-preview.22301.10 --no-path'

then 'Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/sdk/6.0.400-preview.22301.10/dotnet-sdk-6.0.400-preview.22301.10/dotnet-sdk-6.0.400-preview.22301.10-osx-x64.tar.gz'

curl:(22) The requested URL returned error:404

at last log: dotnet_intall;  error: Could not find ‘.NET Core SDK ‘ with version = 6.0.400-preview.22301.10

### Steps to Reproduce

Use 'Pair to Mac' window after upgrading to 6.0.400

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

macOS 12.4

**Comment by anupam99** [comment]
i had the same issue on a new 'clean slate' Mac. 

installing dotnet sdk + maui workload on Mac resolved it.  

refer https://dotnet.microsoft.com/en-us/download?initial-os=macos  (for m2 processor, use arm64).
Then in a terminal : 
sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json
( Refer documentation: https://github.com/dotnet/maui/wiki/macOS-Install )

Pairing worked for me after this step.
