### ISSUE TITLE
The target platform identifier android/ios/maccatalyst was not recognized

### ISSUE THREAD

**Issue by Loch9** [dotnet/maui#9134]
### Description

I recently installed VS 2022 17.3 preview 5.0. When creating and running a MAUI project it failed with these errors:
![image](https://user-images.githubusercontent.com/70388529/182370326-c24d7dd2-3df5-4b89-ab59-7ecb0e1329e0.png)

I am running Windows 11 Version 21H2 (OS Build 22000.795) and .NET version 6.0.400-preview.22330.6. .NET 7 is not installed.

### Steps to Reproduce

1. Install .NET MAUI with these settings:
![image](https://user-images.githubusercontent.com/70388529/182370718-8892b5c7-d988-4f49-824a-9a4f9e4c73fc.png)
2. Create a new project with a  .NET MAUI app template.
3. Select run on windows machine
4. Receive the errors.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by jfversluis** [comment]
What do `dotnet --version` and `dotnet --list-sdks` and `dotnet workload list` tell you?

**Comment by Loch9** [comment]
`dotnet --version`:
`6.0.400-preview.22330.6`

`dotnet --list-sdks`:
`5.0.302 [C:\Program Files\dotnet\sdk]`
`6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]`
`6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]`

`dotnet workload list`:

`Installed Workload Ids      Manifest Version      Installation Source`
`-----------------------------------------------------------------------`

`Use 'dotnet workload search' to find additional workloads to install.`

**Comment by jfversluis** [comment]
Looks like no workloads got installed. Try to run `dotnet workload install maui` manually from a command-line and see if that works.

**Comment by Loch9** [comment]
`dotnet workload install`:
![image](https://user-images.githubusercontent.com/70388529/182389822-8946cd0b-3fab-461f-9c30-3f9162c3962d.png)

**Comment by Loch9** [comment]
VS feedback link:
https://developercommunity.visualstudio.com/t/NET-MAUI-installation-bug:-The-target-p/10110752
