### ISSUE TITLE
Grid Size (Width & Height) is not filled if it is invisible

### ISSUE THREAD

**Issue by Tardigrade42** [dotnet/maui#9151]
### Description

If a Grid is not visible (IsVisible="flase"), the Width and Height is -1. In Xamarin the value was filled properly. I tested it as well with the StackLayout -> so I guess it might be a general issue with all Layouts.

I tested this on Android and Windows (since I don't have a Tizen- or iOS-device) and I got the same result. So I guess it is not os-specific.

### Steps to Reproduce

I used the following code in the MainPage of the std-template for an MAUI-App:

# MainPage.xaml:
```C#
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Test_App.MainPage">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>

        <Grid Grid.Row="0">

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>

            <Grid Grid.Column="0"
                  x:Name="visibleGrid"
                  BackgroundColor="Red"/>


            <Grid Grid.Column="0"
                  x:Name="invisibleGrid"
                  BackgroundColor="Yellow"
                  IsVisible="false"/>


        </Grid>

        <Label Grid.Row="1" x:Name="visibleGridSize"/>
        <Label Grid.Row="2" x:Name="invisibleGridSize"/>
        <Button Grid.Row="3" Text="Refresh" HeightRequest="70" Clicked="RefreshNumbers"/>
    </Grid>

</ContentPage>
```

# Mainpage.xaml.cs:
```C#
namespace Test_App;

public partial class MainPage : ContentPage {
	public MainPage() {
		InitializeComponent();

        visibleGridSize.Text = "Placeholder\nPlaceholder";
        invisibleGridSize.Text = "Placeholder\nPlaceholder";
	}

    public void RefreshNumbers(object sender, EventArgs args) {
        visibleGridSize.Text = "The size of the visible Grid is:\nWidth:" + visibleGrid.Width + " Height: " + visibleGrid.Height;
        invisibleGridSize.Text = "The size of the invisible Grid is:\nWidth:" + invisibleGrid.Width + " Height: " + invisibleGrid.Height;
    }
}
```

# The output is the following:
![2022-08-02 18_24_35-Window](https://user-images.githubusercontent.com/37712964/182425010-75e13806-ae42-4e1c-ae7a-3484b81f767f.png)
(The red side is the visible Grid, the black-right-side is the invisible Grid)

# Note
For testing it with the StackLayout, I changed the "visibleGrid" and "invisibleGrid" to StackLayout.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

I guess all?

### Did you find any workaround?

Not yet, I needed to use the Width and Hight of a visible Element.

**Comment by hartez** [comment]
Here's the same code running in a Xamarin.Forms app:

![Screenshot 2022-08-02 155913](https://user-images.githubusercontent.com/538025/182480901-f94214ab-f661-461f-afa9-241c9d120fe3.png)

The behavior hasn't changed from Forms - an invisible layout doesn't get a Width or Height set.

**Comment by Tardigrade42** [comment]
Ok, now I am confused. I tried to migrate the following code from Xamarin to Maui:

# MainPage.xaml
```C#
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:common="clr-namespace:Test_App;assembly=Test_App"
             x:Class="Test_App.MainPage">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>

        <Grid Grid.Row="0">

            <common:ExternalGrid
                IsVisible="false"
                x:Name="exGrid"/>


        </Grid>
        
        <Button Grid.Row="1" Text="Refresh" HeightRequest="70" Clicked="RefreshNumbers"/>
    </Grid>

</ContentPage>
```

# MainPage.xaml.cs
```C#
namespace Test_App;

public partial class MainPage : ContentPage {
	public MainPage() {
		InitializeComponent();
	}

    public void RefreshNumbers(object sender, EventArgs args) {
        exGrid.IsVisible = true;
        exGrid.Resize();
    }
}
```

# ExternalGrid.xaml
```C#
<?xml version="1.0" encoding="utf-8" ?>
<Grid xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
      xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
      x:Class="Test_App.ExternalGrid"
      BackgroundColor="Red"
      x:Name="grid">
</Grid>
```

# ExternalGrid.xaml.cs
```C#
namespace Test_App {
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class ExternalGrid : Grid {
        public ExternalGrid() {
            InitializeComponent();
        }

        public void Resize() {
            double flyoutWidth = (Width / Height) <= 4 / 3 ? Width / 1.2 : Width / 3;

            grid.WidthRequest = flyoutWidth;
            grid.Margin = new Thickness(0, 0, Width - flyoutWidth, 0);
        }
    }
}
```

I thought it might be because of the Width and Height, but I found out, that you are right. Do you have any idea, why this code is working in Xamarin, but if I press the button in MAUI, the app crashes?

**Comment by hartez** [comment]
It's happening because of a change (for performance reasons) between how Forms and MAUI handle measurement/layout after a visibility change. Basically, after you set `IsVisible = true`, the Width and Height won't be updated until the platform itself (Windows, Android, etc.) does another measure/layout pass. 

There are a couple of options - you could react to the actual size change of the ExternalGrid, or you could handle this in the measurement of the ExternalGrid. 

The first option looks something like this:

```
public class ExternalGrid : Grid
{
    public ExternalGrid()    {
        grid.SizeChanged += ExternalGrid_SizeChanged;
    }

    private void ExternalGrid_SizeChanged(object sender, EventArgs e)    {
        Resize();
    }

    public void Resize()   {
        if (grid.WidthRequest > -1)  {
            return;
        }

        double flyoutWidth = (Width / Height) <= 4 / 3 ? Width / 1.2 : Width / 3;
        grid.WidthRequest = flyoutWidth;
        grid.Margin = new Thickness(0, 0, Width - flyoutWidth, 0);
    }
}
```

Alternatively, you could handle it during measurement, something like this:

```
public class ExternalGrid : Grid
{
    public ExternalGrid()  {
    }

    protected override Size MeasureOverride(double widthConstraint, double heightConstraint)   {
        double flyoutWidth = (widthConstraint / heightConstraint) <= 4 / 3 ? widthConstraint / 1.2 : widthConstraint / 3;

        WidthRequest = flyoutWidth;
        Margin = new Thickness(0, 0, widthConstraint - flyoutWidth, 0);

        return base.MeasureOverride(widthConstraint, heightConstraint);
    }
}
```

**Comment by Tardigrade42** [comment]
Thanks for the answer :)
It stops my app from crashing, but I have still multiple problems with the new behaviour. I have multiple components (Buttons, Picker, Layouts etc.), which have to scale if something appears or disappears. With your solution, multiple of them don't size correctly until I change the Window-Size of the Windows-App during runtime. Is there a way to trigger this: `the Width and Height won't be updated until the platform itself (Windows, Android, etc.) does another measure/layout pass` or is there any other way to get the old behaviour?

**Comment by Tardigrade42** [comment]
I found a "Workaround". I handed down a default-value. Its more code, but it worked at the end.

Thanks for finding the issue in my code :)
