### ISSUE TITLE
[Spec]  Provide Nullable Safe getters on ViewHandler base class

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#916]
# <Get>WithValidation

Checking for nullability and then firing an exception can get repetitive. Adding APIs that perform the null check and then throw an exception is helpful for reducing clutter

I've added a couple of these already

https://github.com/dotnet/maui/blob/6b0158aa7421d88f02ca884aa6aff1f4a34cdebf/src/Core/src/Handlers/View/ViewHandlerOfT.cs#L139

VirtualViewWithValidation
ContextWithValidation
NativeViewWithValidation

This issue is to discuss the API name.

**Comment by hartez** [comment]
For Context, just check in the accessor:

```
public Context Context
{ 
	get 
	{
		var context = MauiContext?.Context ?? throw new InvalidOperationException($"Context cannot be null");
		return context;
	} 
} 
```

There's nowhere we need Context where a `null` Context is useful or valid.

**Comment by hartez** [comment]
I'm honestly not sure we need any of these; in Mappers, the VirtualView _shouldn't_ be `null`, that's already been dealt with by that point. 

If we really do need them, we could create an internal nullable version of the value. Anything which legitimately needs the validation can call a public accessor which does the null check. Anything which needs to deal with the nullable version (basically just the create/connect/disconnect plumbing) can use the internal one. And that code already has to do null checks.

So `public IView? VirtualView {get;}` becomes something like 

```
internal IView? VirtualViewInternal {get; set;}
public IView VirtualView {get { if(VirtualViewInternal == null){throw;} return VirtualViewInternal;  }}
```

**Comment by PureWeen** [comment]
@hartez we can go that route but we'd probably need to do it via explicit interfaces

Currently the IViewHandler is

```C#
public interface IViewHandler
	{
		IView? VirtualView { get; }
		IMauiContext? MauiContext { get; }
		object? NativeView { get; }
	}
```

Because none of these are set in the constructor so we'd have to change these implementations to all be explicit interfaces and then do the public ones how you describe

Which we could definitely do
I'm doing something similar to that on the NavigationPageHandler.Android.cs stuff as well
