### ISSUE TITLE
Button not showing when under a CollectionView in StackLayout on iOS

### ISSUE THREAD

**Issue by zuzannaczaja** [dotnet/maui#9164]
### Description

I have problem with Button under CollectionView. When I have Button under CollectionView, button isn't visible.

For example:
```xml
    <StackLayout Orientation="Vertical">
        <CollectionView ItemsSource="{Binding ViewModel}"></CollectionView>
        <Button Text="ButtonName"></Button>
    </StackLayout>
```

When I have CollectionView under Button, button is visible.

For example:

```
    <StackLayout Orientation="Vertical">
        <Button Text="ButtonName"></Button>
        <CollectionView ItemsSource="{Binding ViewModel}"></CollectionView>
    </StackLayout>
```

On Windows and Android platform I don't have this problem.

### Steps to Reproduce

1. Create project.
2. Paste first example to page or view.
3. Run project on iOS platform.
4. Replace the first example with a second example.
5. Run project on iOS platform.

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by BlagoCuljak** [comment]
Like @jfversluis said, we find the button pushed way down. Set entire stacklayout inside scrollview and then scroll down to empty space, and there is your button.

We are having major issues with this.

**Comment by zuzannaczaja** [comment]
> Like @jfversluis said, we find the button pushed way down. Set entire stacklayout inside scrollview and then scroll down to empty space, and there is your button.
> 
> We are having major issues with this.

My version is 6.0.400-preview.22330.6

**Comment by EdwardMcFlurry** [comment]
Instead of opening a new issue, has this issue being fixed especially on iOS.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on iOS 16.4 with below Project:
[9164.zip](https://github.com/dotnet/maui/files/11562990/9164.zip)

**Comment by PureWeen** [comment]
`StackLayout` will by design give infinite space to anything that wants it.

This means the CV will just take infinite space and layout all the controls. 

If you need to add constraints then use Grid
https://learn.microsoft.com/en-us/dotnet/maui/migration/layouts?view=net-maui-8.0
