### ISSUE TITLE
[Windows] - DisplayPromptAsync buttons order

### ISSUE THREAD

**Issue by AntoineValente** [dotnet/maui#9165]
### Description

Hey,

When I open a prompt using `DisplayPromptAsync`, the "accept" button is the left one and the "cancel" the right one. Is it possible to inverse the position of those buttons ?

![prompt](https://user-images.githubusercontent.com/25256341/182622138-09f765eb-840c-4d77-b795-469c419ed18f.png)

### Steps to Reproduce

1. Call `string response = await DisplayPromptAsync("Hello", "How are you ?", "Send", "Close");`
2. You will get the response if you click on the left button. If you click on the right button, `response` is null

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by jfversluis** [comment]
This is as intended. If you're going to cancel the value is unlikely to be used. Therefore, unfortunately, it's not possible to reverse the order of the buttons at this time. If this is something you would like to see changed, please open a feature request with all the details on how you would see this working according to you. Thanks!
