### ISSUE TITLE
Error boundary message does not display on mobile devices

### ISSUE THREAD

**Issue by ltemimi** [dotnet/maui#9175]
### Description

I have a MAUI Blazor project that uses the Error Boundary component .
The error message displays correctly in Blazor server but not on mobile devices

![image](https://user-images.githubusercontent.com/5493492/182674586-e9228f94-db39-4857-9db4-a764d6e73296.png)

### Steps to Reproduce

1 Creat new dotnet Maui Bl;azor app
2 - Place an error boundary around the body tag

 ```<article class="content px-4">
            <ErrorBoundary @ref="_errorBoundary">
                <ChildContent>
                   @Body
                </ChildContent>
                <ErrorContent Context="exception">
                    <ErrorBoundaryMessage
                        ErrorBoundary="@_errorBoundary"
                        Exception="exception">
                    </ErrorBoundaryMessage>
                </ErrorContent>
            </ErrorBoundary>
        </article>
```
3 - Simulate an error and observe it renders correctly on Blazor server but not on IOS or Androind

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Windows server 2022

### Did you find any workaround?

No

### Relevant log output

```shell
just nothing is displayed on ios and android
```

**Comment by MackinnonBuck** [comment]
Hi @ltemimi, would you please provide a public, minimal repro project hosted as a GitHub repository that demonstrates the problem? Thanks!

**Comment by MackinnonBuck** [comment]
Another thing you could try is checking if the default error boundary works correctly.

**Comment by danroth27** [comment]
The default `ErrorBoundary` seems to work fine in a .NET MAUI Blazor app:

![image](https://user-images.githubusercontent.com/1874516/182908029-bb039f26-d61d-4e78-ae97-2155060a7975.png)

**Comment by ltemimi** [comment]
Hi 
Many thanks for your help 
1 - I am attaching the code to show the issue , the code has three projects a BlazorBase (bootstrapper) that is referenced by a Blazor Server project and a Dot net Maui blazor project. It can be used to show that that the error boundary works on blazor server but not in mobile devices.

To get the code bigger than 25 mb please use the link: https://1drv.ms/u/s!Ai1jsiYR5baCmpReUmQua3v6AztSpw?e=o1ZnJR


<img width="794" alt="Code" src="https://user-images.githubusercontent.com/5493492/183444831-04b62594-1293-45fb-a911-453b871f14a5.png">
<img width="396" alt="Android" src="https://user-images.githubusercontent.com/5493492/183444855-bd6914bd-e58c-485c-8f76-fc512e27ae05.png">
<img width="372" alt="IOS" src="https://user-images.githubusercontent.com/5493492/183444903-44883c11-b953-4bd8-9887-cf0de11799de.png">
<img width="373" alt="BlazorServer" src="https://user-images.githubusercontent.com/5493492/183444941-5896459d-e8b7-4e5e-bc28-f660d4236191.png">

**Comment by ltemimi** [comment]
Are we saying I  am stuck with the issue? Any suggestion wor around?

**Comment by danroth27** [comment]
Hi @ltemimi. The reason your ErrorBoundaryMessage is failing when running in .NET MAUI is because it has a dependency on the IHostingEnvironment service, which is only available when running in the context of an ASP.NET Core app. You can see this is the issue by checking dev tools console for the browser control (you can bring up the dev tools when running on Windows by hitting F12):

![image](https://user-images.githubusercontent.com/1874516/184038751-eeee98cf-6086-47fa-8aba-c7d2a5022142.png)

You'll need to refactor your ErrorBoundaryMessage component to not depend on this interface.
