### ISSUE TITLE
RegionInfo.CurrentRegion.ISOCurrencySymbol returns XDR on iOS device

### ISSUE THREAD

**Issue by softlion** [dotnet/maui#9182]
### Description

On an iOS device set to french FR/fr, RegionInfo.CurrentRegion.ISOCurrencySymbol returns XDR instead of EUR.  
This happens only on the device, not on the simulator.

Also, when using standard resource strings on a device with FR language set, the culture stays in EN as if FR was not detected.

Device: iPhone XR, iOS 15.5

![image](https://user-images.githubusercontent.com/190756/182781197-8533d8f3-a42f-410a-a3de-2bb3128b5bd5.png)

```
dotnet --version
6.0.400-preview.22330.6
VS 2022 Mac Preview 17.3.0.2089
with Xamarin.iOS 15.12.0.2
```

### Steps to Reproduce

* Set the iPhone langage/region to FR (france)
* Start the maiu app in debug mode
* Observe the value of RegionInfo.CurrentRegion.ISOCurrencySymbol

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5 device

### Did you find any workaround?

no

**Comment by Eilon** [comment]
This issue was moved to xamarin/xamarin-macios#15633
