### ISSUE TITLE
Error building maui library that invokes platform code via partial class (preview 6)

### ISSUE THREAD

**Issue by matthewclendening** [dotnet/maui#9193]
### Description

I've created a maui library based on the example at https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code. Using the partial class approach is failing for me with an error:

error CS8795: Partial method 'DeviceOrientationService.GetOrientation()' must have an implementation part because it has accessibility modifiers.

### Steps to Reproduce

Dotnet version 6.0.400-preview.22330.6
See the example project at https://github.com/matthewclendening/MauiPartialBug

Attempt to build the maui library.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

n/a

**Comment by mattleibow** [comment]
I believe the issue is that the C# code is invalid. There cannot be a public partial method. https://github.com/matthewclendening/MauiPartialBug/blob/main/MauiLib/Platforms/iOS/DeviceOrientationService.cs#L7

The correct implementation is to either implement them all on all the platforms - or just on iOS and that will automatically make it partial.

**Comment by matthewclendening** [comment]
Then is the documentation at https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code wrong? Looking at the c# spec, it seems to say this is allowed:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

**Comment by matthewclendening** [comment]
MAUI is using C# 10 I believe, so this should work. C# 9 extended partial methods to allow a bunch of features:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/extending-partial-methods

**Comment by mattleibow** [comment]
According to the docs you linked, the partial method annoy have modifiers:

> It doesn't have any accessibility modifiers (including the default private).

**Comment by matthewclendening** [comment]
Thanks Matthew - I discovered the root cause was linked to the
<TargetFrameworks> definition. I was not realizing that the partial class
needs to be implemented for each TargetFramework specified in the csproj
file. Once I did that, the project was able to build successfully.

**Comment by mattleibow** [comment]
Ah, great!
