### ISSUE TITLE
EvaluateJavaScriptAsync does not work if WebViewRenderer is used

### ISSUE THREAD

**Issue by yaho86** [dotnet/maui#9211]
### Description

`WebView.EvaluateJavaScriptAsync` does nothing if WebViewRenderer is used. It works fine with default handler, though.

Probably caused by this condition https://github.com/dotnet/maui/blob/d94a1ad7d8d8d8e2b2bf1a46009955f20762a638/src/Controls/src/Core/WebView.cs#L117

### Steps to Reproduce

1. Enable compatibility mode and register `WebViewRenderer`
````
var builder = MauiApp.CreateBuilder();
builder
  .UseMauiApp<App>()
  .UseMauiCompatibility()
  .ConfigureMauiHandlers((handlers) => {
#if ANDROID
    handlers.AddCompatibilityRenderer(typeof(WebView), typeof(WebViewRenderer));
#endif
  });
````
2. Add WebView like so `<WebView Source="..." />`
3. Call `WebView.EvaluateJavaScriptAsync("alert('Hello')")` (or any other JS code) 
4. JS code is not executed

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

Use handler instead of renderer.

**Comment by NiladriPadhy** [comment]
When using handlers instead of renderers, EvaluateJavaScriptAsync method not found since its implemented from IView interface. Need implementation for EvaluateJavaScriptAsync method.

**Comment by NiladriPadhy** [comment]
Any update on this ?

**Comment by Shishim4ru** [comment]
> When using handlers instead of renderers, EvaluateJavaScriptAsync method not found since its implemented from IView interface. Need implementation for EvaluateJavaScriptAsync method.

Here you can find an implementation of the handler based on IWebView instead of IView [https://github.com/Shishim4ru/MAUIWebViewExample](url)

**Comment by yaho86** [comment]
> ![issue-9211](https://user-images.githubusercontent.com/6755973/196645270-3aa20314-f9ab-40ac-97ee-f8306974171e.png) Could you try with the latest version (net7 rc2)?. Tried but cannot reproduce the issue.

It still doesn't work with the latest version of .NET 7.0. 
The code from .NET MAUI Samples calls `MauiWebView.Eval("alert('text')");` and it works. But on the next line it calls `MauiWebView.EvaluateJavaScriptAsync()` that doesn't work, see https://github.com/dotnet/maui/blob/d94a1ad7d8d8d8e2b2bf1a46009955f20762a638/src/Controls/samples/Controls.Sample/Pages/Controls/WebViewPage.xaml.cs#L75
