### ISSUE TITLE
MAUI tutorial application won't build for Android emulator

### ISSUE THREAD

**Issue by JargerBiirli** [dotnet/maui#9217]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows 10

I've follower the instructions in the tutorial up to this point, but the project fails to build for Android emulator. The emulated system is ”Pixel 5 - API 31 (Android 12.0 - API 31). The error given is ”file not found: C:\Users\[MyUser]\AppData\Local\Temp\[filename].tmp”, ”File = JAVAC”. The filename of the temp file changes every time, but is of the form tmpXXXX.tmp, where XXXX is a four-character code, maybe two hex values? Not sure if related, but MyUser contains spaces and non-ASCII characters that are misinterpreted in the output suggesting an encoding problem somewhere, perhaps this is relevant?

The project builds without problem for Windows.

I'm using 
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 5.0
.NET Framework 4.8.04084

**Comment by ThatJammyDodger** [comment]
I've never had any problem like this when building for Android. Maybe this is an issue with your specific installation of VS or .NET? Perhaps try reinstalling them and that might be able to help.

**Comment by anupam99** [comment]
Menu > Tools > Options
Do you have your android JDK location set?  
![image](https://user-images.githubusercontent.com/5384775/183304980-4b301b84-1345-452b-b322-6488f8ff5732.png)

from your error it seems javac ( java compiler is missing). You need to add its path to path environment .
you can also check on your command prompt by typing javac ... it should invoke java compiler.
![image](https://user-images.githubusercontent.com/5384775/183305094-9168fcb0-3d80-44f4-a6ad-333104f65684.png)

**Comment by JargerBiirli** [comment]
Thank you for your suggestions!

I checked these things, but they seem to be in order. I had an AdoptOpenJDK build of Java Development Kit, and tried changing it to the newest Microsoft one, but it did not solve the issue. JAVAC also runs from the command line. I suppose JAVAC itself is fine, but it cannot for some reason access the tmp file it should, or the previous step in the process is not creating it.
