### ISSUE TITLE
Is Maui UseMauiCompatibility() with handlers.AddCompatibilityRenderer extension buggy?

### ISSUE THREAD

**Issue by dg2k** [dotnet/maui#9229]
### Description

I am trying to migrate Xamarin code to .NET MAUI and I followed @davidortinau Wiki on Custom Renderers as described [here](https://github.com/dotnet/maui/wiki/Using-Custom-Renderers-in-.NET-MAUI).

Enabling the custom renderer with UseMauiCompatibility() in MauiProgram.cs throws an `InvalidCastException` on Android.

### Steps to Reproduce

1. Create a new Maui project
2. In Android MainActivity.cs, ensure to include the `protected override void OnCreate(Bundle savedInstanceState)` method with `base.OnCreate(savedInstanceState);` inside it.
3. Create a simple Custom Renderer. I used ShellRenderer with the Shell control with minimal code as shown below.
4. Activate Custom Renderer in MauiProgram.cs. I followed @davidortinau's Wiki as described [here](https://github.com/dotnet/maui/wiki/Using-Custom-Renderers-in-.NET-MAUI).
5. Run Maui for Android platform. It fails on `base.OnCreate(savedInstanceState);` following the initialization of the Custom Renderer, for the code shown below, after executing the constructor for `ShellCustomRenderer`.

```csharp
 public class ShellCustomRenderer : ShellRenderer
 {
     public ShellCustomRenderer(Context context) : base(context)
     {
     }
     protected override IShellToolbarAppearanceTracker CreateToolbarAppearanceTracker()
     {
         return new CustomToolbarTracker();   // CustomToolbarTracker class not shown here for brevity
     }
 }
```

As a workaround, if I replace the extension `handlers.AddCompatibilityRenderer` with `handlers.AddHandler` upon enabling the Custom Renderer, everything works as expected. 

The issue appears to narrow down to `handlers.AddCompatibilityRenderer` versus `handlers.AddHandler`. Thanks to LeonLu-MSFT (oops! the handle doesn't provide a link - LeonLu-MSFT is based at MICROSOFT Q&A).

You'll also find more details on this issue as Q&A [here](https://docs.microsoft.com/en-us/answers/questions/956778/why-does-mainactivity-baseoncreate-fail-for-androi.html).

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and Android 12

### Did you find any workaround?

Yes. 
If I replace the extension `handlers.AddCompatibilityRenderer` with `handlers.AddHandler` upon enabling the Custom Renderer in MauiProgram.cs, it works as expected.

**Comment by PureWeen** [comment]
@dg2k the documentation is a little confusing and based on old initiatives. 

All of the shell renderers were migrated to work off of `IViewHandler` so they are all compatible with `AddHandler` now and don't require `AddCompatibilityRenderer`
