### ISSUE TITLE
CollectionView Containing SwipeView Within a Grid Throws Access Violation on Windows

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#9233]
### Description

I needed a CollectionView where the items were of this form:
```
<Grid>
    <SwipeView>
        ...
    </SwipeView>
</Grid>
```

It worked fine on Android but threw an Access Violation

### Steps to Reproduce

1. Unzip the project from [MAUIListEntry-SwipeView.zip](https://github.com/dotnet/maui/files/9275385/MAUIListEntry-SwipeView.zip)
2. Build and run it under Android, you should see this:
![MAUIListEntry-SwipeView-android](https://user-images.githubusercontent.com/12423046/183256915-9af009ef-6c39-46c7-a19c-7badd4eb67b3.jpg)
3. Build and run it under Windows, it fails with an Access Violation

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by dg2k** [comment]
I think `SwipeView` should be the outer nest not inside `Grid`, hence:

```
<DataTemplate>
    <SwipeView>
        <Grid>
            <Label Text="{Binding}" />
        </Grid>
    </SwipeView>
</DataTemplate>
```

I checked and it works. Raises a question why Android behaved differently.

**Comment by david-maw** [comment]
Thanks @dg2k, that does indeed work (as I'm sure do many other layouts), but I only want a portion of my DataTemplate to be "swipeable" and want to overlay two different grid column specifications, hence this layout. This is just a simplified example derived from a much more complex original, most of which was irrelevant to the problem. IMHO Android behaved differently because it worked correctly.

**Comment by davepruitt** [comment]
I get this same exact crash (an access violation) when I have the SwipView inside of a Frame:
```
<CollectionView ItemsSource="{Binding Path=TestCollection}" Margin="20">
    <CollectionView.ItemsLayout>
        <LinearItemsLayout Orientation="Vertical" ItemSpacing="10" />
    </CollectionView.ItemsLayout>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Frame HasShadow="False" Padding="0">
                <SwipeView>
                    <SwipeView.RightItems>
                        <SwipeItems Mode="Reveal">
                            <SwipeItem BackgroundColor="Red" Text="Delete" />
                        </SwipeItems>
                    </SwipeView.RightItems>
                    <StackLayout BackgroundColor="White" Orientation="Vertical" Margin="10">
                        <Label Text="{Binding .}" FontAttributes="Bold" FontSize="20" />
                    </StackLayout>
                </SwipeView>
            </Frame>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by hugebug4ever** [comment]
Still crash with dotnet dotnet 8 preview 7,  with memory access violation.

**Comment by david-maw** [comment]
Looks like this is fixed in .NET 8 RC 2 in that this sample no longer faults. That just let me get to the next problem, see issue #18530
