### ISSUE TITLE
AddAppAction icons don't work with MauiImages in the Resources/Images folder on Android

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#9234]
### Description

When declaring AppActions, it appears I can't use images defined in Maui workflows (and have to declare android resources instead). on iOS I can use Maui images. 

### Steps to Reproduce

1. Create a File -> new Maui App
2. Add App Actions in the MauiProgram.cs

```cs
           .ConfigureEssentials(essentials =>
            {
                //TODO: it's unclear whether icons must be in the Resources/Images folder or in the Platforms/{platform} folder
                essentials
                    .AddAppAction("calendar", "Calendar", "IFPA Tournament Calendar", "calendar.png")
                    .AddAppAction("my-stats", "My Stats", "Your IFPA player data", "mystats.png")
                    .AddAppAction("rankings/player-search", "Player Search", "Search for other players in the IFPA database", "search.png")
                    .OnAppAction(App.HandleAppActions);
            })
```

3. Add images to the project with the same names defined in step 2, but from svg files. (so, in the above example, add calendar.svg)
4. On Android, a long press to bring up actions from the home screen or app list screen will not show the icons. This works in iOS.
![image](https://user-images.githubusercontent.com/3627193/183257445-fa3242b8-da9e-4509-ab49-b669b0acd21b.png)

It appears the only way to get AppAction images to work is the images must be declared as Android native resources. This means you need to maintain separate asset / asset references per platform as opposed to using unified maui images.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All Android

### Did you find any workaround?

No

**Comment by edgiardina** [comment]
Reproduction repository:
https://github.com/edgiardina/IfpaMaui

**Comment by edgiardina** [comment]
I installed the latest visual studio Preview (17.5.0 Preview 1.0) and my MAUI project targets 7.0 but I'm not seeing the fix. My project can be found at this repo (.net 7 changes branch)
https://github.com/edgiardina/IfpaMaui/tree/net7-changes

**Comment by edgiardina** [comment]
@mattleibow Is there a trick to this? On android using Visual Studio 17.5.1 Preview and projects targeting .net 7 (and dotnet sdk 7.0.100), I still don't see my svgs appear as icons in my project.

**Comment by mattleibow** [comment]
@edgiardina can you try without an extension?

I am looking at the code and I am not sure it works with extensions... And I am adding this to the backlog as I think we need to properly handle these things. I believe all the platforms add the extensions if it is needed. Android never uses extensions, iOS is optional, and Windows always uses PNG.

This is more of an inconsistency than a bug, but if it was not intuitive, then it is a bug nevertheless.

**Comment by mattleibow** [comment]
For future me...

We can fix this by always removing the extension. For Windows which requires an extension, the only transparent format is a .png so we might as well just use that.

Technically all the platforms are different and may support .jpg, but that is nasty. Also, Android supports passing the actual bitmap pixels, but that is not so great. So going for a .png-only way is probably best. And to be consistent we just remove the extension the developer provided.

We could even throw an exception if the image is not in the correct format... Not sure if just ignoring the extension is very helpful.

**Comment by edgiardina** [comment]
My thoughts are, we should follow the same convention we use the XAML. In the XAML we use .png assuming the svgs are converted to pngs. So everywhere in a MAUI app you know that you want to reference a MauiImage the same way.

**Comment by edgiardina** [comment]
@mattleibow I confirmed the icons are present in Android when the .svg / .png file extension is removed. I don't have a Mac at this time but previously the Mac worked with .png extensions. Do I have to branch on device here until a broader strategy is in place? 

FYI thank you for the attention this is getting. I know its a small piece of the puzzle.

**Comment by moljac** [comment]
Confirming Android behavior and adding iOS analysis

```csharp
.ConfigureEssentials
    (
        essentials =>
        {
            essentials
                .AddAppAction
                    (
                        "notes",
                        "Notes",
                        "Notes",
                        "si_ballot.png"	// will not be rendered
                    )
                .AddAppAction
                    (
                        "chat",
                        "Chat",
                        "Chat",
                        "si_chat"		// rendered
                    )
                .OnAppAction(App.HandleAppActions);
        }
    );
```

On Android icons with extension will NOT be rendered:

<img width="539" alt="Screenshot 2023-03-27 at 16 16 17" src="https://user-images.githubusercontent.com/1768576/228222795-82df0065-a949-4fc7-8501-053f6a6cb744.png">

On iOS icons with extension will be rendered:

<img width="457" alt="Screenshot 2023-03-27 at 16 07 32" src="https://user-images.githubusercontent.com/1768576/228222890-56432815-fc4d-413b-ae46-03143a3faf95.png">

**Comment by moljac** [comment]
Forgotten repro sample:

[AppMAUI.Issue9234.AppActionIcons.zip](https://github.com/dotnet/maui/files/11097568/AppMAUI.Issue9234.AppActionIcons.zip)
