### ISSUE TITLE
Content page databinding bug

### ISSUE THREAD

**Issue by candinho1987** [dotnet/maui#9243]
Hi, i just got a bug, when i add:
```
<ContentPage.BindingContext>
        <local:UsuariosViewModel x:Name="ViewUsers"/>
    </ContentPage.BindingContext>
```
And i get the error:
![erro maui android](https://user-images.githubusercontent.com/66473642/183272128-3aca81e8-fb44-4bf9-869a-fe63bd94a26b.jpg)
and on windows machine it work:
![work on windows ](https://user-images.githubusercontent.com/66473642/183272139-36bb3e9b-3877-4d86-9ae6-53b5d20699b7.jpg)

Steps to reproduce:
create a maui project, add <PackageReference Include="CommunityToolkit.Maui" Version="1.2.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0-preview4" />, contentpage.datacontext.

**Comment by candinho1987** [comment]
> Hi @candinho1987. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

https://github.com/candinho1987/MAUI-DataBinding-Bug-Repl

**Comment by candinho87** [comment]
Any news on this? Really needs attention as we can't use data bindings on Android
