### ISSUE TITLE
Date format DatePicker wrong in Windows

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#9255]
### Description

I set the date format to yyyy-MM-dd.
In Android the date shows as 2022-08-09.
In Windows the date shows as 2022-8-9.

Using Visual Studio Community 2022 - 17.3.0 Preview 6.0

### Steps to Reproduce

1. Open the attached project in Android.
2. Open the attached project in Windows.
3.
[MauiAppTestDateFormat.zip](https://github.com/dotnet/maui/files/9280413/MauiAppTestDateFormat.zip)

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by dg2k** [comment]
@Redth - just to alert that the link for **Triage Process** by *msftbot* above is broken.

**Comment by jfversluis** [comment]
Thanks @dg2k! Fixed it for this comment and fixing the bot now!
