### ISSUE TITLE
No RelativeLayout in MAUI

### ISSUE THREAD

**Issue by sattasundar** [dotnet/maui#9256]
### Description

Not able to find RelativeLayout in MAUI current version.

### Steps to Reproduce

 Can anyone confirm? RelativeLayout is coming in upcoming release or it removed in MAUI.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

11

### Did you find any workaround?

Nope.

**Comment by GalaxiaGuy** [comment]
https://github.com/dotnet/maui/issues/2147

**Comment by sattasundar** [comment]
> #2147

Thanks a lot.
