### ISSUE TITLE
.SVG files not showing up on IOS 

### ISSUE THREAD

**Issue by Vpatel541** [dotnet/maui#9265]
### Description

The svg files show up when running the Android Simulator, but does not show up on the IOS simulator

### Steps to Reproduce

1. Create new .NET MAUI project
2. Add SVG file to image
3. Run on Macbook and run IOS simulator
4. Image should not show, when running on PC with android, image should show up

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15

### Did you find any workaround?

none

**Comment by Symbai** [comment]
SVG files are working fine here. I think you should add a repro project, its probably an issue on your end.

**Comment by Vpatel541** [comment]
I am using a MacBook and running on Iphone IOS 15.5. I started a new project and I see this is still an issue.

**Comment by NonameMissingNo** [comment]
Use ".png" as extension, not ".svg" while leaving things the same

**Comment by xiz0r** [comment]
I am using SVG and they are working fine in my project.  
The reference in Source I am making it without extension,
example:
```
/Resources/Images/icon_settings.svg
```
```
<Image Source="icon_settings" />
```

**Comment by Symbai** [comment]
> I see this is still an issue.

You are the only one. Nobody is able to reproduce, especially with your instructions. So either upload a repro project so we can tell you what you're doing wrong or you probably won't get any help soon.

**Comment by PureWeen** [comment]
This is most likely a duplicate that's similar to 
https://github.com/dotnet/maui/issues/3459

If what @NonameMissingNo indicated still doesn't work please attach a repro
