### ISSUE TITLE
<option> list not updating their position upon window position change, but does so on window refocus

### ISSUE THREAD

**Issue by DrNoLife** [dotnet/maui#9268]
### Description

The issue I'm facing is that I have a <select> which has some options. Whenever the window changes position, the dropdown list for the options, does not update. This means, after changing the Window position and using the <select>, the dropdown list appears somewhere it should not.

The issue is not a problem when just using Blazor WASM, it is however a problem when using a MAUI Blazor App.

I have tried calling StateHasChanged(), but it didn't do anything. I tried using the <InputSelect> component from Blazor, also not doing anything.

However, I have noticed, that whenever I click over to another window (can be anything, Visual Studio, Windows Explorer or whatever), and then try to open the dropdown list again, it now works.

[Video showcasing the issue.](https://i.imgur.com/Wka5lPp.mp4)

[Repository containing 2 sample projects.](https://github.com/DrNoLife/maui-bug-report-option-position) 
One Blazor-Maui, and one Blazor-WASM. WASM project works, the other don't.

### Steps to Reproduce

1. Create a new project -> .NET Maui Blazor App
2. Edit the index.razor component, and add the folowing code:
```cshtml
<label>Select issue showcase.</label>
<select>
    <option disabled hidden selected>Select something.</option>
    @foreach(int i in Enumerable.Range(0, 10)) 
    {
        <option>@i</option>
    }
</select>
```
3. Start the program, and move the window away from the default starting position.
4. Click the &lt;select&gt;, and observe the dropdown being somewhere it should not be.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

By letting another window take focus, and the going back to the Maui application, the issue is fixed.

Until we move the Maui program around again, then the issue is back.

**Comment by Eilon** [comment]
Hi, that issue is a bug in WebView2 and is being tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290

Please post additional thoughts and comments on that issue so that the appropriate team can review. Thanks!

**Comment by Eilon** [comment]
Hi, for anyone running into this issue, we think we found a _workaround_, which should help you with your existing apps. Please read this comment for how to work around this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290#issuecomment-1254273563
