### ISSUE TITLE
FlexLayout no longer works on iOS/Android

### ISSUE THREAD

**Issue by agendamatic** [dotnet/maui#9274]
### Description

FlexLayout does not seem to be working in the current preview on iOS, MacCatalyst and Android. It is working on Windows.

### Steps to Reproduce

Add a new page to a .NET MAUI app. Add a FlexLayout with a few labels: 

    <FlexLayout Background="Red">
        <Label Text="One"/>
        <Label Text="Two"/>
        <Label Text="Three"/>
    </FlexLayout>

Run. Note that no content is rendered.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iOS 15.5, Mac Catalyst 15.?, Android API 29

### Did you find any workaround?

No

**Comment by cmcaquilala** [comment]
I experienced the same bug. Setting the HeightRequest of the FlexLayout to 50 does show the content though, so maybe manually setting it could be a workaround?

**Comment by hartez** [comment]
Just tested this on Android, and it's now working on that platform.

**Comment by hartez** [comment]
Also working on iOS/Mac.
