### ISSUE TITLE
Grid rows within CollectionView are all blank (only in Release mode)

### ISSUE THREAD

**Issue by ednam1** [dotnet/maui#9275]
### Description

The Grid rows within my CollectionView are all blank (**but only when running the .NET MAUI app in Release mode**, as they are displayed properly when this app is built and run in **Debug** mode).

With the code below, I'm noticing that the grid rows (within the CollectionView) are not displaying the **Label**'s Text, nor the grid row's **BackgroundColor**).

**Release mode:**
![image](https://user-images.githubusercontent.com/44980853/183514343-c5240ab8-3dce-4209-a1de-23d6681bcf58.png)

**Debug mode:**
![image](https://user-images.githubusercontent.com/44980853/183513685-c47e62d0-2d9b-42ff-997b-5c5e4c1cb920.png)

SourceViewListPage.xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiClient.Views.SourceViewListPage"
             xmlns:local="clr-namespace:MauiClient.ViewModels"
             xmlns:models="clr-namespace:MauiClient.Models"
             x:DataType="local:SourceViewModel"
             xmlns:converters="clr-namespace:MauiClient.Converters"
             Title="SourceViewListPage">

    <ContentPage.Resources>
        <converters:HexColorConverter x:Key="HexColorConverter" />
    </ContentPage.Resources>

    <StackLayout>

        <StackLayout VerticalOptions="CenterAndExpand">
            <RefreshView>
                <CollectionView x:Name="SourceViewItemListCollectionView"
                                ItemsSource="{Binding SourceViewListItems}"
                                MaximumWidthRequest="450"
                                FlexLayout.Grow="1"
                                ItemsUpdatingScrollMode="KeepLastItemInView">
                    <CollectionView.ItemsLayout>
                        <LinearItemsLayout Orientation="Vertical"/>
                    </CollectionView.ItemsLayout>

                    <CollectionView.ItemTemplate>
                        <DataTemplate x:DataType="models:SourceViewListItem">
                            <Grid RowDefinitions="*"
                                  BackgroundColor="{Binding BackgroundColor, Converter={StaticResource HexColorConverter}}"
                                  MinimumHeightRequest="40" VerticalOptions="Center">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>
                                <Label Text="{Binding PrimaryText}"
                                       TextColor="{Binding FontColor, Converter={StaticResource HexColorConverter}}"
                                       BackgroundColor="{Binding BackgroundColor, Converter={StaticResource HexColorConverter}}"
                                       FontFamily="Courier New"
                                       FontAttributes="Bold"
                                       MinimumHeightRequest="40"
                                       VerticalOptions="Center"
                                       VerticalTextAlignment="Center"/>
                                <BoxView HeightRequest="1"
                                         BackgroundColor="Black"
                                         VerticalOptions="EndAndExpand"
                                 />
                            </Grid>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </RefreshView>
        </StackLayout>

    </StackLayout>

</ContentPage>
```

SoureViewListItem.cs:
```
namespace MauiClient.Models;

public class SourceViewListItem
{
    public string ID { get; set; }
    public string PrimaryText { get; set; }
    public string FontColor { get; set; }
    public string BackgroundColor { get; set; }
}
```

HexColorConverter.cs:
```
using System.Globalization;

namespace MauiClient.Converters;

internal class HexColorConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return Color.FromArgb(value as string);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```

SourceViewListItems view model:
```

    private ObservableCollection<SourceViewListItem> sourceViewListItems = new();
    public ObservableCollection<SourceViewListItem> SourceViewListItems
    {
        get { return sourceViewListItems; }
        set
        {
            sourceViewListItems = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(SourceViewListItems)));
        }
    }
```

Note that if the **Text** and **BackgroundColor** props are set to FIXED values (not bound to properties), then they are displayed properly (even in Release mode).

Used the following IDE for development:
Visual Studio Professional 2022 (64-bit) - Preview version 17.3.0 Preview 6.0

### Steps to Reproduce

1. Build .NET MAUI app in Release mode
2. Run this app (on Windows 10 20H2 or 21H2)
3. Go to the SourceViewListPage

Expected outcome: Grid rows within the CollectionView should be displayed properly in Release mode (as they are in Debug mode)
Actual outcome: Grid rows within the CollectionView are all blank (only in Release mode)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0, Windows SDK 10.0.20348.0

### Did you find any workaround?

Yes, build and run my app in Debug mode for now.

**Comment by hartez** [comment]
@ednam1 I wonder if the HexColorConverter is getting linked out in the release build. Out of curiosity, if you add `private HexColorConverter converter = new HexColorConverter();` to SourceViewListPage.xaml.cs and build/run in Release mode, does that make any difference?

**Comment by ednam1** [comment]
@hartez Unfortunately that did not make a difference.

**Comment by paleicikas** [comment]
The same problem for me. Could you check one case: remove HeightRequest from Grid, there is bug Grid + HeightRequest

**Comment by ednam1** [comment]
> The same problem for me. Could you check one case: remove HeightRequest from Grid, there is bug Grid + HeightRequest

@paleicikas Just tried this, unfortunately that did not make a difference.

**Comment by ednam1** [comment]
Fixed - this was actually an issue with the data binding (there was another partial definition of the SourceViewListItem class).
