### ISSUE TITLE
Reusable / extendable version of SecureStorage? (and for that matter - other relevant packages as well)

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/maui#9276]
### Description

I would like to reuse the [`SecureStorage`](https://github.com/dotnet/maui/tree/main/src/Essentials/src/SecureStorage) code in an Uno Platform app. The platforms supported by Uno Platform do not entirely overlap with MAUIs platforms, and currently the only way to consume this code and add platforms seems to be copying the code into another repo and building a separate library from it.

Is there a way how code from this repo can be reused and extended with other platforms that are not part of MAUI, without taking a dependency on the full MAUI Essentials Nuget package?

### Public API Changes

I guess the same - just packaged in a different way?

### Intended Use-Case

I would like to use the cross-platform code that is part of MAUI in more places with Uno Platform.

**Comment by mattleibow** [comment]
The MAUI Essentials nuget (or soon will be in net8) is note 100% part of maui, so can be used in any mobile app. Right now it is part of the workload system and I think you can use a `<UseMauiEssentials>true</>` in any csproj and you will get the essentials bits.

But, with net8 we are also going to release  (the current plan) a standalone nuget that is just the shared bits.

I am not sure there is going to ever be a set of sub nugets with each api in a separate package.

**Comment by jfversluis** [comment]
There is a form possible today and I don't see a great amount of people pitching in here to say that they also want this. That makes it very hard to prioritize this. I think for now the conclusion is that we won't be doing this in the near future.

Thank you for your suggestion!

Fijn weekend!
