### ISSUE TITLE
Running various Samples in .NET MAUI source code.

### ISSUE THREAD

**Issue by dg2k** [dotnet/maui#9283]
I have subtle issues with .NET MAUI migration (such as CollectionView control crashing) and thought I should delve in and try to discover in the source code (and contribute in the process).

I cloned the Maui code but hitting problems running some samples as a starter (e.g., Essentials samples). Various dependent projects compile okay but the samples fail to deploy and run.

I have gone through the README.md.

Any tips what I need to do to get the samples going?

**Comment by PureWeen** [comment]
Did you go through the `Development.md` ? 
https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md
