### ISSUE TITLE
Shell with SVG icons

### ISSUE THREAD

**Issue by scottkuhl** [dotnet/maui#9291]
### Description

If you set an SVG icon on a tab in a tab bar you will only see a black screen on iOS and MacOS.  On Windows you will see the tabs but no icons.  

On Android it works.  With PNG images instead of SVG images it works on all platforms.

### Steps to Reproduce

1. Create a new Maui App.
2. Add an SVG file to the Images folder.  (I used one from the Fluent System Icons project).
3 Update the AppShell.xaml file to use a tab bar. (Example below)
4. Run the application.

```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp1.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp1"
    Shell.FlyoutBehavior="Disabled">

    <TabBar>
        <Tab Title="Home" Icon="ic_fluent_home_24_regular.svg">
            <ShellContent
                Title="Home"
                ContentTemplate="{DataTemplate local:MainPage}"
                Route="MainPage" />
        </Tab>
        <Tab Title="Away" Icon="ic_fluent_home_24_regular.svg">
            <ShellContent
                Title="Away"
                ContentTemplate="{DataTemplate local:MainPage}"
                Route="MainPage" />
        </Tab>
    </TabBar>
</Shell>
```

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows, macOS

### Affected platform versions

iOS 15, MacOS 12.5, Windows 11

### Did you find any workaround?

Use PNGs instead of SVGs.

**Comment by PureWeen** [comment]
```XAML
<TabBar>
        <Tab Title="Home" Icon="ic_fluent_home_24_regular.svg">
            <ShellContent
                Title="Home"
                ContentTemplate="{DataTemplate local:MainPage}"
                Route="MainPage" />
        </Tab>
        <Tab Title="Away" Icon="ic_fluent_home_24_regular.svg">
            <ShellContent
                Title="Away"
                ContentTemplate="{DataTemplate local:MainPage}"
                Route="MainPage" />
        </Tab>
    </TabBar>
```

If you change these to ".png" does it work? 

Closing as duplicate
https://github.com/dotnet/maui/issues/7066

**Comment by scottkuhl** [comment]
> If you change these to ".png" does it work?
> Closing as duplicate
> #7066
> ```

Yes, I marked that as the workaround.  It’s very strange that the entire screen goes black with SVGs.
