### ISSUE TITLE
Colors render as black

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Colors-render-as-black/10112902)._

---
Using 17.3 build 2089, create a new Maui app from the template. Modify MainPage.xaml to add a boxview and give the boxview a color. Run the app - the boxview is always rendered black regardless of the color you assign.

This repro’s on Mac, iOS and Android. NOTE: the same code running on VS for Windows preview works exactly as expected.

---
#### Feedback Bot on 8/7/2022, 11:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RanjithkumarSyncfusion** [comment]
Hi @MauiTeam

Im facing this issue in 6.0.486, BoxView always renders in Black.

**Comment by jsuarezruiz** [comment]
> Hi @mauiteam
> 
> Im facing this issue in 6.0.486, BoxView always renders in Black.

Could you attach a small sample where reproduce the issue?. Thanks.
