### ISSUE TITLE
Reland #7143 ([X] simplify and avoid duplication in conversion)

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#9294]
Had to revert https://github.com/dotnet/maui/pull/7143 due to a crash on all platforms (see https://github.com/dotnet/maui/pull/9266):

Pushed the commit to a new branch: https://github.com/dotnet/maui/tree/dev/reland-7143

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.1. Not repro this issue on windows and android.
