### ISSUE TITLE
Visual Studio 2022 17.4 Preview 1, Maui projects with only 1 Target do not work

### ISSUE THREAD

**Issue by pierrebrito** [dotnet/maui#9303]
### Description

After upgrading to Visual Studio 2022 17.4 Preview 1, Maui projects with only 1 Target do not work.

![image](https://user-images.githubusercontent.com/6466875/183803370-ac3514e9-a717-44cd-b13c-8d7f553d6c54.png)

### Steps to Reproduce

.csproj

	<PropertyGroup>
		<TargetFrameworks>net6.0-android</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>MauiApp13</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		
		<ApplicationTitle>MauiApp13</ApplicationTitle>

		
		<ApplicationId>com.companyname.mauiapp13</ApplicationId>
		<ApplicationIdGuid>3827a0ba-0bbe-4661-ab46-68547eee3c73</ApplicationIdGuid>

		
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>

	</PropertyGroup>

### Version with bug

6.0.486 (current)

**Comment by MagicAndre1981** [comment]
remove the `s`, so only use `TargetFramework`. Does this work?

**Comment by pierrebrito** [comment]
@MagicAndre1981 That was the first thing I tried.
Does not work ;(

**Comment by adegeo** [comment]
Have you tried setting the debug profile to the Android emulator instead of Windows? You can't target Android in the project file but then use Windows as the Visual Studio debug target.
