### ISSUE TITLE
Unable to create android emulator

### ISSUE THREAD

**Issue by ShioDotNetCodeer** [dotnet/maui#9304]
### Description

I'm form China。
I am not sure if it is related to my network environment。
When I create the Android emulator, I get the error: Network is not reachable. Please check your connection and try again。
But my computer's network is able to access the WAN.
This prevents me from publishing the MAUI program to an Android emulated device for testing。

### Steps to Reproduce

1.Find the Create button in Android Device Manager
2.Cilck the Create button
3.Wait after clicking the create button
4.pop-up error message box :Network is not reachable. Please check your connection and try again

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 Android 11

**Comment by JiuLing-zhang** [comment]
新建模拟器的时候需要下载 Android 相关的内容，连不上外网没法下载。找个代理先下载吧，调试的时候就不用了。

**Comment by ShioDotNetCodeer** [comment]
> 
我挂了梯子的，但还是不行

**Comment by JiuLing-zhang** [comment]
> > 
> 
> 我挂了梯子的，但还是不行

是全局的代理吗？我当时安装的时候，MS和Google的网站都要走代理才能完成下载。有些软件MS默认不走代理。
