### ISSUE TITLE
Default value of a Preferences.Get returns a null value in Windows

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#9306]
### Description

Default value of a Preferences.Get returns a NULL value in Windows, works correct in Android.
Not tested on Apple products.

### Steps to Reproduce

1. Open the attached file
2. Run it in Android and you will see the text: Preference OK
3. Run it in Windows and the text will be: Preference NOT OK

[MauiAppTestPreferencesGet.zip](https://github.com/dotnet/maui/files/9299929/MauiAppTestPreferencesGet.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

**Comment by jfversluis** [comment]
Seems a duplicate/related to #9338 can I please ask you to upload the reproduction to a GitHub repository instead of adding it here as a zip file? Thanks!

**Comment by geertgeerits** [comment]
Hi, here is the link to the GitHub repository:
https://github.com/geertgeerits/MauiAppTestPreferencesGet

**Comment by mattleibow** [comment]
Thanks for the repro! I managed to see that it is a duplicate of #9338
