### ISSUE TITLE
'Unable to activate windows store app {id}. The activation request failed with error code "The parameter is incorrect"'

### ISSUE THREAD

**Issue by MindMeltMax** [dotnet/maui#9324]
### Description

Whenever I launch a .NET MAUI application on windows it crashes with the error (See title).

[Error image](https://i.stack.imgur.com/ICK06.jpg)

No code or info was changed, I just try to debug and it throws this and exits

Tested on an admin account with developer mode enabled

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Launch debug mode on windows machine 

Expected outcome : A window opens with the default page
Actual outcome: A dialog window appears with before mentioned error

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 Home OS Build 19044.1889

**Comment by jfversluis** [comment]
So just to be clear; you are running the Windows app through Visual Studio, right? You click the run button and it shows you this?

What version of Visual Studio are you using? And what does `dotnet --version` tell you?

**Comment by MindMeltMax** [comment]
I tried running it from the startmenu, directly from the debug (and release) folder and from vs itself.
Using vs 2022 Community version 17.3.0 on dotnet 6.0.400

**Comment by Jay-o-Way** [comment]
Is there a shortcut to the app in your Start Menu? If so, right-click it and select 🗑 **Delete**.
Have you tried VS **Menu** > **Build** > **Clean Solution** ?

**Comment by atzimler** [comment]
I have the same issue. I'm able to create a solution with a single MAUI project that is capable of running. As soon as I create the project in another solution, or import it into a solution, or even, create a blank project with Visual Studio and rebuild the solution tree and create the new MAUI application into it, the problem pops up.

I've tried to find anything different between the two code environments, but was unable to figure out what is causing the issue. Maybe someone here would have an idea, let me know if I can provide data for investigating the problem.
