### ISSUE TITLE
Brand new install of Visual Studio 2022 17.3 with Maui Workload on MAC M1 fails

### ISSUE THREAD

**Issue by temisroabrea** [dotnet/maui#9328]
I have a 14" M1PRO MAC running Monterrey. 

I created a brand new! Windows 11 ARM VM with parallels, installed only Visual Studio 2022 17.3 (Released version - not the preview), and checked the Maui workload.

[VS installer screentshot](https://i.stack.imgur.com/QUZSj.png)

Everything installed without errors.

I launched VS, and NO Maui templates showed!.

Opened the Command Prompt and run 'dotnet new --install Microsoft.Maui.Templates'

Launched VS again and templates were there. Created a Project and it failed:

Nuget restore errors:

Severity Code Description Project File Line Suppression State Error NETSDK1139 The target platform identifier android was not recognized. MauiApp1 C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets 112 Error NETSDK1139 The target platform identifier ios was not recognized. MauiApp1 C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets 112 Error NETSDK1139 The target platform identifier maccatalyst was not recognized. MauiApp1 C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets 112 Error NU1012 Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst MauiApp1 C:\xx\MauiApp1\MauiApp1.csproj 1
Error NU1012 Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst MauiApp1 C:\xx\MauiApp1.csproj 1
Error NU1012 Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst MauiApp1 C:\xx\MauiApp1.csproj 1

Build errors: 

1>------ Build started: Project: MauiApp1, Configuration: Debug Any CPU ------ 1>C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(112,5): error NETSDK1139: The target platform identifier android was not recognized. 1>Done building project "MauiApp1.csproj" -- FAILED. 1>C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(112,5): error NETSDK1139: The target platform identifier ios was not recognized. 1>Done building project "MauiApp1.csproj" -- FAILED. 1>C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(112,5): error NETSDK1139: The target platform identifier maccatalyst was not recognized. 1>Done building project "MauiApp1.csproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by InquisitorJax** [comment]
@temisroabrea any luck?
