### ISSUE TITLE
Convert all uses of UICommand to UIAction

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9332]
### Description

OnHold until: https://github.com/dotnet/maui/pull/14740/files/49f5f1f0685a17e332d3d67e4f654a605ccdae47#diff-f1798675642557df37437c1b2586c65818edf78c04b02740ff587e2d3486fc0fR50

Currently for Menus on Catalyst we are using `UICommand`'s which requires selectors. This leads to a lot of awkward extra code. It appears that we can just use `UIAction` instead.

**Comment by Eilon** [comment]
One thing I'm not sure of is that with the selector stuff and UICommand, it _might_ be easier to integrate with the default MacOS menus that nearly every app has, like File/Edit/View. I'm not sure if that works with UIAction. Definitely something to consider.

**Comment by PureWeen** [comment]
I did a basic test just plopping in `UIAction` instead of `UICommand` and it seems like it works

AFAICT the only difference between the two is that one uses a closure and the other uses a selector

<img width="471" alt="image" src="https://user-images.githubusercontent.com/5375137/184033995-3b933a8b-3469-4880-b926-236109766cf0.png">

Still haven't found anything indicating the why of doing one vs the other.
The one advantage I could see with `UICommand` is that the actions all execute through the `MauiAppDelegate` menu override so in theory a user could hook into that for every menu item even ones they've added
