### ISSUE TITLE
the default template of Maui Blazor app underline shows broken in my Android device

### ISSUE THREAD

**Issue by ali50m** [dotnet/maui#9334]
### Description

I`m testing the Maui Blazor app from the defual Maui Blazor app template which was bring by the latest VS2022.3.

When run it in my test Android device (Vivo V2080A, aka Vivo S7t, [device info](https://www.gsmchoice.com/zh-tw/catalogue/vivo/s7t/)), it shows a broken underline with the **brief survey** link.

Also test with Android emulator, it works well with emulator.

Let me know if you need more infomation.

![image](https://user-images.githubusercontent.com/9393831/184050878-fe906ba2-f14a-4ebf-93c6-dd83cd84576a.png)

### Steps to Reproduce

File > New .net Maui Blazor App
Build and deploy to my android device.
View the "Hello world" page.

expected: show a underline below the **brief survey** link.
actual: the underline is broken.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by SteveSandersonMS** [comment]
Hi @ali50m. I'm afraid the exact way that your browser renders HTML+CSS is outside the control of Blazor. It might be something to do with the fonts available on that device, but we don't know for sure.

We'd recommend using CSS to control the styling to be how you want it. If that's not possible, it sounds like an issue with the browser on your device. The only way it would be an issue in MAUI/Blazor is if it's possible to style it how you want with plain HTML, but somehow impossible with a Blazor component. Hope that makes sense!
