### ISSUE TITLE
Maui application toolbar missing

### ISSUE THREAD

**Issue by yzqdev** [dotnet/maui#9335]
### Description

After upgrade to visual studio17.3 maui application toolbar disappeared, hot reload also take no effect;
I followed this procedure https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/intro and it didn't show application toolbar as the tutorial shows.
![image](https://user-images.githubusercontent.com/20037151/184061346-451c44d3-9698-4bc9-aeec-6d2507e59ca6.png)

tutorial shows
![tutor](https://dotnet.microsoft.com/static/images/maui/windows-app-hot-reload.png?v=3ywrkwIFwV9CETCQGNY6_q4QQ8XOQQ5bL1SFDxzv1hw)

### Steps to Reproduce

1. Create a   New .NET MAUI App
2. click on the debug button 
![image](https://user-images.githubusercontent.com/20037151/184061779-67295232-d193-4922-99cb-7d20f63c1b1c.png)
3. you can see the maui app with no application toolbar, hot reload takes no effect,and it's hard to debug.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows sdk 10.0.19041.0

### Did you find any workaround?

no

**Comment by jfversluis** [comment]
Hey @yzqdev thanks so much for the report and amazing to see you starting out with .NET MAUI!

The thing you're seeing is something that is not a part of .NET MAUI itself but the tooling around it. Unfortunately, I have no easy way of transitioning this issue to the right place. I will put a label on this which will trigger a bot that gives you all the info you need on where to report this issue in the right place so the right people will be looking at it and they are provided with all the info necessary to diagnose this. Sorry for the extra effort here!

**Comment by adegeo** [comment]
@jfversluis Is this something that should be reported in the Visual Studio "report a problem" menu?
