### ISSUE TITLE
MAUI is the bug

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/maui#9336]
### Description

I don't really care anymore..

All damn YOUTUBE SHIT or media moment..

You broke xamarin..

MAUI TEAM WHAT THE HELL..

Such a long time..
nothing works..
Bullshit ppl and team who just close topic and stuff, it's so good to fix and help but in reality they don't know anything..

i give up.. MAUI is dead.. or more xamarin is dead.
SIlverlight same problem the team.. maui same problem the team.. bill gates doesn't learn anything..

this will be posted in TIKTOK and youtube..

this time the deadline 10 days..

then i will pay 1 million dollaras to make post every place how fuck up this maui team is. so bill gates can see it..

with content from all those involved in it.

### Steps to Reproduce

I don't really care anymore..

All damn YOUTUBE SHIT or media moment..

You broke xamarin..

MAUI TEAM WHAT THE HELL..

Such a long time..
nothing works..
Bullshit ppl and team who just close topic and stuff, it's so good to fix and help but in reality they don't know anything..

i give up.. MAUI is dead.. or more xamarin is dead.
SIlverlight same problem the team.. maui same problem the team.. bill gates doesn't learn anything..

this will be posted in TIKTOK and youtube..

this time the deadline 10 days..

then i will pay 1 million dollaras to make post every place how fuck up this maui team is. so bill gates can see it..

with content from all those involved in it.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All time.

### Did you find any workaround?

Fire the team of maui. reproducere a system that work

**Comment by NonameMissingNo** [comment]
1), Bill Gates doesn't even have much hand in Microsoft anymore.
2), Maui works for 98% of the cases, talking as somebody who is making a for sale application.

**Comment by janseris** [comment]
> 1), Bill Gates doesn't even have much hand in Microsoft anymore. 2), Maui works for 98% of the cases, talking as somebody who is making a for sale application.

More like 70 %. Our developers are very frustrated using MAUI. We have to use a lot of workarounds and it's a tradition here that documented features don't work properly or work properly only on some platforms.

**Comment by NonameMissingNo** [comment]
Yeah, sorry. Meant the 98% with the workarounds.

**Comment by NonameMissingNo** [comment]
> James Montemagno (promoter) and Maddy Montaquilla (manager) are presenting MAUI on YouTube as 100 % working fast dev iterations high performance framework ready for production but that is false.
Aaaaand there's the main issue.

**Comment by ShariatPanah** [comment]
I totally agree, the team isn't big enough to handle such huge amount of issues, we have a lot of issues unanswered and definitely not solved, i dont know what paths they have taken but i assume if they're gonna keep on like this, the .Net Maui will be shut down soon like Xamarin unless they make serious decision to at least hire some more developers to handle the issues

**Comment by jfversluis** [comment]
We're happy to have a productive conversation, but this isn't that as far as I'm concerned.
