### ISSUE TITLE
Fail to build default Maui application

### ISSUE THREAD

**Issue by kris-golden** [dotnet/maui#9337]
P
On Windowsx 10 1889, Just installed Visual Studio 2022.  Keep getting an error when I try to build the default Maui template app:  MSB4018 The "GeneratgeBuildSessionId" task failed unexpectedly.

**Comment by jfversluis** [comment]
Please use the bug report template to submit a potential issue. In order for us to diagnose this properly we will need a lot more information in the form of Visual Studio versions, more log output, etc. Thanks!
