### ISSUE TITLE
Preferences API not working correctly on Windows

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#9338]
### Description

Preferences.Get returns 0 instead of null when key is never set before.
Preferences.Remove returns 0 instead of being deleted.
Picker ItemSource does not show a drop-down list. Nothing is shown.

### Steps to Reproduce

Just create a Preferences.Get("test", "-1") and you will get 0 instead of null.
Just create a Preferences.Set("test", "1"). Then, Preferences.Remove("test"). Do a Preferences.Get("test", "-1") and you will get 0.
Do a picker. Populate it's ItemSource with a list. Nothing shows up when you click on it.

All these issues work well on Android platform.

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Windows SDK

### Did you find any workaround?

NO.

### Relevant log output

```shell
No log output.
```

**Comment by mattleibow** [comment]
I had a dodgy feeling about this one so had a look. Seems this was a regression introduced in #8536

Specifically:

https://github.com/dotnet/maui/pull/8536/files#diff-6ed591e38dc7754551705bf5bb96f992115c384d19166e8dcda76267e177fb0cR36-R37

**Comment by tekmun** [comment]
I reported the issue on Picker Item Source for Windows in the same bug report.
Picker ItemSource does not show a drop-down list. Nothing is shown.

Should I open a new ticket?

**Comment by mattleibow** [comment]
Yes please.

**Comment by holecekp** [comment]
Has this really been fixed? Preferences.Get behaves really weird on Windows. It returns null even if there is a default value provided. I am getting a lot of run-time NRE because of this.

**Comment by mattleibow** [comment]
This has been fixed and will be released in the next servicing release: SR5

**Comment by DiagProf** [comment]
I also need it urgently. Hopefully SR5 is coming soon.
