### ISSUE TITLE
Android Options -> Additional supported encodings - CJK

### ISSUE THREAD

**Issue by kwiksys** [dotnet/maui#9343]
### Description

Having using Xamarin for sometime. The question is concerning the Android Options -> Additional supported encodings. I normally select CJK .

I am wondering how does Dotnet MAUI handle this ?

Appreciate any assistance .

![Xamarin_Android](https://user-images.githubusercontent.com/31030124/184124213-3c806883-1bff-4168-bf66-b6a8416da57c.jpg)

### (Public) API Changes

NA

### Usage Scenarios

I used  the additional encoding for Thermal Printing.

### Backward Compatibility

NA

### Difficulty

High

**Comment by jenscski** [comment]
Not quite sure if this will help, or if CJK is supporte, but how about using https://www.nuget.org/packages/System.Text.Encoding.CodePages/ ?

**Comment by kwiksys** [comment]
> Not quite sure if this will help, or if CJK is supporte, but how about using https://www.nuget.org/packages/System.Text.Encoding.CodePages/ ?

I am wondering why the Additional Support encoding for Android which is available in Xamarin Forms but not in DotNet MAUI.
Can't find any documentation on this. It is difficult for me to upgrade to DotNet MAUI unless there is an alternative.

**Comment by mattleibow** [comment]
One thing you can try in the interim (after filing an issue in the IDE) is make the change in the old IDE and see what MSBuild properties is set. Then, copy that change into your csproj. Unfortunately I do not have the older IDE installed so I can't check quickly.

**Comment by kwiksys** [comment]
> One thing you can try in the interim (after filing an issue in the IDE) is make the change in the old IDE and see what MSBuild properties is set. Then, copy that change into your csproj. Unfortunately I do not have the older IDE installed so I can't check quickly.
Done filing the issue in IDE.
I am using Visual Studio 2022  version17.3.0.   Xamarin Forms -> Android properties -> Android Options . Have this option but can't seem to find this in DotNet MAUI.

![Xamarin_Android](https://user-images.githubusercontent.com/31030124/184267215-eb221e42-98ad-47bb-bc54-98f06926c782.jpg)

**Comment by jenscski** [comment]
I have once used the additional encoding in Xamarin, but since Maui is built on top of .NET 6, the way to go is probably using the https://www.nuget.org/packages/System.Text.Encoding.CodePages/ as I suggested above.

But now I have tested my self. Add the System.Text.Encoding.CodePages to your project, and call `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);` at startup, then you can use `var encoding = System.Text.Encoding.GetEncoding(932);` to retrieve codepage for Japanese (which I think is part of CJK)

**Comment by mattleibow** [comment]
@jonathanpeppers i know you have done some work on Android before 😉 so just checking if there is a correct way and maybe we have docs @davidbritch?

**Comment by davidbritch** [comment]
@mattleibow No docs. My understanding is that the whole migrate from Xamarin.Forms to MAUI story is waiting for .NET 7.

**Comment by jonathanpeppers** [comment]
As mentioned https://github.com/dotnet/maui/issues/9343#issuecomment-1212795248 the System.TextEncoding.CodePages NuGet package is the way to get this support in .NET 6+.

The doc I found is: https://docs.microsoft.com/dotnet/api/system.text.codepagesencodingprovider?view=net-6.0

The old `Additional Supported Encodings` setting is only used in Xamarin projects. But this is probably a good item to put on a future Xamarin migration doc.

I think we can close this? Thanks!
