### ISSUE TITLE
Visual Studio 2022 not available in this system ?

### ISSUE THREAD

**Issue by nsnaveensharma** [dotnet/maui#9344]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: Windows

Hi Sir/Ma'am

I am not able to update my VS 2022 to the latest features and tools. The moment I opened the Visual Studio installer to update. It is showing "You haven't installed anything yet". But I have VS 2022 and VS 2015 installed in my system. The problem just appeared today because last to last week I updated the VS 2022 using the same installer. I am very afraid of the problem. kindly help me to resolve the issue ASAP as some of my projects are stuck in development. 

Thanks

**Comment by adegeo** [comment]
Hi @nsnaveensharma You should use the Visual Studio feedback as it seems to be a problem with that, not .NET MAUI. https://developercommunity.visualstudio.com/search?space=8
