### ISSUE TITLE
Default Right Click context menu on Entry currently crashes for the Maui.Control.Samples project

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9353]
### Description

You can either go to the ContextFlyoutMenu page and right click here

![image](https://user-images.githubusercontent.com/5375137/184160516-9c5adef3-46b2-4987-ad31-6692ace5eaf5.png)

 or just create a page with only the following XAML

```XAML
    <VerticalStackLayout>
        <Entry Placeholder="Has default context menu">
        </Entry>
    </VerticalStackLayout>
```

I've tested the same code inside our Sandbox and inside a mauiapp and neither of those crash. If you resize the window to a smaller size in our control samples it no longer crashes. 

I wasn't able to narrow down a specific repro for this issue so I'm creating this issue for now as a place for others to report if they are seeing this in the wild.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.1. Not repro this issue.
