### ISSUE TITLE
MAUI DisplayAlert() When User Closes Window : Getting Unhandled Exception

### ISSUE THREAD

**Issue by BhangeeF16** [dotnet/maui#9355]
### Description

I want to show an ALERT/POPUP to the user to ask him/her before he closes the Application.

This is what I am already doing : 

In `App.xaml.cs`

`Application.Current.MainPage.DisplayAlert` this line throws unhandled exception, 
**The Exception gets unhandled by debugger itself**. and it says : 

> a debugger is attached to but not configured to debug this unhandled
> exception.

https://github.com/BhangeeF16/MAUI-DOT-NET/blob/main/SampleApp/App.xaml.cs

        public partial class App : Application
        {
         public static IServiceProvider Services;
        
            public App(IServiceProvider serviceProvider)
            {
                InitializeComponent();
                Services = serviceProvider;
                MainPage = new MainPage();
            }
            protected override Window CreateWindow(IActivationState activationState)
            {
                Window window = base.CreateWindow(activationState);
                window.Page = MainPage;
                window.Destroying += Window_Destroying;
                return window;
            }
        
            private void Window_Destroying(object sender, EventArgs e)
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine("Destroying");
                    App.Current.Dispatcher.Dispatch(async () =>
                    await App.Current.MainPage.DisplayAlert("Alert", "Are you sure you want to close the application.", "Yes", "No"));    
                }
                catch (Exception)
                {
                }
            }
        }
    

### Steps to Reproduce

1. Create an MAUI App
2. Overload **CreateWindow** in **APP.xaml.cs** as shown above
3. Add an EventHandler for **OnDestroying**
4. run app
5. close app from the button in **Top Bar**

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 10 pro

### Did you find any workaround?

None

### Relevant log output

```shell
Destroying
```

**Comment by jfversluis** [comment]
Hey @BhangeeF16 thanks for the report! I think what you're seeing is that this is simply too late in the lifecycle. Some of the objects that you are trying to use (maybe Dispatch?) are already cleaned up at this point and it's not able to show a dialog anymore. I think you will need to find an event earlier in the lifecycle to implement this functionality.

Have a look at the documentation [here](https://docs.microsoft.com/dotnet/maui/fundamentals/app-lifecycle) to help you find the right point in time. It might be that the right lifecycle event for you is not surfaced in .NET MAUI and you'll need to use the platform lifecycle event.

If you find the right one and think it should be part of .NET MAUI, please feel free to open a feature request for it at that time.

Thanks!
