### ISSUE TITLE
MAUI name is already in use

### ISSUE THREAD

**Issue by crnisamuraj** [dotnet/maui#9364]
### Description

"Description
Could not find any open issue on this topic. Others are closed, but still not solved. That is why I open a new issue.

MAUI is a registered trademark in European Union. It is registered by Blue Systems which also employes KDE developers.

Here is a link about trademark status: https://euipo.europa.eu/eSearch/#details/trademarks/013410601

These news struck me like a lightning in early morning when I was drinking my coffee. This happening again? It was similar issue that Microsoft made in the past, I think it was GVfs (GNOME Virtual file system), and now this MAUI, which for the past idk maybe 6-8 years was a KDE project for front-end UI framework based on QQC2 and Kirigami. It is really nice project, free and open-source. How can someone just come and take the name of the project for some another project? Maybe my next project should be called .NET or Microsoft? I don't get it...

Solution to the problem would be simple: rename your project, as it is already registered trademark and these actions are illegal.

Oh, and one more thing. Stealing is bad. Microsoft should be ashamed of themselves."

### Steps to Reproduce

Easy to reproduce.
Check registered trademark.
https://euipo.europa.eu/eSearch/#details/trademarks/013410601

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Workaround?
Stop playing dirty and rename it. Stealing is not nice, against the law, and against common sense.
Wake up! 

### Relevant log output

```shell
Stop stealing.
```

**Comment by crnisamuraj** [comment]
This is so Microsoft move 😂 stealing is how Microsoft was born, and how forst version of MS Windows came to life. I know u motherfuckers wont resolve this, so that's why I'll keep calling you motherfuckers. 
Hope it frustates u as much as u frustrate rest of the open source community.
Microsoft = evil Corp
Fuck you all and have a good day!

**Comment by richlander** [comment]
@crnisamuraj Please keep your language clean. I deleted your initial sentence with curse words. I deleted your following comment that had multiple.

We have a code of conduct that all users need to respect. I grasp that you are upset and why. Writing up your concerns more calmly will greatly help the conversation. I'm in the position of protecting both other community users and Microsoft employees from offensive content. I won't hesitate to lock issues, hide comments, and delete text to achieve that goal, no matter what the base topic is.

I'm going to re-lock this issue. If you'd like to talk with us, you are free to open a new issue, however I'd recommend you try a more calm language style.
