### ISSUE TITLE
Remote Debugging for Mac Catalyst (Desktop Applications)

### ISSUE THREAD

**Issue by NoralK** [dotnet/maui#9367]
### Description

When will remote debugging for Mac Catalyst (Desktop Applications) be available (RTM or Preview)?

### Public API Changes

N/A

### Intended Use-Case

Develop Mac Desktop Application on my PC with Remote Debugging.

**Comment by jfversluis** [comment]
I'm not sure we currently have any plans for it now, in either case, this is something that needs to be enabled by tooling and not the .NET MAUI SDK itself. I will put on a label that will indicate this needs to be reported through another channel in order for it to land with the right team. A bot will put in a comment with all the instructions. Thanks so much for your suggestion!

**Comment by NoralK** [comment]
I submitted  the request [here](https://developercommunity.visualstudio.com/t/Visual-Studio-2022---Remote-debugging-fo/10119220?entry=suggestion&space=8).
