### ISSUE TITLE
MAUI option is not on the VS installer

### ISSUE THREAD

**Issue by bastion9** [dotnet/maui#9368]
I'm doing the MAUI tutorial but I can't find the option.

Visual Studio 2022 Community

**Comment by AndreasReitberger** [comment]
You need to install `Visual Studio 2022 Preview` instead.

https://visualstudio.microsoft.com/de/vs/preview/

**Comment by jfversluis** [comment]
@AndreasReitberger as of this week you should be able to also use Visual Studio 17.3 stable. 

Without an exact version number this is only guessing unfortunately though. In any case, this is a Visual Studio issue and not so much a .NET MAUI issue.
