### ISSUE TITLE
XAML Live preview don't work on Windows build

### ISSUE THREAD

**Issue by BrandonStudio** [dotnet/maui#9369]
### Description

Same as #3190

### Steps to Reproduce

Create a MAUI app (not blazor) with default template,
debug.
Open the XAML live preview window
Got "XAML Live Preview is unavailable ..."

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

**Comment by jfversluis** [comment]
Hey @BrandonStudio thanks for the report, this is an issue in the tooling. I will put a label on that will trigger a bot which comments the instructions on how to report this through the proper channels. Thanks!
