### ISSUE TITLE
Adding Xamarin Native library as nuget causing an build error

### ISSUE THREAD

**Issue by Alex-Dobrynin** [dotnet/maui#9373]
### Description

After adding Xamarin Native library as nuget package and trying to build the project I'm getting build error

![image](https://user-images.githubusercontent.com/23138430/184318786-97f31985-31eb-4f59-991b-12b6fd9f53bf.png)

![image](https://user-images.githubusercontent.com/23138430/184318739-99c8084a-d537-48a5-ad7f-7bb104a13d8c.png)

In xamarin.Forms or Xamarin native project works perfectly.

Tried only on Android, but have thoughts, that situation on iOS is same

[MauiApp1.zip](https://github.com/dotnet/maui/files/9314992/MauiApp1.zip)

### Steps to Reproduce

Open attached project and build

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Use Xamarin Native or Xamarin.Forms project types

**Comment by samhouts** [comment]
@Alex-Dobrynin I'm afraid that's expected for libraries that did not update to .NET 6+. Please contact Scandit and request that they make a MAUI compatible library! In the meantime, you may have success with [ZXing.NET.MAUI](https://github.com/Redth/ZXing.Net.Maui) for barcode scanning.  Thank you!
