### ISSUE TITLE
Allow Native MAUI Controls to be placed and used from .razor pages in Blazor Hybrid App

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#9378]
### Description

Allow .NET MAUI Native Controls to be used inside of .razor Pages in Blazor Hybrid Project.
This way the developer would not have to learn XAML and continue to use their Web Skills.
This will be huge productivity boost.

### Public API Changes

Not sure

### Intended Use-Case

I have an App which requires to Scan QrCode in Blazor Hybrid Project, There are MAUI controls which allows to Scan QrCode but cannot use them in Blazor Hybrid Project. Now mixing the .xaml pages along with .razor pages each using different coding style convolutes the Programing style with additional burden to learn xaml

**Comment by TanayParikh** [comment]
Perhaps you're looking for something like https://docs.microsoft.com/mobile-blazor-bindings/?

**Comment by MackinnonBuck** [comment]
Closing since the question has been answered.
