### ISSUE TITLE
Images not display correctly on WinUI

### ISSUE THREAD

**Issue by osnipezzini** [dotnet/maui#9379]
### Description

When running the project on Android the images are shown correctly, but on Windows it doesn't show any

### Steps to Reproduce

1. Create a blank project or clone [Reproducing project](https://github.com/osnipezzini/MauiSyncBug)
2. Create a list with images (CollectionView or ListView)
3. Load same app on Android and Windows
4. On android images display correctly
5. On Windows images don't show

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by samhouts** [comment]
@osnipezzini Thank you for the report, and sorry for the delay in responding to you!

You should include the .png extension when referencing images. See the [image documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image?view=net-maui-7.0) for reference.

I confirmed that adding the .png extension in your application allows the images to display in WinUI.
