### ISSUE TITLE
ShouldDismissKeyboardAutomatically Not Working

### ISSUE THREAD

**Issue by LeanTolo** [dotnet/maui#9380]
### Description
When running the project on Android the keyboard  does not close automatically

### Steps to Reproduce

1. Create a blank project 
2. Add `xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"` 
3. Add `<SearchBar Placeholder="Test Keyboard" 
                                HorizontalTextAlignment="Center"
                                HorizontalOptions="Center"
                                x:Name="searchBar">
                <SearchBar.Behaviors>
                    <toolkit:UserStoppedTypingBehavior 
                                    ShouldDismissKeyboardAutomatically="True"
                                    StoppedTypingTimeThreshold="1000" />
                </SearchBar.Behaviors>
            </SearchBar>`
          On Main page  
4. Expect keyboard closes automatically

### Version with bug
Android 12.0 - API 31 // Android 7.0 -API 24

### Last version that worked well
Unknown/Other

### Affected 
Android

### Did you find any workaround?
No response

### Relevant log output
No response

**Comment by jfversluis** [comment]
Thank you @LeanTolo! However, you seem to describe a feature from the .NET MAUI Community Toolkit. You might want to open an issue on that [repo](https://github.com/CommunityToolkit/Maui/). Unfortunately I don't have the power to move it automatically. Thanks!
