### ISSUE TITLE
`Clipboard.GetTextAsync()` always returns `null` on iOS

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#9382]
### Description

I try to copy content into the `Clipboard` from the Browser.
When I try to get it with `Clipboard.GetTextAsync()`, it always returns null, even though the `HasText` property is `true`.

Android is working fine!

```cs
if (Clipboard.HasText)
                {
                    string text = await Clipboard.GetTextAsync();
                    Debug.WriteLine($"Clipboard.Text: {text}");
                    AccessToken = text;
                }
```

![image](https://user-images.githubusercontent.com/2952443/184383688-78bfc965-4f2a-40c8-8bdd-02e9c7ba8ea4.png)

### Steps to Reproduce

1. Use the iOS (simulator) and copy something in the `Clipboard` (from a website or so on).
2. In the MAUI iOS app, try to get the text as shown in the code snippet above.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by christopher-flexteam** [comment]
It should also be noted that even when programmatically adding to the clipboard from MAUI on iOS, text does not get added, nor can it be read. Clipboard events firing do fire, but the content of the clipboard is -always- null. In iOS 15, the bubble pops up to say that data was pasted from X application, but getting the text is always null...

This is a show stopping bug for my application!

**Comment by GetTheBalanceRight** [comment]
It should also be noted that even when programmatically adding to the clipboard from MAUI on iOS, text does not get added, nor can it be read. Clipboard events firing do fire, but the content of the clipboard is -always- null. In iOS 15, the bubble pops up to say that data was pasted from X application, but getting the text is always null...

This is a show stopping bug for my application!

**Comment by JerryWatsonJr** [comment]
It works on the MAUI windows app but not on IOS.

**Comment by McoreD** [comment]
I have the exact opposite problem. SetTextAsync() does not set the text in the Clipboard in macOS.

**Comment by AndreasReitberger** [comment]
Seems to work with the latest net7 version now
