### ISSUE TITLE
Change name, maui is taken 

### ISSUE THREAD

**Issue by crnisamuraj** [dotnet/maui#9386]
### Description

Just change it, stop being so retarded 

### Public API Changes

Chsnge it

### Intended Use-Case

Chsnge it!

**Comment by Symbai** [comment]
![NoLetMeThinkGIF](https://user-images.githubusercontent.com/14368203/184426442-803751d5-4446-408e-b435-eed2c70bcccb.gif)

**Comment by hartez** [comment]
Duplicate of #34
