### ISSUE TITLE
exception upon use of OnPlatform WinUI 

### ISSUE THREAD

**Issue by linkaiyu** [dotnet/maui#9390]
### Description

MAUI app crash when using OnPlatform WinUI. Here is the app xaml to reproduce the error. Please see the comment above the problem xaml code inside a Label tag

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="SettingsCrash.SettingsPage">
    <StackLayout BackgroundColor="Black" 
              WidthRequest="480"
              VerticalOptions="Center"
              HorizontalOptions="Center"
              Padding="20">

        <Label Text="Settings" 
                   FontSize="30"
                   Margin="0,0,0,20"/>

        <StackLayout Orientation="Horizontal">
            <CheckBox IsChecked="True" />
            <Label Text="Function Log" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>
        <StackLayout Orientation="Horizontal">
            <CheckBox IsChecked="False" />

            <Label Text="Action Log" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Horizontal">
            <Label Text="Interval Log(Min)" VerticalOptions="Center" InputTransparent="True"/>
            <CheckBox IsChecked="True" />
            <Label Text="MaxMin Log(Min)" Margin="10,0,10,0" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Horizontal">
            <Label Text="Pause updates on resize/move" Margin="0,0,20,0" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Vertical" Margin="0,10,0,0">
            <Label Text="LogPath" />
            <Entry Text="ttt"
                   IsReadOnly="True"/>
        </StackLayout>

        <Grid WidthRequest="440" 
                  RowDefinitions="100" 
                  ColumnDefinitions="*,*">
            <Button Text="Cancel"
                        Grid.Column="0"
                        HeightRequest="50"
                        WidthRequest="100"
                        />
            <Button Text="Save"
                        Grid.Column="1"
                        HeightRequest="50"
                        WidthRequest="100"
/>
        </Grid>

    </StackLayout>

</ContentPage>

### Steps to Reproduce

1. create a new MAUI shell app
2. in the AppShell.xaml, paste in this code:
3.
 <?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="SettingsCrash.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:SettingsCrash"
    Shell.FlyoutBehavior="Flyout">

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

    <ShellContent 
        Title="Settings" 
        ContentTemplate="{DataTemplate local:SettingsPage}"
        Route="SettingsPage"/>

    <ShellContent 
        Title="Test here" />
</Shell>

3. create another xaml file named SettingsPage.xaml and paste in this code:
4.<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="SettingsCrash.SettingsPage">
    <StackLayout BackgroundColor="Black" 
              WidthRequest="480"
              VerticalOptions="Center"
              HorizontalOptions="Center"
              Padding="20">

        <Label Text="Settings" 
                   FontSize="30"
                   Margin="0,0,0,20"/>

        <StackLayout Orientation="Horizontal">
            <CheckBox IsChecked="True" />
            <Label Text="Function Log" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>
        <StackLayout Orientation="Horizontal">
            <CheckBox IsChecked="False" />

            <Label Text="Action Log" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Horizontal">
            <Label Text="Interval Log(Min)" VerticalOptions="Center" InputTransparent="True"/>
            <CheckBox IsChecked="True" />
            <Label Text="MaxMin Log(Min)" Margin="10,0,10,0" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Horizontal">
            <Label Text="Pause updates on resize/move" Margin="0,0,20,0" VerticalOptions="Center" InputTransparent="True"/>
        </StackLayout>

        <StackLayout Orientation="Vertical" Margin="0,10,0,0">
            <Label Text="LogPath" />
            <Entry Text="ttt"
                   IsReadOnly="True"/>
        </StackLayout>

        <Grid WidthRequest="440" 
                  RowDefinitions="100" 
                  ColumnDefinitions="*,*">
            <Button Text="Cancel"
                        Grid.Column="0"
                        HeightRequest="50"
                        WidthRequest="100"
                        />
            <Button Text="Save"
                        Grid.Column="1"
                        HeightRequest="50"
                        WidthRequest="100"
/>
        </Grid>

    </StackLayout>

</ContentPage>

build the app, at runtime, select the Settings menu item from the flyout menu.

### Version with bug

6.0.400

### Last version that worked well

6.0 Release Candidate 3

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows Build 22000.856

### Did you find any workaround?

workaround is to remove the use of Margin="{OnPlatform}"

### Relevant log output

```shell
no specific log output
```

**Comment by jfversluis** [comment]
Hi there! Thanks for all the details in here, but I think it would be easier to put it in a repro project and on a GitHub repository, that way we can also have a look a bit easier and it's more clear what might be the problem. Could I maybe ask you to do that? Thanks!

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue using this piece of code:

```
<StackLayout Orientation="Horizontal">
      <CheckBox IsChecked="True" />
      <Label Text="Function Log" Margin="{OnPlatform WinUI='-90,0,0,0'}" VerticalOptions="Center" InputTransparent="True"/>
  </StackLayout>
```

Could you attach a small sample where reproduce the issue?

**Comment by linkaiyu** [comment]
This issue can only be reproduced in a custom application. The owner of the app is on vacation. Once he is back, we will give you access to the repo

**Comment by linkaiyu** [comment]
Hi Javier, you are given access to the repo: https://github.com/xamcat/fid-nxt-gen-dsktp
here are the steps to reproduce:
1. open FidelityAtpNextGen.sln
2. open FidelityAtpNextGen\Views\AtpSettingsPage.xaml
3. paste in the code provided in the issue description above (it has the OnPlatform WinUI syntax)
4. build and run. when the app is up, click the flyout menu on the top left
5. in the flyout menu, click the first "Settings" item
6. the exception should throw

**Comment by jsuarezruiz** [comment]
> Hi Javier, you are given access to the repo: https://github.com/xamcat/fid-nxt-gen-dsktp here are the steps to reproduce:
> 
> 1. open FidelityAtpNextGen.sln
> 2. open FidelityAtpNextGen\Views\AtpSettingsPage.xaml
> 3. paste in the code provided in the issue description above (it has the OnPlatform WinUI syntax)
> 4. build and run. when the app is up, click the flyout menu on the top left
> 5. in the flyout menu, click the first "Settings" item
> 6. the exception should throw

Tried but cannot reproduce the issue, could we have a small sample or way to reproduce it?

**Comment by linkaiyu** [comment]
Here is the repro link:
https://github.com/linkaiyu/OnPlatformWinUI/tree/main
please note, the repro is build on .NET7 and the original exception from .NET6 based app does not show anymore
