### ISSUE TITLE
Get device serial number

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/maui#9395]
I have checked the Maui essentials, But no luck.
Is there any workaround to get Device Serial Number ?
Or an intention to add IMEI and Serial Number to DeviceInfo ?

**Comment by angelru** [comment]
@Sharaf-Mansour 
Android:
```

      public string DeviceID()
        {
            var context = Android.App.Application.Context;
            return Secure.GetString(context.ContentResolver, Secure.AndroidId);
        }
```

iOS:
```
 public string DeviceID()
        {
            return UIDevice.CurrentDevice.IdentifierForVendor.AsString();
        }
```

**Comment by snlyazilim** [comment]
Secure.AndroidId Is Not Get Serial Number.

**Comment by Sharaf-Mansour** [comment]
No they are not the same.

**Comment by JohnHDev** [comment]
> @angelru I have already tried that. And no they are not the same.
> I want to have the option to get device serial number - MAC Address - IMEI - Etc.

Short answer, you can't. Apple has restricted access to this information for privacy reasons, Im assuming Google is the same. On iOS the closest you can get is the IndentityForVendor property.

A quick google search will give you all the reasons behind this.

**Comment by Sharaf-Mansour** [comment]
@JohnHDev Thanks for the answer.
