### ISSUE TITLE
maui-check fails on xcode and sdk for ios, maccatalyst, tvos, macos

### ISSUE THREAD

**Issue by JohnKesko** [dotnet/maui#9398]
### Description

After quite some time, everything seems to work and I can compile but maui-check still fails the xcode checkup and sdks even though xcode and sdks is installed.

Running maui-check --verbose 
<img width="642" alt="Screenshot 2022-08-13 at 11 30 36" src="https://user-images.githubusercontent.com/87022265/184477993-e8ca21d5-650e-4585-b818-a619eb75d804.png">

xcode:
~ » xcode-select -p
/Applications/Xcode.app/Contents/Developer

sdk:
~ » dotnet workload list

Installed Workload Ids      Installation Source
-----------------------------------------------
macos                       SDK 6.0.300        
maui-maccatalyst    SDK 6.0.300        
maui-ios                    SDK 6.0.300        
maui-android            SDK 6.0.300        
ios                              SDK 6.0.300        
maccatalyst               SDK 6.0.300        
tvos                            SDK 6.0.300  

tried using a rollback-file but still the same.
{
    "microsoft.net.sdk.android": "32.0.440/6.0.300",
    "microsoft.net.sdk.ios": "15.4.447/6.0.300",
    "microsoft.net.sdk.maccatalyst": "15.4.447/6.0.400",
    "microsoft.net.sdk.tvos": "15.4.447/6.0.400",
    "microsoft.net.sdk.macos": "12.3.447/6.0.400",
    "microsoft.net.sdk.maui": "6.0.419/6.0.300"
}

What am I missing?

### Steps to Reproduce

N/A

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

/

**Comment by jfversluis** [comment]
Thanks for the report! However, maui-check is not a officially supported tool. You might try and report the issue on the maui-check repohttps://github.com/Redth/dotnet-maui-check

Thanks!
