### ISSUE TITLE
`Picker.Items.Add()` doesn't work.

### ISSUE THREAD

**Issue by F-Unction** [dotnet/maui#9399]
### Description

Tried to add items of picker by `Picker.Items.Add()`, but it didn't work.

### Steps to Reproduce

[Reproduction project](https://github.com/F-Unction/PickerBug)

1. Create a File > New .NET MAUI App
2. Add a `Picker` like so: `<Picker x:Name="picker"/>`
3. Add `picker.Items.Add("item");` to `MainPage()` in `MainPage.xaml.cs`
4. Change `OnCounterClicked` to 
    ```c#
	private void OnCounterClicked(object sender, EventArgs e)
	{
		picker.Items.Add("won't appear");
	}
    ```
5. Click the button and observe the bug.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

I know Xamarin.Forms is very similiar to MAUI, so I tried to find same thing in Xamarin, and got this: [link](https://stackoverflow.com/questions/52796368/picker-not-updating-when-itemssource-changed)

The bug using `ItemsSource` do appear in MAUI, but that solution did't work at all.

I think both the bug using `Items` and the bug using `ItemsSources` are out of same thing, so I hope you can solve them once.

**Comment by MagicAndre1981** [comment]
Duplicate of https://github.com/dotnet/maui/issues/9239

**Comment by F-Unction** [comment]
sorry
