### ISSUE TITLE
MenuBar not shown on Andoid

### ISSUE THREAD

**Issue by Lyra2108** [dotnet/maui#9421]
### Description

I tried to use a MenuBar in my App. It works fine on Windows but the MenuBar is not shown on my Android phone.

Here are the screen shots from the example project linked below.

Windows:
![grafik](https://user-images.githubusercontent.com/2102141/184554677-46ac442d-2f48-49ce-8b2a-cfab647f9ea6.png)

Android:
![grafik](https://user-images.githubusercontent.com/2102141/184554679-d67ab7be-21fb-4688-b0c8-d762afc875bd.png)

### Steps to Reproduce

I was having the same issue not only with my app but also with this example menubar project:

https://github.com/SyncfusionExamples/maui-general-samples/tree/main/MenuBarUIApplication 

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by 420tech** [comment]
I am pretty sure MenuBar is only supported on desktop apps.

**Comment by jfversluis** [comment]
As pointed out by @420tech (thank you!) At this point MenuBar is not supported beyond desktop targets. You probably want to use ToolBarItems at this point if you need similar functionality on Android and iOS.
