### ISSUE TITLE
Fail to load platform specific dll at runtime.

### ISSUE THREAD

**Issue by Greg-Bates-Trimble** [dotnet/maui#9427]
### Description

Unable to use platform specific dlls because at runtime an InvalidProgramException is thrown.

Have this code for each platform in the csproj;
  ```
<ItemGroup Condition="$(TargetFramework.Contains('-android')) != false ">
    <Reference Include="CompanyName.Licensing.Android">
      <HintPath>ProjectName\CompanyName.Licensing.Android.dll</HintPath>
    </Reference>
  </ItemGroup>
```

This is the stack trace;

**System.InvalidProgramException:** ''

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException
[mono-rt]    at CompanyName.Licensing.Implementation.Licensing..ctor(String storagePath, String serialNumber)
[mono-rt]    at CompanyName.Licensing.LicensingFactory.CreateLicensing(Context context)
[mono-rt]    at ProjectName.FunctionCall() in SourceCodeLocation
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

From looking at the output it seems many dlls are failing to load at runtime. The following are just a few of what I've seen.

[monodroid-assembly] open_from_bundles: failed to load assembly CommunityToolkit.Maui.Core.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll

I can navigate to the correct library through the IDE - only at runtime does it seem to not be loaded. It is possible that I have not done this correctly as manually updated the csproj to include the dlls. If someone has any documentation on loading platform specific libraries that would be appreciated thanks.

### Steps to Reproduce

1. Create a new MAUI project.
2. Add in a platform specific library in the assemblies.
3. Try to access at runtime.
4. InvalidProgramException should occur

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 12, iOS 15.4

### Did you find any workaround?

No workaround

**Comment by jfversluis** [comment]
Hi @Greg-Bates-Trimble thank you for the extensive report here. A `InvalidProgramException` indicated that the IL is corrupted so maybe the DLL gets corrupted somehow? I do doubt that this has something to do with .NET MAUI specifically. Did you try to reproduce this on a .NET 6 Android application and see if it also behaves the same way?

This is probably best reported on https://github.com/xamarin/xamarin-android or see if they already have a similar issue for it. If you do think this has to do with .NET MAUI, could you please add a reproduction project in the form of a GitHub repo so we can have a look? Thanks!

**Comment by Greg-Bates-Trimble** [comment]
Hi Gerald, thanks for the prompt response. Haven't had any issues with this dll in the past. Used it on the Xamarin project which we have now brought across onto MAUI. From using dotPeek I can see that the dll which is in the bin/Debug/net6.0-android looks to be correct. When I take a look into the apk I can see the wrapper for the dll with this convention "lib\x86_64\lib{CompanyName}.Licensing.CSWrapped.so". 
One thing to note is with the Xamarin project we had the option to bundle the assemblies turned off. This means that apk from the Xamarin project has the dlls in the assemblies (MAUI has only rc.bin in the assemblies).
I will attempt to make a reproduction project, however have issues with IP.
Thanks

**Comment by JRosanowski** [comment]
@jfversluis I confirmed that we get the same problem with an Android .Net 6 app. The library was originally built to work with Xamarin projects. (Potentially dumb question...) Does it need to be built as an Android .Net 6 class library to be compatible?
Thanks.

**Comment by jfversluis** [comment]
This sounds more like something that lives on the Android level rather than .NET MAUI. You probably want to open an issue on https://github.com/xamarin/xamarin-android/ where they can help diagnose this better :)

I would move the issue for you, but unfortunately I can't between different GitHub organizations. Please open an issue with them and link them to this one. Hopefully they should be able to give you more info. Thanks!
