### ISSUE TITLE
The target "PrepareMsixPackage" does not exist in the project

### ISSUE THREAD

**Issue by thelimek** [dotnet/maui#9432]
Hi,
After creating a new .NET MAUI project I receive this error after I start the build for windows
I tried to reinstall.
I tried different versions (VS2022 17.4Pre) VS202217.3.

The error remains the same

1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4592,7): error MSB4057: The target "PrepareMsixPackage" does not exist in the project.
1>Done building project "MauiApp3.csproj" -- FAILED.

I can build for Android on the other side

Peter

---
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jfversluis** [comment]
Hey there, so sorry it took some time to get around to this. Is this still something you encounter in newer versions? Is there still anything we can help you with?
