### ISSUE TITLE
Windows TitleBar button hover color not behaving as expected and position alignment is off when maximimized

### ISSUE THREAD

**Issue by ccarv** [dotnet/maui#9436]
### Description

Three separate issues, perhaps related to the same root cause.

I've spent a good portion of the last three days trying to determine how to replace the Windows TitleBar in my Blazor application. I stumbled [on a post](https://docs.microsoft.com/en-us/answers/questions/914870/blazor-hybrid-maui-application-window-customizatio.html) on the Microsoft forum where a developer had some luck.

1. I've managed to change the color of the TitleBar but am still having issues where the TitleBar does not align properly when maximized. You can see a few pixels of the original TitleBar.

![image](https://user-images.githubusercontent.com/2898521/184644012-5a53dfef-1bcd-459a-b212-b0fa2d422bac.png)

2. The window buttons (minimize, maximize, exit) are not aligned vertically - you can see this in the image above. This can cause unexpected behavior when trying to maximize / close or maximize / minimize.

3. And last, I am able to change the color of these buttons in almost every scenario...except hover. Again, you can see it in the screenshot above. The colors remain static when you mouse over.

### Steps to Reproduce

1. Create new MAUI Blazor application
2. Modify Platforms > Windows > App.xaml.cs

Make the following changes to the constructor of `App`.

```C#
    public App()
    {
        this.InitializeComponent();
        
        WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
        {
            var width = 1420;
            var height = 838;

            var nativeWindow = handler.PlatformView;
            nativeWindow.Activate();

            var hWnd = WindowNative.GetWindowHandle(nativeWindow);
            var windowId = Win32Interop.GetWindowIdFromWindow(hWnd);
            var appWindow = AppWindow.GetFromWindowId(windowId);

            var titleBar = appWindow.TitleBar;

            // Set active window colors
            titleBar.ForegroundColor = Colors.White.ToWindowsColor();
            titleBar.BackgroundColor = Colors.Green.ToWindowsColor();
            titleBar.ButtonForegroundColor = Colors.White.ToWindowsColor();
            titleBar.ButtonBackgroundColor = Colors.SeaGreen.ToWindowsColor();
            titleBar.ButtonHoverForegroundColor = Colors.Gainsboro.ToWindowsColor();
            titleBar.ButtonHoverBackgroundColor = Colors.DarkSeaGreen.ToWindowsColor();
            titleBar.ButtonPressedForegroundColor = Colors.Gray.ToWindowsColor();
            titleBar.ButtonPressedBackgroundColor = Colors.LightGreen.ToWindowsColor();

            // Set inactive window colors
            titleBar.InactiveForegroundColor = Colors.Gainsboro.ToWindowsColor();
            titleBar.InactiveBackgroundColor = Colors.SeaGreen.ToWindowsColor();
            titleBar.ButtonInactiveForegroundColor = Colors.Gainsboro.ToWindowsColor();
            titleBar.ButtonInactiveBackgroundColor = Colors.SeaGreen.ToWindowsColor();
        });
    }
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 (build 22000.856)

**Comment by PureWeen** [comment]
- does this code work correctly inside a WinUI3 app without MAUI
- .NET MAUI uses a custom titlebar to display the title bar so you can add a custom one or modify the one we use if you modify the WinUI template https://github.com/dotnet/maui/pull/5811. You might also try disabling the custom titlebar we setup by calling `Window.ExtendsContentIntoTitleBar = false` so that you are only getting the system toolbar you are customizing

**Comment by ccarv** [comment]
@PureWeen I am relatively new to C#, and using MAUI and Blazor is first for me in terms of GUI design on Windows. So bear with me...

> does this code work correctly inside a WinUI3 app without MAUI
I'm not sure where to start with this. I tried creating a new WinUI 3 project but the option is not available in the "Create new project" templates. I will look into testing this today.

> .NET MAUI uses a custom titlebar to display the title bar so you can add a custom one or modify the one we use if you modify the WinUI template https://github.com/dotnet/maui/pull/5811. You might also try disabling the custom titlebar we setup by calling Window.ExtendsContentIntoTitleBar = false so that you are only getting the system toolbar you are customizing
I tried this already and it has no effect. Perhaps I'm invoking this in the wrong place? Using the example above, I added the following just after `appWindow` initialization.
```C#
            appWindow.TitleBar.ExtendsContentIntoTitleBar = false;
```

In addition to this, I made a change to `MauiProgram`:
```C#
        builder.ConfigureLifecycleEvents(lifecycle => {
#if WINDOWS
            lifecycle.AddWindows(windows => windows.OnWindowCreated((del) => {
                del.ExtendsContentIntoTitleBar = false;
            }));
#endif
        });
```

None of these changes had any effect.

In regards to https://github.com/dotnet/maui/pull/5811, I see this solution is only compatible with Windows 11. Are there any plans by Microsoft to officially support manipulating the title bar in XAML? The current work arounds have too many caveats and feel a bit hacky.

**Comment by ccarv** [comment]
I spoke to soon. I removed 
```C#
            appWindow.TitleBar.ExtendsContentIntoTitleBar = false;
```

and kept 
```C#
        builder.ConfigureLifecycleEvents(lifecycle => {
#if WINDOWS
            lifecycle.AddWindows(windows => windows.OnWindowCreated((del) => {
                del.ExtendsContentIntoTitleBar = false;
            }));
#endif
        });
```
and it worked!

Is this solution only compatible with Windows 11?

**Comment by PureWeen** [comment]
> I spoke to soon. I removed
> 
> ```cs
>             appWindow.TitleBar.ExtendsContentIntoTitleBar = false;
> ```
> 
> and kept
> 
> ```cs
>         builder.ConfigureLifecycleEvents(lifecycle => {
> #if WINDOWS
>             lifecycle.AddWindows(windows => windows.OnWindowCreated((del) => {
>                 del.ExtendsContentIntoTitleBar = false;
>             }));
> #endif
>         });
> ```
> 
> and it worked!
> 
> Is this solution only compatible with Windows 11?

Yea, unfortunately those `TitleBar` APIs are only surfaced with Windows 11. 
https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#colors

We're hoping that story will change at some point :-) 

There are also `StaticResources` you can set but I haven't played with these too much as of yet
https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3#platform-options that might do the trick
