### ISSUE TITLE
Removing iOS and Android TargetFrameworks results in being unable to debug Windows

### ISSUE THREAD

**Issue by JacobRFox** [dotnet/maui#9442]
### Description

Starting in VS2022 Preview 17.4.0 Preview 1 if you remove iOS and Android targets by going into properties and unchecking them and reload the project you will be unable to debug on windows, instead receiving an error message saying "Debugging Mac Catalyst on Windows is not current supported." The selected framework was double checked and was selected as "net6.0-windows10.0.19041.0"

Prior to the new VS2022 Preview 17.4.0 Preview 1 we had no issues with this configuration.

Reproduction repo here: https://github.com/JacobRFox/DebuggingBugRepro

### Steps to Reproduce

1. Create a new MAUI App using default settings in VS2022 Preview 17.4.0 Preview 1
2. Go to properties for the created project. Under the "Application" section, uncheck the boxes for iOS and Android targets
3. Save All
4. Visual studio should prompt you to reload projects at the top of the screen, reload via the prompt.
5. Clean, Rebuild, and Debug the application.

Expected Result: Debugging session begins
Actual Result: Receive error message stating "Debugging Mac Catalyst on Windows is not currently supported."

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19044 Build 19044

### Did you find any workaround?

If you include all workloads and restart visual studio, it will sometimes allow you to continue as usual. While attempting to figure out if different combinations of TargetFrameworks would cause the same issue I was able to get the project into a state I could not recover from by simply turning back on all targets.

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/9303

We have an issue filed for this internally as well FYI
