### ISSUE TITLE
GraphicsView Select Path.

### ISSUE THREAD

**Issue by essamce** [dotnet/maui#9451]
### Description

It would be helpful to allow user select a path by tab from GraphicsView.

### Public API Changes

var gv = new GraphicsView();
var hitRes = gv.HitTestResult(); // new api

### Intended Use-Case

In my drawing app I want to let user edit drawing objects graphically.

**Comment by PureWeen** [comment]
@essamce can you provide a bit more information. We're not quite clear on what you're asking for

**Comment by janseris** [comment]
I suppose it's this:
https://github.com/dotnet/maui/issues/8235

**Comment by jfversluis** [comment]
Duplicate of #8235
