### ISSUE TITLE
MAUI App bundle size is too large on release mode

### ISSUE THREAD

**Issue by sattasundar** [dotnet/maui#9453]
### Description

I have created default template app project in both MAUI and Xamarin.Forms. Publish both in release(android) mode, but surprisingly app bundle size of maui is almost double as compared to Xamarin.Forms.

### Steps to Reproduce

1. Create new app in both Xamarin.Forms and MAUI
2. Try to publish app bundle

Screenshots:

![Screenshot (12)](https://user-images.githubusercontent.com/62828724/184843127-1bc78a35-9357-475e-813f-b2150866eab8.png)

![Screenshot (13)](https://user-images.githubusercontent.com/62828724/184843154-180d6e33-a506-4bfa-bc56-e7b165453666.png)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by Symbai** [comment]
If you disable AOT on Maui the app size gets much smaller. I dont know if AOT on Xamarin Android is enabled by default but if not it would explain the difference.

**Comment by sattasundar** [comment]
> If you disable AOT on Maui the app size gets much smaller. I dont know if AOT on Xamarin Android is enabled by default but if not it would explain the difference.

After AOT disabled;

![Screenshot (14)](https://user-images.githubusercontent.com/62828724/184857573-c0cc4753-f27f-4381-b3b9-1b5090635bea.png)

I think, if we are upgrading from Xamarin.Forms to MAUI, there should be more advantages than Xamarin.Forms. The app file size is all time concern since Xamarin.Forms.

**Comment by PureWeen** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
@sattasundar I don't think you should be comparing app bundle sizes for this comparison.

Can you build an `.apk` for a single architecture?

So along with `-p:AndroidPackageFormat=apk`:
* .NET 6: `-r android-arm64`
* Xamarin.Android: `-p:AndroidSupportedAbis=armeabi-v7a`

`RunAOTCompilation=true` is default in .NET 6, while you have to specify `AotAssemblies=true` to use AOT in Xamarin.Android. Specify these properties to be sure they either both have AOT or both do not have AOT.

**Comment by sattasundar** [comment]
@jonathanpeppers sure, i will look into this as per your instructions.
