### ISSUE TITLE
Grid View Row is not working as expected

### ISSUE THREAD

**Issue by sattasundar** [dotnet/maui#9458]
### Description

I have created sample app in both **Xamarin.Forms and MAUI**. And create same ui  in a page using **Grid** , which seems different behavior.

The issue is , we can't fix any view/control at the bottom of Grid. It getting moved along with keyboard while focused on Entry control like below;

**Xamarin.Forms Result:**

![xamarin forms](https://user-images.githubusercontent.com/62828724/184874557-87a5d456-703f-40f1-8455-72015c4fe30c.gif)

**MAUI Result:**

![maui](https://user-images.githubusercontent.com/62828724/184874610-bfacb2d6-8127-439d-86b6-0b724ad770b8.gif)

### Steps to Reproduce

**Sample XAML Code:**

```
 <Grid VerticalOptions="FillAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition/>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>
            <ScrollView VerticalOptions="FillAndExpand">
                <StackLayout Spacing="25"
                             Padding="30,0"
                             VerticalOptions="Center">
                    <Entry Placeholder="Type here..."
                           BackgroundColor="ForestGreen"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                    <Label Text="Hello World!"
                           HorizontalOptions="Center"
                           FontSize="Medium"/>
                </StackLayout>
            </ScrollView>
            <Button Grid.Row="1" Text="Click Me!"
                BackgroundColor="Green"
                HeightRequest="70"
                CornerRadius="35"
                    VerticalOptions="End"/>
        </Grid>
```

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by sattasundar** [comment]
Is this issue going to resolve in upcoming releases? Because this is affecting in so many scenario.

**Comment by riccardominato** [comment]
This is still a problem.  It causes weird behaviors when using Entries with Grids, two widely used components.

I experienced an issue similar to the one described here in the very first page (a simple login page) I developed for an application in .NET MAUI.

**Comment by PureWeen** [comment]
@sattasundar in your project if you add the following code does it resolve the issue for you?

![image](https://user-images.githubusercontent.com/5375137/204575298-6217c4e3-aa8a-409e-96f8-5990dda9bcfe.png)

```C#
public class MainActivity : MauiAppCompatActivity
{

    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);
        Window.SetSoftInputMode(Android.Views.SoftInput.AdjustPan);
    }
}
```

**Comment by riccardominato** [comment]
Thank you @PureWeen. Your hint solved the issue for me.

**Comment by PureWeen** [comment]
> Thank you @PureWeen. Your hint solved the issue for me.

Thank you for testing!!

I'm going to close this issue as fixed by https://github.com/dotnet/maui/pull/11356

If that seems incorrect @sattasundar let me know.
