### ISSUE TITLE
.NET MAUI: Switching the App's MainPage multiple times leads to exception

### ISSUE THREAD

**Issue by selmaohneh** [dotnet/maui#9459]
### Description

The root of a .NET MAUI application is the class `App : Application`. 

This class has a property `Page? MainPage` that contains the current root page.

I try to use this property for navigation. I wrote a method `App.ShowPage(Page page)` that sets the property `MainPage` to the given page.

This works like a charm! I start my application and show a login page - works.

When the user clicks login on my login page I show the main view (a TabbedPage) - works.

When the user clicks on an item on that main view a details view gets shown - works.

Now when the user clicks cancel on that detail view, I try to navigate back to the main view. As always with my method `App.ShowPage(Page page)`. Now I get an exception:

> IllegalStateException; The specified child already has a parent. You
> must call removeView() on the child's parent first.

![bug](https://user-images.githubusercontent.com/29881939/184875488-2f2531a9-ec59-487b-a04e-7d6f074c17bc.PNG)

So the error message tries to tell me what to do. And I do find properties like `Element Parent` or `Element RealParent` on the `Page page` I try to open - but they are all `null`. So how do I remove the page from that parent? What is the `removeView()` method in the .NET MAUI world?

Thanks in advance for any help!

### Steps to Reproduce

1. Add a method that assigns a `IPage` to `MainPage` inside the class `App`.
2. Call the method with a page A.
3. Let page A call the method with page B.
4. Let page B call the method with page A
5. --> exception
![bug](https://user-images.githubusercontent.com/29881939/184875428-558010f6-8c17-433d-b9f7-903081a5c3dd.PNG)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No.

**Comment by sattasundar** [comment]
@selmaohneh  Can you upload zip file/github url of your sample project?

**Comment by PureWeen** [comment]
related https://github.com/dotnet/maui/issues/7153

**Comment by selmaohneh** [comment]
> @selmaohneh Can you upload zip file/github url of your sample project?

Sure. Clicked a sample together --> https://github.com/selmaohneh/ErrorReproduction

Run the app on android. 
Click the button on red screen. 
Click the button on the green screen.
Exception.

It explodes on windows, as well.
