### ISSUE TITLE
Cannot compile for build 17763 (Windows 10 version 1809)

### ISSUE THREAD

**Issue by sinsedrix** [dotnet/maui#9463]
### Description

MAUI is meant to be compiled for Windows 10 version 1809, corresponding to de build 17763.
https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms

I tried to set TargetFramework to net6.0-windows10.0.17763.0 and got the following error:

Erreur	CS0012	Le type 'Application' est défini dans un assembly qui n'est pas référencé. Vous devez ajouter une référence à l'assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.	MauiApp2 (net6.0-windows10.0.17763.0)	C:\Tests\MauiApp2\Platforms\Windows\App.xaml.cs	11	Actif

### Steps to Reproduce

1. Create a new MAUI App
2. Change target framework to net6.0-windows10.0.17763.0
3. Build

dotnet --version
- 6.0.400-preview.22330.6
- 6.0.400

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10  1809

### Relevant log output

```shell
Erreur	CS0012	Le type 'Application' est défini dans un assembly qui n'est pas référencé. Vous devez ajouter une référence à l'assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.	MauiApp2 (net6.0-windows10.0.17763.0)	C:\Tests\MauiApp2\Platforms\Windows\App.xaml.cs	11	Actif
```

**Comment by PureWeen** [comment]
@sinsedrix the min supported version for MAUI is 17763 so you shouldn't need to change the TFM. Why are you wanting to update the TFM?

**Comment by sinsedrix** [comment]
Ok, if I understand, A 19041 target framework should run on a 17763 OS?

**Comment by MagicAndre1981** [comment]
The `TargetPlatformMinVersion` controls which is the lowest version the app runs on.

**Comment by sinsedrix** [comment]
Ok, I just found confusing to have TargetPlatform greater than TargetPlatformMinVersion.

**Comment by MagicAndre1981** [comment]
TargetPlatform is the toolkit/SDK version used to compile the app.
