### ISSUE TITLE
[Windows 11 Insider] Image appears distorted.

### ISSUE THREAD

**Issue by NonameMissingNo** [dotnet/maui#9464]
### Description

[DistortedImages.zip](https://github.com/dotnet/maui/files/9351212/DistortedImages.zip)
There are images that appear like they haven't been converted correctly.
![image](https://user-images.githubusercontent.com/40233496/184886265-54cd444b-e06c-46f8-b34d-59e77a688dbc.png)

### Steps to Reproduce

Make sure to be on Windows 11 Insider build (dev build).
Make a new project, replace the original image with one in the zip file.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Insider

**Comment by PureWeen** [comment]
@mattleibow  we put this in the backlog for now.

**Comment by mattleibow** [comment]
This was fixed in https://github.com/dotnet/maui/pull/10008
