### ISSUE TITLE
Error while trying to run sample app for first time

### ISSUE THREAD

**Issue by npongo** [dotnet/maui#9467]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

When building I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1700: The recipe file "C:\Users\benja\source\repos\MyFirstMauiApp\MyFirstMauiApp\bin\Debug\net6.0-android\MyFirstMauiApp.build.appxrecipe" does not exist. You may need to build your project.	MyFirstMauiApp

**Comment by PureWeen** [comment]
If you rebuild your app does it work?

**Comment by npongo** [comment]
﻿No have been able to get it to work yet. Trying to install/reinstall more Maui workloads to see if that fixes it

Sent from my iPhone

**Comment by jfversluis** [comment]
I'm a bit confused. First you said it did work, then it didn't? 😄

Do you still need help with something here?
