### ISSUE TITLE
Spaces in static files in the main project or in a Razor Class Library cause the image to not load

### ISSUE THREAD

**Issue by jt-pt-dev** [dotnet/maui#9481]
### Spaces in image names cause the image to not load

Shared images will not load if they have a space in the file name.

Debugging gives a message `Failed to load resource: net::ERR_ADDRESS_INVALID` in the browser dev tools.

Setup is a MAUI Blazor project with a Razor Class Library running against Windows.

### Steps to Reproduce

GitHub repository with demo: https://github.com/jt-pt-dev/MAUIReproSpaces

1. VS 17.3.1 new project MAUI Blazor
2. Add Razor class library (for shared UI)
3. Add images folder in wwwroot in RCL; one with a space and one without
4. Reference the images in a Razor component **in the MAUI** project
5. Run the MAUI project targeting Windows
6. Images with a space in the name will not load

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

Remove spaces from the file names of shared images.

**Comment by davidbuckleyni** [comment]
Aint this a bit werid sure if you where working on linux for example you wouldnt use spaces in names should u not trim them and have the real name as a description?

**Comment by javiercn** [comment]
@jt-pt-dev thanks for contacting us.

Do you see any error in the developer tools console?

**Comment by jt-pt-dev** [comment]
Yes. On initial load in the Console tab:

`Failed to load resource: net::ERR_ADDRESS_INVALID`

On a reload in the Console tab:
`GET https://0.0.0.0/_content/MAUIReproSpaces.SharedUI/images/dotnet%20bot.png net::ERR_ADDRESS_INVALID`

On initial load the Network tab shows no error. On reload the Network tab shows:

`https://0.0.0.0/_content/MAUIReproSpaces.SharedUI/images/dotnet%20bot.png` as an error.

The Headers tab within the Network request shows:

```
Request URL: https://0.0.0.0/_content/MAUIReproSpaces.SharedUI/images/dotnet%20bot.png
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Referer: https://0.0.0.0/
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Microsoft Edge";v="104", "Microsoft Edge WebView2";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54
```

If you copy the Response to the Request to the clipboard it is: `data:undefined,`

**Comment by javiercn** [comment]
@jt-pt-dev thanks for the additional details.

This is very likely related to us not URL decoding the path component.

/cc: @Eilon

**Comment by jt-pt-dev** [comment]
Yeah, the difference between a space and %20 not being accounted for.

On 19 Aug 2022, at 9:08 pm, Javier Calvarro Nelson ***@***.***> wrote:

﻿

@jt-pt-dev<https://github.com/jt-pt-dev> thanks for the additional details.

This is very likely related to us not URL decoding the path component.

/cc: @Eilon<https://github.com/Eilon>

**Comment by Eilon** [comment]
Yeah seems like that's the case here. We already do _some_ URL munging [here](https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/SharedSource/QueryStringHelper.cs#L12), so it seems like we need to do a bit more.

**Comment by Eilon** [comment]
BTW this applies to any static asset (image, CSS, etc.) either in the main project or in a Razor Class Library (RCL).

**Comment by Eilon** [comment]
Dup of #9181.
