### ISSUE TITLE
[Windows] Converter not found

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#9484]
### Description

The sample https://github.com/jsuarezruiz/netmaui-surfing-app-challenge is using a simple converter to do upper case in some strings. While is working correctly on Android or iOS:

![image](https://user-images.githubusercontent.com/6755973/185071970-3e380b22-2a57-4ce2-a08a-897d7289ced1.png)

While in Windows:
![image](https://user-images.githubusercontent.com/6755973/185073958-dd206532-8401-4a22-b8b6-247dfac27e66.png)

### Steps to Reproduce

1. Donwload or sync https://github.com/jsuarezruiz/netmaui-surfing-app-challenge
2. Launch the App on Windows.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

**Comment by jsuarezruiz** [comment]
Could be related with https://github.com/dotnet/maui/issues/9471

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on windows platform with sample project.
[netmaui-surfing-app-challenge-main.zip](https://github.com/dotnet/maui/files/11512826/netmaui-surfing-app-challenge-main.zip)
![Screenshot 2023-05-19 094557](https://github.com/dotnet/maui/assets/77434865/eaee4eec-6eec-4fce-b27f-771ecdf9a095)

**Comment by Vignesh-SF3580** [comment]
Hi,

The converter key name was assigned in "HomeView.xaml" but used in "PostItemTemplate.xaml". The key name "ToUpperConverter" was not found in "PostItemTemplate.xaml," causing the crash. We can fix the issue at the sample level by either defining the key in "PostItemTemplate.xaml" or moving it to "App.xaml". 

![image](https://github.com/dotnet/maui/assets/102575140/7d9d5e29-32a9-49ef-99f3-4cd8ea6c97d7)

Regards,
Vignesh

**Comment by Vignesh-SF3580** [comment]
@MartyIX @jsuarezruiz

Please find the PR here: https://github.com/jsuarezruiz/netmaui-surfing-app-challenge/pull/3
