### ISSUE TITLE
[BUG ] The namespace is not being adhered to for the new content pages being created.

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/maui#9488]
### Description

The namespace is not being adhered to for the new content pages being created. On Creation of a new Maul App with custom name space

### Steps to Reproduce

1. Create brand new maui app with custom name say Booking.Maui
2. Create a subfolder called say pages.
3. Create a content page lets call it Bookings
4. Looking in the code behind of the file

![image](https://user-images.githubusercontent.com/5619229/185137244-03bcca03-1af2-40fe-9421-e246f7eeb7d8.png)

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

ALL

### Did you find any workaround?

Just renaming the name space in xaml and also code behind works

I believe the source generator would need fixed to replace the class namespace just

**Comment by janseris** [comment]
We have this problem as well. Always MauiApp1 namespace

**Comment by Rarisma** [comment]
Encountered this too, didn't help that the error was InitalizeComponent() doesnt exist making it almost impossible to figure out.

**Comment by davidbuckleyni** [comment]
I see the templates and see the issue the var is not being passed down to the code behind file but does anyone no what the var is ?

**Comment by davidbuckleyni** [comment]
Seems this is the fix for it would anyone mind if I did this ?

https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2022

**Comment by ablesoftwaredev** [comment]
> Seems this is the fix for it would anyone mind if I did this ?
> 
> https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2022

Thanks for sharing. I have this problem too since updating to 6.0.486. I think the $safeprojectname$ template parameter is not set when a new ContentPage is created. What do you suggest as a solution?

**Comment by ablesoftwaredev** [comment]
Good news 👍  This bug is no longer present in the [release version of .net Maui.](https://devblogs.microsoft.com/dotnet/dotnet-maui-visualstudio-2022-release/) Maui is out of preview and available as a workload in Visual Studio 2022 17.3. 

I checked and after creating a new ContentPage, the correct namespace is added to the code behind file.

**Comment by davidbuckleyni** [comment]
It seems to be addressed in most recently released preview I think safe to close this

**Comment by davidbuckleyni** [comment]
Seems @jamesmontemagno had this in his live stream so lets re open this

**Comment by davidbuckleyni** [comment]
This appears to be fixed all versions closing this must been visual studio tooling.
