### ISSUE TITLE
Cant add a variable to Grid rows more than once.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9493]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-add-a-variable-to-Grid-rows-more-th/10117314)._

---
[severity:It's more difficult to complete my work]
If you attempt to add the same variable e.g. Label label = new Label { Text = "Label In Grid" }; to more than one row in a Grid then this is not allowed.  A run time error is not produced however the debupping stops at the line:
68        if (global::System.Diagnostics.Debugger.IsAttached) **global::System.Diagnostics.Debugger.Break();**
in the file app.g.i.cs
The error is summarised as:
?e.Message
"Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled."

The issue can easily be replicated bu creating a new Maui Project, stripping out the default code and adding the code shown in the screenshot.

---
#### Feedback Bot on 8/11/2022, 07:41 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
> dding the code shown in the screenshot

Can you post the screenshot here? It doesn't seem to have made it into the issue.
