### ISSUE TITLE
Why does System.IO.Directory.Exists return false when viewing Mac path in .net Maui?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9494]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Why-does-SystemIODirectoryExists-retu/10118176)._

---
[severity:It's more difficult to complete my work]
I am building a .net Maui app which targets Mac Catalyst. I implemented a folder picker based on the the following article from @GeraldVersluis

https://stackoverflow.com/questions/70999773/folder-picker-net-maui

When choosing the folder the following path is returned: pickedFolder = file:///Users/macminim1/Documents/Sorted%20Testing/

If I then use:

if (System.IO.Directory.Exists(pickedFolder))
{

}

The result is false. Obviously, the folder exists as I just chose it and I confirmed it's existence in the file system.

Thanks in advance!

---
#### Feedback Bot on 8/11/2022, 07:48 PM: 

(private comment, text removed)

---
#### Julian Dormon solved on 8/11/2022, 10:22 PM, 0 votes: 

<p>The file:/ part needs to be removed from the path and the path needs to be unescaped in order for System.IO.Directory.Exists to “see” the correct path.</p>
<p>I thought Maui or .Net were supposed to handle these kinds of things to make coding platform agnostic?? Anyway, this is the solution I came up with. I hope that helps some one.</p>

**Comment by mattleibow** [comment]
Not sure the `file://` prefix is supported. According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory?view=net-6.0#remarks):

> For example, all the following are acceptable paths:
> * "c:\\MyDir" in C#, or "c:\MyDir" in Visual Basic.
> * "MyDir\\MySubdir" in C#, or "MyDir\MySubDir" in Visual Basic.
> * "\\\\MyServer\\MyShare" in C#, or "\\MyServer\MyShare" in Visual Basic.

If this is incorrect, then please open an issue with the runtime: https://github.com/dotnet/runtime
