### ISSUE TITLE
MAUI Flyout page leaves visual artefact on Android when changing pages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Flyout-page-leaves-visual-artefact-/10113024)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Standard 2.0]
When switching pages on Android using MAUI Flyout page (.NET 6), after the first change (which works as expected) each subsequent change leaves a visual artefact on screen of the page you just changed to (this worked in Xamarin .NET Standard 2.0). See screenshot.
![FlyoutBug.jpg](https://aka.ms/dc/image?name=B5f686bdfb4cb4d9ebc5fe2e6bc6804c0637954537603949279_FlyoutBug.jpg&tid=5f686bdfb4cb4d9ebc5fe2e6bc6804c0637954537603949279)
This bug is specific to MAUI Flyout page on Android. i.e. it works on Windows, it works with Xamarin MasterDetail/Flyout page for both Windows and Android. It renders the feature useless on Android (as your actual page gets pushed further and further down the screen on each page change other than the first change). I have seen the same behaviour on both an emulator Pixel 3a and a physical Note Edge. I haven't tried it on any other platforms.
I've made a repro project at [FlyoutAndroidArtefactRepro](https://github.com/SmartmanApps/FlyoutAndroidArtefactRepro)
Notes about the repro project:
1. I saw the sample Flyout page sample uses CollectionView instead of ListView (I used ListView in my Xamarin projects and as noted worked fine). I couldn't get the CollectionView to work (Nullreference on "App" - yep, very non-specific about the nature of the error, but I know the issue is somewhere in my Flyout code). My CollectionView code is commented out if you want to try that instead (if you can find what is missing in my code, if in fact that is the error). I'm happy to use CollectionView instead of ListView if we can get that working.
2. I tried downloading the MAUI sample app to compare, but couldn't get that to work at all. i.e. not in Windows either. On Windows the Menu stays on page (instead of having a hamburger icon to click on), and when I click on an item the app get an InvalidOperation exception. On Android I get a hamburger menu and can click on it, but literally nothing happens when I do. i.e. stays on the same page regardless of which item I click on. So my repro project is actually more functional that the sample app.
Here's my IDE info:
Microsoft Visual Studio Community 2022
Version 17.3.0 Preview 6.0
VisualStudio.17.Preview/17.3.0-pre.6.0+32728.150
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
C# Tools   4.3.0-3.22375.15+456937d952ad5c0930293ef32c4fbf8c844a9fef

---
#### Feedback Bot on 8/7/2022, 08:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
duplicate https://github.com/dotnet/maui/issues/7153

**Comment by SmartmanApps** [comment]
@PureWeen This isn't a duplicate. The issue you've referenced is about content not being displayed. In this case the content IS displayed, but the navbar gains a new visual artefact each time, pushing the content further down (see screenshot) - completely different issue.
