### ISSUE TITLE
Messed up Appearing/Disappearing events in Maui Pages

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9497]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Messed-up-AppearingDisappearing-events-/10112424)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.3.0 Preview 5.0]
Last update really messed up Appearing/Disappearing events in Maui Pages. They are called every time App lost focus, so debugging is impossible.

In previous version Dispose was called for Shell ViewModel unnecessary.

---
#### Feedback Bot on 8/5/2022, 01:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
This is by design to match how these events worked in XF

The events you probably want are either `Loaded` or `NavigatedTo/From/NavigatingFrom`
