### ISSUE TITLE
.NET MAUI installation bug: The target platform identifier android/ios/maccatalyst was not recognized

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-installation-bug:-The-target-p/10110752)._

---
\[severity:I’m unable to use this version\]  
I recently installed VS 2022 17.3 preview 5.0. When creating and running a MAUI project it failed with these errors:  
![182370326-c24d7dd2-3df5-4b89-ab59-7ecb0e1329e0.png](https://aka.ms/dc/image?name=B16f3cb89065b4e4a82ad8da93035302d637950694533148390_182370326-c24d7dd2-3df5-4b89-ab59-7ecb0e1329e0.png&tid=16f3cb89065b4e4a82ad8da93035302d637950694533148390)  
I am running Windows 11 Version 21H2 (OS Build 22000.795) and .NET version 6.0.400-preview.22330.6. .NET 7 is not installed.

.NET MAUI is installed through the VS Installer with the optional settings:  
IntelliCode,  
Windows Runtime Packs,  
Xamarin.

`dotnet --version:`
`6.0.400-preview.22330.6`

`dotnet --list-sdks:`
`5.0.302 [C:\Program Files\dotnet\sdk]`
`6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]`
`6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]`

`dotnet workload list:`
`Installed Workload Ids Manifest Version Installation Source`
`----------------------------------------------------------------`

`Use 'dotnet workload search' to find additional workloads to install.`

---
#### Feedback Bot on 8/4/2022, 02:31 AM: 

(private comment, text removed)
#### Julian Dormon on 8/10/2022, 08:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
re-opened internal ticket
