### ISSUE TITLE
[Enhancement] Add UseMauiApp(IApplication instance) extension

### ISSUE THREAD

**Issue by dansiegel** [dotnet/maui#950]
## Summary

Currently there is an extension to register the Application type generically or via a delegate factory like:

```cs
builder.UseMauiApp<MyApplication>();

// OR

builder.UseMauiApp(x => new MyApplication());
```

However in some cases such as what we are looking to do with Prism, we will want to simply implement IStartup as part of the PrismApplication. While we could use second overload and simply return `this` it would be better to have an additional extension method that simply takes the Application instance like:

```cs
builder.UseMauiApp(this);
```

## API Changes

```cs
public static IAppHostBuilder UseMauiApp(this IAppHostBuilder builder, IApplication instance)
{
    builder.ConfigureServices((context, collection) =>
    {
        collection.AddSingleton<IApplication>(instance);
    });
    return builder;
}
```

## Intended Use Case

Adds a useful extension for registering the Application singleton for when the IApplication instance also has implemented IStartup.

**Comment by dansiegel** [comment]
after talking more with @mattleibow on this it seems that due to lifecycle and timing... it's actually a bad idea to try to implement IStartup in your Application

**Comment by avaavg6629** [comment]
****ueeh****
