### ISSUE TITLE
When developing maui apps ,application toolbar missing.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9501]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-developing-maui-apps-application-t/10118569)._

---
[severity:It's more difficult to complete my work]
### Description

After upgrade to visual studio17.3 maui application toolbar disappeared, hot reload also take no effect;
I followed this procedure https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/intro and it didn't show application toolbar as the tutorial shows.
![image](https://user-images.githubusercontent.com/20037151/184061346-451c44d3-9698-4bc9-aeec-6d2507e59ca6.png)

tutorial page shows this
![tutor](https://dotnet.microsoft.com/static/images/maui/windows-app-hot-reload.png?v=3ywrkwIFwV9CETCQGNY6_q4QQ8XOQQ5bL1SFDxzv1hw)

### Steps to Reproduce

1. Create a   New .NET MAUI App
2. click on the debug button 
![image](https://user-images.githubusercontent.com/20037151/184061779-67295232-d193-4922-99cb-7d20f63c1b1c.png)
3. you can see the maui app with no application toolbar, hot reload takes no effect,and it's hard to debug.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

windows sdk 10.0.19041.0

### Did you find any workaround?

no

---
#### Feedback Bot on 8/11/2022, 07:36 PM: 

(private comment, text removed)
#### Jay Sumners on 8/12/2022, 02:27 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JaySumners** [comment]
Copying my comment from the developer forum:

I am also running unto this issue. It worked in the latest preview version of VS before the release of 17.3.

I’ve tried:

Uninstall and reinstall.
Production vs preview VS.
Reinstalling Android SDK (an article suggested that could be an issue).

I’ve also noticed that hot reload does not function but seems partially loaded. XAML live tree preview says XAML hot reload is not started, but I can get output on the Hot Reload output tab. Unfortunately the output therein is aways “No changes detected”.

**Comment by jfversluis** [comment]
I'm afraid the vs feedback ticket for directed here wrongfully, sorry about that. I have reopened that ticket and will be closing this one. Please add any relevant information in the ticket. Thanks!
