### ISSUE TITLE
On Windows some controls won't show image icons

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#9502]
### Description

If you add an image to the _resources/images_ folder, then set the `ToolbarItem.IconImageSource` property or `ToolBar.ShellContent.Icon` property, it displays the image on Android but not on Windows.

```xml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Add" Clicked="Add_Clicked" IconImageSource="icon_add" />
    </ContentPage.ToolbarItems>

    <TabBar>
        <ShellContent
            Title="Notes"
            ContentTemplate="{DataTemplate views:AllNotesPage}"
            Icon="icon_notes" />

        <ShellContent
            Title="About"
            ContentTemplate="{DataTemplate views:AboutPage}"
            Icon="icon_about" />
    </TabBar>
```

### Steps to Reproduce

Nothing

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No, FontImageSource extension works fine.

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/3459
