### ISSUE TITLE
Create and Publish android APK for .NET MAUI Blazor 

### ISSUE THREAD

**Issue by hemant149** [dotnet/maui#9511]
Hi

Publishing a .NET MAUI Blazor  application is just creating publish files for window platform.  and not creating a APK file for android. 

Please advise how to create a APK file from .NET MAUI Blazor project.

**Comment by jfversluis** [comment]
Please refer to the Docs for a full description on how to set that up: https://docs.microsoft.com/dotnet/maui/android/deployment/overview
