### ISSUE TITLE
TabbedPage for Android with child navigation shows the Tabbar

### ISSUE THREAD

**Issue by liveinvarun** [dotnet/maui#9512]
### Description

Tabbar space is shown in the next page - The white tabstrip space is shwon even after the push happens in android and while iOS works fine in the same scenario. There is a white strip in the bottom and the issue mostly is happening when the tabbar placement is done in bottom
[Archive.zip](https://github.com/dotnet/maui/files/9367948/Archive.zip)

### Steps to Reproduce

Attached sample that reproduces  the issue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

Not really looks like the child page dont refresh or invalidate the content when it is navigated.

**Comment by yunusefendi52** [comment]
Found workaround, use TabbedPageRenderer instead of the handler one

**Comment by eddie010** [comment]
I have the same issue. Whenever I navigate from a TabbedPage (**using Pop or Push**) I always see a white tabbar on the bottom on Android. So the white empty tabbar is also shown when navigating back... The workaround that is suggested does not work unfortunately... This makes it currently unusable for me...

The sample of liveinvarun shows exactly what's the problem and becomes even more clear when you play around with the background colors.

**Comment by moraismateus** [comment]
I am also seeing this issue, would appreciate if someone could please suggest another workaround.
