### ISSUE TITLE
Global resources when using linked ResourceDictionaries - not able to use from code behind

### ISSUE THREAD

**Issue by arkadym** [dotnet/maui#9513]
### Description

See my last comment there - https://github.com/dotnet/maui/issues/8799 

### Steps to Reproduce

1. Create new MAUI App
2. Add Custom Colors.xaml, assume there is defined `<Color x:Name="Color1">#fff</Color>`
3. Link it into App.xaml as
```
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources/Colors.xaml" />
</ResourceDictionary.MergedDictionaries>
```
5. Try access `Application.Current.Resources["Color1"] from MainForm.xaml.cs - it will throw KeyNotFoundException

As workaround i tried create ResourceLocator helper class (see https://github.com/dotnet/maui/issues/8799)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

-

### Did you find any workaround?

No workaround yet!

**Comment by arkadym** [comment]
Found workaround to make App.xaml empty and add below codes to constructor of the App.xaml.cs
```
Resources.Add(new Theme.Resources.Colors());
Resources.Add(new Resources.Styles());
```

**Comment by PureWeen** [comment]
Reopened 
https://github.com/dotnet/maui/issues/8799
