### ISSUE TITLE
Picker ItemSource not working on Windows

### ISSUE THREAD

**Issue by tekmun** [dotnet/maui#9516]
### Description

I fill up the ItemSource of a Picker with a list.
When I click on the Picker, nothing is shown.

### Steps to Reproduce

Just create a sample project with a Picker.

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

WIndows 10 SDK 10.0.17134.0

### Did you find any workaround?

No.

### Relevant log output

```shell
N.A.
```

**Comment by levitali** [comment]
If the ItemsSource of a Picker is set before a Page is shown, than it works. It doesn't work if the ItemsSource is set lately the first time. Setting ItemsSource second time resolves the issue.

[TestPicker.zip](https://github.com/dotnet/maui/files/9374798/TestPicker.zip)

**Comment by PureWeen** [comment]
Duplicate: https://github.com/dotnet/maui/issues/9239

**Comment by tekmun** [comment]
The TestPicker.zip project shows the same issue. There is no drop-down-list.
I have added this in the .csproj file.
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

This issue does not happen in earlier versions. Please help to rectify it. I cannot upload my app in Microsoft Store because of this bug.

![Error](https://user-images.githubusercontent.com/5379906/186093751-4f3679aa-578b-4376-9c9d-8324c9ec59c8.PNG)
