### ISSUE TITLE
[MAC/iOS] Enabling RightToLeft for scroll view at the run time is not working

### ISSUE THREAD

**Issue by Deepak1799** [dotnet/maui#9518]
### Description

When trying to enable RTL to scroll view using the property "ScrollView.FlowDirection= FlowDirection.RightToLeft" at the run time it is not working.

**_Note: This issue occurs only at the run time enabling of RTL. However it works if we do in the compile time._**

### Steps to Reproduce

1. Create a MAUI APP.
2. Add a scroll view in the main page and run the sample.
3. Using a button click or other way, set the Flow Direction of scroll view to RightToLeft at the run time.

I have attached a repro project here: [MauiApp26 2.zip](https://github.com/dotnet/maui/files/9372676/MauiApp26.2.zip)

1. Run the sample and toggle the switch at the left top to enable RTL.
2. Now check the scroll view, the scroll bar is still at the right end without changing to the left end.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

MacOS v12,1

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on iOS platform with sample project. [MauiApp26 2.zip](https://github.com/dotnet/maui/files/9372676/MauiApp26.2.zip)
