### ISSUE TITLE
ResourceDictionary loaded from rd.xaml does not expose any entries

### ISSUE THREAD

**Issue by etvorun** [dotnet/maui#9526]
### Description

XAML hot reload does not work when modifying base styles

### Steps to Reproduce

1. Open attached app.
2. Build and run
**Expected**: all counts should be the same
**Actual**: most counts are 0
**Note**: XAML hot reload needs a way to enumerate over all keys and values
[MauiApp1.zip](https://github.com/dotnet/maui/files/9375809/MauiApp1.zip)

![image](https://user-images.githubusercontent.com/48451158/185448972-16c9b130-0f97-4379-bdc0-19b0a7cd0634.png)

### Version with bug

6.0.408

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

unknown

**Comment by StephaneDelcroix** [comment]
looks like a bug
