### ISSUE TITLE
We need controls like WPF frame

### ISSUE THREAD

**Issue by ShioDotNetCodeer** [dotnet/maui#9538]
### Description

I want to implement a single page application. But according to the experience of WPF, it is really depressing to find that the frame and WPF controls are completely different. I'm always keen to learn new techniques, but why not unify the naming of XAML properties? Changing attribute names after each revision is a repetitive and tedious process for us during secondary learning.

### Public API Changes

nothing

### Intended Use-Case

nothing

**Comment by jfversluis** [comment]
There is a lot of history here and WPF and .NET MAUI are two very different frameworks. I understand your frustration but I don't think there is an easy fix at this point.

If you have any concrete ideas we love to hear it. Please open issues with concrete examples of what you would like to see and proposals on how you want to use it.

Closing this one as this seems more of a discussion kind of topic and isn't very actionable.

Thanks!
