### ISSUE TITLE
get error while installing .net maui

### ISSUE THREAD

**Issue by mahdibigdely** [dotnet/maui#9541]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

hi im usig visual studio the last version 
when i want to download .net maui its going to download until 75 percent but at the end i get error that some thing get wrong 
and give me some action like continoue or retry or cancel 
i try more than 5 times and its notcomplete 
pease help me to figure it out /
i search for it but there is no answer to it

**Comment by jfversluis** [comment]
Hey there @mahdibigdely sorry to hear that! Did you figure it out by now? Could you post a screenshot of what you're seeing when that happens or let us know what the error message is exactly? Without that it's kind of hard to say what might be going on. Thanks!
