### ISSUE TITLE
Adding a WCF Connected Service: The target framework '$(TargetFrameworks)' is not supported

### ISSUE THREAD

**Issue by MelissaW990** [dotnet/maui#9543]
### Description

I am trying to create a new .NET MAUI application and add a reference to an existing web service to it, as a result I get the error message below. 

If I change the target platform to Android, I get a similar message only instead it says "The target framework 'net6.0-android' is not a supported x,y,z..". I am not able to test this on iOS at this current time but I imagine it would spit out something similar.

Please advise.

![image](https://user-images.githubusercontent.com/46394174/185608591-2432095f-63e7-49d5-b255-f82b8d838f22.png)

### Steps to Reproduce

1. Create a new .NET Maui App
2. Right Click on the project > Add > Service Reference
3. Select WCF Web Service

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows SDK 10.0.19041.0, Android 12.0

### Did you find any workaround?

None

**Comment by bearyung** [comment]
> convert your classic WCF service to [Core WCF with .net 6](https://devblogs.microsoft.com/dotnet/corewcf-1-1-0-and-project-templates/) and try to add this

This error pop-up appeared even before I input the service endpoint URI, have no issue if I create a .NET 6 WPF project instead of MAUI project.

**Comment by bearyung** [comment]
I've tried to copy the reference.cs file, ConnectedService.json from the .NET 6 WPF project to the MAUI project, and updated those required references, and set the binding properties manually, and I can call the WPF service from the MAUI app (both windows and iOS version).

<img width="265" alt="image" src="https://user-images.githubusercontent.com/13907070/186109519-47fef281-934c-45c4-838d-0884cf9bb880.png">

<img width="707" alt="image" src="https://user-images.githubusercontent.com/13907070/186109994-ed91237d-40ef-4d59-864e-50cfe1737920.png">

**Comment by MagicAndre1981** [comment]
ok, so this is a VS tooling issue. Report it from inside the VS:

**Report a problem with the Visual Studio product or installer**
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

![image](https://user-images.githubusercontent.com/8274816/186223051-3fd5c90f-332f-43d6-848b-02823fca61c7.png)

**Comment by rspulini** [comment]
Mi too same problem

**Comment by bearyung** [comment]
> ok, so this is a VS tooling issue. Report it from inside the VS:
> 
> **Report a problem with the Visual Studio product or installer** https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022
> 
> ![image](https://user-images.githubusercontent.com/8274816/186223051-3fd5c90f-332f-43d6-848b-02823fca61c7.png)

Done, thank you for pointing to the right direction.
