### ISSUE TITLE
Flex Layout -> BindableLayout not working after ItemsSource changed in new vs preview version

### ISSUE THREAD

**Issue by LeanTolo** [dotnet/maui#9544]
### Description

Repo that duplicates the bug (It's happend with observable collection / List / Ienumerable ...)

[Repo](https://github.com/LeanTolo/BugFlexLayoutMAUI)

![bug](https://user-images.githubusercontent.com/62771419/185615868-44da10bb-910d-49ae-adfd-924a754e5724.png)

Im working on another project (and yesterday update vs preview to last version) and all data dissapear.

I try to reproduce it in the most simple way that i have. I'm doing something wrong?

### Steps to Reproduce

1. Create Maui Project
2. Add Flex layout with bindinglayout.ItemsSource = "any list"
3. Add Data to the List

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.0 - API 31 // Android 13.0 - API 33

### Did you find any workaround?

Rollback to a VS 17.1.0

### Relevant log output

```shell
-
```

**Comment by holecekp** [comment]
I have a very similar problem with FlexLayout. I wanted to create a new issue for it but then I found out this one, which has probably the same cause. In my case, FlexLayout does not work when I simply set ItemsSource in code (without need to do any subsequent modifications).

I have created a repro project for it. There should be two lines with buttons (A, B, C, D, E, F). Everything is displayed correctly in Xamarin.Forms. However, MAUI displays only the second line (buttons D, E, F only) and the first line is hidden on Android. Moreover, the second line collides with other controls on the page.  The situation is even worse on Windows. The app crashes there (already reported https://github.com/dotnet/maui/issues/9905).

Link to my repro project: https://github.com/holecekp/MauiBugFlexLayout

Screenshot of the correct layout in Xamarin.Forms:
![MauiBugFlexAndroidXamarin](https://user-images.githubusercontent.com/24872113/193984021-4f8f794d-50a4-463f-8eac-235b67d8c36f.png)

Screenshot of the incorrect layout in MAUI:
![MauiBugFlexAndroid](https://user-images.githubusercontent.com/24872113/193984045-b6051f2c-d86b-4d49-9c49-c9d42b1f037c.png)

**Comment by raylight75** [comment]
Same here not working flex out even with simple List collection

**Comment by jknaudt21** [comment]
Hitting a similar issue with using a Bindable layout in tandem with flex-layout. Creating a `<FlexLayout  BindableLayout.ItemsSource="{Binding SomeItems}"> .... `  breaks. 

Running this code will break on Windows and not do anything on Android. It seems this is a somewhat known issue? The tutorials also have commented out similar code: https://github.com/dotnet/maui-samples/blob/main/6.0/UserInterface/Layouts/BindableLayoutDemos/BindableLayoutDemos/Views/UserProfilePage.xaml#L136-L140

**Comment by chrisparnin** [comment]
Same issue. Only happens when setting ListView with DataSource. Workaround to set width/height posted in https://github.com/dotnet/maui/issues/9905, works, which suggests related layout issue.

```xaml
    <FlexLayout
        Direction="Column"
        JustifyContent="SpaceBetween"
        >
        <StackLayout>
            <Label
                BackgroundColor="DarkOrange"
                HeightRequest="10"
            >
                
            </Label>
            <Image Margin="5"
               Source="./dotnet_bot_presenting.png"
               HeightRequest="140" />
            <Label>History</Label>
            <ListView x:Name="Colors" ItemsSource="{x:Static local:NamedColor.All}">
            </ListView>
        </StackLayout>
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 4.0. Not repro on android platform with sample project.
[Repo](https://github.com/LeanTolo/BugFlexLayoutMAUI)
