### ISSUE TITLE
MAUI iOS doesn't work on EFCore 7

### ISSUE THREAD

**Issue by RobertoGFilho** [dotnet/maui#9550]
### Description

EfCore 7 crash on iOS MAUI app. Please you can reproduce this erro on this demo : https://github.com/RobertoGFilho/EFCore

Windows ok
Android ok
iOS crash
![image](https://user-images.githubusercontent.com/68563526/185655260-e89dd020-9def-437a-bb08-32fcc2152f20.png)

Visual studio 17.3.1
Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.0-preview.7.22376.2"

https://user-images.githubusercontent.com/68563526/185655688-1293d2e2-b81e-4be1-b345-4b1e2649dc7f.mp4

### Steps to Reproduce

EfCore 7 crash on iOS MAUI app. Please you can reproduce this erro on this demo : https://github.com/RobertoGFilho/EFCore

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by RobertoGFilho** [comment]
hi folks! 
the trouble is string properties on Model! see:

WORKS:

public class Person : ObservableObject
{
	[Key]
	public Guid Id { get; set; }
	public int Age { get; set; }	
	//public string Name { get; set; }
}

DOESN'T WORK

public class Person : ObservableObject
{
	[Key]
	public Guid Id { get; set; }
	public int Age { get; set; }	
	public string Name { get; set; }
}

**Comment by RobertoGFilho** [comment]
Hi @jsuarezruiz 

I have envolved EFCore team see :  https://github.com/dotnet/efcore/issues/28773  on this issue! Maybe you can share your opinion, about this

**Comment by jfversluis** [comment]
Looks like this is an issue in iOS and moved here: https://github.com/xamarin/xamarin-macios/issues/16228

Please track it there for the latest info.
