### ISSUE TITLE
Cannot set Editor Text Using MVVM

### ISSUE THREAD

**Issue by nabond251** [dotnet/maui#9556]
### Description

**Expected behavior**

I can enter text in the `Editor`; see the text as I enter it, with the cursor at the end where text is still being inserted; move the cursor around in it.

**Actual behavior**

I can enter text in the `Editor`.  However, I can only see a single character at a time, the last character, so 't', 'e', 's', and 't'.  The text is all there, e.g. I can backspace and see 's' again.  I cannot drag the cursor to previous portions of the text.  The cursor is always at the beginning of the editor, just before the single visible character.

**Potentially related issues**

#5401, #5803

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add an empty `<Editor />` to MainPage's `VerticalStackLayout`
3. Run the app and enter text; can only see last character

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

I have an app where I try doing MVVM data binding on the `Editor`'s `Text` property.  When the containing page initializes, the text is cleared; specifically, set to `string.Empty`.  If I hit the power button to black out the screen, then unlock the device so that the screen reinitializes and try typing again, the editor works as expected.  Not sure how relevant this is, or if something else is causing it to work.  The simple repro app described above does not exhibit this workaround, but I am not setting the text to the empty string.

### Relevant log output

```shell
[InputMethodManager] startInputInner - Id : 0
[InputMethodManager] startInputInner - mService.startInputOrWindowGainedFocus
[CompatibilityChangeReporter] Compat change id reported: 163400105; UID 10466; state: DISABLED
[IMM_LC] showSoftInput(View,I)
[IMM_LC] ssi() - flag : 0 view : com.companyname.editortest reason = SHOW_SOFT_INPUT
[Editor] waiting for the right moment
[InsetsController] show(ime(), fromIme=true)
[InsetsSourceConsumer] setRequestedVisible: visible=true, type=19, host=com.companyname.editortest/crc64e5ae10f0379c2efe.MainActivity, from=android.view.InsetsSourceConsumer.show:246 android.view.InsetsController.showDirectly:1489 android.view.InsetsController.controlAnimationUnchecked:1137 android.view.InsetsController.applyAnimation:1456 android.view.InsetsController.applyAnimation:1437 android.view.InsetsController.show:976 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6478 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6403 android.os.Handler.dispatchMessage:106 android.os.Looper.loopOnce:226
```

**Comment by kurtnapolitano** [comment]
I too have been able to reproduce this with just `<Editor />`.  I think the issue is that by default the editor has a width of like 0 and only expands to fit a single character.  When I add a `WidthRequest` of any value, I get an editor I am able to enter text into and work with.
