### ISSUE TITLE
[Tracking] Consider renaming "💡help wanted" and "💡good first issue" labels

### ISSUE THREAD

**Issue by mairaw** [dotnet/maui#9559]
Using the default label names without the lamp is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496

You should also consider adding the project to https://up-for-grabs.net/

/cc @danmoseley

**Comment by danmoseley** [comment]
example of the latter - open a PR to add a file like the one this is editing https://github.com/up-for-grabs/up-for-grabs.net/pull/3320

cc @Eilon fyi

**Comment by mattleibow** [comment]
Done! and Doner!
