### ISSUE TITLE
App.Close | App.Terminate | App.Restart

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#9562]
### Description

Hi,

Many times we want to close the app, terminate it or restart it, whatever word you will use. This means either kill the application or just minimizing it.

### Public API Changes

`App.Close()
`
or

`App.Terminate()`

or 

`App.Restart()
`

### Intended Use-Case

For example when the does not have an internet connection and you want to prompt the user to either try again or close the app. Also when you update something in the app or the user profile and you want him to restart the app so you can provide a button that will restart the app by closing and starting it again.

**Comment by JohnHSE** [comment]
This isn't allowed at the OS level, at least not on iOS.

**Comment by mattleibow** [comment]
We already have this feature for with `Application.Quit()` and this is implemented here: https://github.com/dotnet/maui/pull/2653/files#diff-a69be2286aad70ff56feb239b524203162d394b935d8f74595efd4a7865c6702

However, as @JohnHSE comments, this is not supported on iOS. You can however, write your own handler command for the ApplicationHandler to catch this on iOS and try use some of the "crash to close" mechanisms.
