### ISSUE TITLE
FlexLayout AlignContent SpaceAround

### ISSUE THREAD

**Issue by sacdevops** [dotnet/maui#9569]
### Description

IntelliSense completion is incorrect. For the FlexLayout AlignContent, "SpaceAroun" is displayed as a suggestion instead of "SpaceAround".

### Steps to Reproduce

Write <FlexLayout AlignContent="..">

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly), I was *not* able test on other platforms

### Affected platform versions

All

**Comment by mattleibow** [comment]
Thanks for this issue, it has been fixed in #8983
