### ISSUE TITLE
Publish MAUI Project with reference iOS

### ISSUE THREAD

**Issue by zuzannaczaja** [dotnet/maui#9576]
### Description

I have problem with publish app on iOS platform. I have project with references and when I try publish app it doesn't consider the main project, only the reference. I don't know if this is a bug.

### Steps to Reproduce

Try publish project with references or clone
https://github.com/zuzannaczaja/BugPublishiOSApp

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

**Comment by zuzannaczaja** [comment]
Example project
https://github.com/zuzannaczaja/BugPublishiOSApp

**Comment by jfversluis** [comment]
Could you please explain a bit more about what you are trying to do exactly? What commands are you running? What output do you see? What are the error messages you receive and what do you expect to see happening?

**Comment by zuzannaczaja** [comment]
> Could you please explain a bit more about what you are trying to do exactly? What commands are you running? What output do you see? What are the error messages you receive and what do you expect to see happening?

I use command:
dotnet publish -f:net6.0-ios -c:Release /p:ServerAddress=192.168.8.145 /p:ServerUser=X /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/X/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:EnableAssemblyILStripping=false

And I get:
![image](https://user-images.githubusercontent.com/56079308/186335870-aacfbdb2-cd53-4a90-a136-977c2080cbe8.png)
