### ISSUE TITLE
[Windows] HTML select options are not properly displayed in WebView

### ISSUE THREAD

**Issue by MichaelMelena** [dotnet/maui#9579]
### Description

HTML select option are not rendered properly in BlazorWebView when targeting and running on windows. You can see it on the following image:

![image](https://user-images.githubusercontent.com/24386972/185926191-59173eb6-d11b-4fa5-af09-2b29b65b43a2.png)

I have tested this and it doesn't happen for Android, IOs  and Mac Catalyst.

[Reproduction project](https://github.com/MichaelMelena/MauiSelectIssueRepro)

**OS**: Windows
**IDE**: Visual Studio 2022 preview 17.4.0 preview 1.0
**SDK**: .NET 6.0.400
**Template used**: dotnet new maui-blazor
**Target**: net6.0-windows10.0.190410

### Steps to Reproduce

* target Windows
* run the reproduction project
* try selecting the value from the HTML select

## alternatively
* use .NET MUI Blazor App template
* add following HTML to the bottom of the page
```
<select>
  <option value="1">AAAAAAAAAAAAAAAAAA</option>
  <option value="2">BBBBBBBBBBBBBBBBBB</option>
  <option value="3">CCCCCCCCCCCCCCCCCC</option>
</select>
```
* target windows
* run the project
* try selecting the value from the HTML select

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Microsoft.Windows.SDK.NET 10.0.19041.24

**Comment by TanayParikh** [comment]
@MichaelMelena thanks for creating this issue. Can you kindly confirm if you're able to reproduce this issue on a base WebView (without Blazor)?

**Comment by MichaelMelena** [comment]
> @MichaelMelena thanks for creating this issue. Can you kindly confirm if you're able to reproduce this issue on a base WebView (without Blazor)?

Yes I am able to reproduce this issue on base MAUI WebView

![image](https://user-images.githubusercontent.com/24386972/186343017-ed136e06-4004-4299-a89d-2db0f5d557d0.png)


Here is a [repro project](https://github.com/MichaelMelena/MauiSelectIssueReproWebView)

Steps:
- Target Windows
- Run the Project
- Try to select different value in HTML select

**Comment by TanayParikh** [comment]
Got it, so this is either an issue with MAUI's WebView, or more likely a bug in the underlying `CoreWebView2`. Added the webview label for visibility.

**Comment by Eilon** [comment]
This is an issue with the WebView2 control that is used by MAUI. Please use this issue for tracking:

* https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290

**Comment by TomOeser** [comment]
So far, my experience is that this problem occurs on all different platforms that use Webview2.

No matter if C#/.Net or Rust (Tauri) or Python or[...] is used. The problem is therefore not limited to MAUI but a general problem of Webview2.

In the end everyone is forced to develop his own dropdown solution or to use third party software. If you consider that this is a standard control and also consider the length of time this problem has been known - then you really have to doubt if the problem will be addressed in the foreseeable future, or just taken for granted.

**Comment by Eilon** [comment]
@TomOeser if you haven't done so, please add an up-vote to the main issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290

Teams use the number of votes to help determine the priority of issues.

**Comment by Eilon** [comment]
Hi, for anyone running into this issue, we think we found a _workaround_, which should help you with your existing apps. Please read this comment for how to work around this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2290#issuecomment-1254273563
