### ISSUE TITLE
[iOS] Type x:String not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml

### ISSUE THREAD

**Issue by NiladriPadhy** [dotnet/maui#9580]
### Description

iOS App causing exception while running the app in physical device. Working fine in iOS simulator.

Tried all the work arounds mentioned in below link.
https://github.com/dotnet/maui/issues/6070

Updated Visual Studio Mac 17.4 Preview and Updated Xcode Version to 13.4.1.

### Steps to Reproduce

Add a string static resoruce into App.xaml file.
 <x:String x:Key="FaceID">face.png</x:String>

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No work around working.

**Comment by jfversluis** [comment]
Duplicate of #6070
