### ISSUE TITLE
IsEnabled currently doesn't do anything when set on a ContextMenu

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9583]
### Description

If you set `IsEnabled` to `false` on any of the `Flyout` items inside  `ContextMenu` it currently doesn't do anything.

**Comment by vmusasia10g** [comment]
Notes to add to this behavior -- 
If disabled item is on a sub-menu:

- visually no different than an enabled menu item
- still clickable (although action is not executed)
- checkmark appears on the item when re-navigating to it

**Comment by jsuarezruiz** [comment]
Is this already fixed or something is pending @PureWeen?
![contextflyout-isenabled](https://user-images.githubusercontent.com/6755973/215453749-e81228e9-8853-488b-9602-2a0e8af5d926.gif)

**Comment by Redth** [comment]
This does appear to work on Windows if you manually toggle the IsEnabled property, though as a data binding, it does not seem to work.

**Comment by Redth** [comment]
MacCatalyst does not support the IsEnabled property at all.  We should focus on the PR @jsuarezruiz started soon.
