### ISSUE TITLE
VerticalStackLayout Spacing with hidden children

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#9586]
### Discussed in https://github.com/dotnet/maui/discussions/9585

The `MeasureSpacing` method in the `StackLayoutManager` class is not excluding invisible (collapsed) items when calculating the spacing. So the measurements for VerticalStackLayout and HorizontalStackLayout are returning incorrect values.

**Comment by josh-aw** [comment]
I noticed the same thing occurring with grid column/row spacing
