### ISSUE TITLE
GraphicsView does not call Drawable's Draw() after each Invalidate on iOS

### ISSUE THREAD

**Issue by maiiaKey** [dotnet/maui#9595]
### Description

We are creating a custom Signature Pad control in Maui using GraphicsView as a basis and then we need to consume this control in native .Net6 iOS, Android and Windows projects. 
Since we want to display the stroke as soon as user draws it, we are calling GraphicsView.Invalidate() method each 50ms.

### Observed behavior:
Android and Windows works as designed: the stroke appears as soon as user draws it
However on iOS the stroke only appears after the user ends the touch. 

### Expected behavior:
The control works the same way on iOS as on Windows and Android.

### Steps to Reproduce

Attaching a repro sample (contains a Maui library project and 3 native app projects)
[SignaturePadIos.zip](https://github.com/dotnet/maui/files/9400161/SignaturePadIos.zip)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by WebGoose** [comment]
I am having a similar issue (although I swear it worked a month ago). I have a few graphicsviews in my app and only about 75% of them now call the draw method on Invalidate in iOS, so some controls just don't draw at all. 

The controls work perfectly in Android and call Draw just fine.

**Comment by Dokug** [comment]
I have a similar issue, where an IDrawable is supposed to be refreshed constantly with a timer:
`
		var timer = new System.Timers.Timer(50);
		timer.Elapsed += new System.Timers.ElapsedEventHandler(UpdateDrawable);
		timer.Start();
`
`
//UpdateDrawable just sets a view values and invalidates the drawable
private void UpdateDrawable(object? sender, EventArgs e)
{
    //[...]
    DisplayView.Invalidate(); //DisplayView is of type GraphicsView
}
`

On Windows this works as expected and well, on iOS this only works if `UpdateDrawable()` is called from a Button or any other "finished" UI interaction.

**Comment by danielancines** [comment]
I'm having the same issue here, all my Handlers stop working and was working last month. 😢 
VS 2022 Community - 17.4.2 and 17.4.1
.NET 7.0.100

**Comment by rdessart** [comment]
You need to invoke a dispatcher into your ElapsedEvent:
```csharp
Application.Current.MainPage.Dispatcher.Dispatch(() =>
{
    DisplayView.Invalidate();
});
```
To force the `Invalidate` call to be called on the UI Thread

**Comment by jfversluis** [comment]
Unless I'm mistaken this looks resolved. Its a bit older by now too without too much movement. If someone else encounters something like this and feels like something is wrong here, please open something new!
