### ISSUE TITLE
Label with TextType=Html crash when set & to Text property.

### ISSUE THREAD

**Issue by higty** [dotnet/maui#9596]
### Description

Label with TextType=Html crash when set "&" to Text property via binding.

### Steps to Reproduce

Reproduction step
MyPage.Xaml
<Label TextType="Html" Text="{Binding MyText"></Label>
MyPageViewModel.cs
public class MyPageViewModel
{
    public string MyText { get; set; } = "&";
}
Maui crash on loading.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

NET6.0

**Comment by jsuarezruiz** [comment]
Cannot reproduce the crash. 
![image](https://user-images.githubusercontent.com/6755973/186110698-cc058a79-e040-498b-9184-c8212cdb3b96.png)

Could you attach a small sample where reproduce the problem?. Thanks in advance.

**Comment by higty** [comment]
[MauiApp2.zip](https://github.com/dotnet/maui/files/9401594/MauiApp2.zip)
Hi.
This is the project files that reproduce crash.
Open solution file and press F5, that will not launch.

Additionally, My PC is Japanese Environment. Language is Japanese.

regards.

**Comment by hartez** [comment]
@higty When using TextType.Html, the text you set must be valid HTML or the underlying engine will throw an exception when trying to parse it. "&" by itself is not valid HTML, because "&" is used to escape other characters in HTML (https://html.spec.whatwg.org/multipage/syntax.html#character-references). 

So if you want to display a single "&" in an HTML Label, you'll need to do something like this:

```
public string MyText { get; set; } = "&amp;";
```

**Comment by higty** [comment]
Oh.I'm really sorry about that I was completely miunderstood and I took your time.

**Comment by higty** [comment]
I propose some suggestion.
The application crashed without any information in my case. So, I could not notice the reason.
If it shows some exception message like "Label with TextType is Html must be set valid html.", it looks good.

regards.

**Comment by hartez** [comment]
> @hartez Oh.I'm really sorry about that I was completely miunderstood and I took your time.

No worries - just glad I was able to clear it up. And you're right - it should have a better error message.
