### ISSUE TITLE
Problem with object on Android platform

### ISSUE THREAD

**Issue by zuzannaczaja** [dotnet/maui#9601]
### Description

I have problem with object on Android platform:

![image](https://user-images.githubusercontent.com/56079308/186146129-cfa1f2a9-5bb2-4df1-a2f9-133ae9b2a61f.png)

On Windows platform and iOS platform is ok:

![image](https://user-images.githubusercontent.com/56079308/186146065-4371dbcd-a43f-4f39-a44a-8a48a0d619b9.png)

### Steps to Reproduce

Clone this repo and check _service value on MainViewModel during debug
https://github.com/zuzannaczaja/BugRefreshUIAndroidMAUI

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, Android 11

**Comment by jfversluis** [comment]
Thank you for the report! I'm not really sure what the problem is exactly? I definitely do see the difference in how things are shown, but is there actually something not working or what is the actual problem that you run into with this?

**Comment by zuzannaczaja** [comment]
> Thank you for the report! I'm not really sure what the problem is exactly? I definitely do see the difference in how things are shown, but is there actually something not working or what is the actual problem that you run into with this?

Maybe I added wrong example. (I updated my code)

On Android platform:
![image](https://user-images.githubusercontent.com/56079308/186334410-c13cde6a-f924-428d-99fc-06a0cfcf6329.png)

On Windows and iOS platform:
![image](https://user-images.githubusercontent.com/56079308/186334589-8c99eea9-a56b-4e51-9be2-4a292c16f542.png)

This objects are different so I have problem and I have bugs, because on Windows and iOS my app works, but on Android doesn't.

**Comment by DoubleDBE** [comment]
Is it because "Non-public members" is not visible on Windows and Android?

**Comment by zuzannaczaja** [comment]
> Is it because "Non-public members" is not visible on Windows and iOS?

Yes, for example when I try send object to api and on Android doesn't work.

![image](https://user-images.githubusercontent.com/56079308/186584604-5d60b213-530b-4600-86fe-763afee5a18a.png)

**Comment by mattleibow** [comment]
Is the code up to date on your GitHub repro? I do not see the code you are showing in the screenshots.

Also, when the debugger is attached, what is the value of `obj`?

**Comment by zuzannaczaja** [comment]
I found my problem. Now it's ok. This was my fault ;)
