### ISSUE TITLE
resource raw/ca (aka com.companyname.gestorordenadores.client.maui:raw/ca) not found

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/maui#9602]
### Description

I am trying to set the network security config, so I created the network_security_config.xml file that i place it in platforms/android/resources/xml.

The content of this file is:

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <domain-config>
    <trust-anchors>
      <certificates src="@raw/ca"/>
    </trust-anchors>
  </domain-config>
</network-security-config>
```

I have edit the manifest file androidmanifest.xml to add the parameter android:networkSecurityConfig="@xml/network_security_config".

I have added the ca.crt certificate in the folder [mauiproject]raw/ca.crt. In the properties, I set it as MauiResource and no copy.

But when I build the project I get the error: resource raw/ca (aka com.companyname.gestorordenadores.client.maui:raw/ca) not found.

How could I solve the problem?

Thanks.

### Steps to Reproduce

1.- Create a MAUI project
2.- Add the config file in xml subfolder
3.- add the certificate ca in the raw folder of the MAUI project

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

android

**Comment by jfversluis** [comment]
If you place it in the `Raw` folder you shouldn't have to set any build action for it, it should handle that automatically for you. If it needs to be anything I think it should be a MauiAsset or a AndroidResource. Also double-check in your csproj if no weird entries are added to that.

Does that help anything?

**Comment by ComptonAlvaro** [comment]
I have edited the .csproj and delete all entries that are for certificates, in both, MAUI and plantform/android, clean the project and build the solution again.

Finally it works.

I confirm that the ca has to be in the folder platform/android/resources/raw.

So finally I could solve  the problem.


Thanks so much.

**Comment by PureWeen** [comment]
@davidbritch FYI if you want to make a note for docs
