### ISSUE TITLE
[Windows] project path containing substed drives causes DEP0700 (AppxManifest.xml not found) during launch of desktop app - android is OK

### ISSUE THREAD

**Issue by apws** [dotnet/maui#9611]
### Description

I have updated VS2022 to 17.4 Preview 1.0 and created new empty MAUI or Blazor app. With deployment to Android Emulator, it builds and launches, but after switching to Windows Machine and rebuild, there is error at launch.

DEP0700: Registration of the app failed. [0x80073CF0] error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified.

ROOT CAUSE - project created/accesed from substed drive letter:

"c:\~prj\220823 netmaui-app-helloworld" - OK
c:\~prj\220823-netmaui-app-helloworld - OK
"w:\~prj\220823 netmaui-app-helloworld" - FAILS (onedrive)
w:\~prj\220823-netmaui-app-helloworld - FAILS (onedrive)
v:\~prj\220823-netmaui-app-helloworld - FAILS

Visual Subst is this: https://www.ntwind.com/software/visual-subst.html

### Steps to Reproduce

File New Project MAUI or Blazor app - no user changes, just default project
(my folder isnt much long path, is on mapped/substed letter drive inside user profile documents, folder name contains space)

Rebuild - succeeds

Start Debugging (Windows Machine) - deployment errors:

"DEP0700: Registration of the app failed. [0x80073CF0] error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified."

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net60 win 19041.0

### Did you find any workaround?

"c:\~prj\220823 netmaui-app-helloworld" - OK
c:\~prj\220823-netmaui-app-helloworld - OK

**Comment by MagicAndre1981** [comment]
> DEP0700: Registration of the app failed. [0x80073CF0] error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified.
> 
> ### Steps to Reproduce
> File New Project MAUI app - no user changes, just default project (my folder isnt much long path, is on **mapped letter drive** inside user profile documents, folder name contains space)

I doubt that this is supported in UWP/WinUI. Use something like C:\source\MyMAUIApp\ to store the code or run app unpacked  (add `<WindowsPackageType>None</WindowsPackageType>` to csproj)

**Comment by apws** [comment]
Thanks @MagicAndre1981, you were right, the W:\ drive I have mapped using "Visual Subst" was the problem. But thats not good. I heavily RELY on the substed drives for years and none of maybe hundred of apps I have on machine had issue with using the substed drives (of course those who store data on it). I use several letters to easy access from Total Commander, say W: is subst for onedrive synced \Documents, O:\ as onedrive root and I have also V:\ outside onedrive for versioned folders on github, but this dont work either (I use often W:\~prj\ for project files to be backed up by onedrive, X:\ for web downloads (no onedrive), and V:\~prj\ for source code, but the SUBSTED LETTER here IS problem for NET MAUI project till now). Space in project path isnt problem, nor tilda, but the substed letter IS. I think that in other VS projects this dont happen, and for YEARS, it was not problem with ANY application I use for editing documents or project folders on onedrive backed W:\ - that Visual Subst simply "just works" perfectly, it handles also UAC or so.

And so I really consider this as major BUG, because simply all my project reside this way on W:\ or V:\ for maintaining some clutter-free environment (and short paths without spaces) on my computer, at least ... physically its far worse situation ))

So to sumarize what works and what dont work:

"c:\\~prj\220823 netmaui-app-helloworld"  - OK
c:\\~prj\220823-netmaui-app-helloworld  - OK
"w:\\~prj\220823 netmaui-app-helloworld"  - FAILS (onedrive)
w:\\~prj\220823-netmaui-app-helloworld  - FAILS (onedrive)
v:\\~prj\220823-netmaui-app-helloworld  - FAILS

Visual Subst is this: https://www.ntwind.com/software/visual-subst.html

**Comment by MagicAndre1981** [comment]
ok, in project settings you can select the `output folder` to be like `C:\MyMAUIApp\bin,` here the register could work.

**Comment by apws** [comment]
umm, you think that it is something not easy to solve? but thanks for tip

**Comment by MagicAndre1981** [comment]
no. Try the unpacked app or put output dir on C:\ that are the only 2 things that come to my mind on how to workaround this.

**Comment by apws** [comment]
okay tnx, its possible to live with that. I just added info that the same behavior is with Blazor win desktop app.

**Comment by apws** [comment]
okay, reported, but I also found 3 years old similar issue related to UWP apps, no reactions, nothing, pls escalate, its shame
https://developercommunity.visualstudio.com/t/Build-Succeeds-But-UWP-App-Wont-Deploy/167710?entry=problem&ref=native&refTime=1661489025909&refUserId=ecb74aa0-31ba-4822-987f-e19441c8573b

**Comment by MagicAndre1981** [comment]
this is a WinRT/UWP/WinUI limitation and no real VS issue, but the error handling could be improved to show users a better message that running apps from mapped drives is unsupported.
