### ISSUE TITLE
OpenGLView is not available

### ISSUE THREAD

**Issue by qian-o** [dotnet/maui#9623]
### Description

引发的异常:“System.ArgumentException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“Microsoft.Maui.Controls.Xaml.XamlParseException”(位于 Microsoft.Maui.Controls.Xaml.dll 中)

### Steps to Reproduce

1. Add OpenGLView to Xaml
![image](https://user-images.githubusercontent.com/84434846/186339588-5a71a055-1e13-4923-8587-8cfdb0b7fc0a.png)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

Android11 win11

**Comment by PureWeen** [comment]
The OpenGLView wasn't ported over to .NET MAUI

The renderers are still part of the compatibility projects so you can try `UseMauiCompatibility` but the OpenGLView isn't currently a supported view

**Comment by PureWeen** [comment]
@qian-o what are you hoping to use the OpenGLView for?

**Comment by qian-o** [comment]
> @qian-o what are you hoping to use the OpenGLView for?

I plan to render videos with OpenGLView in the future
SkiaSharp is currently used to do this, but it doesn't work well at 4k resolution

**Comment by jfversluis** [comment]
OpenGL has been deprecated and even now removed for .NET 8. We won't be supporting it anymore, so if you still need it you might want to look for an alternative.
