### ISSUE TITLE
[Bug] Wrap UserControl (which Contains a WrapLayout) inside StackLayout raises Exception

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/maui#9624]
### Description

We tried to make a reusable ChipGroup user control. Inside the user control, we use FlexLayout to hold the data list in a multiline style. When we reuse the user control inside a StackLayout, exception is raised.

Changing the enclosing StackLayout to Grid  or  changing the FlexLayout to StackLayout, the exception disappeared. Weird.

Note: this situation doesn't exist back in Xamarin.

Demo project attached here:
[MaApp.zip](https://github.com/dotnet/maui/files/9413380/MaApp.zip)

Thanks.

### Steps to Reproduce

Please check the attached demo project.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.22000

### Did you find any workaround?

We need to wrap the content with FlexLayout, maybe use other controls which could be wrapped.

**Comment by PureWeen** [comment]
@SunshineSpring666 is this the same exception you are seeing?

https://github.com/dotnet/maui/issues/9075
