### ISSUE TITLE
Fail to install MAUI from main branch with error "microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64::6.0.9 is not found in NuGet feeds"

### ISSUE THREAD

**Issue by cptbtptpg** [dotnet/maui#9625]
### Description

After installing the .NET 6.0 SDK, fails to install MAUI from main branch with the following error:

`Workload installation failed: One or more errors occurred. (microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64::6.0.9 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-6bb76b3f/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://api.nuget.org/v3/index.json".)`

### Steps to Reproduce

1. Install the .NET 6.0 SDK
2. Run open up a Windows PowerShell (run as administrator)
3. Execute the below command from the [script ](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md)to install the maui workload
```
dotnet workload install maui `
  --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-6bb76b3f/nuget/v3/index.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json `
  --source https://api.nuget.org/v3/index.json
```
4. The error is as shown below：
![image](https://user-images.githubusercontent.com/76163330/186376609-d0dc8de5-8351-42ae-b424-41ed64ebb31e.png)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 6.0.400

### Did you find any workaround?

No

### Relevant log output

```shell
PS C:\Windows\system32> dotnet workload install  --sdk-version 6.0.400 maui --skip-sign-check `
>>   --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-6bb76b3f/nuget/v3/index.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json `
>>   --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json `
>>   --source https://api.nuget.org/v3/index.json

Skipping NuGet package signature verification.
Failed to update the advertising manifest microsoft.net.sdk.ios: Failed to extract information from MSI: C:\Users\v-yingfw\AppData\Local\Temp\e42ea3c8-d53b-4d1f-bf7a-9aca0028dbb4\data\Microsoft.NET.Sdk.iOS.Manifest-6.0.400.15.4.447-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.android: Failed to extract information from MSI: C:\Users\v-yingfw\AppData\Local\Temp\df65cfcf-c99a-41f3-9098-a98a286da6be\data\Microsoft.NET.Sdk.Android.Manifest-6.0.400.32.0.461-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.maui: Failed to extract information from MSI: C:\Users\v-yingfw\AppData\Local\Temp\c1ab4a0b-6334-4b89-943e-82d3f6eff8ea\data\Microsoft.NET.Sdk.Maui.Manifest-6.0.400.6.0.509-x64.msi.
Failed to update the advertising manifest microsoft.net.workload.emscripten: Failed to extract information from MSI: C:\Users\v-yingfw\AppData\Local\Temp\d446926d-2e4e-4bda-9f47-ca7b636ceef7\data\Microsoft.NET.Workload.Emscripten.Manifest-6.0.400.6.0.8-x64.msi.
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Failed to extract information from MSI: C:\Users\v-yingfw\AppData\Local\Temp\ae60148c-4fce-477d-83ef-86a1f52abb2c\data\Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.15.4.447-x64.msi.
Installing Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.9-x64.msi ..... Done
Downloading microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64 (6.0.9)
Workload installation failed. Rolling back installed packs...
Installing Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.5-x64.msi .... Done
Workload installation failed: One or more errors occurred. (microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64::6.0.9 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-6bb76b3f/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://api.nuget.org/v3/index.json".)
```
```

**Comment by jfversluis** [comment]
The command that you use is different from the one in our development guide. What happens without the `--sdk-version 6.0.400`? Also it seems like it's trying to get 6.0.300? What is the output of `dotnet --list-sdks` and `dotnet --version`?

@mattleibow ?

**Comment by cptbtptpg** [comment]
> The command that you use is different from the one in our development guide. What happens without the `--sdk-version 6.0.400`? Also it seems like it's trying to get 6.0.300? What is the output of `dotnet --list-sdks` and `dotnet --version`?
> 

@jfversluis Thanks for your reply.
1. There are same errors when execute the command without the `--sdk-version 6.0.400`
![image](https://user-images.githubusercontent.com/76163330/186555947-a77ec283-7644-47f0-91c2-a041c1b45597.png)
2. The output of `dotnet --list-sdks` and `dotnet --version` is 6.0.400
![image](https://user-images.githubusercontent.com/76163330/186556193-af29bb21-0aa8-48e5-9942-643929f9f9f3.png)

**Comment by mattleibow** [comment]
The feeds had changed from various updates. I have corrected the DEVELOPMENT.md:

```
dotnet workload install maui `
  --skip-sign-check `
  --from-rollback-file https://aka.ms/dotnet/maui/net6.0.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-531f715f/nuget/v3/index.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-3f6c45a2/nuget/v3/index.json `
  --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json `
  --source https://api.nuget.org/v3/index.json
```

**Comment by cptbtptpg** [comment]
Thanks Matthew! I try the updated command, it works well.
