### ISSUE TITLE
Using a custom configuration to publish Android app

### ISSUE THREAD

**Issue by manuelelucchi** [dotnet/maui#9627]
### Description

I'm using a custom defined configuration in the csproj (so no standard Debug/Release but something like "Company Release/Debug Production/Staging" and, when the config is a Debug/Release one I define the following properties
![image](https://user-images.githubusercontent.com/17146198/186390130-922e0530-c03c-418f-99c0-c2171e2e45ad.png)
and of course I defined DEBUG and RELEASE in DefineConstants. But when I publish using this configuration for android using ``dotnet publish -f:net6.0-android -c "Custom Configuration"`` I have no assembly optimization step and it doesn't publish the aab, only apk (even tough I have the android key store properties only when I'm in release and android)
Is there anything missing to fully support anything the default Debug/Release configurations do when building and publishing?

### Steps to Reproduce

1. Create a Maui app
2. Create a custom configuration with alla the above properties
3. Try to publish the aab or just compile in release
4. No aab or optimization phase will happen

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All versions

**Comment by manuelelucchi** [comment]
Update: I managed to force the aab format using ``<AndroidPackageFormat>aab</AndroidPackageFormat>`` but afaik it should be the default while in release and also I still don't have the assemblies optimization

**Comment by PureWeen** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
This file has all the settings for Release mode:

https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

I think you'd want these to match `Release` exactly:
```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'FooRelease' ">
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidPackageFormats>aab;apk</AndroidPackageFormats>
    <PublishTrimmed>true</PublishTrimmed>
    <RunAOTCompilation>true</RunAOTCompilation>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
  </PropertyGroup>
```

There was some talk about making MSBuild have a way to "inherit" configurations to make this easier, but I don't know when/if that feature will come.

**Comment by manuelelucchi** [comment]
thank you! can you please share the same for the debug?

**Comment by jonathanpeppers** [comment]
Debug you could probably leave blank.

But to get hot reload you would need:
```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <UseInterpreter>true</UseInterpreter>
  </PropertyGroup>
```

**Comment by manuelelucchi** [comment]
Is there anything similar for iOS?

**Comment by jonathanpeppers** [comment]
@rolfbjarne could maybe comment about the default values for iOS.

As-is, I don't see anything we can do here outside of some general solution for .NET and MSBuild. Basically we need a way to "inherit" / "extend" configurations, and it seems like something we'd need a general design for.

Closing for now as it isn't something we can really address in .NET MAUI, thanks!
