### ISSUE TITLE
ContentView template has wrong namespace

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#9628]
### Description

ContentView template has wrong namespace

### Steps to Reproduce

1.Create maui app name test.
2. Add content view A you get namespace main1 instead.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

....

### Did you find any workaround?

Change manually the namespace.

### Relevant log output

```shell
Not relavant
```

**Comment by jfversluis** [comment]
Please add more information like are you using Visual Studio on Windows or on Mac? What version of Visual Studio? Do you also see this when you give the project another name than "test"?

**Comment by danies8** [comment]
1. Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0
2.On window.
3.In any project.

**Comment by jfversluis** [comment]
Just confirmed that this is a bug in Visual Studio 17.4 preview 1. Visual Studio 17.3.2, the current stable version works as intended. A ticket on the Visual Studio feedback portal about this is here: https://developercommunity.visualstudio.com/t/Problem-with-adding-new-page-to-project/10118293
