### ISSUE TITLE
[Android] Window overlay is not working with Shell

### ISSUE THREAD

**Issue by VijayakumarMariappan** [dotnet/maui#9646]
### Description

`Window overlay` does not work when the application's base is `Shell`  but works fine with `NavigationPage`.

In sample, I tried to draw a circle in a tapped location, which is worked as expected in `Windows` and `iOS`, but facing issues with `Android`.

[Windows output demo](https://user-images.githubusercontent.com/92971875/186631945-4fcfee30-84e0-46be-81c5-4f9f06309843.mp4)

[Android output demo](https://user-images.githubusercontent.com/92971875/186631964-2651afaa-3b20-4127-ba30-b93d46add042.webm)

### Steps to Reproduce

Attached whole sample here [WindowOverlayWithShell.zip](https://github.com/dotnet/maui/files/9423374/WindowOverlayWithShell.zip)

OR

1. Create a new MAUI project.
2. Replace `MainPage.xaml.cs` with

```
public partial class MainPage : ContentPage
{
    private readonly WindowOverlayElement overlayElement;

    private WindowOverlay overlay;

    public MainPage()
    {
        InitializeComponent();

        overlayElement = new WindowOverlayElement();
    }

    protected override void OnHandlerChanged()
    {
        base.OnHandlerChanged();

        if (Handler != null)
        {
            overlay = new WindowOverlay(Window);

            overlay.AddWindowElement(overlayElement);

            overlay.Tapped += OnOverlayTapped;

            Window.AddOverlay(overlay);
        }
        else
        {
            if (overlay != null)
            {
                overlay.Tapped -= OnOverlayTapped;
            }
        }
    }

    private void OnOverlayTapped(object sender, WindowOverlayTappedEventArgs e)
    {
        overlayElement.TapPosition = e.Point;

        overlay.Invalidate();
    }
}

public class WindowOverlayElement : IWindowOverlayElement
{
    private readonly double indicatorSize = 20;

    internal Point TapPosition { get; set; }

    public bool Contains(Point point)
    {
        return true;
    }

    public void Draw(ICanvas canvas, RectF rect)
    {
        canvas.FillColor = Brush.Purple.Color;
        canvas.FillCircle(TapPosition, indicatorSize);
    }
}
```

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All versions

### Did you find any workaround?

No

**Comment by PureWeen** [comment]
Possibly related
https://github.com/dotnet/maui/issues/8866
