### ISSUE TITLE
SQLiteConnection: "System.DllNotFoundException: 'e_sqlite3'"

### ISSUE THREAD

**Issue by adamjhilton** [dotnet/maui#9651]
### Description

I'm migrating our Xamarin Forms app over to MAUI and I'm having an issue with running for Android; running for Windows runs just fine. During runtime I get a "System.DllNotFoundException: 'e_sqlite3'" exception while instantiating a SQLiteConnection object. I've read several other threads that have talked about pulling down half a dozen or so packages from NuGet, but this isn't working. I'm currently including these packages:

```
	<ItemGroup>
	  <PackageReference Include="Simple.Migrations" Version="0.9.21" />
	  <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
	  <PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
	  <PackageReference Include="SQLiteNetExtensions.Async" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.core" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.osx" Version="1.1.14" />
	  <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.0" />
	  <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.0" />
	</ItemGroup>
```

As an aside, in our existing Xamarin app, we were only including sqlite-net-pcl and everything ran just fine. 

```
  <ItemGroup>
    <PackageReference Include="Simple.Migrations" Version="0.9.21" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
  </ItemGroup>
```

I've read to use the asynchronous version (SQLiteAsyncConnection), but SimpleMigrator seems to want a non-asynchronous connection to do its thing.

I have VS2022 up to date and am using the latest stable version of all the packages. My current .NET SDK version is 6.0.400. I noticed in the dropdown on this form below that there is a 6.0.487 version out there but I'm not sure how to get it. It's not posted on the website: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Thoughts? Am I missing more packages? Thanks!

### Steps to Reproduce

Install the above packages and add this code somewhere: 

`SQLiteConnection databaseConnection = new SQLiteConnection(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "registers.db3"));`

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11.0 - API 30

**Comment by adamjhilton** [comment]
I created a test app to see. I'm experiencing the same issues here. 
![image](https://user-images.githubusercontent.com/31253633/186731300-e8cbde41-6113-46b2-aa31-9b8858f34709.png)

So, it looks like the issue is with .NET 6.0 generally. I don't think there's a problem with the "sqlite-net-pcl" package specifically as it works fine in a Xamarin Forms app. I assume over here: https://github.com/dotnet/core/issues

**Comment by PureWeen** [comment]
Can you create an issue at the sqlite repository? https://github.com/ericsink/SQLitePCL.raw

**Comment by adamjhilton** [comment]
I found a duplicate issue already on SQLitePCL's forum. I jumped on that one. Here if anyone is interested: https://github.com/ericsink/SQLitePCL.raw/issues/499
