### ISSUE TITLE
Binding to hexColor doesn't work.

### ISSUE THREAD

**Issue by prok155** [dotnet/maui#9662]
### Description

When I bind BackgroundColor of a button to hexColor in my ViewModel the app throws exception  `'Invalid cast from 'System.String' to 'Microsoft.Maui.Graphics.Color'.'` When I set BackgroundColor like this `<Button BackgroundColor="#fc87ad"/>` it works, but it doesnt work with a viewmodel.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add button with BackgroundColor binding like this `<Button BackgroundColor="{Binding BackgroundButt}"/>`
3. Create ViewModel with `BackgroundButt` property:

 ```c#
    public class MyViewModel : INotifyPropertyChanged
    {
        public string BackgroundButt
        {
            get
            {
                return "#fc87ad";
            }
        }
       public event PropertyChangedEventHandler PropertyChanged;

       protected void OnPropertyChanged(string name)`
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null)
            {
                handler(this, new PropertyChangedEventArgs(name));
            }
        }

    }
```

4. Add ViewModel to your page. The app throws exception `'Invalid cast from 'System.String' to 'Microsoft.Maui.Graphics.Color'.'
` 

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

**Comment by AndreasReitberger** [comment]
Can you try following example?

```cs
public class MyViewModel : INotifyPropertyChanged
   {
       public Color BackgroundButt
       {
           get
           {
               //return "#fc87ad";
               return  new Color("#fc87ad");
           }
       }
      public event PropertyChangedEventHandler PropertyChanged;

      protected void OnPropertyChanged(string name)`
       {
           PropertyChangedEventHandler handler = PropertyChanged;
           if (handler != null)
           {
               handler(this, new PropertyChangedEventArgs(name));
           }
       }

   }
```

or if you want to pass a `string` (this is how I do it in my apps)

```xaml
BackgroundColor="{Binding HexCode, Converter={StaticResource StringToColorConverter}, Mode=OneWay}"
```
```cs
public class StringToColorConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            Color color = Color.Accent;
            if (value is not string str || string.IsNullOrEmpty(str))
            {
                return color;
            }

            try
            {
                color = Color.FromHex(str[0] != '#' ? $"#{str}" : str);
            }
            catch (Exception exc)
            {
                return color;
            }
            return color;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return null;
        }
    }
```

**Comment by prok155** [comment]
Yes, example above works, but it should also work when I pass string instead of color, without any converters. I migrate my app from Xamarin to Maui, in Xamarin evertyhing works when I pass hex as a string.

**Comment by jsuarezruiz** [comment]
This will be possible without require a Converter after merge https://github.com/dotnet/maui/pull/9814

**Comment by prok155** [comment]
Hello! Today I migrated my app from Xamarin to Maui and I also saw that `Color.FromHex()` is obsolete. I used `Color.FromArgb` instead, but in this case I wonder if adding converter which fix this issue is necessary. I guess that in near future `Color.FromHex()` will be removed, so we won't use any hex colors in Maui apps at all and converter will be useless, am I right @jsuarezruiz  ?
