### ISSUE TITLE
Not Rules for Android JAR SDK

### ISSUE THREAD

**Issue by antoniohlopes** [dotnet/maui#9672]
### Description

Hello,
My primary objective in MAUI projects is Android development.
We are developing Android applications that work with Handy terminals. The [manufacturer](https://www.keyence.com/products/mobile-computers/handheld-computers/dx/?ad_local=sitetopslbn1) provided an SDK to access, for example, the barcode reader. 
We would like to use this class library to control the barcode reader.
But there is apparently no way to instantiate this class library.

### Steps to Reproduce

Try to reference a jar file in MAUI Android.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Not yet, but I have checked the issues #1475, #8634
manufacturer sample code:
[BT-A500_INVENTORY_V01_00_00.zip](https://github.com/dotnet/maui/files/9431777/BT-A500_INVENTORY_V01_00_00.zip)
manufacturer SDK - classes.jar as MAUI android Java Library Binding
[classes.zip](https://github.com/dotnet/maui/files/9431798/classes.zip)

### Relevant log output

```shell
No logs
```

**Comment by rachelkang** [comment]
@jonathanpeppers do you have any thoughts here?

**Comment by jonathanpeppers** [comment]
So you probably want to use `dotnet new android-bindinglib` as a starting template:

![image](https://user-images.githubusercontent.com/840039/200662707-7bd2d692-7915-4da9-a12d-cf0443bdfd9e.png)

And then you can actually just drop an `.aar` or `.jar` file in here and build it. See what errors you get?

From there it is the same work you would have done in Xamarin.Android to make a binding project. Some docs on this:

* https://learn.microsoft.com/en-us/xamarin/android/platform/binding-java-library/
* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetBindingProjects.md
* https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md

Do you have a specific/bug, or problem to look into here? Error message?
