### ISSUE TITLE
Infinity loop lifecycle when unfocused from the app between OnDisappearing and OnAppearing

### ISSUE THREAD

**Issue by kevinz33** [dotnet/maui#9688]
### Description

After Visual Studio Update to 17.3.0, the implementation of OnDisappearing and OnAppearing will cause app to enter infinite loop unfocused from the application.
This behavior is not present in previous version of VS preview, this made impossible to dispose objects when page is Disappearing.

### Steps to Reproduce

start VS 2022 and create a new maui project

add folowing code in MainPage.cs

` 
    protected override void OnDisappearing()
    {
        base.OnDisappearing();
    }
`
`
    protected override void OnAppearing()
    {
        base.OnAppearing();
    }
`
put a stop inside either OnAppearing() or OnDisappearing() in VS debug window, the stop point will continue to hit unless the break point is removed,

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.400

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

No workaround

**Comment by AndreasReitberger** [comment]
This behavior is intended. 

- OnAppearing is called and the breakpoint gets hit
- This will bring Visual Studio in the foreground
- This will trigger the OnDisappearing and so on

You can add Debug.WriteLine() instead of the breakpoint. Then you should not see the loop.

**Comment by rachelkang** [comment]
Hi, @kevinz33 - thanks for opening this issue! As @AndreasReitberger, this is intended behavior. Let us know if you have any further questions :)
