### ISSUE TITLE
Top Navigation Menu bar does not show up on MAUIBlazor deployed to iPhone with iOS 15.6

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#9693]
### Description

The top Navigation Menu does not show up on the iPhone 12.
I don't have Mac so cannot test it on emulator.
Works fine on Android Pixel 5 emulator.

![IMG_4211](https://user-images.githubusercontent.com/3267605/186993936-1a1f8fd2-0995-48cb-ab79-786715d907f3.PNG)

### Steps to Reproduce

1. Create new MAUI Blazor App.
2. Pair iPhone 12 device 
3. F5 to run it.
4. Once it is launched you will see the screen where the Top Navigation bar is missing.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.6

### Did you find any workaround?

NO

### Relevant log output

```shell
Screen shot attached
```

**Comment by PBTests** [comment]
Same issue here, I believe it's down to the Component CSS not compiling...

https://github.com/dotnet/maui/issues/9723

**Comment by TanayParikh** [comment]
Thanks @PBTests, this is likely missing https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-blazor/Shared/NavMenu.razor.css as a result of https://github.com/dotnet/maui/issues/9723 / https://github.com/dotnet/maui/issues/7468. Closing this out as a duplicate.
