### ISSUE TITLE
Cannot assign permissions for MAUI app in windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9696]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-assign-permissions-for-MAUI-app-i/10129962)._

---
[severity:I'm unable to use this version]
Create a new .Net Maui App. Then go to the platform folder, then Windows. In the Package.appxmanifest, go to the Capabilities tab. In the capabilities, the list is empty. Therefore, you cannot assign any permission for the app.

---
#### Feedback Bot on 8/24/2022, 07:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Kicked back to vsfeedback for now
