### ISSUE TITLE
maui workloads not installed through visual studio installer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/maui-workloads-not-installed-through-vis/10124913)._

---
[regression] [worked-in:17.4.0 Preview 1.0]
I just updated visual studio and maui workloads aren't there

>error NETSDK1147: To build this project, the following workloads must be installed: maui-android

But Visual Studio 17.4.0 Preview 1.0 says they are installed

![image.png](https://aka.ms/dc/image?name=B45dec1fecb9c47da9835a7360213b84e637964421055009860_20220818-145505-image.png&tid=45dec1fecb9c47da9835a7360213b84e637964421055009860)

---
#### Feedback Bot on 8/18/2022, 07:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Bounced back to vs-feedback
