### ISSUE TITLE
Running a .NET MAUI app from VS that was previously built and run takes a surprisingly long time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9700]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Running-a-NET-MAUI-Blazor-app-from-VS-t/10116421)._

---
Repro steps:

- Create a .NET MAUI app
- Run it on windows
- Run it a 2nd time on Windows without making any changes

Expected result: The 2nd run starts almost immediately

Actual result: The 2nd run takes about 10 to 15sec on my laptop. It appears that VS is rebuilding and redeploying the app.

It seems like a previously built and run .NET MAUI app on Windows should run much faster. When I try the same test with a WPF app subsequent runs take only a second or two. 

---
#### Feedback Bot on 8/10/2022, 11:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment]
This applies to .NET MAUI (non-Blazor) apps as well.

**Comment by PureWeen** [comment]
Moved back to VSFeedback
