### ISSUE TITLE
Switching the MAUI Controls Gallery to RTL causes the currently visible view to not resize correctly

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#9702]
### Description
- run control samples gallery on catalyst
- Change LTR to RTL via the switch
- go back to the main screen
- resize the window
- everything inside the CV cells fly out of the layouts

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio for Mac 17.6.2 (build 414). Not repro on Maccatalyst platform with sample project. [maui-samples/7.0/UserInterface/ControlGallery at main · dotnet/maui-samples (github.com)](https://github.com/dotnet/maui-samples/tree/main/7.0/UserInterface/ControlGallery)
