### ISSUE TITLE
Consuming Component that uses Nuget package in Razor class Library

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#9706]
### Description

I have created Razor Class Library that is using third party Nuget package.
https://github.com/sabitertan/BlazorBarcodeScanner

I now want to consume this library in my MAUIBlazor project.

BlazorBarcodeScanner library requires that I  add the reference to the following script in index.html
```
 <script src="_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js"></script>
 <script src="_content/BlazorBarcodeScanner.ZXing.JS/BlazorBarcodeScanner.js"></script>
```

So in my MAU Blazor project(which is consuming Razor class Library), after adding project reference to the Razor Class Library I tried adding the script reference as shown below but it fails with error "BlazorBarcodeScanner not found"

```
 <script src="_content/RCLLibraryName/zxingjs.index.min.js"></script>
 <script src="_content/RCLLibraryName/BlazorBarcodeScanner.js"></script>
```

What would be correct way to properly reference libraries of Nuget Package that is being used in Razor Class Library

### Steps to Reproduce

1. Create MAU Blazor Project
2. Add new Razor Class Library Project to the solution.
    In this Razor Class Library Add the Nuget Package https://github.com/sabitertan/BlazorBarcodeScanner
    follow the document to add the BarCode scanner.
3. Now Add Project Reference in MAU Blazor Project to the Razor Class Library Project in item 2 above.
4. Now if you run the project for any platform, the MAU Blazor project will crash.
   the error in the logs report that BlazorBarcodeScanner is not found.

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15.6

### Did you find any workaround?

no

### Relevant log output

```shell
BlazorBarcodeScanner was undefiend
```

**Comment by TanayParikh** [comment]
@nssidhu can you please confirm if the browser / webview is able to load the `.js` file?

**Comment by nssidhu** [comment]
I was able to work this out.

When using Nuget Package in the RCL Class library, we just need to reference it as if we are consuming from local project.
No need to use RCL Project Name.

This works
```
<script src="_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js"></script>
 <script src="_content/BlazorBarcodeScanner.ZXing.JS/BlazorBarcodeScanner.js"></script>
```

what I am finding is that RCL project name only needs to be used/reference when creating custom .js & .css file inside RCL Project.
