### ISSUE TITLE
BaseSize on .svg files is not supported

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#9716]
### Description

BaseSize appears to be ignored, its a standard feature of Resizetizer.

### Steps to Reproduce

.NET MAUI project, and a large dimension .SVG to the Resources/Images folder.
Edit the .csproj and update the MauiImage to include BaseSize of 5,5 for example.
Add Image to the page with ImageSource the name of the image file with .png.
Run it, the image is still full resolution.

### Version with bug

6.0.424

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Add .SVG files to any other folder and then you can set the BaseSize and it works. Images added to Resources/Images, if you set the BaseSize in the .csproj it is ignored.

**Comment by F-Goncalves** [comment]
@JohnHDev 
Have you tried removing following line from your .csproj.

`<MauiImage Include="Resources\Images\*" />`

That seems to solve it for me.
