### ISSUE TITLE
Screenshot capture does not work for Blazor MAUI

### ISSUE THREAD

**Issue by Markz878** [dotnet/maui#9718]
### Description

When using Blazor Hybrid MAUI, the MAUI Screenshot function produces a gray image with black top part.
Is this intentional, or should the screenshot work?
![Image](https://user-images.githubusercontent.com/38662394/187062704-eb852a3e-4d39-46b3-8886-f2996a502086.png)
 

### Steps to Reproduce

1. Create new Blazor MAUI app.
2. Change Counter page button handler to this (replace the {name} with your Windows username):
   ```c#
    private async Task IncrementCount()
    {
        currentCount++;
        if (Screenshot.Default.IsCaptureSupported)
        {
            IScreenshotResult screen = await Screenshot.Default.CaptureAsync();
            using FileStream fileStream = new FileStream(Path.Combine(@"C:\Users\{name}\Pictures", "Image.png"), FileMode.Create);
            await screen.CopyToAsync(fileStream, ScreenshotFormat.Png);
        }
    }
    ```

3. Click the button and see the gray image in the given location.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

**Comment by TanayParikh** [comment]
@Markz878 does this happen to work with a non-Blazor default MAUI WebView?

**Comment by Markz878** [comment]
Yes it happens also with default MAUI WebView set to any url.

**Comment by Eilon** [comment]
Hi, this appears to be an issue with WebView2 in WinUI, so I logged this bug: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2799

Please use that bug for tracking, and I'm closing this one as there is no further action in this repo.
