### ISSUE TITLE
The CreatePlatformView is never called?

### ISSUE THREAD

**Issue by FreakyAli** [dotnet/maui#9720]
### Description

So I have been trying out MAUI extensively lately and was trying to Create a Custom Control I guess and I ran into this weird problem, the CreatePlatform method was never getting called, at first I thought this was because I was using a MAUI class library and there was some issue with them, So instead I created another control in the same MAUI project instead of doing it through a CL and to my surprise even then it did not work.

My code is as follows: 

Interface: 

    public interface IExtendedLabel : ILabel
    {
        bool HasUnderline { get; }
        Color UnderlineColor { get; }
    }

Label class: 

    public class ExtendedLabel : Label, IExtendedLabel
	{
        public readonly BindableProperty HasUnderlineProperty = BindableProperty.Create(
            nameof(HasUnderline),
            typeof(bool),
            typeof(ExtendedLabel),
            true);

        public bool HasUnderline
        {
            get => (bool)GetValue(HasUnderlineProperty);
            set => SetValue(HasUnderlineProperty, value);
        }

        public readonly BindableProperty UnderlineColorProperty = BindableProperty.Create(
           nameof(UnderlineColor),
           typeof(Color),
           typeof(ExtendedLabel),
           Colors.Black);

        public Color UnderlineColor
        {
            get => (Color)GetValue(HasUnderlineProperty);
            set => SetValue(HasUnderlineProperty, value);
        }
    }

My shared handler: 

    using System;
    using MAUI.FreakyControls;
    using Microsoft.Maui.Handlers;
    #if ANDROID
    using NativeView = AndroidX.AppCompat.Widget.AppCompatTextView;
    #endif
    #if IOS
    using NativeView = UIKit.UILabel;
    #endif
    namespace Samples
    {
    	public partial class ExtendedLabelHandler : ViewHandler<IExtendedLabel,NativeView>
        {
            #region ctor 
    
            public static CommandMapper<IExtendedLabel, ExtendedLabelHandler> CommandMapper = new(ViewCommandMapper);
    
    
            public ExtendedLabelHandler() : base(FreakyEditorMapper)
            {
    
            }
    
            public ExtendedLabelHandler(IPropertyMapper mapper = null) : base(mapper ?? FreakyEditorMapper)
            {
    
            }
    
            #endregion
    
            #region Mappers
    
            public static IPropertyMapper<IExtendedLabel, ExtendedLabelHandler> FreakyEditorMapper = new PropertyMapper<IExtendedLabel, ExtendedLabelHandler>(ViewMapper)
            {
                [nameof(IExtendedLabel.HasUnderline)] = MapHasUnderlineWithColor,
                [nameof(IExtendedLabel.UnderlineColor)] = MapHasUnderlineWithColor
            };
    
            public static void MapHasUnderlineWithColor(ExtendedLabelHandler handler, IExtendedLabel entry)
            {
    
            }
    
            #endregion
        }
    }
	
Handler Android:

    public partial class ExtendedLabelHandler
    	{
            protected override AppCompatTextView CreatePlatformView()
            {
                var nativeView = new AppCompatTextView(this.Context)
                {
    
                };
                return nativeView;
            }
    
            private void HandleNativeHasUnderline(bool hasUnderline, Color underlineColor)
            {
                if (hasUnderline)
                {
                    var AndroidColor = underlineColor.ToNativeColor();
                    var colorFilter = BlendModeColorFilterCompat.CreateBlendModeColorFilterCompat(
                        AndroidColor, BlendModeCompat.SrcIn);
                    PlatformView.Background?.SetColorFilter(colorFilter);
                }
                else
                {
                    PlatformView.Background?.ClearColorFilter();
                }
            }
        } 

My iOS handler: 

    public partial class ExtendedLabelHandler
        {
            CoreAnimation.CALayer bottomLine;
    
            protected override UILabel CreatePlatformView()
            {
                return new UILabel();
            }
    
            private void HandleNativeHasUnderline(bool hasUnderline, Color underlineColor)
            {
                if (hasUnderline)
                {
                    var uiColor = underlineColor.ToNativeColor();
                    bottomLine = BottomLineDrawer(uiColor);
                    bottomLine.Frame = new CGRect(x: 0, y: PlatformView.Frame.Size.Height - 5,
                        width: PlatformView.Frame.Size.Width, height: 1);
                    PlatformView.Layer.AddSublayer(bottomLine);
                    PlatformView.Layer.MasksToBounds = true;
                }
                else
                {
                    bottomLine?.RemoveFromSuperLayer();
                }
            }
        }

Am I doing something wrong?

You can find the full code on my repo here which has a full working example of the method never getting called for some reason: https://github.com/FreakyAli/MAUI.FreakyControls/tree/r1-gh/feat/freakyeditor

### Steps to Reproduce

- Create the above-mentioned files
- Use them in XAML
- The CreatePlatformView method was never called (Repo available above as well)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Latest of both

**Comment by jfversluis** [comment]
Could you try to change this line: https://github.com/FreakyAli/MAUI.FreakyControls/blob/r1-gh/feat/freakyeditor/MAUI.FreakyControls/MAUI.FreakyControls/Shared/Extensions.cs#L18

To `handlers.AddHandler(typeof(FreakyEditor), typeof(FreakyEditorHandler));`? Notice how I don't use the interface `IFreakyEditor` anymore. Let us know if that works.

**Comment by FreakyAli** [comment]
> Could you try to change this line: https://github.com/FreakyAli/MAUI.FreakyControls/blob/r1-gh/feat/freakyeditor/MAUI.FreakyControls/MAUI.FreakyControls/Shared/Extensions.cs#L18
> 
> To `handlers.AddHandler(typeof(FreakyEditor), typeof(FreakyEditorHandler));`? Notice how I don't use the interface `IFreakyEditor` anymore. Let us know if that works.

Hey, @jfversluis, this seems to fix the issue thanks a lot I was wondering what I did wrong thanks.

**Comment by FreakyAli** [comment]
One Quick question though, @jfversluis the custom control that I just created, All the existing properties that it had have stopped working for instance if I change the BackgroundColor property of Text property nothing happens, Is this intended to be this way? or am I missing something
