### ISSUE TITLE
System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken='.

### ISSUE THREAD

**Issue by roguedev1** [dotnet/maui#9730]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: Windows 10

I have installed VS 2022 and tried to migrate my project from VS 2019. However, when building the project I receive the following error message:

`System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken='.`

**Steps to Reproduce**
Create a new VS 2022 project
Migrate classes and nuget packages from VS 2019
Build the app

**Expected Behavior**
App runs without any issue

**Actual Behavior**
Build failed error with this build log output:

```
1>Build FAILED.
1>
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028: File name: 'Microsoft.Maui.dll'
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 245
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type) in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:line 111
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Mono.Cecil.TypeReference.Resolve() in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/TypeReference.cs:line 278
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionCache.Resolve(TypeReference typeReference) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs:line 20
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.<GetTypeAndBaseTypes>d__5.MoveNext() in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 40
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName, IMetadataResolver resolver) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:line 94
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at MonoDroid.Tuner.FixAbstractMethodsStep.FixAbstractMethods(AssemblyDefinition assembly)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Common.targets(1388,3): error XALNS7028:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs
```:line 17

**Comment by jfversluis** [comment]
Hey there @roguedev1 thanks for the report! Unfortunately it doesn't contain enough info at this point to effectively diagnose what might be going on. Could you maybe elaborate a bit more on these points:

* What type of project are you trying to convert?
* What are the steps you are taking? A bit more precise than copying classes and NuGets
* What NuGets are you using?
* What version of Visual Studio are you using?
* Did you install the .NET MAUI workload when installing Visual Studio?
* What does running `dotnet --version` tell you?

Thanks!

cc: @Sweekriti91 for migration issues maybe?

**Comment by roguedev1** [comment]
> Hey there @roguedev1 thanks for the report! Unfortunately it doesn't contain enough info at this point to effectively diagnose what might be going on. Could you maybe elaborate a bit more on these points:

Hi thanks for the reply. I have added the information below.

**What type of project are you trying to convert?**
MonoGame Android Application (MonoGame Team)

**What are the steps you are taking? A bit more precise than copying classes and NuGets**
Install VS 2022 with the .NET Multi-platform App UI Developement and .NET Desktop development workloads
Using command line dotnet workload install maui and maui-android
Create a new VS 2022 project with the same project name as original
Go into old project and copy classes from VS 2019 into VS 2022 project
In new project, check that MonoGame code works without additional packages, clean and build app
In new project, install NuGet packages one by one to see which ones fail when building (see below)

**What NuGets are you using?**
MonoGame.Framework.Android
MonoGame.Content.Builder.Task
Xamarin.Firebase.Crashlytics
Xamarin.Firebase.Essentials
Plugin.MauiMTAdmob -> I have identified this is the NuGet with the issue, removing this NuGet and code references allows the project to build

**What version of Visual Studio are you using?**
Microsoft Visual Studio Community 2022 (64-bit)
Version 17.3.3

**Did you install the .NET MAUI workload when installing Visual Studio?**
Yes

**What does running dotnet --version tell you?**
6.0.400

**Comment by PureWeen** [comment]
https://github.com/marcojak/MauiMTAdmob/issues/6

**Comment by PureWeen** [comment]
Does this ring any bells @jonathanpeppers

**Comment by jonathanpeppers** [comment]
I think we need an [MSBuild `.binlog`](https://msbuildlog.com/) to look into this more. So @roguedev1 could you `dotnet build -bl` your project and share the `msbuild.binlog` file?

**Comment by KelsamGames** [comment]
@roguedev1 I had the same issue, here is how I fixed it:

Add `<UseMaui>true</UseMaui>` to your .csproj. The UseMauiEssentials directive is insufficient and NuGet does not handle this prerequisite for you. You may also need this: https://github.com/marcojak/MauiMTAdmob/issues/2

Delete your `bin` and `obj` folders (a simple Clean operation didn't work for me, so this was necessary). Rebuild.

MAUI also changes how you deploy to your Android Emulator/Hardware (the debug deploy menu changes from a device list to a standard "Start" button and submenus to select target for deployment).

_**I have been unable to get this (choosing an android deployment target) to work.**_ At first I could build/deploy to an emulator, but upon trying to change to a hardware device target, it simply did nothing and the emulator device kept the checkmark. I then deleted my .csproj.user file in an attempt to get it regen/fix it. Now, the deploy target is stuck on my hardware device (has the checkmark in menu) and can't be changed away from it (unless I disconnect my device), and when I attempt to build I get the error "Please select a valid device before running the application."

**Comment by jonathanpeppers** [comment]
@roguedev1 does `UseMaui=true` solve anything for you?

**Comment by I4-PJ** [comment]
I have the same issue after updating VS from 17.3 to 17.4 prev2. Since than, it was working just fine.

Now I am getting an error 
[error.txt](https://github.com/dotnet/maui/files/9582532/error.txt)

Project structure is not complex but having several MAUI / net standard Only one library is affected (I4.Mobile.Droid.Controls) with that issue.

![image](https://user-images.githubusercontent.com/72924226/190601550-ba4b7e1c-384b-433d-9eae-a32bb8a99a68.png)
![image](https://user-images.githubusercontent.com/72924226/190601747-f372410c-0ad5-49c2-b58e-38d58af71e86.png)

**Comment by jonathanpeppers** [comment]
@I4-PJ I think your issue is the same as:
* https://github.com/dotnet/maui/issues/10150
* https://github.com/dotnet/maui/issues/10148

This is unrelated to this one, as the `Could not load Microsoft.Maui.dll` message is different than one of your own assemblies.

**Comment by roguedev1** [comment]
I tried adding <UseMaui>true</UseMaui> to my .csproj and it did not seem to make any difference.

Here is my build log:

[buildlog.txt](https://github.com/dotnet/maui/files/9599064/buildlog.txt)

**Comment by jonathanpeppers** [comment]
Hi @roguedev1, something how I missed checking back on this.

The build log above is minimal verbosity, so it doesn't have the info we need. If you ran `dotnet build -bl`, can you share the `msbuild.binlog` it created in the current directory?

If it is a sample project (`C:\Users\abc_\source\repos\abc`) are you able to share the entire project? Thanks!

**Comment by roguedev1** [comment]
dotnet build -bl does not create any file that I can locate. What directory is it meant to be in?

**Comment by roguedev1** [comment]
I've created a fresh project with the binlog
[msbuild.zip](https://github.com/dotnet/maui/files/9686612/msbuild.zip)

**Comment by jonathanpeppers** [comment]
From the `.binlog`, `Project1.csproj` does not have `<UseMaui>true</UseMaui>`. I don't think we have a way for NuGet packages to opt your project into using MAUI.

Is the GitHub repo public? The link shows a 404, which could mean it's private.

**Comment by roguedev1** [comment]
I changed it to public now

Yes sorry I made a fresh one without adding the extra line of code, although it made no difference when I tried before

**Comment by jonathanpeppers** [comment]
When I add `UseMaui=true`, the project gets past the `Could not load Microsoft.Maui.dll` and hits errors about missing Java packages:

```
javac.exe error JAVAC0000:  error: package com.google.android.ump.ConsentForm does not exist
```

Then I added the missing package:
```
<PackageReference Include="Xamarin.Google.UserMessagingPlatform" Version="2.0.0.2" />
```
I think that `Plugin.MauiMTAdmob` should make this a dependency?

Does that get things working for you? The sample app crashes, asking for an API key now:

```
09-30 15:54:01.034 14279 14279 I MonoDroid: ******************************************************************************
09-30 15:54:01.034 14279 14279 I MonoDroid: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
09-30 15:54:01.034 14279 14279 I MonoDroid: * should follow the instructions here:                                       *
09-30 15:54:01.034 14279 14279 I MonoDroid: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
09-30 15:54:01.034 14279 14279 I MonoDroid: * to add a valid App ID inside the AndroidManifest.                          *
09-30 15:54:01.034 14279 14279 I MonoDroid: * Google Ad Manager publishers should follow instructions here:              *
09-30 15:54:01.034 14279 14279 I MonoDroid: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
09-30 15:54:01.034 14279 14279 I MonoDroid: ******************************************************************************
```

**Comment by roguedev1** [comment]
Thank you very much for the help @KelsamGames and @jonathanpeppers. I tried again and turns out I was editing the wrong file. I have a file called [projectname].csproj but this is a USER file. I was supposed to edit the [projectname] C# Project File.
