### ISSUE TITLE
运行第一个demo时报错

### ISSUE THREAD

**Issue by Mofi-Zuo** [dotnet/maui#9732]
当我尝试运行Windows maction时，出现如下错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		DEP0700: 应用程序注册失败。[0x80073CF9] 无法针对程序包 8FCE5AA1-D0F1-463D-9A1B-02DBDE438B3C_1.0.0.1_x64__9zz4h110yvjzm 和文件路径 resources.pri 初始化 MRT 资源管理器。	MauiAppDemo		
我的操作系统版本为19041.1415

**Comment by jfversluis** [comment]
I'm very sorry but I cannot read what is being written here. Please report issues in English. Thanks!
