### ISSUE TITLE
Canvas background on iOS isn't transparent

### ISSUE THREAD

**Issue by WebGoose** [dotnet/maui#9740]
### Description

Canvas background on iOS is not transparent and can't be set to transparent. It defaults to solid white and hides other controls beneath it. 

In the sample app attached I layer 2 graphics views on top of each other in a grid to create a gauge control (the colour fills the circle based on a value. )

On Android this is working just fine, the canvas is transparent and you can see both graphics views. On iOS the canvas is solid white so you only see the top layer. 

Trying to draw a transparent rectangle to fill the canvas doesn't work either, just defaults to white.

Android:
![image](https://user-images.githubusercontent.com/5024960/187188895-caf2e1b1-d9cc-48d5-97e8-be7b497eb922.png)

iOS:
![image](https://user-images.githubusercontent.com/5024960/187188949-857cdc47-9cab-4c9e-bda5-e33e883b30fa.png)

[MauiProgram.zip](https://github.com/dotnet/maui/files/9444095/MauiProgram.zip)

I am on VS Preview 17.4.0 Preview 1

### Steps to Reproduce

Create any graphics view in iOS. The canvas is solid white. 

See attached sample for my use case. 

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15..3.1

### Did you find any workaround?

No.

**Comment by mattleibow** [comment]
This is because by default iOS views are opaque and there is a white background.

A workaround is to add this code somewhere before creating any views. I just added it to the top of the `MauiProgram.CreateMaioApp()`:

```cs
#if IOS || MACCATALYST
Microsoft.Maui.Handlers.GraphicsViewHandler.Mapper.AppendToMapping("MakeTransparent", (handler, view) =>
{
	handler.PlatformView.Opaque = false;
	handler.PlatformView.BackgroundColor = null;
});
#endif
```

**Comment by WebGoose** [comment]
Thanks @mattleibow , I will add that workaround

**Comment by mattleibow** [comment]
Ah, no need for the handler code? OK, lol, that is better then hehe.
