### ISSUE TITLE
CarouselView displaying views through DataTemplate throws exception when loop is enabled

### ISSUE THREAD

**Issue by KPHIBYE** [dotnet/maui#9744]
### Description

When setting the ItemsSource of a CarouselView to a collection of views and specifying a DataTemplate with a ContentView or ContentPresenter to display it, a `Java.Lang.IllegalStateException` is thrown on Android that says

> The specified child already has a parent. You must call removeView() on the child's parent first

On Windows, if everything is left untouched, the first View is not displayed and a very long horizontal scrollbar is displayed on the bottom. If Loop is disabled, the first view is still not displayed but the horizontal scrollbar is not present. If Loop is disabled and the converter workaround described below is used, it seems to behave normally (scroll not tested). If Loop is enabled and the converter workaround is used, and the horizontal scrollbar is used, it scrolls uncontrolled and very fast.

I did not test this on other platforms besides Android and Windows.

### Steps to Reproduce

[Reproduction Repository](https://github.com/KPHIBYE/CarouselViewLoopCrashDemo)

OR

Just add this to a View

```xaml
<CarouselView Loop="True">
    <CarouselView.ItemsSource>
        <x:Array Type="{x:Type Label}">
            <Label Text="Item 1" />
            <Label Text="Item 2" />
        </x:Array>
    </CarouselView.ItemsSource>
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <ContentView Content="{Binding}" />
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 5 and up, Windows 10.0.17763.0 and up

### Did you find any workaround?

Yes, setting Loop to false, or writing an `IValueConverter` that removes the view from the parent.

**Comment by PureWeen** [comment]
Duplicate https://github.com/dotnet/maui/issues/7884
