### ISSUE TITLE
Path resources cannot be consumed multiple times via StaticResource

### ISSUE THREAD

**Issue by maexsp** [dotnet/maui#9747]
### Description

When porting an existing SVG multicolor image to an .NET MAUI Grid with some paths and consume it multiple times via StaticResouce the Android App or WinUI App crashes:

WinUI Exception: {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"}

Android Exception: Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

Repo for reproduction: https://github.com/maexsp/MauiResources 

### Steps to Reproduce

1. Create a empty default Maui App and add the following code and run on Android or WinUI.
2. See that the second `<Frame Content="{StaticResource ImagePath}"/>`  is producing the crash. Uncomment and it works. Using x:Shared="false" does not seem to work. May this is the source of error?

`
   
    <ContentPage.Resources>

        <Grid x:Key="ImagePath" x:Shared="false" Background="White" WidthRequest="200" HeightRequest="100">
            <Path Aspect="None" Data="F1M99,51C90.5,51,84,57.5,84,66C84,74.5,90.5,81,99,81C107.5,81,114,74.5,114,66C114,57.5,107.5,51,99,51 M1,14L69,14L69,56L1,56z" Fill="#FF12579B"/>
            <Path Stroke="Black" Data="M13.908992,16.207977 L32.000049,16.207977 32.000049,31.999985 13.908992,30.109983Z" />
            <Path Stroke="Red" Data="M5,1 L32.000049,16.207977 32.000049,31.999985 13.908992,30.109983Z" />
            <Path Stroke="Pink" Data="M3,2 L20,10 15,25 12,5Z" />
        </Grid>

    </ContentPage.Resources>

    <ScrollView>
        <VerticalStackLayout Spacing="5" Padding="15" VerticalOptions="Start">

            <Label Text="Icon instance 1:"/>
            <Frame Content="{StaticResource ImagePath}" BorderColor="Transparent" Padding="0"/>

            <Label Text="Icon instance 2:"/>

            
            
            
            <Frame Content="{StaticResource ImagePath}"/>
            
        </VerticalStackLayout>
    </ScrollView>
 
`

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15, Win 10

### Did you find any workaround?

No workaround found. Tryed many attempts.

**Comment by jsuarezruiz** [comment]
With x:Shared this case should work. Without it, the second time trying to adding the Grid from the Resources to the second Frame will fail because the same Grid already have a Parent, the first Frame.

Stephane worked on it here https://github.com/xamarin/Xamarin.Forms/commit/dbeefb95284fea76886d250009c498792ad3f6fc, but this changes are NOT included in the .NET MAUI code.

**Comment by mattleibow** [comment]
Have you tried using a control template? `Grid` is a control and can't be reused in multiple locations.

Might be better to use a ControlTemplate?

@StephaneDelcroix is this a missing feature in MAUI that we need to move over?

**Comment by maexsp** [comment]
@mattleibow Just tried out to enclose the paths into a ControlTemplate resource.
Using a ControlTemplate and consume it via <ContentView ControlTemplate=... /> works.

But to consume it via <Frame ControlTemplate=.../> does not work at all.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Not repro on Windows and Android platform with sample project.
[MauiResources-master.zip](https://github.com/dotnet/maui/files/11541642/MauiResources-master.zip)
Android:
![Screenshot 2023-05-23 165232](https://github.com/dotnet/maui/assets/77434865/e24d7f20-1069-49c0-8b1b-820dcdf57815)
Windows:
![Screenshot 2023-05-23 165317](https://github.com/dotnet/maui/assets/77434865/0db36ac0-73fe-410c-817f-ec5583d1df27)
