### ISSUE TITLE
Changing CarouselView Position has no effect until it is set >0 and back to 0 when loop is disabled

### ISSUE THREAD

**Issue by KPHIBYE** [dotnet/maui#9749]
### Description

When changing the Position property of a CarouselView with Loop disabled in code and it has not already been changed through swiping, the CarouselView will not change its displayed item until Position was set to a value >0 and back to 0. After this, the behavior is as expected. If Loop is enabled, the behavior is as expected on Android.

I am unsure if Windows is affected since the CarouselView behaves very differently compared to Android, as #7180 shows.

### Steps to Reproduce

[Reproduction Repository](https://github.com/KPHIBYE/CarouselViewPositionDemo)

OR

Create a CarouselView with Loop disabled and try to change the displayed item by changing the position property exclusively in code

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 5 and up

### Did you find any workaround?

Yes, setting Loop to true, or setting Position to something other than zero and back

**Comment by eddie010** [comment]
Can conform. Workaround is to indeed set Position on 1, then on 0 and then on 1 the first time you increment the position

**Comment by tranb3r** [comment]
Any update ? Thanks

**Comment by DeepWorksStudios** [comment]
any updates? i just wanted to report the same issue

**Comment by SarthakB26** [comment]
any update ?

**Comment by DeepWorksStudios** [comment]
It's just ridiculous.. its like reporting a bug does not make any difference by now since they don't fix most of the reported bugs or they just really to slow...

**Comment by jadenrogers** [comment]
He's not wrong, why are these still open? Can you advise what the official solution is here, do we simply move to .net 8 previews?
Is .net 8 previews better than current state of production .net 7?

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android platform with sample project.
[Reproduction Repository](https://github.com/KPHIBYE/CarouselViewPositionDemo)

**Comment by DeepWorksStudios** [comment]
> He's not wrong, why are these still open? Can you advise what the official solution is here, do we simply move to .net 8 previews? Is .net 8 previews better than current state of production .net 7?

Sadly thats not really an option i tryed to move to .net 8 preview but it worsen the situation in therms of stability and bugs
I just can advise you to stay at .net 7 untill .net 8 gets released for public use

**Comment by davidortinau** [comment]
Testing with net8 preview6 I confirmed this behavior still exists. I also confirmed that `MyCarousel.ScrollTo(1);` works immediately. Try this for now.

Also confirmed this method works on .NET 7.

**Comment by BeepBeepBopBop** [comment]
Any update ?

**Comment by standamikes** [comment]
It works properly on .net 8 RC2

**Comment by beglaryan-alen** [comment]
You can just create new carouselview control with Position property, here is an example

```
 public class CustomCarouselView : CarouselView
 {
     public new static readonly BindableProperty PositionProperty =
         BindableProperty.Create(nameof(Position), typeof(int), typeof(CustomCarouselView), propertyChanged: OnPositionPropertyChanged);

     private static void OnPositionPropertyChanged(BindableObject bindable, object oldValue, object newValue)
     {
         var carouselView = bindable as CustomCarouselView;
             if (carouselView.viewModel is ViewModels.MyLibraryPageViewModel myLibraryVm)
             {
             carouselView.ScrollTo(myLibraryVm.CurrentTabIndex);
             }
     }

     public new int Position
     {
         get => (int)GetValue(PositionProperty);
         set => SetValue(PositionProperty, value);
     }

     private BaseVm viewModel;

     protected override void OnBindingContextChanged()
     {
         base.OnBindingContextChanged();

         viewModel = BindingContext as BaseVm;
     }
 }
```
