### ISSUE TITLE
Shell content navigation does not navigate to correct view

### ISSUE THREAD

**Issue by Sashi13** [dotnet/maui#9765]
### Description

Recently I started to migrate my Xamarin framework based application to MAUI framework. I have faced an issue where my `Appshell` doesn't navigate to the correct page when I press the content in flyout but it shows the last page navigated on the content page.

I have used same code on Xamarin and I didn't face this issue. Below I have attached a gif and code as well. I have a logic when application is started in `app.xaml.cs` where it sets `Mainpage` to `Appshell` if `autologin` is checked or login is successful else the main page will set to login page.

![ezgif-3-106a4d21df](https://user-images.githubusercontent.com/46073300/187328147-08a5a02e-f460-4768-9afd-af9f87fd8826.gif)

I have posted the question in stackoverflow as well (https://stackoverflow.com/questions/73524090/maui-shell-content-navigation-does-not-navigate-to-correct-view)

### Steps to Reproduce

1. Create a MAUI project
2. Create a flyout shell with multiple contents
3. Create pages for the contents
4. Click one of the content and navigate to next page (either using PushAsync or GotoAsync)
5. Click the content again

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1

**Comment by AndreasReitberger** [comment]
I organized each `ShellContent` in a single `FlyoutItem`.  On my end, the navigation works fine. Also you need to set the `Route` property. Maybe the missing `Route` value leads to this behaviour.

See: https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation#register-routes

Please see my example below:

XAML


```xaml
<!-- Flyout Items -->
    <FlyoutItem
        Title="{x:Static localization:Strings.Status}"
        >
        <FlyoutItem.Icon>
            <FontImageSource
                FontFamily="{StaticResource MaterialDesignIcons}"
                Glyph="{StaticResource MaterialDesign_ProgressCheck}"
                Color="{DynamicResource PrimaryColor}"
                Size="{StaticResource DefaultIconSize}"
                />
        </FlyoutItem.Icon>
        <!-- Status -->
        <ShellContent 
            Title="{x:Static localization:Strings.Status}" 
            ContentTemplate="{DataTemplate views:KlipperStatePage}"
            Route="KlipperStatePage"
            />
    </FlyoutItem>

<FlyoutItem
        Title="{x:Static localization:Strings.ControlPanel}" 
        >
        <FlyoutItem.Icon>
            <FontImageSource
                FontFamily="{StaticResource MaterialDesignIcons}"
                Glyph="{StaticResource MaterialDesign_TuneVertical}"
                Color="{DynamicResource PrimaryColor}"
                Size="{StaticResource DefaultIconSize}"
                />
        </FlyoutItem.Icon>
        <ShellContent
            ContentTemplate="{DataTemplate views:SingleControlPanelPage}"
            Route="SingleControlPanelPage"
            IsEnabled="{Binding IsLightVersion,Converter={StaticResource BooleanReverseVisibilityConverter}}"
            >
        </ShellContent>
    </FlyoutItem>
```

**Comment by PureWeen** [comment]
Can you paste this logic?
> . I have a logic when application is started in app.xaml.cs where it sets Mainpage to Appshell if autologin is checked or login is successful else the main page will set to login page.

did I miss it?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Not repro on iOS platform with sample project. https://github.com/Sashi13/ShellNavigation
