### ISSUE TITLE
MAUI Android projects generate an \obj\Debug\net6.0-android\Resource.designer.cs file containing code that assigns values to const identifiers

### ISSUE THREAD

**Issue by frauenholz** [dotnet/maui#9766]
When proper, the UpdateIdValues() method has about 59 statements (see **Resource.designer - UpdateIdValues() proper.cs**)

Something is causing the Android Resource.designer.cs file's UpdateIdValues() method to have 6000+ statements, the majority of which are assignment to const's, thus producing approx 6000+ compiler errors (see **Resource.designer - UpdateIdValues() constAssigns.cs**)

an example is the line:
global::MauiLib1.Resource.Animation.abc_tooltip_enter = global::MauiApp1.Resource.Animation.abc_tooltip_enter;;

where the target of the assignment is declared as:
public **const** int abc_tooltip_enter = 2130771978;

it is likely (but not certain) that this is related to when a MAUI app project references a MAUI library project, I am trying to pin it down

[Resource.designer - UpdateIdValues.zip](https://github.com/dotnet/maui/files/9449348/Resource.designer.-.UpdateIdValues.zip)

**Comment by PureWeen** [comment]
@jonathanpeppers @dellis1972  ?

**Comment by dellis1972** [comment]
This is probably because the Library project is setting the `AndroidApplication` property set to `true`. We only generate const values for applications, not for libraries. For libraries we generate a `static` so it can be set.

**Comment by dellis1972** [comment]
Can you post the csproj files for both the App and the Library projects?

**Comment by dellis1972** [comment]
@PureWeen I can't add the needinfo label.

**Comment by jonathanpeppers** [comment]
In .NET 6 it could also be OutputType=Exe, we set AndroidApplication=true for that as well.

**Comment by dellis1972** [comment]
I tried to repo this using the templates in VSForMac and I get `static` for the library project. So I guess in this case the library project has an OutputType of Exe.

**Comment by dellis1972** [comment]
However setting OutputType to Exe is not all that would need to happen. The library project would also need an AndroidManifest and all the ApplicationId settings.

**Comment by frauenholz** [comment]
repo created at https://github.com/frauenholz/MauiApp_9766
this is a .sln with a MauiApp, a MauiLib with a ContentPage, where the MauiApp AppShell.xaml only ShellContnet is the Lib's ContentPage named NewPage1.xaml.
The Android Resource.designer.cs file generated by this .sln on my local machine is attached
[Resource.designer.zip](https://github.com/dotnet/maui/files/9478307/Resource.designer.zip)

**Comment by dellis1972** [comment]
Weird, that repo works locally for me on macOS. 

Are you able to provide a diagnostic binlog for us to look at? It would be interesting to see what properties the MauiLib_9766 project is getting when building.

**Comment by frauenholz** [comment]
I observed that after cleaning the solution, and re-building, the **Resource.designer.cs** file is 732KB.  After running the MAUI App in the "Pixel 5 - API 31" emulator, while deploying the app the **Resource.designer.cs** file increased to 1,654 KB, and has the **const** assignment compile errors.  I am not sure how to generate a binlog from the IDE.  The attached file is a save of the Output Window from the IDE, Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.3.  Running on Windows 10.

[Output-Debug MAUI issue 9766.txt](https://github.com/dotnet/maui/files/9479054/Output-Debug.MAUI.issue.9766.txt)

**Comment by jonpryor** [comment]
I have attempted to repro this issue using https://github.com/frauenholz/MauiApp_9766, and have been unable to cause `Resource.designer.cs` within to have `const` statements within the `MauiLib_9766` project, even after deploying to a device.  It feels like we need something "more" in order to properly repro this. ☹️

**Comment by dellis1972** [comment]
@frauenholz area you able to provide us a complete build tree of a sample app? This should include the bin and obj directories for all the projects. We cannot repo this issue using the sample you provided.

Also does this happen from the command line or just the IDE?

**Comment by frauenholz** [comment]
**MauiApp_9766.zip** (184 MB) on https://drive.google.com/file/d/1-yXG_3Bar_dA6rGB_TB7aWfi57flAT5P/view is a zip of the original sample project repository at https://github.com/frauenholz/MauiApp_9766, and has bin and obj directories and other build content.  Please let me know if you need something else.

**Comment by dellis1972** [comment]
That is very confusing. Looking at the source files the MauiLib1 Resource.designer.cs contains static fields which is expected. The assembly itself has static fields again expected. 

So I am not sure why you are getting a build error. 

I'll try to repo again on a Windows machine next week.

**Comment by Eilon** [comment]
This issue was moved to xamarin/xamarin-android#7724
