### ISSUE TITLE
[Bug] Respond to Screen Scaling

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#977]
### Description

![image](https://user-images.githubusercontent.com/41873/117469108-fd61fd00-af1a-11eb-921b-7391531554c5.png)

Please enable some hook/event for apps to react to OS level scaling changes such as this.

### Steps to Reproduce

1. Open an app on Windows
2. Change the scaling to 125%, 150%, 100% etc.

### Expected Behavior

As a dev I can choose how my UI should respond to these differences.

Would be nice if a layout would be triggered automatically when the scaling changes so some basic things would resize properly. 

### Actual Behavior

I have no control. Menus and things positioned against the window are out of view until I resize the window.

### Basic Information

- Version with issue: Preview 4
- Applies to macOS and Windows

**Comment by rachelkang** [comment]
@davidortinau are you still experiencing this issue? I'm on Windows 11 so my settings look different, and the one that I believe correlates to this seems blocked for me. I was able to try the OS level Text size scaling though and that worked great!

**Comment by hartez** [comment]
This might be related to #716

**Comment by hartez** [comment]
This might also have been related to the fact that nothing on Windows was responding to _any_ resize events until the window was manually resized. It's possible that this is all fixed now that layout updates are triggered without having to resize the window.

**Comment by hartez** [comment]
Closing this for now. The platforms are now responding to OS-level scale changes by redrawing the app. AFAIK there's no option to hook into an event for this change and make it available for developers - you're just supposed to design your app to scale properly. 

If you have a more specific use case where you need such an event, we can re-open this and look into it.
