### ISSUE TITLE
Set or Get Row & Column Properties.

### ISSUE THREAD

**Issue by jrahma** [dotnet/maui#9774]
### Description

Hi,

This is a great and clean way to define the row and columns:

`<Grid x:Name="myGrid" ColumnDefinitions="*,Auto" RowDefinitions="*,50">
`
but the problem is now there is no way to set or get the properties of the row or column

### Public API Changes

It will be great if you make it this way:

```
myGrid.Row[0].Height = 20
myGrid.Row[2].IsVisible = False

```

or:

```
myRow.Column[0].Width = 25
myGrid.Row[1].IsVisible = True
```

### Intended Use-Case

Get or Set Row and Height properties.

**Comment by danielftz** [comment]
You already can do that. 
`myGrid.RowDefinitions[2].Height = new GridLength(2, GridUnitType.Star);`

**Comment by rachelkang** [comment]
Hi, @jrahma - as @danielftz mentioned in their comment above, this is already supported. Please let us know if we're misunderstanding something, and we'll reopen the issue!

**Comment by jrahma** [comment]
Great. Thank you
