### ISSUE TITLE
CarouselView crashes IOS app

### ISSUE THREAD

**Issue by AbstractionsAs** [dotnet/maui#9775]
### Description

App works fine on Android, but a certain page crashes IOS. It hangs without an error message.

The device logs are spammed with the following messages: "negative or zero item sizes are not supported in the flow layout"
If I remove the carousel view from the page it works fine.

I've tried:

- Replacing the ItemTemplate with an empty one
- Removing the ItemsSource Binding
- Setting IsVisible to both true and false

### Steps to Reproduce

Use carousel view in iOS

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

15

### Did you find any workaround?

No

### Relevant log output

```shell
negative or zero item sizes are not supported in the flow layout
```

**Comment by jsuarezruiz** [comment]
Could you share a small sample where reproduce the issue, or share the piece of code defining your CarouselView (layout, spacing, etc)?

**Comment by AbstractionsAs** [comment]
The carousel is part of a control I use multiple places in the app. The control looks like this:
``` xaml
<ContentView.Content>
        <VerticalStackLayout IsVisible="{OnPlatform Android={Binding HasImages}, iOS=true}">
            <CarouselView x:Name="carousel"  IndicatorView="{x:Reference indicator}">
                <CarouselView.ItemTemplate>
                    <DataTemplate x:DataType="models:ImageAttachmentModel">
                        <Grid>
                            <Image HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" HeightRequest="150" Aspect="AspectFit" Source="{Binding UploadBytes, Converter={StaticResource imageBytes}}">
                                <Image.Shadow>
                                    <Shadow Brush="Black" Offset="5,5" Radius="40" Opacity="0.8" />
                                </Image.Shadow>
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Source={x:Reference carousel}, Path=BindingContext.ImageDetailsCommand}" CommandParameter="{Binding}" />
                                </Image.GestureRecognizers>
                            </Image>
                        </Grid>
                    </DataTemplate>
                </CarouselView.ItemTemplate>
            </CarouselView>
            <IndicatorView x:Name="indicator" HorizontalOptions="Center" Margin="0,5,0,5" />
        </VerticalStackLayout>
  </ContentView.Content>
```

The crash still occurs if I do this:

``` xaml
<ContentView.Content>
        <VerticalStackLayout IsVisible="{Binding HasImages}">
            <CarouselView>
                <CarouselView.ItemTemplate>
                    <DataTemplate x:DataType="models:ImageAttachmentModel">
                        <Grid>
                            <!--<Image HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" HeightRequest="150" Aspect="AspectFit" Source="{Binding UploadBytes, Converter={StaticResource imageBytes}}">
                                <Image.Shadow>
                                    <Shadow Brush="Black" Offset="5,5" Radius="40" Opacity="0.8" />
                                </Image.Shadow>
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Source={x:Reference carousel}, Path=BindingContext.ImageDetailsCommand}" CommandParameter="{Binding}" />
                                </Image.GestureRecognizers>
                            </Image>-->
                        </Grid>
                    </DataTemplate>
                </CarouselView.ItemTemplate>
            </CarouselView>
            <!--<IndicatorView x:Name="indicator" HorizontalOptions="Center" Margin="0,5,0,5" />-->
        </VerticalStackLayout>
  </ContentView.Content>
```

So there's really not a lot of things I can think of here. It can't be related to to itemtemplate, I've removed the ItemsSource and visibility, basically everything. Even when I'm left with just a simple, empty, carousel the app crashes. If I comment out the carousel itself, everything is fine.

**Comment by AbstractionsAs** [comment]
I've assigned someone to create a repo with the problem.

Does this mean you're not able to reproduce by simply copying the above markup?

Skaff deg Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by AbstractionsAs** [comment]
Ok, so there's some progress on this.

First and foremost: Setting a heightrequest on the carouselview _sort of_ resolves the issue. That is to say - the app no longer crashes, however the carouselview will still consume vertical space even when parent container has IsVisible=false.

The longer version:

When we created a separate repo to reproduce the issue, we were unable to reproduce the crash, but we ran into a different issue: The empty carousel would consume an unreasonable amount of vertical space, more than the screen height, hiding any views below the caousel when placed in a vertical stack layout.

Even when wrapping the stacklayout in a scrollview, the views below the carousel would still be outside the scrollable area, giving the effect that you could scroll the page, but still never see the views below the carousel.

This made me think this was an underlying effect of the same problem. 

When adding a HeightRequest to the carousel in the original app:

1. The app no longer crashes
2. The view consumes visible space even when not visible
3. Adding items to the carousel does not cause the view to refresh, bit it seems to work otherwise.

**Comment by rmarinho** [comment]
This doesn't t seem to be an issue anymore. Please reopen with a repo with the latest stable version if this is still present in the latest version.
