### ISSUE TITLE
Was the issue with MAUI project templates appearing for VS Preview resolved?

### ISSUE THREAD

**Issue by guardrex** [dotnet/maui#9777]
### Description

WRT the VS 17.3 Preview 1.1-era problem of templates not showing up after installing VS Preview with the MAUI workload ...

* [Suggest alternative actions when MAUI Templates are not installed with VS 2022 Preview 6.0](https://github.com/dotnet/maui/issues/7185)
* [.NET MAUI Templates not showing up - Windows 11, Visual Studio 2022 17.3.0 Preview 1.1 (dotnet/maui #8076)](https://github.com/dotnet/maui/issues/8076)
* [.NET MAUI Known Issues: .NET MAUI templates do not appear in Visual Studio](https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio)

At the time of the early reports, it went under investigation. I couldn't find a public tracking issue, possibly because it was being worked by the VS team offline. We're carrying guidance on using `dotnet new -i Microsoft.Maui.Templates` in the ASP.NET Core Blazor-MAUI tutorial on the workaround that I'd like to drop from the topic when the issue is resolved.

* Was the problem resolved in one of the recent VS/.NET 7 previews?
* If it remains a problem for some devs, is there a public issue that I can track on for our Blazor-MAUI tutorial in the ASP.NET Core doc set? Alternatively, should I schedule removing the NOTE on the workaround from the doc at .NET 7 GA in November?

### Steps to Reproduce

1. Install the VS 2022 Preview with the **.NET Multi-platform App UI development** workload.
2. Attempt to create a Blazor-MAUI app (or any flavor of MAUI app, as I think all MAUI templates were absent).
3. .NET MAUI project templates don't appear in the **Create a new project** UI.
4. The templates must be installed manually as a workaround with the `dotnet new` command.

**NOTE**: I never saw this repro myself. This was based on reader reports in GH issues.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.424

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Described by the *Known Issues* GH doc.

### Relevant log output

```shell
None
```

**Comment by rachelkang** [comment]
Hi, @guardrex - yes, this has since been fixed. If you're still experiencing issues, please open an issue with VS feedback

**Comment by guardrex** [comment]
Thanks ... I'll remove the note that was placed in the ASP.NET Core docs on this.
