### ISSUE TITLE
Have better BlazorWebView diagnostics and logging

### ISSUE THREAD

**Issue by Eilon** [dotnet/maui#9792]
Ideas from a recent Blazor Hybrid meeting:

* Add more logging (via `ILogger`) to many areas of BlazorWebView, such as:
   * Control lifecycle events (native view created, things getting initialized), Blazor started
   * Report stuff that's calculated by the control, such as HostPage location, app root dir
   * Static assets being requested, loaded, or failed to load, and anything else related to file providers
   * Other events taking place, such as navigations, launching external browser (including the URL and why the decision was made)
* Add "How to debug Blazor Hybrid" doc that says _exactly_ how to enable logging in MAUI/WinForms/WPF, how to see the logs, etc.

**Comment by Eilon** [comment]
Initial work in this branch: https://github.com/dotnet/maui/compare/eilon/more-blazorwebview-logging

And this commit in particular: https://github.com/dotnet/maui/commit/d32a5a5cf9a530da2c67332acf852d95ee32e4a1

And this is an example of what the output is in a sample app:

```
Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebView: Debug: Creating file provider at content root 'wwwroot', using host page relative path 'index.html'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Starting WebView2...
Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebView: Debug: Starting initial navigation to '/'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: WebView2 is started.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Navigating to https://0.0.0.0/.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Navigation event for URI 'https://0.0.0.0/' with URL loading strategy 'OpenInWebView'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/' with HTTP status code 200.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/css/app.css'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/Maui.Controls.Sample.styles.css'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/_framework/blazor.webview.js'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/_framework/blazor.webview.js'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/css/app.css' with HTTP status code 200.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/Maui.Controls.Sample.styles.css' with HTTP status code 200.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/_content/MauiRazorClassLibrarySample/MauiRazorClassLibrarySample.bundle.scp.css'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/_content/MauiRazorClassLibrarySample/MauiRazorClassLibrarySample.bundle.scp.css' with HTTP status code 200.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Calling Blazor.start() in the WebView2.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/favicon.ico'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/_framework/blazor.modules.json'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/_framework/blazor.modules.json'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content was not found for web request to URI 'https://0.0.0.0/favicon.ico'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/_content/MauiRazorClassLibrarySample/background.png'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content being sent for web request to URI 'https://0.0.0.0/_content/MauiRazorClassLibrarySample/background.png' with HTTP status code 200.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Handling web request to URI 'https://0.0.0.0/favicon.ico'.
Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager: Debug: Response content was not found for web request to URI 'https://0.0.0.0/favicon.ico'.
```

**Comment by Eilon** [comment]
Draft doc to help users enable logging for BlazorWebView and how to see the logs is below.

Links to this new doc should be added to at least the following existing docs (and maybe others):

* https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-7.0
* https://learn.microsoft.com/en-us/dotnet/maui/troubleshooting?view=net-maui-7.0

---

# Diagnosing issues in Blazor Hybrid

Blazor Hybrid uses the BlazorWebView control, which has built-in logging that can help you diagnose problems in your application. There are two steps to enable this logging:

1. Enable BlazorWebView and related components to log diagnostic information
1. Configure a logger to write the log output to where you can view it

## Enable BlazorWebView logging

All logging configuration can be performed as part of service registration in the dependency injection system. To enable maximum logging for BlazorWebView and related components under the `Microsoft.AspNetCore.Components.WebView` namespace,, add the following code to where your app's services are registered:

```c#
services.AddLogging(logging =>
{
	logging.AddFilter("Microsoft.AspNetCore.Components.WebView", LogLevel.Trace);
});
```

Or to enable maximum logging for every component that uses Microsoft.Extensions.Logging, you could use the following code instead:

```c#
services.AddLogging(logging =>
{
	logging.SetMinimumLevel(LogLevel.Trace);
});
```

## Configure logging output and viewing the output

Now that components are configured to write log information, you need to configure where the loggers should write those log to, and then view the log output.

The **Debug** logging providers writes the output using Debug statements that can be viewed from Visual Studio.

To configure the **Debug** logging provider, first add a reference in your project to the `Microsoft.Extensions.Logging.Debug` NuGet package. Then register the provider inside the call to `AddLogging` that you added in the previous step by calling the `AddDebug()` extension method:

```c#
services.AddLogging(logging =>
{
	logging.AddFilter("Microsoft.AspNetCore.Components.WebView", LogLevel.Trace);
	logging.AddDebug();
});
```

When you run the application from Visual Studio (with debugging enabled), you can view the debug output in Visual Studio for Windows' **Output** window or in Visual Studio for Mac's **Application Output** window (along with the debug output of various other components).

## Further reading

To learn more about the Microsoft.Extensions.Logging system used in .NET MAUI applications:

* https://learn.microsoft.com/dotnet/core/extensions/logging

**Comment by Eilon** [comment]
@davidbritch - for this .NET 8 fix I have a proposed doc update above as well. How should we track getting that content into the .NET 8 MAUI docs?

**Comment by davidbritch** [comment]
@eilon I've created https://github.com/dotnet/docs-maui/issues/1207 to track it.
