### ISSUE TITLE
Add better support for Android 12+ Splash Screen APIs

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#9794]
### Description

As part of Android's ongoing improvements and changes to splash screens, Android 12+ has additional image requirements:

 - https://developer.android.com/develop/ui/views/launch/splash-screen#elements

The first issue was that images were not showing at all because of new things, but that was fixed in https://github.com/dotnet/maui/pull/8394

However, those changes also missed the image size requirements. As of now, the image is still the large sizes from the source image which results in it being clipped. This issue is to track any work to automatically fit the screen.

### Workaround

Add a file into your .NET MAUI app with this exact name:

`Platforms\Android\Resources\drawable\maui_splash.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
	<item android:drawable="@color/maui_splash_color" />
	<item
		android:width="108dp"
		android:height="108dp"
		android:gravity="center">
		<bitmap
			android:gravity="fill"
			android:src="@drawable/name_of_your_splash_image"
			android:mipMap="true"/>
	</item>
</layer-list>
```

> Make sure to use the name of your splash screen image in the place of `name_of_your_splash_image`

### Related:

 - The issue with no images is here https://github.com/dotnet/maui/issues/7404  
    and was fixed in this PR https://github.com/dotnet/maui/pull/8394
 - The issue with broken images is fixed here: #9509

**Comment by developer9969** [comment]
Great news!!!. Will this workaround work for xamarin forms too?

**Comment by mattleibow** [comment]
> Great news!!!. Will this workaround work for xamarin forms too?

I don't think forms has resizetizer as part of it... However, you can use the same xml and add it to your own project - whatever you called your drawable files. The trick is really to set thesplash size somewhere to a small size and put your image in there. But, just for Android 12+

**Comment by speschka** [comment]
I've tried the above work around multiple times in multiple ways and it will not compile.  First it looks for your splash file in the same directory as the XML file.  When I copy the file in there it gives me a System.IO.Exception error - process cannot access the file because it's being used by another process.  If I try and change the splash image name and update the XML file to the new name, then I get a file can't be found error, and failed linking file resources error.  Maybe this just needs more instructions, or maybe it's not working with the GA of MAUI (6.0.400).

**Comment by WebGoose** [comment]
Workaround is not working for me either unfortunately. The file is called splashscreen.svg and I've tried @drawable/splashscreen, @drawable/splashscreen.svg and neither work.
