### ISSUE TITLE
Editor/Entry controls don't raise Completed event consistently cross-plat

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#9796]
### Description

When using the Editor/Entry controls on Windows, it seems to work as expected. When you focus a different control, The `Completed` event for the previous control is raised. However, when you're using Android, the event is never raised by simply focusing a different control.

### Steps to Reproduce

Add these controls and create the code behind for each event. Then, put a breakpoint in each event:

```xml
    <VerticalStackLayout Spacing="10" Margin="5">
        <Editor
                Placeholder="Enter your note"
                HeightRequest="100" Completed="Editor_Completed" />
        <Entry Completed="Entry_Completed" />
    </VerticalStackLayout>
```

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Unknown

**Comment by rachelkang** [comment]
Potentially related to #8872

**Comment by BaY1251** [comment]
Entry的问题目前还有很多,Completed事件较TextChanged事件的应用场景更多,起码在Windows系统上是这样. 期待Android平台解决此问题!

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on Android platform with mentioned code.

**Comment by vishalpr-hs** [comment]
any plans on solving this issue?

**Comment by samirgcofficial** [comment]
Any updates ?
