### ISSUE TITLE
Cannot scroll Scrollview on iOS when content dynamically resized

### ISSUE THREAD

**Issue by paulhavey** [dotnet/maui#9798]
### Description

Cannot scroll when content is dynamically revealed on ios

### Steps to Reproduce

Add the following code below the last control in the MainPage.xaml in the sample project when creating a new MAUI app

`
<Button x:Name="btnReveal" Text="Reveal" Clicked="btnRevealClicked" HorizontalOptions="Center"/>
`
`<BoxView x:Name="boxViewBlue" IsVisible="false" BackgroundColor="Blue" HeightRequest="1000" Margin="20" HorizontalOptions="FillAndExpand"/>
`

With the below event in the code behind:

`private void btnRevealClicked(object sender, EventArgs e)
{
		boxViewBlue.IsVisible = !boxViewBlue.IsVisible;
}`

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

No

**Comment by rachelkang** [comment]
Closing this issue as a duplicate of #9078 - please continue to track the issue there!
