### ISSUE TITLE
Pair to Mac failed with error "Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower..."

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/maui#9800]
### Description

Pair to Mac failed with error "Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.9' required by manifest 'microsoft.net.workload.mono.toolchain'".

### Steps to Reproduce

1. Install the latest build of Dev17.4 Preview 2 and use the [script](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md) to install the MAUI(**6.0.517**) workload from main branch  
1. On the Windows machine, create a new Blazor Hybrid project on the command line using the following:
`dotnet new maui-blazor -o iOSWindowsProject`
1. Open the iOSWindowsProject solution with Visual Studio.
1. Select the "Pair to Mac" option in the Visual Studio toolbar.
1. Select the mac OS device that is connected to the network and press "Connect".
1. In the next window, enter the username and password for the user account on the macOS machine.
1. Connect the machine.

**ACTUAL:**
Pair to mac failed.
![image](https://user-images.githubusercontent.com/66412474/187581763-53bb9222-d6f6-4e9a-b50f-7dfd6b148138.png)

**NOTE:**
1. This issue does not repro when only installing Dev17.4 Preview 2, which includes MAUI version is 6.0.486.
1. This issue still repro after manually adding the following feeds in VS.
    - https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-531f715f/nuget/v3/index.json 
    - https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-3f6c45a2/nuget/v3/index.json 
    - https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json 

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 6.0.400

### Did you find any workaround?

No

### Relevant log output

```shell
Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.9' required by manifest 'microsoft.net.workload.mono.toolchain' [/Users/netcore/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json]
```

**Comment by TanayParikh** [comment]
@EmilyFeng97 could you please link the VS Feedback ticket here when you get a chance?

**Comment by EmilyFeng97** [comment]
> @EmilyFeng97 could you please link the VS Feedback ticket here when you get a chance?

I have file a new VS Feedback ticket [10138259](https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could/10138259?port=1025&fsid=d0e0711b-673b-4e2e-b244-7d366f2ded2e&entry=problem) for this bug.

**Comment by carlfranklin** [comment]
I am also experiencing this exact same bug. Started happening once I updated Visual Studio

**Comment by carlfranklin** [comment]
![image](https://user-images.githubusercontent.com/1486348/190026500-5506f106-3e2b-42de-8e72-bcc96a7bd313.png)
Also happening with 17.4.0 preview 1

**Comment by carlfranklin** [comment]
![image](https://user-images.githubusercontent.com/1486348/190026572-e9035a0d-0851-4555-b112-bdf7fe0e5791.png)

**Comment by CodeAirInc** [comment]
@carlfranklin Were you able to fix it?  I get the same error after updating Visual Studio.

**Comment by jared-morley** [comment]
We are seeing this issue too.  Appeared after updating VS

**Comment by carlfranklin** [comment]
> @carlfranklin Were you able to fix it? I get the same error after updating Visual Studio.

No. I also couldn't build my app on the mac. I got around that by installing XCode 13.4.1 (previous version). I still can't pair to the mac.

**Comment by CodeAirInc** [comment]
@carlfranklin I tried repair but it didn't work.  I'm uninstalling 17.3.4 and installing the older version of visual studio.

**Comment by EmilyFeng97** [comment]
> When I try to open this link I get:
> 
> > We were unable to get this feedback item. It could be because you don't have access to it or it doesn't exist
> 
> Did you get any help solving this issue?

You can view the feedback items after logging in to your account. And you also can track this issue using the internal Feedbackticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1611003 on devdiv. 

The latest comment about this issue on feedback item is as follows. 
`A fix for this issue has been internally implemented and is being prepared for release. We'll update you once it becomes available for download.`

**Comment by hasanoruc** [comment]
I changed C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest file:

from:
{
  "version": "6.0.9",
  "depends-on": {
    "Microsoft.NET.Workload.Emscripten": "6.0.9"
  },............
...............

to:

{
  "version": "6.0.4",
  "depends-on": {
    "Microsoft.NET.Workload.Emscripten": "6.0.4"
  },............
.................


and it works and pair to mac correctly...

**Comment by kyakhta** [comment]
> I changed C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest file:
> 
> from:
> 
> ```
> {
>   "version": "6.0.9",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.9"
>   },............
> ...............
> ```
> 
> to:
> 
> ```
> {
>   "version": "6.0.4",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.4"
>   },............
> .................
> ```
> 
> and it works and pair to mac correctly...

Thank you, it helps - I can connect to the Mac, but all the simulators are gone. Did you had issue with selecting iOS simulators?

**Comment by hasanoruc** [comment]
@kyakhta change all 6.0.9 to 6.0.4 to that file. hope it helps.

**Comment by kyakhta** [comment]
> @kyakhta change all 6.0.9 to 6.0.4 to that file. hope it helps.

Thank you, it did not fix it - will keep digging. Hopefully upcoming MS update will fix it.

**Comment by carlfranklin** [comment]
I feel completely stupid for not being able to figure out how to be able to edit C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json. I am an administrator on my Windows 10 box, and admins have full access, yet it's restricted.

**Comment by carlfranklin** [comment]
Success! I thought I tried that. Duh.

**Comment by jatech1** [comment]
I am experiencing the same issue.  New to paired mac ios dev.  I updated the two spots in the file listed above on the Windows side but I still get the same error.  The error points to the same file on the mac side, so I edit that one also.  When I try to pair again, it fails, and I see that the mac file got switched back to 6.0.9, so the pairing must be overwriting it from somewhere... this is driving me nuts... ever since I updated the Win side to 17.3.4 from 17.3.3 I cant do an ios publish build on win, and I can't pair to update files on mac side due to this error!  Has anyone solved this?  Or is going back to 17.3.3 on windows side the only answer?  Will that then push the correct files to mac side via pair, and allow me to once again build via the win to mac ssh dotnet publish?  Does anything need to be change in mac side or is it all driven by win side VS version and files?  Thanks!

**Comment by foosfam** [comment]
> I changed C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest file:
> 
> from:
> 
> ```
> {
>   "version": "6.0.9",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.9"
>   },............
> ...............
> ```
> 
> to:
> 
> ```
> {
>   "version": "6.0.4",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.4"
>   },............
> .................
> ```
> 
> and it works and pair to mac correctly...

@hasanoruc - You Are The Man!  Thanks Brother... 🏆😊👍

**Comment by jatech1** [comment]
thanks foosfam.  I have tried that.  Even tried replacing with the same file from good .3.3 install.  Somehow when I do the pair and before it fails, it is still pushing a workload manifest file to the mac with the wrong values in it... and then the error message I see is the path on the mac to t hat file.. but in the 6.0.400 folder.

**Comment by foosfam** [comment]
@jatech1 - just delete the XMA folder on your Mac - it will copy the right one over.  I also used the Windows Visual Studio Installer and ran a repair AND installed Visual Studio on my Mac.  Give that a try.

**Comment by RichardMarsh** [comment]
> C:\Program Files\dotnet\sdk-manifests



> I changed C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest file:
> 
> from:
> 
> ```
> {
>   "version": "6.0.9",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.9"
>   },............
> ...............
> ```
> 
> to:
> 
> ```
> {
>   "version": "6.0.4",
>   "depends-on": {
>     "Microsoft.NET.Workload.Emscripten": "6.0.4"
>   },............
> .................
> ```
> 
> and it works and pair to mac correctly...

The real MVP. Thank you for this!

**Comment by AndreasReitberger** [comment]
Seeing the same issue, following up.

**Comment by arivoir** [comment]
I'm also seeing this issue after updating visual studio

**Comment by g4mb10r** [comment]
@rachelkang  and @TanayParikh This issue is still actual.  The latest Visual Studio update has broken our ability to pair to a Mac for Xamarin/Maui work.

**Comment by g4mb10r** [comment]
@samhouts The latest Visual Studio release has broken your ability to connect to a Mac for MAUI/Xamarin development.  P1?

**Comment by TanayParikh** [comment]
As others have pointed out above, this issue has been fixed and is pending release. Regardless, this is a tooling issue, and tracked separately from the main `maui` project. 

A temporary workaround may be to try using the [`NuGet.config`](https://github.com/dotnet/maui/blob/main/NuGet.config) file from this repo within your project.

**Comment by Forestbrook** [comment]
@TanayParikh  can you please specify where the tooling issue is tracked?

Using the specified NuGet.config does NOT solve the issue.

**Comment by peter-bozovic** [comment]
Where do we need to save the NuGet.config and how to configure it for the project ?

**Comment by TanayParikh** [comment]
> can you please specify where the tooling issue is tracked?

It doesn't appear to be publicly accessible, but it's available at [10138259](https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could/10138259?port=1025&fsid=d0e0711b-673b-4e2e-b244-7d366f2ded2e&entry=problem).



> Where do we need to save the NuGet.config and how to configure it for the project ?

Based on @Forestbrook's comment above, doesn't look like the nuget config is working. It would be placed at the root of your project (where your csproj is)

**Comment by Forestbrook** [comment]
@TanayParikh please make sure the fix is released asap or make a workaround available. Changing the version number in C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest file does not work for us, neither the NuGet.config workaround.

We cannot build and we are about to release!!!

**Comment by g4mb10r** [comment]
@samhouts and @TanayParikh since we cannot see the VS feedback, is there a priority or ETA associated with it?  Essentially the ability to build for iOS/MacOS with a connected Mac is broken in the latest VS release, which you think would be a high priority to fix?  Can the .MAUI/Xamarin team communicate the severity to the VS team?

**Comment by samhouts** [comment]
I believe we just made the VS feedback public so you can track it now. The issue is resolved and pending release very soon! Thank you for your patience!!

**Comment by g4mb10r** [comment]
@samhouts Thanks!  However, they don't seem to be aware that this issue exists in the production release version, as all the feedback is related to a preview version.

**Comment by leungkimming** [comment]
Hi, I managed to pair Mac with all simulators and build & run my MAUI IOS App in the IOS simulator. My workaround is below:
1. In folder C:\Program Files\dotnet\sdk-manifests, rename the 6.0.300 folder as 6.0.300_bak
2. Copy folder C:\Users\<login user>\.dotnet\sdk-advertising\6.0.300 to C:\Program Files\dotnet\sdk-manifests
3. Reboot my PC (not sure if it is neccessary but to play safe)
4. In my Mac, rename <login user>/library/Caches/Xamarin/XMA to XMA_bak
5. in PC, start VS2022 and pair with Mac. Build and run.

I found that the 6.0.300 in step 1 is newer than that in step 2. Hence, I reverted Microsoft.NET.Workload.Emscripten' version 6.0.9 back to 6.0.4.

Hope it helps.

**Comment by inexuscore** [comment]
> Hi, I managed to pair Mac with all simulators and build & run my MAUI IOS App in the IOS simulator. My workaround is below:
> 
> 1. In folder C:\Program Files\dotnet\sdk-manifests, rename the 6.0.300 folder as 6.0.300_bak
> 2. Copy folder C:\Users<login user>.dotnet\sdk-advertising\6.0.300 to C:\Program Files\dotnet\sdk-manifests
> 3. Reboot my PC (not sure if it is neccessary but to play safe)
> 4. In my Mac, rename /library/Caches/Xamarin/XMA to XMA_bak
> 5. in PC, start VS2022 and pair with Mac. Build and run.
> 
> I found that the 6.0.300 in step 1 is newer than that in step 2. Hence, I reverted Microsoft.NET.Workload.Emscripten' version 6.0.9 back to 6.0.4.
> 
> Hope it helps.

Thanks a ton, that worked. I can't believe how many hours I've wasted on this issue. Unbelievable that the VS team would ship broken toolchains and dependencies without testing first. I hope we get a proper fix soon, fingers crossed.

**Comment by Forestbrook** [comment]
Hi all,

I see alot of you manage to get it working by changing the version number in C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json

This does not work for me. It looks like VS copies WorkloadManifest.json directly from Nuget.

Does anybody know how to change that? Something to change in a NuGet.config?

**Comment by kfrancis** [comment]
> Hi all,
> 
> I see alot of you manage to get it working by changing the version number in C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json
> 
> This does not work for me. It looks like VS copies WorkloadManifest.json directly from Nuget.
> 
> Does anybody know how to change that? Something to change in a NuGet.config?

Same here, none of the workarounds listed here seem to do anything. 6.0.9 just appears on the mac no matter what.

**Comment by jburtjr** [comment]
I am having the same issues.  I have spent most of the day trying the workarounds and so far, nothing is working.  We have a product release forthcoming and now we are dead in the water.  I hope Microsoft puts this as a high priority soon.

**Comment by 3steve3** [comment]
Why is the fix "pending release" since September 7th? This should be considered a critical bug as it is preventing iOS development for .net Maui. It affects both Visual Studio Preview 17.4 and 17.3.4.

**Comment by nickrandolph** [comment]
If you make the suggested change but in the 6.0.400 folder on Windows, and **restart** Visual studio, it appears to work.

**Comment by nickrandolph** [comment]
If you're missing simulators after successfully pairing, you should check what XCode version you've got installed. If XCode 14 you'll need to install 13 alongside and set that as the default in order to get the simulators to appear

**Comment by whann0205** [comment]
Workaround is working but.....
1. You have to take over security of that file so that one is able to change it.
2. Clear all other SDKs as shown in https://www.itnota.com/removing-dot-net-runtime-sdk-macos/
3. Follow the instructions in the URL https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting and delete that XMA Folder.
4. Have Xcode 13 installed again as nick suggested

**Comment by leungkimming** [comment]
> > Hi all,
> > I see alot of you manage to get it working by changing the version number in C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json
> > This does not work for me. It looks like VS copies WorkloadManifest.json directly from Nuget.
> > Does anybody know how to change that? Something to change in a NuGet.config?
> 
> Same here, none of the workarounds listed here seem to do anything. 6.0.9 just appears on the mac no matter what.

I have also tried just changing the verion number in the WorkloadManifest.json file and yes, you are absolutely correct. It is not working.
Therefore, I found another "6.0.300" folder in my profile directory and it is the real original 6.0.4 version. I copied the WHOLE 6.0.300 folder to the dotnet\sdk-manifests folder and reboot. May be I am very lucky. I can continue with my work now.

**Comment by MichaelDWalker** [comment]
> It doesn't appear to be publicly accessible, but it's available at [10138259](https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could/10138259?port=1025&fsid=d0e0711b-673b-4e2e-b244-7d366f2ded2e&entry=problem).

A workaround has been posted today in the above tracked tooling issue: https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could/10138259#T-N10153057. It worked perfectly for me.

**Comment by Forestbrook** [comment]
An update of Visual Studio Preview is available now which should fix the problem. The update does fix the connection problem, but unfortunately introduces other problems. 
See: [https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could-/10138259#T-N10154055](https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could-/10138259#T-N10154055)

**Comment by tradegear** [comment]
This is an absolute show-stopper.  I also can't run Android emulators (a different bug post).  I have two dedicated machines only for dot .net maui, a fresh windows 11, VS 2022 17.3.4, and a fresh mac OS Monterey with last Xcode v13.  Fingers cannot be pointed elsewhere.

**Comment by whann0205** [comment]
Well it works for me at the moment. 
No more Update install for the next time until my apps get production status. 
As i remember i did not got it to work with 17.3 and installed Version 17.4.0 Preview 2.0. 
my mac has also the latest preview version installed. 
Important is patching that file though!
Hope that helps you...

**Comment by vbjack72** [comment]
> Hi, I managed to pair Mac with all simulators and build & run my MAUI IOS App in the IOS simulator. My workaround is below:
> 
> 1. In folder C:\Program Files\dotnet\sdk-manifests, rename the 6.0.300 folder as 6.0.300_bak
> 2. Copy folder C:\Users<login user>.dotnet\sdk-advertising\6.0.300 to C:\Program Files\dotnet\sdk-manifests
> 3. Reboot my PC (not sure if it is neccessary but to play safe)
> 4. In my Mac, rename /library/Caches/Xamarin/XMA to XMA_bak
> 5. in PC, start VS2022 and pair with Mac. Build and run.
> 
> I found that the 6.0.300 in step 1 is newer than that in step 2. Hence, I reverted Microsoft.NET.Workload.Emscripten' version 6.0.9 back to 6.0.4.
> 
> Hope it helps.

Having the same issue, but I do not see folder 6.0.300 in C:\Users<login user>.dotnet\sdk-advertising\6.0.300 the only folder I see under my user folder is 6.0.400

**Comment by lnaie** [comment]
I have the same problem. VS for win & max are up to date on win and mac. The latest .net framework is installed on both OSes.

**Comment by leungkimming** [comment]
There is a Microsoft official workaround. Please refer to 
https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could-/10138259#T-N10154055

**Comment by Forestbrook** [comment]
Now fixed in VS 17.3.5
See: https://developercommunity.visualstudio.com/t/Failed-to-pair-to-Mac-with-error-Could-/10138259#T-N10159813

**Comment by kfrancis** [comment]
![image](https://user-images.githubusercontent.com/67574/192806700-ee70300d-b5e6-4188-980f-75b69a1a6e01.png)

**Comment by Forestbrook** [comment]
> ![image](https://user-images.githubusercontent.com/67574/192806700-ee70300d-b5e6-4188-980f-75b69a1a6e01.png)

Press OK to continue.
Everything seems to works fine with XCode 13.4, I do not have errors with the build.

**Comment by prollin** [comment]
This issue is back after updating to 17.3.6

**Comment by AndreasReitberger** [comment]
> This issue is back after updating to 17.3.6

Have you tried to redo the workaround?

**Comment by prollin** [comment]
In `~/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk-manifests/6.0.300/microsoft.net.workload.emscripten/WorkloadManifest.json` I simply replaced `6.0.4` with `6.0.9`

Quick follow-up question: why is 6.0.300 even relevant here; shouldn't it only use 6.0.400 (or whatever is the latest SDK available)

**Comment by EmilyFeng97** [comment]
I have verify this issue on Dev17.3.6, the results as following.
1. After creating a 6.0 MAUI project, pair to mac is successful, but fails to launch and start debugging due to error [1638401](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1638401).
3. After installing Xamarin.ios, pair to mac fails with error [1611102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1638401). If I follow these steps in [Private dotnet SDK and workloads - XMA Installation - Overview (azure.com)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30667/Private-dotnet-SDK-and-workloads-XMA-Installation), I can successfully pair to the mac and build the project correctly.

**Comment by Forestbrook** [comment]
> I have verify this issue on Dev17.3.6, the results as following.
> 
> 1. After creating a 6.0 MAUI project, pair to mac is successful, but fails to launch and start debugging due to error [1638401](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1638401).
> 2. After installing Xamarin.ios, pair to mac fails with error [1611102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1638401). If I follow these steps in [Private dotnet SDK and workloads - XMA Installation - Overview (azure.com)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30667/Private-dotnet-SDK-and-workloads-XMA-Installation), I can successfully pair to the mac and build the project correctly.

@EmilyFeng97  [Private dotnet SDK and workloads - XMA Installation - Overview (azure.com)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30667/Private-dotnet-SDK-and-workloads-XMA-Installation) is not publicly available. Can you ask to make it available, or copy the instructions?

**Comment by EmilyFeng97** [comment]
> @EmilyFeng97 [Private dotnet SDK and workloads - XMA Installation - Overview (azure.com)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30667/Private-dotnet-SDK-and-workloads-XMA-Installation) is not publicly available. Can you ask to make it available, or copy the instructions?

Sorry, I can't give you the file [Private dotnet SDK and workloads - XMA Installation - Overview (azure.com)](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30667/Private-dotnet-SDK-and-workloads-XMA-Installation) because it contains some internal feeds. As bug [1611102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1611102) will be resolved and a pull request is being merged. After the error get fixed, you can try again.
