### ISSUE TITLE
Changing properties on MauiIcon, MauiImage and MauiSplashScreen sometimes does not regenerate images

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#9803]
### Description

In some cases, changing Color, TintColor, BaseSize or some other property on the various Maui* items in the .csproj do not cause an update.

There are also some special cases as well:
 - iOS Hot Restart from Windows: #8685
 - Tint colors not working: https://github.com/dotnet/maui/issues/7206
 - Windows icons: #5162

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Run the app
3. Change/add a relevant property on the Maui* items
4. Observe that some don't cause the app to get updated

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

**Comment by DRAirey1** [comment]
I can't say I've got a 100% work around, but if you delete the 'obj' and 'bin' folders, then do a Rebuild All, I've managed to get some sense of repeatability when I change visual assets.

**Comment by DRAirey1** [comment]
> I can't say I've got a 100% work around, but if you delete the 'obj' and 'bin' folders, then do a Rebuild All, I've managed to get some sense of repeatability when I change visual assets.

Nope. I take it back. This crappy environment has no repeatability at all. If it's a Tuesday in September, than this solution works. If it's a day of the week that begins with 'S' then it fails. This environment defies all logic.

**Comment by mattleibow** [comment]
@DRAirey1 what visual assets? Which platform? There is this big one about splash and iOS: https://github.com/dotnet/maui/issues/8685

**Comment by mattleibow** [comment]
Closing this now as I think we fixed most issues and have separate issues for other items.

If there are any specific ones, please open a new issue so we can work on them instead of my big "things are broken, but not sure".
