### ISSUE TITLE
Border in ScrollView will flicker when scroll on Android

### ISSUE THREAD

**Issue by xtuzy** [dotnet/maui#9805]
### Description

I try use Border wrap a ContentView, and set it in ScrollView, when i scroll it, border will flicker on Android.

https://user-images.githubusercontent.com/17793881/187607492-36687c6d-c3d5-4d18-aebe-05b1dc12405d.mp4

Set center Border StrokeThickness="2", also show little flicker

https://user-images.githubusercontent.com/17793881/187607743-d3255dc9-7c51-4b00-a4a0-51cedf2cdcf6.mp4

On iOS is Ok:

https://user-images.githubusercontent.com/17793881/187608058-def39374-6970-4784-902a-d4b3fad26865.mp4

On Windows is Ok:

https://user-images.githubusercontent.com/17793881/187608163-02dded3e-fab5-4d3a-b404-ccfc93e710c7.mp4

### Steps to Reproduce

1. Run this example 
[MauiAppScrollviewBorderBug1.zip](https://github.com/dotnet/maui/files/9459050/MauiAppScrollviewBorderBug1.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

**Comment by jsuarezruiz** [comment]
Can see the issue on 6.0.486 but, on current main branch cannot reproduce the issue:
![issue-border-scroll](https://user-images.githubusercontent.com/6755973/187659862-f7d1dfa3-9759-4f54-b152-65fea3297b97.gif)
The code to invalidate the Border (stroke, strokethickness etc) is not invoked. We need to review it with more details.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on Android platform with sample project. [MauiAppScrollviewBorderBug1.zip](https://github.com/dotnet/maui/files/9459050/MauiAppScrollviewBorderBug1.zip)
