### ISSUE TITLE
get_IsLoaded throws ObjectDisposed exception

### ISSUE THREAD

**Issue by alexdi220** [dotnet/maui#9806]
### Description

Hello, I have a test for Android where I change the application's theme. I get the ObjectDisposed exception. Take a look at the screenshot (the emulator have crashed when I try to catch any exception). For iOS, it works fine. The exception throws because the native view has been disposed of. But I guess the getter of MAUI.View.IsLoaded shouldn't throw it. You need to check that the android view disposed and return false if it.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/47348109/187622536-4afa30ab-18dc-4d4e-9885-ba1451d313a5.png)

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

**Comment by jsuarezruiz** [comment]
Could you attach a sample where reproduce the issue?. Thanks in advance!

**Comment by alexdi220** [comment]
> Could you attach a sample where reproduce the issue? Thanks in advance!

Unfortunately, the project is large and contains our production code. Also, the test will be failed when all tests run. So, it depends on the random environment - guess a view which I check IsLoaded from another test. I subscribe to the RequestedThemeChanged event and change the appearance of my component. If IsLoaded is false I don't do it. Even if the native view is disposed I shouldn't worry about it. In this case, the IsLoaded should return me a false.

Looks like you need to check that the Handler is disposed or disconnected
![image](https://user-images.githubusercontent.com/47348109/187627614-55a55f32-dd3e-4f0f-86fe-70a92edd724e.png)

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/pull/9811

**Comment by mattleibow** [comment]
Fixed in https://github.com/dotnet/maui/pull/9811
