### ISSUE TITLE
[iOS] CarouselView DataTemplateSelector NullReferenceException

### ISSUE THREAD

**Issue by Phenek** [dotnet/maui#9833]
### Description

I was moving my playground project from direct List\<View\> in ItemsSource to DataTemplateSelector
as suggested @PureWeen for best practise on this Android issue #7884.

But this best practise just crash on iOS

<img width="1271" alt="Screenshot 2022-09-01 at 01 02 15" src="https://user-images.githubusercontent.com/4518686/187802103-16718ac8-d70d-46ff-95e6-3c15033d29c3.png">

### Steps to Reproduce

- Open this file from the reproduction project repository [MainPage.xaml.cs](https://github.com/Phenek/ScrollConflicts/blob/main/MainPage.xaml.cs)

````
        Content = new CarouselView
        {
            ItemTemplate = new TabTemplateSelector
            {
                Tab1 = new DataTemplate(() => new Tab1()),
                Tab2 = new DataTemplate(() => new Tab2()),
                Tab3 = new DataTemplate(() => new Tab3())
            },
            ItemsSource = new List<int> { 1, 2, 3 }
        };
	}
````
````
    public class TabTemplateSelector : DataTemplateSelector
    {
        public DataTemplate Tab1 { get; set; }
        public DataTemplate Tab2 { get; set; }
        public DataTemplate Tab3 { get; set; }

        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            switch ((int)item)
            {
                case 1:
                    return Tab1;
                case 2:
                    return Tab2;
                default:
                    return Tab3;
            }
        }
    }
````

### Link to public reproduction project repository

https://github.com/Phenek/ScrollConflicts.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by mlancione** [comment]
Any update on this issue?
