### ISSUE TITLE
[MAC-CATALYST] Presses methods not triggered for input keys in Entry

### ISSUE THREAD

**Issue by Lakshminatarajan** [dotnet/maui#9838]
### Description

PressesBegan and PressesEnded override methods not triggered when typing text in the Entry. Only the input keys such as Alphabets, numbers and delete keys are not detected.

This scenario occurs only on mac-catalyst and iOS working fine.

### Steps to Reproduce

1. Run the attached sample in mac.
2. Click the entry and type.

Expected behavior: PressesBegan and PressesEnded methods should be triggered when typing.
Actual behavior: PressesBegan and PressesEnded methods not triggered.

### Link to public reproduction project repository

[Sample](https://www.syncfusion.com/downloads/support/common/2915/ze/DemoIssue_b37b5479.zip)

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacCatalyst-15.4.442

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

**Comment by PureWeen** [comment]
Can you attach a simplified repo or a public one please?

**Comment by Lakshminatarajan** [comment]
Hi @PureWeen ,

Please find the replication sample below,
[DemoIssue_b37b5479.zip](https://github.com/dotnet/maui/files/9488750/DemoIssue_b37b5479.zip)

**Comment by rmarinho** [comment]
Hi @rkops-bd and @Lakshminatarajan thanks for your report, I had some time to look at the issue and this seems to be an issue with Apple's MacCatalyst and not with MAUI or the iOS dotnet sdk. 

I have tried this in .net iOS and got the same issues, then I went to try on objective c MacCatalyst app and I also get the same. So this seems a problem with Catalyst. You should open a bug with Apple at https://developer.apple.com/bug-reporting/ 

here's the .net iOS code I used:
```
 public partial class ViewController : UIViewController
 {
        public override void ViewDidLoad ()
        {
            View.Add(new CustomTextField());
            base.ViewDidLoad ();
        }
    }

    public class CustomTextField : UITextField
    {
        public CustomTextField()
        {
            Text = "hello";
            BackgroundColor = UIColor.Cyan;
            Frame = new CoreGraphics.CGRect(20, 20, 320, 100);
        }

        public override void PressesBegan(NSSet<UIPress> presses, UIPressesEvent evt)
        {
            System.Diagnostics.Debug.WriteLine($"NativeCustomEntry: PressesBegan {presses.AnyObject.Key.KeyCode.ToString()}");
            base.PressesBegan(presses, evt);
        }
}
```

here the objective C code I used
```
@implementation ViewController

- (void)viewDidLoad {
    CGRect customFrame = CGRectMake(50, 50, 400, 50);
    CustomTextField *textField = [[CustomTextField alloc] initWithFrame:customFrame];
    textField.text = @"hello";
    [self.view addSubview:textField];
    [super viewDidLoad];
}

@end

@implementation CustomTextField

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        self.delegate = self;
    }
    self.backgroundColor = UIColor.systemPinkColor;
return self;
}

- (void)pressesBegan:(NSSet<UIPress *> *)presses withEvent:(UIPressesEvent *)event
{
    NSLog(@"NativeCustomEntry: PressesBegan %ld",  presses.anyObject.key.keyCode);
}

@end
```

Thanks best regards 
Rui
