### ISSUE TITLE
Layout of Grid contents not updated when IsVisible changes

### ISSUE THREAD

**Issue by jrc14** [dotnet/maui#9850]
### Description

In some cases, when I change the IsVisible property of an element inside a Grid, the Grid's size is not correctly updated.  It seems to happen in cases when a Grid is the content of another Grid for instance in code like:

```
        <Grid
            VerticalOptions = "Center"
            HorizontalOptions = "Fill">
            <Grid
                VerticalOptions = "Center"
                HorizontalOptions = "Fill">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"></RowDefinition>
                    <RowDefinition Height="Auto"></RowDefinition>
                </Grid.RowDefinitions>
                <Label
                    Text="Click the button to hide this text"
                    FontSize="16"
                    IsVisible="True"
                    Grid.Row="0" />
                <Button
                    Text="Click me"
                    HorizontalOptions="Center"
                    Grid.Row="1"/>
            </Grid>
        </Grid>
```
Though it displays OK when first run, if you set the Label's IsVisible property to false and then back to true, the Grid does not then expand again to show both the label text and the button.

### Steps to Reproduce

Build and run the repro code below.  It will show this:
![image](https://user-images.githubusercontent.com/5305671/187917969-7739776f-eefa-4aca-a85e-4e8a724b73cb.png)

Click the 'click me' button.  On the first click the text will be hidden at the grid will shrink accordingly:
![image](https://user-images.githubusercontent.com/5305671/187918193-f805f2ac-4191-4c4c-af9a-29439d543169.png)

Click it again.
EXPECTED BEHAVIOUR is that the grid will expand again to show its content,
ACTUAL BEHAVIOUR is that the grid does not expand, giving this appearance:
![image](https://user-images.githubusercontent.com/5305671/187918546-fc233a2e-3e7e-4365-8d34-36724449b7b6.png)

### Link to public reproduction project repository

https://github.com/jrc14/VisibilityTest

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No workaround so far.

**Comment by josh-aw** [comment]
#9078

**Comment by PureWeen** [comment]
This should be resolved with .NET7
Let me know if you still have the issue once it lands

**Comment by hector2d2** [comment]
What I do when faced with this problem is to re-update (render) the entire grid. In the same way, I use an IsLoading variable and create another variable for the grid, for example IsGridVisible. and when I modify the IsLoading variable it would be like this:

```
IsGridVisible = false;            
IsLoading = false;
IsGridVisible = true;
```
I've also had to use it when I get information from an api and it doesn't update on the screen.

**Comment by jrc14** [comment]
> This should be resolved with .NET7 Let me know if you still have the issue once it lands

Can you give any update as to when .NET7 MAUI will be generally available? (or what I might do to get early access).  The issue is blocking for me at the moment.

**Comment by jrc14** [comment]
> What I do when faced with this problem is to re-update (render) the entire grid. In the same way, I use an IsLoading variable and create another variable for the grid, for example IsGridVisible. and when I modify the IsLoading variable it would be like this:
> 
> ```
> IsGridVisible = false;            
> IsLoading = false;
> IsGridVisible = true;
> ```
> 
> I've also had to use it when I get information from an api and it doesn't update on the screen.

Thanks for the input.  In my particular case, deleting and recreating the Grid isn't a great solution (as well as being inefficient, it's going to make the UI appear quite glitchy).  I will try to work around it by using AbsoluteLayout instead of Grid.  My code-behind can in principle figure out the right sizes and positions for the child elements, based on which of them are visible; it will just mean some rather ugly coding to duplicate the logic that Grid ought to implement.

**Comment by jrc14** [comment]
https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
