### ISSUE TITLE
Exception occurs when using System.IO.Ports

### ISSUE THREAD

**Issue by trantamcdt92** [dotnet/maui#9870]
### Description

I am using SerialPort class to open a serial device on MacOS (Monterey), an exception occurs when I call Open function
Example Code:
SerialPort port = new SerialPort();
port.Open("/dev/cu.usbxxxx");

Exception: "System.DllNotFoundException: libSystem.IO.Ports.Native"

I'd like to ask how to fix this issue.

### Steps to Reproduce

1. Create a .NET MAUI App

2. In MainPage() function, create an instance of SerialPort class and then call Open() method

3. Build and Run the App

### Link to public reproduction project repository

Can't share

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

OSX 10.13

### Did you find any workaround?

No

**Comment by rmarinho** [comment]
@rolfbjarne  any idea on this?

**Comment by rolfbjarne** [comment]
This works for me - I get an expected exception instead:

```
Unhandled exception. System.UnauthorizedAccessException: Access to the port '/dev/cu.usbxxxx' is denied.
 ---> System.IO.IOException: No such file or directory
   --- End of inner exception stack trace ---
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at AppDelegate.Main(String[] args) in /Users/rolf/test/dotnet/macos/AppDelegate.cs:line 12
```

please provide a sample project we can use to reproduce this.

**Comment by samirgcofficial** [comment]
<img width="1440" alt="Screen Shot 2022-09-04 at 8 33 49 AM" src="https://user-images.githubusercontent.com/55045516/188296019-504d00e4-f010-45c1-b88b-c50fb77c0fe2.png">
I too get the same error when i try to release the iOS Project. 'Debug` works fine for me. [Repo is a prod app]

**Comment by mattleibow** [comment]
@samirgcofficial Your error is that a file is not accessible during build time. Could you open a new issue for that? This issue is a runtime issue when trying to use ports.

**Comment by mattleibow** [comment]
@trantamcdt92 Maui does not do anything nor does it provide code around opening ports. Could you please open a new issue (along with a sample) over on the macOS/iOS SDK repo: https://github.com/xamarin/xamarin-macios/issues

**Comment by trantamcdt92** [comment]
Hello @mattleibow 

Sorry for late reply. I can do a workaround for this issue by copying manually the libSystem.IO.Ports.Native.dylib file from MonoBundle folder of Visual Studio (Preview) to MonoBundle folder of my application.

**Comment by trantamcdt92** [comment]
Somehow, libSystem.IO.Ports.Native.dylib is not automatically copied to the bundle of applications. Did I set up something wrong?

**Comment by mattleibow** [comment]
@trantamcdt92 probably not. Sounds like the mac packaging step did not include the dylib for some reason. The sdk team will know.

**Comment by trantamcdt92** [comment]
@mattleibow I see. Should I create another issue ticket? or will you reopen this ticket?

**Comment by trantamcdt92** [comment]
I created this ticket https://github.com/xamarin/xamarin-macios/issues/15874
Please help to investigate it

Thank you
