### ISSUE TITLE
Button/ImageButton's Border has a default value on Windows

### ISSUE THREAD

**Issue by AllenMiaoFil** [dotnet/maui#9871]
### Description

When I tried to add a Button and an ImageButton into page,  there is a default button border around Button, but I've never set button border. I must set it to 0 explicitly so that the Border is removed. and it also effect ImageButton.  
In below screenshot you can see the Button2 has a default BorderThickness(Im not quite sure it is the root issue, but when I tried to modify it's value, the border width is modified).
![image](https://user-images.githubusercontent.com/100921408/188139906-b40ca4aa-6c00-4da5-afb8-9d05478fc57f.png)

This below screenshot you can see the Button3, I set BorderWidth="0", then it works well(But the default BorderThickness value is 1, I think maybe BorderWidth style override the default value).
![image](https://user-images.githubusercontent.com/100921408/188139833-08860eaf-7788-402d-afa1-6d73c728dbf1.png)

It also has seem issue on ImageButton, but I can't reproduce in this simple project, can do you a research on ImageButton?
I can show my pervious screenshot.
![image](https://user-images.githubusercontent.com/100921408/188140794-e6637386-860a-4fd0-b49e-e034e3ff8109.png)

### Steps to Reproduce

1.Create a MAUI project
2. Add a Image button and set button BackgroundColor to Transparent.
3. Add a Button set button BackgroundColor to Transparent.
4. Run program.

This issue only on Windows, I checked on MacOS, it works well. I also attached a simple project.
[ImageButton.zip](https://github.com/dotnet/maui/files/9477766/ImageButton.zip)

### Link to public reproduction project repository

No repository

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window10

**Comment by jsuarezruiz** [comment]
The default value of StrokeThickness is -1 and with that value, Windows is using the default value. We can solve this, and the attached example would be:

![image](https://user-images.githubusercontent.com/6755973/189310546-fade3622-214b-4b44-be0a-74a8620fcf65.png)

However, buttons without a background color would look different:
![image](https://user-images.githubusercontent.com/6755973/189310628-5562dcc8-f9e7-469b-81b7-d97bd23f6140.png)

From the current behavior:
![image](https://user-images.githubusercontent.com/6755973/189311564-355a5189-8915-46d0-a343-dc118c2fa68a.png)

**Comment by jsuarezruiz** [comment]
> The default value of StrokeThickness is -1 and with that value, Windows is using the default value. We can solve this, and the attached example would be:
> 
> ![image](https://user-images.githubusercontent.com/6755973/189310546-fade3622-214b-4b44-be0a-74a8620fcf65.png)
> 
> However, buttons without a background color would look different: ![image](https://user-images.githubusercontent.com/6755973/189310628-5562dcc8-f9e7-469b-81b7-d97bd23f6140.png)
> 
> From the current behavior: ![image](https://user-images.githubusercontent.com/6755973/189311564-355a5189-8915-46d0-a343-dc118c2fa68a.png)

@Redth What do you think?

**Comment by Redth** [comment]
@mattleibow you did a fair amount of work in this area, to me this seems like we don't want to make this change and it's expected you must override the defaults explicitly.

**Comment by jsuarezruiz** [comment]
Testing with the latest 7.0 version, the behavior is the correct one:
![image](https://user-images.githubusercontent.com/6755973/231690884-03f83627-1e83-4af3-9ce9-a25744362ec4.png)

By default, set the default BorderWidth, setting 0 remove the Border and setting a custom value modify the border thickness.
