### ISSUE TITLE
Android ImageSource.FromFile mistakenly displays MauiImage file rather than FileSystem file when filename is the same

### ISSUE THREAD

**Issue by hbraasch** [dotnet/maui#9883]
### Description

There are two images in the system. One is a MauiImage, the other is a file in the file system. For the sake of the demo, the images content differ. They have the same filename.
Under Android, when filling an image using ImageSource.FromFile, the app mistakenly displays the MauiImage rather than the FileSystem file. It works correctly under Windows and iOS
Here is the display under Android, it shows a repeat of the same image

![AndroidWrong](https://user-images.githubusercontent.com/7484186/188255111-ed735c7a-e677-43c1-9ad2-213cff775572.png)

Here is a display under Windows, it shows two different images

![WindowsOk](https://user-images.githubusercontent.com/7484186/188255119-06285c38-c989-48ac-bc7c-fe24c6829121.png)

Here is the display under iOS, it shows two different images
![iOS_OK](https://user-images.githubusercontent.com/7484186/188255123-29099596-f8e3-4558-8a75-991907de75a3.png)

A simple repro has been provided under https://github.com/hbraasch/ImageSourceConfusionTester.git

### Steps to Reproduce

1. Install the repro project [https://github.com/hbraasch/ImageSourceConfusionTester.git] under VS
2. Run it for the three different targets, notice the difference
3. The effective code is in the file [StartupPage.cs]

### Link to public reproduction project repository

https://github.com/hbraasch/ImageSourceConfusionTester.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31, Android 11 = API 30

### Did you find any workaround?

Ensure the filename in the file system is different, but that unneccesarilly complicates code. My app needs the image content to be the same, only the resolutions to differ, thats why I want it to be named the same.

**Comment by mattleibow** [comment]
fixed in https://github.com/dotnet/maui/pull/9926

**Comment by Eilon** [comment]
@mattleibow / @Redth - this is an open bug sitting in 6.0-sr5. DOes it need to be closed in this milestone, moved to another milestone, or some other action?
