### ISSUE TITLE
Splash Icon displayed in a circle and cut off

### ISSUE THREAD

**Issue by Neralem** [dotnet/maui#9886]
### Description

When setting up a custom splash screen in my maui app, it is displayed inside a circle and cut off. 

I gave my svg a red rectangle to fill the whole view box so one can see where it is cut off.

The behavior I want and expected is that the width of my svg is equal to the width of the entire screen and nothing is cut off.

This is what it looks like. I've replaced the original splash.svg file and and tried some BaseSize values but no success.

This is what I have:
![image](https://user-images.githubusercontent.com/49270443/188267008-dab8ff92-529a-47f6-9da3-7643763eeccf.png)

This is what I want:
![image](https://user-images.githubusercontent.com/49270443/188267195-8594527c-69f2-4f61-85fa-78481c83d836.png)

Here is just the svg:
![splash](https://user-images.githubusercontent.com/49270443/188267223-b0a226dc-a9e9-4bc3-b2dc-83b8f3f10f36.svg)

### Steps to Reproduce

1.: Clone repo
2.: Deploy to android
3.: Start App
4.: See what I showed in the screenshot

The repo is just a fresh maui app with a different splash.svg

### Link to public reproduction project repository

https://github.com/Neralem/CustomSplashBugTest

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12.0 - API 31

**Comment by janseris** [comment]
Fixed by https://github.com/dotnet/maui/pull/9797 in upcoming Service release 5
