### ISSUE TITLE
Android Emulator Tries to Start but then Crashes and Disappears

### ISSUE THREAD

**Issue by geno333** [dotnet/maui#9897]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/device-setup
Operating System: windows

I'm trying to follow the tutorial, but no matter what i've tried,
the Android Emulator Tries to Start but then Crashes and Disappears

**Comment by arsalanhub** [comment]
Same problem I am also facing. Do let me know if you know how to run it on a Local Device.

**Comment by geno333** [comment]
Yes, Mohammad, I’ll let you know about anything that turns up.  Please do the same

**Comment by jfversluis** [comment]
Hey there, thanks for reporting this! That is not the first experience we want you to have obviously. Unfortunately, this seems to have something to do more with tooling and/or Visual Studio. As such, it should be reported in a different place. That way, all the appropriate logs and such will automatically be collected and sent over to the right team that should be able to help you further. I will put on a label that triggers a comment that will give you all the information on how to proceed.

Hope you'll get it resolved quickly so you can get working on that amazing .NET MAUI app!

**Comment by geno333** [comment]
Thanks for pointing me in the right direction, Gerald!

I will put the report into the VS reporting system
