### ISSUE TITLE
Image size is not stable on MacOS and iOS

### ISSUE THREAD

**Issue by try0** [dotnet/maui#9899]
### Description

Sets the image source in code-behind, the display size may be different even if the same process is executed.  
This issue occurs on MacOS or iOS.

### Steps to Reproduce

1. Sets source in code-behind.
```c#
img.Source = ImageSource.FromStream(() => stream);
```

2. Run on MacOS or iOS

---

Click the button a couple of times, the drawn size changes.
https://github.com/try0/MauiAppTest/blob/main/MauiAppTest/MainPage.xaml.cs#L30

### Link to public reproduction project repository

https://github.com/try0/MauiAppTest

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS15, macOS Monterey 12.5.1

### Did you find any workaround?

After copying the file to the cache directory, loading it using ImageSource.FromFile renders fine.

**Comment by try0** [comment]
![MacOS](https://user-images.githubusercontent.com/17096601/188299610-1a36f19c-eafd-4de6-8c7e-9e0caf63f8f3.gif)

**Comment by drasticactions** [comment]
I think I hit a similar issue to this. When you look at the border behind the image as I update it, you can see the width be inconsistent. Sometimes it's contained to the image width, other times the window. 

https://user-images.githubusercontent.com/898335/189021372-5653f3b1-ba60-4b9d-9ca7-008d122947ba.mov

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. [MauiAppTest](https://github.com/try0/MauiAppTest)

**Comment by jfversluis** [comment]
Using version 8.0.80 I cannot reproduce this anymore using the repro provided. Could you please confirm?
