### ISSUE TITLE
The image is not rendered on iOS only the first time 

### ISSUE THREAD

**Issue by try0** [dotnet/maui#9902]
### Description

The image is not rendered on iOS only the first time when the image source is set in code-behind.

Not rendered at page initialization.
https://github.com/try0/MauiAppTest/blob/main/MauiAppTest/MainPage.xaml.cs#L11

When the source is set up again, it is render correctly.
https://github.com/try0/MauiAppTest/blob/main/MauiAppTest/MainPage.xaml.cs#L26

### Steps to Reproduce

1. Sets source in code-behind.
2. Run on iOS.

### Link to public reproduction project repository

https://github.com/try0/MauiAppTest

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS15

### Did you find any workaround?

After copying the file to the cache directory, loading it using ImageSource.FromFile renders fine.

**Comment by AlanGusLive** [comment]
@try0 : I can't test on IOS, but I think you can try this:
1) In the MainPage.xaml, add the event `Loaded="ContentPage_Loaded"`
2) In the MainPage.xaml.cs replace All `RenderImageAsync();` by `await RenderImageAsync();`
3) In the MainPage.xaml.cs replace `private void RenderImageAsync()` by `private async Task RenderImageAsync()`
4) In the MainPage.xaml.cs in the constructor move `await RenderImageAsync();` to the function `private async void ContentPage_Loaded(object sender, EventArgs e)`

Sample to test on IOS:
[MauiAppTestIOS.zip](https://github.com/dotnet/maui/files/9484810/MauiAppTestIOS.zip)

**Comment by try0** [comment]
@AlanGusLive 

Thanks for suggesting a workaround.
However the result was the same, not rendered.

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Can repro on iOS platform with sample project. [MauiAppTest](https://github.com/try0/MauiAppTest)

**Comment by jadenrogers** [comment]
@try0 Did you ever solve it, got the same issue

**Comment by try0** [comment]
@jadenrogers 

No, I never did. 
See `Did you find any workaround?`

**Comment by jfversluis** [comment]
Using version 8.0.80 I cannot reproduce this anymore using the repro provided. Could you please confirm?
