### ISSUE TITLE
[MAUI-Windows] "Element not found. (0x80070490)" exception occurs when ScrollView is inside a FlexLayout

### ISSUE THREAD

**Issue by Deepak1799** [dotnet/maui#9905]
### Description

When placing scrollview inside a flexlayout, I am facing the following exception in this latest release.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/65169077/188312061-d46b20a2-1105-4205-9ae8-8c317f6c257c.png">

### Steps to Reproduce

1. Run the linked MAUI sample project.
2. The exception will occur directly.

_**Note: This crash occurs from the latest release of MAUI 6.0.486**_

### Link to public reproduction project repository

https://github.com/Deepak1799/.NET-MAUI-Samples/tree/master/ScrollViewInFlexLayout

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.424

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

This is not a workaround, but setting HeightRequest and WidthRequest to the flex layout does not cause the crash.

### Relevant log output

```shell
Error Message: "Element not found. (0x80070490)"
Error Code: -2147023728
```

**Comment by holecekp** [comment]
I have the same problem but an app with a FlexLayout crashes with the same exception even without a ScrollView. I have created a simple repro project for it:
https://github.com/holecekp/MauiBugFlexLayout

The crashes are on Windows only. It does not crash on Android, but the FlexLayout is rendered incorrectly there.

**Comment by hartez** [comment]
Digging into this, it appears that "Element not found" is a red herring; the underlying problem is a layout cycle.

**Comment by Qws** [comment]
I have this issue too.

Maui needs a dynamic and reliable flex solution. That dynamically wraps the controls based on container size.

In UWP/WinUI3 there is GridView. In HTML/CSS there is Flex display.
