### ISSUE TITLE
.NET MAUI Maps custom object in map Pin

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#9909]
### Description

Map Pin currently has some basic properties such as string Name.
It would be useful, if it had object Tag which could be any value related to the pin, e.g. Animal which is at that location etc.

### Public API Changes

new property in Pin called Tag of type object

### Intended Use-Case

associate custom value with map Pin

**Comment by janseris** [comment]
@VladislavAntonyuk cool,  what about offline map or custom image tiles provider for the map control? It is somewhere near or not possible at all now?

**Comment by VladislavAntonyuk** [comment]
I don’t know if offline maps api available in native Map of each platform.
https://issuetracker.google.com/issues/35827808?pli=1

**Comment by janseris** [comment]
> @janseris What does this give us that we can't accomplish by subclassing `Pin`? It seems like we already have a mechanism available to add arbitrary properties to a pin.

It gives a builtin use case for associating values with Pins. This is available in most paid third party desktop control vendors Map controls and is in my opinion often useful.

**Comment by jfversluis** [comment]
I don't see a whole lot of traction here by other people wanting this and there is a pretty straight-forward "workaround" by subclassing it so you have a strongly-typed way of doing this. I don't think we'll be adding this in the near future, therefore closing this for now.
