### ISSUE TITLE
Fails build on Microsoft-openjdk@17

### ISSUE THREAD

**Issue by ss-proc** [dotnet/maui#9912]
### Description

Hi, I'm a newbie trying to setup my machine for maui. I'm using Rider as my IDE and I already have the Microsoft-openjdk@17 (LTS) installed. But when I run a new maui app, I see this error:

```
  Microsoft.Android.Sdk.Tooling.targets(20, 5): [XA0030] Building with JDK version `17.0.4.1` is not supported. Please install JDK version `11.0`. See https://aka.ms/xamarin/jdk9-errors
```

### Steps to Reproduce

1. Install openjdk using https://docs.microsoft.com/en-ca/java/openjdk/install#install-on-macos
2. Install dotnet for macOS https://dotnet.microsoft.com/en-us/download/dotnet/6.0
3. File > New Maui APP
4. Build and run

### Link to public reproduction project repository

Brand new maui app on macOS

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS

### Did you find any workaround?

Installed older version of jdk brew install --cask microsoft-openjdk11 but note that openjdk 17 is the latest LTS. So I want this to work with openjdk 17

**Comment by jfversluis** [comment]
Hey @ss-proc thanks for this! It looks like you're confusing 2 different versions of OpenJDK. The "regular" OpenJDK might indeed have a version 17 that is the current LTS version, however, .NET MAUI is using the _Microsoft_ OpenJDK [build](https://docs.microsoft.com/java/openjdk/overview). You'll have to have that installed with the specified version to make .NET MAUI work.

Good luck!
