### ISSUE TITLE
CollectionView: ScrollTo does not work [Windows11, Android11/12, iOS not tested]  dotnet --version: 6.0.400

### ISSUE THREAD

**Issue by leoderja** [dotnet/maui#9920]
### Description

ScrollTo method is not working.

### Steps to Reproduce

Please, see the Link to [public reproduction project repository](https://github.com/leoderja/MAUI_CollectionView_ScrollTo)

It has a 1) CollectionView filled with 40 items and 2) a Button with this code attached on "Clicked" event handler:

cvItemCollection.ScrollTo(25, position: ScrollToPosition.MakeVisible);

### Link to public reproduction project repository

https://github.com/leoderja/MAUI_CollectionView_ScrollTo

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 / 12, Windows 11

### Did you find any workaround?

No workarounds

### Relevant log output

```shell
No
```

**Comment by mattleibow** [comment]
You say the ScrollTo method is not working. Could you describe what is happening? Crash? Not scrolling? Scrolling to a wrong item?

Also, in your repro project, I see you have the CollectionView in a ScrollView. What happens if you take the CV out of the SV?

**Comment by leoderja** [comment]
Hi matt,
CV out of the SV, scrolls well with the ScrollTo method...
Thank you for your feedback and sorry for the inconveniences..
