### ISSUE TITLE
RemainingItemsThresholdReachedCommand inside CollectionView does not get triggered on windows platform

### ISSUE THREAD

**Issue by MissedSte4k** [dotnet/maui#9935]
### Description

RemainingItemsThresholdReachedCommand does not work on Windows. It works on other platforms I've tested (Android, iOS).

### Steps to Reproduce

1. open my sample project 
https://github.com/MissedSte4k/MAUI-RemainingItemsThreshold-not-workeing-example
2. Launch on Windows platform
3. Try to reach the bottom of the collection

Expected:
Collection is updated and you can't reach the bottom

Actual results: 
You can reach the bottom

Try the app on the Android. It woks as intended

### Link to public reproduction project repository

https://github.com/MissedSte4k/MAUI-RemainingItemsThreshold-not-workeing-example

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK

**Comment by dannymonteiro** [comment]
I've ran into this issue too, works on Android, but on Windows it doesn't. :(

**Comment by nicop85** [comment]
+1 to this issue. It is still happening on WinUI. Please consider moving it up the priority list.

**Comment by nicop85** [comment]
@dannymonteiro Thanks for sharing that! I will try that until they fix this
