### ISSUE TITLE
[WinUI] Frame with an Entry causes app to freeze

### ISSUE THREAD

**Issue by ghost** [dotnet/maui#9937]
### Description

Whenever an Entry underneath a Frame has its properties Text and IsPassword set, the app freezes when ran on WinUI. I've attached a sample app that showcases the issue.

### Steps to Reproduce

1. Open the MauiApp1 app I've attached
2. Run the app on WinUI
3. App freezes
[MauiApp1.zip](https://github.com/dotnet/maui/files/9495008/MauiApp1.zip)

Without opening the sample app:
1. Create a new Maui app
2. Add a StackLayout to the MainPage.xaml
3. Add a Frame to the StackLayout
4. Add an Entry to the Frame
5. Set the Text property of the Entry to for instance "blabla"
6. Set the IsPassword property of the Entry to True
7. Run the app on WinUI
8. The app freezes

### Link to public reproduction project repository

https://github.com/ProgressiveDeyo/MauiApp1

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10

**Comment by jsuarezruiz** [comment]
When you mean the app freezes, you can't write or do resizing etc. Cannot reproduce the issue.

![issue-9937](https://user-images.githubusercontent.com/6755973/188622581-5708e676-b3a5-4347-a991-873218c65dea.gif)

**Comment by filipDN** [comment]
Same on my side, it will freeze if you set text in xaml with long text (10+ characters)

**Comment by filipDN** [comment]
Workaround is to use border instead of frame

![image](https://user-images.githubusercontent.com/98592429/188863566-ee68df8a-7802-4ccb-a680-0a7845ac3cc4.png)

**Comment by EmanterolaDN** [comment]
I will explain it a little bit...

When you set a frame with a nested entry with Text>5 char long (No matter if is hardcoded or binded), then that view freezes on loading.
If you set initial value length to <=5 it works properly (Then you can write, delete, and so on like @jsuarezruiz does):

If you set XAML design like this that view freezes:
```
 <Frame>
            <Entry Text="12345678910" />
 </Frame>
```
If you set XAML design like this that view behaves normally:
```
 <Frame>
            <Entry Text="12345" />
 </Frame>
```

CC/ @filipDN
