### ISSUE TITLE
Shell crashes upon adding/removing items

### ISSUE THREAD

**Issue by rxDietel** [dotnet/maui#9938]
### Description

Upon adding or removing FlyoutItems during runtime, the Shell occasionally crashes with nullReferenceExceptions

#### 1. Add Items:
- Start App
- click on `disable add workaround`
- click on `add Shell Item`
- click on `add Shell Item`
=> App will crash

#### 2. Remove Items:
- Start App
- click on `disable remove workaround`
- click on `add Shell Item`
- click on `add Shell Item`
- click on `add Shell Item`
- click on `remove Shell Item`
- click on `remove Shell Item`
- click on `remove Shell Item`
=> App will crash

### Link to public reproduction project repository

https://github.com/rxDietel/MauiAppShellTest

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, iOS, I was *not* able test on other platforms

### Affected platform versions

net6.0-windows10.0.19041.0
iOS 15.6.1

### Did you find any workaround?

See Bug number 4 in ReadMe.md of reproduction project

**Comment by rxDietel** [comment]
Just tested this on iOS
removing the add workaround will crash the app
removing the remove workaround won't crash the app

**Comment by rxDietel** [comment]
@PureWeen : I might have found the root for the null reference exception!
in https://github.com/dotnet/maui/blob/net6.0/src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs#L26
_shell might be null when called from https://github.com/dotnet/maui/blob/net6.0/src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs#L93 this causes the nullReferenceExceptions for me at least in a few cases.
Right now this is an absolute show stopper for our apps migration to Maui.

**Comment by hugebug4ever** [comment]
Dynamically setting the shell item's IsVisible and FlyoutItemIsVisible properties also do not works on pc, while works on Android.

**Comment by rxDietel** [comment]
@jsuarezruiz @PureWeen 

When are you planing to fix this issue?
The issue has changed to resemble something more like the below linked issue.
But essentially all bugs are still present.
Bugs 1, 2 and 4 still persist. The workaround for Bug 4 does no longer work.
And Bug 3 has changed. Every time the items collection changes, all current items will be appended to the current menu in the correct order. This iss probably also whats happening in the issue linked below.

Hoping for some work on this soon. Its blocking us from using Maui and we're locked to xamarin for our App. Our customer want's a cross platform app, but right now his highest priority is windows.

https://github.com/dotnet/maui/issues/12159

**Comment by codemonkey85** [comment]
I'm running into a very similar issue in my repo. For now I've added a workaround that *sort of* fixes it (at least prevents the crash): https://github.com/codemonkey85/DotNet-Maui-Mobile-App-Development-Course/commit/2ba14df44a3ab0777b8d1b111686a129f92da984

**Comment by Foda** [comment]
@jsuarezruiz @PureWeen 👋 I'm currently investigating this --

Outside of fixing the base null ref issues, there's another issue that arises. Basically, if you have an item that's set to `FlyoutDisplayOptions.AsMultipleItems` and the child is selected and then removed, the "hidden" parent item becomes the current item (it was actually already the current item, but nevermind that). This results in the main view not updating, and the shell nav view shows no items selected:

![image](https://github.com/dotnet/maui/assets/890772/c0644229-81a7-4945-acc9-bfa9602eb6fb)

There's a few ways to solve this. We could do a check on `Shell.CurrentItem` for this case specifically:
```
if (CurrentItem != null &&
    CurrentItem.FlyoutDisplayOptions == FlyoutDisplayOptions.AsMultipleItems && 
    CurrentItem.Items.Count == 0 &&
    CurrentItem != Items[0])
{
    CurrentItem = Items[0];
}
```

An alternative would be to not allow shell items with `FlyoutDisplayOptions.AsMultipleItems` to be set as the `CurrentItem`. It's a lot more work, and I'm not sure what the context was behind the current enum implementation. However, right now we're in-between a tree-view and flat-list and I suspect we'll see more issues regarding this.

**Comment by Foda** [comment]
Thinking about this a bit more -- I'm just going to fix the null refs for now :)
