### ISSUE TITLE
Shell in WinUI layout bugged

### ISSUE THREAD

**Issue by Rabosa616** [dotnet/maui#9941]
### Description

I´ve figure out that when building a Localized application most of samples shows that needs to instantiate again the appshell page by:
```chsarp
App.Current.MainPage = new AppShell();
``` 
By doing so the Shell layout in Windows moves up and overly the windows app toolbar.
![image](https://user-images.githubusercontent.com/12774781/188614351-7d18f930-c0bb-4ddd-a588-de099512c4d3.png)

### Steps to Reproduce

I´ve created a repo to reproduce the error

1. Clone the repo https://github.com/rabosa616/MauiMultilanguageApp/
2. Build it with Visual Studio in windows
3. Press F5 to run the app
4. This is the current layout:
![image](https://user-images.githubusercontent.com/12774781/188614945-cbdd9b46-a0b7-4c68-b11d-4e0bfd7eb736.png)
5. Click the button 'ChangeLanguage'
6. The layout now:
![image](https://user-images.githubusercontent.com/12774781/188614351-7d18f930-c0bb-4ddd-a588-de099512c4d3.png)

### Link to public reproduction project repository

https://github.com/rabosa616/MauiMultilanguageApp/

### Version with bug

6.0.303
6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

**Comment by mattleibow** [comment]
Might be related to #8718

**Comment by mattleibow** [comment]
@PureWeen I think you have a fix for this?

**Comment by mattleibow** [comment]
I think this is the PR that fixes the swapping of the main page: https://github.com/dotnet/maui/pull/9955

**Comment by DelphinRP** [comment]
We're running into same same issue with the exact same use case.

**Comment by Rabosa616** [comment]
@mattleibow I'm checking the PR you mention an @PureWeen only did changes for Android and this issue here is for windows platform. I did not experienced that behavior on Android or iOS

**Comment by PureWeen** [comment]
This should get resolved by https://github.com/dotnet/maui/pull/9955
