### ISSUE TITLE
FilePicker: Not possible to pick a file on an iPad-Pro Simulator with iOS 15.5 

### ISSUE THREAD

**Issue by FischertBilligheim** [dotnet/maui#9953]
### Description

It's not possible to pick any file with the Maui-FilePicker - on an iPad-Pro Simulator with iOS 15.5.
All the existing files are greyed out. (Same topic existed in Xamarin also)

The same code works on a real device.

Best regards
Thomas

### Steps to Reproduce

Use "FilePicker.PickAsync()" with or without PickOptions.

### Link to public reproduction project repository

no specific project needed.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

**Comment by mattleibow** [comment]
Is the device a iPad or iPhone.

**Comment by FischertBilligheim** [comment]
The device is an iPad-Pro.

**Comment by jfversluis** [comment]
Seeing the same report with our friends over at React Native: https://github.com/rnmods/react-native-document-picker/issues/532 which seems to be an iOS 15 Simulator issue.

Can you confirm that it works on a physical device and/or other Simulator iOS versions?
