### ISSUE TITLE
Entry ClearButton does not clear the text? 

### ISSUE THREAD

**Issue by FreakyAli** [dotnet/maui#9954]
### Description

So earlier today I was trying to use the internal property for an Entry to clear the text in it.

```
 <Entry
   Placeholder="This is a freaky entry"
   TextColor="Purple"
   ClearButtonVisibility="WhileEditing"
   FontSize="Large"
   Keyboard="Chat"/>
```

But when I click on it nothing seems to happen.

Am I missing something here?

Is this the intended behaviour?

If so how do I add the clear button functionality, I don't seem to find a command or a event for it...

### Steps to Reproduce

- Add an Entry to your XAML
- Add the following property  `ClearButtonVisibility="WhileEditing"`

Expected output: A clear button shows up while editing the Entry and on Click of the Clear button the text clears.
Actual output: the text does not clear on the click of clear button.

### Link to public reproduction project repository

https://github.com/FreakyAli/MAUI.FreakyControls

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Latest of both 

### Did you find any workaround?

No

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with the latest version (net7 rc2) or the current main branch. Could you try again with the latest version?
![issue-9954](https://user-images.githubusercontent.com/6755973/197717942-489ec794-a253-4529-8658-1a68ae17496a.gif)

**Comment by mjphillips1981** [comment]
I can confirm this is not working on the latest preview 5 build.

**Comment by mjphillips1981** [comment]
> I can confirm this is not working on the latest preview 5 build.

Nevermind, I created a new project from the MAUI template and it does work on .NET 6.0 and .NET 7.0. 

It does not work in my existing project.  That I thought was using the latest preview version but it must not be.

**Comment by FreakyAli** [comment]
@mjphillips1981 So is this working in the lastest preview and if so how do I confirm if I have the latest preview?

**Comment by mjphillips1981** [comment]
That's a good question. I am trying to figure out how to get it working in my already created project.  
It only works when I create new projects as of right now.

**Comment by FreakyAli** [comment]
I just did this and I can confirm I am facing the same issue, it only works on new projects but fails on existing projects

**Comment by mjphillips1981** [comment]
I just may have pinpointed this issue.
Currently I have a Frame around my entry.  The clear button does not work.
If I remove the frame, the clear button works.
Also, this only seems to be a bug on Android.  When I test on iOS all seem to work.

**Comment by mjphillips1981** [comment]
Nothing to do with frame, seems to be linked to Padding.

I think it has to do with Padding.  My frame has a padding of 20.  If I pressed to the left of the "X" roughly the length of the padding it will clear the text.  If I change my padding to 0 clicking the "X" clears the text.

**Comment by FreakyAli** [comment]
> Nothing to do with frame, seems to be linked to Padding.
> 
> I think it has to do with Padding. My frame has a padding of 20. If I pressed to the left of the "X" roughly the padding length, it will clear the text. If I change my padding to 0 clicking the "X" clears the text.

I guess we do need the padding though right...

**Comment by ismasanchez** [comment]
This is an absolute nightmare, I can't spend 2 hours debugging this bug for such a standard functionality... anyway, here are the steps to reproduce:

Create a brand new MAUI app with this code, clear button doesn't work properly:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiBug.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">

            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />

            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

            <Border Stroke="black"
            StrokeThickness="1"
            BackgroundColor="Transparent">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="10,10,10,10" />
                </Border.StrokeShape>
                <Entry
                        ClearButtonVisibility="WhileEditing"
                        HorizontalOptions="FillAndExpand"/>
            </Border>

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```
Remove Padding in VerticalStackLayout, now it works.

Here's my workload:

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.52/7.0.100         VS 17.4.33205.214
maui-maccatalyst           7.0.52/7.0.100         VS 17.4.33205.214
maccatalyst                16.1.1477/7.0.100      VS 17.4.33205.214
maui-ios                   7.0.52/7.0.100         VS 17.4.33205.214
ios                        16.1.1477/7.0.100      VS 17.4.33205.214
android                    33.0.4/7.0.100         VS 17.4.33205.214
maui-android               7.0.52/7.0.100         VS 17.4.33205.214
