### ISSUE TITLE
[Blazor .NET MUAI] Not all CSS cursor properties are functional

### ISSUE THREAD

**Issue by Brosinski** [dotnet/maui#9960]
### Description

Assigning certain cursor properties results in no changes being made to the cursor for the styled element.

The following I tried to use that don't work are:

cursor : col-resize
cursor : move
cursor : cell
cursor : alias

### Steps to Reproduce

Create a new Blazor Maui project with Visual Studio 2022

Try style any element with the _cursor_  property set to _cell_ or _col-resize_

Hover your mouse over the property

### Link to public reproduction project repository

https://github.com/Brosinski/BrokenCursorBlazor

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows	10.0.19044 

### Did you find any workaround?

Using the cursors  that work

**Comment by javiercn** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/43758

As mentioned in the other issue, this is not something Blazor controls or configures in any way. Support for this feature is up to the underlying webview2 control.

**Comment by Brosinski** [comment]
@javiercn Thank you for the further elaboration.  When loading a webview with XAML I was able to replicate the bug without blazor.

 I will take the issue to https://github.com/MicrosoftEdge/WebView2Feedback.

Please note that _BlazorWebView_ does exist, so the clarification on what exact web view controller you were referring to originally was enlightening. 

Thank you for your time
