### ISSUE TITLE
SetEnvironmentVariable for GOOGLE_APPLICATION_CREDENTIALS works on windows but give error on android

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [dotnet/maui#9963]
### Description

I Use Google.Cloud.Firestore Nuget package to connect to firestore from .net Maui App

It works fine for Windows, but gives an error on android and ios.

Is there any better way to connect my .net Maui app to firestore?

### Steps to Reproduce

Here is my code:
```C#
var path = AppDomain.CurrentDomain.BaseDirectory + @"credentials.json";

            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", path);

            db = FirestoreDb.Create("projectID");
```

### Link to public reproduction project repository

/

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15 and Android 11

### Did you find any workaround?

https://stackoverflow.com/questions/71877262/how-do-i-connect-my-maui-app-to-a-firestore-database-via-service-account-json

### Relevant log output

```shell
System.InvalidOperationException: 'Error reading credential file from location /data/user/0/com.agxium.agxium_manager/filescredentials.json: Could not find file '/data/user/0/com.agxium.agxium_manager/filescredentials.json'.
Please check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS'
```

**Comment by mattleibow** [comment]
I think this is because `AppDomain.CurrentDomain.BaseDirectory` on Android represents a file inside a zip stream. The best way to do this in a cross-platform manner is to use the Essentials `FileSystem` API and always copy the settings to a local temp file:

1. Add the json file to the .csproj using the `MauiAsset` build action
2. Read the file at runtime and store in a temp folder:
   ```cs
   var localPath = Path.Combine(FileSystem.CacheDirectory, "credentials.json");
   
   using var json = await FileSystem.OpenAppPackageFileAsync("credentials.json");
   using var dest = File.Create(localPath);
       await json.CopyToAsync(dest);
   
   Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", localPath);
   ```
3. Now use the API:
   ```cs
   db = FirestoreDb.Create("projectID");
   ```

**Comment by MahmoudAlEssawi** [comment]
Thank you very much @mattleibow for your help.

I followed your steps, but I get the error below on both windows and android:

System.InvalidOperationException
  HResult=0x80131509
  Message=Error reading credential file from location C:\Users\maale\AppData\Local\Packages\CA73DA79-3516-41E4-A816-45BCF18EDBDE_9zz4h110yvjzm\LocalCache\credentials.json: The process cannot access the file 'C:\Users\maale\AppData\Local\Packages\CA73DA79-3516-41E4-A816-45BCF18EDBDE_9zz4h110yvjzm\LocalCache\credentials.json' because it is being used by another process.
Please check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS
  Source=Google.Apis.Auth
  StackTrace:
   at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.<CreateDefaultCredentialAsync>d__11.MoveNext()
   at Google.Api.Gax.Grpc.DefaultChannelCredentialsCache.<<-ctor>b__5_1>d.MoveNext()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.Firestore.V1.FirestoreClientBuilder.BuildImpl()
   at Google.Cloud.Firestore.FirestoreDbBuilder.Build()
   at AGXIUM_MANAGER.Authentication.SignUpViewModel.<FirestoreConnectionAsync>d__23.MoveNext() in E:\AGXIUM Projects\AGXIUM MANAGER\Authentication\SignUpViewModel.cs:line 90

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IOException: The process cannot access the file 'C:\Users\maale\AppData\Local\Packages\CA73DA79-3516-41E4-A816-45BCF18EDBDE_9zz4h110yvjzm\LocalCache\credentials.json' because it is being used by another process.

**Comment by MahmoudAlEssawi** [comment]
Solved

I add this code 

            dest.Close();
after this code
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", localPath);

thanks again @mattleibow
