### ISSUE TITLE
Image wrong rotation with a ContentView and BindableProperty

### ISSUE THREAD

**Issue by AlanGusLive** [dotnet/maui#9969]
### Description

1) When an image is displayed with a .NET MAUI view Image the rotation is ok
```
<Image
 Source="dotnet_bot.png"
 HeightRequest="100"
 Rotation="90"                
 HorizontalOptions="Center" />
```
2) When an image is displayed with a  ContentView and BindableProperty the rotation is wrong
```
<im:ImageMaui
 x:Name="ImageBot"
 Source="dotnet_bot.png"
 RotationMaui="90"
 HeightRequest="100"
 HorizontalOptions="Center" />
```

![image](https://user-images.githubusercontent.com/15076413/188887968-bd9eb058-d8c4-4079-89df-d2cb7f8b87ae.png)

### Steps to Reproduce

1) Create a MAUI Application
2) Add a ContentView with an image in a grid
3) Add a BindableProperty called "Source" to load the file. The goal is to avoid to load each time the image from the file but to load it from a cache in memory.
4) Add a BindableProperty called "RotationMaui" to change the rotation

### Link to public reproduction project repository

https://github.com/AlanGusLive/BindableProperty

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows SDK 10.0.19041.0

### Did you find any workaround?

None

**Comment by SagarPanwala** [comment]
This seems bug in your code and not in the MAUI.
I've updated your code of ImageMaui.cs little bit.

You can find the code on this link.
https://dotnetfiddle.net/6a81QY

**Comment by AlanGusLive** [comment]
@SagarPanwala Thank you for the fix. I tested and now it works. I improved the code to change the type of the rotation from int to double.

The updated code is available on this repository:
[BindablePropertyV2](https://github.com/AlanGusLive/BindablePropertyV2)

@SagarPanwala Well done :smiley:
