### ISSUE TITLE
[MAC] Horizontal Options of child inside absolute layout is not working with "RightToLeft' flow direction

### ISSUE THREAD

**Issue by Deepak1799** [dotnet/maui#9970]
### Description

When applying the RightToLeft flow direction to Absolute layout, the contents are not aligned properly to the HorizontalOptions provided.

I have applied flow direction to Absolute layout as "RightToLeft" and Horizontal option to its child (Grid) as "Start" 

**Expected result:**
In RightToLeft flow direction, the content **should be aligned** to the "Right" side, if its HorizontalOptions is "Start".

**Current result:**
In RightToLeft flow direction, the content is aligned to the "Left" side, if its HorizontalOptions is "Start".

**_Note: The expected behaviour works fine in Android and Windows. The issue is only in MAC_**

### Steps to Reproduce

1. Create an Absolute layout and set its flow direction property as "RightToLeft".
2. Add a child (Grid)  to the Absolute Layout with HorizontalOptions "Start". 
3. Run the sample and you will find the content is aligned to left side instead of right side.

(Or)
Run the attached sample project and you will find the content is aligned to left side instead of right side.

### Link to public reproduction project repository

https://github.com/Deepak1799/NET-MAUI-Samples/tree/master/AbsoluteLayoutRTL

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

MacOS v12,1

### Did you find any workaround?

I need to force set the Layout bounds manually to the Content identifying the Flow Direction in MAC.

### Relevant log output

```shell
NA
```

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on iOS and macOS platform with sample project. [MauiAppScrollviewBorderBug1.zip](https://github.com/dotnet/maui/files/9459050/MauiAppScrollviewBorderBug1.zip)
