### ISSUE TITLE
Connectivity implementation not thread-safe on Windows, returning incorrect network status

### ISSUE THREAD

**Issue by breenbob** [dotnet/maui#9972]
### Description

On the WinUI platform, any calls to Connectivity.Current only work from the first thread to access the property. Subsequent calls from any other thread will cause a silent thread access exception:
![image](https://user-images.githubusercontent.com/6000851/188937048-03e10458-1176-4f4f-9ece-54077e616743.png)

That will end in a value of Unknown being returned:
![image](https://user-images.githubusercontent.com/6000851/188937277-c26dfd2b-fe02-4435-853b-bd0bc0798c43.png)

Doesn't matter which thread is first - main thread or background thread, it will always return correct value, and continue to return the correct value _for that thread_. But if you try to access it from a _different_ thread, that is when this issue occurs.

### Steps to Reproduce

I've linked to a sample repro below. Just run and click button 1 then button 2, or button 2 then button 1 to invert the outcome.

Main thread before bg thread:
![xJ9MaGocEK](https://user-images.githubusercontent.com/6000851/188937925-0000c476-eedd-4471-91c2-3ddc6d63c762.gif)

Bg thread before main thread:
![TSWdWFLxeB](https://user-images.githubusercontent.com/6000851/188937892-54d808b5-96e4-4d18-a904-42f54ecfc424.gif)

### Link to public reproduction project repository

https://github.com/breenbob/MauiWindowsConnectivityIssue

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.17763.0

### Did you find any workaround?

If checks are always done on the same thread you won't see the issue, but that's not a feasible long term solution.

**Comment by breenbob** [comment]
Not quite a duplicate but probably closely related to [#7393](https://github.com/dotnet/maui/issues/7393)

**Comment by MagicAndre1981** [comment]
using `Device.BeginInvokeMainThread()` should always work

**Comment by breenbob** [comment]
@MagicAndre1981 yes as I said in the workarounds if you consistently access from same thread it's not an issue, but it is not always possible/practical to do that, and it is thread safe on the other platforms. Also, in .Net Maui you need to use `MainThread.BeginInvokeOnMainThread()`, `Dispatcher.Dispatch()` or `App.Current.Dispatcher.Dispatch()` to access the UI thread (depending on your scenario, e.g. multi-window where each window has it's own UI thread) as `Device.BeginInvokeOnMainThread()` is obsolete.

**Comment by BenBtg** [comment]
I've been working with a customer who is also seeing this issue.

**Comment by janseris** [comment]
FYI that was the point I left Windows MAUI development. After many disappointments, this was the final one, breaking the app

**Comment by MagicAndre1981** [comment]
ok, this will be fixed with #10062 and the fixed code also calls it on Main Thread

**Comment by breenbob** [comment]
Great stuff, thanks @jsuarezruiz and @BenBtg!

**Comment by breenbob** [comment]
@jsuarezruiz Does this also fix https://github.com/dotnet/maui/issues/7393?

**Comment by janseris** [comment]
Why does Internet check have to run on UI thread anyways?

**Comment by mattleibow** [comment]
I am super not sure about things. I am reverting the main thread "fix" as this is breaking other things: https://github.com/microsoft/WindowsAppSDK/issues/2965#issuecomment-1254680453

But I cannot repro the original issue anymore nor can I repro the issue in this https://github.com/microsoft/WindowsAppSDK/issues/2965#issuecomment-1279475882

I think this may have been a windows app sdk issue and they fixed it - or maybe even an OS issue. I had an issue with XXH1 and it was fixed in XXH2. (can't recall offhand anymore, but yeah... OS was dodgy)
