### ISSUE TITLE
Simplify and make more robust the process for Single-instance WinUI apps

### ISSUE THREAD

**Issue by breenbob** [dotnet/maui#9973]
### Description

We are in the process of migrating one of our apps to .Net Maui. As part of the process we realised that default behaviour of WinUI in .Net Maui is to allow multiple instances of your app to run. This gives us a lot of problems for various reasons that I won't go into in detail, but it covers areas like deep linking, storage, and security. Suffice to say we need to force single instance behaviour. 

Only documentation we could find on how to do this, is [this blog post](https://blogs.windows.com/windowsdeveloper/2022/01/28/making-the-app-single-instanced-part-3/).

This approach does work, but seems like a very drawn out and 'hacky' way to have to control such a common and fundamental behaviour. For anyone interested, we did notice an issue whereby forcing single instance in this manner seems to completely break any instances of the WebView2 control, perhaps as it runs out of process... will be logging a separate issue for that against WinUI repo.

I would propose something built into .Net Maui/WinUI/Visual Studio to enable turning this on/off at csproj level.

### Public API Changes

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
                ...
		<WinUISingleInstance>true</WinUISingleInstance>
	</PropertyGroup>
</Project>
```
### Intended Use-Case

There are many legitimate reasons why single instance behaviour is desirable, such as access to shared resources such as a SQLite database, or deep linking that must be able to use context of current logged-in user. This proposal is just to make it _easier_ to do that.

### Depends on

- [ ] https://github.com/microsoft/WindowsAppSDK/issues/1709
- [x] https://github.com/microsoft/WindowsAppSDK/issues/2121
> VS bug [#1846133](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1846133)

**Comment by BenBtg** [comment]
I've been working with a customer who is also seeing this issue.

**Comment by breenbob** [comment]
Relevant issue worth tracking on this subject:
https://github.com/microsoft/WindowsAppSDK/issues/1709
and a closed linked issue (including as one comment links to a gist for a custom workaround):
https://github.com/microsoft/WindowsAppSDK/issues/2121

**Comment by bobwhitten** [comment]
This would definitely help me.

**Comment by mdbill** [comment]
This feature is also critical for upgrading my XF apps to Maui.

**Comment by breenbob** [comment]
In case anyone else is having same issue, I've worked out the reason any WebView2 controls failed to load when forcing single instance behaviour was down to the fact that the blog post I've referenced has an async main method and makes some async method calls in the main method. This means the async calls being made aren't properly awaited, and this causes WebView2 registration/instantiation to fail. Changing the return type to int instead of Task<int> and changing the code to force synchronous behaviour fixed the issue for me, with no obvious side effects, i.e. deep linking still works to my single instance. I.e.

```csharp
    [STAThread]
    static int Main(string[] args)
    {
         WinRT.ComWrappersSupport.InitializeComWrappers();
         bool isRedirect = DecideRedirection().Result;
         if (!isRedirect)
         {
             Microsoft.UI.Xaml.Application.Start((p) =>
             {
                 var context = new DispatcherQueueSynchronizationContext(
                     DispatcherQueue.GetForCurrentThread());
                 SynchronizationContext.SetSynchronizationContext(context);

                 new App();
             });
         }

        return 0;
    }
```

**Comment by sathyajithps** [comment]
This is how I got single instancing working on Maui (Windows Platform). `dotnet workload list` for my project.

![image](https://user-images.githubusercontent.com/21971192/225839145-2829134a-a227-49b1-8609-f992039b64d0.png)

In the <maui project>.csproj, copy paste the below snippet.

```
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    </PropertyGroup>
```

In Platforms/Windows, create a `Program.cs` file. and copy paste the below code into it.

```
using Windows.ApplicationModel.Activation;
using Microsoft.UI.Dispatching;
using Microsoft.Windows.AppLifecycle;


namespace <YourApp>.WinUI;

public class Program
{
    private static App app;

    [STAThread]
    static async Task<int> Main(string[] args)
    {
        WinRT.ComWrappersSupport.InitializeComWrappers();
        var isRedirect = await DecideRedirection();
        if (!isRedirect)
        {
            Microsoft.UI.Xaml.Application.Start((p) =>
            {
                var context = new DispatcherQueueSynchronizationContext(
                    DispatcherQueue.GetForCurrentThread());
                SynchronizationContext.SetSynchronizationContext(context);
                app = new App();
            });
        }

        return 0;
    }

    private static async Task<bool> DecideRedirection()
    {
        var isRedirect = false;
        var args = AppInstance.GetCurrent().GetActivatedEventArgs();
        var keyInstance = AppInstance.FindOrRegisterForKey("idk_what_this_is_any_string_works");

        if (keyInstance.IsCurrent)
        {
            keyInstance.Activated += OnActivated;
        }
        else
        {
            isRedirect = true;
            await keyInstance.RedirectActivationToAsync(args);
        }

        return isRedirect;
    }

    private static void OnActivated(object sender, AppActivationArguments args)
    {
        if (app is null)
        {
            throw new Exception("app should not be null");
        }
     // You can check if args.Data is ProtocolActivatedEventArgs if you are expecting a uri invocation
    }
}
```

**Comment by OnepunchmanSven** [comment]
@sathyajithps your workaround works for me.

I'm expecting a uri invocation in the OnActivated event because the login feature is hosted in the websites, I can get the protocol uri back from the args, but in this case there're two issues:
1. The uri didn't open the existing app instance, I mean make it visible
2. How can I redirect to the HomePage after login successfully?

Thanks in advance.

**Comment by mattleibow** [comment]
I created a simple sample on making your WinUI app be a single instance without the complex MSBuild and implementations: https://github.com/mattleibow/MauiSingleInstanceApp

**Comment by mattleibow** [comment]
I actually think we can close this since .NET MAUI will have to somehow try make single instancing work with all the platforms. 

This is already pretty easy in WinUI (including .NET MAUI for Windows). Similarly, I think Android just needs some Activity flags. Not sure about Mac Catalyst.

The main code is in the WinUI App.xaml.cs file:
```cs
public App()
{
    var singleInstance = AppInstance.FindOrRegisterForKey("SingleInstanceApp");
    if (!singleInstance.IsCurrent)
    {
        // this is another instance

        // 1. activate the first instance
        var currentInstance = AppInstance.GetCurrent();
        var args = currentInstance.GetActivatedEventArgs();
        singleInstance.RedirectActivationToAsync(args).GetAwaiter().GetResult();

        // 2. close this instance
        Process.GetCurrentProcess().Kill();
        return;
    }

    // this is the first instance

    // 1. register for future activation
    singleInstance.Activated += OnAppInstanceActivated;

    // 2. continue with normal startup
    this.InitializeComponent();
}

private void OnAppInstanceActivated(object? sender, AppActivationArguments e)
{
    // handle the old app being loaded
}
```

**Comment by mattleibow** [comment]
Windows also has a fairly in-depth doc on things that can be done for different scenarios: https://learn.microsoft.com/windows/apps/windows-app-sdk/applifecycle/applifecycle-instancing

Using that as a guide may help.

**Comment by breenbob** [comment]
Thanks @mattleibow for taking the time to look at this, and for wibbling up a sample. Will give this a go in my WinUI app and see how it goes.

Can I ask, when you said:

> I actually think we can close this since .NET MAUI will have to somehow try make single instancing work with all the platforms.

Did you mean it would need to force single instance behaviour on all of the platforms by default? Curious what the rationale is for that?

**Comment by mattleibow** [comment]
I meant that if we are to create some "single instance" API for _just_ windows it would be confusing since it only worked there. And then we already have a Windows-only API, so it would be a bit redundant.

But, maybe there is some value. However, the Windows API is fairly powerful and allows for more than just a single instance. So we may reduce functionality.

But then again, this looks cool and easy:

```cs
builder.UseMauiApp<App>()
       .ConfigureSingleInstanceApp()
```

Or even, 
```cs
builder.UseMauiApp<App>()
       .ConfigureSingleInstanceApp(args => {
         // do something with a new instance request
       })
```

**Comment by captain01010101** [comment]
> I actually think we can close this since .NET MAUI will have to somehow try make single instancing work with all the platforms.
> 
> This is already pretty easy in WinUI (including .NET MAUI for Windows). Similarly, I think Android just needs some Activity flags. Not sure about Mac Catalyst.
> 
> The main code is in the WinUI App.xaml.cs file:
> 
> ```cs
> public App()
> {
>     var singleInstance = AppInstance.FindOrRegisterForKey("SingleInstanceApp");
>     if (!singleInstance.IsCurrent)
>     {
>         // this is another instance
> 
>         // 1. activate the first instance
>         var currentInstance = AppInstance.GetCurrent();
>         var args = currentInstance.GetActivatedEventArgs();
>         singleInstance.RedirectActivationToAsync(args).GetAwaiter().GetResult();
> 
>         // 2. close this instance
>         Process.GetCurrentProcess().Kill();
>         return;
>     }
> 
>     // this is the first instance
> 
>     // 1. register for future activation
>     singleInstance.Activated += OnAppInstanceActivated;
> 
>     // 2. continue with normal startup
>     this.InitializeComponent();
> }
> 
> private void OnAppInstanceActivated(object? sender, AppActivationArguments e)
> {
>     // handle the old app being loaded
> }
> ```

Any way to test this while running in the debugger?

**Comment by PavlikBender** [comment]
Previous answer worked for me.
I'm just added little tweak for that code.
To restore old app window I wrote this 
```csharp
private const int SW_SHOWNORMAL = 1;

[DllImport("User32.dll")]
private static extern bool SetForegroundWindow(IntPtr hWnd);

[DllImport("user32.dll")]
private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

private void OnAppInstanceActivated(object? sender, AppActivationArguments e)
{
    // handle the old app being loaded
    var windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(m_window);
    // restores the window in case it was minimized.
    ShowWindow(windowHandle, SW_SHOWNORMAL);
    // brings the window to the foreground.
    SetForegroundWindow(windowHandle);
}
```
And I had issue with AppInstance class, VS define that class from wrong library. Full name of that class is Microsoft.Windows.AppLifecycle.AppInstance.

**Comment by DennisWelu** [comment]
@PavlikBender Good addition, thanks. How are you getting the "m_window" handle?

**Comment by DennisWelu** [comment]
I was able to use the WinUIEx library (https://dotmorten.github.io/WinUIEx/concepts/index.html) to simplify further:

```
	/// <summary>
	/// Shows and brings the main window to the foreground when a secondary instance is activated.
	/// </summary>
	static void OnAppInstanceActivated(object? sender, AppActivationArguments e)
	{
		var window = (Microsoft.UI.Xaml.Window)Microsoft.Maui.Controls.Application.Current!.MainPage!.Window!.Handler!.PlatformView!;
		window.Show();
		window.SetForegroundWindow();
	}
```
That line getting the window is pretty ugly but everything else looks nice. :-)

**Comment by PavlikBender** [comment]
> @PavlikBender Good addition, thanks. How are you getting the "m_window" handle?

Standart template of WinUI 3 app has OnLaunched event (maybe in maui app this event missing, idk)
in App.xaml.cs:
```csharp
    private Window m_window;
    
    /// <summary>
    /// Invoked when the application is launched.
    /// </summary>
    /// <param name="args">Details about the launch request and process.</param>
    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        m_window = new MainWindow();
        m_window.Activate();
    }
```

**Comment by urielginsburg** [comment]
@mattleibow 

> I actually think we can close this since .NET MAUI will have to somehow try make single instancing work with all the platforms.
> 
> This is already pretty easy in WinUI (including .NET MAUI for Windows). Similarly, I think Android just needs some Activity flags. Not sure about Mac Catalyst.
> 
> The main code is in the WinUI App.xaml.cs file:
> 
> ```cs
> public App()
> {
>     var singleInstance = AppInstance.FindOrRegisterForKey("SingleInstanceApp");
>     if (!singleInstance.IsCurrent)
>     {
>         // this is another instance
> 
>         // 1. activate the first instance
>         var currentInstance = AppInstance.GetCurrent();
>         var args = currentInstance.GetActivatedEventArgs();
>         singleInstance.RedirectActivationToAsync(args).GetAwaiter().GetResult();
> 
>         // 2. close this instance
>         Process.GetCurrentProcess().Kill();
>         return;
>     }
> 
>     // this is the first instance
> 
>     // 1. register for future activation
>     singleInstance.Activated += OnAppInstanceActivated;
> 
>     // 2. continue with normal startup
>     this.InitializeComponent();
> }
> 
> private void OnAppInstanceActivated(object? sender, AppActivationArguments e)
> {
>     // handle the old app being loaded
> }
> ```

this works well and thank you for sharing this. however, if the app is not running, launching the main instance with a URI activation, for example, the `AppInstance.Activated` event is *not* raised for this first-time launch. I ended up calling my OnActivated method manually in the main AppInstance i.e.,
```
var singleInstance = AppInstance.FindOrRegisterForKey("SingleInstanceApp");
if (singleInstance.IsCurrent)
{
  var args = singleInstance.GetActivatedEventArgs();
  var type = args.Data.GetType();
  OnInstanceActivated(this, args);
  singleInstance.Activated += OnInstanceActivated;
  InitializeComponent();
}
```

Does this seem right to you?

Thanks!
Uriel

**Comment by mattleibow** [comment]
Goung to close this for now since this is a windows only feature and there is already a windows only api. The code is all in windows only files so there is no need for anything really.

If someone feels this is a feature that is really needed and they know of a way to make this actually work with other platforms then feel free to open a new discussion with your ideas and maybe some code.
