### ISSUE TITLE
Errors in try/catch kill the application when there is no internet

### ISSUE THREAD

**Issue by LackyCraft** [dotnet/maui#9977]
### Description

My MAUI.Android app has an error in the try/catch block. When android hits an exception, it dies.

### Steps to Reproduce

1. Run the project
2. Start debugging under Android
3. Turn off the Internet and press Button

Actual vision:
Application error and crash.

Expected behavior:
Processing the catch block

### Link to public reproduction project repository

https://github.com/LackyCraft/bag-report

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, Win11, VS2022

**Comment by jfversluis** [comment]
We can't accept zip files as reproductions, please add it on a public repository for us to look at. Thanks!

**Comment by janseris** [comment]
@jfversluis you can't open zip files? You guys are hilarious

**Comment by jfversluis** [comment]
@janseris https://github.com/dotnet/maui/blob/main/.github/repro.md#why-cant-you-just-download-my-zip-file-reproduction

**Comment by janseris** [comment]
The requested info was added by editing the post
