### ISSUE TITLE
Blazor HTML Code Event not working on .Net Maui Blazor App

### ISSUE THREAD

**Issue by nextcodelab** [dotnet/maui#9987]
### Description

All my @onclick event in html not firing on android side.. .razor 
```html
<div style="margin-left:8px; margin-top:6px; margin-bottom:6px;" @onclick="@(()=> TapSelectBook(item))">
                                <span style="font-size:larger;">@item.human</span>
                            </div>
```
```c#
The @onclick="@(()=> TapSelectBook(item))"
```
Not Fired.. only on android.. but it is ok on windows.

```c#
void TapSelectBook(books book)
    {
        string b_name = App.IsMobileWidth ? book.osis : book.human;
        HomePage.Current.SetHeader(b_name, null);
        Preferences.Set(nameof(App.CurrentApp.bibleManager.Book), book.osis);
        TabSelection(2);
        App.CurrentApp.searchFinder.GetBook(book.osis);
        App.CurrentApp.bibleManager.SetBook(book);
    }
```

### Steps to Reproduce

No

### Link to public reproduction project repository

No

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

Also, can you confirm if the `onclick` handler doesn't work specifically for html elements (not components)?

**Comment by dsuny** [comment]
Android Webview version check.

**Comment by nextcodelab** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
> 
> Also, can you confirm if the `onclick` handler doesn't work specifically for html elements (not components)?

Thaks for reply,,, I moved to .Net Maui Xaml UI.  The razor component is working fine for any handers with small sample,, but when my app become complicated with a lot of codes. All my razor components event handler stop working like @onclick, sometimes working fine in a few clicks and stop firing... I cannot upload sample because it working fine in new project... but when I started to copy all complete codes and libraries the issues starting to occurs,,  my real projects that I cannot upload as sample.
Sometimes to the emulator the clicks is working.. but in Real Device all event do not works...
NOTE ONLY FOR ANDROID. the app is in the PLAYSTORE and I found out the selected items not working so I UNPUBLISHED and moving now to XAML UI even it is not fast in queries.

**Comment by mkArtakMSFT** [comment]
We think this is due to a known issue with the Android WebView which has been fixed already and customers should not face this (assuming they have updated WebView on their Android devices).
If someone faces this issue again please file a new issue and provide details so that we can investigate it further.
